### ISSUE TITLE
[Bug]: Transactions - Cannot send a transaction using a custom localhost network

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25655] opened 2024-07-03 13:54 UTC
### Describe the bug

Whenever I import a custom ganache network and start a transaction, the tx always fails with a fresh account.

### Expected behavior

Tx should succeed

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/f70226e7-487e-4d73-95ae-2eb878a57ed0

### Steps to reproduce

1. Start ganache locally
2. Import the network
3. Import and account with funds
4. Send a tx
5. See how tx always fails

### Version

11.16.x prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by MinHtet-O** [comment] 2024-07-08 01:44
It's happening the same for me. Not only can I not send transactions, but I also cannot execute smart contract transactions. In Ganache, `eth_sendRawTransaction` is logged, but after that, the transaction never gets executed and does not form a new block.

Dup: https://github.com/MetaMask/metamask-extension/issues/25693

**Comment by gauthierpetetin** [comment] 2024-07-11 14:15
Duplicate issue with interesting context: https://github.com/MetaMask/metamask-extension/issues/25693

**Comment by MinHtet-O** [comment] 2024-07-25 03:22
Hello, I was wondering if there have been any updates on this issue

**Comment by gauthierpetetin** [comment] 2024-07-25 08:57
cc @MetaMask/confirmations , in case there is any update to share

**Comment by shoenseiwaso** [comment] 2024-08-06 06:34
We're seeing this as well

**Comment by dahu33** [comment] 2024-08-06 06:57
cc @gauthierpetetin

The issue is MetaMask is using it's own gas oracle for the network ID `1337` (default for most local networks) instead of relying on the `eth_estimateGas` RPC Method: https://gas.api.cx.metamask.io/networks/1337/suggestedGasFees

The MetaMask gas oracle should probably return the same error for network ID `1337` than it does for other unsupported network IDs such as `1234`: https://gas.api.cx.metamask.io/networks/1234/suggestedGasFees

This is a critical issue has is affects pretty much anyone developing on Ethereum using a local node.... MetaMask team, please wake up!

**Comment by danjm** [comment] 2024-08-06 18:10
Thanks everyone for highlighting this issue and for the shared information. We will be addressing this soon. But we may not get solutions to prod until early next week.

**Comment by Gudahtt** [comment] 2024-08-13 16:58
You can work around this issue by disabling "Basic functionality" in Settings > Security & Privacy.

We are still working on a full resolution, we will post more updates soon.

**Comment by Gudahtt** [comment] 2024-08-14 12:50
We found that this error was caused by an API change, and that change has now been reversed. This should be fixed for all MetaMask versions now.

**Closed by Gudahtt** 2024-08-14 12:50 UTC
Labels: type-bug, Sev1-high, team-api-platform, team-confirmations, regression-prod-11.16.0

**Comment by VladChernenko** [comment] 2024-08-20 20:17
### GM, @Gudahtt and/or @danjm 

Just checked issues #25693 and this one(#25655) in attempts to solve same issue

### Intro

We have a sharded EVM in our [project Klyntar](https://github.com/KLYN74R) and definitely wants Metamask compatibility🦊😃 We've rewritten the whole JSON-RPC(required methods only) from a scratch and add JS version of EVM.

Seems everything good - balances resolved correctly, chainID and other stuff API works great.

But when I try to send transaction, the status is allways `pending`, but in reality it's successful and already executed in VM.

As a proof(and mb it will be helpful) - I'll send the screen

![image](https://github.com/user-attachments/assets/3b4e096c-32a8-4668-8da6-9ffcb3927906)

Here you can see that the `status = 1` and tx body & receipt already in VM and state.

### What is strange here?

The strange here is that mobile Metamask version is fully compatible with our core - again proof please 👇 

![image](https://github.com/user-attachments/assets/a0b223cf-90cf-46ec-831d-7a31e285f8af)

**So, I have issues only with browser extensions**


### Troubleshooting

So, weaponizing the BurpSuite I started to monitor network connections and notify that:

1) Mobile version sends only `obvious` queries like `eth_estimateGas`, `eth_blockNumber`, `eth_sendRawTransaction` and so on
2) Browser extensions sends additional `eth_call` queries to VM via RPC

E.g:

```shell

DEBUG: Accept body =>  {
  id: 190,
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      to: '0x069bdf66961ce2d38ebe48dd2e095f2c8015ac82',
      data: '0x01ffc9a7d9b67a2600000000000000000000000000000000000000000000000000000000'
    },
    '0x319'
  ]
}
DEBUG: Accept body =>  {
  id: 192,
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      to: '0x069bdf66961ce2d38ebe48dd2e095f2c8015ac82',
      data: '0x95d89b41'
    },
    '0x319'
  ]
}
DEBUG: Accept body =>  {
  id: 193,
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      to: '0x069bdf66961ce2d38ebe48dd2e095f2c8015ac82',
      data: '0x313ce567'
    },
    '0x319'
  ]
}

```

My node answer with `0x` for such queries, because it's simple `address => address` tx, not a contract call.

### But, problem 2

When I've tried to test `public` network (Sepolia), Metamask sent only `obvious` queries to Infura URL.

Again, as I proof, I tracked the whole workflow - from building tx to green status of tx finalization:

![image](https://github.com/user-attachments/assets/fb2a304c-02ce-40cc-a42d-5b1be242d3ab)

![image](https://github.com/user-attachments/assets/7468894f-33db-4eae-94d2-0a7a2b829148)

![image](https://github.com/user-attachments/assets/48b97498-a9a1-4ad3-8146-7ba837b060a7)


![image](https://github.com/user-attachments/assets/3750841c-3580-4801-bf6b-f833dcf82f99)

![image](https://github.com/user-attachments/assets/3dc6173e-a492-415c-a073-1497b786f339)


##### Finally, I received the full interaction session with Sepolia URL and there were no `eth_call` messages at all 👀 

![image](https://github.com/user-attachments/assets/8f58069f-c97a-4859-9e2e-5dd0160834f0)

### Metamask version

`v11.16.16` - tested in Firefox / Chrome

### Final

I've expected that the tx workflow should looks smth like this:

1) Build transaction
2) Send it
3) Metamask monitor for tx receipt
4) Once receipt received - check the status and show to user

But, somewhy Metamask gives the permanent `Pending` status for normal tx 👀 

# So, what to do with it? This issue is only for local networks? Or what? Should I downgrade Metamask version? Or wait for fix? Thank you in advance 😊

**Comment by Gudahtt** [comment] 2024-08-20 20:50
Thanks for the report @VladChernenko ! This looks like a distinct problem, could you create a new issue for it? We will investigate it.

**Comment by VladChernenko** [comment] 2024-08-21 06:44
Ok, @Gudahtt
