### ISSUE TITLE
[Bug]: Certain chains icons are not displayed in the Send flow

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24450] opened 2024-05-09 01:59 UTC
### Describe the bug

BNB Chain  and Linea Mainnet icons are not displayed in the Send flow. 

### Expected behavior

 Network icons are properly displayed.

### Screenshots/Recordings

<img width="522" alt="Screenshot 2024-05-08 at 21 50 49" src="https://github.com/MetaMask/metamask-extension/assets/104780023/86111d89-422e-494e-a397-71281dad35a3">

<img width="1136" alt="linea" src="https://github.com/MetaMask/metamask-extension/assets/104780023/e32e7927-b713-43fc-845a-50218d979ee9">

### Steps to reproduce

1. Switch to BNB Chain / Linea Mainnet
2. Start Send transaction
3. Notice that BNB / Linea network icon is not displayed in the Send flow

### Version

latest build

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by BZahory** [comment] 2024-05-10 16:48
Seeing this in develop as well – downgrading from a blocker

**Comment by sleepytanya** [comment] 2024-06-07 04:25
Latest build [Slack discussion link](https://consensys.slack.com/archives/C068SFX90PN/p1717713259996549).
Chrome - Linea mainnet and BNB Chain icons displayed:
<img width="1119" alt="Screenshot 2024-06-07 at 00 25 30" src="https://github.com/MetaMask/metamask-extension/assets/104780023/a11728e1-4d1d-4b56-81df-4dbdf01f4218">

**Comment by BZahory** [comment] 2024-06-07 08:06
Is this within the scope of Swap+Send? It seems like a general/confirmations bug

**Comment by sleepytanya** [comment] 2024-06-10 17:47
Icons for BNB Chain and Linea Mainnet not disaplyed, tested on the latest send+swap build and `develop`:

<img width="366" alt="Screenshot 2024-06-10 at 13 45 32" src="https://github.com/MetaMask/metamask-extension/assets/104780023/3f6119f5-54b3-4801-9a41-23fc0d667c20">

<img width="366" alt="Screenshot 2024-06-10 at 13 45 11" src="https://github.com/MetaMask/metamask-extension/assets/104780023/35daa769-85f2-490c-b326-136fba5557f3">


<img width="360" alt="Screenshot 2024-06-10 at 13 44 25" src="https://github.com/MetaMask/metamask-extension/assets/104780023/a430072b-e37a-4ce9-b661-4d936c6413e5">

**Comment by ejwessel** [comment] 2024-06-25 18:34
Looks like the network icons are still missing, but the tokens are correctly showing or at least displaying an icon other than `?`
<img width="700" alt="Screenshot 2024-06-25 at 11 33 50" src="https://github.com/MetaMask/metamask-extension/assets/3590816/76b9da59-988c-4e06-816d-dccede1cdf15">

**Comment by sleepytanya** [comment] 2024-06-25 20:11
Closed by https://github.com/MetaMask/metamask-extension/pull/25470

**Comment by ejwessel** [comment] 2024-06-25 22:16
Closing in lieu of https://github.com/MetaMask/metamask-extension/issues/25447

**Comment by ejwessel** [comment] 2024-06-26 00:30
https://github.com/MetaMask/metamask-extension/pull/25518

**Comment by sleepytanya** [comment] 2024-07-16 01:57
This bug is present in v12.0.0 beta:

<img width="360" alt="Screenshot 2024-07-15 at 21 53 43" src="https://github.com/user-attachments/assets/c23c85bf-2117-4b51-8ea4-de0a2954ce2c">

<img width="410" alt="Screenshot 2024-07-15 at 21 55 30" src="https://github.com/user-attachments/assets/dbd2d82e-fd15-4eb7-b952-60ef338fc79a">

**Comment by sleepytanya** [comment] 2024-07-17 21:44
@danjm It affects only Confirmation screen.

**Comment by bschorchit** [comment] 2024-07-23 16:54
I think this PR https://github.com/MetaMask/metamask-extension/pull/25518 might fix it, but was not cherry picked to v12.0. That being said, it's not a regression so shouldn't be considered a release blocker.

**Comment by bschorchit** [comment] 2024-07-23 16:58
Reverting labels as discussed in release sync as the original issue was slightly different than the latest and was cherry picked to the release.

**Comment by bschorchit** [comment] 2024-07-23 17:03
Closing as the original issue has been fixed to facilitate v12.0 bug triage. We can open a separate one for the confirmation specific issue.

**Closed by bschorchit** 2024-07-23 17:03 UTC
Labels: type-bug, Sev2-normal, team-bridge, regression-develop, send-swap, regression-beta-12.0.0
