### ISSUE TITLE
Impossible to dismiss notification to backup seed phrase

### ISSUE THREAD

**Issue by AntonioJuliano** [MetaMask/metamask-extension#6980] opened 2019-08-08 23:13 UTC
**Describe the bug**
It is impossible to dismiss the notification to backup your seed phrase. This is a bad experience for those who have already backed up their seed phrase as it constantly covers the bottom of the app.

**To Reproduce**
Have an already initialized wallet, and open the extension

**Expected behavior**
Expect to be able to permanently close or dismiss the notification to backup the seed phrase

**Screenshots**
<img width="365" alt="Screen Shot 2019-08-08 at 3 35 21 PM" src="https://user-images.githubusercontent.com/2073956/62743468-52e04180-b9f7-11e9-84a9-89b3aef69451.png">

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: chrome
 - MetaMask Version 7.0.1

**Comment by danfinlay** [comment] 2019-08-09 15:27
Sorry this was caused by 7.0.0, and is fixed in 7.0.1, but for the few people who opened during the partial rollout of 7.0.0, you will need to verify your seed phrase to dismiss this message. Sorry for the nuissance.

**Comment by AntonioJuliano** [comment] 2019-08-12 22:49
Great, thanks!

**Closed** 2020-01-08 16:55 UTC
Labels: L15-onboarding, T14-seedPhrase
