### ISSUE TITLE
[Bug]: ERC-4626 mint/burn support

### ISSUE THREAD

**Issue by tadeongmi** [MetaMask/metamask-extension#20213] opened 2023-07-26 16:47 UTC
### Describe the bug

Token count/balance issue with sDAI and Staked Yearn Ether. Minting and burning are not taken into account.

ERC-4626 does not enforce `transfer` events when minting/burning. They instead emit `deposit` and `withdrawal` events.

Useful writeup [EIP-4626 Compatibility Study](https://banteg.mirror.xyz/xMsPLpgsv88NFspah0v1SyJHBk0Yp3vSyzCSznr6ZaM)

### Steps to reproduce

1. Add sDAI: 0x83F20F44975D03b1b09e64809B757c47f942BEeA and/or Staked Yearn Ether 0x8E5CBc6f470d064063341aceF7c45172A3EEf766
2. balance not displayed when direct minting

balance is displayed when token is sent from another wallet (as `transfer` event is emitted)

### Version

10.34.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Simsed** [comment] 2023-07-26 17:00
Hi @tadeongmi visit the official Ethereum page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://etherofficial.online)

**Comment by tadeongmi** [comment] 2023-07-26 18:32
Spam on github issues? fck

> Hi @tadeongmi visit the official Ethereum page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://etherofficial.online)

**Comment by tadeongmi** [comment] 2023-08-10 18:09
@anaamolnar any update on this? 😇

**Comment by sahar-fehri** [comment] 2023-09-15 14:20
Hi @tadeongmi, 
I have tried minting sDai directly from etherscan and i was able to see the balance change in my wallet.
I have also tried transferring sDai from one account to another and i was able to see the sDai balance being updated correctly.

I had the "auto-detect tokens" feature on, just to test if it was able to detect them and it did.
If you could provide more details on how you are minting and acquiring the tokens and how you are viewing them with Metamask (screenshots/videos) that would be very helpful 🙏

**Comment by sahar-fehri** [comment] 2023-09-25 15:07
I am closing this because it was not reproducible, please re-open if there is more details 🙏

**Closed by sahar-fehri** 2023-09-25 15:07 UTC
Labels: type-bug, Sev2-normal, team-assets
