### ISSUE TITLE
Any site can receive the address of the user's wallet

### ISSUE THREAD

**Issue by zhek** [MetaMask/metamask-extension#3160] opened 2018-01-31 21:28 UTC
If matamask is unlocked, any site can receive the address of the user's wallet without notification. The user must give explicit permission to receive this information for each site separately (example: Google Chrome notification about access to the location)

**Comment by frankiebee** [comment] 2018-02-01 04:04
closing as a duplicate of #1508 and #714

**Closed by frankiebee** 2018-02-01 04:04 UTC
