### ISSUE TITLE
[Bug]: Closing Metamask login popup does not throw Error 4001 in Chrome, but does in Edge

### ISSUE THREAD

**Issue by Heshbruwn** [MetaMask/metamask-extension#18012] opened 2023-03-07 04:23 UTC
### Describe the bug

I am creating a React button component that will connect the user to MetaMask upon clicking it using `await ethereum.request({ method: 'eth_requestAccounts' })`. Currently facing issues in the event the user clicks the "X" button to close the log in pop up. It works as expected in Edge, but does not in Chrome. I have also attached the relevant ReactJS component code in case it helps: [MetaMaskConnectButton.js.txt](https://github.com/MetaMask/metamask-extension/files/10905287/MetaMaskConnectButton.js.txt)

**Expected Result (seen in Microsoft Edge):**
- Exception throws and the blue "pending" notification in the extension icon goes away when I close the log in pop up
![Expected Result in Edge](https://user-images.githubusercontent.com/25974614/223319044-fe9172bf-9700-47f4-8b8a-7cccd98dd9a4.png)
![Edge- blue notif gone](https://user-images.githubusercontent.com/25974614/223319092-334f9a27-ac9c-43b1-9721-33f5398f778d.png)

**Actual Result (seen in Chrome):**
- No exception throw in console at all (console remains blank)
- When I click the button again, it will throw "RPC Error: Already processing eth_requestAccounts. Please wait."
- Blue "pending" notification in the extension icon also remains
- Refreshing the page does not help, I need to close and reopen the entire browser to reset
![Actual Result in Chrome](https://user-images.githubusercontent.com/25974614/223319255-38be8d3b-38c5-4782-bc93-fd486ce59da6.png)
![Chrome - blue notif remains](https://user-images.githubusercontent.com/25974614/223319416-b47e4584-c47b-4bf8-9f56-5d94c6075679.png)

I have tried:
- Clearing cache, cookies and browser history
- Updating Chrome to the latest version
- Restarting my machine.

### Steps to reproduce

1. Have extension installed in Google Chrome
2. Execute await ethereum.request({ method: 'eth_requestAccounts' }) 
3. MetaMask login will pop up
4. Close the login popup
5. Try to execute await ethereum.request({ method: 'eth_requestAccounts' })  again

### Error messages or log output

```shell
{
  "code": -32002,
  "message": "Already processing eth_requestAccounts. Please wait.",
  "stack": "Error: Already processing eth_requestAccounts. Please wait.\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:13593)\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:16533)\n    at Object.resourceUnavailable (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:17601)\n    at implementation (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:413021)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:402126\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:39039\n    at new Promise (<anonymous>)\n    at a._runMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:38696)\n    at a._runAllMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:38602)\n    at async a._processRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:38383)\n    at async a._handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:38224)"
}
  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:13593)
  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:16533)
  at Object.resourceUnavailable (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:17601)
  at implementation (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:413021)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:402126
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:39039
  at new Promise (<anonymous>)
  at a._runMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:38696)
  at a._runAllMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:38602)
  at async a._processRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:38383)
  at async a._handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:10:38224)
```

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by Heshbruwn** [comment] 2023-03-10 01:51
Anyone else facing this issue? I am still encountering it on my end.

**Comment by OGPoyraz** [comment] 2023-03-15 10:59
Hello @Heshbruwn ,
I have tried the code sample that you sent. Unfortunately, I couldn't reproduce the issue, everything works well on my end on Chrome.
The reason that you see `"code": -32002` is that there is an ongoing confirmation waiting to be either `approved` or `rejected`. And closing the first MM confirmation window should reject that request. Blue notification means it's still open and awaiting an answer. 

To ensure we have the same environment, which exact MetaMask version are you using?

**Comment by Heshbruwn** [comment] 2023-03-17 17:32
hi @OGPoyraz I am on Metamask version 10.25.0. Chrome version 111.0.5563.65 (Official Build) (64-bit). My OS is Windows 10 Enterprise 64-bit.

![image](https://user-images.githubusercontent.com/25974614/225977032-ed6af646-6114-4695-8926-128172ae6f95.png)
![image](https://user-images.githubusercontent.com/25974614/225977172-a17b4e0c-d29f-422a-a678-540369cd21e7.png)

**Comment by OGPoyraz** [comment] 2023-03-20 08:44
I have tried but everything works properly as expected with the same versions on my end. 
@Heshbruwn if a blue notification appears on the extension icon it means there is an ongoing approval process so before sending `eth_requestAccounts` you need to make sure there are no notifications pending.

**Comment by OGPoyraz** [comment] 2023-03-31 07:49
I am closing the issue for now since no other related issue is observed. 
Feel free to reopen if this problem persists on different clients

**Comment by Alekussu** [comment] 2023-04-03 20:57
Facing the exact same issue. This issue was close too fast event with the good description of @Heshbruwn
![image](https://user-images.githubusercontent.com/111154340/229625808-a47f4fae-cb8c-4d24-af79-8a80ab61cbfa.png)

**Comment by OGPoyraz** [comment] 2023-04-04 15:22
Hi @Alekussu, 
Thanks for your report, we are here to help and solve the issue you are facing. 
Do you mind sharing your MetaMask and Brave versions?

**Comment by Alekussu** [comment] 2023-04-04 20:30
Hi @OGPoyraz,

Thanks for reopening this issue. Yes sure my Metamask version is 10.27.0 and the brave version is v1.49.132 chromium 111.0.5563.147

**Comment by vandan** [comment] 2023-10-20 19:59
May need to confirm this issue is still reproducible @tmashuang

**Comment by tmashuang** [comment] 2023-10-24 20:09
This issue is not reproducible with the current version (11.2.0). Closing the eth_account request notification window will result in a user rejection error.

**Closed by tmashuang** 2023-10-24 20:09 UTC
Labels: type-bug, needs-reproduction, Sev3-low, team-devex
