### ISSUE TITLE
[Bug]: Gas simulation error message persists after proceeding

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14448] opened 2022-04-14 20:58 UTC
### Describe the bug

The gas simulation error message is still shown after the user click's the `I want to proceed anyway` button

https://user-images.githubusercontent.com/53189696/163473800-7e0f8260-a5a2-438a-acd9-3023a4b4c8e9.mov

### Steps to reproduce

1. Settings > Experimental > Enable Enhanced Gas Fee UI > ON
2. Connect to [Test Dapp](https://metamask.github.io/test-dapp/)
3. Click `Deploy Failing Contract`, click `Confirm`
4. Click `I want to proceed anyway`

Expected result:
The actionable message is no longer displayed

Actual result:
The actionable message is still shown

### Version

10.13.0

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment] 2022-04-18 20:51
Closing this as leaving the warning message is the intended behavior. [Related Slack thread with designers](https://consensys.slack.com/archives/G4V2HTG0Y/p1650313821776519).
It's also a pattern being currently used in swaps (video below). I created a [papercut ](https://www.notion.so/Review-actionable-warning-messages-design-54330bc5d5bd470cb2ed5fdc9ff71c45)so we review the warning style for these in the future. 

https://user-images.githubusercontent.com/34968356/163875463-28a708e8-a63e-42b5-86db-d6abd1d980b2.mov

**Closed by bschorchit** 2022-04-18 20:51 UTC
Labels: type-enhancement, needs-designs, area-transactions
