### ISSUE TITLE
Can't sign a message with Ledger via metamask extension

### ISSUE THREAD

**Issue by auryn-macmillan** [MetaMask/metamask-extension#7876] opened 2020-01-21 15:51 UTC
**Describe the bug**

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to https://mycrypto.com/sign-and-verify-message/sign
2. Choose "MetaMask"
3. Type some text to sign
4. Try to sign text using a Ledger wallet connected via metamask

**Expected behavior**
The signed message should be displayed.

**Screenshots**
Signing a message on MyCrypto while logged in directly with a Ledger.
![image](https://user-images.githubusercontent.com/8453294/72819053-87108d00-3c3a-11ea-88fe-174631040d7e.png)

Trying to sign the same message with a Ledger via metamask (I pressed ✅ on the ledger when prompted to sign the message)
![Peek 2020-01-21 10-43](https://user-images.githubusercontent.com/8453294/72819257-f25a5f00-3c3a-11ea-87f0-ea5bd0e3b8ec.gif)

**Browser details (please complete the following information):**
 - OS: Xubuntu 18.04
 - Hardware Wallet: Ledger Nano S
 - Browser: Brave
 - MetaMask Version: 7.7.2

**Comment by 1mdc** [comment] 2020-01-24 12:37
I have the same problem in Chrome MacOs

**Comment by mudgen** [comment] 2021-01-13 17:46
This issue is almost a year old.  I really want to use MetaMask with my ledger.   Can this be fixed soon?   I heard that Ledger fixed this problem on their side already so it just needs to be fixed in Metamask.  Can we elevate the status of this issue?  @Gudahtt

**Comment by Gudahtt** [comment] 2021-02-02 14:19
We updated the Ledger connect library we're using on Jan. 21st, which seems to have fixed this issue. I have confirmed that this now works.

**Closed by Gudahtt** 2021-02-02 14:19 UTC
Labels: L17-hardware, S2-normal, T00-bug, ledger-hardware-wallet, needs-triage

**Comment by mudgen** [comment] 2021-02-02 14:24
@Gudahtt Thank you!

**Comment by boffix** [comment] 2021-02-02 17:54
Just checked LedgerLive and Ethereum app are up to date - all good. Then checked metamask extension which got an update from 9.0.3 to 9.0.4 - hopium! Immediately tried to send some Matic with Matic Mainnet - but no luck for me - yet. 
![2021-02-02 18_29_00-MetaMask](https://user-images.githubusercontent.com/42446112/106641867-fb894600-6587-11eb-8c6f-9b68d5a910b0.png)
:( got the same error message instead.

**Comment by Gudahtt** [comment] 2021-02-02 17:59
Thanks for checking @boffix!

I suspect what you've encountered here is a separate issue, though similar. I am able to consistently sign messages using MyCrypto, as described in this issue.

Could you open a separate issue, and provide steps to reproduce?

**Comment by danfinlay** [comment] 2021-02-02 18:26
Looks like we have a new issue that's been created that describes the reported behavior: #10294

**Comment by mudgen** [comment] 2021-02-02 18:32
@Gudahtt Adding Matic Network to Metamask is done like this:

Add the following as a custom RPC connection:

Name: Matic Network
RPC URL: https://rpc-mainnet.maticvigil.com/
ChainID: 137
Symbol:  MATIC

**Comment by boffix** [comment] 2021-02-02 20:04
> Thanks for checking @boffix!
> 
> I suspect what you've encountered here is a separate issue, though similar. I am able to consistently sign messages using MyCrypto, as described in this issue.
> 
> Could you open a separate issue, and provide steps to reproduce?

Happy to help, Opened a new issue, see here: https://github.com/MetaMask/metamask-extension/issues/10336
