### ISSUE TITLE
[Bug]: Adding custom RPC URL results in 'Error: No custom network client was found with the ID'

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26072] opened 2024-07-24 05:09 UTC
### Describe the bug

Adding another RPC URL for the existing chain results in 'Error: No custom network client was found with the ID'. URL is successfully replaced, transactions can be submitted as expected.

Unable to change RPC URL back to https://network*name-mainnet.infura.io, error 'Couldn't fetch chain id':

<img width="309" alt="Screenshot 2024-07-25 at 23 27 59" src="https://github.com/user-attachments/assets/e1dbb84c-efcb-409b-b9b5-e8214dd59ee7">

Error when adding cutom RPC for Polygon:

<img width="585" alt="Screenshot 2024-07-25 at 23 28 51" src="https://github.com/user-attachments/assets/5f4008ed-23fc-44c2-a023-0aea4ff3d204">

Bug is present in the latest v12.0.0, on `develop` and in 12.1.0

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/16389ede-996c-40e1-b19a-166bd302e90d

<img width="583" alt="Screenshot 2024-07-24 at 00 45 59" src="https://github.com/user-attachments/assets/22c4544f-5dca-4d52-a095-536c86891b09">

### Steps to reproduce

1. Go to Setting -> Networks
2. Add alternative RPC URL for the existing chain

### Detection stage

In production (default)

### Version

v12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Gudahtt** [comment] 2024-07-26 13:13
I don't think `https://avalanche-mainnet.infura.io` is a valid URL, the project ID is missing. So "Could not fetch chain ID" is the correct error in that case.

**Comment by sleepytanya** [comment] 2024-07-26 16:24
@Gudahtt @salimtb 

 Network details showing wrong / incomplete link?

<img width="327" alt="Screenshot 2024-07-26 at 12 04 10" src="https://github.com/user-attachments/assets/6851e61a-73e6-4c2f-8f94-f817dc50d857">

I'm on Arbitrum with the custom RPC, doing nothing, getting these errors non-stop (+floating error message in the Settings):


<img width="567" alt="Screenshot 2024-07-26 at 12 19 28" src="https://github.com/user-attachments/assets/8a4537cf-27dd-4ce3-9452-1c7af5623717">

<img width="537" alt="Screenshot 2024-07-26 at 12 20 28" src="https://github.com/user-attachments/assets/fc489ce0-9177-426d-9e03-02bc84faff87">



https://github.com/user-attachments/assets/665a64df-d48e-49cb-a6cb-00a8c2e3e39f

**Comment by Vitomir2** [comment] 2024-08-29 09:34
Hello, community,

I am experiencing also some problems with networks that are not added. I am using the web3onboard and receive the following errors from MetaMask:
<img width="527" alt="image" src="https://github.com/user-attachments/assets/37dbf3ad-f5da-4c77-a102-d91399a4b82b">

**Comment by benjisclowder** [comment] 2024-12-18 15:14
This is not reproducible on 12.10.0.

**Comment by adrigug** [comment] 2024-12-18 20:53
Initial issue: avalanche endpoint:
The initial issue happened since the rpc endpoint [https://network*name-mainnet.infura.io] is invalid. Assuming the user would already have an infura account, the url would read with the following structure: https://avalanche-mainnet.infura.io/v3/YOUR-PROJECT-ID

When reproducing these steps in ext 12.9.0, when trying to add an rpc endpoint for one of the networks that already exist in MM, the error message is as follow:

![Image](https://github.com/user-attachments/assets/dc75284a-5719-4aaa-9e1c-09bbedb0bd1f)

Second issue:
Arbitrum endpoints - In the recording where the user changes the arbitrum endpoint, before making the change, the rpc endpoint is set to use the arbitrum one public rpc endpoint:
![Image](https://github.com/user-attachments/assets/eb6fc2f3-4a7a-4f43-9308-6b144db28d0d)
Later in the recording, the user changes it to the https://rpc.ankr.com/arbitrum/ (which points to the nova blockchain).

Arbitrum One and Arbitrum Nova have two different chainID. So the issues after updating the endpoint are very likely due to the chaindID and rpc endpoints looking at two different things.

Third issue:
@Vitomir2 - The error message you shared seem to indicate that you tried to set the chainID as 0x228c . In the wallet, we expect the chainID to be a number. In the initial post, the chain ID for Avalanche for example is 43114. If you re still having the issue after using a whole number, please create a new ticket with the details of the blockchain network you re trying to use including rpc url and the chain ID.
thanks

**Comment by adrigug** [comment] 2024-12-18 21:20
Adding reproduction steps to update the rpc url on Avalanche mainnethttps://github.com/user-attachments/assets/8c3ea754-1d6b-45c8-8726-5db889bd137d

**Comment by adrigug** [comment] 2024-12-18 21:21
https://github.com/user-attachments/assets/5494c019-a34e-47d0-b06f-2b7db1660c86

Reproduction steps for the avalanche mainnet endpoint update.

**Comment by adrigug** [comment] 2024-12-20 16:54
closing this ticket based on information provided.

**Closed by adrigug** 2024-12-20 16:54 UTC
Labels: type-bug, Sev2-normal, team-assets, regression-RC-12.0.0
