### ISSUE TITLE
[Bug]: Initiating a swap from the "All networks" assets view for a token on a different network than the one currently selected results in the token balance being displayed as zero on the swap screen

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28509] opened 2024-11-16 05:49 UTC
### Describe the bug

Attempting to initiate a swap from the "All networks" assets view for a token on a different network than the one currently selected results in the token balance being displayed as zero. Transaction can't be submitted.

Build https://drive.google.com/file/d/1qhGX0lnrTX47M_7kbqBmhOXTd8HvmflL/view?usp=drive_link

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/3bfdd455-34eb-4a9f-af21-953d520c5fa5

### Steps to reproduce

1. Switch to 'All network' view
2. Select token on a different network
3. Start swap
4. 

### Detection stage

On the development branch

### Version

dev build 

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gambinish** [comment] 2024-11-18 22:00
Addressed here: https://github.com/MetaMask/metamask-extension/pull/28386/commits/023518971e24ecdeb635aa3f4f9b03e6d8e7d348

**Comment by sleepytanya** [comment] 2024-11-19 06:09
Balance is not 0 but the message about insufficient token balance is shown under the actual token balance. After destination token is selected the message disappears.


https://github.com/user-attachments/assets/cafabe65-4f19-443c-aa0b-85bfd4a8696a

**Comment by Unik0rnMaggie** [comment] 2024-11-20 09:55
Issue is not present in the qa-3 build.

The balance of the token seems to be updated correctly on the swap screen.


https://github.com/user-attachments/assets/18075282-15c3-4596-96d7-7a31efd1b6d3

**Comment by gambinish** [comment] 2024-11-20 23:57
I'm about to release another build `qa-5`. Can we verify that this bug has been fixed, so that we can close this out?

**Comment by sleepytanya** [comment] 2024-11-21 06:08
@gambinish 
Same behavior as in the previous [comment ](https://github.com/MetaMask/metamask-extension/issues/28509#issuecomment-2484784885) - Balance is not 0 but the message about insufficient token balance is shown under the actual token balance. After destination token is selected, the message disappears. Tx can be succesfully submitted on the correct network:

<img width="619" alt="Screenshot 2024-11-21 at 01 03 05" src="https://github.com/user-attachments/assets/546a2ee4-72eb-4d37-a7a4-370abc6c8110">




https://github.com/user-attachments/assets/c2e23963-f0f4-478a-ab53-0f6d6a1cacc1

**Comment by Unik0rnMaggie** [comment] 2024-11-21 10:58
Confirming same bahavior in qa 5- build:

After destination token is selected, the message disappears:


https://github.com/user-attachments/assets/a3e16025-d72d-47a3-a24d-6005f91862e4

**Comment by gambinish** [comment] 2024-11-22 00:42
Thanks, this sounds like a messaging issue that should be a quick fix. Likely still in qa-6, but I can look at fixing this tomorrow

**Comment by sleepytanya** [comment] 2024-11-23 06:03
The 'Not enough token' message is not related to the fact that user selects the token on a different network.
It happens for all non-native tokens if swap is initiated from the token details screen, it can be token on the currently selected network as well as token from another network:



https://github.com/user-attachments/assets/94a31b3d-a02a-42a5-9b74-8a3f28e89881

**Comment by Unik0rnMaggie** [comment] 2024-11-25 10:06
Reproduced on qa-7 build, when swapping non native tokens from the token details screen.

The message disappears after selecting the token to swap to


https://github.com/user-attachments/assets/f00f4265-2b0d-4ee5-8626-af0f31a1a483

**Comment by gambinish** [comment] 2024-11-26 15:55
Closing, since this seems to be fixed on qa-8

**Closed by gambinish** 2024-11-26 15:55 UTC
Labels: type-bug, Sev2-normal, team-wallet-ux, portfolio-view
