### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by jeffscottward** [MetaMask/metamask-extension#9230] opened 2020-08-14 15:03 UTC
**Describe the bug**
Trying to reveal private key and encountered this error when entering my password. It keeps crashing now and wont stop.
I was trying to port some keys over to firefox if that helps.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Install MM in firefox
2. Paste in a previous seed phrase
3. Success
4. Go to import a specific key pair
5. Go to chrome
6. Try to reveal a private key
7. Crash
8. Try to access options for a an address - crash - restart chrome and try again - still crash

**Expected behavior**
For this not to happen.

**Screenshots**
N/A

**Browser details (please complete the following information):**
 - OS: Lastest OSX - Latest Chrome
 - MetaMask Version Latest

**Additional context (Error Messages, etc.)**
I was typing very fast - copy pasted my password twice I think. Overflow bug? Race condition? Etc

**Comment by jeffscottward** [comment] 2020-08-14 15:03
MetaMask encountered an error
Try again by closing and reopening the popup, or contact support at support@metamask.io
Error Details
Message: Cannot read property 'type' of undefined

Code: TypeError

Stack:
TypeError: Cannot read property 'type' of undefined
    at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:180:303714)
    at ca (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:59367)
    at Pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:104449)
    at bl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:90053)
    at pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:89978)
    at ol (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:87326)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:45768
    at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:220:3472)
    at Gi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:45477)
    at Xi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:45713)
    at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:45648)
    at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:114525)
    at Tr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:29321)
    at HTMLDocument.u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:55:120400)

**Comment by Gudahtt** [comment] 2020-08-18 22:53
Thanks for the report! This sounds like #9063 which was released in v8.0.7 of the extension.

It's possible you were on v8.0.6, since v8.0.7 was published to Chrome on the same day you made this report 🤔 . Are you still experiencing this issue?

**Closed** 2020-08-26 23:19 UTC
Labels: N02-needsReproduction, S1-high, T00-bug

**Comment by maikelmclauflin** [comment] 2021-07-22 16:54
I experienced this issue today

**Comment by Gudahtt** [comment] 2021-07-26 13:34
@maikelmclauflin Thanks for the report - could you give any more details? Which version of the extension, which browser, and which OS? Was the error message exactly the same? Are the steps to reproduce the same as in this issue?
