### ISSUE TITLE
Popup instantly closes on FireFox Quantum

### ISSUE THREAD

**Issue by ligi** [MetaMask/metamask-extension#4902] opened 2018-07-27 16:38 UTC
video of the problem: https://www.youtube.com/watch?v=8ZpDvevmLJk

using MetaMask on chromium for a while now. Had to install it on firefox now to test something. Unfortunately MetaMask on Firefox does not work for me after installation. The popup always instantly closes for me.

Happens with FireFox quantum 61.0.1 (64-bit) on Ubuntu 18.04 LTS

please let me know if I can be of assistance getting to the ground of the problem - e.g. access some logs. Problem is completely reproducible for me

**Comment by Maayu2415** [comment] 2018-07-27 16:44
Hi! You are change my password?You don't my mine.

ส่งจากสมาร์ทโฟน Samsung Galaxy ของฉัน
-------- ข้อความดั้งเดิม --------จาก: ligi <notifications@github.com> วัน​ที่: 27/7/18  23:38  (GMT+07:00) ถึง: MetaMask/metamask-extension <metamask-extension@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> เรื่อง: [MetaMask/metamask-extension] Popup instantly closes on FireFox Quantum (#4902) 
video of the problem: https://www.youtube.com/watch?v=8ZpDvevmLJk
using MetaMask on chromium for a while now. Had to install it on firefox now to test something. Unfortunately MetaMask on Firefox does not work for me after installation. The popup always instantly closes for me.
Happens with FireFox quantum 61.0.1 (64-bit) on Ubuntu 18.04 LTS
please let me know if I can be of assistance getting to the ground of the problem - e.g. access some logs. Problem is completely reproduceable for me

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MetaMask/metamask-extension","title":"MetaMask/metamask-extension","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MetaMask/metamask-extension"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Popup instantly closes on FireFox Quantum (#4902)"}],"action":{"name":"View Issue","url":"https://github.com/MetaMask/metamask-extension/issues/4902"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MetaMask/metamask-extension/issues/4902",
"url": "https://github.com/MetaMask/metamask-extension/issues/4902",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Popup instantly closes on FireFox Quantum (#4902)",
"sections": [
{
"text": "",
"activityTitle": "**ligi**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ligi",
"facts": [
{
"name": "Repository: ",
"value": "MetaMask/metamask-extension"
},
{
"name": "Issue #: ",
"value": 4902
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"MetaMask/metamask-extension\",\n\"issueId\": 4902,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"MetaMask/metamask-extension\",\n\"issueId\": 4902\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/MetaMask/metamask-extension/issues/4902"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 361735768\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Maayu2415** [comment] 2018-07-27 17:03
Thank you. Please check code
I used password regist  in Bitbounce
Un
success

ในวันที่ ศ. 27 ก.ค. 2018 23:38 ligi <notifications@github.com> เขียนว่า:

**Comment by tmashuang** [comment] 2018-07-27 17:05
@ligi https://consensys.zendesk.com/hc/en-us/articles/360007617432

**Comment by ligi** [comment] 2018-07-27 17:10
@tmashuang thanks - that looks like it could fix the problem - will test after the next computer restart - which seems to be needed here but is really inconvenient right now ..-)

**Comment by tmashuang** [comment] 2018-07-27 17:13
@ligi lets us know if this doesn't work. There is a known issue with ibus and Ubuntu 18.04 found here. https://github.com/ibus/ibus/issues/2002#issuecomment-386537208. We are monitor it to see a potential fix.

**Comment by ligi** [comment] 2018-07-29 16:20
Yes this worked - thanks. Should this one be kept open?

**Comment by bdresser** [comment] 2018-07-31 18:32
@ligi we have a couple open issues with various symptoms of the same, so I'm going to close this one for now.

**Closed by bdresser** 2018-07-31 18:32 UTC
