### ISSUE TITLE
Unchecked runtime.lastError: Could not establish connection

### ISSUE THREAD

**Issue by travisdmathis** [MetaMask/metamask-extension#6817] opened 2019-07-06 14:41 UTC
**Describe the bug**

When a dapp is open in a tab and user closes the browser and later reopens it, when the tab is reopened metamask fails to connect to the browser.

```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
contentscript.js:1 MetamaskContentscript - lost connection to MetaMask Background Multiplex
H @ contentscript.js:1
contentscript.js:1 MetamaskContentscript - lost connection to MetaMask muxed traffic for channel "provider" failed.
H @ contentscript.js:1
contentscript.js:1 MetamaskContentscript - lost connection to MetaMask muxed traffic for channel "publicConfig" failed.
```

**To Reproduce**
1. Open a dapp enabled website and login / connect
2. close the browser completely
3. reopen it and browse to your console on the tab connected to a web3 page.

**Expected behavior**
A clear description of what you expected to happen.

metamask to work w/o refreshing the page

**Screenshots**
![metamaskerrors](https://user-images.githubusercontent.com/1335198/60757625-1f1a9200-9fdb-11e9-9e3e-8c502427cbf3.gif)

**Browser details (please complete the following information):**
- Brave Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
- MetaMask 6.7.2

**Additional context**

**Comment by tjayrush** [comment] 2020-02-12 14:26
I'm seeing this same issue under

```
Google Chrome
Version 80.0.3987.100 (Official Build) (64-bit)
```

**Comment by tmashuang** [comment] 2020-02-13 21:04
Closing due to inability reproduce behavior on Chrome and Brave. I was unable to access the dapp in the screen capture due to my region, but I used a few other ones without issues, Idex/CryptoKitties/etc. There must be something specific to reproduce the issue that I am missing. Please fill out the reproduction steps thoroughly in a new issue.

**Closed by tmashuang** 2020-02-13 21:04 UTC
Labels: N02-needsReproduction, S07-brave, T00-bug

**Comment by jamesmorgan** [comment] 2020-02-17 12:23
I have also seen this issue occurring in Chrome, Windows. Not sure on how to reproduce it tbh but I see this for some web3 contract calls. `Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by cliffhall** [comment] 2020-05-06 16:06
One of our users is seeing this issue as well:
![metamask-issue](https://user-images.githubusercontent.com/871933/81200458-fa43d200-8f91-11ea-8606-f27ba713a91c.png)

**Comment by TimDaub** [comment] 2021-06-24 14:12
I've seen this as part of #9196

**Comment by Mattijah** [comment] 2023-11-12 20:27
Experiencing a similar issue https://community.metamask.io/t/provider-not-getting-connected/27309/2
