### ISSUE TITLE
SignTypedData error -- incorrect chainid

### ISSUE THREAD

**Issue by JTraversa** [MetaMask/metamask-extension#11894] opened 2021-08-19 16:17 UTC
**Describe the bug**
When attempting to use signTypedData_v3 or v4, I am returned the error `MetaMask - RPC Error: Provided chainId "66" must match the active chainId "42"` 

(signed on Kovan(42), but reading chainId as OkEx Chain(66))

**Steps to reproduce**
Just attempt to sign a typed data object using signtypeddata
(https://swivel.exchange)

**Expected behavior**
The modal with the typed data pops up allowing me to sign the data.

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 92.0.4515.131
 - MetaMask Version: 10.0.2
 (did not happen pre 10.0.2)

**Other comments**
I've tested other deployments of ours which dont appear to have this issue. Perhaps it is an issue with ethers versioning (5.0.31)?

**Comment by JTraversa** [comment] 2021-08-19 22:24
I've tried replicating outside of this app and haven't been able to.

We're rebuilding our app and releasing a new version next week, so this isn't necessarily a blocker for us as it isn't replicated in the new app. 

It is just definitely strange behavior, and after checking our signing methods, ethers, etc, its definitely a bug on the side of the metamask RPC.

**Comment by jknight** [comment] 2021-08-20 10:19
I can reproduce this consistently on FF and Chrome. We are using ethers 5.4.4

**Comment by jknight** [comment] 2021-08-20 10:34
Is this a duplicate of #11830 ?

**Comment by Pol-Lanski** [comment] 2021-08-20 14:08
Same issue as https://github.com/MetaMask/metamask-extension/issues/11847

**Comment by jmagder** [comment] 2021-08-20 14:30
I haven't been able to reproduce this but I have two team members who consistently reproduce this.

**Comment by jmagder** [comment] 2021-08-21 02:57
I am able to reproduce this consistently.  The chainId is being treated as a hex number.  Even if I provide 01337. it gets interpreted as 0x1337.

**Comment by jmagder** [comment] 2021-08-21 14:50
https://github.com/MetaMask/metamask-extension/pull/11900

**Comment by Gudahtt** [comment] 2021-09-16 03:06
This should be fixed as of #11900, which will be included in the next release.

**Closed by Gudahtt** 2021-09-16 03:06 UTC
Labels: needs-reproduction
