### ISSUE TITLE
[Bug]: eth_requestAccounts query returns nothing and shows no error

### ISSUE THREAD

**Issue by zdesqa** [MetaMask/metamask-extension#17339] opened 2023-01-21 16:19 UTC
### Describe the bug

- If you open chrome devtools beforehand, there is no error.

- The same problem is observed with TronLink wallet, which like MetaMask inserts its functions into window object.

**Therefore, the error is most likely in the interaction with the window object.**

- Google Chrome 109.0.5414.87

- we don’t use any additional libraries, we take window.ethereum directly

- output the ethereum.isConnected() method gives: true

### Steps to reproduce

1. Open the page app.rubic.exchange
2. Connect Wallet select MetaMask
3. Disconnect Wallet
4. Open a new page app.rubic.exchange do not refresh, just open a link
5. Connect Wallet select MetaMask

### Version

10.23.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by freshaspect** [comment] 2023-02-16 21:47
Hitting this issue multiple times a day across a variety of sites, including blur.io and app.gelato.network -- a page refresh resolves it but it delivers a poor UX and as app developers we're struggling to find a workaround.

**Comment by freshaspect** [comment] 2023-02-16 21:59
We are experiencing the same issue on app.gelato.network, users when they return to our application they find that the app hangs waiting for Metamask to connect but eth_requestAccounts returns nothing. As a user I get the same symptoms on blur.io so it feels like a generalised issue but does seem to be more prevalent if your wallet has a decent number of accounts and/or networks configured within it. 

In the console, entering:
```
let accounts = await ethereum.request({ method: 'eth_requestAccounts' });
accounts
```
Returns an empty response but if you simply refresh the page it connects fine and entering the command above will show the connected wallet. 

The problem is that for average users it looks like they simply can't connect and delivers poor UX. We have been unable to find a workaround thus far.

**Comment by danjm** [comment] 2023-07-25 04:16
@freshaspect @zdesqa are you still seeing this problem?

**Comment by vandan** [comment] 2023-10-20 19:33
We believe issues like this may have been resolved by: https://github.com/MetaMask/metamask-extension/issues/19290

**Closed** 2023-10-20 19:33 UTC
Labels: type-bug, needs-reproduction, Sev2-normal, team-devex
