### ISSUE TITLE
[Bug]: Changing the network from the "Send" tokens page may cause the page to break

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#17013] opened 2022-12-20 19:31 UTC
### Describe the bug

When changing networks from the "Send" token page, an occasional error may cause the page to break.

Error:
<img width="1055" alt="Screen Shot 2022-12-15 at 04 45 38" src="https://user-images.githubusercontent.com/20778143/207721890-a9da5dae-6d8a-4296-a868-fa7997baad79.png">

note: If we find this error is found on v10.23.0 and older, this may not be a blocker for v10.24.0, but should be fixed ASAP. 

### Steps to reproduce

1. Log in to extension
2. Click the circular "Send" button on the overview page
3. Change networks
4. Maybe repeat step 3 a few times
5. Observe error 

### Version

10.24.0 and possibly older versions

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jpuri** [comment] 2022-12-21 15:10
Changing network on confirmation screen causes some un-predictable behaviour, but I think it is not regression - it is an old issue. I think this is more visible for Goerli network as I found that api for Goerli network are behaving bit unpredictably.

I would rather prefer to take time to analyse this issue more and fix later.

**Comment by digiwand** [comment] 2022-12-21 16:54
Thanks for confirming this issue is found on older versions as well. Removed this issue from the v10.24.0 milestone

**Comment by digiwand** [comment] 2022-12-21 16:54
@jpuri Thanks for confirming this issue is found on older versions as well. Removed this issue from the v10.24.0 milestone

**Comment by ElvirCe** [comment] 2023-01-23 10:57
@bschorchit we tried with multiple versions and browsers but could not reproduce this error message. Can anyone please confirm that this error is still coming up?

**Comment by bschorchit** [comment] 2023-01-23 12:57
@seaona Dan assigned this ticket to PS team this week, but they were not able to reproduce it. Once you have a chance, could help them with that? Thank you <3

**Comment by seaona** [comment] 2023-01-24 11:23
I could not repro so far, using the last develop. @digiwand @jpuri could you still reproduce the issue?

**Comment by digiwand** [comment] 2023-01-24 14:43
I no longer see the page breaking. We can close this issue. Thanks for looking into this y'all!

I am observing another issue. After switching networks, clicking next, and returning back to edit, I am unable to open the network dropdown not sure if we should open an issue for this now
cc: @seaona @bschorchit 
https://user-images.githubusercontent.com/20778143/214322406-bcae8b82-fcfa-4a09-a204-c2cd1dd33868.mov

**Closed** 2023-01-24 14:43 UTC
Labels: type-bug, PS-team, team-confirmations

**Comment by seaona** [comment] 2023-01-26 09:54
thank you @digiwand !! I double-check and can confirm the behaviour on the Edit page, not being able to Switch Networks. Not sure if it's something we want to change, but maybe? @bschorchit @danjm
