### ISSUE TITLE
Create new account - NOT "welcome back"

### ISSUE THREAD

**Issue by Tectract** [MetaMask/metamask-extension#6430] opened 2019-04-10 00:13 UTC
**What problem are you trying to solve?**
I don't want to use my old account. I want to keep it, and create a new wallet. There is no "create new wallet" page when I open metamask, only options are to log in or restore from seed. I don't want to do either of these.

**Describe the solution you'd like**
On the frontpage, before you log in, instead of saying "Welcome back", it should give you the option to use an already-existing account, or to create a new one. Don't assume that the person using the browser is always the same person or that they always want to use an already-created wallet.

**Additional context**

**Comment by tmashuang** [comment] 2020-12-04 16:49
Duplicate of https://github.com/MetaMask/metamask-extension/issues/6656, and related to #4828.

**Closed by tmashuang** 2020-12-04 16:49 UTC
Labels: N00-needsDesign
