### ISSUE TITLE
[Bug]: Transaction stuck in 'Unapproved' state when Smart Transaction is pending

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26360] opened 2024-08-10 00:28 UTC
### Describe the bug

To provide some clarity on the current situation: when there is a Smart Transaction (STX) in a 'Pending' state, MM restricts the initiation of other transactions across any network. 
However, transactions of the 'Approval' type, whether initiated from a dApp or directly within MetaMask, can still be started. This action leads to the MetaMask popup displaying a perpetual loading spinner, and the transaction is listed as 'Unapproved' in the Activity tab. These 'Unapproved' transactions cannot be rejected or confirmed, even after the STX has been successfully processed. 
The issue can be remedied by reloading the extension, after which the 'Unapproved' transaction can be addressed as needed.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/fee1548a-f925-4654-abe0-fc1467bd4f92

https://github.com/user-attachments/assets/4b6d7751-4c0c-4e80-97a7-02f5d9e6e83c

### Steps to reproduce

1. Send STX
2. Start Approval transaction on another network
3. The approval transaction is stuck in 'Pending' state

### Detection stage

In production (default)

### Version

v12.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment] 2024-10-23 00:59
@dbrans feel free to close if it looks good to you!

On current `develop`:

-  It remains possible to submit an `Approval` transaction even while an STX transaction is in a `Pending` state
-  A relevant message indicating a queued transaction is properly shown
- The` Approval` transaction appears in the Activity list marked as` Unapproved`
- Users can engage with the Confirmation screen for the `Unapproved `transaction, although they are unable to cancel it.
- Once the STX transaction has been submitted, the` Approval` transaction is successfully confirmed



https://github.com/user-attachments/assets/407d6a8a-414b-4dd4-b19f-f5b0677d8109

**Comment by dbrans** [comment] 2024-10-23 15:29
Thanks for the detailed update, @sleepytanya! The behavior you're seeing looks normal, so I'll go ahead and close this bug since the issue isn't happening anymore.

**Closed by dbrans** 2024-10-23 15:29 UTC
Labels: type-bug, Sev2-normal, team-transactions, regression-prod-12.0.1
