### ISSUE TITLE
Display estimated confirmation time of pending transactions

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#7123] opened 2019-09-09 00:57 UTC
**What problem are you trying to solve?**
After a tx is submitted, the user doesn't know what is the actual realistic estimate of how long until the tx is mined. MM did display an estimate, but its calculation at the time may have been outdated or the mempool may have substantially changed in the meantime. By default users click "View on Etherscan" to get an estimate. This is suboptimal at least for two reasons:
* extra effort for an essential piece of information
* uses more resources (time, traffic, memory)
* reduces privacy (by loading the website, tracking elements get loaded from parties like Google, Cloudflare, etc.)

**Describe the solution you'd like**
I'm not sure about this as I have no idea what MM uses for the pre-submission estimates. But the same source could be used for displaying this post-submission. Otherwise, if Etherscan allows, MM could just pull it from them,

**Comment by bdresser** [comment] 2019-09-09 19:18
closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/6850

**Closed by bdresser** 2019-09-09 19:18 UTC
