### ISSUE TITLE
[Bug]: Precision is lost displaying Permit value in simulation and data tree

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#25755] opened 2024-07-10 23:33 UTC
### Describe the bug

formatAmount in `ui/pages/confirmations/components/simulation-details/formatAmount.ts` utilizes Intl.NumberFormat, which requires a BigInt or number passed to it causing a loss in precision when computing large numbers. It does not accept strings. Currently, it will display 0s for the digits after 15 digits.

we should update the logic to preserve the precision

Example:
- 30001231231212312138768 → 30,001,231,231,212,312,000,000
- 115792089237316195423570985008687907853269984665640564039457584007913129639935 → 115,792,089,237,316,200,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000

Related: https://github.com/MetaMask/metamask-extension/pull/25741
Related: https://github.com/MetaMask/metamask-extension/pull/25438

### Screenshots/Recordings

<img width="420" src="https://github.com/MetaMask/metamask-extension/assets/20778143/290209e0-29bd-45a2-bcc7-cce8715c6ec4"> 
<img width="320" src="https://github.com/MetaMask/metamask-extension/assets/20778143/9fa377cf-e1f4-42b9-aa62-622fe502c07b">

### Steps to reproduce

1. run `yarn storybook`
2. go to http://localhost:6006/?path=/story/pages-confirmations-confirm-signatures-signedtypeddatav3orv4--permit-story&args=msgParams.data:3.0001231231212312e+22
3. copy and paste the following into data
```
"{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"Permit\":[{\"name\":\"owner\",\"type\":\"address\"},{\"name\":\"spender\",\"type\":\"address\"},{\"name\":\"value\",\"type\":\"uint256\"},{\"name\":\"nonce\",\"type\":\"uint256\"},{\"name\":\"deadline\",\"type\":\"uint256\"}]},\"primaryType\":\"Permit\",\"domain\":{\"name\":\"MyToken\",\"version\":\"1\",\"verifyingContract\":\"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\",\"chainId\":1},\"message\":{\"owner\":\"0x935e73edb9ff52e23bac7f7e043a1ecd06d05477\",\"spender\":\"0x5B38Da6a701c568545dCfcB03FcB875f56beddC4\",\"value\":30001231231212312138768,\"nonce\":0,\"deadline\":50000000000}}"
```

### Version

12.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment] 2024-07-15 14:25
Can this issue be closed? (since this [PR's](https://github.com/MetaMask/metamask-extension/pull/25438) been merged)

**Closed** 2024-07-26 13:11 UTC
Labels: type-bug, Sev1-high, team-confirmations, regression-prod-12.1.0

**Comment by benjisclowder** [comment] 2024-08-12 15:47
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

**1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?**
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @digiwand / cc: @jpuri

**Comment by digiwand** [comment] 2024-08-20 03:42
Hi @benjisclowder, thanks for reaching out and the information for this! @jpuri did create the fix for the specific precision error. I do have details on its cause, so I can provide the RCA here. @jpuri feel free to edit or update this as you see fit as well

1. What PR fixed the issue?
Fix BigNumber() more than 15 digits error: https://github.com/MetaMask/metamask-extension/pull/25741
&
Fix value precision for large values: https://github.com/MetaMask/metamask-extension/pull/25968
 
2. Can you pinpoint the commit from which the issue originated?
Generally, Redesigned Confirmations (new UI created 2024) has been built to display entire values rather than their scientific notation forms. Old confirmations would display the scientific notation form (e.g.  3.0001231231212312e+22). Since I believe the precision bug has existed since the Redesigned Confirmation's inauguration, I cannot pinpoint its exact origin commit. I can however add...
</br>BigNumber() more than 15 digits error has been a common bug that has appeared in various parts of the codebase dating back even years. There have been past workarounds which included turning inputs into strings (which may result in loss of precision) or not accepting large inputs. In this context, I think the error was created here: [#25438 line 55](https://github.com/MetaMask/metamask-extension/pull/25438/files#diff-75a4552cfc3ec527bfa9e53eb4e70b63f00a96d7bffc02846e778978d6bfddceR55). We added a calculation that could result in a large number being passed to BigNumber. Fixing this error uncovered the precision error. 
</br> re: precision - https://github.com/MetaMask/metamask-extension/pull/24036 - This PR introduces the formatAmount method we use to display values for the signature redesign. Notice that [in the tests](https://github.com/MetaMask/metamask-extension/pull/24036/files#diff-92f7b0f022ec4e39540bedb66ecab79bac7310e0cfb0bb78951fcf2b293a91b2R37), we didn't test numbers greater than the JavaScript MAX_SAFE_INTEGER. If we created tests for these large values, we might have noticed the precision error earlier on. 
</br>console showing largest tested value in PR is below MAX_SAFE_INTEGER:
    ```
    > Number.MAX_SAFE_INTEGER
    > 9007199254740991
    > 1213098292340944.5 < Number.MAX_SAFE_INTEGER
    > true
    ```

3. Write a short explanation of the technical cause of the bug
Please see "Technical Details" in https://github.com/MetaMask/metamask-extension/pull/25741

4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
Yes, testing large numbers greater than MAX_SAFE_INTEGER where they may exist.
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
We have various coding patterns to handle numbers. Deciding between Numeric, BigNumber, or other number-value types isn't clear. The libraries can easily be mishandled. e.g. If a large number could be passed to BigNumber it could break the application, but there is no lint warning. As a counter-example, if a string-number value was passed to BigNumber, there would be no runtime error that could break the application. 
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
