### ISSUE TITLE
Events trigger when the user click close button of the left

### ISSUE THREAD

**Issue by hoan-cynopsis** [MetaMask/metamask-extension#6297] opened 2019-03-13 10:10 UTC
**What problem are you trying to solve?**
I'm trying to trigger events when the user clicks on the close button on the left of pop up

**Describe the solution you'd like**
I hope the team can provide the events/feature to manage as well

**Additional context**
![image](https://user-images.githubusercontent.com/42921390/54270766-bda96000-45b2-11e9-8250-4d1fb7f0c059.png)

**Comment by bdresser** [comment] 2019-03-13 19:49
Closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/3124

**Closed by bdresser** 2019-03-13 19:49 UTC
