### ISSUE TITLE
notification window won't open if there is another 'popup' type window from other app

### ISSUE THREAD

**Issue by HangYang** [MetaMask/metamask-extension#4135] opened 2018-04-30 04:30 UTC
Checked your code.  You are detecting if there is any `popup` type window already opened, if there is one, you just update it as `active` no matter if it is the notification window of MetaMask.

To reproduce.
- enable gmail notifications. 
- send a test email to your gmail
- your gmail will popup a desktop notification on the screen
- click on the notification and it will open the email in a `popup` type window, don't close it.
- do a transfer on some dapp website.
- MetaMask will update the Gmail `popup` type window as `active`, while it should display another `popup` window (`notification window` in your code).

my opinion to fix it.
- define an array, every time you show a notification window, store it's `windowId` in it
- every time a notification window been closed (chrome.window.onRemoved), remove it's `windowId` from the array
- when you trying to decide whether the extension should show the notification window, do not query the window with `popup` type, just check the array first, to see if it has any element in it, if there is one,  check the status with the id to decide whether you should display a new one or just update it as `active`.

**Comment by frankiebee** [comment] 2018-05-01 17:19
Ah thanks for opening an issue on this that is defiantly not the intended behavior.

**Comment by vittominacori** [comment] 2018-06-12 09:29
@frankiebee any update about this?

I'm developing an embeddable popup window that generates an address.
People should send payments to this address but when copy and try to paste on MetaMask, it closes my window and lost any progress.

**Comment by danfinlay** [comment] 2018-06-12 18:09
I believe we have identified the cause of this, and so I'm closing this issue in favor of #4553, where we can much more decisively fix this bug.

**Closed** 2018-06-12 20:18 UTC
Labels: P2-sooner, T00-bug, bounty worthy
