### ISSUE TITLE
Browser is crashed after re-login to MetaMask extension

### ISSUE THREAD

**Issue by OleksiiFalkoDevPro** [MetaMask/metamask-extension#7104] opened 2019-09-04 12:31 UTC
**Summary:**
Browser is crashed after re-login and providing request access to MetaMask extension.

**Steps to reproduce:**
1. Go to an application that request access to MetaMask extension
(for instance: https://dai.makerdao.com)
2. Login to MetaMask extension;
3. Click "Connect";
4. Logout from MetaMask extension;
5. Clear browser cache (Ctrl+Shift+R);
6. Repeat steps 1-3;
7. Wait a few seconds

**Expected result:**
Application gets access to the MetaMask extension.

**Actual result:**
Browser is crashed.

**Browser details (please complete the following information):**
 - OS: Windows 10 Version 1903
 - Browser: Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)
 - MetaMask Version: 7.1.0

**Additional context:**
Crash dumps
https://drive.google.com/open?id=10lCkKueWfIFH9rtw9ywoTyLHu_81zJFs

**Comment by danfinlay** [comment] 2019-09-05 21:14
Closing as a duplicate of #7097.

Thanks for the crash dumps, we didn't have any of those yet, so they may help!

**Closed by danfinlay** 2019-09-05 21:14 UTC
Labels: N02-needsReproduction
