### ISSUE TITLE
[Bug]: Metamask json-rpc-engine gets into a bad state if metamask_sendDomainMetadata rpc does not respond

### ISSUE THREAD

**Issue by wwhchung** [MetaMask/metamask-extension#19085] opened 2023-05-10 02:45 UTC
### Describe the bug

We are observing that if you go from one page to another, sometimes the metamask injected provider's json-rpc-engine hangs, with no response ever bing received from a metamask_sendDomainMetadata event.

This screenshot shows the pending rpc request that never resolves.
<img width="259" alt="Screenshot 2023-05-09 at 7 36 09 PM" src="https://github.com/MetaMask/metamask-extension/assets/13840097/ae44dcc5-9143-4309-b5ff-cfd063da6f3f">

### Steps to reproduce

Go back and forth between one page and another (Chrome 112.0.5615.137 arm64 + Metamask 10.29.0).  Eventually, the window.ethereum will become completely unresponsive to any .request rpc calls.

If you trace it down, you will see that there are a number of pending rpc requests that never receive responses, with the first being metamask_sendDomainMetadata.

Because the engine is using a readable stream, it seems that the failure to properly respond to metamask_sendDomainMetadata prevents all subsequent requests from even hitting the infura node (as observed in the extension debugger).

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by wwhchung** [comment] 2023-05-10 03:33
After further testing, it appears that it's not just failure to respond to metamask_sendDomainMetadata.  We've observed random failure to respond to eth calls at well which break the stream/provider.

**Comment by donpdang** [comment] 2023-05-10 05:07
Also noticing the same bug on https://opensea.io/
Steps to reproduce:
1. Connect your wallet on [opensea.io](https://opensea.io/)
2. Open a new tab, and go to [opensea.io](https://opensea.io/)
3. Do this a few more times, eventually, opensea will not hang like this
<img width="1633" alt="Screenshot 2023-05-09 at 10 06 21 PM" src="https://github.com/MetaMask/metamask-extension/assets/65093351/6e7a4eb9-6db1-4723-857d-645a175a4874">

On the console, doing `await window.ethereum.request({method: 'chainId'})` will never return and just hang forever

**Comment by jiexi** [comment] 2023-06-05 21:55
related: https://github.com/MetaMask/metamask-extension/issues/19290

**Comment by wwhchung** [comment] 2024-02-08 00:23
Followup on this:
it is still occurring and seems to be exasperated if phantom + MM is installed.  If you attempt to issue any eth command in certain scenarios, metamask rpc becomes unresponsive.

**Comment by wwhchung** [comment] 2024-05-08 18:12
Why is this closed? it's still a recurring issue.

**Comment by jiexi** [comment] 2024-11-20 18:09
Hey, @wwhchung .

I'm sorry that you're experiencing this issue. 

Could you do me a favor and more precisely specify the exact steps you take to reproduce the bug? Could you elaborate on what `Go back and forth between one page and another` entails? I see you have already mentioned that you have Phantom installed and enabled as well. Does this bug only occur if both MetaMask and Phantom are installed and enabled?

Thank you for taking the time to debug and report it!

**Comment by wwhchung** [comment] 2024-11-20 18:13
Go back and forth between one page and another means to visit one site that uses web3, and another on the same tab, and go between the two pages/sites.

It happens with only metamask installed, but is exasperated/easier to repro if both are installed.

**Comment by jiexi** [comment] 2024-11-20 21:54
Hey @wwhchung ,

Does go between the two pages/sites mean that you are manually entering the url of each one and pressing enter, or using the browser history navigate back and forward functions, or something else?

I'm going to guess you are using the browser history navigation, but I just want to confirm.

Thank you for your support.

**Comment by wwhchung** [comment] 2024-11-20 21:56
> Hey @wwhchung ,
> 
> Does go between the two pages/sites mean that you are manually entering the url of each one and pressing enter, or using the browser history navigate back and forward functions, or something else?
> 
> I'm going to guess you are using the browser history navigation, but I just want to confirm.
> 
> Thank you for your support.

No provlem. Using History navigation primarily.

**Comment by jiexi** [comment] 2024-11-20 22:03
I believe I have a [fix here already](https://github.com/MetaMask/metamask-extension/pull/24950) and will work on getting this merged and released. I don't have an estimated time until you will see this fixed in the Chrome store build, but hopefully this makes it into the next release or the one after that. Sorry again that you have been dealing with this for so long.

Thank you again 🙏

**Comment by Gudahtt** [comment] 2024-11-26 02:20
Fixed by #24950

Thanks again for the help @wwhchung ! It looks like this is slated for v12.9.0, which should be in production by December 11th (potentially earlier if the release process goes well). Please let us know if you continue encountering this problem on that version or any later versions (preferably by creating a new issue that links this one).

**Closed by Gudahtt** 2024-11-26 02:20 UTC
Labels: type-bug, Sev2-normal, team-wallet-api-platform

**Comment by wwhchung** [comment] 2024-11-26 02:22
The referenced bug fix makes sense with respect to what I described.
