### ISSUE TITLE
install && login wrong!!!!

### ISSUE THREAD

**Issue by albert32** [MetaMask/metamask-extension#11062] opened 2021-05-12 11:36 UTC
MetaMask 遇到了一个错误
Try again by reloading the page, or contact support 这里.
错误详情
信息：Incorrect locale information provided

代码：RangeError

栈：
RangeError: Incorrect locale information provided
  at new DateTimeFormat (<anonymous>)
  at r.getTranslatedUINoficiations (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui.js:152:86362)
  at chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui.js:152:410446
  at Array.map (<anonymous>)
  at w (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui.js:152:410388)
  at ca (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:59367)
  at jl (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:104449)
  at bu (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:90053)
  at pu (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:89978)
  at iu (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:87326)
  at chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:172:3472)
  at Vo (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:45477)
  at Yo (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:45713)
  at Ko (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:45648)
  at eu (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:84115)
  at Object.enqueueSetState (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:75:50429)
  at t.x.setState (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:136:1461)
  at chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:93:48080
  at n (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:19:98310)
  at chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:19:98540
  at Array.forEach (<anonymous>)
  at Object.notifyListeners (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:19:98510)
  at S (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:19:102095)
  at chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:19:103236
  at Object.confirmTransitionTo (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:19:98249)
  at Object.push (chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui-libs.js:19:103045)
  at chrome-extension://kepgkpibcmjhcniphhnekleplblgmehn/ui.js:152:874787

**Comment by jcoinas** [comment] 2021-05-12 13:24
Its fixed already

**Comment by thankst** [comment] 2021-05-12 13:50
> Its fixed already on 9.5.1

when can update on chrome store？

**Comment by tmashuang** [comment] 2021-05-12 17:15
Duplicate of #11047, #11045, #11038, #11033, #11055, and #11059

Fixed by #11036

**Closed by tmashuang** 2021-05-12 17:15 UTC

**Comment by rafanake** [comment] 2021-05-28 14:02
9.5.6 and the problem remains....

**Comment by tamakisquare** [comment] 2021-05-31 02:52
I am getting this problem. I am running v9.5.6 on Chrome with MacOS.

@tmashuang I see that you have closed all issues sharing the same symptom as the one reported here. The problem, however, might have been re-introduced after you fixed it previously, as per @rafanake and myself.  Should we re-open one of the closed issues and track the ongoing findings and progress there?
