### ISSUE TITLE
How to disconnect metamask?

### ISSUE THREAD

**Issue by liangzai927** [MetaMask/metamask-extension#10685] opened 2021-03-22 02:29 UTC
![metamask](https://user-images.githubusercontent.com/48548032/111932924-691e1100-8af9-11eb-8687-b68e843f14e8.gif)
How can I realize the disconnection operation in the animation?

**Comment by tmashuang** [comment] 2021-03-22 19:17
Duplicate of #8990, https://github.com/MetaMask/metamask-extension/issues/8990#issuecomment-658985565 is a potential workaround. If there is an additional scenario that is not captured within the discussion in that issue, feel free at reference that issue in a new issue and describe the additional need/use case for this particular feature.

**Closed by tmashuang** 2021-03-22 19:17 UTC
