### ISSUE TITLE
Unresponsive window.ethereum.request() on SPA Applications (React & Vue)

### ISSUE THREAD

**Issue by re2005** [MetaMask/metamask-extension#19290] opened 2023-05-25 14:41 UTC
### Describe the bug

Seems that `SPA` (React, Vue) and `Metamask` are having this issue.
I've tested this behaivour on many websites and it seems consistent every time.

As example Uniswap built in `React`
https://app.uniswap.org

On a previous connected session `Metamask` usually connected automatically if that site have already been approved.

So lets say, if you call:

```
await window.ethereum.request({
      method: 'eth_requestAccounts',
      params: [{ eth_accounts: {} }],
    })
```

It will return your connected address in a Array format.

So far so good, the issue comes when you return to that same website, and than calling `await window.ethereum.request(...)` is not responsive anymore.

Interesting is that same never happens on websites SSR, but mostly happens when is a SPA.

### Steps to reproduce

1. Go to https://app.uniswap.org (or any other React or Vue project)
2. Connect your wallet
3. Open a new tab and paste the address `https://app.uniswap.org` again.
4. Repeat the process until you see that `Uniswap` won't automatically connect
5. Once that happens open the `Console` and try yo fetch your accounts 

```
await window.ethereum.request({
      method: 'eth_requestAccounts',
      params: [{ eth_accounts: {} }],
    })
```

You will notice that `Metamask` doesn't return anything.

To fix, refresh the page, and it will work as expected

### Version

v10.30.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

https://github.com/MetaMask/metamask-extension/assets/2920357/5bc37d35-b357-4ffd-9a8f-e6b0e4be37c1

**Comment by anaamolnar** [comment] 2023-05-30 15:57
Hello, @re2005. Thanks for reporting! I will pass this on to the team.

**Comment by yonigoldberg** [comment] 2023-05-31 01:25
We noticed this issue as well

**Comment by vandan** [comment] 2023-06-01 17:29
There are typically no params passed into eth_requestAccounts.
https://docs.metamask.io/wallet/get-started/access-accounts/

You would then use wallet_getPermissions to retrieve the accounts that the dapp already has permissions for.
https://docs.metamask.io/wallet/reference/rpc-api/#wallet_getpermissions

Does changing that help?

**Comment by re2005** [comment] 2023-06-01 18:37
Thanks @vandan.
Calling 
`window.ethereum.request({method: 'wallet_getPermissions'})`
or 
`window.ethereum.request({method: 'eth_requestAccounts'})`

Doesn't return anything.

Curious is that the `ethereum` object is still available.

But the method `request` never respond.

also tried:
 `await window.ethereum.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: 1 }]
})`

But no success.

<img width="1674" alt="Screenshot 2023-06-01 at 20 31 57" src="https://github.com/MetaMask/metamask-extension/assets/2920357/041a0c4e-54d6-4ab8-9d81-ce1e9875ec35">

**Comment by jiexi** [comment] 2023-06-14 21:47
In summary so far:
* this bug only seems to occur on chrome(ium?) due to the prerender feature
* prerendered pages are loaded and rendered in the background when the user types in a url (but does not hit enter) for a page that they already have open in another tab
* prerendered pages have fully functional inpage <=> extension connection ***until the user presses enter*** in the url bar and the page becomes active and visible
* Following the reproduction steps in the comment above, you can expect to see the following behavior regarding connection stream for the second tab:
  * Immediately after typing the url, [new connection in mm controller](https://github.com/MetaMask/metamask-extension/blob/46a2604df0f09f412c89d586a552ff2d07f9dff0/app/scripts/metamask-controller.js#L3978) for `https://metamask.github.io` with a random `tab id 1`
  * A few seconds later without hitting enter, [new connection in mm controller](https://github.com/MetaMask/metamask-extension/blob/46a2604df0f09f412c89d586a552ff2d07f9dff0/app/scripts/metamask-controller.js#L3978) for `https://ogs.google.com` with random `tab id 2`
  * After hitting enter
    * [connection removed in mm controller due to stream close](https://github.com/MetaMask/metamask-extension/blob/46a2604df0f09f412c89d586a552ff2d07f9dff0/app/scripts/metamask-controller.js#L3710) for `https://metamask.github.io` with a random `tab id 1`
    * [connection removed in mm controller due to stream close](https://github.com/MetaMask/metamask-extension/blob/46a2604df0f09f412c89d586a552ff2d07f9dff0/app/scripts/metamask-controller.js#L3710) for `https://ogs.google.com` with a random `tab id 2`
    * no errors from the closed streams
  * Page now visible and active to the user, but the inpage stream is broken and nonresponsive
  
Attempted fixes:
* checking `document.prerendering` and/or awaiting the `prerenderingchange` event on the document object to delay the [inpage stream creation](https://github.com/MetaMask/metamask-extension/blob/46a2604df0f09f412c89d586a552ff2d07f9dff0/app/scripts/inpage.js#L53) until after the page changes from prerendered to active
  * works, but breaks dapps that do not wait for the ethereum window object to be available much later in the page load process
* https://github.com/MetaMask/json-rpc-middleware-stream/pull/47/files
  * the fix above seems unrelated to this prerender stream bug in particular

**Comment by jiexi** [comment] 2023-06-16 23:32
Branch with more boiled down reproduction here `jl/mme-17339/stream-skeleton-chrome-bug`

[video in slack](https://consensys.slack.com/archives/GTQAGKY5V/p1686779937014549) (was too large for github)

**Comment by jiexi** [comment] 2023-06-21 23:38
Chrome bug report submitted [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1457040). Will work on a fix meanwhile

**Comment by jiexi** [comment] 2023-06-22 20:29
Workaround [here](https://github.com/MetaMask/metamask-extension/pull/19727)

**Comment by jiexi** [comment] 2023-06-27 16:10
Workaround merged

**Closed** 2023-06-27 16:11 UTC
Labels: type-bug, Sev2-normal, team-devex
