### ISSUE TITLE
[Bug]: Error: Ledger device: UNKNOWN_ERROR (0x650f)

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14504] opened 2022-04-22 13:21 UTC
### Describe the bug

Unhandled exception thrown when the Ethereum app on the Ledger device is closed

### Steps to reproduce

1. Connect ledger hardware wallet
2. Send a transaction with low gas e.g. (max priority fee 0.1, max fee 0.1)
3. Accept the transaction
4. Quit the Ethereum app on the ledger device
5. Speed up the transaction

### Error messages or log output

```shell
Error: Ledger device: UNKNOWN_ERROR (0x650f)
  at new TransportStatusError(/eth-ledger-bridge-keyring/bundle.js:23425:18)
  at TransportWebHID.<anonymous>(/eth-ledger-bridge-keyring/bundle.js:23561:39)
  at step(/eth-ledger-bridge-keyring/bundle.js:23467:23)
  at Object.next(/eth-ledger-bridge-keyring/bundle.js:23448:53)
  at fulfilled(/eth-ledger-bridge-keyring/bundle.js:23439:58)
```

### Version

10.14.0

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by luoquanquan** [comment] 2022-09-29 11:40
same bug

**Comment by pedronfigueiredo** [comment] 2023-01-15 18:34
I get the same message if I try to connect to a Ledger wallet that does not have the Ethereum app installed through ledger live.

Try the following steps:
1. install the Ethereum app through ledger live
2. open the app on the device
3. connect MetaMask to ledger

**Comment by Passpartoo** [comment] 2023-12-21 19:10
Hi,

This issue was not closed.
I add screen shot, for help.
Ledger Nano S Plus with 1.1.0 system
But to reproduce on my side, i launch Metamask connection before Hardware Ledger Wallet.

This error can be reproduce with a WebHID connection,
With LedgerLive Connection a other error message ask to use WebHID connection because the bridge is no more available.

"Si l'application Ledger Live est ouverte, désactivez toute connexion en cours à celle-ci et fermez-là".

But even we close the Ledger Live application, this error persiste
![Capture1](https://github.com/MetaMask/metamask-extension/assets/60202252/801a29c6-228f-4dd8-a126-df86461527c9)
![Capture2](https://github.com/MetaMask/metamask-extension/assets/60202252/8f08b888-1325-4763-86cb-8d9825bea59e)
![Capture4](https://github.com/MetaMask/metamask-extension/assets/60202252/b72d96b8-9aa4-4983-9b2e-9ddb5ce94076)
![Capture5](https://github.com/MetaMask/metamask-extension/assets/60202252/6fc38ad3-fd7e-4350-81f7-e3d68191f425)
![Capture6](https://github.com/MetaMask/metamask-extension/assets/60202252/7fabe332-e47a-472d-aa65-375e35604bc7)
![Ledger_Metamask_21_12_2023](https://github.com/MetaMask/metamask-extension/assets/60202252/558098b0-f37b-4385-a8fd-66155783cebb)
.

**Comment by vivek-consensys** [comment] 2024-03-21 10:07
Tested on Chrome using MM Extension v11.12.4

The instructions clearly state to unlock the Ledger device and open the Ethereum app but we can maybe update the error handling for when the Ethereum application is not opened on the device. @AlexJupiter any thoughts on the error handling message that should be displayed?

Instructions:-
![image](https://github.com/MetaMask/metamask-extension/assets/106310394/72351a69-8189-4ec3-9697-2a2fe5699c81)

Application not opened error:- 
![image](https://github.com/MetaMask/metamask-extension/assets/106310394/c8aa7706-6489-4b6a-a7ae-f5748f61b526)

**Comment by Akaryatrh** [comment] 2024-07-18 16:26
I could not reproduce the issue about the error code. But instead I faced a new issue: https://github.com/MetaMask/metamask-extension/issues/25948

Closing this one then.

**Closed by Akaryatrh** 2024-07-18 16:26 UTC
Labels: type-bug, area-Sentry, area-hardware, Sev2-normal, CS-reported, CS-tracking, team-hardware-wallets
