### ISSUE TITLE
Incorrect transaction fee symbol displayed when switching networks

### ISSUE THREAD

**Issue by miguelmota** [MetaMask/metamask-extension#11507] opened 2021-07-12 19:00 UTC
**Describe the bug**
Transaction fee token symbol on approval is incorrect when switching networks.

**Steps to reproduce (REQUIRED)**

1. Switch to Polygon network
2. Then switch to xDai network
3. Make an approval transaction
4. Notice fee token symbol is Matic

**Expected behavior**

Fee token symbol to be XDAI

**Screenshots**

Notice how xDai network is selected, but fee is shown as Matic

![DeepinScreenshot_select-area_20210712112916](https://user-images.githubusercontent.com/168240/125341458-778e7380-e308-11eb-94f4-422474e10ca0.png)
![DeepinScreenshot_select-area_20210712112950](https://user-images.githubusercontent.com/168240/125341461-79583700-e308-11eb-8395-3ad5ab0350f2.png)

**Browser details (please complete the following information):**
 - OS: Arch linux
 - Hardware Wallet: n/a
 - Browser: FireFox 89
 - MetaMask Version: 9.7.1

**Additional context (Error Messages, etc.)**

**Comment by danjm** [comment] 2021-07-14 13:14
Duplicate of https://github.com/MetaMask/metamask-extension/issues/11469 and fixed in v9.8.0

**Comment by danjm** [comment] 2021-07-14 13:15
But thanks for reporting @miguelmota!

**Closed by danjm** 2021-07-14 13:14 UTC

**Comment by miguelmota** [comment] 2021-07-14 16:18
Sorry about the dup. Thanks!
