### ISSUE TITLE
Batch requests failing

### ISSUE THREAD

**Issue by olaf89** [MetaMask/metamask-extension#1844] opened 2017-07-31 12:29 UTC
*  Expected Behavior
Batch request are working
  *  Actual Behavior
Batch requests are failing 
  *  Browser Used
Chrome
  *  Operating System Used
Mac

Im trying to batch 2 transactions using web3.js(0.20.1) batch request interface
var batch = web3.createBatch();
batch.add(request1);
batch.add(request2);
batch.execute();

When creating batched request first time its working as expected, I got a popup with two transactions to confirm. I can approve it and both callbacks are called. Each time i do the same thing after that its failing. I tested it both on testrpc and kovan. 
![screen shot 2017-07-31 at 13 58 49](https://user-images.githubusercontent.com/11535118/28777721-a5c348de-75fc-11e7-8ef9-433b60ce4829.png)
![screen shot 2017-07-31 at 14 13 45](https://user-images.githubusercontent.com/11535118/28777722-a7187560-75fc-11e7-81f5-7a0356048d91.png)

**Comment by Zanibas** [comment] 2017-07-31 19:55
Duplicate of #1092, will elevate priority there.

**Closed by Zanibas** 2017-07-31 19:55 UTC
