### ISSUE TITLE
wheres the safari metamask extension?

### ISSUE THREAD

**Issue by markmark1** [MetaMask/metamask-extension#5173] opened 2018-08-30 18:22 UTC
wheres the safari metamask extension?

**Comment by bdresser** [comment] 2018-09-07 19:21
Hey @markmark1 - Safari doesn’t use the WebExtension protocol like every other browser does. To build an add-on for Safari would require a lot of browser-specific work that we haven't prioritized yet.

In the meantime, try Chrome 😄

**Comment by markmark1** [comment] 2018-09-07 19:26
Chrome is slow and heavy electron app
Pls do safari plugin if possible

On Sep 7, 2018 at 12:21 PM, bobby dresser <notifications@github.com> wrote:


Hey @markmark1 <https://github.com/markmark1> - Safari doesn’t use the
WebExtension protocol like every other browser does. To build an add-on for
Safari would require a lot of browser-specific work that we haven't
prioritized yet.

In the meantime, try Chrome 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MetaMask/metamask-extension/issues/5173#issuecomment-419539971>,
or mute the thread

**Comment by bdresser** [comment] 2018-09-07 19:27
@markmark1 it realistically won't happen in the next couple months - if you'd like to start on a Safari version yourself, we'd be happy to provide guidance!

**Comment by markmark1** [comment] 2018-09-07 19:37
Thanks for sharing! I’m just requesting the feature not looking to build as I think metamask is missing safari   
  
  
  

  
  

  
  
>

**Comment by balupton** [comment] 2018-12-06 01:30
Just wanted to make note that the lack of Safari extension is what is keeping me from MetaMask and all apps that use it. The barrier to entry, of installing a less preferred browser, configuring it, installing some obscure browser extension and configuring that, to access some obscure web app, it too much of an impediment to bother with.

**Comment by markmark1** [comment] 2018-12-06 01:32
Thanks for sharing! I agree absolutely   
  
  
  

  
  

  
  
>

**Comment by whymarrh** [comment] 2018-12-10 18:51
Hey folks, as someone who uses Safari as their daily driver, I too would like to see MetaMask on Safari. That said, Safari has a distinct extension model separate from the one that MetaMask uses (basically [what @bdresser said above](https://github.com/MetaMask/metamask-extension/issues/5173#issuecomment-419539971)) so this would likely be a medium-to-larger amount of work (to first abstract away the extension model and then to build in Safari support).

It would ideal if Safari came to support the same extension model that every other browser uses, but it is probably technically possible to build support for Safari with its current API. I think efforts are best spent petitioning Apple's Safari team to adopt the standard/join the [Browser Extensions Community Group](https://www.w3.org/community/browserext/). (Disclaimer: I don't know if Apple is or isn't part of the group, it _seems_ like they aren't. I don't know how the group operates or what level of control they have over the Browser Extensions standards.)

See also: a lot of other extensions talking about their Safari support e.g. [RES Safari Support](https://redditenhancementsuite.com/safari/):

> It ultimately came down to the direction development of Safari extensions was heading. Major browsers such as Google Chrome, Microsoft Edge and Mozilla Firefox were all adopting a standard commonly known as "WebExtensions". This provides a single API across all browsers. This is hugely beneficial as you can develop for all major browsers from a single code base. Safari is not adopting this standard and instead moving to their own format, with a strong reliance on Xcode. This would require significant investment from the development team to support the browser, as well as core developers having access to Xcode. Supporting this change would mean the codebase for RES would not be unified.

**Comment by whymarrh** [comment] 2019-02-07 01:52
I'm going to close this for now. We can re-open this in the future should things change.

**Closed by whymarrh** 2019-02-07 01:52 UTC
Labels: T11-distribution

**Comment by philburrrt** [comment] 2021-06-08 00:56
> @markmark1 it realistically won't happen in the next couple months - if you'd like to start on a Safari version yourself, we'd be happy to provide guidance!

It's time sers. https://9to5mac.com/2021/06/07/apple-brings-safari-web-browser-extensions-to-iphone-and-ipad-with-ios-15/
i haven't been able to use my ipad for 1.5 years because always need metamask for workflow.

**Comment by caffeinum** [comment] 2021-06-11 04:36
@philburrrt came to this issue to write exactly this. Maybe we can set up a gitcoin grant page for this?

**Comment by philburrrt** [comment] 2021-06-11 04:40
> @philburrrt came to this issue to write exactly this. Maybe we can set up a gitcoin grant page for this?

After writing this, I realized that someone had already made a barebones version. But this was a depressing comment that was included w/ the release. https://github.com/InjectiveLabs/metamask-extension/releases/tag/v9.0.5-safari

"InjectiveLabs team is proud to provide notarized builds for macOS, until the Extension will be approved by Apple and added to the Safari Web Extensions store (unlikely happens), this is the only official way to access the build."

**Comment by eivindml** [comment] 2021-09-20 15:21
Anyone looked further into this? MetaMask is approved on iOS App Store, so don't see why it wouldn't work on the macOS App Store. But probably should be an official MetaMask app/extension.

**Comment by satanworker** [comment] 2021-10-03 18:29
Just installed InjectiveLabs extension and it works great! Not sure what it would take to make hardware wallet to work and pass notarized process, but so far so good, working absolutely fine

**Comment by Zettersten** [comment] 2021-10-31 00:55
https://www.macrumors.com/guide/ios-15-safari-extensions/

With iOS 15 Safari now supporting extensions - how can we (the community members) support MetaMasks appearance their?

Open things to discuss:

- does the new extension framework support MetaMasks technical requirements?
- does an extension need to live separate from the app? (Sounds like it can be bundled - similar to keyboard extensions)
- can the plug-in support the same UX that browsers follow?

**Comment by justhodlmate** [comment] 2021-11-23 12:53
Metamask team please look at extension for Safari please. As you can read above Safari is now supporting extensions! It take too much time for me. 

Please Metamask do something for it.

**Comment by geeksified** [comment] 2021-12-08 11:19
Hello? :(

**Comment by justhodlmate** [comment] 2022-01-11 17:44
I taking too much time. Come on guys, what we can do about it? Any ideas? I will hit their Twitter, Facebook etc. today, any other ideas?

**Comment by balupton** [comment] 2022-01-12 05:12
The best way would be to send a PR

**Comment by arizaxu** [comment] 2022-06-01 06:47
4years after

**Comment by biafra23** [comment] 2022-06-07 07:58
Just speculating here:
Maybe the problem is getting into the official `Safari Web Extensions store`?

**Comment by andresvanegas19** [comment] 2023-10-07 03:32
Hi :) I was wondering...

**Comment by Gogo6969** [comment] 2023-12-15 11:40
Apple does not seem to care about a huge part of its user base.

We need a MetaMask extension for Safari now or you will lose us. I’ve already bought a Windows PC because of the lack of Apple support, and I’m sure I’m not the only one.
