### ISSUE TITLE
Support hardware wallets without creating an account

### ISSUE THREAD

**Issue by dankrad** [MetaMask/metamask-extension#6830] opened 2019-07-10 12:30 UTC
I never had any intention to use Metamask in any other way except for connecting to my hardware wallet. However, in order to do this, I first had to create an account before I could find the menu option "Connect hardware wallet".

This is very confusing UX: For users who only ever want to use a hardware wallet, there should be a menu option that leads them straight to this, without having to create a (useless) account first.

**Comment by bdresser** [comment] 2019-07-10 15:59
closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/6466

**Closed by bdresser** 2019-07-10 15:59 UTC
