### ISSUE TITLE
Default gas set too low on chrome extension  

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#8261] opened 2020-03-31 17:07 UTC
**Describe the bug**
MetaMask extension on Chrome browser suggests default gwei that is lower than on Brave of Firefox for the same transaction, swap, etc. at the same time (same block).

**To Reproduce (REQUIRED)**
On Brave:
![image](https://user-images.githubusercontent.com/16330048/78054637-fcd65a80-7347-11ea-8221-cc7160b5262b.png)

On Chrome:
![image](https://user-images.githubusercontent.com/16330048/78054658-03fd6880-7348-11ea-8316-be4d210efc55.png)

**Expected behavior**
Gas should be estimated the same across browsers, and it should default to the higher option that Firefox and Brave is getting.

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser Chrome
 - MetaMask Version 7.7.8

**Comment by tmashuang** [comment] 2020-03-31 20:02
Our single source for gas price is ethgasstation which we save into local storage for about a minute before querying again. Could this be one of those times that the prices changed in that window and one client gets a different gas price? Can anyone else repro this reliably?

**Comment by monokh** [comment] 2020-03-31 20:18
@tmashuang 
It doesn't feel like a corner case to me. I've had this defaulting to 1 gwei for a few weeks now and it's consistently reproducible. Same for others that have told me they experience this.
I even installed this from source of the latest tag and still reprod.

I saw in the code that there is a constant for default gas (1 gwei), I guess it can be checked to see what situations this will happen.

And ETH gas station integration seems to be working fine for me as I see the slow, average, fast with the graph fine.

**Comment by tmashuang** [comment] 2020-03-31 20:30
Your situation seems unrelated since OP states that this is more about discrepancies in client gas price. 
What you described seems that the ethgassation call doesn't work at all, or isn't updating the localStorage. 
For a little debugging you can open the devtools on the main screen and type `localStorage.BASIC_PRICE_ESTIMATES` to see that the last estimate was. To check if the call is working to go to the Network tab, click Send then there should be a `ethgasAPI.json` call for the price.

**Comment by monokh** [comment] 2020-03-31 21:06
Actually @dpazdan raised this as a result of a chat we had about the issue i'm referring to. 

My localstorage doesn't contain `BASIC_PRICE_ESTIMATES` but it does have `GAS_API_ESTIMATES` set and the values are consistent with what you would get from ethgasstation. 

Getting a confirmation dialog doesn't do any network calls for me, but clicking "edit" beside fee gives me one for `https://ethgasstation.info/json/predictTable.json`.

Yes the same number input as the screenshot above. Here's my screenshot that demonstrates the problem. At this point in time, the low and average were at least 3 gwei. They were displayed as such when you go to "Edit" of fee so it wouldn't seem like ethgasstation was the issue.
![image](https://user-images.githubusercontent.com/11529637/78075007-a266e980-739b-11ea-877c-f16750e4359c.png)

**Comment by tmashuang** [comment] 2020-03-31 21:29
> values are consistent with what you would get from ethgasstation

This is probably correct for the graph, not for the gas price.
All the data that you have is comes from `https://ethgasstation.info/json/predictTable.json`, which is used to populate the graph. The estimated gas price that your screenshot shows should come from `https://ethgasstation.info/json/ethgasAPI.json`, but doesn't seem to be the case for you?

Can you navigate to the `/ethgasAPI.json` url normally? Would you be willing to send you state logs to the support team, titled with this github issue number, for me to look it over, or continue the Q/A here?

**Comment by monokh** [comment] 2020-04-08 06:57
@tmashuang yes no problems in accessing the gasAPI url. 
I can reproduce again now so I've sent state logs and a new video to support. 
Let me know if you need anything else to help.

**Comment by tmashuang** [comment] 2020-04-09 16:22
At look into your logs and the screen capture you posted shows this is happening on external transactions, transaction made by a dapp. We do not use the ethgasstation api on these transactions, rather we use common gas prices in recent block data to present the gas price.
https://github.com/MetaMask/metamask-extension/blob/d1e078b8dec5653a536619274cd33debc20bab22/app/scripts/metamask-controller.js#L1836
The block data, at the time, shows that 1gwei was a sufficient price for transactions to complete, so 1gwei was presented.

**Comment by Gudahtt** [comment] 2020-05-12 19:50
I suspect this is fixed by #8575

**Comment by Gudahtt** [comment] 2020-07-23 18:27
I'll close this now, since it was likely fixed by #8575

**Closed by Gudahtt** 2020-07-23 18:27 UTC
