### ISSUE TITLE
[Bug]: Ledger is no longer working on Firefox 

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-extension#18566] opened 2023-04-13 10:41 UTC
### Describe the bug

The Ledger integration on Firefox is no longer working due to the latest version of Firefox dropping support for U2F. 

Internal Slack conversation: https://consensys.slack.com/archives/GTQAGKY5V/p1679484733528029 

### Steps to reproduce

Try and connect a Ledger to Firefox 112 and you'll see this error:
![image](https://user-images.githubusercontent.com/7900773/231733558-cea791b1-a9b0-4eb5-baa7-9c56664de781.png)

### Version

Firefox 112

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

Ledger

### Additional context

We don't know a long term fix right now, so I'm proposing a super small copy change to the existing error message to direct users to a Ledger article describing a workaround. 

We should change the existing Firefox warning text from:
> We had trouble connecting to your ledger, try reviewing our hardware wallet connection guide 

To:
> We had trouble connecting to your Ledger, try reviewing our [hardware wallet connection guides](https://support.metamask.io/hc/en-us/articles/4408552261275-Hardware-Wallet-Hub#:~:text=MetaMask%20currently%20supports%20five%20lines,to%20Mobile%20in%20future%20updates.).  If you're using the latest version of Firefox you might be experiencing a specific issue related Firefox dropping U2F support, for instructions on how to fix this issue go [here](https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-Firefox-Ledger-Integration-Issue?support=true). 

We should also add an on click metrics event to this support article. Something like `Ledger-firefox-support-article-clicked`

**Comment by kremalicious** [comment] 2023-04-15 14:10
probably duplicate of #18547

**Comment by fabdarice** [comment] 2023-04-18 05:29
Doesn't work still even after re-enabling security.webauth.u2f

**Comment by AlexJupiter** [comment] 2023-04-18 11:21
@fabdarice interesting. Can you make sure you have all other desktop applications closed (especially Ledger Live) and update your Ledger to the latest firmware and Ethereum app versions please? 

If the problem still persists can you share a screenshot with the developer console logs when trying to connect your Ledger please?

**Comment by AlexJupiter** [comment] 2023-04-19 12:31
Someone reached out to me via Twitter DMs who said they'd followed these instructions but they still couldn't connect their Ledger to Firefox. This is a screenshot of their developer console:

![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/d92f5ef8-8e9a-443f-afa1-019fc177b116)

They confirmed:
`ledger firmware is the latest i believe, 2.1.0
firefox browser version says up to date - 112.0.1`

**Comment by christophkoenekamp** [comment] 2023-04-19 14:43
Unfortunately, my friend has been facing the exact same issue since last week. We attempted to resolve it on Chrome, Firefox, and Brave yesterday.

System details:
• Windows 11
• Latest Chrome
• Latest Firefox
• MetaMask Extension: 10.28.3
• Preferred Ledger connection type: WebHID
• Ledger Live Version: 2.57.0
• Ledger Nano S Plus: 1.1.0
• Ethereum App: 1.10.1

However, he remains stuck on:
"Looking for your Ledger", missing the next step of the Pop-up saying: "'MetaMask' wants to connect to a HID device"
This situation is identical to what @AlexJupiter shared to us (see his screenshot above).

Regrettably, Chrome displays no error messages. Firefox shows the following message: 
"Content Security Policy: The page's settings blocked the loading of a resource at eval ('script-src'). runtime-lavamoat.js:9043:14", but this isn't helpful at all.

What's quite strange is that after updating my system to the exact same versions, trying to reproduce his error, I encountered no issues on either Mac or Windows 11 using Chrome or Firefox.

**Comment by danjm** [comment] 2023-04-20 11:30
@christophkoenekamp Regarding your comment "What's quite strange is that after updating my system to the exact same versions, trying to reproduce his error, I encountered no issues on either Mac or Windows 11 using Chrome or Firefox."

Do you mean that you updated your browser, MetaMask and ledger versions to all match your friends, and you could not reproduce the error?

**Comment by danjm** [comment] 2023-04-20 11:48
also @christophkoenekamp, is it possible your friend has any other extensions or software installed that might somehow interfere with the connection of ledger. For example, an ad blocker or something like that. I am trying to think about how your set ups might be different.

**Comment by danjm** [comment] 2023-04-20 19:41
It would be a great help if any experiencing this bug reproduce the problem you are seeing and then take a screenshot of any error in the _background_ console. Here is how to do that

1. Attempt to connect your ledger to MetaMask and/or send a transction with your ledger
2. Once you hit the error, go to chrome://extensions
3. Toggle on "Developer Mode" in the top right corner
4. click the "background.html" that is under the metamask version that your are using
5. this will open a new window, where you can select "console"
6. Take a screenshot of any errors

The below video shows how to do that:

https://user-images.githubusercontent.com/7499938/233470815-42a71d9c-d172-4930-bcae-1e79e4146541.mp4

**Comment by christophkoenekamp** [comment] 2023-04-22 02:39
@danjm @AlexJupiter, first of all, I apologize for my late response!

_Do you mean that you updated your operating system, browser, MetaMask and ledger versions to all match your friend's, and you could not reproduce the error?_ -> Yes, I updated to the exact same versions.

_...is it possible your friend has any other extensions or software installed that might somehow interfere with the connection of ledger. For example, an ad blocker or something like that._ -> He only had a few other wallet extensions like Coinbase.

However, we where able to solve this, at least for him. I offered him two possible solutions and it seems to be a Chrome issue:

Settings -> Privacy and security -> Site settings -> Additional permissions -> HID devices -> Select "Sites can ask to connect to HID devices" -> Click on one of your displayed Ledger's -> Click 'Reset permissions' and make sure it displays "No HID devices found"

Start over to connect your Ledger with MetaMask.

I will get back to you asap once I have a precise answer from him (different time zones). Just wanted to share this with you guys as a potential approach that might be helpful for others as well.

**Comment by danjm** [comment] 2023-04-25 13:48
thank-you @christophkoenekamp, that's helpful

**Comment by plasmacorral** [comment] 2023-05-11 16:40
Ticket originated focused on Firefox, but ultimately [the solution](https://github.com/MetaMask/metamask-extension/issues/18566#issuecomment-1518478913) shared was for Chrome.

> This was the precise solution he needed:
> 
> Settings -> Privacy and security -> Site settings -> Additional permissions -> HID devices -> Select "Sites can ask to connect to HID devices" -> Click on one of your displayed Ledger's -> Click 'Reset permissions' and make sure it displays "No HID devices found"


Firefox warning was changed as requested in #18570 

Closing this with the expectation that Firefox support is limited until the user either [enables U2F deep in their browser settings](https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-Firefox-Ledger-Integration-Issue?support=true), or until a time that Mozilla fully supports webHID.

**Closed by plasmacorral** 2023-05-11 16:40 UTC
Labels: type-bug, Sev2-normal, team-key-management

**Comment by ilya-bobyr** [comment] 2023-05-11 19:12
> Firefox warning was changed as requested in #18570
> 
> Closing this with the expectation that Firefox support is limited until the user either [enables U2F deep in their browser settings](https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-Firefox-Ledger-Integration-Issue?support=true), or until a time that Mozilla fully supports webHID.

Firefox wording seems more subtle than it could have been.

Cannot addon check if it is running in Firefox and the specific browser version?
In which case, it can use a much more explicit language.
Instead of saying `If you are Firefox you might be experiencing...` it can say `Your Ledger will not work, unless you do ...`.

I would imagine, most people do not read the "What's New" section, or would not necessarily remember it in a day or a week.
It would be better to show a warning when a Ledger transaction was not correctly signed, when on Firefox, on a certain version.
And have a checkbox, saying something like "I got it, do not show this again".

**Comment by kremalicious** [comment] 2023-05-20 19:09
> Closing this with the expectation that Firefox support is limited until the user either [enables U2F deep in their browser settings](https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-Firefox-Ledger-Integration-Issue?support=true), or until a time that Mozilla fully supports webHID.

Just a heads up that neither of those options will come true:

- Firefox v114 (currently in Nightly channel) has removed U2F altogether, making workaround obsolete
- whole WebHID spec is marked as "negative" by Mozilla so there won't be any WebHID implementation anytime soon in Firefox (for very good security concerns btw, which Google likes to simply ignore)

Using MetaMask and a Ledger with this version will result in this error message:

> RPC Error: U2F browser support is needed for Ledger. Please use Chrome, Opera or Firefox with a U2F extension. Also make sure you're on an HTTPS connection

<img width="1294" alt="Screenshot 2023-05-20 at 19 44 04" src="https://github.com/MetaMask/metamask-extension/assets/90316/ee072106-1113-4d6a-abb4-0221053c4dfe">

Tested with:
- Firefox v114.0b6
- MetaMask v10.30.4 (installed manually from file)
- macOS 13.4

As per Mozilla:

> The U2F/CTAP1 protocol is still supported, but only through WebAuthn
> https://bugzilla.mozilla.org/show_bug.cgi?id=1833231#c2

Regarding WebHID spec position:

> This API, like [WebUSB](https://mozilla.github.io/standards-positions/#webusb), provides access to generic devices. Though this API is limited to human interface devices (HID), the same concerns apply as WebUSB, namely that devices are generally not designed with access from arbitrary websites in their threat model.
> https://mozilla.github.io/standards-positions/

The [Ledger support article](https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-Firefox-Ledger-Integration-Issue) states at the end:

> The MetaMask team is actively investigating this issue and is working on a permanent solution.

I think it's safe to say Ledger has not been good with what and how they communicate in the past, so better double check in here:

- What is this permanent solution?
- Will it be implemented for stable release of Firefox v114?

As soon as Firefox v114 gets pushed out in stable channel this issue can be reopened again.

**Comment by dr4go** [comment] 2023-06-07 09:42
How comes that this issue has been closed? Do you seriously believe that this issue is "fixed" now by providing such a lousy workaround that doesn't even work anymore since yesterday (Firefox 114 is out now)?

**Comment by kremalicious** [comment] 2023-06-07 11:03
@plasmacorral this issue should be reopened now that Firefox v114 is released as stable and breaks Ledger support, see [my comment above](https://github.com/MetaMask/metamask-extension/issues/18566#issuecomment-1555974245).

**Comment by EoghanH** [comment] 2023-06-07 16:14
Confirming, Ledger is no longer usable with Firefox as of v114. No known workaround as WebHID is now fully removed.

**Comment by plasmacorral** [comment] 2023-06-08 20:38
The investigation on a viable solution is not over, but for the near term it is [recommended](https://github.com/MetaMask/metamask-extension/pull/19498) that Ledger users consider trying Chrome.  

Thank you all for confirming that this latest update has effectively disabled the Ledger and MetaMask integration for Firefox users.

**Comment by topynate** [comment] 2023-07-28 09:42
> The investigation on a viable solution is not over, but for the near term it is [recommended](https://github.com/MetaMask/metamask-extension/pull/19498) that Ledger users consider trying Chrome.
> 
> Thank you all for confirming that this latest update has effectively disabled the Ledger and MetaMask integration for Firefox users.

Are there plans to implement WebAuthn? As I understand it, Mozilla have no plans to implement WebHID, so U2F-over-WebAuthn will remain the only supported way to get hardware wallets working on Firefox for the forseeable future.

**Comment by CertainLach** [comment] 2023-08-09 16:06
I have developed a prototype of WebHID support for Firefox; maybe you folks might be interested:
https://github.com/CertainLach/hidfox

There are almost no docs, yet `make install` might just work. I might continue the development in my free time, if there is enough interest, but it works as-is for me right now.
Just do not try to use it on untrusted websites.

**Comment by Elliott-Green** [comment] 2023-09-29 16:45
I just want to say, this is a massive PITA.
