### ISSUE TITLE
[Bug]: Onboarding V2 - user is unable to navigate back from the create a password screen after closing and reopening MM

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#16959] opened 2022-12-14 20:19 UTC
### Describe the bug

https://user-images.githubusercontent.com/53189696/207702943-6fc0e05f-c7cf-42cc-aad5-6a4754704477.mov

The user cannot return to the onboarding welcome page, after reopening the extension (if the extension stays open the user can navigate back and forth at leisure switching between an imported wallet or wallet creation)

### Steps to reproduce

1. Install the extension with ONBOARDING_V2 enabled
2. Go through the onboarding step to the `Secure your wallet` page
3. Close the extension
4. Open the extension

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by digiwand** [comment] 2022-12-15 16:39
@adonesky1 I believe this was caused by the recent work merged yesterday
https://github.com/MetaMask/metamask-extension/pull/16916

**Comment by digiwand** [comment] 2022-12-15 16:39
I believe this was caused by the recent work merged yesterday https://github.com/MetaMask/metamask-extension/pull/16916 cc: @adonesky1

**Comment by adonesky1** [comment] 2022-12-16 18:02
I don't believe https://github.com/MetaMask/metamask-extension/pull/16916 would have impacted this. I may not be understanding correctly, but when the user closes the page, their browser level navigation history tied to that session is lost, so I wouldn't expect them to be able to navigate back on the browser level. @PeterYinusa are you able to that in the current (v1) onboarding flow? If we want to enable that we could add an in-app navigation so that the browser/session history doesn't prevent this. Or we could always send the user back to the beginning of the Onboarding flow if the page gets closed and reopened and they have not completed the entire flow. Thoughts @danjm @darkwing ?

**Comment by digiwand** [comment] 2022-12-16 18:42
oops, apologies for the assumption. Thanks for the added details @adonesky1

**Comment by WalletSupportt** [comment] 2022-12-19 13:39
> ### Describe the bug
> 
> 
> https://user-images.githubusercontent.com/53189696/207702943-6fc0e05f-c7cf-42cc-aad5-6a4754704477.mov
> 
> The user cannot return to the onboarding welcome page, after reopening the extension (if the extension stays open the user can navigate back and forth at leisure switching between an imported wallet or wallet creation)
> 
> ### Steps to reproduce
> 
> 1. Install the extension with ONBOARDING_V2 enabled
> 2. Go through the onboarding step to the `Secure your wallet` page
> 3. Close the extension
> 4. Open the extension
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.24.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by darkwing** [comment] 2022-12-19 19:01
My opinion is that this shouldn't block release; it's a very edge case that doesn't allow the user to lose anything.  Absolute worst case scenario would be needing to reinstall the extension.

**Comment by PeterYinusa** [comment] 2023-01-04 13:12
Just seeing the comments here.

I believe this is a blocker to the release. Happy to discuss it further.

Here's my assumptions:
1. I don't think the user should be able to navigate back after setting the password
2. When the password is set and the extension is closed and reopened, I think the user should land on `step 2 - secure your wallet` and NOT `step 1 - create a password` as they have already created a password and just used it to unlock the extension. **The new password the user enters will cause issues if its different from the one they used to unlock the extension**

If we choose to allow the user to navigate back and forth (we probably don't), then:
1. we should have some in-app navigation such as a back button or a link to toggle between flows but we will need to reset the state of onboarding

**Comment by adonesky1** [comment] 2023-01-04 16:19
I agree with Peter 👍

**Closed** 2023-01-09 20:55 UTC
Labels: type-bug, team-extension-client
