### ISSUE TITLE
Failed to execute 'getDevices' on 'HID': Access to the feature "hid" is disallowed by permissions policy.

### ISSUE THREAD

**Issue by snajjar** [MetaMask/metamask-extension#12257] opened 2021-09-30 21:26 UTC
**Describe the bug**
Can not connect Ledger device (up to date with the last firmware, contract data settings to "on" on ethereum app).

Getting the following message when trying to create a new hardware wallet from my ledger (or perform a transaction with the old one):

    Failed to execute 'getDevices' on 'HID': Access to the feature "hid" is disallowed by permissions policy.

**Steps to reproduce (REQUIRED)**

1. Update your ledger to the last firmware with ledger live
2. Open Ethereum app and set "Allow Contract Data" settings to "On" (Yes, again!)
3. Try to use Metamask with your ledger (create a new ledger wallet)

**Expected behavior**
Expected metamask to create a wallet from the ledger device, and to be able to perform transactions from it (on Ethereum, polygon or BSC blockchain)

**Screenshots**
![metamask-ledger-error](https://user-images.githubusercontent.com/1130216/135532408-4dc46244-ca96-43ab-99f4-811f3b0e5529.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: Ledger nano X firmware version 1.3.0
 - Browser: Brave 1.31.59
 - MetaMask Version: 10.1.1

**Additional context (Error Messages, etc.)**
MM worked fine until I updated the ledger firmware

**Comment by rsbowers** [comment] 2021-10-01 03:00
Having the same issue

**Comment by steamysocks** [comment] 2021-10-01 03:07
I am having the same Issue

**Comment by Guilhermegit-code** [comment] 2021-10-01 04:02
i was having the same issue after update my ledger, i can fix the problem activing use ledger live on metamask settings
![ledger active](https://user-images.githubusercontent.com/57755426/135563336-fe0526ab-582c-42d2-b503-fa9ceec0b890.PNG)

**Comment by Guilhermegit-code** [comment] 2021-10-01 04:02
the ledger live app will open you give acess to connect to metamask

**Comment by ojg1778** [comment] 2021-10-01 05:28
I have the exact same issue. What's the solution?

**Comment by Cryptome2** [comment] 2021-10-01 06:18
same issue from this morning.  It works with Ledger Live enabled, but it is buggy/cumbersome when you work with advanced passphrases on your ledger (2 sets of accounts).  The issue is that you can't close the bridge from MM to LL in a clean way to connect again. So the procedure in this case is: restart Ledger, stop LL, close all Chrome tabs, start chrome again,  connect MM again. I preferred to work with LL disabled.

**Comment by jkievit** [comment] 2021-10-01 08:12
In Metamask under Settings, Advanced, there is a switch "Use Ledger Live". Turning that on did the trick for me.

**Comment by Fabsbags** [comment] 2021-10-01 16:24
Having the same issue. Is there any update?

**Comment by Pi-Rr** [comment] 2021-10-01 17:32
Same here, and as per @Cryptome2 comment, I would much prefer not to have to use Leger Live connect.
I am having this issue with both Brave and Chrome, but Firefox is spare for now.

**Comment by mariozidov** [comment] 2021-10-01 18:00
Same for me... even on Egde browser.
I have a company laptop without admin rights so I can't even install LL. 
Ledger becomes useless in combination with Metamask

**Comment by ccie19125** [comment] 2021-10-01 19:03
Having the same issue!!  This was working just fine till about 24 hours ago.  No new updates to any software or my ledger, just stopped working.  Does not work in Chrome, but as mentioned Firefox is still working fine for now at least.  I also don't want to link through Ledger Live.

**Comment by marek22k** [comment] 2021-10-01 19:05
Same issue here. My Ledger App had an update (Ethereum and Binance Smart Chain). And when I remember correctly metamask had also an update.

**Comment by michaelmcquaid** [comment] 2021-10-01 19:12
Having the same issue as of this morning...

**Comment by gustavo2121** [comment] 2021-10-02 08:22
can sombody tell me what is the right metamask on Firefox? I saw one with less than 1500 users by danfinlay, kumavis. I guest this can't be real... what do you guys think please?

**Comment by 85256638** [comment] 2021-10-02 20:55
same issue, need update!

**Comment by STRIKEFOX** [comment] 2021-10-03 01:35
Another solution is has Metamask install in Firefox ... I have the same problem but, since yesterday I have beeng using Firefox without any problem. And yes ... For 3 days it seemed that it was necessary to have the ledger live option activated to be able to work with chrome

**Comment by danjm** [comment] 2021-10-04 09:54
We believe this was fixed. Is anyone still experiencing this issue?

**Comment by Pi-Rr** [comment] 2021-10-04 11:15
Works for me now, thanks!

**Comment by yannick10800** [comment] 2021-10-04 11:31
Hi
it worked using with " ledger live bypass " this weekend but it is not working anymore now...................

**Comment by darkwing** [comment] 2021-10-06 18:26
This has been confirmed fixed, so closing for now.

**Closed by darkwing** 2021-10-06 18:26 UTC

**Comment by tradersnow222** [comment] 2023-05-08 16:21
Getting this exact same error again today, with MM Brave extension + Ledger Nano X. 
@danjm @darkwing
