### ISSUE TITLE
Cant send transations since "warning" appeared, yesterday

### ISSUE THREAD

**Issue by Icebergx** [MetaMask/metamask-extension#3376] opened 2018-03-01 14:43 UTC
Hi,

Yesterday, I mistakenly sent Eth to an old contract address. Luckily this was rejected, and I then managed to send Eth to the correct Eth address straight after. In the MM window, a "warning" message appeared, but I didn't think anything of it, and all my Eth was still in my wallet, as expected.

Today, I tried to send Eth to an ICO twice, with 40gwei, and neither transation went through. In fact, neither transaction is even visible on Etherscan. In my MM widow, they too have "warning" next to them too!
(Please see screenshot)
<img width="365" alt="screen shot 2018-03-01 at 14 27 09" src="https://user-images.githubusercontent.com/8325148/36850361-75b714a4-1d5e-11e8-8b76-a02f9fa56fbb.png">

To send the Eth to the ICO, I had to log-in to MEW with my private key... Not ideal.

I tried to log out of MM and restarted my computer and just logged back in. The three "warning" transactions (one from yesterday and two from today) are still there, and when I try to log into IDEX, IDEX says that MetaMask isn't installed.
<img width="701" alt="screen shot 2018-03-01 at 14 55 51" src="https://user-images.githubusercontent.com/8325148/36851258-bfa94292-1d60-11e8-810b-ef01178e4fee.png">

Browser:Chrome
OS: Mac OSX 10.10

Any help would be appreciated.

Rak.

**Comment by danfinlay** [comment] 2018-03-02 18:20
Closing as duplicate of #3357. Idex should fix this on their end, but we'll also try to fix it on ours.

**Closed by danfinlay** 2018-03-02 18:20 UTC
