### ISSUE TITLE
update Trezor Connect

### ISSUE THREAD

**Issue by MoneyOnChain** [MetaMask/metamask-extension#8972] opened 2020-07-12 13:23 UTC
The current version of firmware (2.3.1) may be not compatible with the running version of Trezor Connect.
The current version of firmware contains major changes that could affect the efficient functionality of Trezor Connect.

If you’re experiencing any issue as a user, please contact the owner of chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn.
If you are a developer of chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn please, update Trezor Connect to the newest version.

**Comment by tmashuang** [comment] 2020-07-12 13:25
Closing as this a duplicate of #8349

**Closed** 2020-07-12 13:26 UTC
