### ISSUE TITLE
meta mask has error when change from account 1 to 2 

### ISSUE THREAD

**Issue by Yazanalsharif** [MetaMask/metamask-extension#9066] opened 2020-07-23 17:22 UTC
HELLO GUYS 

after the last update of meta mask , it had become displays some error when i change between accounts 
the meta mask connected with dapp on localhost i made it and when i change the accounts its displays this errors
inpage.js:1 Uncaught TypeError: Cannot read property 'subscription' of undefined 

GET chrome-extension://invalid/ net::ERR_FAILED
GET chrome-extension://invalid/ net::ERR_FAILED

**Comment by brad-decker** [comment] 2020-07-23 17:50
Hey, @Yazanalsharif thanks for the issue report. This is a duplicate of #9013 which will be resolved in the next release of MetaMask! Going to close this, but if the issue persists after the release we'll reopen the original issue for tracking. Thanks again for your report!

**Closed by brad-decker** 2020-07-23 17:50 UTC
