### ISSUE TITLE
Reseting account with custom RPC selected doesn't work.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#4499] opened 2018-06-05 12:30 UTC
1. Setup Custom RPC pointing to a local node.
1. Go into settings and Reset Account.
1. Wait for a while before realizing that nothing is happening.
1. Click outside of the reset box to make it go away.
1. Scroll up.
1. --> Notice the following error:
![image](https://user-images.githubusercontent.com/886059/40975982-3e42cf62-68ff-11e8-91d9-e794a5ea6308.png)

**Comment by bdresser** [comment] 2018-06-05 16:35
@MicahZoltu thanks for reporting. this is a dupe of #4462, closing this and added your comment there 👍

**Closed by bdresser** 2018-06-05 16:35 UTC
