### ISSUE TITLE
wallet showing zero balance, when connected web3 apps and etherscan show positive balances

### ISSUE THREAD

**Issue by aklitzke** [MetaMask/metamask-extension#9512] opened 2020-10-08 12:39 UTC
![image](https://user-images.githubusercontent.com/6123576/95459217-f1886b00-0938-11eb-9253-cce815fc05d9.png)

![image](https://user-images.githubusercontent.com/6123576/95459253-02d17780-0939-11eb-97ef-b18a29f039b3.png)

This started occurring immediately following import of the wallet using a seed phrase.

**Expected behavior**
Correct ethereum and ERC20 token balance appears

**Browser details (please complete the following information):**
 - OSX Mojave 10.14.6
 - Chrome Version 85.0.4183.121 (Official Build) (64-bit)
 - MetaMask Version 8.0.10

EDIT: [Etherscan link](https://etherscan.io/address/0x738c701bed8b9b4d2c704e381e231377b8dea78d)

**Comment by gfmartinez** [comment] 2020-10-30 14:42
@aklitzke Any solution on this?
I have the same issue, except that metamask shows the activity coming into my wallet, but the balance still shows 0

**Comment by gfmartinez** [comment] 2020-11-03 16:59
@aklitzke I was able to solve this for my scenario. I hope this helps for you...

First, I made sure to sync my chrome extension with my mobile app. 
The mobile app showed the balance.
So, I knew it must be an issue with the extension.
Removed the extension from Chrome.
Quite chrome.
Restarted chrome.
Reinstalled Metamask extension
Had to import wallet using seed phrase.
Then metamask showed two accounts: one had balance with same wallet address as mobile app, second had no balance.
Delete zero balance account.
Now all up and running.

**Comment by Gudahtt** [comment] 2021-01-13 22:33
Thanks for the report! Can this still be reproduced on the latest version of MetaMask?

**Comment by NicolasMassart** [comment] 2021-01-29 17:25
On version 9.0.3 it's happening on my mac/chrome yes.

**Comment by Gudahtt** [comment] 2021-01-29 17:29
Thanks for the update @NicolasMassart !

Unfortunately we've been unable to reproduce this issue. I would help a great deal in diagnosing this if you were to [submit a support request with state logs](https://metamask.zendesk.com/hc/en-us/requests/new), and [check your background logs for any error messages](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue).

**Comment by NicolasMassart** [comment] 2021-01-30 00:07
It looked to be an issue on derivation path used in previous versions of MM and it may not be enough to update.
I removed and installed the extension again and it was able to load the Ledger accounts.

**Comment by Zsmith32** [comment] 2021-03-25 02:04
Hi this is happening to me as well:

I first created the wallet on Brave. Synced with mobile. Then made my first transactions. The balance still shows correctly on my mobile app: Android 11, metamask V 1.0.11 (46)

[Etherscan link](https://etherscan.io/address/0xbd4b9a29a113e2e6d601adf0d2af345ce3cedd13)

Browser details (please complete the following information):

![image](https://user-images.githubusercontent.com/7588701/112407353-f0c77380-8ce3-11eb-876f-c7a38bd1016f.png)
![image](https://user-images.githubusercontent.com/7588701/112407390-02108000-8ce4-11eb-9dca-6c48fb05d656.png)
![image](https://user-images.githubusercontent.com/7588701/112407415-0d63ab80-8ce4-11eb-8845-5b17a88c66bb.png)

**Comment by dpazdan** [comment] 2021-09-01 18:26
No reports of this issue since 9.2 - closing due to length of time without updates unless someone reports it still exists.

**Closed by dpazdan** 2021-09-01 18:26 UTC
Labels: type-bug, needs-reproduction, Sev2-normal
