### ISSUE TITLE
No option for hardware connection

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [MetaMask/metamask-extension#7743] opened 2020-01-03 10:05 UTC
**Describe the bug**
Installed the matamask extention. When I click it it there is no option popping up but a new page with a "Get started" button. When I click "get started" I'm leading to a page where there are only two options 1. Import seeds  2. Create wallets.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

Install metamask
metamask icon
3. See error 
No option for hardware connection

**Expected behavior**
A hardware connection option.

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows] 
Linux

 - Browser [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
Chrome
 - MetaMask Version [e.g. 5.0.2]
Latest on Jan 3. 2020.

**Comment by tmashuang** [comment] 2020-01-03 20:04
Duplicate of #6466.

**Closed by tmashuang** 2020-01-03 20:04 UTC

**Comment by Rakaunui-1111** [comment] 2024-03-15 19:19
that was not helpful at all.
