### ISSUE TITLE
[Bug]: Chrome console error related to lockdown-run.js and lockdown-more.js

### ISSUE THREAD

**Issue by unsiu** [MetaMask/metamask-extension#20847] opened 2023-09-13 02:19 UTC
### Describe the bug

<img width="1728" alt="CleanShot 2023-09-13 at 10 12 10@2x" src="https://github.com/MetaMask/metamask-extension/assets/142329514/68b77b8d-d1bd-44c3-8384-b35e8facdd8c">

- lockdown-run.js:17
Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
  at isAllowedPropertyValue (lockdown-install.js:1:53384)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at isAllowedPropertyValue (lockdown-install.js:1:53041)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at lockdown-install.js:1:55523
  at repairIntrinsics (lockdown-install.js:1:144597)
  at lockdown-install.js:1:145462
  at lockdown-run.js:4:3

- lockdown-more.js:99
lockdown-more.js:99 Protecting intrinsics failed: ReferenceError: harden is not defined
  at lockdown-more.js:69:13
  at Set.forEach (<anonymous>)
  at protectIntrinsics (lockdown-more.js:44:22)
  at lockdown-more.js:97:5

### Steps to reproduce

When I turn on the MetaMask extension and open any web page, an error appears in the console.
These errors disappear when MetaMask is disabled.

### Version

11.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment] 2023-09-13 09:47
Hello, @unsiu. Thanks for reporting! Do you have other crypto wallets and extensions in the browser? Did this start occurring when updating the extension? Thank you!

**Comment by unsiu** [comment] 2023-09-13 12:04
> Hello, @unsiu. Thanks for reporting! Do you have other crypto wallets and extensions in the browser? Did this start occurring when updating the extension? Thank you!

I only have this one cryptocurrency related extension. These errors were reported with the last version (v10.35.1).

**Comment by x1ongzhu** [comment] 2023-09-14 03:25
I'm facing the same error on macos.
Chrome version: 117.0.5938.62
Extension version: 11.0.0

**Comment by krasezzza** [comment] 2023-09-14 10:34
The same issue on my machine.
OS: Windows 11 Pro;
Chrome version: 117.0.5938.62
Extension version: 11.0.0

**Comment by RAMTO** [comment] 2023-09-14 10:38
Same here

**Comment by ochikov** [comment] 2023-09-14 10:42
Same here:
OS: Mac OS Monterey 12.6.1 (21G217)
Chrome version: 116.0.5845.110
Extension version: 11.0.0

**Comment by fditrapani** [comment] 2023-09-14 11:39
Same here:
MAC OS: 13.5.2
Chrome: 117.0.5938.62
Extension version: 11.0

**Comment by huytq03** [comment] 2023-09-14 13:51
same here

**Comment by SandiRizqi1503** [comment] 2023-09-14 14:05
I just solved this issue by Uninstall Metamask and VPN Google Chrome plugin

**Comment by thomasbeckford** [comment] 2023-09-14 14:11
Same here

**Comment by krasezzza** [comment] 2023-09-14 14:12
> I just solved this issue by Uninstall Metamask and VPN Google Chrome plugin

How do you use MetaMask wallet interactions in a dApp then?

**Comment by co1incasey** [comment] 2023-09-14 20:48
It's coming from Metamask. Disable the extension and the errors will go away.

**Comment by githubarj** [comment] 2023-09-14 20:53
same getting the error too

**Comment by colinjcasey** [comment] 2023-09-15 02:48
> > I just solved this issue by Uninstall Metamask and VPN Google Chrome plugin
> 
> How do you use MetaMask wallet interactions in a dApp then?

How is it so difficult for you to understand that this is an issue with MetaMask? You giving responses thumbs down because the helpful responses don't answer your noob question of "h0w Do U uze metamask..." is worthy of public humiliation. If you're such a poor web3 developer that you don't have other wallet extensions, well, then it's clear Darwin's survival of the fittest has made it to the digital realm.

**Comment by rick-liruixin** [comment] 2023-09-15 05:43
same getting the error too 
![image](https://github.com/MetaMask/metamask-extension/assets/50647350/4b737eeb-d064-4424-b7ba-2ff929341395)

**Comment by francesco-gaglione** [comment] 2023-09-15 06:05
> > > I just solved this issue by Uninstall Metamask and VPN Google Chrome plugin
> > 
> > 
> > How do you use MetaMask wallet interactions in a dApp then?
> 
> How is it so difficult for you to understand that this is an issue with MetaMask? You giving responses thumbs down because the helpful responses don't answer your noob question of "h0w Do U uze metamask..." is worthy of public humiliation. If you're such a poor web3 developer that you don't have other wallet extensions, well, then it's clear Darwin's survival of the fittest has made it to the digital realm.

I agree with you that perhaps there are many other alternatives to at least continue to develop. And I agree that the question posed that way makes no sense at all. But it's not exactly as you say. There are situations in which there are non-technical limitations for which one is forced from the outside to use a certain wallet. And therefore the problem must be solved in all cases. I don't change my car every time it runs out of petrol, I solve the problem by refueling. So if this is a problem with the metamask extension and does not depend on factors external to metamask this issue should be resolved. There are products in production that can only use metamasks and cannot find themselves unable to connect the wallet overnight. And I'm in a similar case



.....so if any maintainers or contributors read this, please let us know if we can provide you with additional information about the bug to analyze and resolve it asap.

**Comment by csmartinsfct** [comment] 2023-09-15 08:05
I just upgraded chrome to 117.0.5938.62 and started seeing this error as well, wasn't there before (unsure what version I was on tbf).

**Comment by krasezzza** [comment] 2023-09-15 08:09
> I just upgraded chrome to 117.0.5938.62 and started seeing this error as well, wasn't there before (unsure what version I was on tbf).

It seems to be an issue between Chrome and MetaMask because I notice the same behavior after browser version update.

**Comment by WebDevTalha** [comment] 2023-09-15 09:48
Hello, In my Dapp everything was working fine so far but when I added the web3js package to my dapp to make my contract read function work, it kept showing the same error in my console, so I want to know if there will be any problem with my dapp due to this error? Should I ignore this error?

**Comment by anaamolnar** [comment] 2023-09-15 10:40
Hey @danjm. Could you please take a look? Thanks!

**Comment by mattimatt** [comment] 2023-09-15 13:17
Yup just removed meta mask and error goes away. For me it also appeared after updating chrome.

**Comment by lucaslee129** [comment] 2023-09-15 15:22
I have the same problem and it came up just before. What is the reason and what is the solution?

**Comment by d1v1ng1sC00l** [comment] 2023-09-15 16:18
Me too. Error on Brave and Chrome.

**Comment by FranRom** [comment] 2023-09-15 16:19
Same here

**Comment by mujtabashamas** [comment] 2023-09-15 18:20
same came after updated chrome.

**Comment by tadpole2077** [comment] 2023-09-15 19:35
Details relating to metamask lockdown.js issue and root cause on stackoverflow : https://stackoverflow.com/questions/76393186/what-is-causing-the-warning-removing-intrinsics-arrayprototype-toreversed-in

Its the anti-pershing detect feature on metamask (v10.31.1), that isnt aligned with latest ES2023 prototypes, so all those new native methods throw warnings with MetaMask 10.31.1

Seems to be resolved with MetaMask 11.0.0

**Comment by tadpole2077** [comment] 2023-09-15 19:40
> Details relating to metamask lockdown.js issue and root cause on stackoverflow : https://stackoverflow.com/questions/76393186/what-is-causing-the-warning-removing-intrinsics-arrayprototype-toreversed-in
> 
> Its the anti-pershing detect feature on metamask (v10.31.1), that isnt aligned with latest ES2023 prototypes, so all those new native methods throw warnings with MetaMask 10.31.1
> 
> Seems to be resolved with MetaMask 11.0.0

Those warning are going to occur with Chrome 110 and higher (latest version is 116)  and MetaMask 10.31.1 , 110 is when ES2023 support/compatibility was activated.

**Comment by federicosan** [comment] 2023-09-15 21:23
@weizman please look into this as you resolved an issue that is mentioned here I think this two may be related.

**Comment by federicosan** [comment] 2023-09-16 04:56
Chrome update 117.0.5938.88 for desktop and the errors persist, should I be worried using metamask?

**Comment by roudra323** [comment] 2023-09-16 08:09
Facing the same issue.
Browser - > Brave (1.58.124) -> Chromium (117.0.5938.62)
MetaMask -> 11.0.0
Windows -> 11

**Comment by bytemtek** [comment] 2023-09-16 09:19
Same here +1

**Comment by prajun7** [comment] 2023-09-16 14:51
Was getting the same error. My fix was to disable the MeteMask Wallet and a VPN extension.

**Comment by federicosan** [comment] 2023-09-16 19:46
No error on Version 11.0.0 
on Brave [Version 1.58.124 Chromium: 117.0.5938.62 (Official Build) (x86_64)

**Comment by kevinghim** [comment] 2023-09-16 22:59
This issue will be fixed through https://github.com/MetaMask/metamask-extension/pull/20877

**Comment by abdulmabud** [comment] 2023-09-17 05:44
Disable metamask extension

**Comment by federicosan** [comment] 2023-09-17 07:30
> This issue will be fixed through #20877

take into account that this is saying the the error does not show on locked wallets and that is not the case for many, it is appearing even when locked.

**Comment by danjm** [comment] 2023-09-17 09:04
> take into account that this is saying the the error does not show on locked wallets and that is not the case for many, it is appearing even when locked.

@federicosan Where does it say the error "does not show on locked wallets "?

**Comment by alejandroch1202** [comment] 2023-09-17 17:09
Same here

**Comment by federicosan** [comment] 2023-09-17 20:33
> > take into account that this is saying the the error does not show on locked wallets and that is not the case for many, it is appearing even when locked.
> 
> @federicosan Where does it say the error "does not show on locked wallets "?

Sorry for the confussion I linked to the wrong issue, I was talking about issue https://github.com/thirdweb-dev/dashboard/issues/1680  posted above that one.

**Comment by hadarhubara10** [comment] 2023-09-18 12:36
Same here

**Comment by michyaraque** [comment] 2023-09-18 12:58
Facing the same issue

- Browser: Microsoft Edge (117.0.2045.31) (64 bits)
- MetaMask version: 11.0.0
- SO: Windows 11

**Comment by manazpr** [comment] 2023-09-18 22:26
I'm facing the same issue.

**Comment by tamoimi** [comment] 2023-09-19 00:59
Same here, just disabled metamask extension and the error disappeared

**Comment by nashidahmed** [comment] 2023-09-19 01:33
Same here

**Comment by DorianPRO-S** [comment] 2023-09-19 06:11
I turned off MetaMask extension to chrome and the error gone.

**Comment by nephcode** [comment] 2023-09-19 14:08
Same bug ... 0day ?

**Comment by kosso** [comment] 2023-09-19 14:49
Same issue. 
Version 11.0.0 

Seems to have just started appearing in my console after a recent Chrome update.

**Comment by zanniboni** [comment] 2023-09-19 23:34
Same issue here

**Comment by ThiLourenco** [comment] 2023-09-20 01:36
same issue.

Ubuntu 22.04.3
Chrome Version 117.0.5938.88
MetaMask version 11.0.0

**Comment by sonnh58** [comment] 2023-09-20 02:29
same issue

**Comment by comadaihiep92** [comment] 2023-09-20 07:22
same issue on mac

**Comment by adriensoulie** [comment] 2023-09-20 07:24
same issue on mac, disabling metamask made it work, however there was no link between my project and metamask

**Comment by MHHui00** [comment] 2023-09-20 07:59
Same issue on mac

Edge Version 117.0.2045.31 
MacOS Ventura 13.5
MetaMask 11.0.0

**Comment by Kiki-Q** [comment] 2023-09-20 08:23
how to solve this problem?

**Comment by luckywangming** [comment] 2023-09-20 08:32
Same here +1

**Comment by arash-hk** [comment] 2023-09-20 08:59
still not solutions?

**Comment by wongprom** [comment] 2023-09-20 09:43
Same for me

- MacOS Ventura 13.5.1 
- Chrome  117.0.5938.88
- Metamask 11.0

**Comment by Sylphritz** [comment] 2023-09-20 14:32
Been getting the same error on Mac OS Ventura and Windows 10 for the past few days. Both are updated to their latest version.

**Comment by jemiks** [comment] 2023-09-20 16:23
In my case after disabling the Metamask extension, that was fixed

**Comment by Kashterion** [comment] 2023-09-20 20:57
Same issue here.

Ubuntu: 22.04
Chrome: Version 117.0.5938.88 (Official Build) (64-bit)
Metamask: 11.0.0

**Comment by 0xGuybrush** [comment] 2023-09-20 21:16
From [Kevin's comment up-thread](https://github.com/MetaMask/metamask-extension/issues/20847#issuecomment-1722335396), it looks like the Metamask team have already identified the root cause and have a fix working its way through PR. It's tagged now as on the critical path of the next release.

(I appreciate the irony of a "reply-all" comment asking to stop the "reply-alls", but...), it'd be great if people could please hold off on the "same here" replies, as it makes it harder to spot real updates to the ticket 🙏

**Comment by zavg** [comment] 2023-09-20 22:48
Same issue
Version 117.0.5938.88 (Official Build) (arm64)

**Comment by hongshu7** [comment] 2023-09-21 07:14
Facing the same issue

Browser: Chrome Version 117.0.5938.88 (arm64)
MetaMask version: 11.0.0
OS: MacOS 15

**Comment by mr-possible** [comment] 2023-09-21 13:45
> I just solved this issue by Uninstall Metamask and VPN Google Chrome plugin

This solved the issue for me! Thanks. I anyways don't like to use metamask. I prefer Ganache. I would recommend the same.

**Comment by Bobby-iv** [comment] 2023-09-22 14:23
![Screenshot from 2023-09-22 17-21-28](https://github.com/MetaMask/metamask-extension/assets/145783031/9ff1bd58-3948-4eed-9b1b-599f0e2a1f68)
Same problem here. 
OS: Ubuntu 22.04
Browser: Chrome 117.0.5938.62
website: https://jackpotinsight.com/

**Comment by sntgchns** [comment] 2023-09-22 22:39
same here, on microsoft edge latest version Windows 11 Pro. Problem with MetaMask extension

**Comment by henrygagnier** [comment] 2023-09-23 00:49
I am experiencing this issue on Edge. I am a web developer testing an application, so "fixes" for this issue do not help. I would like this fixed for my users rather than just myself so uninstalling and reinstalling does not fix that for everyone.
![image](https://github.com/MetaMask/metamask-extension/assets/101131194/13f4e9aa-d8a5-496f-9230-485da6b3cd96)

**Comment by bytrislasis** [comment] 2023-09-23 18:48
I'm having the same problem and it's very annoying.

**Comment by PedroReyes** [comment] 2023-09-23 20:55
Hello,

Experiencing the same issue on my side too. Leave here details, let me know if you need more:

![image](https://github.com/MetaMask/metamask-extension/assets/4096108/2fb29322-7a12-408e-aa9b-4e131b460f1e)

![image](https://github.com/MetaMask/metamask-extension/assets/4096108/08d29b16-b243-4a52-a647-c2efa7713db3)

Best regards,
Pedro Reyes.

**Comment by robinpunn** [comment] 2023-09-23 23:26
I'm having the same issues as the screenshots shared above using Brave. I can still connect to dapps, that isn't really an issue. The console just shows the 'Lockdown failed' error. 

My problem is more with the Ethernaut challenge. When I log in with the wallet I've been using, all my progress is gone, and I can't start any challenges. If I switch wallet addresses, I still can't start any challenges. 

When I switch to Chrome, I still get "Lockdown failed" on the console. But I have all my progress from Ethernaut, and I'm able to start new challenges.

**Comment by cyberpunketh** [comment] 2023-09-24 11:11
> > > I just solved this issue by Uninstall Metamask and VPN Google Chrome plugin
> > 
> > 
> > How do you use MetaMask wallet interactions in a dApp then?
> 
> How is it so difficult for you to understand that this is an issue with MetaMask? You giving responses thumbs down because the helpful responses don't answer your noob question of "h0w Do U uze metamask..." is worthy of public humiliation. If you're such a poor web3 developer that you don't have other wallet extensions, well, then it's clear Darwin's survival of the fittest has made it to the digital realm.

It is indeed an issue with metamask.  This is the metamask repo.  That's why it's reported here as an issue. It's fair to assume people here are interested in making metamask work. Maybe that's why people are not fully satisfied with the solution "remove metamask".  Your comment isn't very illuminating and neither does it particularly elevate the discourse, I think the thread would be better off without it.

As for "survival of the fittest", I wonder how not understanding the context of the issues you land on after a google search for your error message and barging into the conversation adding nothing and antagonizing the participants is a good fit for your problem space, but then again, I don't need to know, you'll swim or you'll sink, and I don't think anybody is going to miss you when you sink.

**Comment by federicosan** [comment] 2023-09-24 22:02
The fix for this has been merged here https://github.com/MetaMask/metamask-extension/pull/20877 and ready for the next release so it seems this issue can be closed now.

**Comment by atsoc1993** [comment] 2023-09-25 01:13
Just uninstalled metamask-- no errors-- not sure if updating helps as well but I don't really use metamask extension anyways.

**Comment by leoxyKing** [comment] 2023-09-25 07:03
Same problem, 
Google version 117.0.5938.92 
Microsoft Edge  117.0.2045.41

**Comment by ajays97** [comment] 2023-09-25 19:57
is the issue update released? I am facing the same error too.

OS: Pop!_OS 22.04 LTS
Chrome Version 117.0.5938.92
Extension version: 11.0.0

**Comment by FrederikBolding** [comment] 2023-09-25 20:53
This will be fixed in an upcoming release of MetaMask (v11.1.0). 

**For now, this error can be safely ignored and should not prevent you from running MetaMask.**

**Comment by sadeeqdev** [comment] 2023-09-26 17:39
> I just upgraded chrome to 117.0.5938.62 and started seeing this error as well, wasn't there before (unsure what version I was on tbf). MetaMask still seems to work though.

I also noticed the error after updating google chrome

**Comment by nicszerman** [comment] 2023-09-26 17:55
Same

**Comment by tharindunishal** [comment] 2023-09-27 06:38
Disable temporarily Metamask extension and it will be ok

**Comment by ilocxdev** [comment] 2023-09-28 05:30
Yup.
Uninstall Metamask, then error will be gone.

**Comment by levi0214** [comment] 2023-09-28 10:20
Same error, but wallet still works.

**Comment by top-comengineer** [comment] 2023-09-30 06:20
> This will be fixed in an upcoming release of MetaMask (v11.1.0).
> 
> **For now, this error can be safely ignored and should not prevent you from running MetaMask.**

I am also facing the same issue.
Thank you for your clarification, @FrederikBolding 
Could you let me know when will be probably the upcoming release time of the Metamask?
Thanks again.

**Comment by omarabid** [comment] 2023-10-02 10:10
Bumping this. The wallet functions fine but this pollutes the console + any debugging/tracing tool you have out there.

**Comment by Fikunmi01** [comment] 2023-10-03 11:19
> I just solved this issue by Uninstall Metamask and VPN Google Chrome plugin

Thanks bro you just saved me from stressing much haha

**Comment by dankelleher** [comment] 2023-10-03 11:26
About one in ten sites are currently broken for me because of this. Removing metamask fixes them.

**Comment by hacenbarb** [comment] 2023-10-03 13:58
I'm facing the same issue

**Comment by Hiker-Hope** [comment] 2023-10-03 15:36
Same 🙃

**Comment by samyan** [comment] 2023-10-03 19:58
same here. I've Metamask plugin.

**Comment by eriksonlizandro** [comment] 2023-10-03 21:21
No need to remove Metamask just do this
![Screen Shot 2023-10-03 at 3 18 41 PM](https://github.com/MetaMask/metamask-extension/assets/48691408/a5950e0a-e4ac-4567-abcf-c45cf8d4d7c9)

**Comment by etsraphael** [comment] 2023-10-04 10:13
Same issue here, the only trick right now is to disable it. But that's not even a solution.

**Comment by karlwerxz** [comment] 2023-10-06 06:23
uninstalled metamask :)

**Comment by FrandeSUG** [comment] 2023-10-06 06:44
Same Hereだよもう

**Comment by aiiiden** [comment] 2023-10-06 10:35
Same issue here

**Comment by ennioVisco** [comment] 2023-10-06 10:38
For gods sake don't post new comments if you have nothing relevant to add.
Just subscribe to the issue, if you want, react to previous comments, and then wait for updates from the devs, instead of triggering notifications to hundreds of people for just saying "me too".

**Comment by elliotWoas** [comment] 2023-10-06 17:24
Thanks for the report. I had the same problem, I reinstalled Metamask with a VPN to fix the bug

**Comment by PRChain** [comment] 2023-10-10 11:54
Get the same error,  always use a VPN.
![image](https://github.com/MetaMask/metamask-extension/assets/35719581/b8a278f7-e14f-4041-9b8a-bc1b9e2788a0)

**Comment by moazzamgodil** [comment] 2023-10-10 13:16
I think the issue is fixed. I recently updated to version 11.1.2, and now there are no more error logs, so everything seems to be working fine.

**Comment by Muurtaja** [comment] 2023-10-12 07:31
The issue has been resolved in version 11.1.2. Thank you all for your assistance!

This issue can now be considered closed.

**Closed** 2023-10-13 05:36 UTC
Labels: type-bug, Sev2-normal, team-extension-platform

**Comment by GimpMaster** [comment] 2023-10-26 04:49
Looks like the Edge (chrome) extension hasn't been up dated in the store yet. That is currently at 11.0.0

![image](https://github.com/MetaMask/metamask-extension/assets/7818200/7417e933-a145-420b-a330-ba68bfc8f46a)

**Comment by vunh195** [comment] 2023-10-29 05:12
same

**Comment by vunh195** [comment] 2023-10-29 05:12
> Looks like the Edge (chrome) extension hasn't been up dated in the store yet. That is currently at 11.0.0
> 
> ![image](https://user-images.githubusercontent.com/7818200/278214955-7417e933-a145-420b-a330-ba68bfc8f46a.png)

same

**Comment by rheza** [comment] 2024-01-21 10:19
what is my options now ?, I cant access my wallet.

**Comment by nazar-pc** [comment] 2024-01-27 03:19
Still happening with 11.7.3 version of extension in Chromium 123.0.6267.0 (nightly). Metamask is not loading, making it useless.

**Comment by yahdielo** [comment] 2024-12-12 18:57
it says it solve, but im having the same problems updated chrome and metamask and still getting this
