### ISSUE TITLE
[Bug]: User cannot see all the connected account permissions for Snaps

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#20903] opened 2023-09-15 11:43 UTC
### Describe the bug

Cannot see the full name of the following snaps:
@shapeshiftoss/metamask-snaps
btcsnap

<img width="1480" alt="Snap connected accounts permissions" src="https://github.com/MetaMask/metamask-extension/assets/53189696/a6abcc11-835c-41f2-bfde-bc43f702fa7b">

### Steps to reproduce

1. Log in to the extension
2. navigate to snaps.metamask.io
3. install the following snaps (wallet-guard-snap, @tenderly/metamask-snap, @shapeshiftoss/metamask-snaps and btcsnap)
4. open the MM popup
5. click the connected site's icon
6. expand the Permissions drop down

### Version

11.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Montoya** [comment] 2023-09-15 12:33
This is a duplicate of #20405

**Closed** 2023-09-15 13:47 UTC
Labels: type-bug, regression-RC, team-snaps, release-11.1.0
