### ISSUE TITLE
metemask-extension crash

### ISSUE THREAD

**Issue by maiiz** [MetaMask/metamask-extension#4890] opened 2018-07-26 11:22 UTC
my metamaks always crash when open

![image](https://user-images.githubusercontent.com/6994201/43258748-62e91eaa-9106-11e8-8a32-fcf3d875a514.png)

**Comment by Maayu2415** [comment] 2018-07-26 11:33
Thank you my friend.where are you?


ในวันที่ พฤ. 26 ก.ค. 2018 18:23 maiiz <notifications@github.com> เขียนว่า:

**Comment by bdresser** [comment] 2018-07-26 14:53
@maiiz what browser, browser version, and operating system are you using?

**Comment by xiaoxiaoleo** [comment] 2018-07-31 06:28
Same issue, 
Chrome :  67.0.3396.99 32bit
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134

**Comment by bdresser** [comment] 2018-08-03 21:44
@xiaoxiaoleo "Crash" as in the extension closes entirely and you get a Chrome notification? or are you seeing a blank screen?

@maiiz what makes you think this might be caused by a large number of transactions? 

and if either of you are able to open the popup or background logs, any errors you see would be super helpful. Read how [here](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue).

**Comment by xiaoxiaoleo** [comment] 2018-08-04 03:12
@bdresser As you said, a Chrome notification pop up and I need to reload MetaMask extension.

**Comment by gussulliman** [comment] 2018-08-06 01:12
im having same issue, and when reloading, crashes again with about 1 minute. 
chrome: 67.0.3396.99 (64-bit)
os name: MacOS high sierra
os version: 10.13.5 (17F77)

shows this upon crashing: 
![image](https://user-images.githubusercontent.com/32939482/43692258-cce38106-9958-11e8-9750-dfb91bdf6eb2.png)

If opened before crashing seems to have no issue, although have not tried to send a tx in that short time.

**Comment by bdresser** [comment] 2018-08-06 15:50
thanks for the detail @xiaoxiaoleo @gussulliman 

Anything you're able to see in the UI console or background console will be would be helpful to debug on our side. Instructions on how to see the logs are [here](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue).

**Comment by xiaoxiaoleo** [comment] 2018-08-06 16:26
Hi, i got something from UI console:
`ui.js:1 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
(anonymous) @ ui.js:1
ui.js:1 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.
n.default @ ui.js:1
ui.js:1 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
(anonymous) @ ui.js:1
ui.js:1 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
(anonymous) @ ui.js:1
ui.js:1 Setting up Sentry Remote Error Reporting: PROD
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/fonts/Montserrat/Montserrat-Regular.ttf
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/fonts/fonts/fontawesome-webfont.woff2?v=4.4.0
`

**Comment by whymarrh** [comment] 2019-02-07 01:46
@maiiz @xiaoxiaoleo @gussulliman can any of you reproduce this/are any of you experiencing this on the latest MetaMask?

**Comment by bdresser** [comment] 2019-02-12 21:32
closing - please let us know if you're still experiencing this issue!

**Closed by bdresser** 2019-02-12 21:32 UTC
Labels: N02-needsReproduction, T00-bug
