### ISSUE TITLE
Update knobs to controls in storybook: MetamaskTemplateRenderer

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18498] opened 2023-04-06 23:36 UTC
### Description
Currently there are a few storybook stories still using knobs in our storybook files `*.stories.js`. knobs have been deprecated in favour of controls. It would be great to migrate these last stories from knobs to controls.

This issue is to migrate the `ui/components/app/metamask-template-renderer/metamask-template-renderer.stories.js` from knobs to controls

<img width="1440" alt="Screenshot 2023-04-06 at 4 34 17 PM" src="https://user-images.githubusercontent.com/8112138/230512403-cafaaa5c-2c2e-4906-b026-12b52cb64cf8.png">

### Requirements
If you would like to take on this issue please comment but before asking to take on this issue there are a few requirements that will help complete this task:
- Get storybook up and running `yarn storybook`
- Some knowledge of storybook is not required but would be beneficial for this task. [storybook docs here](https://storybook.js.org/)

### Technical Details
- Migrate knobs to controls

### Acceptance Criteria
- knobs have been migrated to controls for listed story
- Take Before / After screenshots of the knobs and new controls and attach to the PR
- Tag @georgewrmarshall, @garrettbear, or @NidhiKJha in the PR to review

**Comment by dpundir-vertex** [comment] 2023-04-08 13:36
Hey @georgewrmarshall  I would like to work on this assignment. Could you please assign this to me? Thanks in advance!!!

**Comment by georgewrmarshall** [comment] 2023-04-11 11:29
Assigned thanks @dpundir-vertex!

**Comment by dpundir-vertex** [comment] 2023-04-11 14:09
Thanks @georgewrmarshall  to assign me this.

I have a query while checking the storyboard for MetamaskTemplateRenderer --> "With Invalid Element" **Currently** It is showing me following:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/61174028/231188050-cc4c7a8a-9e62-469c-be4b-1b22920c848a.png">


I understand why it is showing because we are passing `element: 'Unsafe',` then it goes to `MetaMaskTemplateRenderer` component where each section is processed. In processing first we check if the section's element is exist in the component `safeComponentList` or not. Here is the possible elements list:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/61174028/231186959-c9ec60f0-0b5c-4efb-8b03-9ec5bdc47f61.png">


Is that the expected behavior when we change Knobs to Controls? Actually i am confused by seeing the error page. If that's fine we can go ahead because its used for Invalid element by the way. So it should show some error somehow.

**Comment by georgewrmarshall** [comment] 2023-04-18 08:01
Hey @dj-pundir, I'm actually not sure why the knobs implementation is working. It should also error. I understand the intention of the story but I don't think it adds much value to show the thrown error. I think we could just remove the `WithInvalidElement` story altogether?

**Comment by georgewrmarshall** [comment] 2023-04-18 08:06
Also I'm curious what VS Code plugin or eslint settings you have to show these deprecated components with a strike through? I might suggest adding it to the repo it would be very helpful for an initiative to improve DX I'd like to complete

<img width="928" alt="Screenshot 2023-04-18 at 5 34 25 PM" src="https://user-images.githubusercontent.com/8112138/232713017-97127888-2546-4af0-abbc-da823c4b5b29.png">

**Closed** 2023-04-26 15:13 UTC
Labels: good first issue, type-story, design-system
