### ISSUE TITLE
Upload Custom Identicon

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4878] opened 2018-07-25 20:30 UTC
If you have many accounts, identicons can be difficult to distinguish between accounts. Would be useful if we enable a way for you to upload your own image to replace the generated identicons. This would increase trust and the customizability of the app which people tend to really like.

**Comment by Gudahtt** [comment] 2021-01-06 17:54
Closing as a duplicate of #2471

**Closed by Gudahtt** 2021-01-06 17:54 UTC
Labels: T01-enhancement
