### ISSUE TITLE
Uniswap, Pool/Remove Liquidity/Remove/Sign doesn't work with Ledger+MetaMask

### ISSUE THREAD

**Issue by zhangzhongnan928** [MetaMask/metamask-extension#8621] opened 2020-05-19 01:03 UTC
Bug Description
Pool/Remove Liquidity/Remove/Sign doesn't work with Ledger+MetaMask or AlphaWallet (iOS and Andriod)

Steps to Reproduce

Go to Uniswap/Pool/Remove Liquidity/Remove/Sign
Click on Sign
Ledger+MetaMask: MetaMask popup signing page, but won't ask for signing on Ledger

https://github.com/Uniswap/uniswap-frontend/issues/795

**Comment by Gudahtt** [comment] 2021-02-02 14:12
Thanks for the report! It looks like this was caused by Ledger not supporting `eth_signTypedData_v4`. They have since added support for EIP-712, but it still requires a library update on our part which is tracked in #10240.

I'm going to close this since Uniswap updated to no longer require EIP-712 support for that action, but you can track progress on supporting EIP-712 with Ledger in #10240

**Closed by Gudahtt** 2021-02-02 14:12 UTC
Labels: L17-hardware, L33-signTypedData, N02-needsReproduction, S2-normal, T00-bug, ledger-hardware-wallet, needs-triage
