### ISSUE TITLE
Switching Not to a Network: “Cancel” Button Not Working

### ISSUE THREAD

**Issue by faxotherapy** [MetaMask/metamask-extension#11214] opened 2021-05-31 14:44 UTC
**Describe the bug**
When asked to switch network on Beefy website, clicking “Cancel” button does not work.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Add Polygon network to MM.
2. In MM, remains in Ethereum blockchain.
2. Visit https://polygon.beefy.finance/
3. Website will ask to switch to Polygon side-chain.
4. Click “Cancel” button.

**Expected behavior**
MM should accept my request not to switch to Polygon network.

**Screenshots**
![CancelButtonNotWorking](https://user-images.githubusercontent.com/6538008/120209378-86bcd480-c226-11eb-82b0-6ea3272b747b.gif)

**Browser details (please complete the following information):**
 - OS: MacOS Mojave
 - Hardware Wallet: Trezor 1.9.4
 - Browser: Firefox 88.0.1
 - MetaMask Version: 9.5.5

**Additional context (Error Messages, etc.)**
I use Trezor HW in conjunction with MetaMask. No error message seen.

**Comment by darkwing** [comment] 2021-06-10 19:09
I can verify an issue here.  I see the following error in the background process:

```
Uncaught (in promise) Error: write after end
lockdown.js:4906:17
    rejectPendingApproval actions.js:2347
    AsyncFunctionThrow self-hosted:696
    Redux 2
    rejectPendingApproval index.js:97
    onCancel add-ethereum-chain.js:205
    React 17
    bind_applyFunctionN self-hosted:1373
    dispatchEvent self-hosted:1336
    unstable_runWithPriority scheduler.development.js:697
    React 4
    dispatchDiscreteEvent self-hosted:1279
    (Async: EventListener.handleEvent)
    addEventBubbleListener React
```

**Comment by adonesky1** [comment] 2021-06-25 17:23
Closing this issue because we will use duplicate #11383 for reference

**Closed by adonesky1** 2021-06-25 17:23 UTC
Labels: Sev2-normal, type-bug

**Comment by romain130492** [comment] 2021-12-14 08:34
@faxotherapy May I know how you made MM to programmatically update your user's network ?
Using `wallet_switchEthereumChain`?

```js
     await ethereum.request({
                        method: 'wallet_addEthereumChain',
                        params: [
                            {
                           /*  chainId: '0x137', */ // Hexadecimal version of 80001, prefixed with 0x
                            chainId: '137',
                            chainName: "POLYGON Mainnet",
                            nativeCurrency: {
                                name: "MATIC",
                                symbol: "MATIC",
                                decimals: 18,
                            },
                            rpcUrls: ["https://matic-mainnet.chainstacklabs.com"],
                            iconUrls: [""],

                        }],
                    });

```

**Comment by merket** [comment] 2021-12-25 02:51
I also confirm this issue.

**Comment by pageagency** [comment] 2022-01-15 16:53
+1 On this issue.

**Comment by voldemarz** [comment] 2022-01-19 14:14
Also having this issue Windows 10. Having these automatic network switch popups is often undesirable and annoying in itself when have tabs open that deal with different chains. Then constantly get this popup when switch tabs. Something as simple as disabling this automatic popup would be good and alleviate some of frustration caused by this bug.

**Comment by faxotherapy** [comment] 2022-01-19 14:18
Same for me. Being on Harmony on one tab and Fantom on another is often a pain and causes many issues like the MM pop-up asking me to switch. When I don't want to, the pop up persists and remains stuck. I'm just forced to switch so that the pop-up disappear. Extremely irritating. Maybe, using one browser per chain… LOL.

**Comment by scottrpaterson** [comment] 2022-04-12 18:40
This is still an issue on Firefox.

**Comment by klaypigeon** [comment] 2022-04-13 21:33
This is still an issue on FireFox, this should not be closed.
