### ISSUE TITLE
Using MetaMask for encryption/decryption

### ISSUE THREAD

**Issue by Qqwy** [MetaMask/metamask-extension#3872] opened 2018-04-04 17:01 UTC
We would like to create an application that encrypts/decrypts small pieces of information (that themselves will be used as passphrases for some larger synchronious encryption/decryption scheme).

What would be the best way to do this using MetaMask? Is it at all possible, or does MetaMask currently really only expose the functionality to `sign`/`sendTransaction`?

**Comment by kumavis** [comment] 2018-04-04 18:58
We currently only support signing and do not support encryption/decryption
more general key mgmt is on our roadmap

in the mean time take a look at https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

**Comment by danfinlay** [comment] 2018-04-10 21:24
Closing as duplicate of #1190.

**Closed by danfinlay** 2018-04-10 21:24 UTC
Labels: T06-devQuestion
