### ISSUE TITLE
API: How to get erc20 token user added to MetaMask programmatically?

### ISSUE THREAD

**Issue by Jack-Works** [MetaMask/metamask-extension#8865] opened 2020-06-29 08:53 UTC
If a user adds a token X to their MetaMask, how can I get the details of token lists?

**Comment by Gudahtt** [comment] 2021-01-05 22:54
It sounds like the "token selection API" described in #6060 would fit this use case. I'll close this for now as a duplicate of #6060.

For now, the answer is that the user's token list isn't accessible to dapps. This is probably the best default behaviour, so that dapps can't fingerprint or otherwise snoop on users by looking at their token list. But this would be a useful feature!

**Closed by Gudahtt** 2021-01-05 22:54 UTC
