### ISSUE TITLE
[Sentry] [Bug]: TrezorConnect has been already initialized

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14893] opened 2022-06-07 21:04 UTC
### Describe the bug

Unhandled exception is thrown when attempting to connect a hardware wallet after removing a Trezor account

https://user-images.githubusercontent.com/53189696/172482039-bbd20ef3-ff75-4114-828d-741ad451de12.mov

### Steps to reproduce

1. Login to the extension
2. Click the account menu and select Connect Hardware Wallet, select Trezor then click Continue
3. Connect your Trezor device, select an account and click Unlock
4. Click the account options ellipsis menu, select Remove account, then press Remove
5. Click the account menu and select Connect Hardware Wallet

### Error messages or log output

```shell
background-1.js:10 Uncaught (in promise) Error: TrezorConnect has been already initialized
  at t (background-1.js:10:544564)
  at new t (background-6.js:12:12715)
  at r.TypedError (background-6.js:12:12856)
  at background-6.js:12:32054
  at l (common-7.js:1:52790)
  at Generator._invoke (common-7.js:1:52578)
  at Generator.next (common-7.js:1:53219)
  at n (common-1.js:20:108953)
  at a (common-1.js:20:109164)
  at common-1.js:20:109223
  at new Promise (<anonymous>)
  at Object.<anonymous> (common-1.js:20:109104)
  at Object.init (background-6.js:12:32489)
  at new m (background-2.js:1:181082)
  at t.exports.addNewKeyring (common-1.js:46:33580)
  at Me.getKeyringForDevice (background-6.js:12:189756)
  at async Me.checkHardwareStatus (background-6.js:12:190709)
  at async s.<anonymous> (background-4.js:1:68290)
```

### Version

10.14.7

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

**Comment by gauthierpetetin** [comment] 2023-11-02 15:21
Related issue:
https://github.com/MetaMask/metamask-extension/issues/15007

**Comment by vivek-consensys** [comment] 2024-04-16 10:28
Unable to reproduce, closing issue.

**Closed by vivek-consensys** 2024-04-16 10:28 UTC
Labels: type-bug, area-Sentry, area-hardware, Sev3-low, hardware-trezor, hardware-wallet-connection-error, team-accounts, INVALID-ISSUE-TEMPLATE, regression-prod-11.3.0, team-hardware-wallets
