### ISSUE TITLE
Wrong checkmark on current account

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#1898] opened 2017-08-10 17:07 UTC
<img width="267" alt="screen shot 2017-08-10 at 10 05 46 am" src="https://user-images.githubusercontent.com/9360827/29182403-9dde9eca-7db3-11e7-98c0-a246c5f7c6bd.png">
Current selected account: romanstorm.eth, but it always shows as first one

**Comment by tmashuang** [comment] 2017-08-10 17:08
duplicate of #1895

**Closed by tmashuang** 2017-08-10 17:08 UTC
