### ISSUE TITLE
[Bug]: Premature close

### ISSUE THREAD

**Issue by Aliceonly** [MetaMask/metamask-extension#26326] opened 2024-08-02 16:14 UTC
### Describe the bug

When modify the network config and then metamask can't connect the network through the rpc url,
it leads metamask can't open and always get the Premature close
Cannot destructure property 'chainId' of '(0 , t.useSelector)(...)' as it is undefined.

### Steps to reproduce

1. Swith to a network metamask can't connect
2. switch network
3. can't open metamask anymore

### Error messages or log output

```shell
Error#17: Premature close scripts/sentry-install.js:1
```

```
TypeError: Cannot destructure property 'chainId' of '(0 , t.useSelector)(...)' as it is undefined.
  at z (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:857888)
  at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:61316)
  at Cs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:106147)
  at Au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:92055)
  at Ou (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:91980)
  at Tu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:89328)
  at vu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:86072)
  at al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:113703)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:114902
  at xu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:89679)
  at dl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:114887)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:116810)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:54554
```

### Detection stage

In production (default)

### Version

latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

fatal

**Comment by Sentini14** [comment] 2024-08-05 08:03
Yes please can you give me a link for chain list

***@***.***

**Comment by Sentini14** [comment] 2024-08-05 11:37
Ok, I will try.

**Comment by Sentini14** [comment] 2024-08-07 04:00
How can  I see my real public phrase key secret place

**Comment by Gudahtt** [comment] 2024-08-14 13:13
I suspect that this crash will no longer happen in v12.0.1, but the circumstances leading up to that crash probably are still possible, and would still be considered a bug.

@Aliceonly could you clarify how you were able to reproduce this problem? I am having trouble with these steps. I have tried switching to an unavailable network, but I don't see any crash and MetaMask doesn't get stuck. I just see that the balance loads infinitely, or a loading overlay appears that eventually lets me switch back.

Also, let us know if this is still a problem on v12.0.1. Thanks!

**Comment by Gudahtt** [comment] 2024-08-15 12:41
Thanks! Hmm, this sounds similar to #26072 but the repeated errors make me unsure. And with #26072 we never saw a crash. We will investigate further.

**Comment by Gudahtt** [comment] 2024-08-15 17:06
OK, so I believe I know what's happening now. The crash was caused by https://github.com/MetaMask/metamask-extension/issues/26320, that has been resolved.

The errors that caused the crash, and are still causing these console errors, are tracked already in these issues:
* https://github.com/MetaMask/metamask-extension/issues/26072 (for the network form error; I know your case was an edit rather than an add, but we're covering both issues here)
* https://github.com/MetaMask/metamask-extension/issues/26309 (for the state corruption resulting from that form)

I will close this issue for now, as it should be resolved in the next release as we fix those remaining two issues. Thanks very much for the report though, and let us know if you still see this in v12.0.5 or later versions!

**Closed by Gudahtt** 2024-08-15 17:06 UTC
Labels: type-bug, Sev1-high, team-extension-platform, external-contributor
