### ISSUE TITLE
[Bug]: Incorrect nonce when transaction is sent from non-connected active account

### ISSUE THREAD

**Issue by hd878** [MetaMask/metamask-extension#28274] opened 2024-11-04 17:31 UTC
### Describe the bug

When a dapp is connected to a different account from the active account that currently been selected in Metamask, the transaction nonce of active account is used instead of connected account, making transaction fails and not broadcasts.

### Expected behavior

Metamask should retrieve nonce from account which is connected to the dapp. 

### Steps to reproduce

1. Import 2 accounts which have different transaction counts to Metamask.
2. Connect first account to an dapp.
3. Switch to the second account. 
4. Nonce is incorrect for transaction performed.

### Detection stage

In production (default)

### Version

12.5, 12.5.1, 12.6

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by Henrywilliam96** [comment] 2024-11-04 20:15
> ### Describe the bug
> When a dapp is connected to a different account from the active account that currently been selected in Metamask, the transaction nonce of active account is used instead of connected account, making transaction fails and not broadcasts.
> 
> ### Expected behavior
> Metamask should retrieve nonce from account which is connected to the dapp.
> 
> ### Screenshots/Recordings
> _No response_
> 
> ### Steps to reproduce
> 1. Import 2 accounts which have different transaction counts to Metamask.
> 2. Connect first account to an dapp.
> 3. Switch to the second account.
> 4. Nonce is incorrect for transaction performed.
> 
> ### Error messages or log output
> _No response_
> 
> ### Detection stage
> In production (default)
> 
> ### Version
> 12.5, 12.5.1, 12.6
> 
> ### Build type
> None
> 
> ### Browser
> Brave
> 
> ### Operating system
> MacOS
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Severity
> _No response_



Hello @hd878

hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID MET00228, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link:[Metamask Network Dapps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by DanielTech21** [comment] 2024-11-08 12:13
Hi @hd878 

Thank you for informing us about this.
Our team will look into this in more detail.

**Comment by bschorchit** [comment] 2024-12-10 14:05
Closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/28014 that has already been fixed. @hd878 could you upgrade your MM to the latest version and let us know if you still encounter this issue? Thank you!

**Closed by bschorchit** 2024-12-10 14:05 UTC
Labels: type-bug, Sev2-normal, external-contributor, team-confirmations
