### ISSUE TITLE
Metamask keeps loading

### ISSUE THREAD

**Issue by lukaszGrynasz** [MetaMask/metamask-extension#5789] opened 2018-11-20 10:59 UTC
**Describe the bug**
Metamask keeps loading

**To Reproduce**
1. Go to https://ethtoolkit.io
2. Sometimes when i accept usage of Metamask ( new functionality  https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8 ) on website its stuck, otherwise when i want to perform approve ERC20 method on this DApp it stuck also. It is deterministic. Now it allways stuck unitl i do not off/on plugin in chrome. But after that it works until first transaction using metamask is made. 

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - MetaMask Version [e.g. 5.0.2]

**Additional context**

![capture](https://user-images.githubusercontent.com/40950183/48768155-b505e480-ecb8-11e8-984d-3c1a88d73ad6.PNG)

![capture2](https://user-images.githubusercontent.com/40950183/48769002-d7006680-ecba-11e8-8fe1-1b42861a2d37.PNG)

**Logs**
Setting up Sentry Remote Error Reporting: SENTRY_DSN_PROD
background.js:1 Injecting MetaMask Mesh testing client
inpage.js:1 ATTENTION: In an effort to improve user privacy, MetaMask stopped exposing user accounts to dapps if "privacy mode" is enabled on November 2nd, 2018. Dapps should now call provider.enable() in order to view and use accounts. Please see https://bit.ly/2QQHXvF for complete information and up-to-date example code.
(anonymous) @ inpage.js:1
partialRollout.js:28 MetaMask Mesh Testing - threshold not matched -- skipping test

**Comment by lukaszGrynasz** [comment] 2018-11-21 10:20
I try off/on plugin in chrome, but now i have a problem with simply log in to Metamask, after i type a password Metamask stucks.

**Comment by lukaszGrynasz** [comment] 2018-11-21 12:29
I have removed and added Metmask once again but this time i chose an old UX version and its working fine.

**Comment by tmashuang** [comment] 2018-11-21 17:34
Related to https://github.com/MetaMask/metamask-extension/issues/5784, sounds like there was a issue with a transaction before the one shown on the screenshot. Possibly the previous transaction might have not successfully went through. Can you clarify?

**Comment by lukaszGrynasz** [comment] 2018-11-22 01:00
Unlikely, i have perform losts of transaction on rinkeby ( i have checked on etherscan and all of them passed ). My scenario was as fallow : I executed some transaction on rinkeby , one or two on mainnet. Next i back to rinkeby and tests some contracts function. After one, maybe two days Metamask starts to stuck. First it stucks after 1 or 2 transaction but next it crashed when ``` window.ethereum.enable().then(() ``` was executed.

**Comment by MoMannn** [comment] 2018-11-22 11:02
I have the same problem. From the metamask console I found that metamask goes into an infinite loop of calling getBalance. I'm not sure what caused it. I also found that if I switch to the main network everything works ok but when I change to ropsten I gets stuck in the infinite loop.

**Comment by HeesuShin** [comment] 2018-11-23 08:40
Same issue for me!

**Comment by HeesuShin** [comment] 2018-11-23 08:52
And it's only matters in ropsten testnet.

**Comment by Cygnusfear** [comment] 2018-11-24 16:44
I have this issue due to a transaction, on Mainnet an unapproved transactions that is set to a gas limit of 0. Disabled extension, enabled it again, switched to Ropsten, logged in, switched to Mainnet. When I close the window Metamask returns to the infinte loading loop. With the workaround I can see the tx, and reject it. After rejecting all transactions, it opened the window as usual. 

Would be nice if the whole UI isn't blocked by a malformed TX so users can export seed phrase and such in case of emergency (and use it with another wallet).

**Comment by danjm** [comment] 2018-11-26 17:11
@MoMannn Can you share the steps you took to get into the "infinite loop of calling getBalance" state?

**Comment by Cygnusfear** [comment] 2018-11-26 17:13
@danjm infinite getBalance loop also occurred on my end

**Comment by MoMannn** [comment] 2018-11-26 17:14
@danjm I don't know exactly how I got into it. From what I recall I made a few transactions one after the other. 

The only way I found to fix it was to remove metamask and reinstall.

**Comment by danjm** [comment] 2018-11-26 17:15
Thanks @Cygnusfear and @MoMannn I'll use @Cygnusfear's and @lukaszGrynasz' repro steps and try to find and fix the cause of this.

**Comment by Bwest981** [comment] 2018-12-01 20:00
Same issue here. I have to turn off the plugin and turn it back on. Sometimes I have to switch networks, login, and switch networks back to use Metamask on testnets. It is not happening to me on Mainnet. Very unfortunate. I really like using Metamask when it works.

**Comment by superphly** [comment] 2018-12-03 16:30
Can confirm that it does this on Ropsten. I'm trying to present a demo tomorrow and now I'm dealing with this at the 11th hour. So frustrating.

**Comment by bdresser** [comment] 2019-01-07 15:48
5.2.0 included several fixes for infinite spinner bugs - can you let us know if you're still experiencing this issue?

**Comment by bdresser** [comment] 2019-01-22 17:16
closing this for now - @lukaszGrynasz or others let us know if you're still having trouble on the latest version.

**Closed by bdresser** 2019-01-22 17:16 UTC
Labels: N02-needsReproduction, T00-bug

**Comment by livingaftermidnight** [comment] 2021-01-01 21:36
I have this issue. Seems like just about everything I do I see a loading symbol that lasts forever.

**Comment by francovenica** [comment] 2021-01-20 21:20
I'm having this issue as well. It started all on itself a couple of weeks ago.

I run automation with a tool called Dappeteer, that loads a chromium browser with the metamaks extension, imports the wallet and the keys of some users.
Is tool is able to open the metamaks exension in a new tab, types the seed phrase, the pass and pass confirmation and when it hits "Import" then is when the Sentry error shows up.

The metamask used is a version 5.3.0. I'm using it on windows 10, in chromium. The browser is loaded everytime clean, so no cache or anything of the sort should be the problem.

![image](https://user-images.githubusercontent.com/4503659/105240755-e8b84f80-5b4b-11eb-9abd-faf7661bf882.png)

**Comment by jetlej** [comment] 2021-03-22 14:54
Same issue here

**Comment by Cr0wn-Gh0ul** [comment] 2021-03-27 17:59
Same issue
