### ISSUE TITLE
[Bug]: Double transactions triggered on Ledger Device

### ISSUE THREAD

**Issue by nikolay44u** [MetaMask/metamask-extension#24335] opened 2024-05-01 22:00 UTC
### Describe the bug

After the latest update, Metamask extension seems to be trigerring a second transaction on Ledger hardware devices, after the first one has been manually approved on the Ledger device.

Workflow: On a dapp, I trigger a transaction, and approve it on the Metamask extension, and then finally approve it on Ledger HW and it gets broadcasted to the network. This should be the end of the transaction. However, after few seconds, the Ledger shows the same transaction again for approval with the same nonce. 

### Steps to reproduce

1. On a dapp, I trigger a transaction.
2. Approve it on the Metamask extension, 
3. And then finally approve it on Ledger HW and the TX gets broadcasted to the network. 
 
This should be the end of the transaction. 
 
However, after few seconds, the Ledger shows the same transaction again for approval with the same nonce. 

### Version

11.14.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

### Severity

Critical - tried on multiple devices

**Comment by vivek-consensys** [comment] 2024-05-02 07:07
@nikolay44u can you please share what firmware version you are using on the Ledger device? Also, which Ledger device you are using?

**Comment by gauthierpetetin** [comment] 2024-05-02 14:05
Hi @MetaMask/hardware-wallets , I added a `sev2` label for now but feel free to re-assess and turn this into a `sev1` if needed.

**Comment by nikolay44u** [comment] 2024-05-02 15:02
> @nikolay44u can you please share what firmware version you are using on the Ledger device? Also, which Ledger device you are using?

The Ledger Firmware version(updated to the latest version) is: 
Secure Element 2.1.0
Microcontroller: 1.12

**Comment by vivek-consensys** [comment] 2024-05-02 15:15
> > @nikolay44u can you please share what firmware version you are using on the Ledger device? Also, which Ledger device you are using?
> 
> The Ledger Firmware version(updated to the latest version) is: Secure Element 2.1.0 Microcontroller: 1.12

hi @nikolay44u , please update your firmware versions. I was not able to reproduce this issue using the following versions on Ledger Nano X:- 

Secure Element - 2.2.3 
Microcontroller - 2.30
Bootloader - 1.16

**Comment by nikolay44u** [comment] 2024-05-03 06:21
> > > @nikolay44u can you please share what firmware version you are using on the Ledger device? Also, which Ledger device you are using?
> > 
> > 
> > The Ledger Firmware version(updated to the latest version) is: Secure Element 2.1.0 Microcontroller: 1.12
> 
> hi @nikolay44u , please update your firmware versions. I was not able to reproduce this issue using the following versions on Ledger Nano X:-
> 
> Secure Element - 2.2.3 Microcontroller - 2.30 Bootloader - 1.16

Im on the latest firmware as per Ledger Live. The app is also up-to date.

<img width="304" alt="Screenshot 2024-05-03" src="https://github.com/MetaMask/metamask-extension/assets/120264360/1d4688c6-ce98-4907-9193-523110a0bc28">

My device is Ledger Nano S. Havent tried on the X yet. 

It keeps happening on ETH network. Havent had this issue on another L2 network yet. 

Same flow as outlined earlier - tx that was already approved on the Hw device, appears again for approval on the Hw device. I just now had to cancel one such tx on the device because it was already confirmed onchain 😅

**Comment by angelcheung22** [comment] 2024-05-07 08:47
Pending support from Ledger team with nano s device. Issue cannot be reproduced from hardware wallet team on both nano X and nano S plus specific. Putting this to blocked.

**Comment by vivek-consensys** [comment] 2024-06-03 08:50
Hi @nikolay44u , are you still facing this issue?
If so, would you be able to share the exact steps to reproduce this including the information below:- 

- Firmware versions 
- Ledger device version
- dApp used
- Network used (Eth mainnet / Linea mainnet?)
- Browser used
- Metamask version

**Comment by JordaneJL** [comment] 2024-06-05 12:00
On Ledger side for the moment we're not able to reproduce this issue.
Will update accordingly if this changes.

**Comment by vivek-consensys** [comment] 2024-06-13 08:50
We are closing this as we can not reproduce this issue with the steps provided by @nikolay44u. Please reopen this, if you are able to reproduce and can clearly mention the steps with the devices/firmware versions used.

**Closed by vivek-consensys** 2024-06-13 08:50 UTC
Labels: type-bug, Sev2-normal, external-contributor, team-hardware-wallets, regression-prod-11.14.3
