### ISSUE TITLE
eth_signTypedData is no longer showing Sign-in transaction popup window automatically

### ISSUE THREAD

**Issue by Maxxi** [MetaMask/metamask-extension#3952] opened 2018-04-10 23:51 UTC
The previous version of the plugin (till ~4.5.0) showed transaction sign-in window popup automatically when you call eth_signTypedData API

```
const method = 'eth_signTypedData';
web3.currentProvider.sendAsync( method, params, .. )
```

But the latest metamask plugin (v.4.5.5) hides this popup under the main metamask plugin icon. Please return the previous functionality back, so the user doesn't need to click on the plugin's icon to see the transaction sign-in popup window, which should automatically be shown after 'eth_signTypedData' API call.

Also, when the main plugin window with accounts is shown and you call 'eth_signTypedData' API => then metamask hides this main plugin window and doesn't popup transaction Sign-in window. You have to re-click on plugin's icon to see it.

**Comment by danfinlay** [comment] 2018-04-13 18:47
Sorry about this, I believe it's a duplicate of #3759, so I'm closing it here, but we will fix this soon.

**Closed by danfinlay** 2018-04-13 18:47 UTC
