### ISSUE TITLE
Network: disable cache on localhost

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3088] opened 2018-01-24 20:00 UTC
There are some issues with testrpc/ganache-cli and metamask cache, when using instant blocks. One easy way to resolve this is to not include the BlockCache when targeting localhost.

Selected P1 because this affects lots of developers using metamask. They see old state from before the last tx.

**Comment by timothywangdev** [comment] 2018-04-11 01:42
We experienced the same bug while testing on ganache-cli.  Metamask always returns the old (incorrect) value for a contract variable. My current workaround is to connect Metamask to an other network then reconnect to localhost.

**Comment by danfinlay** [comment] 2018-06-06 19:04
More caching observations by @MicahZoltu:

micah.zoltu [1:47 AM]
I'm trying to author a dapp against MetaMask.  When connected to a private network and I attempt to do `eth_call`, MetaMask returns a JSON-RPC _success_ response with `.result: '0x'`.  When I watch the network traffic coming out of MetaMask, I can see that no request is being made of the private node, which means MetaMask is generating the response internally.
I am able to do `net_version` successfully and I can witness the request going to the private node I'm pointing at.
When I switch networks to Rinkeby and fire the _exact_ same `eth_call` request I can see it posting to Infura.  This _implies_ to me that the issue is specific to custom nodes and `eth_call` in some way?
Am I doing something wrong?
Ahah!  Apparently MetaMask doesn't like me passing `from: '0x00000...'` to eth_call.  Will file a bug about that.

Hmm, it actually appears to be some _super_ aggressive caching by MetaMask.
As a developer, how do I force MetaMask to bust its cache?  I rebuilt my private network with a bugfix, but it appears that MetaMask cached the response from before my bugfix.

Previously I hadn't worked on MetaMask integration personally on other projects, though I have heard other developers complain about "weird MetaMask behavior that eventually went away".  Now that I am experiencing them I took some time to debug to try to figure out the source of the problem and caching looks like the root cause.

I can certainly appreciate the desire to have the results of many things cached (e.g., `eth_call`) to avoid having a poorly written app hammering the backing nodes.  It just feels like at the moment the caching is a bit too aggressive and busting the cache is a bit too hard.

**Comment by bdresser** [comment] 2018-07-10 17:36
being handled in #4279

**Comment by bdresser** [comment] 2018-08-16 00:34
fixed in https://github.com/MetaMask/metamask-extension/pull/4279

**Closed by bdresser** 2018-08-16 00:34 UTC
Labels: L00-provider, P1-asap, T00-bug, U1-dev

**Comment by saturnial** [comment] 2018-08-18 10:09
This issue is fixed apparently, but curious to know what the original caching strategy was -- and how exactly it has been addressed in #4279.

**Comment by kumavis** [comment] 2018-08-20 16:41
@saturnial #4279 changes our handling of rpc methods from `provider-engine` to `json-rpc-engine`.

before with `provider-engine` we used this [default configuration](https://github.com/MetaMask/provider-engine/blob/master/zero.js) for all networks. Its cache logic can be found [here](https://github.com/MetaMask/provider-engine/blob/master/subproviders/cache.js).

now with `json-rpc-engine` and [some additional changes in metamask's `NetworkController`](https://github.com/MetaMask/metamask-extension/blob/fb5faec372a718722be901a81efe873d014cdd87/app/scripts/controllers/network/network.js#L151-L167), we configure infura mainnet like [this](https://github.com/MetaMask/metamask-extension/blob/fb5faec372a718722be901a81efe873d014cdd87/app/scripts/controllers/network/createInfuraClient.js) and localhost like [this](https://github.com/MetaMask/metamask-extension/blob/fb5faec372a718722be901a81efe873d014cdd87/app/scripts/controllers/network/createLocalhostClient.js). The primary difference is the inclusion of [these two layers of caching](https://github.com/MetaMask/metamask-extension/blob/fb5faec372a718722be901a81efe873d014cdd87/app/scripts/controllers/network/createInfuraClient.js#L18-L19). The caching layers are the primary [block-based](https://github.com/MetaMask/eth-json-rpc-middleware/blob/fb5faec372a718722be901a81efe873d014cdd87/block-cache.js) and the network-request deduping [inflight-cache](https://github.com/MetaMask/eth-json-rpc-middleware/blob/fb5faec372a718722be901a81efe873d014cdd87/inflight-cache.js).

The block-cache was built to do a straightforward cache on requests with a lifetime of one block. The inflight cache was built to solve the problem where request 1 and 2 are equivalent but request 2 is made before request 1 finishes. Request 2 will be held until request 1 completes, then will return with Request 1's result. [Here](https://github.com/MetaMask/eth-json-rpc-middleware/blob/master/cache-utils.js#L73-L152) is where we determine the methods that we cache (anything marked `perma` + `block`).
