### ISSUE TITLE
Firefox browser

### ISSUE THREAD

**Issue by wep1211** [MetaMask/metamask-extension#12272] opened 2021-10-03 09:00 UTC
May I ask the Firefox browser to click on the extension to open the Little Fox Wallet, and then why is it blank?

The browser restarts, and the computer restarts the same as it keeps displaying blank

**Comment by danjm** [comment] 2021-10-04 09:56
Appears to be a duplicate of:
https://github.com/MetaMask/metamask-extension/issues/9196
https://github.com/MetaMask/metamask-extension/issues/11245
https://github.com/MetaMask/metamask-extension/issues/4894

You may have to uninstall, re-install and restore your account using your seed words

**Closed** 2021-10-04 09:57 UTC
