### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by backmen** [MetaMask/metamask-extension#16700] opened 2022-11-26 17:59 UTC
> > I have made ethereum fork and my custom wallet works, metamask mobile works, but ethereum extension does not.
> > When I try to send coins it wont let me!
> > ![image](https://camo.githubusercontent.com/ebead73634f6953e9147ea892c7ceb172d9cf2ddd1214729617362ff5d5831d7/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f497a48544c2e706e67)
> > My custom rpc: https://rpc.avescoin.io
> > My network uses smaller minimum gas ( 11k instead of 21k ) but other wallets work!

### Steps to reproduce

1.
> > ### Steps to reproduce
> > 
> > 1. Go to https://avescan.io
> > 2. Add network button
> > 3. Ask me to send you 2 AVS ( we are still on test net ! )
> > 4. See for your self

> 

### Error messages or log output

```shell
> > ### Error messages or log output
> > 
> > sentry-install.js:1          GET https://gas-api.metaswap.codefi.network/networks/33333
> > Only error
```

### Version

10.22.1

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS, Linux

**Comment by kevinghim** [comment] 2022-12-02 00:44
@backmen would you be able to provide more details? It's not possible to reproduce this or investigate with very little detail.

**Comment by backmen** [comment] 2022-12-02 00:54
> @backmen would you be able to provide more details? It's not possible to reproduce this or investigate with very little detail.

Its simple add network in metamask ( https://rpc.avescoin.io), (chain id 33333) (explorer https://avescan.io9, let me know when you add to i send you some coins on your address, and try you to send back or other AVS address..metmask simple not allow to send  just write no conversion rate available
Picture or error in atachment

![noconversion](https://user-images.githubusercontent.com/22981802/205190352-f79bda59-8632-45e8-acdf-9947c7f4c9e0.PNG)

**Comment by backmen** [comment] 2022-12-08 15:22
Can someone help us?

**Comment by danjm** [comment] 2023-02-06 19:38
duplicate of https://github.com/MetaMask/metamask-extension/issues/16593

**Closed by danjm** 2023-02-06 19:38 UTC
Labels: type-bug, needs-reproduction, area-customNetworks, Sev2-normal
