### ISSUE TITLE
Can not create new account

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#10201] opened 2021-01-16 03:06 UTC
Firefox 84.0.2 (64-bit)
Manjaro Linux
MetaMask Version 9.0.1

action : click "Create account" , type in name off account , hit [create]

Account does not show up in account list

It is working as expected on Chrome Version 89.0.4329.0 (Developer Build) (64-bit) + Metamask 9.0.1

**Comment by Gudahtt** [comment] 2021-01-18 16:39
Thanks for the report! Unfortunately I was unable to reproduce this, using the same version of the extension and MetaMask (though I'm using Ubuntu, rather than Manjaro Linux).

We can investigate a bit further in the meantime, but it'll be difficult without a reproduction. You could help us find one by submitting [a support request here](https://metamask.zendesk.com/hc/en-us/requests/new) that includes a [copy of your state logs](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue). They may provide additional instructions on how to get console logs as well, to help debug the issue further.

**Comment by SvenMeyer** [comment] 2021-01-19 03:20
@Gudahtt thanks for following up.
I just tried again after a full restart of my laptop and browser, and now it works again as expected.
I downloaded the state logs, had a quick look inside and found that it contains too much information (all my accounts and balances?) to share ...

**Comment by Gudahtt** [comment] 2021-01-19 03:48
State logs do indeed contain a lot of information, and it's understandable to not want to share them. We do take privacy quite seriously and only use these logs internally and for debugging purposes, but please don't send them in if you feel any discomfort about doing so.

There are further steps that support could have walked you through to help us learn more about the problem without sharing state logs, but if you're not experiencing the issue anymore then the opportunity is lost. I'll leave this issue open for a while longer though, in case anybody else has the same problem and can help shed further light on the situation.

**Comment by danjm** [comment] 2021-10-04 15:41
Closing as we have not had further reports for ~9 months

**Closed by danjm** 2021-10-04 15:41 UTC
Labels: type-bug, needs-reproduction, Sev2-normal

**Comment by nunyvega** [comment] 2024-08-01 13:08
Hey folks, I had the same issue:
Chrome version: Version 127.0.6533.74 (Official Build) (arm64)
The extension was freshly installed. 

Not sure if creating an account should send a network request, but if it had to, it was not, I was checking the network tab. No errors in console were logged either. 

Steps to reproduce:
1- On chrome, install MetaMask and create a new account:
2- Log out -> Log in
3- Go to expanded view
4- try to create a new account from here, or from the default extension view.

As soon as chrome is fully restarted and you log in again, it works fine.
