### ISSUE TITLE
KeyringController - potentially intializing different seed phrase?

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#2383] opened 2017-10-16 17:14 UTC
in some very rare cases, initially backed up seed phrases may generate different addresses

we should tie setting of `notBackedUpYet` flag to creation of mnemonic 
in case this is an issue with initialization

**Comment by danfinlay** [comment] 2017-10-16 18:02
Some notes:

- Our theory of the bug seems to have been backwards: Mnemonic generation is on the `addAccount()` function.
- Actually that’s the problem, maybe initializing with no parameters should be treated as a first time setup, or maybe we need to add a parameter for “create new vault”
- If constructed with no mnemonic, create a fresh mnemonic *then*.
- When adding accounts, if there is no mnemonic, throw.

**Comment by Zanibas** [comment] 2017-10-16 18:29
Duplicate of #1950

**Comment by Zanibas** [comment] 2017-10-16 22:25
So it turns out that deleting the generated root of the HD keyring mid-application won't cause anything to break--it'll gracefully (and silently) generate a new root using a new mnemonic and generate a new account based on that (while still preserving the other accounts).

That helps explain some cases where the first account is correct, but other accounts are off. What this does not account for is people getting some set of accounts when they first create MetaMask, and are given seed words that will restore to another set accounts, yet do not realize this until they attempt to restore.

Continuing to investigate, but playing around with deleting certain background data within certain functions to see if we can replicate the behavior on the backend. Still have NO idea how this happens from a front-end prompting.

**Comment by danfinlay** [comment] 2017-10-17 18:43
Based on Kevin's latest, new theory:
This problem is related to a (possibly old bug) where we would generate multiple hd-keyrings at setup.

If a person has two hd keyrings:
- Which one do we show the seed phrase for?

If we show for just the earliest, that may not be the one they actually have accounts for. We could automate a notice for this.

**Comment by danfinlay** [comment] 2017-10-17 20:30
To test that previous concern/theory, I did some tests, I seem to at least have disproved it on master:

Added slight delay to vault create button
Clicked "create" several times on first time setup.
Got seed phrase A
Got first account B
show seed phrase still shows A
recovering from seed on same metamask showed same account B
Restoring on fresh install gave same results.

**Comment by kumavis** [comment] 2018-01-09 14:29
This issue was resolved as https://github.com/MetaMask/metamask-extension/issues/2577
Here is the relevant blog post https://medium.com/metamask/seed-phrase-issue-bounty-awarded-e1986e811021

**Closed** 2018-01-09 14:30 UTC
Labels: L2-keymanagement, P2-sooner, labeled
