### ISSUE TITLE
Metamask - Blank Screen (after recent migration?)

### ISSUE THREAD

**Issue by 12Solve** [MetaMask/metamask-extension#3963] opened 2018-04-12 04:25 UTC
Hi,

After I click on the Fox, I have a blank screen. A couple of weeks ago I did not have this issue.
I attached some screenshots of the logs I found.

I am using version 4.5.5

Any help would be more than welcome, thank you.

Kurt
![schermafdruk 2018-04-12 08 21 02](https://user-images.githubusercontent.com/38307212/38656352-f5f815d6-3e2a-11e8-8cfa-fed9a86e7de5.png)
![schermafdruk 2018-04-12 08 18 55](https://user-images.githubusercontent.com/38307212/38656353-f63de214-3e2a-11e8-90f3-7a0fb8fdcb04.png)

![schermafdruk 2018-04-14 08 52 13](https://user-images.githubusercontent.com/38307212/38717751-ed80bb4a-3ef9-11e8-9b49-28ee410b4672.png)

**Comment by danfinlay** [comment] 2018-04-13 22:59
Have you tried restarting your browser? If you have your seed phrase backed up, you can probably work around this by uninstalling, reinstalling, and restoring from your seed phrase.

If you'd like us to figure out exactly what has gone wrong for you, you should send us your [logs](https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue) to support@metamask.io

**Comment by 12Solve** [comment] 2018-04-14 09:50
Thank you.
I will first send you the logs, if we cant solve it that way, I will use seed phrase after uninstalling and reisntalling.
I will not loose my Envion tokens which were on my wallet?

Greetings,

Kurt

Verstuurd vanaf mijn iPhone

Op 14 apr. 2018 om 02:59 heeft Dan Finlay <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Have you tried restarting your browser? If you have your seed phrase backed up, you can probably work around this by uninstalling, reinstalling, and restoring from your seed phrase.

If you'd like us to figure out exactly what has gone wrong for you, you should send us your logs<https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue> to support@metamask.io<mailto:support@metamask.io>

**Comment by berlinczyk** [comment] 2018-04-15 12:47
Bank Page, chrome on Mac also in Firefox ;(

**Comment by danfinlay** [comment] 2018-04-16 20:51
@berlinczyk if you get this, would you mind opening the background logs to see what error you're having? Is it the same "provider is undefined" error that we see above?

https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by rzelnik** [comment] 2018-05-17 06:50
I have the same issue and I tried it in multiple fresh OS installations in VirtualBox. Freshly installed Metamask shows the Terms of Use first, then after acceptance, it only shows a blank screen (Firefox 51 in Ubuntu 16.04), which hides immediately (Firefox 60 in Ubuntu 18.04 LTS).
It shows this error message in the Add-ons list > MetaMask:
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
Reading manifest: Error processing externally_connectable: An unexpected property was found in the WebExtension manifest.

**Comment by danfinlay** [comment] 2018-05-18 18:59
@rzelnik what version of MetaMask is that listed as?

**Comment by rzelnik** [comment] 2018-05-18 19:14
Currently I have 3.13.8 - the version which is on the https://addons.mozilla.org/ page, but before I had 4.5.something. The blank screen issue appeared also in the 4.5.X version.

**Comment by danfinlay** [comment] 2018-05-18 20:58
Sorry, Firefox has been very picky about releases they would publish (required deterministic builds). Our latest versions should be reaching the firefox store soon, in the meanwhile, Firefox should be considered behind the latest version.

**Comment by bdresser** [comment] 2018-06-11 23:41
hey all, Firefox is now up to the latest version (4.7.4) and I'm unable to reproduce this issue. could you update to the recent release and let us know if you're still having trouble?

**Comment by rzelnik** [comment] 2018-06-12 07:20
I do have version 4.7.4 in my Firefox and the blank screen issue still appears. Maybe I should remove my old MetaMask user data?

**Comment by danfinlay** [comment] 2018-06-12 17:23
@rzelnik That's very strange. If you were using Firefox Developer mode I'd ask you to look at the background console, but normal Firefox doesn't have this.

Do you have your seed phrase backed up? If so, remove & reinstall might work around your problem.

**Comment by rzelnik** [comment] 2018-06-13 08:41
Reinstalling of MetaMask doesn't solve the issue. I tried multiple new installations of several Linux distributions (Ubuntu, CentOS, Fedora). It's still the same - in Chrome/Chromium it works well, but in Firefox there's just an empty window, which hides immediately. In new installations, the Terms of Use are shown first, and then, after accepting, the empty window appears.

**Comment by rzelnik** [comment] 2018-06-14 07:06
Ok, I have Firefox Developer Edition with MetaMask installed. The first thing that I noticed is an error message in Debug Addons list:

> MetaMask
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
Reading manifest: Error processing externally_connectable: An unexpected property was found in the WebExtension manifest.

I tried to start the debugger, but the Firefox Developer Edition mixes English and Slovak languages in the error messages, so I put the Console output from the standard Firefox, which generates plain English error messages:

![error1](https://user-images.githubusercontent.com/610651/41396656-ebc52dde-6fb1-11e8-9754-3bf9f2144aab.png)

Now I am clicking on a MetaMask icon, it generates new error messages (starting with Download the React DevTools...):

![error2](https://user-images.githubusercontent.com/610651/41396697-14ba796a-6fb2-11e8-9663-a9f3153f7e45.png)

Is this helpful for you?

**Comment by nicejoe2121** [comment] 2018-06-24 16:52
Hello, i have the exact same problem with he metamask plugin turning blank when hitting the button in Firefox and in Chrome. I see the case was closed, but i can't seem to read the solution to this problem. Is there a solution ? Or is there another way of accessing the coins that are hosted by metamask ?
thanks

**Comment by rzelnik** [comment] 2018-06-24 17:11
This issue is not closed. The "closed" label belongs to the related Bug in mozzila after last update (14.06).

**Comment by danfinlay** [comment] 2018-06-24 18:52
Hi All, sorry this issue is happening. Our team is on a retreat this week, we very rarely actually see each other in person, and so it is probably unlikely we have time to fix this until next week.

If you need to access your MetaMask wallet until then, you can easily using your seed words. Either set up MetaMask on a different browser (we also support Chrome, Brave, and Opera), or use your seed words on a different wallet entirely (mycrypto, myetherwallet, trezor, all support our seed word format).

Again, sorry for the wait, we will dig into this closer soon.

**Comment by Emiller88** [comment] 2018-06-28 20:02
I have the same issue on 18.04.

**Comment by estebanmino** [comment] 2018-07-03 23:36
I'm in 18.04 as well and I can log in using the Disable popup auto hide button in Firefox Developer Tools. While I'm logged in I have no problems at all with the app, it works fine, the problem comes when I log out and the extension goes to blank and it closes itself, that's why it cannot be open at first, the is no user logged in. So when I'm logged in there is no problem. Any thoughts on this? Maybe an UI specific issue?

**Comment by estebanmino** [comment] 2018-07-04 20:07
I detected that the components InitializeMenuScreen and AccountDetailScreen of both OldUI and UI are failing due to a strange reason, for example to open the extension and have the menu screen I deleted the password-word  element and it worked (of course I cannot do login) I guess that something similar happens in the other component.

Deleting this from old-ui/app/ first-time/int-menu.js 
```
// password
      h('input.large-input.letter-spacey', {
        type: 'password',
        id: 'password-box',
        placeholder: 'New Password (min 8 chars)',
        onInput: this.inputChanged.bind(this),
        style: {
          width: 260,
          marginTop: 12,
        },
      }),
```
I was able to render the MenuScreen, without the password input. Then deleting this

```
document.getElementById('password-box').focus()
```
 in line 144 I was able to render the view but I couldn't type a password because the extension closes itself.

**Comment by estebanmino** [comment] 2018-07-04 20:45
I was able to run the app deleting all type password of inputs (~~type: 'password',~~), therefore working without hide the password in the inputs.

```
// password
      h('input.large-input.letter-spacey', {
        id: 'password-box',
        placeholder: 'New Password (min 8 chars)',
        onInput: this.inputChanged.bind(this),
        style: {
          width: 260,
          marginTop: 12,
        },
      }),
```
Maybe an issue related to react-hyperscript?

**Comment by estebanmino** [comment] 2018-07-04 21:45
@Emiller88 @nicejoe2121 @rzelnik  could you check your version of Firefox? I had the version 60.2 on Ubuntu 18.04 and I had the same issue than you, now I've updated it to version 61 running `sudo snap install firefox` and the extension is working fine.

**Comment by rzelnik** [comment] 2018-07-05 05:39
@estebanmino I can confirm that Metamask with snap-based Firefox version 61 works well for me.

**Comment by nicejoe2121** [comment] 2018-07-05 10:51
Hello, i have firefox version 52.9.0. 32 bit.
I'm working on windows vista SP2 32 bit.
Firefox says he's up to date.

**Comment by rzelnik** [comment] 2018-07-06 09:34
Now the Firefox in Ubuntu (I mean classic APT repository) is also updated on version 61. So I updated my Firefox to 61 and reinstalled Metamask. And... it still does not work. So the issue is not related to a version of the Firefox. Probably there is some difference between the APT version and the snap version. Maybe there is some conflict.

**Comment by KojimaGeniy** [comment] 2018-07-08 20:31
I have only appearing license screens, after accepting which it gets blank, but if during this I'll choose beta version, it works fine for one session, after restarting it stops working again.

**Comment by estebanmino** [comment] 2018-07-10 19:13
@KojimaGeniy which version of Firefox and OS are you using?

**Comment by KojimaGeniy** [comment] 2018-07-10 19:42
@estebanmino Ubuntu 18.04, Firefox 61, Metamask 4.8.0 from official firefox hub.
And I had no luck inspecting metamask with browsers dev tools opening it as a separate tab, it goes into infinite loading.

**Comment by adibas03** [comment] 2018-07-11 13:01
@KojimaGeniy I am on the same environment as you,
an this helped:
https://github.com/MetaMask/metamask-extension/issues/3313#issuecomment-400013621

**Comment by KojimaGeniy** [comment] 2018-07-11 13:42
@adibas03 Thank you, really works! I was trying it like this, but without popup.html had no luck, now it's good.

**Comment by estebanmino** [comment] 2018-07-13 16:20
I reproduced this but the extension itself still doesn't work so I was able to interact with it through the browser as web page. The problem is still related to the type password on inputs.

**Comment by estebanmino** [comment] 2018-07-13 19:07
Have the same issue with other add-ons, workaround should be a solution for APT version of firefox

**Comment by danfinlay** [comment] 2018-07-16 17:29
User also affected on Firefox Developer edition.

We're going to add a feature to automatically transition ubuntu/firefox users into full-screen mode, since the popup is so buggy.

It does seem the good workaround for now is to open in full screen mode, using the `popup.html` URL.

**Comment by estebanmino** [comment] 2018-07-18 19:24
@KojimaGeniy @adibas03 I found an interesting fix for this related to the new Xorg Gnome version in Ubuntu 18.04. The default keyboard input method system is Ibus which has issues with password types (https://github.com/ibus/ibus/issues/2002#issuecomment-386537208), can you try changing keyboard input method system to XIM? I did it and the extension is working fine now.

**Comment by KojimaGeniy** [comment] 2018-07-20 13:51
@estebanmino I confirm, works now even without separate tab, just like it was on 16.04, thank you.

**Closed** 2018-07-20 18:45 UTC
Labels: P1-asap, S06-firefox, T00-bug

**Comment by nicejoe2121** [comment] 2018-07-20 19:01
So if i understand correctly, the issue of the blank screen can be resolved on Ubuntu. But i run windows vista and still have the blank screen on Firefox and on Chrome. Any news on this ?

**Comment by bdresser** [comment] 2018-07-20 19:40
@nicejoe2121 what version of Windows are you running?

**Comment by nicejoe2121** [comment] 2018-07-21 05:49
I'm running Windows Vista Home Basic SP2 32 bit. thank you

**Comment by bdresser** [comment] 2018-07-23 15:10
@nicejoe2121 see https://github.com/MetaMask/metamask-extension/issues/4817 for the issue on Windows

**Comment by dringdahl0320** [comment] 2018-09-30 23:44
I am having this exact same issue on Brave 0.24.0 - Metamask version 4.11.1 - Did anyone get a solution to this? And steps to fix?
