### ISSUE TITLE
Can't click Accept button on first use Meta Mask

### ISSUE THREAD

**Issue by dzahar** [MetaMask/metamask-extension#2724] opened 2017-12-11 02:28 UTC
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior : 
on first use, I would be displayed the terms and conditions and allowed to click the Accept button.

  *  Actual Behavior
on first use, MetaMask displays the terms and conditions pop-up, but I am not able to scroll down this window and the "Accept" button is not active.

  *  Browser Used
Chrome Version 63.0.3239.84 (Official Build) (64-bit)

  *  Operating System Used
Windows 10 

![metamask-screenshot](https://user-images.githubusercontent.com/23047437/33813337-f999112c-de5d-11e7-8dd9-17bf21c2b86a.JPG)

**Comment by kevag4** [comment] 2017-12-13 11:59
Hello,

I can see the exact same issue and my characteristics are the same as @dzahar . Any solution?

BRS / Kostas

**Comment by H256** [comment] 2017-12-15 08:48
Hello, I too have the same issue. :(

**Comment by eeldivad** [comment] 2017-12-16 06:44
It was working fine for about a week and today I just noticed the same problem.  I have the same issue too.  I realize the problem is the mouse position doesn't reflect the actual position.  It seems to be about an inch off.  For example if I want my mouse position to be at point A, then I actually have to move the mouse about an inch above and an inch to the left of point A, then click.  Took me awhile to find the spot for the scroll bar and then able to click down the scrollbar to activate the button and then click it.  I tried closing the browser and even resetting all settings of chrome and restarting my computer but nothing worked.  Then I tried uninstalling it and reinstalling it.  Then it worked for awhile but then the issue came back.  I tried installing chrome with metamask on a different computer and it worked ok so not sure why it's doing this on mine.

I'm running Windows 10 with latest chrome Version 63.0.3239.108 (Official Build) (64-bit)

**Comment by latinbrownie** [comment] 2017-12-17 17:09
Hi, I am also having this issue tried re-installing metamask and issue remains. does anyone have a solution regarding this matter??

**Comment by ifElser** [comment] 2017-12-18 10:12
Yes, same issue - cursor over Acctpt button indicate text input and button not clickable.

**Comment by latinbrownie** [comment] 2017-12-18 10:47
Found the solution in my case:   i have 2 screens with different sizes i moved my browser window to my other screen and this made it possible for me to click the accept button. it seems to be a screen resultion/size issue.

hope it helps others

**Comment by kevag4** [comment] 2017-12-18 10:49
Amazing! @latinbrownie is right!

**Comment by eeldivad** [comment] 2017-12-18 16:17
Great, so to fix the problem is to move chrome to my other monitor.  But this should still be fixed.

**Comment by danfinlay** [comment] 2017-12-18 19:44
Closing in favor of #2767.

**Closed by danfinlay** 2017-12-18 19:44 UTC
