### ISSUE TITLE
RPC errors not bubbled back to Ðapp

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8483] opened 2020-04-30 19:41 UTC
Currently when a Ðapp initiates a call to `eth_sendTransaction`, if the RPC backend throws an error (like `transaction underpriced`), this error is not returned to the Ðapp, instead a generic internal wrapper is returned, like `"Error: [ethjs-rpc] rpc error with payload {"...`

Checked and this behavior continues to exist on develop.

Ideal case:
- [ ] Return the RPC error to the Ðapp itself.
- [ ] Show the failure reason in the transaction history to the user.

**Comment by wighawag** [comment] 2020-05-20 20:41
Ok, seems I am getting this issue, but I am getting the following error for every metamask tx, even when I use metamask ui to send ether to another address 

Here is the error I get when executing one my dapp transaction :

```
{code: -32603, message: "Error: [ethjs-rpc] rpc error with payload {"id":79…method":"eth_sendRawTransaction"} [object Object]", stack: "Error: Error: [ethjs-rpc] rpc error with payload {…method":"eth_sendRawTransaction"} [object Object]"}
```

```
stack : "Error: Error: [ethjs-rpc] rpc error with payload {"id":7973398896595,"jsonrpc":"2.0","params":["0xf8cb2b8504a817c80082bd5d943037e0b21e7b8e0babaf3611d6d0d5cac51e67c080b864c47f0027000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000036473640000000000000000000000000000000000000000000000000000000000820a95a04314f99297ee7e82db567bc8008c3d2739558e9010b9dac763d266a71f72bb0ca03a9aa5658bfc4dde3c754c40a5345aaba47819cc6df5b39c57144fb42c60bf85"],"method":"eth_sendRawTransaction"} [object Object]"
```

**Comment by wighawag** [comment] 2020-05-20 20:42
This was on chrome and loaded a new profile with a new metamask and there my dapp function fine

**Comment by adrianmcli** [comment] 2020-06-15 01:54
This is quite frustrating, as things work fine when I am just running scripts in Node.js but suddenly throws a cryptic error when I do it through the frontend. Is there a `toString()` getting called somewhere that's causing the underlying object (w/ revert reason string) to become `[object Object]` instead?

**Comment by MicahZoltu** [comment] 2020-06-27 12:11
Not only is the RPC mangled, it also is wrapped in a more opaque error.  When I inspect the JSON-RPC error I get back from `sendAsync`, I see:
```json
{
  "code": -32603,
  "message": "[object Object]",
  "data": {
    "code": -32603,
    "message": "revert: ERC20: transfer amount exceeds allowance"
  },
  "stack": "..."
}
```
Note that the *actual* JSON-RPC error (the onet hat would be immensely useful for debugging) is burried inside the `data` field of the error I actually get back.

**Comment by wbt** [comment] 2020-07-13 20:29
I am [not seeing](https://github.com/MetaMask/metamask-extension/issues/8975) the `data` member in Chrome.

**Comment by Gudahtt** [comment] 2021-01-19 03:06
Relates to #8975 and #7142

**Comment by MicahZoltu** [comment] 2021-02-15 15:49
I received an error report from a user today where it appears MetaMask is throwing a string instead of an error!  This means I don't get a stack trace, which is critical for debugging.

This is what is showing up in my code's catch block.
```json
{
	"code":-32000,
	"message":"err: insufficient funds for gas * price + value: address ... have ... want ... (supplied gas ...)"
}
```

**Comment by vandan** [comment] 2022-07-26 18:04
Relates to #12646

**Comment by MicahZoltu** [comment] 2022-07-27 05:33
I think you mean that #12646 is a duplicate of this.  😉

**Comment by adrianmcli** [comment] 2023-09-04 04:15
I don't think this is stale.

**Comment by vandan** [comment] 2023-10-20 19:43
A related PR was created https://github.com/MetaMask/metamask-extension/pull/15205 but resulted in other issues (tradeoffs). Needs further assessment on the approach here.

**Comment by wighawag** [comment] 2023-10-20 20:04
@vandan thanks for chiming in here

Could you please do so for all issues that are being closed by bots. This is honestly alienating people like me who would live to see Metamask improve and create issue with that goal in mind, but whose only interlucutor is a bot closing issues :(

I understand that you might have too many issues in your hand, but closing issues blindly will only make the issue count down. The issue wont resolve themeselves. 

Sorry if that sounds harsh but some issue are being closed while they exist in the repo for a long time with few or no comment from Metamask team

**Comment by vandan** [comment] 2023-10-21 00:10
> @vandan thanks for chiming in here
> 
> Could you please do so for all issues that are being closed by bots. This is honestly alienating people like me who would live to see Metamask improve and create issue with that goal in mind, but whose only interlucutor is a bot closing issues :(
> 
> I understand that you might have too many issues in your hand, but closing issues blindly will only make the issue count down. The issue wont resolve themeselves.
> 
> Sorry if that sounds harsh but some issue are being closed while they exist in the repo for a long time with few or no comment from Metamask team

We understand your frustration. We'll see what can be done about the automated actions, but generally the best way we can avoid this is by being more responsive to these issues so they don't become stale in the first place.
We absolutely appreciate the effort our community goes through to help MetaMask improve and don't want to lose your good will. 🙏

**Comment by MicahZoltu** [comment] 2023-10-21 04:10
FWIW, I have stopped filing issues with MetaMask because 90%+ of the issues I encounter just get closed by the bot and remains unfixed.

**Comment by adrianmcli** [comment] 2023-10-21 11:12
What's most ironic is that this issue was filed by @danfinlay himself.

**Comment by adrianmcli** [comment] 2024-01-19 20:02
Not stale. Do we know if this new plan has changed and the necessary fixes inside `ethjs-query` have been implemented?

<img width="547" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/943555/9a865035-4959-4824-bb63-4501becd7d7a">

From here: https://github.com/MetaMask/metamask-extension/pull/15205#issuecomment-1199953855

I'm not sure if I have the energy to say "not stale" again.

**Comment by MicahZoltu** [comment] 2024-01-20 09:55
Sadly, I gave up on filing issues and commenting "not stale".  90% of the issues I follow/file just go stale and are never fixed, even after many years of the bug existing.

**Comment by adrianmcli** [comment] 2024-01-20 13:43
> Sadly, I gave up on filing issues and commenting "not stale". 90% of the issues I follow/file just go stale and are never fixed, even after many years of the bug existing.

With all the money that MetaMask makes. I wonder why they can't have someone do triage on these open source issues?

And I've said it above a few months ago, but the most ironic thing is that this is an issue @danfinlay raised himself.

Dan probably will not remember, but I have fond memories of chatting with Dan when I was part of ConsenSys in 2018. Times have really changed.

**Comment by Jaycat66** [comment] 2024-01-20 13:58
do not close because i am workin on it

**Comment by BelfordZ** [comment] 2024-01-25 18:45
> Not stale. Do we know if this new plan has changed and the necessary fixes inside `ethjs-query` have been implemented?
> 
> <img alt="image" width="547" src="https://private-user-images.githubusercontent.com/943555/298184348-9a865035-4959-4824-bb63-4501becd7d7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMDgzMzEsIm5iZiI6MTcwNjIwODAzMSwicGF0aCI6Ii85NDM1NTUvMjk4MTg0MzQ4LTlhODY1MDM1LTQ5NTktNDgyNC1iYjYzLTQ1MDFiZWNkN2Q3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxODQwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODA5YmM0MmIzMGQ2MjliODMyYTUzNDUyYjBiYTE2YTA5Nzg0ZDg0MzlkMGFlNWM3NjFjZDZhYWQ2NTRiZjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hPCOgtxFjikeEgq7URTiafumLip2gpGkJbhjECYZs5Y">
> From here: [#15205 (comment)](https://github.com/MetaMask/metamask-extension/pull/15205#issuecomment-1199953855)
> 
> I'm not sure if I have the energy to say "not stale" again.

Sorry, I tried to get it sorted out but it turned out to be more complicated then it seemed. I had a [this PR](https://github.com/MetaMask/metamask-extension/pull/15205) that we had to reject becasue it would cause breaking changes for those who had already written code to parse these bad errors. A new plan was hatched, but other priorities came up and I wasn't able to keep at it. 

Just know that its on our radar, and it *will* get better. I also understand asking for patience at this point is almost insulting, so I will spare you on that.

**Comment by vandan** [comment] 2024-03-15 22:26
This issue is no longer reproducible. See [our notes](https://github.com/MetaMask/metamask-improvement-proposals/pull/36#issuecomment-1991790792) for the detail about why the issue is resolved.

Please re-open if you are able to reproduce.

**Closed by vandan** 2024-03-15 22:26 UTC
Labels: type-bug, Sev2-normal, area-api, team-wallet-api-platform

**Comment by steven1227** [comment] 2024-12-26 07:46
> Not only is the RPC mangled, it also is wrapped in a more opaque error. When I inspect the JSON-RPC error I get back from `sendAsync`, I see:
> 
> {
>   "code": -32603,
>   "message": "[object Object]",
>   "data": {
>     "code": -32603,
>     "message": "revert: ERC20: transfer amount exceeds allowance"
>   },
>   "stack": "..."
> }
> Note that the _actual_ JSON-RPC error (the onet hat would be immensely useful for debugging) is burried inside the `data` field of the error I actually get back.

Nowadays, when invoke the contract using sendTransaction, the error.data is not return anymore?
