### ISSUE TITLE
YEFI Token doesn't appear after adding as custom token

### ISSUE THREAD

**Issue by DomDomHaas** [MetaMask/metamask-extension#10094] opened 2020-12-16 21:30 UTC
**Describe the bug**
YEFI Token doesn't appear after adding it via custom token.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to 'Assets'
2. Click on 'add token'
3. Click on tab 'custom token'
4. Enter token hash 0xcf282ba0bc91d2aa6e775bcfd90da6b7912f1b1a (see https://etherscan.io/token/0xcf282ba0bc91d2aa6e775bcfd90da6b7912f1b1a)
5. the details are filled correctly
5. click add (from my wallet it the amount shows correctly)
6. it keeps on loading

**Expected behavior**
It finishes loading and under assets appears with the correct balance

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Browser 83.0 (64-bit)
 - MetaMask Version: 8.1.8

**Comment by dpazdan** [comment] 2020-12-17 02:08
possibly related tickets 70689, 70860, 70440, 70684, 69630, 69811

**Comment by Gudahtt** [comment] 2020-12-17 06:14
Thanks for the report! We have gotten multiple reports from support similar to this, but we've been unable to reproduce this so far.  I have tested this with v8.1.8 in the same version of Firefox, and it all seems to work. We'd appreciate any additional help you can offer in tracking this down. I had a few follow-up questions:

* Are you still experiencing this issue with v8.1.9?
* Does this fail consistently, or intermittently?
* Does it fail for other tokens too?
* Are there any errors in the background process?
  * You can check this by navigating to "Add-Ons", clicking the gear menu to the right of "Manage Your Extensions", clicking "Debug Add-ons", then clicking the "Inspect" button next to MetaMask.

If you can't find anything useful in the background logs, I'd suggest contacting support and sending them your state logs, in case the problem is triggered by some local state.

**Comment by jacobcantele** [comment] 2020-12-17 18:24
Possibly related to #10097

**Comment by Gudahtt** [comment] 2021-01-14 00:33
We've addressed a number of issues recently that involved the UI freezing (e.g. #10097), and most of them appear to be fixed in the latest version of the MetaMask extension (v8.1.11). I'm going to close this for now as I think it's likely fixed, but please let us know if you're still experiencing this problem. Thanks!

**Closed by Gudahtt** 2021-01-14 00:33 UTC
Labels: N02-needsReproduction, T00-bug
