### ISSUE TITLE
Data is not same with  blockchain

### ISSUE THREAD

**Issue by ziqiDev** [MetaMask/metamask-extension#5578] opened 2018-10-23 03:54 UTC
**Describe the bug**
After Approve,  the state of Metamask shows pending, But the transaction on the Etherscan has been success.
Then if you go to send the token , it will show transfer error.

Now you can click the speed up. It will jump to transfer page again, click cancel then it will show confirmed.

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: macOs
 - Browser chrome
 - MetaMask Version 4.16
 - New UI

**Additional context**

**Comment by bdresser** [comment] 2018-10-23 15:40
thanks @ziqiDev - closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/5551

**Closed by bdresser** 2018-10-23 15:40 UTC
