### ISSUE TITLE
[Bug]: PPOM - `Error validating JSON RPC using PPOM:  Error: enrichment: db: custom error: Stable coin estimation failure`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24169] opened 2024-04-22 13:22 UTC
### Describe the bug

The `Request may not be safe` warning was displayed for a malicious Permit signature.
The following error was displayed in the console `Error validating JSON RPC using PPOM:  Error: enrichment: db: custom error: Stable coin estimation failure`

### Expected behavior

No error and display the Malicious warning.
I think this error might be on the ppom side. What do you think @jpuri ?

### Screenshots/Recordings

![Screenshot from 2024-04-22 15-22-58](https://github.com/MetaMask/metamask-extension/assets/54408225/5c289c2a-e36b-427d-bdfa-dfc7b573debd)

https://github.com/MetaMask/metamask-extension/assets/54408225/93780d60-2d66-41a1-a03b-15ecaf113fff

### Steps to reproduce

The issue appeared 1 time and I cannot reproduce again:
1. Select Mainnet
2. Go to the test dapp
3. Trigger a Malicious Permit
4. See `Request might not be safe` warning and error in the background console

### Version

11.15.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment] 2024-04-23 12:29
I am not able to reproduce this, it worked for each time I tried:

![Screenshot 2024-04-23 at 5 59 15 PM](https://github.com/MetaMask/metamask-extension/assets/2182307/ec0ff55d-9a77-44c3-b13b-5aeb05da36d7)

**Comment by jpuri** [comment] 2024-06-25 11:13
Closing this issue as this is no more reproducible.

**Closed by jpuri** 2024-06-25 11:13 UTC
Labels: type-bug, needs-reproduction, Sev3-low, team-confirmations
