### ISSUE TITLE
MetaMask can't work

### ISSUE THREAD

**Issue by TamirTian** [MetaMask/metamask-extension#7828] opened 2020-01-15 10:32 UTC
![image](https://user-images.githubusercontent.com/20901836/72426646-19d9a380-37c5-11ea-9474-9832ec7da6d4.png)
![image](https://user-images.githubusercontent.com/20901836/72426677-2b22b000-37c5-11ea-80ef-7cbc722dfbd0.png)
![image](https://user-images.githubusercontent.com/20901836/72427276-5f4aa080-37c6-11ea-95a6-5433ff163a68.png)

version: 7.7.2

The chrome also got the slow in the past. I usually reinstall it, but i have many private keys now in my MetaMask of brave.

**Comment by Jetsoanalin** [comment] 2020-01-20 07:23
i'm facing similar issue it would be good if we get a solution for this soon

**Comment by hhanquez** [comment] 2020-01-21 06:15
Same problem on firefox

![image](https://user-images.githubusercontent.com/42935669/72779976-c4b2ed00-3c1d-11ea-84c6-4fd79e9ff262.png)
![image](https://user-images.githubusercontent.com/42935669/72779983-ca103780-3c1d-11ea-9bd3-3b2686ee7cd3.png)

**Comment by dpazdan** [comment] 2020-01-21 14:43
@TamirTian Do you mind sending in your console logs to us at support@metamask.io?  Reference this github issue #, thanks!  https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue

**Comment by Jetsoanalin** [comment] 2020-01-22 06:40
Duplicate of #7847

**Comment by tmashuang** [comment] 2020-01-31 01:15
Fixed in v7.7.3.

**Closed by tmashuang** 2020-01-31 01:15 UTC
Labels: T00-bug
