### ISSUE TITLE
Fix "Import flow @no-mmi Import wallet using Secret Recov..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27336] opened 2024-09-23 13:28 UTC
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101671/workflows/7916cc8f-082c-4486-8cc0-36802704df43/jobs/3785883/tests

Build - Regular
Browser - Chrome
Test Scenario - Import flow @no-mmi Import wallet using Secret Recovery Phrase
Test Path - /test/e2e/tests/account/import-flow.spec.js

```
TimeoutError: Waiting for element to be located By(css selector, [data-testid="account-list-menu-details"])
Wait timed out after 10023ms
  (Ran on CircleCI Node 17 of 20, Job test-e2e-chrome)
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![image](https://github.com/user-attachments/assets/6f7c5726-4931-4ac4-ba8b-e37ff533071b)

**Comment by chloeYue** [comment] 2024-09-27 07:38
test still flaky. CI failure: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102428/workflows/43303c30-7f7a-4a51-a61c-527cf010f872/jobs/3816802

**Comment by seaona** [comment] 2024-10-03 12:43
@chloeYue do you think we can close this ticket now? The PR which fixed this and other cases with the same root cause has now been merged. See below:

https://github.com/MetaMask/metamask-extension/commit/7a5e4d6b88897eb914780fdd15157fc0d9b6f0c5

**Comment by chloeYue** [comment] 2024-10-07 07:53
> @chloeYue do you think we can close this ticket now? The PR which fixed this and other cases with the same root cause has now been merged. See below:
> 
> [7a5e4d6](https://github.com/MetaMask/metamask-extension/commit/7a5e4d6b88897eb914780fdd15157fc0d9b6f0c5)

 yes we can close it ! thanks for the fix!

**Closed** 2024-10-07 08:00 UTC
Labels: type-bug, Sev2-normal, team-extension-platform, flaky tests
