### ISSUE TITLE
Add an API option to import a seed phrase

### ISSUE THREAD

**Issue by westonb7** [MetaMask/metamask-extension#7365] opened 2019-11-07 18:46 UTC
**What problem are you trying to solve?**
We're looking for ways to integrate SeedQuest (https://github.com/reputage/seedQuest) with MetaMask, and after exploring the options available through plugins, determined that a plugin wouldn't quite work for what we're trying to accomplish.

**Describe the solution you'd like**
We want to allow MetaMask users to import a seed phrase from an external Dapp or website, which could be used to allow the user to access accounts/keyrings in MetaMask by importing seed phrases from external sources.

**Additional context**
We (the SeedQuest team) would be happy to collaborate and help out in any way we can.

**Comment by rickycodes** [comment] 2019-11-08 14:33
closing because dupe of #7364

**Closed by rickycodes** 2019-11-08 14:33 UTC
