### ISSUE TITLE
Transactions not sending - latest version, all txns get stuck in pending with nonce 0

### ISSUE THREAD

**Issue by REPTILEHAUS** [MetaMask/metamask-extension#5687] opened 2018-11-06 09:47 UTC
**Describe the bug**
Trying to purchase tokens, when submitting txn with gas of 50 gwei and gas price of 255000 they just sit there in pending state, doing another transaction just adds to the queue and all have nonce 0 while never getting processed, clicking on the open link opens up etherscan results in this page being opened up ```https://etherscan.io/tx/undefined```

**To Reproduce**
Carry out a normal Transaction

**Expected behavior**
That my transaction goes through

**Screenshots**
<img width="345" alt="screenshot 2018-11-05 at 22 31 25" src="https://user-images.githubusercontent.com/4680621/48055756-a1368a80-e1b0-11e8-8f34-a7e37b158035.png">

<img width="358" alt="screenshot 2018-11-06 at 10 41 20" src="https://user-images.githubusercontent.com/4680621/48055790-af84a680-e1b0-11e8-96fa-be6efe5a2dae.png">

<img width="341" alt="screenshot 2018-11-06 at 10 41 38" src="https://user-images.githubusercontent.com/4680621/48055808-b57a8780-e1b0-11e8-9951-a22206a566c1.png">

**Browser details (please complete the following information):**
 - OS: OSX Mojave
 - Browser Chrome Version 70.0.3538.67 (Official Build) (64-bit)
 - MetaMask Version 4.17.1 
 - New UI

**Comment by emn178** [comment] 2018-11-06 15:42
Same problem, stuck forever
![image](https://user-images.githubusercontent.com/3477613/48075186-96fea580-e21d-11e8-9355-f68f44cc6329.png)

How to remove them

**Comment by bdresser** [comment] 2018-11-06 16:48
Thanks for reporting. Can you both please 
(1) check if there are any errors in your UI or background console when you submit a transaction?
(2) send your state logs to support@metamask.io and mention this issue number.
Intstructions on both [here](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue).

**Comment by MUSystem** [comment] 2018-11-08 10:00
The same. https://etherscan.io/tx/undefined
Chrome, latest version

**Comment by REPTILEHAUS** [comment] 2018-11-09 17:04
Will send on my logs now but i reset the account to clear the txns then tried to buy tokens again and its hanging still but no errors in the js console of the extension other than below:

<img width="898" alt="screenshot 2018-11-09 at 18 03 10" src="https://user-images.githubusercontent.com/4680621/48277052-e0333d00-e449-11e8-96df-e1d4ebbcf016.png">

**Comment by bdresser** [comment] 2018-11-12 16:17
Thanks for the state logs @REPTILEHAUS, we're taking a look. Looks like you found the UI console fine, would you mind checking the background logs as well? head to `chrome://extensions` and click `background.html`, see if anything throws when submitting a tx. Instructions [here](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue) with a working link :)

**Comment by REPTILEHAUS** [comment] 2018-11-13 17:05
No confirmations.. however i do see this error. 

<img width="892" alt="screenshot 2018-11-13 at 14 33 13" src="https://user-images.githubusercontent.com/4680621/48430038-af674680-e76e-11e8-874e-53693b169f94.png">

**Comment by CryptoDave111** [comment] 2018-11-13 19:08
**I stopped being able to send ether yesterday** and put in lots of transations and nothing would send or show up on IO.  I found the solution - REVERT back to the OLD UI.  And clear the transactions.  That is in your settings. Now it is sending again!  The new Beta has some bug.

**Comment by tmashuang** [comment] 2018-11-13 19:19
Thanks for the workaround @CryptoDave111, can we determine the root cause to the issue? Does the old UI show transactions the New UI doesn't? Were these transactions created by mistake?

**Comment by CryptoDave111** [comment] 2018-11-13 19:24
Hi
I tried to send and nothing would happen.  Tried a few transactions and nothing ever would go to the etherscan.  I then tried cancelling and they just showed pending forever.   I upped the gas and nothing.  Just nothing.
I cleared the transactions so they are gone now
But I did download the log and am attaching here David Johnson


Mobile 573-604-1481david@dhammasukha.orgwww.thepathtonibbana.comwww.dhammasukha.orgAnnapolis, MO 63620
Free Online Retreats at Dhamma Sukha.org
Consider a Recurring donation to Dhamma Sukha that makes you smile every month!

**Comment by tmashuang** [comment] 2018-11-13 19:49
Please email logs to support@metamask.io. With the issue number, 5687.

**Comment by CryptoDave111** [comment] 2018-11-13 19:55
File sent!  Dave

**Comment by REPTILEHAUS** [comment] 2018-11-13 20:17
Tried to revert to old UI with cleared txns' still no joy

**Comment by danfinlay** [comment] 2018-11-14 06:51
@REPTILEHAUS were you using the Ledger hardware wallet with MetaMask when this happened?

**Comment by tmashuang** [comment] 2018-11-14 16:49
@REPTILEHAUS As David points out in the issue related it is not clear to check your ledger after step 4 to confirm the transaction on the ledger. Since this extra step is not taken, step 5 is the result.

**Comment by lyricalpolymath** [comment] 2018-11-20 15:10
+1 here too.
MM creates undefined TXs https://etherscan.io/tx/undefined 
and gets stuck, even the "cancellation TXs won't work

Here are the background.html errors (something to do with balanc3 price finder?)
(will send the logs)

![screenshot](https://user-images.githubusercontent.com/516744/48782404-69fec800-ecde-11e8-8467-72cdc50611d1.png)

I've tried logging out and also disabling the extension and re-enabling it but the list of stuck TXs are still there.
nothing in local storage that we can manipulate

**Comment by lyricalpolymath** [comment] 2018-11-20 20:20
Some more Log digging - **can it be a problem with assigning the Nonce?**
- This happened without the ledger wallet connection, just trying to change the daily limit in a gnosis multisig https://wallet.gnosis.pm
- with the new version of MM
- but switching back to the old UI didn't work either, the TXs are still there

Transaction 11 worked
Transaction 12 was the first to fail and give undefined

![screen shot 2018-11-20 at 20 24 28](https://user-images.githubusercontent.com/516744/48797432-6f6e0980-ed02-11e8-9ecb-62fe804592c0.jpg)

### //// Histories

![screen shot 2018-11-20 at 20 24 09](https://user-images.githubusercontent.com/516744/48797708-397d5500-ed03-11e8-912e-4775cdfd54b7.jpg)

can the problem be in /txParams/nonce ?



### workaround

I've tried to switch to the old UI but the pending TXs where still there.
It did however work to send new transactions
and after sending a new transaction with the old UI
you could send other Txs also with the new UI, even if the Queued transactions are still there like a vestigial organ of a failed past :)

**Comment by bdresser** [comment] 2018-11-20 23:15
We're rolling our 5.0.3, which has a couple updates that aim to address this issue. Once your extension has updated, please let us know if you're still having this problem.

(You can also manually install 5.0.3 from https://github.com/MetaMask/metamask-extension/releases)

Will leave this open until we can confirm this is no longer an issue.

**Comment by lyricalpolymath** [comment] 2018-11-21 09:59
> We're rolling our 5.0.3, which has a couple updates that aim to address this issue. Once your extension has updated, please let us know if you're still having this problem.

 @bdresser 
 awesome thanks. what's the lifecycle of the update? ETA? does it do it automatically?
thanks

**Comment by bdresser** [comment] 2018-11-21 19:57
cc @danfinlay sounds like some old-ish tx are still hanging around post-migration

@lyricalpolymath if you want to get rid of them, you can go to Settings and hit Reset Account. This just wipes your local transaction history.

**Comment by danfinlay** [comment] 2018-11-29 20:05
Yeah, this should be fixed as of last week's release. This was the "tx stuck in approved state" bug. Let us know if this isn't fixed, and we'll reopen.

**Closed by danfinlay** 2018-11-29 20:05 UTC
Labels: L00-provider, L18-transactions, N02-needsReproduction, T00-bug

**Comment by itamarro** [comment] 2019-01-26 04:09
This still happens in the latest version. I suggest documenting the Reset Account option as the remedy, or perhaps better - providing a way to clear (not actively cancel) a pending transaction that the network is not aware of from the UI (I did not find such an option in the old/new UI).

**Comment by k06a** [comment] 2019-03-03 19:42
Same happens for me today with the latest versions of MetaMask and Google Chrome. Re-adding of Ledger to MetaMask not even erases Tx Queue.

**Comment by k06a** [comment] 2019-03-03 19:43
@danfinlay reopen, please!

**Comment by k06a** [comment] 2019-03-03 21:47
Heh, this was U2F bug, only Google Chrome restart helps

**Comment by LA555** [comment] 2019-05-07 01:07
Hi Everyone, 
I have now 27 pending transactions on Metamask and I started these transactions 2 weeks ago. I have restored Metamask with my seed phrase and resent the tokens but these too have failed. I would really appreciate your help to be able to send transactions on Metamask please.

**Comment by bdresser** [comment] 2019-05-07 22:33
@LA555 please reach out to support@metamask.io and we'll do our best to help/

**Comment by acarreras** [comment] 2021-10-16 09:37
Same issue here with queued and pending transactions forever. On Ubuntu with Firefox. After MM update nothing is working with Ledger. Cancelling the transactions or sending a new transaction with the previous NONCE only increases the queue! :-S
