### ISSUE TITLE
Fix infinite spinner bug

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2548] opened 2017-11-07 23:23 UTC
We've had some users report issues that show `Failed to fetch` as an error in the background console.

Seems to suggest we may not be handling some disconnects perfectly.

**Comment by danfinlay** [comment] 2017-12-18 20:32
This issue is just for the error that's crashing our provider, causing infinite provider spinners. Can be expanded by #2552.

**Comment by amirsohail01** [comment] 2018-02-02 04:44
Hi Dan, you have closed my incident #3151, I have tried that workaround and it doesn't work for me. I tried it by switching to each of the other networks one by one and then switching back to Main network. Nothing worked. :(

**Comment by Douglasacost** [comment] 2018-02-15 17:45
in my case the issue is caused by the date configuration

**Comment by Douglasacost** [comment] 2018-06-15 14:48
@danfinlay in the server the datetime doesn't mismatch from network

**Comment by bdresser** [comment] 2018-09-25 22:16
sorry @Douglasacost still not super clear - what server?

**Comment by whymarrh** [comment] 2019-02-13 16:21
I think we might be able to close this in favour or some combination of #3253 and #5210, thoughts?

**Comment by bdresser** [comment] 2019-02-13 23:06
Sounds good - we opened this when there were a couple live reports of this being a big issue, seems like it's quieted down. We should still implement the global timeout on spinners though.

**Closed by bdresser** 2019-02-13 23:06 UTC
Labels: N04-needsQA, T00-bug, T01-enhancement
