### ISSUE TITLE
Cannot click radio button for address when setting up Ledger.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6343] opened 2019-03-25 11:25 UTC
**Describe the bug**
When going through the process of connecting a Ledger to MetaMask, I am prompted to Select HD Path (I chose Legacy), and then Select an Account.  When I click on the radio buttons for the accounts in the list, nothing happens, the radio button does not become selected and the unlock button does not become enabled.

**To Reproduce**
1. Click to setup a new ledger.
2. Change HD Path to Legacy.
3. Try to click on the first account.
4. Notice that clicking does nothing.

**Expected behavior**
I can select an account.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - MetaMask Version: 6.2.2

**Comment by brunobar79** [comment] 2019-03-28 02:02
Can't reproduce on Chrome, so it's either a Brave or Windows specific issue: 

![demo-2](https://user-images.githubusercontent.com/1247834/55124243-f7628680-50db-11e9-8dd1-04841bc822bb.gif)

@tmashuang  can you give it a try?

**Comment by MicahZoltu** [comment] 2019-03-28 06:12
In your video you already had address 2 selected upon initially connecting to the ledger.  This suggests to me you have something cached locally or something.  For me, by default no radio option is selected.

**Comment by brunobar79** [comment] 2019-04-02 17:00
@MicahZoltu  Fair enough. Just tried it again in a fresh state I still can't reproduce.

![ledger](https://user-images.githubusercontent.com/1247834/55421454-3c0c7880-5547-11e9-940f-d6a31c829110.gif)

I'll check if anyone in the team running windows has a ledger device.

**Comment by brunobar79** [comment] 2019-04-16 14:13
That’s good news! We can reopen if it happens in the future.

**Comment by racabu** [comment] 2019-08-16 05:14
Im experience this issue today.

**Comment by Mkneeshaw** [comment] 2019-10-19 14:13
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16686828/67146424-0156fd00-f259-11e9-8b13-3e1a3fc47057.gif)


I am experiencing this issue today with Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by Mkneeshaw** [comment] 2019-10-19 14:16
Metamask overview screen was the active tab. I tried later going through the metamask icon and it worked.

**Comment by rbmilch** [comment] 2019-12-04 14:03
@Mkneeshaw thanks for that workaround. 
But it looks like a bug not like a feature.

**Comment by brandoncurtis** [comment] 2020-02-29 03:29
This issue is still present.

Version 79.0.3945.130 (Official Build) (64-bit)
Metamask 7.7.5

To reproduce:
1. click on Metamask icon
2. click `...`
3. click `Expand View`
4. click on identicon
5. click `Connect Hardware Wallet`
6. click `Ledger`
7. try to click on the radio buttons to select an address.  you can't!

It works fine if I do this without expanding Metamask into a tab.

**Comment by rbmilch** [comment] 2020-02-29 13:58
Thank you!

Am Sa., 29. Feb. 2020 um 04:29 Uhr schrieb Brandon Curtis <
notifications@github.com>:

**Comment by DiceDemon** [comment] 2020-05-03 00:18
Still an issue. Going through the metamask icon instead of expanding into a tab fixes it.

**Comment by akda5id** [comment] 2020-06-08 17:52
This bug is still active on MetaMask Version 7.7.9. During the initial setup for the chrome extension, the radio buttons are non functional. Closing the extension configuration page, and accessing again though the icon allows the buttons to be selected successfully.

**Comment by tylerlevine** [comment] 2020-09-17 17:02
I also just ran into this in version 8.0.8.

The workaround mentioned by @Mkneeshaw above worked for me and I was able to select the right account.

**Comment by senselessDev** [comment] 2020-10-03 17:04
Can also confirm the problem and working workaround for Brave 1.14.84 and MetaMask 8.0.10.

**Comment by stoecki222** [comment] 2020-10-09 13:45
Can also confirm the problem. Workaround does not work for me. Windows security somehow blocks access to ledger Nano. 

![image](https://user-images.githubusercontent.com/72613112/95590471-61384c00-0a46-11eb-862d-e14e3ba2d4f3.png)

**Comment by rkagerer** [comment] 2021-01-03 21:46
Confirmed this bug still exists.  Tried it today under a fresh install of MetaMask 8.1.9, Chrome 87.0.4280.88 (64-bit, official build), Windows 10.  Had to close the MetaMesh tab and open a new one, then the radioboxes were clickable.  If it helps, I did visit the MetaMask configuration settings prior to setting up the wallet.

**Comment by molecular** [comment] 2021-01-04 14:31
Installed metamask for the first time ever today and experience this issue in both firefox 84.0.1 and brave 0.65.121 (Chromium: 75.0.3770.100)

The workaround works for me, thanks @Mkneeshaw !

**Comment by Strernd** [comment] 2021-01-05 16:31
Same for me. Problems with Metamask extension on Chrome and Brave Wallet on Mac OS 10.15.7

**Comment by Gudahtt** [comment] 2021-01-19 00:53
This may be fixed by #10198. I wasn't able to confirm because I'm having trouble reproducing this today (despite having _no trouble_ reproducing this yesterday; I'm not sure what changed).

**Comment by Gudahtt** [comment] 2021-01-29 17:12
I'm going to close this for now, as I believe it was fixed by #10198 (which shipped in v9.0.4 of the extension)

**Closed by Gudahtt** 2021-01-29 17:12 UTC
Labels: L17-hardware, N02-needsReproduction, S2-normal, T00-bug
