### ISSUE TITLE
Contact / address book: previous entries gone, cannot delete entries, cannot add entries

### ISSUE THREAD

**Issue by zacksinclair** [MetaMask/metamask-extension#9818] opened 2020-11-06 17:25 UTC
**Describe the bug**
After the auto-update to version 8.1.3, the contact book feature is all but completely broken. 

All my previously saved addresses are gone. I cannot add new entries to it. Cutting and pasting an address into the Eth address field to add an account provides no UI feedback at all. There are two "recent" entries that are addresses I have not used in 2 years. Attempting to delete these entries yields no results.

When sending to an address that is not in the address book, and clicking "save address here" and going through the flow, nothing happens - the address is not saved.

**Steps to reproduce (REQUIRED)**
Simply try to use the address book - try to add or delete an entry. Perhaps reproduction would be to have a function address book with saved entries using a previous version of metamask, then when it auto-updates, it would be broken? 

**Expected behavior**
The address book is useable.

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: none
 - Browser: Version 86.0.4240.183 (Official Build) (x86_64)
 - MetaMask Version: 8.1.3

**Comment by jacobcantele** [comment] 2020-11-07 22:33
I have a video of the issue above that was shared with me by @zacksinclair, and have also requested state logs. Zack's client is in some sort of bugged/corrupted state. 

When working this issue, please reach out to me directly to review those items.

**Comment by ESA14** [comment] 2020-11-11 11:08
I have the same issue since the auto-update to version 8.1.3

**Comment by sam0thius** [comment] 2020-11-24 19:51
Same issue here with the address book after auto-updating to Metamask version 8.1.3 with W10 64bit and Brave browser.

**Comment by Enverex** [comment] 2020-11-30 00:26
Same here, all addresses have gone and it seems to refuse to save new ones.

**Comment by shaimo** [comment] 2020-12-01 00:07
Same here. Logged into a new computer. All contacts are gone, and can't save new ones

**Comment by sam0thius** [comment] 2020-12-03 07:04
@jacobcantele, any news about this issue? I understand this is not a critical bug, but for a "cosmetic" one it sure is annoying. Hopefully this can be fixed in upcoming MetaMask updates as evidently the issue is affecting more than just one or two individuals.

**Comment by tmashuang** [comment] 2020-12-03 07:13
Duplicate of #9982
> Could you try switch to from Mainnet to Ropsten(or any other network), and back? This is to reinitialize the provider object and correctly populate the chainId which is how we sort the contract list.

**Comment by sam0thius** [comment] 2020-12-03 07:50
Many thanks @tmashuang for the tip, switching from Mainnet to Ropsten and back resolved the issue for me! After the switch some quite old addresses came back to the Metamask contact list and I can again save new addresses to the contact list. 👍

**Comment by zacksinclair** [comment] 2020-12-03 20:41
Confirmed that switching from Mainnet to Ropsten and back restored previously missing address book entries.

**Comment by Gudahtt** [comment] 2020-12-07 20:18
This is a duplicate of #9861 and has been fixed in #9999, which will be included in the next release _after_ v8.1.6.

Please follow the [workaround steps in @tmashuang 's comment](https://github.com/MetaMask/metamask-extension/issues/9818#issuecomment-737714510) to restore your contacts in the meantime.

**Closed by Gudahtt** 2020-12-07 20:18 UTC
Labels: S2-normal, T00-bug
