### ISSUE TITLE
[Bug]: Firefox blank screen

### ISSUE THREAD

**Issue by malcolm-dane** [MetaMask/metamask-extension#14838] opened 2022-06-03 00:11 UTC
### Describe the bug

Firefox all versions. Metamask fails to open. This is on three different computers.

Uninstall, reinstall, of metamask and of firefox did not help. It just is a white blank.

### Steps to reproduce

1.Download Firefox, update to latest. Install metamask. Allow for incognito, and attempt to load.

### Error messages or log output

```shell
None. 10.14.7
```

### Version

10.14.7

### Browser

Firefox, Microsoft Edge

### Operating system

Windows, Linux

### Additional context

IT also fails on Edge it appears. My friends won't connect despite numerous attempts. Maybe stop using sentry.js to collect our data.

**Comment by seaona** [comment] 2022-06-03 11:03
@malcolm-dane is it only happening with Incognito mode? or are you seeing the same behaviour with regular Firefox/Edge?

**Comment by malcolm-dane** [comment] 2022-06-03 13:26
![metafail](https://user-images.githubusercontent.com/11442006/171863238-e6a2b1ac-9111-4893-8ba2-ddfeae079d07.png)

**Comment by malcolm-dane** [comment] 2022-06-03 13:30
It is happening on clean install, clean cookie and cache, security settings restored to default, security settings turned off, advanced security settings turned off, other extensions turned off,other  extensions uninstalled, incognito, and regular. It just shows a white out.  On edge, and this is from a video call yesterday, it seems to disappear even with active notifications. It will appear, but doesn't goto background, it just closes and you have restart the browser.

**Comment by digiwand** [comment] 2022-06-03 18:24
hm... MetaMask appears to work fine on my macOS, Firefox versions 100.x and 101.0. Sorry you're running into this issue and thank you for reporting this! 

Question: Where it says `TypeError: e is undefined in the console`, can you expand this and send us the output there please? Hopefully, we can get enough information here to see what the problem is. 

It might help to [send a state log](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-to-download-state-logs) with a support ticket: https://metamask.zendesk.com/hc/en-us.

**Comment by malcolm-dane** [comment] 2022-06-12 03:00
I can't access the state, or interact with the extension in any way. The only reason I was able to do it that time, was because at first install it briefly will allow me to ctrl shift I to the console. Only on the first run. It doesn't like what sentry is doing.

**Comment by malcolm-dane** [comment] 2022-06-12 03:05
![m2](https://user-images.githubusercontent.com/11442006/173212492-45bd9bfa-4aa8-4a58-b073-dcee077ad8b1.png)

**Comment by malcolm-dane** [comment] 2022-06-12 03:07
https://gist.github.com/malcolm-dane/901199bfe71c2ab44b84d3bbf3ee4ebc

**Comment by kevinghim** [comment] 2022-06-13 18:32
Could be related to #9196

**Comment by digiwand** [comment] 2022-06-22 00:30
Hi @malcolm-dane,

Is this no longer an issue? If so, could you please share how you resolved this issue? 

I saw that you recently created a new issue, https://github.com/MetaMask/metamask-extension/issues/14998. It appears that version 10.14.6 is not producing a blank screen for you at this time.

**Comment by digiwand** [comment] 2022-06-22 01:05
I also want to clarify something you mentioned: 
> Maybe stop using sentry.js to collect our data.

under **Additional context**. We are not logging any personal, confidential, or sensitive information (PII) sent to Sentry. MetaMask does not collect or store any personally identifiable information. We are using Sentry to simply monitor, catch, and respond to any bugs that may occur in our application.

**Comment by digiwand** [comment] 2022-08-18 03:56
This issue instance appears to have been resolved. It might also be a duplicate as mentioned by @kevinghim. Closing this issue.

**Closed by digiwand** 2022-08-18 03:56 UTC
Labels: type-bug
