### ISSUE TITLE
Metamask-extension blocks sending messages from Nakama.js 

### ISSUE THREAD

**Issue by OlegVitiuk** [MetaMask/metamask-extension#5533] opened 2018-10-16 16:45 UTC
MetaMask injects its content scripts into all frames, including the frame that uses Nakama.js for online games. Metamask changes postmessage and this changes conflict with Nakama.js

**To Reproduce**
1. Create a test nakama server
2. Create simple client https://heroiclabs.com/docs/javascript-client-guide/
3. Install metamask-extension to your browser
3. Try to send some message to the server https://heroiclabs.com/docs/gameplay-matchmaker/ with active metamask extension

**Expected behavior**
Sending message with data doesn't work

**Screenshots**
![image](https://user-images.githubusercontent.com/19871720/47032526-3da1da00-d17b-11e8-820e-8557447e02df.png)

**Browser details (please complete the following information):**
 - Windows 10
 - Chrome
 - MetaMask Version 4.14.0
 - Old UI

this issue is related to #2737

**Comment by whymarrh** [comment] 2018-10-16 20:30
> this issue is related to #2737

#2737 is a bug with the site (Instapage in that case), are you suggesting this is a bug with Nakama?

**Comment by whymarrh** [comment] 2018-10-16 20:33
Also would you mind clarifying the expected behaviour here? You have "sending [...] doesn't work" in the description, what should and shouldn't work exactly?

**Comment by maxie-max** [comment] 2018-10-16 20:52
> Also would you mind clarifying the expected behaviour here? You have "sending [...] doesn't work" in the description, what should and shouldn't work exactly?

Metamask is capturing all messages and not bypassing the messages it does not consume

**Comment by whymarrh** [comment] 2018-10-17 22:46
@maxie-max thanks for the clarification, it would be helpful if you could provide a reduced test case (creating a Nakama server and client is a lot to setup) or an example app maybe

**Comment by maxie-max** [comment] 2018-10-18 07:04
@whymarrh OK, here you may find an [example app](http://staging.playchap.io/) (in development stage...)
Test users: 
test1@playchap.com | letmein123
test2@playchap.com | letmein123

Please review the [video](https://www.youtube.com/watch?v=Erl1LrzQGhY) first to get the idea on how to reproduce the bug.

Hope that helps

**Comment by maxie-max** [comment] 2018-11-07 10:21
> @whymarrh Sure, here you may find an [example app](http://staging.playchap.io/) (still under heavy development)
> 
> Test users:
> [test1@playchap.com](mailto:test1@playchap.com) | letmein123
> [test2@playchap.com](mailto:test2@playchap.com) | letmein123
> 
> You would need to open 2 browsers simultaneously - at least one must have MetaMask extension enabled and logged in.
> Please review the [video](https://www.youtube.com/watch?v=Erl1LrzQGhY) first to get the idea on how to reproduce the bug.
> 
> Hope that helps

Small update. Due to the aforementioned bug which hasn't been fixed, we had to move the game out of iframe embedding it directly to the app. Therefore the test scenario which is described earlier can't be reproduced any longer. It is a temporary solution though ...
Having said that, the bug still is a huge issue for those who are using iframes and sending messages from iframe to parent as an object via Window.postMessage()

**Comment by maxie-max** [comment] 2018-11-09 15:36
@whymarrh Apparently, this issue is directly related to [issue#5286](https://github.com/MetaMask/metamask-extension/issues/5286)

**Comment by danfinlay** [comment] 2021-01-19 20:51
This is a problem with how nakama is over-confidently interpreting `postMessage` messages as its own. The `postMessage` event space is shared, and so developers need to code defensively.

In [this comment](https://github.com/MetaMask/metamask-extension/issues/5286#issuecomment-468122063), we see a workaround by simply checking for messages that MetaMask is sending to itself, like this:
```javascript
// example iframe
const iframe = document.createElement('iframe')
iframe.setAttribtute('src', 'https://example.com')
document.body.appendChild(iframe)
const iwindow = iframe.contentWindow

// example event listener
window.addEventListener('message', event => {
  if (event.source === iwindow) { // filters out ALL messages from other sources than `iwindow`
    // no metamask messages will get logged here
    console.log(event.data)
  }
})
```
This solution would need to be built into nakama.js, and so I will open an issue there, and am closing this issue here for now.

**Closed by danfinlay** 2021-01-19 20:51 UTC
Labels: L01-injection, N02-needsReproduction, S2-normal, T00-bug, needs-triage
