### ISSUE TITLE
Empty dialog extension

### ISSUE THREAD

**Issue by simoneromanelli** [MetaMask/metamask-extension#3619] opened 2018-03-19 20:40 UTC
Hi 
I installed the extension on chrome Version 52.0.2743.116 (64-bit)
metamask 4.2.0 on my Ubuntu 14.04.5 LTS and when I click on the shortcut the dialog is blank. 

![metamask](https://user-images.githubusercontent.com/9480700/37621010-16fd60d0-2bbe-11e8-819b-bc1fbff1c2fb.jpg)

Thanks

**Comment by lazaridiscom** [comment] 2018-03-19 20:46
Sorry for not displaying a concrete error-message:

Your browser version is not support, see: https://github.com/MetaMask/metamask-extension/issues/3505#issuecomment-372049787

**Comment by danfinlay** [comment] 2018-03-19 21:17
Hoping to fix this soon, closing as duplicate of #3505

**Closed by danfinlay** 2018-03-19 21:17 UTC
