### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Trulexbob** [MetaMask/metamask-extension#10130] opened 2021-01-01 12:42 UTC
When I try to change gas limit to 21000 it shows me error.There is link. 
Pls help

-- Including our issue template to help provide the necessary details -- 

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by brad-decker** [comment] 2021-01-01 16:27
@Trulexbob -- your state logs are truncated in gist, and we generally don't recommend sharing them publicly. I recommend removing the gist link from the issue, and [opening a new ticket](https://metamask.zendesk.com/hc/en-us/requests/new) with our support team. There is a place to include your state logs there in a way where they won't be truncated.

I'd also ask that you include details of the error you are being shown, including screenshots, the version of MetaMask you are using, and the browser. Steps to reproduce are also very helpful for our team!

I've edited your original post to include the issue template for you to help make sure we get enough details to be of assistance!

**Comment by Gudahtt** [comment] 2021-01-05 21:49
I'll close this for now, since there isn't enough information yet for us to act. Please fill out the template next time to the best of your ability!

**Closed by Gudahtt** 2021-01-05 21:49 UTC
Labels: N03-needsInformation, T00-bug
