### ISSUE TITLE
Custom Spend Limits not reflected in submitted transaction.

### ISSUE THREAD

**Issue by adamdossa** [MetaMask/metamask-extension#7915] opened 2020-01-27 17:44 UTC
When approving a spend of DAI, modifying the "Permission" to change the spend limit (using the "Custom Spend Limit" box) doesn't impact the transaction data.

As per screenshot I modified the custom spend limit to 5,000 DAI - this doesn't impact the approved amount in the transaction data which is still fff.fff (i.e. the original maximum limit).

This seems potentially very dangerous behaviour.

<img width="349" alt="Screenshot 2020-01-27 at 13 40 08" src="https://user-images.githubusercontent.com/2633913/73199361-17ebda80-410b-11ea-980c-1e12b77e7f22.png">

**Comment by Gudahtt** [comment] 2020-01-28 00:21
Thanks for the report! I have managed to reproduce this problem.

It looks like the transaction data is in fact being set correctly, but the UI isn't updating. In my attempts to reproduce this, I confirmed on etherescan that the amount was modified correctly. Let me know if your case was different.

**Comment by adamdossa** [comment] 2020-01-28 12:01
When I got the error, the transaction actually executed including the original spending limit (i.e. not just a UI issue). Happy to jump on a screen share to reproduce the bug with you if that's helpful.

**Comment by Gudahtt** [comment] 2020-01-28 13:45
I've fixed a related UI bug, but I'm going to continue trying to reproduce the error you're describing where the final transaction retains the original limit.

**Comment by Gudahtt** [comment] 2020-01-28 17:30
I'm going to close this as a duplicate of #7735, as that appears to be the same issue. I'll continue the investigation over there.

**Closed** 2020-01-29 02:49 UTC
Labels: T00-bug
