### ISSUE TITLE
[Bug]: Import account allows you to use the private key of an account derived from the seed phrase of the active wallet

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-extension#20670] opened 2023-08-30 20:43 UTC
### Describe the bug

Import account allows the user to import a private key that is derived from the seed phrase of the active wallet. Using Create account after this will cause a duplicate account to appear in MetaMask.

### Steps to reproduce

1. In one instance, MetaMask A, use Add account to create an Account 2 and have the private key for this account ready
2. In a different instance, MetaMask B, restore the wallet using the seed from MetaMask A
3. In MetaMask B, select Import account and use the private key from Account 2 in MetaMask A
4. In MetaMask B, use Add account, which will create a duplicate Account 2

https://recordit.co/IV9eT4ArHB

### Error messages or log output

```shell
at r.default.setAccountLabel (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:12:79242)
  at s.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:186275)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:36942
  at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:37012)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79414)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79229)
  at y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:80043)
  at e.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:26:327181)
  at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:92654)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:95838
  at b.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:95865)
  at t.exports.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:84614)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:36942
  at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:7:37012)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79414)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:79229)
  at y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:80043)
  at t.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:294186)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:16:294033
```

### Version

10.35.0

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by plasmacorral** [comment] 2023-08-30 21:42
Duplicate of https://github.com/MetaMask/metamask-extension/issues/14601

**Closed by plasmacorral** 2023-08-30 21:42 UTC
Labels: type-bug
