### ISSUE TITLE
"Sent Token" history incorrectly shows contract address as recipient

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-extension#6335] opened 2019-03-22 18:27 UTC
**Describe the bug**
"Sent Token" history incorrectly shows contract address as recipient

**To Reproduce**
1. Make an ERC20 token transfer
2. Look at "Sent Token" history

**Expected behavior**
Show the token recipient, not the contract address

**Screenshots**
<img width="347" alt="Screen Shot 2019-03-22 at 2 23 57 PM" src="https://user-images.githubusercontent.com/1577353/54844927-6c822600-4cae-11e9-974d-5332d9107cc7.png">

**Additional context**
Etherscan transaction:
https://rinkeby.etherscan.io/tx/0x883471b4c8dc416b0e39e1d010ec9729326ee7fbc7486e6d99b45b24894c5669

**Comment by bdresser** [comment] 2019-03-25 19:18
duplicate of https://github.com/MetaMask/metamask-extension/issues/5257

**Closed by bdresser** 2019-03-25 19:18 UTC
