### ISSUE TITLE
Using browser nav to go back on full-screen onboarding causes issues

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#6240] opened 2019-03-05 18:52 UTC
**Describe the bug**
The extension does not take into account when a user has pressed 'back' on the browser to navigate to a previous screen on onboarding.
**To Reproduce**
1. Get to onboarding for MetaMetrics
2. Choose 'no thanks'
3. Navigate back using your browser's back button.
4. Attempt to press 'no thanks' again
5. Cannot proceed without clicking 'I agree'

**Expected behavior**
I should be able to click 'no thanks' as many times as I darn please and proceed to the next screen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - MetaMask Version 6.2.0

**Comment by danjm** [comment] 2019-03-05 19:47
@Zanibas I am not able to reproduce. Are you seeing any errors in the console?

**Comment by tmashuang** [comment] 2020-02-05 18:25
This seems to have been fixed. Closing.

**Closed by tmashuang** 2020-02-05 18:25 UTC
Labels: L03-UI, N02-needsReproduction
