### ISSUE TITLE
"Known Contract Address" alert is confusing for token sends

### ISSUE THREAD

**Issue by GriffGreen** [MetaMask/metamask-extension#10062] opened 2020-12-11 18:59 UTC
**Describe the bug**

Confusing pop up about an address being a contract address

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Send 
2. Click on asset 
3. Scroll down to any token

![Screen Shot 2020-12-11 at 1 47 04 PM](https://user-images.githubusercontent.com/14945613/101943109-d95bf300-3bea-11eb-9525-316c1a0756fa.png)

This made me thing the address i was sending to was a contract address.... but its not.

**Expected behavior**
Despite interacting with a contract when making a token send, Metamask should be aware that the user thinks they are sending dai to an address... not interacting with a contract. 

The Alert should not pop up!

**Browser details (please complete the following information):**
 - OS: MacOC Catalina
 - Hardware Wallet: no
 - Browser: brave Version 1.17.75 Chromium: 87.0.4280.88 (Official Build) (x86_64)
 - MetaMask Version: 8.1.6

**Comment by Gudahtt** [comment] 2020-12-11 19:52
Thanks for the report! This is a duplicate of #10044, which was fixed very recently and will be included in the next release.

This warning has been around for years, but it's not supposed to be shown in this case. This was a regression.

**Closed by Gudahtt** 2020-12-11 19:52 UTC
