### ISSUE TITLE
Invariant Violation: Minified React error #31

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3690] opened 2018-03-22 19:26 UTC
https://sentry.io/metamask/metamask/issues/501017473/

```
Invariant Violation: Objects are not valid as a React child (found: Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=SyntaxError%3A%20Unexpected%20token%20%3C%20in%20JSON%20at%20position%200&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.).
  at t.exports (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1462282)
  at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1464998)
  at t.exports (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1465093)
  at Object.instantiateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1363748)
  at K._reconcilerInstantiateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1420456)
...
(45 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment] 2018-03-22 19:27
possibly related? https://github.com/metamask/metamask-extension/issues/3688

**Comment by danjm** [comment] 2018-04-09 14:41
This is a duplicate of #3688

**Closed by danjm** 2018-04-09 14:41 UTC
Labels: L03.1-newUI/UAT, P2-sooner, T00-bug
