### ISSUE TITLE
[Bug]: Error: Transaction reverted: function selector was not recognized and there's no fallback function

### ISSUE THREAD

**Issue by PatrickAlphaC** [MetaMask/metamask-extension#14963] opened 2022-06-15 21:08 UTC
### Describe the bug

I have created this issue on the hardhat github & the moralis github, and both locations have directed me to metamask instead. 

https://github.com/NomicFoundation/hardhat/issues/2708
https://github.com/MoralisWeb3/react-moralis/issues/257

I have a small contract that looks like such:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract FundMe {
    address public s_someAddress;

    constructor(address someAddress) {
        s_someAddress = someAddress;
    }

    function fund() public payable {
        // do stuff
    }
}
```

That is deployed to the hardhat network. When I call `fund` from the frontend using [ethers](https://docs.ethers.io/v5/getting-started/#getting-started--importing--web-browser), I get the following error in the terminal my hardhat node is running:

```
eth_call
  Contract call:       <UnrecognizedContract>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0xe7f1725e7734ce288f8367e1bb143e90bb3f0512)
      at HardhatNode.runCall (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
      at EthModule._callAction (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at Server.JsonRpcHandler.handleHttp (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

However, if I approve the transaction on the front end, it goes through fine. Any code that I have in the `fund` function is successful.

What is happening? 

I have reset my metamask account several times. Here is how I'm calling this function from the front end:

```javascript
async function fund() {
  const ethAmount = "0.1"
  console.log(`Funding with ${ethAmount}`)
  if (typeof window.ethereum !== "undefined") {
    const provider = new ethers.providers.Web3Provider(window.ethereum)
    const signer = provider.getSigner()
    const contract = new ethers.Contract(contractAddress, abi, signer)
    const transactionResponse = await contract.fund({
      value: ethers.utils.parseEther(ethAmount),
    })
  }
}
```

### Steps to reproduce

1. Clone the repo and install dependencies
```
git clone https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc
cd hardhat-smartcontract-lottery-fcc
yarn
```

2. Run the hardhat node
```
yarn hardhat node
```

3. Add the hardhat network to your metamask & import one of the private keys from the hardhat nodes output 

(Let me know if you need help doing this)

4. Then, in a new terminal, clone the UI repo, and install dependencies

```
git clone https://github.com/PatrickAlphaC/nextjs-smartcontract-lottery-fcc
cd nextjs-smartcontract-lottery-fcc
yarn
yarn dev
```

Go to the UI, and try to hit the `Enter Lottery` button, and in your terminal, you'll get this issue:

```
th_call
  Contract call:       <UnrecognizedContract>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0xe7f1725e7734ce288f8367e1bb143e90bb3f0512)
      at HardhatNode.runCall (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
      at EthModule._callAction (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at Server.JsonRpcHandler.handleHttp (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

### Error messages or log output

```shell
th_call
  Contract call:       <UnrecognizedContract>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0xe7f1725e7734ce288f8367e1bb143e90bb3f0512)
      at HardhatNode.runCall (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
      at EthModule._callAction (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at Server.JsonRpcHandler.handleHttp (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

### Version

10.14.6

### Browser

Brave

### Operating system

MacOS

**Comment by brian-tam** [comment] 2022-06-16 02:01
Hi Patrick I have a similar issue while working on the HTML FundMe app. Is it metamask problem..?

`eth_call
  Contract call:       FundMe#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: Transaction reverted: function selector was not recognized and there's no fallback function`

**Comment by elijahhampton** [comment] 2022-06-21 03:32
I am having the same issue using ethers, hardhat and metamask using the same reproduction steps with my own UI and smart contract of course.

**Version**
10.15.0

**Build Type**
No Response

**Browser**
Chrome

**Operating System** 
MacOS

**Hardware Wallet**
No response

**Additional Context**
No response

**Comment by RobertoDonPedro** [comment] 2022-06-28 15:57
I get this error with Hardhat, too.
`  Error: Transaction reverted: function selector was not recognized and there's no fallback function`

But it works with Rinkeby...

**Comment by brian-tam** [comment] 2022-06-29 04:21
> I get this error with Hardhat, too. ` Error: Transaction reverted: function selector was not recognized and there's no fallback function`
> 
> But it works with Rinkeby...

Yes once I see it works with Rinkeby and was deployed successfully, I ignore the error and continue the course. I believe it might be the problem of metamask or moralis.. or the integration of both.

**Comment by PatrickAlphaC** [comment] 2022-06-30 15:34
Can you click the gitpod button of this repo? 

https://github.com/PatrickAlphaC/hardhat-fund-me-fcc

Then run:

```
yarn hardhat node
```

Grab a private key from the output and import into metamask - and add the hardhat localhost network to metamask. 

Then, gitpod button for this repo:

https://github.com/PatrickAlphaC/html-fund-me-fcc

Spin up the UI, enter a number and select "fund".

**Comment by BelfordZ** [comment] 2022-07-01 07:47
It appears your transaction is being reverted. Hardhat/ganache will respond with the Transaction Reverted error immediately, whereas testnets will mine the transaction, and revert can be found by looking at the transaction receipt.

Please double check your smart contract, and check the receipt status of the transaction when you try it on testnet - it likely is also reverting without reason.

If you are still having this issue, pull out the relevant code into the smallest example you can still reproduce the issue with, and post that code back here so that we can get to the bottom of this. I will close the issue for now until the issue is made more clear.

**Closed by BelfordZ** 2022-07-01 07:47 UTC
Labels: type-bug, needs-reproduction, area-api

**Comment by jorgelannister** [comment] 2022-07-04 09:23
> 

Hello Patrick, 
I am not sure if this helps, but if I run everything on a Ganache Local host instead of a Hardhat local node, everything works fine. So the problem might be also something related to the hardhat node (or maybe the interaction between that and Metamask)

**Comment by PatrickAlphaC** [comment] 2022-07-06 00:27
Maybe I'm just big dummy. That happens sometimes too. 

Thanks all, sorry for the ruckus... I'll see if I can reproduce again...

**Comment by leonfancy** [comment] 2022-07-07 06:54
I got the same issue with hardhat node, too.

**Comment by marcosmartinez7** [comment] 2022-07-07 17:54
Same issue with hardhat using `useDapp`, transaction is successful but hardhat receives invalid calls after that

See the `console.log` represent the correct behavior, and immediately it receives invalid calls. Maybe metamask is resending some tx? 

<img width="406" alt="image" src="https://user-images.githubusercontent.com/14795944/177838226-4284671d-f8fb-407a-8dce-dbb0e1e279d3.png">

**Comment by BigTava** [comment] 2022-07-14 16:46
Same issue here! It happens when I call a function that requires signing the transaction.

**Comment by sheinix** [comment] 2022-07-18 08:26
Exactly the same issue here as well. For some reason Metamask interaction with hardhat node goes through but hardhat receives invalid calls

**Comment by NitroSOPrivate** [comment] 2022-07-19 07:57
Has anyone found any solution for this error?

**Comment by andreupifarre** [comment] 2022-07-26 06:29
any updates? I am getting the same errors

**Comment by CamArmstr** [comment] 2022-08-01 19:11
Also getting a similar error here w/ hardhat and [ethers](https://docs.ethers.io/v5/getting-started/#getting-started--importing--web-browser) on a local chain.

The transaction will go through fine, it just throws multiple of these error messages

![image](https://user-images.githubusercontent.com/52431864/182227469-7234f391-ca94-46d9-ab9c-e2b9dec67cf2.png)

**Comment by mitya-zilbs** [comment] 2022-08-02 01:51
I am encountering this issue as well, but it seems to me that the transaction is going through because if I console log the transaction hashes, confirmations, and amounts, everything shows up correctly in the console., as well as in my Metamask wallet where all of the transactions and their data are displayed, and the test eth is taken out of the wallet. So I think its just a localhost issue with Hardhat where it posts the response as being reverted before the transaction is confirmed on metamask.

**Comment by umair-mirza** [comment] 2022-09-21 12:59
The fix for this issue is pretty simple.

Steps:
1- In your Metamask, for the selected account, Go to Settings.
2- Click on 'Advanced'
3- Click on "Reset Account'

Then try to do the transaction. It will work :)

**Comment by pacmac0** [comment] 2022-10-10 15:45
> The fix for this issue is pretty simple.
> 
> Steps: 1- In your Metamask, for the selected account, Go to Settings. 2- Click on 'Advanced' 3- Click on "Reset Account'
> 
> Then try to do the transaction. It will work :)

Unfortunately for me, it does not fix the issue of the unrecognized selector calls displayed in the console. Is there any progress with this issue? Or anyone has an alternative solution? 
Could it maybe be due to a newer/incompatible version of moralis, hardhat or so?

**Comment by tariqthecoder** [comment] 2022-10-11 16:13
I am also facing the same issue, have anyone solved it, Error: Transaction reverted: function selector was not recognized and there's no fallback function

**Comment by pacmac0** [comment] 2022-10-12 09:09
> I am also facing the same issue, have anyone solved it, Error: Transaction reverted: function selector was not recognized and there's no fallback function

As it was discussed in other  issues, this might be an interaction problem within  hardhat, metamask or so. I ignored the hardhat node console error for now and moved on. The frontend interaction seems to work anyway and the transactions seem to happen, since number players and so on are being updated. I also hope someone will come up with an explanation for the phenomenon thou.

**Comment by egvandell** [comment] 2022-11-13 20:48
Still seeing this issue as well

**Comment by egvandell** [comment] 2022-11-13 20:51
Still seeing this issue as well.  I did some additional testing and noted that if you run a test with a view function instead of a payable function, the error is not generated.

**Comment by egvandell** [comment] 2022-11-13 20:53
It may be obvious, but since I didn't see it mentioned in the thread I thought worth mentioning....that I did some additional testing and noted that if you run a test with a view function instead of a payable function, the error is not generated in the node output, and it operates as expected in this case.

**Comment by AndyOooh** [comment] 2022-11-17 14:22
Same issue here. Also, unable to debug. Resolved to the fallback/receive work around.

**Comment by DrGreeny** [comment] 2022-11-18 07:16
For me this error was due to a wrong chainId in Metamask. I had some problems with Id: 1337 and used 31337. Metamask was on 1337 still, so after I changed this it worked (also did a reset). Maybe you could check your chainId settings in hardhat and Metamask.

**Comment by HashHaran** [comment] 2022-11-23 06:22
I wouldn't be very sure if this is a metamask issue. When I faced this issue, no solution I found online seemed to work. I tried to use [anvil](https://book.getfoundry.sh/anvil/), a local Ethereum development node by [foundry](https://www.paradigm.xyz/2021/12/introducing-the-foundry-ethereum-development-toolbox), in place of hardhat node. This seems to solved the issue for me. I am able to continue my testing in my local node. I believe the issue is somewhere in the metamask and hardhat local node integration.

**Comment by techybolek** [comment] 2023-01-29 17:37
Same problem here.
```
 Contract call:       FundMe#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

```

**Comment by MemoBaca** [comment] 2023-02-11 03:49
[smartcontractkit/full-blockchain-solidity-course-js#315 (comment)](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/315#discussioncomment-3937306) explains the issue and how to fix it.

**Comment by SyedImam1998** [comment] 2023-04-01 09:33
Currently, i am facing same issue. Did anyone resolve this issue

![image](https://user-images.githubusercontent.com/52135949/229278199-81515089-7a49-46df-a041-c61a7158d783.png)

**Comment by SyedImam1998** [comment] 2023-04-01 09:39
Found something interesting look at here. My first call to setname was successfully done. later 5 calls were made to the contract which all eventually failed but the first call which was succeed changed the state of the contract.

why there is 5more calls happened from meta mask?????

![image](https://user-images.githubusercontent.com/52135949/229278376-da50f55b-7ed3-47f9-823f-150ea7da4090.png)

**Comment by MemoBaca** [comment] 2023-04-01 09:46
@SyedImam1998 Metamask makes a lot of "random" RPC calls. Check [this issue](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/315#discussioncomment-3937306) and [this issue](https://github.com/MetaMask/metamask-extension/issues/15372) for further reading.

**Comment by SyedImam1998** [comment] 2023-04-01 09:53
@MemoBaca Thanks mate i have added this fallback function now at least this is not throwing error like before:
```
 fallback() external payable {
       
    }
```
![image](https://user-images.githubusercontent.com/52135949/229279203-a49971b7-9825-4533-9eb1-051f7ed649d0.png)

**Comment by netzulo** [comment] 2023-04-14 02:49
If want to protect your users, use this, not payable for fallback calls :D
```
/// @dev DON'T give me your money.
  function () external {}
```

**Comment by bruce2233** [comment] 2023-05-02 11:42
Same issue still

**Comment by vladimir-byshevets** [comment] 2023-06-25 16:44
Hello, I have a similar problem 
![3](https://github.com/MetaMask/metamask-extension/assets/107269761/37a5ad2b-98ba-4956-aaa3-4c6b4c92b9d8)

**Comment by vladimir-byshevets** [comment] 2023-06-25 16:45
Send button not active
![2](https://github.com/MetaMask/metamask-extension/assets/107269761/cd8dec67-3027-43a6-9803-535afbd7c02e)

**Comment by vladimir-byshevets** [comment] 2023-06-25 16:47
Here is the function
![1](https://github.com/MetaMask/metamask-extension/assets/107269761/c827b2ef-b7b0-4e42-b7ce-2e4721f2b369)

**Comment by vladimir-byshevets** [comment] 2023-06-26 11:06
Решил проблему добавлением в файл - hardhat.configю.js код
module.exports = {
  solidity: "0.8.18",
  networks: {
    hardhat: {
      initialBaseFeePerGas: 0,
    },
  },
};
, а так-же добавил в конец кода функцию - fallback() external payable {}
Очистил Метамаск, перезапустил hardhat и всё заработало!

**Comment by thepop42** [comment] 2023-08-29 16:40
Hi,
I have still the same error. 
1/ Is the failback function solves this issue ?
2/ What means a function selector was not recognized as my function was executed

**Comment by nuliknol** [comment] 2023-10-04 20:18
@vladimir-byshevets by creating a fallback() function you just obfuscated the problem, now all calls (which the method doesn't implement) go into fallback() where they silently dropped and you never figured out what is the real cause

**Comment by vladimir-byshevets** [comment] 2023-10-05 09:22
> @vladimir-byshevetsсоздав функцию Fallback(), вы просто запутали проблему, теперь все вызовы (чьи методы не реализуются в контракте) переходят в Fallback(), где они молча удаляются, и вы так и не поняли, в чем настоящая причина

Критикуешь - предлагай!. Если я не правильно сделал, то как правильно?

**Comment by tanim0la** [comment] 2023-12-16 09:04
To resolve this, add a fallback function in your contract:

`fallback() external payable {}`

**Comment by nuliknol** [comment] 2024-01-10 00:49
> > @vladimir-byshevetsсоздав функцию Fallback(), вы просто запутали проблему, теперь все вызовы (чьи методы не реализуются в контракте) переходят в Fallback(), где они молча удаляются, и вы так и не поняли, в чем настоящая причина
> 
> Критикуешь - предлагай!. Если я не правильно сделал, то как правильно?

you can actually setup tcpdump program and sniff all the traffic that is coming over TCP connection (provided plain HTTP is used and not HTTPS) , when I did that I discovered that Metamask is calling decimals() method on the contract when the popup window with transaction details appears to the end User. This is what is causing this error. Obviously Metamask shouldn't do it, but if you want to get rid of this error and have clean hardhat log for debugging purposes you can just declare decimals() in your contract for the time you are developing (and later remove it). Fallback function will just hide all the calls to the contracts that are unsupported and you will have less development power to see what is going on. The other option is to throw Metamask to the trash.
@vladimir-byshevets

**Comment by maoaixiao1314** [comment] 2024-01-24 06:26
I also encountered the same problem with the hardhat and metamask versions. I lowered the metamask version to 10.17.0 and the problem was resolved 
  If there are still problems, you need to modify the chain of hardhat, which defaults to 31337. Try changing it to 1337
