### ISSUE TITLE
[Bug]: Preventing injection for docs.google.com is too encompassing and prevents any website that just has docs.google.com in a query parameter from accessing Metamask.

### ISSUE THREAD

**Issue by brianfakhoury** [MetaMask/metamask-extension#16059] opened 2022-10-03 18:22 UTC
### Describe the bug

I'm working on a side project where "docs.google.com" is a necessary component in my URL query params. I'm unable to connect to Metamask as it doesn't inject on my site, even though the domain is something completely different.

### Steps to reproduce

1. Add `?test=docs.google.com` to any website. `window.ethereum` is no longer available.

### Version

10.19.0

### Browser

Brave

### Operating system

MacOS

**Comment by bschorchit** [comment] 2022-10-04 22:00
This is likely caused by: https://github.com/MetaMask/metamask-extension/pull/15459 which could be reverted as the original issue https://github.com/MetaMask/metamask-extension/issues/15374 turned out to be caused by Brave and was fixed by them already ( https://github.com/brave/brave-core/pull/14483 )

**Comment by brianfakhoury** [comment] 2022-10-05 18:46
Is there an issue to revert this yet? I don't see one, I can submit a PR if not.

**Comment by ryanml** [comment] 2022-10-11 15:05
Closed via: https://github.com/MetaMask/metamask-extension/pull/16154

**Closed by ryanml** 2022-10-11 15:05 UTC
Labels: type-bug, area-injection, browser-brave, Sev2-normal
