### ISSUE TITLE
Metamask dropped all but one wallet for no reason 

### ISSUE THREAD

**Issue by radu123ca** [MetaMask/metamask-extension#3965] opened 2018-04-12 12:24 UTC
I was using 3 or 4 ethereum wallets on one metamask account. I had no issues exporting the seed to another computer and having access to the accounts from there.  About a month ago metamask started crashing google chrome frequently, so I started to use internet explorer. Yesterday when I tried logging into metamask, I could not do it. I was forced to restore the account from seed phrase, and only 1 wallet was displayed.

This is troubling for me because I had made another wallet under metamask that had some funds in it, and now that wallet is gone. The funds are still in the same wallet, according to etherscan.io. 

I never received a separate seed or private key for that wallet in question when I created it through meta mask. maybe there was one, but metamask never alerted me to one, I thought everything was recoverable through original seed, including loose accounts. 

Please help me. 

I would like to make an eddit, I managed to retrieve my funds, yayyy!!!
All I did was create a new account, and the account that was created happed to be the one with the finds in it under a generic name of Account2.  Very strange, please fix your browser extension or whatever it is, I don't want it to lose my funds or crash my browser.

**Comment by lazaridiscom** [comment] 2018-04-13 00:30
> All I did was create a new account, and the account that was created happed to be the one with the finds in it under a generic name of Account2

@radu123ca - Accounts are recreated (by design and standard) in the exact same order. Within MetaMask, this is a little bit misleading though - this known-issue is already filed here: #3424.

So, as this is already filed, and your issue is (gladly) solved, you can close this issue if you like.

**Comment by jrmoreau** [comment] 2018-04-13 16:57
Indeed, After restoring with your seed phrase you must click the "Create Account" button from the drop down menu - for each old account you had in your original installation you must add a new account. Currently we don't re-add them automatically. But if you follow this step it will add your other accounts in the order they were originally created.

**Closed by jrmoreau** 2018-04-13 16:57 UTC
