### ISSUE TITLE
Accounts and Network are not immediately set after Approved promise is resolved.

### ISSUE THREAD

**Issue by zlyojciec** [MetaMask/metamask-extension#5583] opened 2018-10-23 12:04 UTC
**Describe the bug**
`web3.eth.accounts` and `web3.version.network` is not immediately populated after resolved promise  `ethereum.enable()`

**To Reproduce**
1. Click on `APPROVE`
2. `web3.eth.accounts` and `web3.version.network` has to wait around 30ms to get populated (times are not consistent)
3. Same thing happen when host is already approved

**Expected behavior**
Account and Network variables should be set when `.enabled()` is resolved.

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Firefox, Opera
 - MetaMask Version 4.16.0
 - New / Beta UI / EIP-1102 / cf02009:

**Comment by simondlr** [comment] 2018-10-23 16:55
Just want report that this is fairly random to me. Sometimes it happens more frequently, sometimes it doesn't.

**Comment by bitpshr** [comment] 2018-10-23 17:52
Hi @zlyojciec and @simondlr, thanks very much for reporting this issue. The error was caused by a race condition between when the `ethereum#enable` Promise was resolved and when an internal MetaMask configuration store populated. This has been fixed as of 634121de6125d4faab5d815d981e62aff8946290 and new builds can be found [here](https://github.com/MetaMask/metamask-extension/pull/4703#issuecomment-432346488) to use for verification.

Don't hesitate to let us know if you experience any additional issues while testing.

**Closed** 2018-10-23 19:12 UTC
