### ISSUE TITLE
MetaMask: Failed to send site metadata

### ISSUE THREAD

**Issue by farhanJR** [MetaMask/metamask-extension#9819] opened 2020-11-06 18:44 UTC
**Metamask Failing to send site Metadata**
Our website which has is using Metamask and we did the updates as per the changes and it was working, but suddenly, Metamask started throwing the below the error on console and It asked to report this Bug.

`"MetaMask: Failed to send site metadata. This is an internal error, please report this bug."`

**Steps to reproduce (REQUIRED)**
Its on our website, so I don't know how to send the steps for this. But it's just open the website and open Dev Console and I see this errors. 

**Expected behavior**
I haven't seen this bug ever but just wanted to highlight the dev console message being received on dev console.

**Screenshots**
![image](https://user-images.githubusercontent.com/40184125/98402734-a7200a00-201c-11eb-8ade-66d37a12e59b.png)

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome Version Version 86.0.4240.183 (Official Build) (x86_64)
 - MetaMask Version: 8.1.3

**Additional context (Error Messages, etc.)**
Other Error Messages:

![image](https://user-images.githubusercontent.com/40184125/98402901-ea7a7880-201c-11eb-960e-e4d4cebc613a.png)

Also, I can see there are a lots of 404 when trying to get `inpage.js` via the MM extension:

`DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

Edit:

Also, when I try to do `ethereum.request({method: 'eth_requestAccoutns'})` or `ethereum.request({method: 'eth_accounts'})` i get the error (which I pasted above) adding below too.

`TypeError: this._processRequest(...).catch(...).finally is not a function
    at e._handle (inpage.js:15)
    at e.handle (inpage.js:15)
    at t.exports._rpcRequest (inpage.js:1)
    at inpage.js:1`

**Comment by rekmarks** [comment] 2020-11-09 19:08
This is a duplicate of #9823

**Closed by rekmarks** 2020-11-09 19:08 UTC
