### ISSUE TITLE
Disconnect event does not trigger

### ISSUE THREAD

**Issue by qmzik** [MetaMask/metamask-extension#10125] opened 2020-12-28 13:45 UTC
When I delete service from MetaMask extension, disconnect event does not call the function
![image](https://user-images.githubusercontent.com/26081016/103218413-fb17e280-492b-11eb-9b65-65ef8f14a446.png)

Code example:
`window.ethereum.on('disconnect', () => console.log('disconnected'));`

**Comment by rekmarks** [comment] 2020-12-31 21:21
@qmzik, that's because the `disconnect` event (specification [here](https://eips.ethereum.org/EIPS/eip-1193#disconnect)) has nothing to do with account permissions, which we call "connected sites" or "connected accounts" in the MetaMask UI. 

The event you should be listening for in this instance is `accountsChanged` (specification [here](https://eips.ethereum.org/EIPS/eip-1193#accountschanged)).

You can read more about provider events in our documentation [here](https://docs.metamask.io/guide/ethereum-provider.html#events), and how to use the provider [here](https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider).

Since this functionality is working as intended, I will go ahead and close this issue, but please let me know if you have any further questions.

**Closed by rekmarks** 2020-12-31 21:21 UTC

**Comment by Xeway** [comment] 2022-02-16 13:27
Thanks @rekmarks !
