### ISSUE TITLE
Events are not triggering even after successful transaction. 

### ISSUE THREAD

**Issue by Armaansharma** [MetaMask/metamask-extension#7060] opened 2019-08-22 15:25 UTC
I am using MetaMask as my wallet to complete the transaction. Now i am facing some issues in Metamask. These are as follows:
 1. Not able to add private Key showing incorrect password even i am writing right one.
 2. In my project events are not triggering even after successful transaction pop up. 

Browser: Chrome

Please try to fix this issue as soon as possible regarding the transaction update. Metamask should forward events to my app.

**Comment by Gudahtt** [comment] 2021-01-07 21:04
>Not able to add private Key showing incorrect password even i am writing right one.

This looks like a duplicate of #9077, which was fixed.

>In my project events are not triggering even after successful transaction pop up.

What "events" are you referring to? Could you provide steps to reproduce? Any additional information would be very helpful as well, such as browser version and MetaMask version.

**Comment by pbukva** [comment] 2021-01-19 02:22
Probably refereing to this:

**Comment by pbukva** [comment] 2021-01-19 02:27
It most probably means this - the code like bellow:
```js
const r = await web3.sendTransaction(...)
                      .on("transactionHash", ...)
                      .on("confirmation", ...)
                      .on("receipt", ...)
                      .on("error", ...)
```
is working as it supposed to for Metamask ver = 8.1.11 - I’m getting triggered all events (`transactionHash`, `confirmation` and `receipt`), I was lazy to test `error` case.

HOWEVER, it does NOT work for Metamask ver >= 9.0.0 -  tested that on both Firefox & Chrome browsers (using  web3 ver 1.2.2 (typescript’s @types/web3) in our TypeScript src behind the web page).

**Comment by BelfordZ** [comment] 2022-06-22 17:39
notes:

 - look into web3.sendTransaction - what is the expected return value? (likely should be returning the tx hash as per https://ethereum.org/en/developers/docs/apis/json-rpc/)

**Comment by Gtonizuka** [comment] 2022-08-04 13:51
I was looking into this today, it seems that the issue is on `web3` side.

Steps to reproduce:

- Use web3 or install legacy web3 MetaMask extension in Firefox
- paste
```
 window.web3.eth.sendTransaction({nonce: '0x00', // ignored by MetaMask
  to: '0x0000000000000000000000000000000000000000', // Required except during contract publications.
  from: window.ethereum.selectedAddress, // must match user's active address.
  value: '0x00', // Only required to send ether to the recipient from the initiating external account.
  data:
    '0x7f7465737432000000000000000000000000000000000000000000000000000000600057', // Optional, but used for defining smart contract creation and interaction.
  chainId: '0x3', // Used to prevent transaction reuse across blockchains. Auto-filled by MetaMask.
                                         }, () => console.log('FOOO'))
                      .on("transactionHash", () => console.log('transactionHash'))
                      .on("confirmation", () => console.log('confirm'))
                      .on("receipt", () => console.log('receipt'))
                      .on("error",() => console.error('aa'))
```
- Transaction goes through but no logs in console

**Closed by Gtonizuka** 2022-08-04 13:51 UTC
Labels: type-bug, needs-reproduction, needs-information, Sev2-normal, needs-triage, area-api
