### ISSUE TITLE
Slow/unresponsive browser makes Metamask autonomously skip key onboarding screens

### ISSUE THREAD

**Issue by pacamara** [MetaMask/metamask-extension#6496] opened 2019-04-23 06:08 UTC
**Describe the bug**
Some versions of Metamask can be induced to autonomously skip the "Your unique account image", "Secret Backup Phrase" and "Confirm Your Secret Backup Phrase" screens during apparently successful account setup. 

**To Reproduce**
1. Install metamask; Click past welcome screen; Fill in password fields
2. Open new tab and load misbehaving page, for example a bookmarklet which spams console.warn:
```javascript: var end=new Date().getTime()+60000; do {console.warn("foo");} while (new Date().getTime()<end); alert("DONE")```
3. Switch back to Metamask page
4. Click "Create"
5. After 60 seconds, close non-responding metamask page
6. Switch back to bookmarklet page and observe it's finished ("DONE" alert)
7. Open new tab
8. Open Metamask in popup mode
9. Version:
5.1.0: Metamask shows "Terms of use", "Privacy notice", "Phishing warning", then main account screen, i.e. Account Image and seed-word related onboarding screens never shown. 
5.2.2-6.1.0: Metamask shows "Secret Backup Phrase" screen, i.e. Account Image screen never shown.
10. User can use Metamask normally from here on, load funds, send funds, etc. Everything works normally.

**Expected behavior**
A slow browser should at worst slow down the extension, or cause account setup to fail. It should not cause Metamask to autonomously skip onboarding screens. With version 5.1.0, an inexperienced user could continue using the extension without knowing the seed words exist, and later not be able to recover the account.

**Browser details (please complete the following information):**
-Google Chrome on Linux
-Google Chrome on Windows (need --process-per-site option)
-Metamask version: 5.1.0 to 6.1.0

**Additional context**
Spamming console.warn is the easiest repro. But have also repro'd by spamming document.write, and just with a pure maths calculation. I.e. this issue is to do with timing and CPU load, not some pathological artifact of the console log.

It's not clear if the root cause of the issue has been fixed in latest version 6.3.1, or whether the design changes to remove the Account Image screen from onboarding, and always displaying the full page login screen even when opened in popup mode are just masking the underlying issue.

Initially reported as comment on https://github.com/MetaMask/metamask-extension/issues/3127

**Comment by bdresser** [comment] 2019-04-23 16:34
@pacamara do you experience the same behavior on the current version of MetaMask (6.3.2)?

**Comment by pacamara** [comment] 2019-04-23 19:18
@bdresser No. Problem does not occur in 6.3.2 either. But given the Account Image screen has been removed from onboarding, and opening metamask in popup mode always requires login now, it's not obvious if the root cause has been fixed. Perhaps the fragility in state transition in onboarding is still there and being masked by those changes.

**Comment by danfinlay** [comment] 2019-06-12 22:29
First of all, sorry for taking so long to reply to this. It was largely because of the strange ambiguity of this particular submission, and we wanted to be fair about it.

Since the skipping of the seed phrase was only reproduced in an earlier version, and only the account 
image screen was skipped in the current version, this doesn't really seem like it satisfies the criteria of a reproduction in the current codebase, and so is not eligible for the bounty prize.

We do acknowledge this involved some deep investigation on your part, so we've decided to award you a prize of 100 DAI to show our appreciation. 

Could you confirm your ether address from gitcoin of `0x0BcfEA5D16160143E10F6f651Fea938b924512Df`?

I'll leave the issue open so we can track fixing this skipping of the icon screen.

**Comment by pacamara** [comment] 2019-06-13 13:29
@danfinlay Thanks, that seems fair, and no worries about the delay. Yes that's the correct eth address. Cheers! :beers:

**Comment by danfinlay** [comment] 2019-06-13 16:22
Sent! `0xcd29f92cbfa980ffdb9fb571c5dc600efbecbc7a3236b58163a5f52259e7a9d8`

**Comment by pacamara** [comment] 2019-06-14 06:15
Thanks! :smile:

**Comment by kumavis** [comment] 2020-03-03 09:10
Closing this as the issue author states that it no longer presents itself

**Closed by kumavis** 2020-03-03 09:10 UTC
