### ISSUE TITLE
Metamask "Incorrect locale information"

### ISSUE THREAD

**Issue by GananciasBNB** [MetaMask/metamask-extension#11046] opened 2021-05-11 16:18 UTC
Metamask Versión: 9.5.0

Chrome Versión 90.0.4430.212 (Build oficial) (64 bits)

Mensaje: Incorrect locale information provided

Código: RangeError

Pila:
RangeError: Incorrect locale information provided
  at new DateTimeFormat (<anonymous>)
  at r.getTranslatedUINoficiations (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:86362)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:410446
  at Array.map (<anonymous>)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:410388)
  at ca (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:59367)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:104449)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:84094)
  at zu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:112010)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:113243
  at lu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87674)
  at Ku (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:113228)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:115151)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbe

**Comment by tmashuang** [comment] 2021-05-11 16:18
Duplicate of #11033

**Closed by tmashuang** 2021-05-11 16:18 UTC

**Comment by rafanake** [comment] 2021-05-28 13:53
Its not fixed yet!
