### ISSUE TITLE
Metamask extension displays empty window or does not respond at all

### ISSUE THREAD

**Issue by 7hKBg82PX** [MetaMask/metamask-extension#5447] opened 2018-10-07 15:29 UTC
> **Describe the bug**
> When clicking on the Chrome extension, Metamask does either not respond, shows an empty window (see screenshot), or a miniature empty window (see screenshot) instead of allowing me to log in. Interestingly, after making the screenshot of the big empty window, Metamask displayed the login page, yet still did not respond and disappeared.
> 
> **Steps to reproduce the behavior:**
> 
> 1. Open Google Chrome
> 2. Click on Metamask icon on the right of the screen
> 3. See error
> 
> **Expected behavior**
> For Metamask to open, display the login page, and allow me to log in.
> 
> **Browser details**
> 
> * Mac OS High Sierra 10.13.6
> * Chrome
> * Metamask version 4.13.0
> * old UI
> 
> **Screenshots:**
> <img alt="screen shot 2018-10-07 at 17 21 05" width="50" src="https://user-images.githubusercontent.com/32685272/46583368-1b5edc80-ca56-11e8-86e2-f15426b029b5.png">
> <img alt="screen shot 2018-10-07 at 17 20 47" width="1414" src="https://user-images.githubusercontent.com/32685272/46583369-1b5edc80-ca56-11e8-9926-5a7beef29a18.png">

**Comment by bdresser** [comment] 2018-10-07 23:56
closing as a duplicate of #4894, which has an open bug bounty. 

if you see any errors in the UI console or background console, please post on #4894 to help debug!

**Closed by bdresser** 2018-10-07 23:56 UTC
