### ISSUE TITLE
MetaMask Chrome extension high CPU usage on MacOS

### ISSUE THREAD

**Issue by chut** [MetaMask/metamask-extension#2754] opened 2017-12-15 19:15 UTC
Latest build of MetaMask on Chrome is extremely slow and utilizing tons of CPU when unlocked and open. Only seems to happen when a Dapp is autolaunching MetaMask. UI populates very slowly and CPU usage spikes above 100% until that window is closed. Never had this issue in previous builds.

What is MetaMask doing that it is using some many resources all of a sudden?

Steps to reproduce:
1. Go to any Dapp that uses MetaMask 
2. Unlock MetaMask
3. Interact with Dapp UI to force open MetaMask with a transaction
4. Observer CPU usage in Activity Monitor and UI "sluggishness"

**Comment by danfinlay** [comment] 2017-12-18 19:15
Could you provide your exact MetaMask version? You can find it either in the Chrome extension manager, or in MetaMask, in the Info section (top right menu).

**Comment by mhannigan** [comment] 2017-12-19 05:43
The problem is the same on Windows 10 with the current version. It happens in Chrome, but not in Firefox. In task manager, it appears to be trying to use the 3d GPU.

**Comment by bneiluj** [comment] 2018-01-03 14:23
@danfinlay That's true. I'm also investigating that matter. 
v3.13.2

**Comment by yi-ji** [comment] 2018-07-22 06:41
same problem

chrome Ver67, macOS 10.13, metamask 4.8.0

The dapp that caused this is exitscam.me ...

**Comment by bdresser** [comment] 2018-08-01 20:50
Hey all, we've had intermittent reports of this issue for several weeks now and have just posted a bug bounty on another issue that describes the same problem (https://github.com/MetaMask/metamask-extension/issues/4074)

Closing this for now and we'll track on #4074. If you're interested in helping out, feel free to pick up the bounty on Gitcoin!

**Closed by bdresser** 2018-08-01 20:51 UTC
Labels: N01-needsResearch, P2-sooner, T01-enhancement
