### ISSUE TITLE
TypeError: Cannot read property 'getHostNode' of null

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3689] opened 2018-03-22 19:22 UTC
https://sentry.io/metamask/metamask/issues/500717045/

```
TypeError: Cannot read property 'getHostNode' of null
  at Object.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1425656)
  at c.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1368557)
  at Object.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1425656)
  at Object.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1363969)
  at K._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1420560)
...
(44 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment] 2018-03-22 19:23
promise handling issue in shapeshift form?

**Comment by danjm** [comment] 2018-04-09 14:39
This is a duplicate of https://github.com/MetaMask/metamask-extension/issues/3690

The sentry logs show that that this 'getHostNode' error happens after the 'Minified react error'. 'getHostNode' errors are always a result of something not rendering due to some other error.

Fix the other error and this one will go away.

**Closed by danjm** 2018-04-09 14:39 UTC
Labels: L03.1-newUI/UAT, P2-sooner, T00-bug
