### ISSUE TITLE
After disconnect an account accountsChanged triggers with a next account despite it was not selected

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-extension#9619] opened 2020-10-16 10:13 UTC
**Describe the bug**
After disconnect account on a site accountsChanged triggers with a next account despite it was not selected

**Steps to reproduce**
1. Connect 2 MetaMask accounts to some website 
2. Disconnect the first account
3. `accountsChanged` event returns the next account, despite it is still not selected

**Expected behavior**
`accountsChanged` should return `undefined`? 

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Version 86.0.4240.80 (Official Build) (x86_64)
 - MetaMask Version: 8.0.10

**Comment by jacobcantele** [comment] 2020-11-08 00:28
Closing this issue since it appears to be a duplicate of #920

**Closed by jacobcantele** 2020-11-08 00:28 UTC

**Comment by mqklin** [comment] 2020-11-08 05:17
I think you mean #9620 :)
