### ISSUE TITLE
P0 ~ MetaMask lacks Sign Out

### ISSUE THREAD

**Issue by Loreneum** [MetaMask/metamask-extension#1887] opened 2017-08-09 21:03 UTC
P0 ~ MetaMask lacks Sign Out.

My friend **does not have a computer** and wants to open a MetaMask account. We, naturally, do not want to link accounts in any way. I discovered how to create a separate account on the same computer (create Person 2 in Chrome, add MetaMask ext in Person 2 instance, create new acct), but I didn't discover this until AFTER unwittingly linking our accounts using Civic Secure Identity. So now in MY MetaMask account, I have Account 1 linked with my personal info and Account 2 linked with his personal info, but access to BOTH ACCOUNTS only requires ONE PASSWORD or the SAME 12 WORDS <- NO BUENO! Now we need a way to PERMANENTLY separate our accounts!! MetaMask needs both a way to Sign Out AND Create Separate Logins for existing accounts!

**Comment by kumavis** [comment] 2017-08-09 21:05
Closing as duplicate of #1888

**Closed by kumavis** 2017-08-09 21:05 UTC

**Comment by Loreneum** [comment] 2017-08-09 21:07
this is not a duplicate of #1888 separate issue entirely

**Comment by Loreneum** [comment] 2017-08-09 21:31
this is still an issue. LOCK does not sign out; it only prompts user to reenter password. is a feature request for this submitted?

**Comment by flyswatter** [comment] 2017-08-09 21:33
You can use the "forgot password" feature to restore metamask to another seed phrase, but a simpler solution for your use case for now is probably to just use a second browser profile, so your friend can have their own metamask vault.

**Comment by flyswatter** [comment] 2017-08-09 21:36
Note this doesn't solve your issue of having both accounts on one seed phrase. There's no way to separate them permanently, both accounts were derived from that seed phrase, there is no un-deriving function. You probably just want to create a new user profile & vault for your friend, and set them up with a new account.

Also, if they trust you, you could just export their account's key, and they could use it however they like.

**Comment by kumavis** [comment] 2017-08-09 21:37
@Loreneum you may have intended this to be a separate issue but it contains the same description as #1888

**Comment by Loreneum** [comment] 2017-08-09 21:39
yes the description is identical because the description describes both issues, but they are still 2 separate issues

**Comment by Loreneum** [comment] 2017-08-09 23:43
description edited for clarity

**Comment by talktotrey** [comment] 2018-09-11 01:44
This is a serious issue.  Please Metamask developers, you tell us to logout but we can't.

**Comment by danfinlay** [comment] 2018-09-11 18:06
In the top right menu, the first button is "Log Out".
