### ISSUE TITLE
Incorrectly formatted error message when you reject a Ledger Nano S transaction

### ISSUE THREAD

**Issue by weijiekoh** [MetaMask/metamask-extension#5318] opened 2018-09-22 06:39 UTC
The "Failed Transaction" Chrome notification is incorrectly formatted for rejected transactions due to pressing the X button on a Ledger Nano S.

**To Reproduce**
1. Connect your Ledger to your MetaMask (v4.10.0)
2. Initiate a transaction
3. Reject the transaction by pressing the X button on your Ledger

**Expected behavior**
The error message should be more informative.

**Screenshots**
<img src="https://i.imgur.com/Z3izicv.png" />

**Browser details (please complete the following information):**
 - Kubuntu Linux
 - Chrome 65
 - MetaMask Version 4.10.0
 - New / Beta UI

**Comment by brunobar79** [comment] 2018-11-15 05:45
Duplicate of #5641

**Closed by brunobar79** 2018-11-15 05:45 UTC
