### ISSUE TITLE
Approval confirmation links to etherscan.io/token/... instead of etherscan.io/contract/...

### ISSUE THREAD

**Issue by 0xVires** [MetaMask/metamask-extension#12945] opened 2021-12-02 10:22 UTC
On the token approval confirmation, clicking the link of the to be approved contract leads to etherscan.io/token/<contractAddr> instead of etherscan.io/contract/<contractAddr>

![image](https://user-images.githubusercontent.com/25792899/144402789-6910f78a-c8c1-4438-bffb-f24123b1b062.png)

![image](https://user-images.githubusercontent.com/25792899/144403368-c0d56519-0015-4c68-b75e-95d559828f35.png)

Using Metamask v10.6.4

**Comment by bschorchit** [comment] 2022-04-18 23:31
Closing as this is the intended behavior.

**Closed by bschorchit** 2022-04-18 23:31 UTC
