### ISSUE TITLE
[Bug]: Bring popup to the foreground functionality is not working as expected.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25397] opened 2024-06-18 20:26 UTC
### Describe the bug

When a user has an unapproved transaction pending, initiating a connect request does not trigger the expected popup to appear. 
After the first request is rejected and the subsequent request can be accessed MM can break with an error.
Related issues:

https://github.com/MetaMask/metamask-extension/issues/25393

https://github.com/MetaMask/metamask-extension/issues/25361

Slack discussion links:

https://consensys.slack.com/archives/C03ETQA9EPK/p1695933147044299

https://consensys.slack.com/archives/C03ETQA9EPK/p1695932531166009

### Expected behavior

All necessary popups are displayed appropriately.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/5d73b747-0c66-4778-ac0a-0117345375c8

<img width="351" alt="Screenshot 2024-06-18 at 17 53 06" src="https://github.com/MetaMask/metamask-extension/assets/104780023/0424c866-dfe6-420f-90f5-c7a67d7ae877">

<img width="576" alt="340407819-904bd247-432b-4b71-9465-d3547e498e91" src="https://github.com/MetaMask/metamask-extension/assets/104780023/19646f09-1b86-41e7-825f-2c355e2bc40a">

### Steps to reproduce

1. Connect to test-dapp
2. Click button to start legacy send transaction; popup comes up, I see a "1" in the extension icon, I ignore the popup window
3. Open new tab, go to Uniswap
4. Click "Connect" button, click MetaMask; I see a "2" in the extension icon, no popup occurs
5. Click "Connect" button again, click MetaMask; I see a "3" in the extension icon, no popup occurs

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jiexi** [comment] 2024-06-18 20:31
To be clear here, subsequent requests in steps 4 and 5 should cause a popup that shows the pending confirmation from step 2 to show up

**Comment by hesterbruikman** [comment] 2024-06-18 20:57
@sleepytanya @jiexi To make sure I understand the issue, is this right?

GIVEN A pending transaction request
AND MetaMask is closed
AND Initiate a dapp connection
THEN Count goes up, but popup does not open automatically

It looks like the confirmation from step 2 is shown when opening MM manually, but expected is for the popup to open automatically. Is that right?

**Comment by sleepytanya** [comment] 2024-06-18 21:40
@hesterbruikman  Right!
If you open popup manually by clicking MM icon you'll see pending transaction. There is no navigation for the user to be able to see another pending request.

<img width="360" alt="Screenshot 2024-06-18 at 17 34 35" src="https://github.com/MetaMask/metamask-extension/assets/104780023/653986f4-6fb0-4824-81fc-e6e2f2a341d2">
   
You can also reject unapproved transaction from the homepage. But if you reject from there the next request will be displayed in fullscreen:

https://github.com/MetaMask/metamask-extension/assets/104780023/2b9447bc-877a-4e3d-8e10-89530298938f

**Comment by seaona** [comment] 2024-06-19 08:37
:information_source:  I've added repro steps for the `Cannot destructure property 'balance' of 'K[Z]' as it is undefined` [here](https://github.com/MetaMask/metamask-extension/issues/25406)

**Comment by sleepytanya** [comment] 2024-06-20 21:41
Latest build [https://github.com/MetaMask/metamask-extension/commit/eebc4d5b2284024eaeb190cddfa89990f593ca34]

Popup behavior didn't change:
-  only the first popup displayed
- `Cannot destructure property 'balance' of 'K[Z]' as it is undefined` is present
-  `Cannot read properties of undefined (reading 'permission')` is present


 

https://github.com/MetaMask/metamask-extension/assets/104780023/f94410ad-f8e2-48db-b5d5-a2d8b4ac5a98

**Comment by darkwing** [comment] 2024-06-21 20:32
Findings thus far:

1.  The function that ultimately shows the popup is `triggerUi` in `app/scripts/background.js`
2. `triggerUi` is called when `NOTIFICATION_MANAGER_EVENTS.POPUP_CLOSED` is signaled and when `MetamaskController`'s `showUserConfirmation` is called.
3. Clicking "Send Transaction" in test dapp on the current network brings forth the popup *every time*
4. Switch to a tab connected to a different network and triggering a transaction (ex: PancakeSwap swap) does *not* trigger `triggerUi` via `MetamaskController`'s `showUserConfirmation`
5. It's clear that `MetamaskController`'s `showUserConfirmation` only calls `triggerUi` when the confirmation is on the currently selected network
6. `showUserConfirmation` is called by `ApprovalController`'s `showApprovalRequest`

**Comment by sleepytanya** [comment] 2024-06-21 20:58
New error.

1. Start send+swap txs with low gas
2. Send another (approve) tx from a dapp
3. Confirmation is stuck on the spinner
4. Activity tan has two txs - Pending and Unapproved
5. Unapprovedtxs can't be rejected
6. If user rejects first tx MM displays an error Cannot destructure property 'balance' of 'Q[z]' as it is undefined.

<img width="751" alt="Screenshot 2024-06-21 at 16 09 26" src="https://github.com/MetaMask/metamask-extension/assets/104780023/53a4f3f7-a7f2-4602-997f-ee0667e4291d">

**Comment by darkwing** [comment] 2024-06-24 14:38
There's a separate issue for balance destructuring issues.

**Comment by jiexi** [comment] 2024-06-24 19:19
The issue is the QueuedRequestController will only allow requests to continue on to the ApprovalController if all currently unapproved transactions belong to the same networkClientId. Once a request (that requires confirmation) is received for a networkClientId that differs from the current set of unapproved transactions, that transaction and _all_ transactions afterward (including those matching the original networkClientId with unapproved transactions still visible and scrubbable by the user) are held in the request queue until the current set of unapproved transactions for the first networkClientId are approved/rejected.

This means that the notification window will not be focused starting with the first transaction that differs from the existing unapproved transactions batch. 

I believe the fix here is to expose the `showUserConfirmation`/`triggerUi` hook to either the QueuedRequestMiddleware or Controller and call that each time a request is queued.

**Comment by hesterbruikman** [comment] 2024-06-25 15:10
@jiexi is my understanding correct that your PR fixes the issue: Popup does not appear when a new confirmation request is received, for a `networkClientId` that differs from the current set of unapproved transactions?

If so it seems like we can close this issue when your PR gets merged. 

There might be residual work related to queue batches not represented clearly in the UI, but that seems like a larger project and out of scope for v12.

cc @darkwing

**Comment by jiexi** [comment] 2024-06-25 18:37
Should be fixed by https://github.com/MetaMask/metamask-extension/pull/25514

**Closed** 2024-06-26 12:19 UTC
Labels: type-bug, Sev1-high, release-blocker, team-wallet-ux, regression-RC-12.0.0

**Comment by benjisclowder** [comment] 2024-08-12 15:16
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

**1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?**
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

**Tagging eng. who added the fix**: @jiexi
