### ISSUE TITLE
MetaMask Refuses to Open on Firefox

### ISSUE THREAD

**Issue by YuhanLiin** [MetaMask/metamask-extension#5291] opened 2018-09-19 01:04 UTC
**Describe the bug**
After installing MetaMask on Firefox I see the icon appear on the top right corner of my browser. When I click the icon to open MetaMask I see an empty extension window appear on the top right for a split second before going away. Removing and re-installing MetaMask does not fix this issue, and the issue does not happen with Chrome.

**To Reproduce**
1. Install MetaMask from "https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/" on Firefox
2. Click the MetaMask icon on the top right corner.

**Expected behavior**
The MetaMask extension window opens and stays open on the top right of the screen.

**Actual behaviour**
An empty extension window appears for a split second.

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox 62.0 (64-bit)
 - MetaMask Version: 4.9.2
 - Beta UI.

**Comment by bdresser** [comment] 2018-09-19 16:51
@YuhanLiin there are a couple known issues on Firefox. Start with [this helpdesk article](https://consensys.zendesk.com/hc/en-us/articles/360007617432) for Firefox & Ubuntu. 

Otherwise sounds like a duplicate of https://github.com/MetaMask/metamask-extension/issues/3313 

In general there are intermittent blank screen issues reported on every browser (Chrome: https://github.com/MetaMask/metamask-extension/issues/4894, Brave: https://github.com/MetaMask/metamask-extension/issues/4782) with a standing bounty if you're able to debug!

**Closed by bdresser** 2018-09-19 16:51 UTC

**Comment by REVOLUTIONS001** [comment] 2019-06-22 12:58
fuck you
