### ISSUE TITLE
Metamask Crash when too many un submitted tx

### ISSUE THREAD

**Issue by lkiversonlk** [MetaMask/metamask-extension#4754] opened 2018-07-08 12:55 UTC
If we send about 10 or more transactions before we went to metamask and submit/cancel the transaction, Metamask will stuck, keep spinning and can't do anything.

some of my friends didn't back up the account, now he lost all his eth in this account.

I guess it's because metamask will retrieve some info about tx waiting to submitted and errored?

please help how to cancel the stuck?

**Comment by lkiversonlk** [comment] 2018-07-08 13:09
I've tried chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html

**Comment by bdresser** [comment] 2018-07-09 15:32
Always always back up your seed phrase. If the extension is stuck, you can try closing your browser, or un-installing and re-installing the extension. In the second case, you will need your seed phrase.

@lkiversonlk I can't reproduce this issue though - when I send 10+ transactions, they stack up in the extension and then I can go through and accept/reject them individually. What browser and MM version are you on?

**Comment by bdresser** [comment] 2018-08-03 22:19
hey @lkiversonlk - closing this issue due to inactivity. If you're still having trouble or can provide more detail, please feel free to re-open.

**Closed by bdresser** 2018-08-03 22:19 UTC
Labels: N02-needsReproduction
