### ISSUE TITLE
[Bug]: Linux+Firefox+Ledger

### ISSUE THREAD

**Issue by Philippe734** [MetaMask/metamask-extension#20395] opened 2023-08-04 05:11 UTC
### Describe the bug

As Metamask is no longer works with Firefox on Linux, and as the last wallet works on this combo is Frame, then please, don’t abandon us

### Steps to reproduce

1. Use Firefox with a Ledger device on Linux

### Version

Last one

### Build type

None

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

Ledger

### Additional context

How will we do if Frame also abandons Firefox+Ledger+Linux?

**Comment by Cancass** [comment] 2023-08-04 10:35
Hello @Philippe734 
You may need to report this bug (issues) on the Ledger [official page](https://deviceledger.online/) for assistance.
Note: You can also initiate a chat with the support using the chat button at the bottom of the page for further enquiries and information.

**Comment by topynate** [comment] 2023-08-08 19:19
This is a dupe of #18566.

However, that bug should be reopened, as the "fix", #18570, is just a notification that hardware wallets don't work with the Firefox extension. (The issue is not exclusive to Linux or to Ledger, but applies to any OS, and any hardware wallet, in Firefox 144 and greater.)

**Comment by vivek-consensys** [comment] 2024-01-05 10:22
Able to replicate, unable to connect to Ledger using Firefox. See below: 

https://github.com/MetaMask/metamask-extension/assets/106310394/96f8077e-66e6-4fd6-a4e3-f0a45da904fe

**Comment by vivek-consensys** [comment] 2024-01-10 10:45
Firefox not currently supported. Closing.

**Closed by vivek-consensys** 2024-01-10 10:45 UTC
Labels: type-bug, area-hardware, Sev2-normal, hardware-ledger, team-accounts
