### ISSUE TITLE
Is is possible to include more human readable transaction data?

### ISSUE THREAD

**Issue by stefek99** [MetaMask/metamask-extension#1925] opened 2017-08-16 07:54 UTC
Example:
![image](https://user-images.githubusercontent.com/249703/29352925-6de3c482-8260-11e7-828e-c21c94d5b4d7.png)

I'm moving ETH from EtherDelta. Would be nice to know what transaction I'm signing - is it possible to include relevant pieces of information?

**Comment by flyswatter** [comment] 2017-08-16 16:59
We definitely plan to do this, have just been busy.

Closing as duplicate of #1142 and #552.

**Closed by flyswatter** 2017-08-16 16:59 UTC

**Comment by stefek99** [comment] 2017-08-17 08:46
I think it is important.

Have you considered https://commiteth.com/ ?

It will save a lot of ETH in the long run...

Much love, you are `de facto` becoming a standard in many tutorials...

**Comment by stefek99** [comment] 2017-09-24 18:33
# It's scary

**I want to know exactly what transaction I'm signing**

At some point some serious money could be on the line and someone could make a costly mistake...

<img width="458" alt="screen shot 2017-09-24 at 19 32 26" src="https://user-images.githubusercontent.com/249703/30785482-2d8c54a8-a15f-11e7-9759-5ad33434f5f4.png">

**Comment by kumavis** [comment] 2017-09-24 18:43
Thanks for making your case, but this issue has been closed
Please add it to https://github.com/MetaMask/metamask-extension/issues/1142

in summary, we can provide some extra information sometimes, but its difficult to know how to express what might happen at a low level in a high level human understandable format
