### ISSUE TITLE
[Bug]: Can't change network

### ISSUE THREAD

**Issue by BrilliantPy** [MetaMask/metamask-extension#23537] opened 2024-03-17 07:39 UTC
### Describe the bug

After I changed the rpc of the base chain from this website. [https://chainlist.org/?search=base](https://chainlist.org/?search=base)
My metamask shows network as "?" and when I click on network to change to another network, you will see the error page as shown in the picture. Now I can't login. Because after logging in, you will see an error page and cannot do anything else. I don't want to delete and reinstall. Because there are some accounts that I imported and didn't write down the private key, how can I solve this problem? Thanks for all the advice.

![Screenshot 2024-03-16 013119](https://github.com/MetaMask/metamask-extension/assets/76525428/0c28368c-30e0-436c-bc3c-58eb3fbce8d1)

![Screenshot 2024-03-17 143213](https://github.com/MetaMask/metamask-extension/assets/76525428/24cdc750-dd6b-4c32-8303-4e031ce49701)

![Screenshot 2024-03-16 004841](https://github.com/MetaMask/metamask-extension/assets/76525428/3d9a6828-98f8-480d-a659-01179f5f5b81)

### Steps to reproduce

connect the wallet
Change new rpc for base network >> [https://chainlist.org/?search=base](https://chainlist.org/?search=base)
The extension shows a rotating icon as if it's connected. and show the error page
Then, where you want to change the network, it always shows "?" and when you press it, it will bring up an error page every time.

### Version

11.12.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by danjm** [comment] 2024-03-19 11:19
@BrilliantPy Can you toggle open "Error details" on the error screen, and take a screen shot of the error information that is shown?

**Comment by BrilliantPy** [comment] 2024-03-21 16:50
![Screenshot 2024-03-21 234922](https://github.com/MetaMask/metamask-extension/assets/76525428/14a9349b-5746-4bc8-9dca-bd0ee5893e23)
![Screenshot 2024-03-21 234858](https://github.com/MetaMask/metamask-extension/assets/76525428/cb497191-8fb5-4ae4-97a8-7cc69ee2b663)

**Comment by BrilliantPy** [comment] 2024-03-21 17:00
![Screenshot 2024-03-21 235628](https://github.com/MetaMask/metamask-extension/assets/76525428/a9a6903f-3031-4e50-aff0-a9ee90f5e2ab)
![Screenshot 2024-03-21 235949](https://github.com/MetaMask/metamask-extension/assets/76525428/584aa462-a1a6-478c-a70c-7254c63fcebd)
![Screenshot 2024-03-22 000010](https://github.com/MetaMask/metamask-extension/assets/76525428/8e7a55c3-31c3-420f-a898-046169ce5615)

**Comment by anaamolnar** [comment] 2024-03-26 22:30
Hello, @BrilliantPy. Thanks for reporting! Can you attempt to trigger a network request from chainlist.org using a different RPC URL (by pressing the arrow under Add network)? Please also make sure your Metamask is updated to the latest version. You will be able to manually update it from your browser. Go to extensions-> Metamask->Details->Enable developer mode from the top right, then there should be a button for Updating in the top left. Please let me know how it goes.

**Comment by anaamolnar** [comment] 2024-03-28 13:29
Hey @BrilliantPy, I understand, thanks for the information. Does it still behave like this if you change these settings? https://support.metamask.io/hc/en-us/articles/360038139452-MetaMask-states-Balance-may-be-outdated-displays-in-orange-or-ETH-not-added-to-balance

**Comment by gauthierpetetin** [comment] 2024-04-12 13:12
@danjm do you have any idea which of these Sentry issue(s) corresponds to this?

**Comment by Gudahtt** [comment] 2024-05-30 12:41
From looking at the stack trace, the "Cannot read properties of undefined (reading 'id')" error appears to come from this line: https://github.com/MetaMask/metamask-extension/blob/6d3dc017d272d86b5e139351d183329e3bd1d1ab/ui/components/multichain/network-list-menu/network-list-menu.js#L337

**Comment by Gudahtt** [comment] 2024-05-30 13:28
Without a reproduction, it's hard to say exactly what happened here. I can't find any similar reports in Sentry either. But it appears that this is a case of state corruption; somehow your `providerConfig` state refers to a network that doesn't exist in your `networkConfigurations` state.

@BrilliantPy sorry for the delay in replying here. Are you still stuck on this error? I might be able to suggest a hacky solution to get past this problem (delete the problematic state and restart the extension)

**Comment by Gudahtt** [comment] 2024-05-30 13:32
For now I'm going to close this, as we cannot reproduce it and have not had similar reports. But @BrilliantPy please reach out if you're still stuck, and we will help you resolve the problem and recover your accounts.

**Closed by Gudahtt** 2024-05-30 13:32 UTC
Labels: type-bug, needs-reproduction, Sev1-high, team-extension-platform, external-contributor, regression-prod-11.12.0

**Comment by Gudahtt** [comment] 2024-05-30 13:35
As far as preventing this in the future; there is a future refactor of wallet state that should prevent this (`providerConfig` is getting eliminated, so it will be impossible for it to become out-of-sync).

**Comment by benjisclowder** [comment] 2024-06-14 12:00
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

What PR fixed the issue?
Can you pinpoint the commit from which the issue originated?
Write a short explanation of the technical cause of the bug
How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

cc: @Gudahtt only if you believe this issue can be RCA'd.

**Comment by Gudahtt** [comment] 2024-07-15 19:01
This bug was not fixed, it was closed because we were unable to reproduce it.
