### ISSUE TITLE
[Bug]: Send - `TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is null.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23148] opened 2024-02-23 11:58 UTC
### Describe the bug

**Problem:** whenever I am performing a Send eth with hex data, if I add a hex data corresponding to a function signature and click Next, I stay in the same page and get the following error `TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is null.`

Note: [we had this other behaviour](https://github.com/MetaMask/metamask-extension/issues/20948) but now it has evolved to this one

### Expected behavior

We should be able to proceed to the next screen

### Screenshots/Recordings

![Screenshot from 2024-02-23 12-56-47](https://github.com/MetaMask/metamask-extension/assets/54408225/f76783dc-dc59-4179-bf16-f947d71cd4fe)

### Steps to reproduce

1. Enable hex data from advanced settings
2. Click Send ETH
3. Add any recipient
4. Add any amount
5. Add a signature on the hex data field (i.e. 0x095ea7b3)
6. Click Next -- see error and you cannot proceed to the next screen

### Version

11.10.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by HusainModiwala** [comment] 2024-02-24 13:11
I think that 'submitRequestToBackground' (line 23) function inside background-connection.ts is causing the issue

**Comment by HusainModiwala** [comment] 2024-02-24 13:25
> I think that 'submitRequestToBackground' (line 23) function inside background-connection.ts is causing the issue

Also the issue is specifically with the hex value "0x095ea7b3", because of size limit. This value exceeds the limit set. The reason I say this is because with other hex values it works fine. And with this specific value I get error

![image](https://github.com/MetaMask/metamask-extension/assets/98813758/b100ce31-db26-4d28-8c9e-0957e4a3d9aa)

**Comment by jclancy93** [comment] 2024-09-13 09:19
This is related to the old send flow, and I have not seen any incidence of this issue in Sentry for over a month, so closing this out. We can reopen if we see it happening again

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/389ec643-040f-4fbc-800e-2e30721ad05a">

**Closed by jclancy93** 2024-09-13 09:19 UTC
Labels: type-bug, Sev3-low, team-bridge, regression-prod-11.10.0
