### ISSUE TITLE
[Bug]: Send ERC20 - Unable to send any ERC20 token with 0 decimals, I always get the `Insufficient Token balance`error

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27533] opened 2024-10-01 12:08 UTC
### Describe the bug

When I am trying to send an ERC20 token with 0 decimals, I always get the error `Insufficient token balance` despite having balance.
This seems to only happen with tokens with 0 decimals

### Screenshots/Recordings

https://github.com/user-attachments/assets/32f25bdd-9122-4174-93f8-3d5fd5ba5c74

### Steps to reproduce

1. Go to the test dapp
2. Deploy an ERC20 token with 0 decimals
3. Add token to the wallet (10 tokens)
4. Try to send some amount to another address
5. See error

### Detection stage

In production (default)

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by mikesposito** [comment] 2024-12-16 10:23
Cannot reproduce on 12.9.0

The issue has been fixed by https://github.com/MetaMask/metamask-extension/pull/27074

**Closed by mikesposito** 2024-12-16 10:23 UTC
Labels: type-bug, Sev2-normal, team-assets, regression-prod-12.3.0
