### ISSUE TITLE
Set custom gas fee for cancel transaction

### ISSUE THREAD

**Issue by Soleone** [MetaMask/metamask-extension#8011] opened 2020-02-07 07:14 UTC
**What problem are you trying to solve?**

Ethereum account was stuck with multiple pending transactions using 1 gwei gas fee. The mainnet since then jumped up to 2 - 5 gas fee on average.

When I try to cancel using MetaMask it seems to set the current gas fee only a little bit higher than the original fee, not enough to cancel the original transaction quickly enough. For example it set it to around 1.1 or 1.2 gwei instead, so my cancel tx is not being processed.

I was actually completely unable to cancel my original tx even using MyEtherWallet.com or Mycrypto.com, when I chose a custom nonce there (same as original tx i want to cancel) it seemed to not respect that and MetaMask instead used a new nonce.

So either the gas fee was too low cancelling just via MetaMask, or the nonce was not correct when using external wallet user interfaces like MyEtherWallet.

A similar problem seems to be happening with the "Speed up" feature in MetaMask, I can also not choose the gas fee. What I am currently doing is speeding up the same tx like 10 times to finally get from 1 gwei original gas cost up to 3 and more gwei so that my tx actually gets processed when the network is busy.

**Describe the solution you'd like**

Simple input field to set custom gas fee instead of just "Yes" and "No". Could only show up when choosing "Advanced gas controls" in advanced settings.

**Additional context**

Need to be able to set custom (higher) gas fee here:
![image](https://user-images.githubusercontent.com/2923/74008360-a0aa1800-494e-11ea-859a-803522211a33.png)

**Comment by jennypollack** [comment] 2020-03-10 17:04
i believe this is a duplicate of #8156

**Comment by wjmelements** [comment] 2020-03-11 00:34
It seems to be a separate issue as #8156 concerns gasLimit  and not in the cancel case.

**Comment by leafcutterant** [comment] 2020-03-13 00:55
It's a separate issue and it would be very important to fix because if your transaction queue is stuck at the transaction on which you cancelled, you have to speed it up a lot of times to get it mined. Users need the ability to define the gas price themselves.

**Comment by djrosenbaum** [comment] 2021-05-06 12:27
Running into this issue as well when trying to cancel a transaction. Currently, the cancellation gas price is not adjustable. Seems like the user should be able to adjust the gas price when cancelling a transaction, but instead metamask is telling the user what the gas price will be without any option to adjust.

**Comment by djrosenbaum** [comment] 2021-05-06 12:56
In the meantime, I was able to cancel by following these steps 

1. Toggle Settings -> Advanced -> Customize transaction nonce
2. Send a transaction to yourself
3. Set the gas price
4. Manually override the Nonce to match with the transaction you are looking to cancel

**Closed** 2022-06-13 22:10 UTC
Labels: type-enhancement, area-transactions, area-settings, area-gas
