### ISSUE TITLE
[Bug]: Cannot open metamask anymore

### ISSUE THREAD

**Issue by krakovia-evm** [MetaMask/metamask-extension#22148] opened 2023-12-04 18:02 UTC
### Describe the bug

cannot open Metamask since some days, probably Firefox or Metamask update.
Same thing happening on another VM.

### Screenshots/Recordings

![immagine](https://github.com/MetaMask/metamask-extension/assets/90364822/2b8925fa-6930-4101-b129-c7196cc4afe1)

### Steps to reproduce

just click on the extension

### Error messages or log output

```shell
Uncaught (in promise) Error: An unexpected error occurred
```

### Version

11.5.1

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Severity

critical

**Comment by anaamolnar** [comment] 2023-12-05 09:29
Hello, @krakovia-evm. Thanks for reporting! Can you please update manually to the latest version and let us know if this continues to occur? Thanks!

**Comment by MetaMask-Support-io** [comment] 2023-12-05 11:03
> ### Describe the bug
> 
> cannot open Metamask since some days, probably Firefox or Metamask update.
> Same thing happening on another VM.
> 
> ### Expected behavior
> 
> _No response_
> 
> ### Screenshots/Recordings
> 
> ![immagine](https://github.com/MetaMask/metamask-extension/assets/90364822/2b8925fa-6930-4101-b129-c7196cc4afe1)
> 
> 
> ### Steps to reproduce
> 
> just click on the extension
> 
> ### Error messages or log output
> 
> ```shell
> Uncaught (in promise) Error: An unexpected error occurred
> ```
> 
> 
> ### Version
> 
> 11.5.1
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Firefox
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_
> 
> ### Severity
> 
> critical

NEED HELP??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)

**Comment by MetaMask-Support-io** [comment] 2023-12-05 11:13
> ### Describe the bug
> 
> cannot open Metamask since some days, probably Firefox or Metamask update.
> Same thing happening on another VM.
> 
> ### Expected behavior
> 
> _No response_
> 
> ### Screenshots/Recordings
> 
> ![immagine](https://github.com/MetaMask/metamask-extension/assets/90364822/2b8925fa-6930-4101-b129-c7196cc4afe1)
> 
> 
> ### Steps to reproduce
> 
> just click on the extension
> 
> ### Error messages or log output
> 
> ```shell
> Uncaught (in promise) Error: An unexpected error occurred
> ```
> 
> 
> ### Version
> 
> 11.5.1
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Firefox
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_
> 
> ### Severity
> 
> critical

NEED HELP @krakovia-evm ??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)

**Comment by xTranxen** [comment] 2023-12-06 19:46
I have the same symptom and Metamask won't with Firefox.
![Capture d'écran 2023-12-06 204514](https://github.com/MetaMask/metamask-extension/assets/142092242/cc3f541c-87b8-410a-9988-d5a74ec9c2ae)

Metamask 11.5.1
Firefox 120.0.1

**Comment by krakovia-evm** [comment] 2023-12-14 15:30
> Hello, @krakovia-evm. Thanks for reporting! Can you please update manually to the latest version and let us know if this continues to occur? Thanks!

Tested with 11.6.2, same behaviour.
Infinite loading and error in the console

**Comment by anaamolnar** [comment] 2023-12-14 23:23
@danjm Can you please take a look?

**Comment by sokiren168** [comment] 2023-12-14 23:41
> Hello, @krakovia-evm. Thanks for reporting! Can you please update manually to the latest version and let us know if this continues to occur? Thanks!

Absolutely same issue here as the guys previously mentioned. I can add this:

11.7.0 metamask doesn't solve it, I have updated manually from github. 
Also, just in case, I've updated Firefox versions to 121.0-1, 121.0b9-1, 122.0a1 and it doesn't help either.

**Comment by andylaw2022** [comment] 2023-12-17 03:10
![1](https://github.com/MetaMask/metamask-extension/assets/96398239/43443056-b3c0-48dd-b6e5-c79e198d1ad7)
save problem. always loading.
 metamask ver 11.6.2. firefox: 120.0.1 (64)
 pls fix it. I just restart my computer.

**Comment by andylaw2022** [comment] 2023-12-17 05:17
I follow this instructions  and fix it.
https://zhuanlan.zhihu.com/p/628097854?utm_id=0

**Comment by krakovia-evm** [comment] 2023-12-17 16:23
> I follow this instructions and fix it. https://zhuanlan.zhihu.com/p/628097854?utm_id=0

woah 😅 is this still a thing?
it was the "how to fix metamask" last year.

Not a solution for me this time... seems the file has the number "2" and it's indeed wrong..
![image](https://github.com/MetaMask/metamask-extension/assets/90364822/c1eb9968-2460-42b5-bd59-9b63c1c67cf8)

Also by manually opening the sqlite, seems i had a sort of bad database upgrade or something.
I can see my encrypted pkey there but there is no connection between key&file_ids.

Can i know if it's totally broken or shall i just wait for a fix?
@anaamolnar @danjm

**Comment by krakovia-evm** [comment] 2023-12-28 06:59
latest update doesn't fix the problem.
Still getting the last two errors in the first screen, while the "missing strong RNG" is gone.

**Comment by krakovia-evm** [comment] 2024-01-11 14:02
Bumping the issue as it still breaking for me and other peoples.
Is there anyhow i can help out to resolve this issue? @anaamolnar @danjm

**Comment by xTranxen** [comment] 2024-01-16 15:09
Anyone alive ? 
No workaround proposed, no answer, nothing ?

**Comment by krakovia-evm** [comment] 2024-02-20 16:39
hello, this problem still breaking today
there's anything we can do as users?
i cannot suggest Metamask to new users anymore if i cannot help resolving a breaking issue somehow or the team doesn't care to fix it.

**Comment by daxicek** [comment] 2024-02-26 12:02
Same here :/

**Comment by krakovia-evm** [comment] 2024-02-26 18:20
i mean... if it's the good "old" bug, where we need to find the exact number to assign as name to the database.. just tell us guys i'll try to make a python script.
But i don't wanna waste time doing something that worked for a 3-years old bug.
Any guidance? i'm free to do any kind of test/debug you want, but give us a direction at least!!

**Comment by gauthierpetetin** [comment] 2024-02-27 09:23
Potentially same issue as:

- https://github.com/MetaMask/metamask-extension/issues/22659
- https://github.com/MetaMask/metamask-extension/issues/22533
- https://github.com/MetaMask/metamask-extension/issues/22589

**Comment by krakovia-evm** [comment] 2024-02-27 17:12
> @krakovia-evm Would you be willing to meet on zoom with us so that we can observe the bug? We want to fix this as fast as we can, but we have not be able to reproduce it, so a screen share could be helpful

sure! we can also use telegram if you wish
you can reach me out on https://t.me/krakovia

**Comment by krakovia-evm** [comment] 2024-02-27 17:40
![image](https://github.com/MetaMask/metamask-extension/assets/90364822/759af863-ab06-4fb5-808e-5ea8f38f75aa)
just reproduced with a cloned windows10 vm (i used that vm for a small tutorial so i consider it clean)

steps
1) download metamask
2) configure a new wallet
3) open/close it various times
4) go to C:\Users\config_web3\AppData\Roaming\Mozilla\Firefox\Profiles\cdsewtpq.default-release\storage\default\moz-extension+++9f9cdbe8-e2df-4db8-9b06-41acef0f7d6e^userContextId=4294967295\idb\3647222921wleabcEoxlt-eengsairo.files (that's on the test, may be different)
5) change the number of the single file in the folder
6) restart firefox
7 bug

**Comment by krakovia-evm** [comment] 2024-03-18 00:18
hey guys any update on this?

**Comment by old-mikser** [comment] 2024-06-07 13:36
Interesting, I have three files there... I guess that's because of imported wallets...

**Comment by gauthierpetetin** [comment] 2024-06-14 14:53
Closing this issue as it is a duplicate of: https://github.com/MetaMask/metamask-extension/issues/9196

**Closed by gauthierpetetin** 2024-06-14 14:53 UTC
Labels: type-bug, needs-information, Sev1-high, team-extension-platform, ready-for-dev, external-contributor, regression-prod-11.5.1
