### ISSUE TITLE
[Bug]: all accounts on polygon network are unusable with msg: `A previous transaction is still being signed or submitted`

### ISSUE THREAD

**Issue by rouzwelt** [MetaMask/metamask-extension#23361] opened 2024-03-07 01:33 UTC
### Describe the bug

So in past 2 days or so, all my accounts in metamask chrome extension are unusable when trying to send a token with this msg appearing on the screen `A previous transaction is still being signed or submitted`.
this happens only on `Polygon` network and for all accounts, not just one.
I should mention other networks are fine and work as normal, and also on polygon network I was able to do a swap using metamask swap, but the issue still present even after that swap when trying to send a token.
I should also mention I already tried clearing data/reset nonce, but still no luck. also tried different providers urls, and still no luck.
Also another thing to mention is that I was able to perform a approval tx from quickswap website, but when it came to do the actual swap tx, still encountered the same error msg on metamask panel, but approval tx went through ok.

### Screenshots/Recordings

<img width="342" alt="Screenshot 2024-03-07 at 1 22 03 AM" src="https://github.com/MetaMask/metamask-extension/assets/98348398/d32ec142-c1ce-430a-b765-b76ccaaea38b">

### Steps to reproduce

1. Go to polygon network
2. try to send any token

### Version

11.11.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

this is critical because it has blocked me from sending any tokens on polygon network

**Comment by davigp** [comment] 2024-03-08 00:25
facing the exact same issue, it started to happen today even for new accounts.

**Comment by rouzwelt** [comment] 2024-03-08 00:49
> same issue,I'm able to transfer tokens, however when I try to interact with a contract this error happens, even for new account without any previous contract interaction.

looks like this is a known bug from past few versions, and it has been flagged as being fixed, so hopefully we get a fix soon for this

**Comment by rouzwelt** [comment] 2024-03-08 18:50
error still present in v11.11.4

**Comment by royalblayd** [comment] 2024-03-10 08:12
Have tried reaching out to the MetaMask team ?

**Comment by John2204** [comment] 2024-03-10 08:19
I can also confirm error still presents for me also after the recent update.

**Comment by bear7bull** [comment] 2024-03-10 10:57
Hi, I have the same issue but on BSC network...

**Comment by froid1911** [comment] 2024-03-11 08:10
same here with polygon

**Comment by hiteshdamke** [comment] 2024-03-11 12:19
i also face this problem

**Comment by Mcshowromzz** [comment] 2024-03-12 16:28
I have same problem , if anyone found solution

**Comment by cxheng315** [comment] 2024-03-16 03:08
"clear activity tab" , works for me
https://twitter.com/calibreftw/status/1766446629081788491

**Comment by rouzwelt** [comment] 2024-03-17 23:16
> "clear activity tab" , works for me
> https://twitter.com/calibreftw/status/1766446629081788491

yup this seemed resolve the issue for me too, the key is you need to clear data for all your accounts and not just one of them

**Comment by Corfucinas** [comment] 2024-03-20 12:16
> > "clear activity tab" , works for me
> > https://twitter.com/calibreftw/status/1766446629081788491
> 
> yup this seemed resolve the issue for me too, the catch is you need to clear data for all your accounts and not just one of them

Very bad suggestion for when you have hundreds of wallets....

**Comment by rouzwelt** [comment] 2024-03-25 09:37
> Hello @rouzwelt ,
> Unfortunately I cannot reproduce the issue on my end. I made send, swap, contract interaction on several and same accounts but no luck. 
> Could you please clarify what exactly have you done to see that error?

well I dont really know how to reproduce this, it happened to me out of nowhere, one day i opened my metamaak to send some tokens and saw that error only on polygon network, and it stayed there after few mm releases, until i saw a comment from somone on this post suggesting a possible workaround and that fixed the issue for me.

but as you can see it is not only me, others have/are experiencing the same issue.

if you ask me it looks like to be some sort of cache/storage issue, because that workaround is clearing the cache basically and it is fixing the issue, at least it did for me and a couple other guys.

**Comment by OGPoyraz** [comment] 2024-03-25 10:42
Thank you for sharing your experience and the workaround that helped resolve the issue for you @rouzwelt 

Since we don't know the steps to reproduce this issue, there is also another way that you can help us. 
You can send here the "state logs" which could be find under "Settings > Advanced > State Logs". This will help us to understand which exact transaction make it stuck. 

It's totally clear that one of the transactions that happened earlier stuck the upcoming transactions. But there are limited ways for us to understand what exactly causing the issue. 

Also, in original issue, you didn't opt in but I need to ask again to be sure, were you using hardware wallet before doing the stucked transaction?

Thank you again for your cooperation and patience.

**Comment by benjisclowder** [comment] 2024-06-14 11:16
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
 
 We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
 
1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

cc: @OGPoyraz @cryptotavares

**Comment by OGPoyraz** [comment] 2024-06-18 10:14
> **Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
> 
> We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
> 
> 1. What PR fixed the issue?
> 2. Can you pinpoint the commit from which the issue originated?
> 3. Write a short explanation of the technical cause of the bug
> 4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
>    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
>    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
>    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
> 
> Please provide your answers as a reply to this comment and tag me as well.
> 
> You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!
> 
> Tagging eng. who added the fix: @OGPoyraz cc: @cryptotavares

**What PR fixed the issue?**
- https://github.com/MetaMask/metamask-extension/pull/24027 

**Can you pinpoint the commit from which the issue originated?**
- This is not the origin of the issue but users started facing the issue with https://github.com/MetaMask/metamask-extension/pull/22676

**Write a short explanation of the technical cause of the bug**
- MM persists `TransactionController` states which hold all past transactions that user did. Some of those old transactions have status of `signed` or `approved` status which is not an issue. But after recent implementation it was a blocking the user with stating that there is actually an ongoing transaction. Because the changes assumed there could be no final `signed` or `approved` status tied to a transaction. 
We simply added a migration for the users had these type of transactions in their MM state and finalise those ones manually. 

**How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?**
- Since this is really hard to foresee such an edge case maybe more manual test with such history / background with an account would make us identify the bug. 

**4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?**
- The migration could have been pushed with the changes so users wouldn't face such issue. But as mentioned above this would definitely need to be identify upfront, otherwise it wouldn't be possible.

@benjisclowder fyi

**Comment by adapt7** [comment] 2024-08-27 13:39
Hi team. When are you going to fix the issue? It's happening to many users. Workaround to "clear activity tab data" won't work if ones have thousands of wallets. Please can you provide a fix, MetaMask is not usable with this error.

@benjisclowder @OGPoyraz

**Comment by royalblayd** [comment] 2024-08-28 08:40
Can you send me an email see if I can help you out on this. I resolved this personally but can't share the information here . Chainabuse@duck.com

**Comment by royalblayd** [comment] 2024-08-28 09:31
@adapt7 I've done you the favors. Enjoy your day.

**Comment by adapt7** [comment] 2024-08-31 08:56
Guys, is there any fix for this. It's so frustrating.

Clearing activity tab data for all wallets is not a solution when having 1k+ wallets. Please can you fix or provide any workaround?

**Closed** 2024-09-17 10:56 UTC
Labels: type-bug, Sev1-high, release-blocker, external-contributor, regression-prod-11.11.4, release-11.16.0, team-confirmations, release-12.3.0

**Comment by bfondevila** [comment] 2024-10-10 11:42
I can confirm on Version 12.2.X this was still an issue - on version 12.4.0 of the Metamask extension now, my accounts are working again as expected, without having to clear activity tab or anything similar.

**Comment by adapt7** [comment] 2024-10-10 11:49
I can also confirm, the latest version fixed the issue. Well done!
