### ISSUE TITLE
[Bug]:LavaPack is not defined   

### ISSUE THREAD

**Issue by ManeeshNadcab** [MetaMask/metamask-extension#13793] opened 2022-03-01 10:55 UTC
### Describe the bug

this error occurs on windows if you will clone it on ios or linux then metamask clone  will be  run properly. clone your metamask on Linux or Ios and follow docs of metamask

### Steps to reproduce

1.
clone code of metamask from git

install yarn if yarn not installed in your os

in terminal->

     1.yarn install
     2.yarn setup
     3.yarn start

and after that go to your chrome browser
and on developer mode and then press 'load unpacked' button 
and go to dist folder and inside dist you eill get chrome folder select that folder.
that's it.

### Version

10.10.1

### Browser

Chrome, Firefox

### Operating system

MacOS, Linux

**Comment by ManeeshNadcab** [comment] 2022-03-01 11:01
after completing above steps 

; Extra environment variables
PASSWORD=METAMASK PASSWORD
INFURA_PROJECT_ID=00000000000
SEGMENT_WRITE_KEY=
ONBOARDING_V2=
SWAPS_USE_DEV_APIS=
COLLECTIBLES_V1=
you can find this code in a file of your cloned code that file name is '.metamaskrc.dist' 
create a new file and give name '.metamaskrc' and then in above code fill your password and 
for infura id go to infura site and login and copy your id and fill .

**Comment by jesseharte** [comment] 2022-03-08 17:48
This is the problem I face when I use `yarn start`, while `yarn build` will result in the error reported in issue #10748.

**Comment by HowardBraham** [comment] 2022-11-17 04:12
Duplicate of #13318

**Closed** 2022-11-30 15:19 UTC
Labels: type-bug, area-devmode, contributor experience
