### ISSUE TITLE
Metamask recognises seed but fails to restore ETH and gives different deposit address

### ISSUE THREAD

**Issue by HussJenks** [MetaMask/metamask-extension#2864] opened 2018-01-05 02:28 UTC
I have Metamask synced on 2 PCs using Chrome web extension. After sending some Ether out using PC #1, the transaction read as failed and was unable to be viewed on Etherscan. However the Ether has still been taken from my wallet. So I uninstalled and reinstalled the extension and used my seed to restore. Now it's showing up looking like a brand new account with no history of transactions and 0 balance.  If I look at my wallet using PC #2, it shows my original balance minus the sent Ether from the failed transaction but does not show the transaction history from PC #1. 

Have I lost the Ether I sent from PC #1? Also why won't it restore my wallet and balance?

Thanks!

**Comment by Zanibas** [comment] 2018-01-09 19:24
Could you please click on the "Reveal Seed Words" button on the settings page on MetaMask PC #2 and see if those seed words are the same as the one you copied down?

**Comment by Rakeshree** [comment] 2018-01-09 19:34
hu i have the same problem i have checked and the seed are same but i cant find my balance in my account

**Comment by HussJenks** [comment] 2018-01-09 19:52
I got it fixed by setting up my account within Metamask again. Just needed
to add the account. Hope that works for u.

**Comment by Rakeshree** [comment] 2018-01-09 19:55
how can i do that will you please tell me the proccess?

**Comment by Rakeshree** [comment] 2018-01-09 19:55
and you got you balance back ?

**Comment by HussJenks** [comment] 2018-01-09 19:56
http://metamask.consensyssupport.happyfox.com/kb/article/7-importing-accounts

Followed these instructions and yes balance is back.

**Comment by Rakeshree** [comment] 2018-01-09 19:57
okay i just go to the meamask and wil try it..and get back to you..thank you

**Comment by Sharehearts** [comment] 2018-03-25 06:29
same here ,, I lost a lot . but not giving my tokens up .    please tell me how you retrieve your original account back in your metamask without using private key .  I didn't back up my private key because  those UI only told that you need to back up the12phrase and then you will be back in businesses just fine  as you loose your account.   didnt mention about private key .         I didn't expected that  this extension was that disorganised .      if someone know anything , please tell me   .

**Comment by lazaridiscom** [comment] 2018-03-25 18:36
@Sharehearts

Possibly your installation had multiple accounts?

See: https://github.com/MetaMask/metamask-extension/issues/2641#issuecomment-352545382

**Comment by lazaridiscom** [comment] 2018-03-25 20:10
@danfinlay , should be closable as duplicate of #654

**Comment by Sharehearts** [comment] 2018-03-26 07:03
@lazaridiscom ,     I got it solved right after I posted my comment.    and you are right , I had multiple account.     what a relief  .           thanks anyway.!

**Comment by danfinlay** [comment] 2018-03-26 21:38
Closing as duplicate of #654

**Closed by danfinlay** 2018-03-26 21:38 UTC
Labels: L02-keyManagement, P2-sooner, T00-bug

**Comment by achwartz** [comment] 2018-05-27 07:44
PLease hel!, i hd the same problem

**Comment by Sharehearts** [comment] 2018-05-28 15:29
ok calm down.    as I experienced same problem , I guess I can guide you through .   first, only one thing you can rely on reclaiming your coins on matamusk is seed.    no matter how much account you have created, as long as you are with all those seed you will be just fine .                asure yourself that you have the same number of accounts for  the number of seeds.     when  you open the account using the seeds phrase , if you don't see  what supposed to be there, it is simply because the seed phrase doesn't much the account you are trying to recover                             this is where I puzzled as I thought I lost all my coins .    I've forgotten that I made 4 account by mistake and at the time  I only remembered that I made 3 account .   as I kepp recovering those acount , coins never showed up.        because the very first account's seeds was missing .        when I finally found the first account's seeds I created, I could recovered the account just fine with all the coins intact.

**Comment by Sharehearts** [comment] 2018-05-28 15:34
@achwartz  .      loosing your seeds, your account would never be recovered.

**Comment by danfinlay** [comment] 2018-05-29 23:14
@achwartz Please contact MetaMask support at support@metamask.io
