### ISSUE TITLE
[Bug]: snaps private key does not export

### ISSUE THREAD

**Issue by povertyhacked** [MetaMask/metamask-extension#21060] opened 2023-09-27 11:42 UTC
### Describe the bug

i am using the starknet snap and when testing it out, i tried to export the private key. I am able to click "export" but no response after that.

### Expected behavior

private key to be shown and/or copied to clipboard

### Steps to reproduce

Go to https://snaps.consensys.io/starknet
Click 'export'

### Version

11.0.0

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by plasmacorral** [comment] 2023-09-27 15:12
Hey @povertyhacked, I'm not able to reproduce this with the Starknet v2.2.0 snap in Brave even while pop-ups are blocked in browser settings.  Are you seeing the notification prompt that requests your consent to reveal the private key in the extension?  If the extension is not opening over the snap page, does your extension icon show a blue box over the fox with a `1`?

**Comment by povertyhacked** [comment] 2023-09-27 17:02
> Hey @povertyhacked, I'm not able to reproduce this with the Starknet v2.2.0 snap in Brave even while pop-ups are blocked in browser settings. Are you seeing the notification prompt that requests your consent to reveal the private key in the extension? If the extension is not opening over the snap page, does your extension icon show a blue box over the fox with a `1`? If so, click the extension and you should have the opportunity to consent to revealing the private key, and once you approve you should see the private key on screen and have the option to copy it.

Thank you, @plasmacorral - the issue isn't occurring anymore; i just loaded the page again and it prompted a Snap update and all working now!

**Comment by povertyhacked** [comment] 2023-09-27 17:03
updated has resolved this

**Comment by plasmacorral** [comment] 2023-09-30 00:07
Closing per [comment](https://github.com/MetaMask/metamask-extension/issues/21060#issuecomment-1737775452)

**Closed by plasmacorral** 2023-09-30 00:07 UTC
Labels: type-bug, needs-information
