### ISSUE TITLE
eth_sendRawTransaction keep getting called, draining my account

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#1981] opened 2017-08-25 13:50 UTC
Hi, I am getting a very strange behaviour.

I was thinking it was on my side first but since I could not get a breakpoint to it (where it send transaction) and the sender where the metamask account I closed all tabs running dapps, actually all tabs and I could still eth_sendRawTransaction hitting my testrpc server This was happening every 20 seconds.

The transactions being sent were similar if not identical to some I send earlier by approving with the metamask ui.

It stopped after a while (or maybe after there were not enough balance)

version 3.9.11

**Comment by flyswatter** [comment] 2017-08-25 22:46
When you approve a transaction in MetaMask, it tries re-submitting that transaction on each block until mined, or until a limit is exceeded (currently 3500 blocks, about 1 day).

My guess would be if you check, these repeated sendRawTransaction calls were for identical transactions.

What doesn't make sense to me is how you'd compose an invalid transaction on TestRPC. It's not like a low gas would keep you from getting mined, and with instant-mining, it's hard to get into a bad nonce state. Curious how that happened, or what was bad about the tx that was being re-submitted, why it wasn't getting mined.

**Comment by wighawag** [comment] 2017-08-26 10:25
Actually all these transactions got mined (I had a log listener and all these transaction were sending events, (error events used for debugging purpose)), that's why it was draining the account.

Thus the hashes were different for each (nonce were incrementing else this would not mined)

By the way the testrpc server was launched with a 20s mining period (no  instant-mining)

**Comment by flyswatter** [comment] 2017-08-26 14:43
If this is a new bug, we are incredibly lucky you found it on a test server. We'll have to put some serious time to validate things that can ever create a new tx with a unique nonce.

Since we only allow signing at user approval time, what if this was a bug where the tx was being duplicated when sent to the approved state, so the old one would then also duplicate again and the new duplicate nonce would be incremented? Would that be possible?

Need to investigate more.

**Comment by wighawag** [comment] 2017-08-26 21:09
By the way the issue continued to happen even after a browser restart.
It stopped I think when there were not enough ether left in the account, but not sure about that.
Could it be specific to testrpc ?

**Comment by flyswatter** [comment] 2017-08-27 01:06
It could help for you to send us the state logs for that account:

https://support.metamask.io/kb/article/15-copying-state-logs

You might want to send them in private if you use any of the same accounts in public and don't want them known (no private keys included in logs).

**Comment by wighawag** [comment] 2017-08-27 07:53
I am not sure it contains everything, I resetted the testrpc several times but here is the one I got :

https://gist.github.com/wighawag/a50edbb84466da518a56f8f18946b3ca

**Comment by flyswatter** [comment] 2017-09-11 17:57
Moving to the backlog until we have more clues for reproducing, doing some investigation of related code didn't give me any clues how this could happen.

**Comment by flyswatter** [comment] 2017-09-20 00:32
I experienced this for a bit! It involved:
- TestRPC
- A custom token
- Myetherwallet pointed at the testrpc at the same time

Were you using myetherwallet by any chance? Checking if it could be part of the issue.

Also noting:
When we called `eth_getTransactionByHash` on the testrpc, we did not get signature parameters, so it seems that testrpc was maybe not validating or enforcing signatures, or was maybe "signing" on its end, so it's hard to validate whether these transactions were ever signed by metamask, or if it is just some error, for example where myetherwallet sends `sendTransaction` calls to the testrpc open port.

**Comment by flyswatter** [comment] 2017-09-20 00:38
Using the ethjs example [block explorer](http://ethjs-examples.surge.sh/blockchain-explorer.html) we were able to inspect some of the transactions & blocks. Fun trivia: The blocks did not include those transactions! This is looking like a testrpc bug, or some combination of bugs. Worth sharing with @tcoulter

**Comment by wighawag** [comment] 2017-09-20 05:58
Interesting, I thought about the possibility of it being testrpc but because it was affecting the metamask account I discarded it. 

I was not using myetherwallet but I was sending potentially multiple sendRawTransaction from the dapp page with a javascript generated private key (not a metamask account)

My smart contract did not involved tokens

**Comment by danfinlay** [comment] 2018-05-10 19:02
I believe this problem no longer exists, and I am closing it. Please comment if you experience it again.

**Closed by danfinlay** 2018-05-10 19:02 UTC
Labels: L04-backend, N02-needsReproduction, P3-soon, S02-testRPC/ganache, T00-bug, T10-spooky
