### ISSUE TITLE
Custom Nonce setting not passed to ConfirmTransactionBase from ConfirmApprove component (approve spend limit dialog)

### ISSUE THREAD

**Issue by shhac** [MetaMask/metamask-extension#10129] opened 2020-12-31 17:10 UTC
**Describe the bug**

Transaction flows using `ConfirmApprove` component is not resulting in settings-configured values being passed into `ConfirmTransactionBase` for `useNonceField`, `customNonceValue` or `updateCustomeNonce`

**Steps to reproduce (REQUIRED)**

1. Check custom nonce is enabled in Settings > Advanced > Customise Transaction Nonce
2. Initialise any ERC20 spend limit approval transaction, e.g. from uniswap, etc
3. Custom nonce section of `ConfirmTransactionBase` **is not** displayed in the dialog

**Expected behavior**

Custom nonce section of `ConfirmTransactionBase` **is** displayed in the dialog

**Screenshots**

https://github.com/MetaMask/metamask-extension/blob/869124c4c92c093194cca3e59e0ff8eca7f5375a/ui/app/pages/confirm-approve/confirm-approve.js#L91-L96

https://github.com/MetaMask/metamask-extension/blob/869124c4c92c093194cca3e59e0ff8eca7f5375a/ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js#L49-L51

**Browser details (please complete the following information):**

 - OS: any
 - Hardware Wallet: n/a
 - Browser: any
 - MetaMask Version: 8.1.9

**Additional context (Error Messages, etc.)**

Looks like it was missed when custom nonce feature was added due to split flows?

**Comment by shhac** [comment] 2020-12-31 17:23
A little more investigating I saw there is a container which is supplying these via `mapStateToProps`

https://github.com/MetaMask/metamask-extension/blob/869124c4c92c093194cca3e59e0ff8eca7f5375a/ui/app/pages/confirm-transaction-base/confirm-transaction-base.container.js#L182-L183

https://github.com/MetaMask/metamask-https://github.com/MetaMask/metamask-extension/blob/869124c4c92c093194cca3e59e0ff8eca7f5375a/ui/app/selectors/selectors.js#L301-L307

however, that it is not working suggests `state.metamask` is not populated by the extension settings correctly for this flow

**Comment by Gudahtt** [comment] 2021-01-04 17:34
This looks like it could be a dupe of #9989

**Comment by shhac** [comment] 2021-01-04 23:06
@Gudahtt I don't consider this a duplicate as in this issue there is no UI shown to enter a nonce or see a warning about a nonce, whereas the other issue shows UI about a nonce, so I believe they must be different transaction types.

This issue is specifically on the approve spend limit transaction dialog

**Comment by Gudahtt** [comment] 2021-01-04 23:12
Good point! I think you're right.

**Comment by AJolly** [comment] 2021-01-08 05:45
Thanks! Just came here to submit this bug.  It applies even if you call the approve function directly in etherscan.

**Comment by Ankarrr** [comment] 2021-02-08 06:20
What's the progess?

**Comment by bmino** [comment] 2021-03-03 04:10
I can confirm I'm also experiencing this issue.

Attempted to perform an `approve` on yearn, aave, and uniswap
![image](https://user-images.githubusercontent.com/10902767/109751440-79069d00-7bac-11eb-897f-4643b4e82e50.png)

**Comment by sebastiantf** [comment] 2021-03-29 13:47
This is highly required feature!

**Closed** 2021-04-16 22:00 UTC
Labels: Sev2-normal, needs-designs, type-bug, ux-enhancement

**Comment by intpg** [comment] 2021-04-29 21:36
I fully support it, not sure why it's not a thing yet.
