### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'text_signature')

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16949] opened 2022-12-14 11:11 UTC
### Describe the bug

**Problem**: with a verified Contract, when I try to call one of its functions, I get the UI console error `TypeError: Cannot read properties of undefined (reading 'text_signature')`.

https://user-images.githubusercontent.com/54408225/207579605-bed243c6-e964-447a-a361-118e3e5d17a9.mp4

### Steps to reproduce

1. Set Goerli network
2. Go to the contract https://goerli.etherscan.io/address/0x0E58766584C320B41CD1dCF9364acc612E1999F7#writeContract
3. Click on Write Contract
4. Click Connect for connecting MM
5. Click `lotsOfParams`function
6. Fill the values
7. Click Write
8. Right click MM popup to inspect the console -- see error

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by EresDev** [comment] 2022-12-15 12:30
This is what I was able to find. 

Metamask fetches contract's method **text_signature** from https://www.4byte.directory/ by sending it **hex_signature** of the method.

When 4byte.directory does not have mapping from method's hex to text, it sends back an empty results response, which creates this error. Metamask is always trying to read the **text_signature** even when there is none.

I am not sure if etherscan automatically adds these hex to text mapping of verified contracts to 4byte database. At least it doesn't look like the case for goerli testnet.

One way is to add the hex to text mapping (or submit ABI) on the https://www.4byte.directory/. But not everyone will do so. In this case, Metamask should ignore the response from 4byte.directory to prevent the error in question. I think I will be submitting a fix using this approach. 

Please note that the "Steps to reproduce" above will not work with the given contract now because I ended up adding a hex to text mapping. However, you can use the following contract if you want to reproduce the error: https://goerli.etherscan.io/address/0x0ef46122991b9c36f53ad08c162d1cbb9240dbfb#writeContract

**Comment by bschorchit** [comment] 2023-07-20 22:11
ˆ keeping this one open

**Comment by seaona** [comment] 2024-09-13 07:32
This is still present in 12.3.0

![Screenshot from 2024-09-13 09-32-15](https://github.com/user-attachments/assets/09cf7dcf-971b-4013-88d2-798c9fdc3fe4)

**Comment by bschorchit** [comment] 2024-10-15 14:32
Closing in favor of: https://github.com/MetaMask/metamask-extension/issues/27527

**Closed by bschorchit** 2024-10-15 14:32 UTC
Labels: type-bug, Sev3-low, team-confirmations
