### ISSUE TITLE
Can I Sign Data Without Popup

### ISSUE THREAD

**Issue by mudgen** [MetaMask/metamask-extension#3809] opened 2018-03-30 23:32 UTC
I am implementing a dapp and users will use metamask with it.

Is it possible for me to sign some data using metamask without a popup being shown to the user?

The reason I want to do this is that I want to authenticate the user's account address on the server side by signing a message in the client and sending it and the users address to the server. But I don't want to show a popup to the user to sign the message. Or is there a better way to automatically authenticate a user on the server using MetaMask?

**Comment by A1kartikey** [comment] 2018-04-01 19:41
I m also facing the similar issue. how should the D'app look for users? Do the user need to submit the gas every time. Can v make that internally?

**Comment by mudgen** [comment] 2018-04-09 17:40
@ripern I didn't realize there was a transaction cost to sign some data.

**Comment by danfinlay** [comment] 2018-04-17 21:03
We do not allow dapps to get signatures without user confirmation. Signatures are similar enough to transactions, we make sure they represent user intention.

If you need to do something that requires cryptographic signatures, I recommend you ask the user to sign a local key that can then be used by the app to sign freely, with cryptographic proof of user intent.

Closing because this is a question, not a bug or feature.

**Closed by danfinlay** 2018-04-17 21:03 UTC

**Comment by zenshubham** [comment] 2019-02-20 08:24
@danfinlay  Is there a way i can sign multiple documents with a single confirmation.

**Comment by Linch1** [comment] 2022-06-04 15:13
> d to do something that requires cryptographic signatures, I recommend you ask the user to sign a local key that can then be used by the app to sign freely, with cryptographic pr

Can you link some resource about how to let the user sign a 'local key' ?
I cannot really find something about it
