### ISSUE TITLE
Unable to download state logs on Chrome

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/metamask-extension#3791] opened 2018-03-29 17:16 UTC
When I click "download state logs" nothing happens in both old and new UI. 

Version 65.0.3325.181 (Official Build) (64-bit) Chrome

MetaMask v 4.3.0

No console log errors I can see.

**Comment by tmashuang** [comment] 2018-03-29 17:38
Also, unable to download private keys as a file. Seems there is an issue with `ui/app/util.js exportAsFile`

**Comment by danfinlay** [comment] 2018-03-29 18:31
I've been unable to reproduce this, but since it blocks support, I've moved it to the current sprint and bumped some lower urgency issues. May be fixed in `4.4.0`.

**Comment by jrmoreau** [comment] 2018-04-03 20:15
I am on v 4.5.0 and I still cannot download state logs. I have users who are also unable to do so. Please let me know how to best reproduce this @danfinlay

**Comment by danfinlay** [comment] 2018-04-03 21:14
If you open the logs and try again, do you see errors in any console, @jrmoreau?

I'm on a `master` build and am not getting this problem.

**Comment by alacrity26** [comment] 2018-04-04 09:44
I am on v4.5.1 and found this error: 
"ui.js:6149 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.", alongside 2 other warnings. 
Does it correspond to the issue?

**Closed** 2018-04-05 07:51 UTC
Labels: N02-needsReproduction, P1-asap, T00-bug, in progress
