### ISSUE TITLE
Beta UI request: .eth name resolving

### ISSUE THREAD

**Issue by adamyala** [MetaMask/metamask-extension#3408] opened 2018-03-02 22:53 UTC
In the old UI entering a .eth name resolved it to the appropriate address. In the new UI it's considered an invalid address.

<img width="337" alt="screen shot 2018-03-02 at 2 50 27 pm" src="https://user-images.githubusercontent.com/3434677/36925797-77076644-1e29-11e8-91ee-9593e7d24622.png">
<img width="340" alt="screen shot 2018-03-02 at 2 50 49 pm" src="https://user-images.githubusercontent.com/3434677/36925798-7720a0dc-1e29-11e8-8559-a145c67aac30.png">

Could this feature get carried over to the new UI?

**Comment by danjm** [comment] 2018-03-03 01:03
@adamyala Good suggestion. In fact, the work for this is planned. This feature should be added by end of next week.

**Comment by askucher** [comment] 2018-03-04 12:34
So, are you going to add @names?

**Comment by danfinlay** [comment] 2018-03-12 18:15
Closing as duplicate of #2528

**Closed by danfinlay** 2018-03-12 18:15 UTC
Labels: NewUI/UAT, P2-sooner, T1-enhancement
