### ISSUE TITLE
Scroll Bar Galore in Approve Screen

### ISSUE THREAD

**Issue by lucasvo** [MetaMask/metamask-extension#8517] opened 2020-05-05 17:30 UTC
![image](https://user-images.githubusercontent.com/31727/81096496-bf488c80-8f06-11ea-8ffb-2686152bdab7.png)

**Comment by brad-decker** [comment] 2020-05-05 17:33
Hey @lucasvo can you provide some details on which version of Metamask you're currently running, and in which browser? Thanks for the report!

**Comment by Gudahtt** [comment] 2021-01-11 22:47
I wasn't able to reproduce this with v8.1.11 of the extension using either Chrome or Firefox. I'll close this for now, since we don't have enough information to investigate further. Please let us know if you can still repro this though!

**Closed by Gudahtt** 2021-01-11 22:47 UTC
Labels: L03-UI, N02-needsReproduction, S2-normal, T00-bug
