### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jiaozishen** [MetaMask/metamask-extension#13850] opened 2022-03-06 20:10 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/101066444/156940226-8bdb5632-94dc-4130-a14f-a8c332b14e0d.png)
![image](https://user-images.githubusercontent.com/101066444/156940325-85591034-5f8b-46bd-bfc4-28606645786c.png)
I can't open my wallet, there are many accounts in it, and I don't have backup private keys for many accounts, there are also many assets in it, please help me!!

### Steps to reproduce

1.

### Error messages or log output

```shell
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:1000
Removing intrinsics.Object.hasOwn sentry-install.js:1:102726
missing dep: bn.js requested buffer 2 sentry-install.js:1:102726
LavaMoat: ignoring write attempt to read-access global "XMLHttpRequest" sentry-install.js:1:102726
missing dep: bn.js requested buffer 5 sentry-install.js:1:102726
Error: An unexpected error occurred
sentry-install.js:1:102726

​
```

### Version

10.10.2

### Browser

Firefox

### Operating system

Windows

**Comment by danjm** [comment] 2022-03-07 10:46
You said you don't have backup for many private keys. But do you have your seed phrase / secret recovery phrase? If you do, you don't need the private keys for individual accounts (unless those accounts were important from a wallet with a different seed phrase / secret recovery phrase).

**Comment by Jiaozishen** [comment] 2022-03-07 10:56
I have created many accounts without backing up their mnemonics and private keys, I need a way to find my data in Firefox and put it into the MetaMask Vault Decryptor so I can recover my account.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dan J ***@***.***&gt;; 
发送时间: 2022年3月7日(星期一) 晚上6:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MetaMask/metamask-extension] [Bug]:  (Issue #13850)






你说你没有备份很多私钥。但是你有你的种子短语/秘密恢复短语吗？如果需要，则不需要个人帐户的私钥（除非这些帐户在具有不同种子短语/秘密恢复短语的钱包中非常重要）。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by Jiaozishen** [comment] 2022-03-07 10:57
I have created many accounts without backing up their mnemonics and private keys, I need a way to find my data in Firefox and put it into the MetaMask Vault Decryptor so I can recover my account.

**Comment by danjm** [comment] 2022-03-07 10:57
Do you have the "Secret Recovery Phrase" or "Seed Phrase"?

**Comment by Jiaozishen** [comment] 2022-03-07 10:59
> Do you have the "Secret Recovery Phrase" or "Seed Phrase"?

I didn't backup the first account, and I did have private keys for some of the later accounts, but it didn't work, and I couldn't find many accounts

**Comment by danjm** [comment] 2022-03-07 11:02
Okay, but just to be clear, the "Secret Recovery Phrase" is different from a "private key". You would have been shown this when first installing MetaMask.

It is 12 random word (example: "promote fortune female explain until tiger matter entry enrich color pretty bracket"). This backs up ALL of your accounts. This is different from a "private key" (example: "0x5b8b4a55983b811ad04e84bfe7497be7f4b28cbe40c9b69588491d1a7d82a864") which only backs up a single account.

Do you ever remember saving the random 12 word phrase that is shown to you when first installing MetaMask?

**Comment by Jiaozishen** [comment] 2022-03-07 11:05
> Okay, but just to be clear, the "Secret Recovery Phrase" is different from a "private key". You would have been shown this when first installing MetaMask.
> 
> It is 12 random word (example: "promote fortune female explain until tiger matter entry enrich color pretty bracket"). This backs up ALL of your accounts. This is different from a "private key" (example: "0x5b8b4a55983b811ad04e84bfe7497be7f4b28cbe40c9b69588491d1a7d82a864") which only backs up a single account.
> 
> Do you ever remember saving the random 12 word phrase that is shown to you when first installing MetaMask?

I can't remember whether I used the import wallet or created it directly. Do you have a way to find local seed files? I want to use this function, because the wallet is still in my local file, https://github.com/MetaMask/vault-decryptor

**Comment by danjm** [comment] 2022-03-07 11:10
Thanks for clarifying. The vault is likely recoverable, but there is another bug you are experiencing that we will have to resolve.

Please follow the steps here https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1034044323 and then we will try to help further.

**Comment by danjm** [comment] 2022-03-07 11:11
Duplicate of #9196

**Closed by danjm** 2022-03-07 11:11 UTC

**Comment by wcr1pt0** [comment] 2022-03-12 06:29
Hello,

I'm having the same problem... tried restoring metamask in Brave using the 12 words but it only recovers the 1st wallet, right?

Firefox 98 on macOS (Mojave) - Metamask 10.10.2

<img width="1435" alt="Screen Shot 2022-03-12 at 03 28 04" src="https://user-images.githubusercontent.com/78519867/158006831-4152a4af-6338-467c-b3b4-491d6c1c0fce.png">

I need help to recover all accounts.

Thanks in advance
