### ISSUE TITLE
EIP 67 or 681 support for payments through uri

### ISSUE THREAD

**Issue by pr0toshi** [MetaMask/metamask-extension#8500] opened 2020-05-03 10:31 UTC
**What problem are you trying to solve?**
A short description of what you're trying to do.
MM mobile supports this but not the chrome app. Would be amazing for linking and payments as well as being able to remove putting in addresses from the payment process

**Describe the solution you'd like**
67 for basic support or 681 for full support

**Additional context**
Will pay in cookies

**Comment by whymarrh** [comment] 2020-05-03 15:59
Duplicate of #5125

**Closed by whymarrh** 2020-05-03 15:59 UTC

**Comment by pr0toshi** [comment] 2023-01-19 20:02
@whymarrh Definately not the same

also
Team didnt implement EIP 67 / 681 right for the mobile wallet

Sample
https://addrs.to/pr0/USDC?amount=20

the URI
ethereum:0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/transfer?address=0x9d31e30003f253563ff108bc60b16fdf2c93abb5&uint256=20000000

app shows
20000000 USDC
as the amount, the standard makes it so that the uint should be raw, not with dec
