### ISSUE TITLE
Primary currency radio buttons not working

### ISSUE THREAD

**Issue by helderjnpinto** [MetaMask/metamask-extension#8189] opened 2020-03-13 11:28 UTC
**Describe the bug**
Radio buttons of Primary Currency not working

**To Reproduce (REQUIRED)**
General -> Primary currency setting

**Expected behavior**
Expected change the radio button and save the settings as ETH and not convert the value of balance

**Screenshots**
![image](https://user-images.githubusercontent.com/12281088/76616829-cf527a00-651c-11ea-826f-1815ecc665fe.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Browser [Chrome version 80.0.3987.87 (Official Build) (64-bit)]
 - MetaMask Version [e.g. 7.7.7]

**Comment by Gudahtt** [comment] 2020-03-13 15:55
That setting allows you to switch between the native currency of the current network and your configured fiat currency. If you're seeing `USD` as the left option, it means you've set USD as the native currency of your current network. All of the default networks have that set to `ETH`.

**Comment by helderjnpinto** [comment] 2020-03-20 11:30
yes, i understand that, but radio button can't be switched, this option not working.

**Comment by Gudahtt** [comment] 2020-03-20 14:33
I am unable to reproduce this behaviour; the radio button seems to be working fine for me, on both Chrome and Firefox. Could you help with finding a reproduction?

**Comment by helderjnpinto** [comment] 2020-06-17 10:27
@Gudahtt here is the video latest metamask and chrome for ubuntu 18, [](https://streamable.com/1y9zwu )

**Comment by Gudahtt** [comment] 2021-01-11 18:17
Thanks for the video @helderjnpinto! It looks like it's gone now, but I recall I did see it when you first posted it, and it did demonstrate the problem as you described.

I was unable to reproduce this behaviour, but there was a similar problem fixed in v8.1.10 - there were various problems that resulted in frozen UI, which matches your problem here. When you get the chance, could you try to reproduce this on the latest version of MetaMask?

If you're still seeing this, and if you're willing to provide additional assistance in debugging this problem, I'd recommend contacting support so they can walk you through how to provide state logs, console logs, and network logs to help us debug the issue.

**Comment by helderjnpinto** [comment] 2021-01-12 11:45
Hi @Gudahtt, now i can switch the button only works for Ethereum mainnet, i got some frozen UI when the first time that i switched it's needed do a refresh (tested with "expanded view").

OS: Ubuntu 20 LTS
Browser [Version 87.0.4280.141 (Official Build) (64-bit) ]
MetaMask Version [8.1.11]

Good work, thanks!

**Comment by Gudahtt** [comment] 2021-01-19 02:54
Thanks for the update! I'm glad that the situation has at least improved.

I didn't _quite_ understand part of what you just said - did you mean that the button still can't be switched when on a testnet or custom network?

Let me know if you continue to have trouble with this, or if you still see a "frozen UI" type behaviour in some circumstances.

**Comment by helderjnpinto** [comment] 2021-01-27 15:59
@Gudahtt  It's just a problem when switch from networks this is a problem of refresh state i think, i will close this issue thanks, here is the demo that i made just for reference - https://streamable.com/m5m2oh

**Comment by Gudahtt** [comment] 2021-01-27 16:07
Oh wow, great find! I really appreciate that video, it very clearly demonstrated the problem. I was easily able to reproduce this myself as well.

I'm going to re-open this bug to address the remaining issue you just found. I'll advise support of this problem as well, in case anyone else runs into it. Now that it's so easy to reproduce, I suspect this will be easy to fix completely.

**Comment by mcmire** [comment] 2021-09-13 20:42
I played around with the settings screen for a bit and am not seeing any weird behavior. Both of the videos posted here are gone, do we remember what the original issue was?

**Comment by Gudahtt** [comment] 2021-09-13 21:00
I don't remember the exact reproduction steps, but it was something like:

* Navigate to the settings screen
* Switch to a different network
* Try switching the primary currency

I can't reproduce it anymore either, so I think we can close this for now and hope that it's fixed. We can re-open it if anyone manages to reproduce it again.

**Closed by Gudahtt** 2021-09-13 21:00 UTC
Labels: type-bug, area-settings, Sev2-normal
