### ISSUE TITLE
[Bug]: Lavapack is not defined

### ISSUE THREAD

**Issue by Arslan-95** [MetaMask/metamask-extension#15237] opened 2022-07-14 15:07 UTC
### Describe the bug

.metamaskrc:
; Extra environment variables
PASSWORD=Develop
INFURA_PROJECT_ID=*************************** // Not 'awefoij'. Is awefoij.
SEGMENT_HOST='http://localhost:9090'
SEGMENT_WRITE_KEY='FAKE'
ONBOARDING_V2=
SWAPS_USE_DEV_APIS=
COLLECTIBLES_V1=
TOKEN_DETECTION_V2=
ADD_POPULAR_NETWORKS=

; Set this to test changes to the phishing warning page.
PHISHING_WARNING_PAGE_URL=
-----------------------------
After yarn install > yarn setup > create .metamaskrc file > yarn start > Just pause at wallet-extension\dist\brave\ui-2.js reloaded. If i load this to Chrome, i have Error Lavapack is not defined.

### Steps to reproduce

1.

### Version

10.17.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

### Additional context

![Скриншот 14-07-2022 170203](https://user-images.githubusercontent.com/66091159/179015014-7e3e075f-b786-499e-9789-5797ab2bdd52.jpg)
![Скриншот 14-07-2022 170152](https://user-images.githubusercontent.com/66091159/179015019-c17ddec1-78a4-4255-bcb6-8036653ea983.jpg)

**Comment by dfibuch** [comment] 2022-08-11 11:11
This isn't exactly a fix but there is a workaround that I found. I'm running WSL with Ubuntu 18.04 and I cloned the repo there, followed the setup steps again and that problem is no longer there, it all works.

**Comment by HowardBraham** [comment] 2022-11-17 04:13
Duplicate of https://github.com/MetaMask/metamask-extension/issues/13318

**Closed** 2022-11-30 15:19 UTC
Labels: type-bug, needs-triage, dx

**Comment by yazeed** [comment] 2024-01-18 23:49
What if I'm getting this on production version of metamask?
