### ISSUE TITLE
[Bug]: extension showing incorrect price in usd for pandoproject

### ISSUE THREAD

**Issue by vishalpando** [MetaMask/metamask-extension#17037] opened 2022-12-22 06:24 UTC
### Describe the bug

we are writing from pandoprojects , we have our ptx coin registered on metamask whose price in usd is being displayed incorrectly  on researching we found metmask is taking prices prom coingecko and further we contacted coingecko and they told that they are using api named pando-token and to check on the metamask side if the same api is being used 

### Steps to reproduce

1.check the api if its same as pando-token or not 
2.if not please let us know what to change 

### Version

10.23.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Helpcenter101** [comment] 2022-12-31 04:59
> ### Describe the bug
> 
> we are writing from pandoprojects , we have our ptx coin registered on metamask whose price in usd is being displayed incorrectly  on researching we found metmask is taking prices prom coingecko and further we contacted coingecko and they told that they are using api named pando-token and to check on the metamask side if the same api is being used 
> 
> ### Steps to reproduce
> 
> 1.check the api if its same as pando-token or not 
> 2.if not please let us know what to change 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.23.1
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by brad-decker** [comment] 2023-01-02 18:52
Duplicate of #17071

**Closed by brad-decker** 2023-01-02 18:52 UTC
Labels: type-bug

**Comment by vishalpando** [comment] 2023-01-03 04:13
Heyy Brad!!
we are developers team at pando , we just want to know what api (name) is
being called from the metamask side to coingecko by which the price is
being taken and also there are a number of PTX symbolled token so is it a
possibility that the price is being taken from there.
