### ISSUE TITLE
Metamask Chrome all settings acounts gone

### ISSUE THREAD

**Issue by MichaelRazum** [MetaMask/metamask-extension#3467] opened 2018-03-07 15:33 UTC
Hello,
I'm using the newest Chrome Version, Windows 10 and MetaMask installed.

Without any warning or even restart of the browser. After clicking on MetaMask all the data seems to be gone. I had to accept the terms of agreement and so on. Is this bug known? 

Also is there a way to restore the "old" data MetaMask was using without the secret phase. Since I would be very surprised if that data is just wiped out from the PC. 

Thanks a lot!

**Comment by lazaridiscom** [comment] 2018-03-07 15:57
@MichaelRazum , really sorry for your problems. I suggest you don't touch your MetaMask installation for now, until someone of the team responds.

There was a similar report here #3191. You can try account restoration on a 2nd pc (or at least on a 2nd browser, e.g. use Firefox to reinstall MetaMask and try out your seeds). 

> Also is there a way to restore the "old" data MetaMask was using without the secret phase.

As to my knowledge, no.

**Comment by MichaelRazum** [comment] 2018-03-07 16:15
@lazaridiscom Thanks a lot for your response. Maybe chrome wiped out the memory somehow. Actually I don't have the seed. It's not that bad since I have saved most of my private passwords. But unfortunately not for all of the accounts. So was hopping that there is a way to restore. Will wait for a response or a resolution of this bug.

**Comment by danfinlay** [comment] 2018-03-07 22:35
Sorry this hit you @MichaelRazum, we actually are aware of this, it turns out browsers will sometimes wipe local storage, and we need to use a new storage strategy. We have a fix that we're finishing up today:
https://github.com/MetaMask/metamask-extension/pull/3083

Closing as a duplicate of #3076.

**Closed by danfinlay** 2018-03-07 22:35 UTC
