### ISSUE TITLE
Show wrong amount of currencies after switching network

### ISSUE THREAD

**Issue by tmnhutdev** [MetaMask/metamask-extension#12495] opened 2021-10-27 14:21 UTC
**Describe the bug**
I have some MATIC on Polygon chain and I try to switch to other network (like Etherum, Binance Smart Chain,...) but the amount was not updated or changed. It shows amount the same of MATIC, and I cannot do any transaction on Etherum, Binance Smart Chain with this amount.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Metamask wallet
2. Check amout of Matic on Polygon
![image](https://user-images.githubusercontent.com/29451168/139083459-40712a94-a287-476e-abdb-fa32fa0318a4.png)
3. Click on Network and change to Etherum Mainnet
4. Check amount of ETH on Etherum Mainnet
5. Expected amount is 0, but it shown same amount of Matic
![image](https://user-images.githubusercontent.com/29451168/139084035-72c5e115-2d2b-4c33-86f9-68fc66022a42.png)

**Expected showing amount**
Amount is shown correctly in corresponding network

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser:  Chrome Version 95.0.4638.54 (Official Build) (64-bit)
 - MetaMask Version: 10.3.0

**Comment by EroticKlaxon** [comment] 2021-10-31 14:15
I see this pretty frequently. It's like seeing a car accident when you wonder where your ETH went for that first couple seconds.

**Comment by danjm** [comment] 2022-03-18 11:56
While fixing this bug, we can leave the balance empty while it is loading or unknown.

But we should also make the improvement tracked here: https://github.com/MetaMask/metamask-extension/issues/14040

**Comment by EHaracic** [comment] 2022-03-21 09:39
Tasks

- Reproduce, try using the network tools in the background console to fail requests from the different networks.
- While fixing this bug, we can leave the balance empty while it is loading or unknown.

**Comment by seaona** [comment] 2022-05-27 10:24
@danjm @VSaric I've seen this exact behaviour happening on a friend wallet a couple of months ago. Relevant things to consider:
- The exact amount of MATIC is displayed on Ethereum Mainnet as ETH
-  Everytime he sends MATIC, and the balance of MATIC updates, when he changes back to Mainnet, he also sees the ETH balance updated to the last MATIC value
- He is seeing the ETH wrong balance since then. (A couple of months ago)
- **Wrong ETH balance is always visible**, no matter if Metamask is locked and then unlocked again. No matter which day he checks it
- No ETH transaction has ever happened to that Account/Wallet.

Actions that I remember we performed: Opened a new Wallet (he has no ETH), I sent him MATIC, he changed back to Mainnet, wrong ETH amount was there, and it's there since then. Maybe I'm missing something in between, as I couldn't repro it following this steps yet.

I think we cannot close this issue by [this fix](https://github.com/MetaMask/metamask-extension/pull/14354), as it's not a matter of "slow" loading/fetching network data, neither a punctual network issue, but a permanent miss-match with Polygon network, leaving the wallet un-usable for other networks, aside from Polygon.

I can try to reach him and investigate this using his address/wallet.

@tmnhutdev could you confirm you are still seeing the wrong balance?

**Comment by VSaric** [comment] 2022-05-27 13:57
> @danjm @VSaric I've seen this exact behaviour happening on a friend wallet a couple of months ago. Relevant things to consider:
> 
> * The exact amount of MATIC is displayed on Ethereum Mainnet as ETH
> * Everytime he sends MATIC, and the balance of MATIC updates, when he changes back to Mainnet, he also sees the ETH balance updated to the last MATIC value
> * He is seeing the ETH wrong balance since then. (A couple of months ago)
> * **Wrong ETH balance is always visible**, no matter if Metamask is locked and then unlocked again. No matter which day he checks it
> * No ETH transaction has ever happened to that Account/Wallet.
> 
> Actions that I remember we performed: Opened a new Wallet (he has no ETH), I sent him MATIC, he changed back to Mainnet, wrong ETH amount was there, and it's there since then. Maybe I'm missing something in between, as I couldn't repro it following this steps yet.
> 
> I think we cannot close this issue by [this fix](https://github.com/MetaMask/metamask-extension/pull/14354), as it's not a matter of "slow" loading/fetching network data, neither a punctual network issue, but a permanent miss-match with Polygon network, leaving the wallet un-usable for other networks, aside from Polygon.
> 
> I can try to reach him and investigate this using his address/wallet.
> 
> @tmnhutdev could you confirm you are still seeing the wrong balance?

What do you think @danjm about this? 
It will be great if @seaona can reach @tmnhutdev and investigate this using his address/wallet. We can wait @tmnhutdev to confirm if he still see the wrong balance.

**Closed** 2022-06-13 19:39 UTC
Labels: type-bug, needs-reproduction, area-customNetworks, Sev2-normal, PS-team
