### ISSUE TITLE
MetaMask wallet extension  not open in chorme 

### ISSUE THREAD

**Issue by RansaPalana** [MetaMask/metamask-extension#9245] opened 2020-08-17 05:30 UTC
I have tried to issue certificate using  "https://admin.opencerts.io/" this site but my metamask wallet extension is not working or not opening.

**Comment by RansaPalana** [comment] 2020-08-17 08:20
console shows Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': Symbol(Symbol.toPrimitive) could not be cloned. error

**Comment by Gudahtt** [comment] 2020-08-18 01:46
Thanks for the report! This appears to be a duplicate of #9234

**Closed by Gudahtt** 2020-08-18 01:46 UTC
