### ISSUE TITLE
CSS does not update

### ISSUE THREAD

**Issue by tomtom87** [MetaMask/metamask-extension#5851] opened 2018-11-29 05:44 UTC
**Describe the bug**
I am updating the css and building but it remains the same

**To Reproduce**
1. clone the repo and make changes to the css try to build with `npm run dist` and `npm start`
2. load extension into browser
3. open extension
4. See no change to css

**Expected behavior**
The css to update the changes made

**Browser details (please complete the following information):**
 - OS: Windows & OSX
 - Browser Chrome
 - MetaMask Version 5.0.2

**Comment by whymarrh** [comment] 2019-02-07 02:19
I believe this is a duplicate of #3352

**Closed by whymarrh** 2019-02-07 02:19 UTC
