### ISSUE TITLE
Recovery seed phrase only restores original "account"/wallet - lost a lot of tokens!

### ISSUE THREAD

**Issue by oojacoboo** [MetaMask/metamask-extension#2641] opened 2017-12-02 04:58 UTC
Firstly, I should state the the current behavior of metamask has me extremely disappointed.  In part I blame myself because I should have known that an "account" (horrible horrible horrible name btw), is really a wallet address with a respective private key, or at least that's my assumption now.

But, when creating a new account, it does not prompt you to save the private key, or a new seed phrase, as it does when you install the metamask client for the first time.

I assumed, I'm guessing incorrectly, that that seed phrase was for all "accounts" created within metamask.  However, just in the past week or so, I guess because of a new update with some fancy terms of service, it has reset itself, asking that I recover from a seed phrase or enter a new password to setup a new account.

I wasn't sure what to do here, I opted to recover initially and did that, then notice that I had a fancy "Account 1" added with some of my tokens (the small portion).  However, the other account I had, did not show up.

So, I then tried recovering my hard drive from a time machine backup in hopes that a version of the OS wouldn't have this destructive update - it did however.  I'm still going to try again for an older update.

So, I have a few questions, if my scenario isn't clear as to the issue.

1.  Where are these wallet configs stored on disk?  And, can I access historical backups to recover a config file that would allow me to just input my password and get back to where I was weeks/month or so ago?

2.  Am I correct in my assumption that a seed phrase is just the private key and represents a single "account"/wallet?

If #2 is correct, why in the world does the UI not make this more clear?  I'm afraid I've lost a substantial amount of money due to this issue.  I was on Slack earlier within a crypto discussion group and a few people tried this as well, equally confused by this and confirmed that it only restored the original account, despite saying that the passphrase was for both accounts.

Please advise, I'd be forever grateful if this account can somehow be recovered.  Thanks.

**Comment by oojacoboo** [comment] 2017-12-02 06:06
Okay, I've been able to resolve this issue - what a whirl-wind!  This issue should be addressed immediately though from a UX perspective as it's a disaster.

After uninstalling the plugin and re-installing the plugin, I was able to access the seed phrase recovery (no other way to access this without uninstalling).  After putting in my seed phrase, I get the original one account, named "Account 1" :(  Then, after clicking "Create New Account" (completely not intuitive), it restored the previous secondary account.  I'm assuming if I have 3 or 4, subsequent accounts added would take these positions, although I have no idea.

Regardless, the lack of focus on this issue is upsetting.  The account recovery process and pieces around this should very rock solid.  Unfortunately, the entire process was extremely confusing.  Additionally, while there are some other issue tickets similar to this, they all talk about clicking the "+" icon, which there is not one anymore.

I'll leave this ticket open for the mods to decide how to handle.

**Comment by sardoru** [comment] 2017-12-02 07:19
OMG! Thank you so much.. thats exactly what happened to me... First I saved the Vault data, uninstalled extension, reinstalled it and added the accounts by "+" again, thank you!!!

**Comment by btcmacroecon** [comment] 2017-12-09 00:51
same exact thing got me too man. I'm like are you serious? I'm just figuring out. I thought it was a standard advisory and then I remember clicking DEN. I had no other option but to input  new passphrase. I still have to figure out how to get it all dialed in again. Shouldn't be too hard but man I'd hate to be the person that thinks its gone for good or can't access it. I thought the seed phrase would have brought it all back too. Sort of scary like you started this thread out as!

**Comment by btcmacroecon** [comment] 2017-12-09 01:02
oh  wow now etherdelta isn't picking up my account....oh noooooo

**Comment by brandoncurtis** [comment] 2017-12-10 02:32
> Additionally, and most importantly, everyone should be encouraged to back up the private key for all wallets created, regardless of metamask.

The seed phrase is enough to recover all accounts, so this would be unnecessary.  The seed phrase is sufficient to regenerate all keys using [any BIP-39 compatible software](https://www.ledgerwallet.com/support/bip39-standalone.html).

A "hierarchical deterministic wallet" (HD wallet) like MetaMask can generate an unlimited number of "accounts" (public/private keypairs) from a single "seed phrase".  With an HD wallet, it's possible to support multiple accounts, and even multiple cryptocurrencies, and all the user has to record is a single seed phrase.

The general concept of HD wallets is discussed in [Bitcoin Improvement Proposal (BIP) 32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki), mnemonics are discussed in [BIP-39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki), and a particular implementation is discussed in [BIP-44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki).

The Ethereum network is still very experimental.  Projects like MetaMask are a public service, and there are still many UX abstraction issues to work through.

**Comment by danfinlay** [comment] 2017-12-18 20:16
To users restoring from the seed phrase, who are looking for all their accounts, just click "Create Account" again, your accounts will be restored in the order they were created. Closing as duplicate of #654.

**Closed by danfinlay** 2017-12-18 20:16 UTC

**Comment by j-zen** [comment] 2018-03-24 19:39
I'm still having the problem. I tried to create a new one but it also comes up empty. Shouldn't there be a record of it? I have my keys and my seed also. Shouldn't it be able to be tracked and located. Freaking out!

Thanks much!

**Comment by lazaridiscom** [comment] 2018-03-25 18:31
@j-zen 

Restore from your Seed, then:

>> To users restoring from the seed phrase, who are looking for all their accounts, just click "Create Account" again, your accounts will be restored in the order they were created

>  I have my keys

Then you can "Import Account" with MetaMask, or another wallet.

**Comment by vishwas1980** [comment] 2018-04-25 12:28
Hey All,
I have issue . I have created one metamask wallet on Token store and then token store wallet is automatically created . I transfer ETH from other  personal wallet to this new personal wallet and transfer again ETH to Token store wallet. I made transaction and purchased some coins and were reflecting in this new token store wallet. But I did't save private key. After that mistakenly i close this account so that now I am not able to access this account having some coins. Can you please help me to recover my token store wallet?

**Comment by danfinlay** [comment] 2018-04-25 18:55
@vishwas1980 Please send usage questions to support@metamask.io, this issue is closed, and is not the same problem as you are reporting.

If you created your accounts in MetaMask, and restored with your seed phrase, you should be able to re-generate all of your accounts by clicking "Add Account" again until you see it.

Our support staff will help you much sooner than our GitHub will usually get an answer, so please ask there.

**Comment by mryellow** [comment] 2018-04-26 10:47
This UX  is reinforced by a "warning" message shown on `Import Account`.

> Imported accounts will not be associated with your originally created MetaMask account seedphrase. 

This suggests that as as opposed importing a key, using the `Create Account` feature within metamask will somehow be associated with your seed phrase.

**Comment by Densi1** [comment] 2018-04-27 20:00
I uninstalled , reinstalled and no funds? created 2nd account no funds. no what ??

**Comment by Densi1** [comment] 2018-04-27 20:16
The problem started after I switched to beta. I was not able to send or receive ether???Following a suggestion from git hub I uninstalled and reinstalled using seed exactly as it was printed and stored in three different sources, so I know the seed is right, but theres a bug in metamask. I don't like to use myetherwallet either. Now I'm not sure what to do?

**Comment by danfinlay** [comment] 2018-04-27 22:44
Please send usage questions to support@metamask.io, this issue is closed, and is not the same problem as you are reporting.
