### ISSUE TITLE
[Bug]: Not able to Send any transaction or deploy any contract with Trezor

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14324] opened 2022-04-01 09:38 UTC
### Describe the bug

**Problem**: I am not able to send any transaction using Trezor hardware wallet.

[Update]: The error `device disconnected during action` might be due to the same problem we had with Ledger account: the state of the dropdown is not cleared and addresses between BIP44 and testnet types are mixed up, turning on a state where addresses don't work on Trezor.

![image](https://user-images.githubusercontent.com/54408225/165118127-badcc8e6-a473-453d-afac-0cefd33fc2f6.png)

See complete explanation here: https://github.com/MetaMask/metamask-extension/pull/14508

### Version

10.13.0

### Browser

Firefox

### Operating system

Linux

**Comment by FrederikBolding** [comment] 2022-04-04 11:04
For whoever ends up tackling this. I've seen this before when trying to use paths that don't match the SLIP44 for the network.

See: 
https://twitter.com/FrederikBolding/status/1433149877207326723
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by seaona** [comment] 2022-04-04 19:14
thanks for the comment @FrederikBolding. I've performed again the process changing the Keypath to Testnet and now the error I get is different:
![image](https://user-images.githubusercontent.com/54408225/161615427-78fc780d-0001-4d29-b98d-643facd66a5d.png)

https://user-images.githubusercontent.com/54408225/161615475-8026e14c-b3c4-4950-a4a5-becdd7319412.mp4

**Comment by jasondesante** [comment] 2022-04-24 23:31
I am also having this issue where metamask does not work at all with my trezors.  This is important that Metamask be able to do stuff like allowing interaction with contracts to do stuff like transferring a token or buying a token.  Please even though not everyone has a Trezor, this is a very essential and important feature of the wallet, being able to interact.

**Comment by jasondesante** [comment] 2022-05-08 04:50
Please help.  There's something called "Otherside land" that only has a limited window to claim and I wasn't able to mint because of hardware wallet problems with metamask, I need to be able to claim the land from my mutant before the 21 day window is over.  Please this is actually important that metamask work with trezor.  I even tried a different browser.

**Comment by vivek-consensys** [comment] 2024-01-25 14:41
I am able to replicate the issue where I am unable to send a tx using Trezor, once the device is locked. Please see screen recording:- 

https://github.com/MetaMask/metamask-extension/assets/106310394/aa6dfc4d-f201-45c1-8262-74ac53cbae7c

**Comment by vivek-consensys** [comment] 2024-04-16 09:51
@Akaryatrh did you manage to debug this? I am still able to reproduce.

**Comment by vivek-consensys** [comment] 2024-04-23 10:45
Tested on MM Extension version `11.14.1` and working as expected using Trezor T

https://github.com/MetaMask/metamask-extension/assets/106310394/2114bb1b-6eb0-4ba1-9045-f5b7175521d5

**Closed by vivek-consensys** 2024-04-23 10:45 UTC
Labels: type-bug, Sev2-normal, hardware-ledger, hardware-trezor, rc :heavy_check_mark:, team-hardware-wallets
