### ISSUE TITLE
I updated metamask and some the game it won't sign in. their website showing me i need install or unlock metamask, but i did install and unlocked.

### ISSUE THREAD

**Issue by Dubsry** [MetaMask/metamask-extension#6411] opened 2019-04-05 11:23 UTC

**Comment by Parinyadahmi** [comment] 2019-04-05 12:45
I found this issue on Metamask 6.3.1 
method get accounts return empty array

**Comment by bhayward93** [comment] 2019-04-05 15:44
I'm working for a site using metamask and we've had an influx of users complaining about this the past couple of days. Is this a known bug to the dev team or a mistake on our users part?

**Comment by PumpkingWok** [comment] 2019-04-08 08:50
Hi there !! Maybe it could be correlated to privacy mode, now it is enable by default. 
In theory the dapps should be ready to manage it since few months, in the meanwhile you can try to disable it in `Settings` -> `Security & privacy` in Metamask.

**Comment by bdresser** [comment] 2019-04-08 16:28
As of 6.3.1 MetaMask enables Privacy Mode by default for new users. This means your address isn't exposed to sites until they ask for your permission.

If you're having trouble using a site that hasn't updated to support Privacy Mode / EIP 1102, you can head to Settings > Security & Privacy and disable Privacy Mode, then refresh the dapp.

@bhayward93 make sure your site is compatible with [EIP 1102](https://medium.com/metamask/eip-1102-preparing-your-dapp-5027b2c9ed76). 

if you're seeing unexpected behavior not described here, let us know and provide detailed steps to reproduce and we can take a look!

**Comment by bdresser** [comment] 2019-06-03 21:42
closing this - let us know if you're still having trouble

**Closed by bdresser** 2019-06-03 21:42 UTC
