### ISSUE TITLE
Show ENS domain in confirmation popup

### ISSUE THREAD

**Issue by calebrate** [MetaMask/metamask-extension#5294] opened 2018-09-19 14:41 UTC
**What problem are you trying to solve?**
I want my users to be certain with the contract address they interact with.

**Describe the solution you'd like**
For this, I would imagine having the ENS name spelt out next to the contract address, combined with a green checkmark.

**Additional context**
This is partially possible in the send ETH form. I would feel more confident if the ENS address would be written out next to the contract address.
In my opinion, the perfect solution would be if every address input would accept an ENS name.

**Comment by bdresser** [comment] 2018-09-19 16:44
thanks for the feedback @calebrate! sounds like a duplicate of https://github.com/MetaMask/metamask-extension/issues/4616

**Comment by calebrate** [comment] 2018-09-19 16:51
> thanks for the feedback @calebrate! sounds like a duplicate of #4616

@bdresser I would wish not only to have this in the form, but also callable from the API, eg
```
web3.eth.signTransaction({
    from: "myaccount.eth",
    gasPrice: "20000000000",
    gas: "21000",
    to: 'vitalik.eth',
    value: "1000000000000000000",
    data: ""
})
```

**Comment by bdresser** [comment] 2018-09-19 16:53
Ah, I see. Thanks for the clarification. Are you accepting these ENS addresses from user input? Or are you suggesting the feature because you anticipate users will prefer to interact with a readable ENS domain?

**Comment by calebrate** [comment] 2018-09-19 19:22
> Ah, I see. Thanks for the clarification. Are you accepting these ENS addresses from user input? Or are you suggesting the feature because you anticipate users will prefer to interact with a readable ENS domain?

I see the main attack vector on most dapps in that the attacker could gain access to the dapps webserver and changes smart contract addresses to steal users deposits.
An ENS domain, is far harder to tamper with, than the dapps web backend, assuming the controling key is offline.
Having the smart contract address resolved in the wallet prevents this attack vector.

**Comment by danfinlay** [comment] 2018-10-15 17:13
Should use reverse-resolution sanitizer to prevent homoglyph attacks:
https://github.com/MyCryptoHQ/ens-validation

**Comment by lyricalpolymath** [comment] 2019-05-07 14:30
+1 on this
using reverse ENS names would also make it easy to independently update the name that appears in the Metamask confirmation popup

**Are these contract names hardcoded?
is there a process to update them?**

example
We just launched the new ENS Registrar, but MM keeps calling "ENS Registrar" the old one

![Screenshot 2019-05-07 at 16 08 21](https://user-images.githubusercontent.com/516744/57307053-2bba6100-70e4-11e9-8196-6cdbd8da7fbc.jpg)

And the [new registrar](https://etherscan.io/address/0xf0ad5cad05e10572efceb849f6ff0c68f9700455#code) doesn't appear to be called ENS Registrar
![Screenshot 2019-05-07 at 16 11 19](https://user-images.githubusercontent.com/516744/57307087-3674f600-70e4-11e9-961a-65959d6c8c41.jpg)

In case you want to update the ENS related contract names
- `ENS Registrar` should now be - [0xf0ad5cad05e10572efceb849f6ff0c68f9700455](https://etherscan.io/address/0xf0ad5cad05e10572efceb849f6ff0c68f9700455#code)
- `old ENS Registrar` should now be - [0x6090A6e47849629b7245Dfa1Ca21D94cd15878Ef](https://etherscan.io/address/0x6090A6e47849629b7245Dfa1Ca21D94cd15878Ef#code)

**Comment by danfinlay** [comment] 2019-05-15 21:32
Hey @cjeria @omnat I opened a design issue for this [here](https://github.com/MetaMask/Design/issues/89). I think this is pretty simple and overdue, maybe we can get it on the next sprint.

**Comment by whymarrh** [comment] 2019-11-17 23:03
This functionality was added to the extension in #7177 (also refs #5525)

**Comment by whymarrh** [comment] 2019-11-17 23:04
Please open up new issues for any problems you run into

**Closed by whymarrh** 2019-11-17 23:03 UTC
Labels: L20-ENS, P3-soon, T09-featureRequest
