### ISSUE TITLE
NewUI: Indicate loading when confirmation screen is starting up

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4195] opened 2018-05-05 19:38 UTC
On stage at EdCon, the New UI confirmation windows took a painful 5 seconds or so to pop up during a live demo.

We should at the very least indicate why it's taking so long (old UI says "estimating gas cost"), and also investigate how we can make it load faster, if it's something we can control.

I wonder if #2991 would improve this performance.

**Comment by bdresser** [comment] 2018-06-04 19:56
i weirdly sometimes see a spinner and label that says "generating transaction." probably 1/10 times, can't reproduce reliably. maybe from [here](https://github.com/MetaMask/metamask-extension/blob/389346913bf076fde6190a61afc4e3e4cd210afc/ui/app/components/pending-tx/index.js#L131)? 

might be the case that the loader exists just isn't showing properly

**Comment by danfinlay** [comment] 2018-09-09 22:55
I just watched a hackathon video where metamask took like 20 seconds for the confirmation window to show anything. It's really painful. At least saying why they're waiting would be a big fix, I think it's often gas estimation.

**Comment by whymarrh** [comment] 2018-10-02 00:35
As discussed a few days ago we'll close this for now an break out separate more specific issues

**Closed by whymarrh** 2018-10-02 00:35 UTC
Labels: L03-UI, P1-asap, T00-bug
