### ISSUE TITLE
Deprecation notices are not helpful

### ISSUE THREAD

**Issue by macbem** [MetaMask/metamask-extension#2016] opened 2017-09-05 13:17 UTC
Metamask lets me know that signing messages or web3 in general will be deprecated, but there aren't any docs on what I can do to make my Dapp future-proof.

I feel like the preferred way of doing things will be announced a day before changes take place, which makes the whole Ethereum + Metamask stack feel really unstable and fragile for me as a developer.

Of course, UI/UX is really important and you guys are doing a great job at that, but IMO you should focus a bit more on Developer Experience as well - otherwise, people aren't going to write Dapps using your platform. It's a bit of a bitter pill to swallow, but I really mean no harm or offence - I just want a stable environment to develop for.

I'd suggest creating a page which would inform developers how they should migrate their code to use new, accepted solutions.

**Comment by flyswatter** [comment] 2017-09-05 15:19
I agree, duplicate of #2014.

I wrote an article like you are requesting just yesterday here:

https://github.com/MetaMask/faq/blob/master/detecting_metamask.md

**Comment by flyswatter** [comment] 2017-09-05 18:32
As for the forward-compatible signing method:
https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527

**Comment by flyswatter** [comment] 2017-09-12 23:54
Fixed and deployed.

**Closed by flyswatter** 2017-09-12 23:54 UTC
Labels: fixed-in-master, L1-injection, P1-asap, T3-discussion
