### ISSUE TITLE
Cryptokitties display

### ISSUE THREAD

**Issue by chaitanyapotti** [MetaMask/metamask-extension#7376] opened 2019-11-10 06:42 UTC
**Describe the bug**
Cryptokitties are being displayed in metamask erc20 token list

**To Reproduce**
get a kitty into metamask address

**Expected behavior**
To not show erc271 in the list of erc20 tokens

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Manjaro
 - Browser Chrome
 - MetaMask Version 7.4.0

**Additional context**
Transfer fails

**Comment by jennypollack** [comment] 2020-01-08 15:50
closing as duplicate of https://github.com/MetaMask/metamask-extension/issues/5230

**Closed by jennypollack** 2020-01-08 15:50 UTC
