### ISSUE TITLE
[Bug]: Confirmations not rejected on close when  "select networks for each site" toggle is enabled

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#22934] opened 2024-02-14 06:28 UTC
### Describe the bug

When a dapp proposes something requiring confirmation, MetaMask will open a "notification window" to show the confirmation to the user. Closing this window should reject the confirmation shown.

This works today in production with a fresh installation (tested with v11.9.4), but it fails if the "select networks for each site" is enabled. With the toggle enabled, the confirmation stays when the window is closed. I had to open the popup again after closing the notification window to reject the confirmation.

### Expected behavior

When the notification window is closed, the currently displayed confirmation should be rejected

### Steps to reproduce

- Enable  "select networks for each site" in the experimental settings
- Connect to a dapp
- Submit a transaction (e.g. the test-dapp "Send" button), which should result in a notification window opening
- Close the notification window
- Open the popup to check whether the confirmation is still pending or not

### Version

11.9.4

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by gauthierpetetin** [comment] 2024-02-15 15:05
Hi @Gudahtt @vandan , we've labeled this issue as a sev1 during triage session but feel free to re-assess if not relevant.

**Comment by Gudahtt** [comment] 2024-02-23 19:27
Downgrading to sev2 because it only affect users who enable this experimental feature. Plus it's just an annoyance, easy workaround that is highly discoverable.

**Comment by adonesky1** [comment] 2024-03-13 18:58
May be addressed by: https://github.com/MetaMask/metamask-extension/pull/22865/ ?

**Comment by BelfordZ** [comment] 2024-04-17 23:17
> May be addressed by: #22865 ?

confirmed

**Closed by BelfordZ** 2024-04-17 23:17 UTC
Labels: type-bug, Sev1-high, team-wallet-api-platform, regression-prod-11.9.4

**Comment by benjisclowder** [comment] 2024-06-14 11:18
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
 
 We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
 
1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

cc: @BelfordZ

**Comment by Gudahtt** [comment] 2024-07-15 19:39
@benjisclowder 


1. What PR fixed the issue?
#22865

2. Can you pinpoint the commit from which the issue originated?

#21522

3. Write a short explanation of the technical cause of the bug

The behavior of rejecting confirmations on close was intentionally disabled here, presumably because it was unclear how to reconcile this feature with the RPC queue feature. There was a comment given that explained the previous method we used to reject confirmations would no longer work.

4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?

4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?

No, not exactly.

4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?

It wasn't clear from the description of the RPC queue feature how we wanted this case to be handled. Ideally we would have had a more comprehensive feature spec that explained what to do in this situation. We should have looped in the confirmations team as well; we had a known issue that impacted their feature, but we didn't discuss it with them.

The design of the QueuedRequestController contributed to the problem as well. Pending confirmations would be duplicated in our state, both in that controller and the ApprovalController, which gave us no clear way to ensure we only counted and rejected each one once. This was fixed in a later version of the controller.

4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

N/A
