### ISSUE TITLE
[Bug]: Custom Approve/SetApprovalForAll screens not displayed after changing Networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18544] opened 2023-04-12 09:43 UTC
### Describe the bug

**Problem**: the Custom Approve screens are not displayed when we perform an approve after changing networks. Instead it is displayed a regular SendETH screen, with the associated Hex Data for that approval (meaning, effectively the transaction is correctly made, but the UI is not correct as we expect to see the custom screens)

https://user-images.githubusercontent.com/54408225/231426602-ff062aaf-f174-431c-847a-d74115aa0173.mp4

https://user-images.githubusercontent.com/54408225/231456814-2b368962-5387-4e63-9219-2316d3acc8c2.mp4

**Affected screens:**
- ERC20 Approve
- ERC721 Approve
- ERC721 SetApprovalForAll true
- ERC721 SetApprovalForAll false (Revoke)

### Steps to reproduce

1. Go to test dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Create Token and accept in MM
4. Click Approve tokens -- check custom screen is displayed
5. Change networks
6. Refresh test dapp
7. Click Create Token and accept in MM
8. Click Approve tokens -- custom screen is **not** displayed now
 

### Version

This is **NOT** happening in prod `10.28.2`but it is in `develop`

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by brad-decker** [comment] 2023-04-13 19:53
After changing networks is a red herring in this case. Even clicking approve tokens again to update your approval amount results in a normal simpleSend type confirmation screen being displayed. Furthermore I cannot seem to ever get the setApprovalForAll confirmation screen to reappear after the first appearance. no matter how many times I change networks etc. @danjm @seaona

**Comment by brad-decker** [comment] 2023-04-13 19:57
Hmmm... I think there is *something* to do with transaction history that is causing this bug to surface. I tried clearing my activity data and saw the approval screen show back up. I started recording. Note that the approval screen shows up AGAIN after i expected it to not to... until I issue a contractDeployment for creating a new token then after that it works as I anticipated.

**Comment by brad-decker** [comment] 2023-04-13 19:57
https://user-images.githubusercontent.com/4448075/231869352-081c354c-853c-48a5-b5fe-c1bf6289e4e0.mov

**Comment by bschorchit** [comment] 2023-04-13 23:12
It seems on the video you're getting the correct fallback screen (a contract interaction one), Brad. Although, ideally you would be seeing the custom UI there, this might not be the exactly the same as Mariona reported above as she was seeing a Send ETH screen with approve tx data instead. 

I've come across the contract interaction screen instead of the custom UI in prod recently (10.28.2) and here's Dan's comment on it in case it's helpful: https://github.com/MetaMask/metamask-extension/issues/18521#issuecomment-1502438778

**Comment by bschorchit** [comment] 2023-04-13 23:15
(or maybe I misunderstood your `until I issue a contractDeployment for creating a new token then after that it works as I anticipated.` 😅) I've re-read your first comment and realized that you also saw it as a simple send before 🙈

**Comment by brad-decker** [comment] 2023-04-14 17:27
@bschorchit in @seaona 's screen cast its a contract interaction, not a simple sendEth screen. In any case there is something going on with the logic of which confirmation screen to display. I still don't understand what controls this logic. it appears to be based on the route?

**Comment by seaona** [comment] 2023-04-17 10:22
Notice, on my second video, I landed into a **sendETH Screen** instead of Contract Interaction @brad-decker @bschorchit @danjm 
I've also landed into the Contract Interaction screen (see first video).

**Comment by danjm** [comment] 2023-04-17 16:20
Sounds like there may be two separate issues here:

1) We are not showing the custom "Approve" screen sometimes when we should be
2) Sometimes the sendETH screen i shown

The first is a problem in its own right. In the case of ERC20 tokens, we shouldn't have to default to the "Contract Interaction" screen, that should only be needed in the case NFT approvals.

**Comment by danjm** [comment] 2023-04-17 16:22
I see that when I repro this, `assetStandard` (returned by `useAssetDetails`) is undefined.

`useAssetDetails` is called within `ConfirmTokenTransactionSwitch`. `assetStandard` is passed to `ConfirmApprove`, which is where the logic is to fall back to the contract interaction screen if we don't know the standard.

**Comment by brad-decker** [comment] 2023-04-17 16:42
I'll work on resolving the tokenId being present for a ERC20 tx

**Comment by brad-decker** [comment] 2023-04-17 16:46
@danjm could you share your methodology for understanding this flow, was it just prior context of how the confirmation screens stack up? I regret that I have been working with MetaMask for three years and still don't fully understand the logic here :|

**Comment by brad-decker** [comment] 2023-04-17 17:23
So, I added a console.error in the getAssetDetails method where it fails and this is what I'm seeing:
![image](https://user-images.githubusercontent.com/4448075/232562036-c482ee97-5a3f-4e9c-bbb4-5b783b81dff3.png)
I also made the useAssetDetails effect an infinite loop until a contract standard was known, so it doesn't appear to be a race condition at all and there is definitely something about switching networks that breaks this. I think I may know the cause and it may be our network controller hooks that are sent to other controllers. I'll investigate.

**Comment by brad-decker** [comment] 2023-04-17 19:22
Alright so I don't think the asset contract controller is getting updated appropriately when the network changes. Check out this very long video. In this video I'm showing you my background console as I do the actions outlined by @seaona. In this case the asset controllers' provider is always the network *before* the last change. It is correct on boot, which is why in MOST of our test cases we are getting a clean first attempt, but when we start switching networks its a hit or miss if the address of our TST is a contract at all on the network we were on prior to the current one. I'm a little confused as to how the 'set provider' method of the assets contract controller is getting called, it must be a part of the base controller, I'll ask @mcmire for some assistance in understanding this and it could either be a controller issue or a metamask-controller setup issue.

**Comment by adonesky1** [comment] 2023-04-17 19:28
looks like this could be related: https://github.com/MetaMask/core/issues/1186

**Closed** 2023-04-18 16:33 UTC
Labels: type-bug, release-blocker, team-extension-client, team-extension-platform, v10.29.0
