### ISSUE TITLE
Allow creation of new seed again

### ISSUE THREAD

**Issue by jchittoda** [MetaMask/metamask-extension#5445] opened 2018-10-06 08:06 UTC
**What problem are you trying to solve?**
As of now, MetaMask supports seed creation only first time. When a user wants to create a new seed, there is no option. It only showed import seed on the login screen. For a user to create a completely new seed, he has to uninstall and re-install plugin.

**Describe the solution you'd like**
There should be another option on the login screen to allow a user to create another completely new seed. This option is not present when a user has already created a seed.

**Additional context**
Although this feature could be bit confusing for the users who knew less about the blockchain and account stuff. They can easily get confused with "create new account" and "create new seed". But for the developers, this should be an option to create a new seed. For the safety of normal users, you can hide this button, but for developers features, this should be there, somewhere hidden which can be unlocked by devs.

**Comment by bdresser** [comment] 2018-10-08 00:44
Duplicate of https://github.com/MetaMask/metamask-extension/issues/4828

**Closed by bdresser** 2018-10-08 00:44 UTC
