### ISSUE TITLE
Metamask .test domain (or any other non TLD) triggers search from Portal Network

### ISSUE THREAD

**Issue by zmaglica** [MetaMask/metamask-extension#4979] opened 2018-08-08 05:21 UTC
Bug Reports:

  I am using .test domain for local development and when I type URL in the browser, Metamask redirects me to Portal Network search. I am not sure why you guys using that search engine in first place...
  *  Expected Behavior
  When I type URL in browser it actually redirects you to URL you typed
  *  Actual Behavior
  If you type any non-TLD domain in browser, Metamask will redirects you to the portal search engine (tested with .test domain)
  *  Browser Used
  Chrome 68
  *  Operating System Used
  Windows 10

**Comment by simonk1234** [comment] 2018-08-08 07:12
I've also had this message and would like to know if it's safe to accept.

**Comment by jmigdelacruz** [comment] 2018-08-08 08:55
Same issue, same specs except:

Operating system used

- MacOS Sierra

**Comment by bdresser** [comment] 2018-08-08 17:44
@zmaglica thanks for the question. We're not routing your request through portal.network - we're loading the ENS info from the blockchain via Infura, and the IPFS content via infura as well.

You can read a full summary of the feature here: https://consensys.zendesk.com/hc/en-us/articles/360012782931

I'll leave this open for a couple days in case other folks have the same question.

**Comment by bitpshr** [comment] 2018-08-08 18:03
@zmaglica @jmigdelacruz some additional context: URLs in the form of both `<some_domain>.eth` and `<some_domain>.test` are considered valid ENS URLs on certain networks (with `.test` TLDs being specific to testnets like Rinkeby and Ropsten.) You can read more about the difference between these two TLDs [here](http://docs.ens.domains/en/latest/introduction.html#ens-on-ethereum).

This means that MetaMask (and any other dapp browser that resolves ENS domains) will attempt to resolve `.test` URLs on using ENS.

**Comment by jmigdelacruz** [comment] 2018-08-09 08:50
@bitpshr Thanks for clarifying. Just curious, why do we need Metamask to resolve ENS domains? Can't we leave that functionality to the browser or let users decide to enable/disable this feature?

As a user, i'm coming from the fact that i'm using Metamask primarily, apologies for the simple term, as a "wallet." I am not interested in ENS domains.

**Comment by eduadiez** [comment] 2018-08-09 15:31
@bdresser I've reported an issue #5009 related to this and a PR #5010 to fix it, I hope you can review it.

**Comment by bdresser** [comment] 2018-08-10 15:27
@zmaglica this issue is fixed on 4.9.2 by https://github.com/MetaMask/metamask-extension/pull/5010. We'll try DNS first, and if it doesn't resolve, then try ENS.

**Closed by bdresser** 2018-08-10 15:27 UTC
Labels: T05-userQuestion

**Comment by pesho** [comment] 2018-08-17 21:45
Seems that #5010 does not fix the issue completely (using Metamask 4.9.3 on Chrome/Linux).

I have a `.test` domain configured in `/etc/hosts` which is intercepted by Metamask. I have to disable Metamask in order to access it.

Requesting that the issue be reopened @bdresser

**Comment by pesho** [comment] 2018-08-17 21:50
Update: Looks like this is actually a Chrome issue. Chrome seems to have stopped resolving domains via `/etc/hosts` after updating to v68.x. So Metamask attempts to handle it after the browser fails to resolve the domain.

You can disregard my previous comment.

**Comment by ilyakatz** [comment] 2018-10-01 16:57
I'm getting this on Firefox, so it's not just a Chrome issue. Would be nice to reopen it

**Comment by bdresser** [comment] 2018-10-01 18:52
This issue was for MetaMask matching on all `.test` domains. @ilyakatz could you open a new issue with reproduction steps for the problem you're seeing? Thank you!

**Comment by ilyakatz** [comment] 2018-10-01 19:01
Yes, i'm seeing the same problem with `.test` domains. just answering to @pesho who seemed to imply that it's only a chrome issue

**Comment by bdresser** [comment] 2018-10-01 19:48
We can't reproduce the original issue, and pesho is writing about interference with domains added to his `/etc/hosts`. Would appreciate a clean issue with your specific repro steps! Thanks.

**Comment by pesho** [comment] 2018-10-02 00:08
I was actually mistaken in my previous message, sorry for any confusion caused. This was the wrong part:

> Chrome seems to have stopped resolving domains via /etc/hosts after updating to v68.x. So Metamask attempts to handle it after the browser fails to resolve the domain.

Back then it turned out that there was simply nothing listening on that port locally (Haproxy had failed to start due to incorrect config). It was not a Chrome bug in fact. Metamask actually intercepts such requests not only when DNS doesn't resolve, but also when the target can't be reached (@ilyakatz check if you have a similar issue). 

In my case fixing the Haproxy config resolved the issue. I didn't post an update here back then because I had already added enough noise to the thread.
