### ISSUE TITLE
Strange file filled up my HD containing endless code that seems to be from MetaMask

### ISSUE THREAD

**Issue by yousei-san** [MetaMask/metamask-extension#5204] opened 2018-09-05 13:04 UTC
As the title says, I noticed my HD was getting filled and I couldn't figure out why until I found a file called .asd.swp that took over 200GB of space and contained lots of code, I took a picture:
![2018-08-29-182436_1366x768_scrot](https://user-images.githubusercontent.com/31820981/45094720-c19c8700-b124-11e8-971c-33e0d5625d7d.png)

Also there was another smaller file called .asd.swo that also contained code but was much smaller. I deleted the files already because the .swp file seemed to be growing and I was running out of space.
I haven't really used MetaMask much on this laptop, I tried if it worked on TorBrowser but it didn't and I can't give you the logs from that since the extension won't open, I've probably some time ago checked some dapps with Brave Browser and here's the logs from that:

[logs.zip](https://github.com/MetaMask/metamask-extension/files/2352831/logs.zip)

I'm running Debian buster on this laptop.

**Comment by bdresser** [comment] 2018-09-05 17:37
@kumavis @tmashuang

**Comment by onetom** [comment] 2018-11-20 07:04
The `.swo` and `.swp` extensions are used by `vim` as a form of journaling, so it can restore changes after a crash.
It doesn't seem to be related to MetaMask though.
Why do you think it's related?
Also, where are these files?
The screenshot suggests they are in `~/Downloads`.

**Comment by tmashuang** [comment] 2020-02-05 19:29
We will keep this in mind but fundamentally don't know the cause of this file. This seems to look like our source code. but we do not allow users to manually download this. Could it be browser/OS issue? Closing for now.

**Closed by tmashuang** 2020-02-05 19:29 UTC
Labels: N01-needsResearch, T10-spooky
