### ISSUE TITLE
[FLASK] Race condition when installing a snap

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/metamask-extension#15194] opened 2022-07-12 10:08 UTC
Sometimes when installing a snap, the install prompt may be auto-rejected due to a race condition. This happens after accepting the connect prompt allowing the DApp to connect to the snap. 

I believe the race condition occurs when the `permission-connect` component manages to load the install prompt after the connect prompt but before the first window is closed, then because the "notification" is supposed to close, it detects the window closing and automatically cancels the request.

**Comment by rekmarks** [comment] 2022-11-14 17:59
@bowensanders please reproduce.

**Comment by bowensanders** [comment] 2022-11-29 16:56
This has been reproduced. The "approve and install" screen never appears.

The following error was produced in background.html console:

Adding snap: npm:@metamask/test-snap-error
​Authorizing snap: npm:@metamask/test-snap-error
​ Error when adding snap. Error: Assertion failed.
  at new i (common-0.js:1:306644)
  at s (common-0.js:1:306563)
  at n.assert (common-0.js:1:306797)
  at background-1.js:15:52160
  at Array.map (<anonymous>)
  at le.M (background-1.js:15:51987)
  at le.authorize (background-1.js:15:42505)
  at le.processRequestedSnap (background-1.js:15:39960)
  at async background-1.js:15:38720
  at async Promise.all (index 0)
  at async le.installSnaps (background-1.js:15:38460)
  at async n.handleInstallSnaps (background-1.js:3:113263)
  at async implementation (background-1.js:3:116148)
  at async background-5.js:8:106236

**Comment by bowensanders** [comment] 2022-11-29 17:06
Clarification: No snaps will install once this happens.

**Comment by FrederikBolding** [comment] 2022-11-29 17:16
@bowensanders This looks like an unrelated error to this issue 🤔

**Comment by FrederikBolding** [comment] 2022-12-05 13:41
@bowensanders Could you try to reproduce this on the latest version?

**Comment by bowensanders** [comment] 2022-12-07 23:55
I have tried several different snap combinations, and cancelling install at either connect or at accept no longer causes a problem with installation for me, following the steps above.

It appears as though the problem is no longer a problem.

**Comment by kenhkan** [comment] 2022-12-14 17:23
Closing since we cannot reproduce this.

**Closed by kenhkan** 2022-12-14 17:23 UTC
Labels: type-bug, area-snaps, flask
