### ISSUE TITLE
Would be great to be able to perma-set my preferred gas price to safe-low

### ISSUE THREAD

**Issue by JohnAllen** [MetaMask/metamask-extension#6926] opened 2019-07-28 00:06 UTC
**What problem are you trying to solve?**
Basically it's annoying having to reduce the gas price for every tx.  Just let me set my preferred gas price to safe-low, since I need to make many transactions and have to click extra buttons each time.

**Comment by bdresser** [comment] 2019-08-02 19:15
closing as a duplicate of the more expansive https://github.com/MetaMask/metamask-extension/issues/3912, added your comment there. thanks for the feedback!

**Closed by bdresser** 2019-08-02 19:15 UTC
