### ISSUE TITLE
Lost ETH Please help !!

### ISSUE THREAD

**Issue by vemuriraja** [MetaMask/metamask-extension#3103] opened 2018-01-26 00:40 UTC
I did a transaction long back on Meta mask and it was rejected then.Yesterday i found that the same transaction went through without my notice and it shows a warning sign.

https://etherscan.io/tx/0x2ca0159555b051ff202551bd2bc68417eedcc9eda06f58f8a0c5fff1f24fbd8d

I am not sure what happened.

What can I do to get my Ethereum back?

Thanks!

**Comment by vemuriraja** [comment] 2018-01-26 00:54
[MetaMask State Logs.txt](https://github.com/MetaMask/metamask-extension/files/1666198/MetaMask.State.Logs.txt)

**Comment by danfinlay** [comment] 2018-01-29 19:02
Regarding your "rejected" transaction - let me explain a bit more. You didn't reject your transaction. What you clicked was a button to re-submit another tx with a higher gas price to try and get it accepted. So your original tx probably did go through even though you thought it was rejected. I understand how this is confusing. We're going to need to explain this better. But please understand this is what the case is at the moment. So your funds that were sent away are where they were originall

**Comment by danfinlay** [comment] 2018-01-29 19:02
Closing as duplicate of #3011.

**Closed by danfinlay** 2018-01-29 19:02 UTC
