### ISSUE TITLE
Setting a custom Network and trying to send freezes all buttons

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-extension#8020] opened 2020-02-08 11:57 UTC
**Describe the bug**
If you set a Custom RPC to use a different Network, like:

Network name: xDai Chain
New RPC URL: https://dai.poa.network
ChainID: 100
Symbol: XDAI
Block explorer: https://blockscout.com/poa/xdai/

The balance of the native token in that Network appears correctly, but if you click SEND the interface (e.g. while in expanded view) freezes and all buttons stop working.

A blank window issue also arises (could help debug #4894 ?), hence the need to use the expanded view after a few tries.

**To Reproduce (REQUIRED)**

1. Add the custom network shown above
2. Resolve the blank window issue by using the expanded view () or re-opening the browser several times.
3. See the balance update correctly
4. Click the SEND button to see error

**Expected behaviour**
A clear description of what you expected to happen.

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome Version 82.0.4052.0 (Build oficial) canary (64 bits) 
 - MetaMask Version 7.7.2

**Screenshots**
This is what appears in the Console right after clicking the SEND button, which does nothing and freezes all other buttons in the expanded view (all except the circle profile picture button in the top-right).

<img width="1440" alt="1a" src="https://user-images.githubusercontent.com/2995401/74084833-435bb700-4a73-11ea-810d-5547647b27c7.png">

<img width="1440" alt="2a" src="https://user-images.githubusercontent.com/2995401/74084835-46ef3e00-4a73-11ea-8435-443e140a42d8.png">

<img width="1440" alt="3a" src="https://user-images.githubusercontent.com/2995401/74084836-4a82c500-4a73-11ea-8396-ef8e5cb47908.png">

<img width="1440" alt="4a" src="https://user-images.githubusercontent.com/2995401/74084839-4d7db580-4a73-11ea-843f-6c300cfe9a52.png">

**Comment by whymarrh** [comment] 2020-02-08 21:02
> MetaMask Version 7.7.2

Does this issue persist in 7.7.**4**? We've fixed an important conversion related bug in the latest version.

**Comment by tmashuang** [comment] 2020-04-07 18:05
Unable to reproduce on 7.7.8

**Comment by Gudahtt** [comment] 2021-01-11 15:25
Closing, as we've been unable to repro since the version mentioned. @rdymac let us know if you can still repro this though, and we can re-open this.

**Closed by Gudahtt** 2021-01-11 15:25 UTC
Labels: S1-high, T00-bug, x02-customNetworks
