### ISSUE TITLE
Low Gas Estimates for Uniswap Transactions

### ISSUE THREAD

**Issue by ashleigh-schap** [MetaMask/metamask-extension#8869] opened 2020-06-29 15:35 UTC
<img width="338" alt="Screen Shot 2020-06-18 at 4 19 17 PM" src="https://user-images.githubusercontent.com/32169583/86026208-6b9e7f00-ba2f-11ea-86d1-037b0c500303.png">
<img width="354" alt="Screen Shot 2020-06-18 at 4 19 23 PM" src="https://user-images.githubusercontent.com/32169583/86026213-6ccfac00-ba2f-11ea-9fe6-149912ed4013.png">

Currently, Metamask transactions suggest gas prices which are too low for many uniswap transactions to complete. It looks like Metamask is properly suggesting gas estimates for other projects like Kyber/Compound, and Uniswap itself doesn't do anything around gas estimation, so the issue must be with Metamask. It looks like maybe the default gas estimation is even lower than metamask's safe low. 

As you can see in the screen shots, the default is $0.61 of gas but when you manually edit, the lowest gas price for a "slow" transaction is $0.84.

**Comment by danfinlay** [comment] 2020-06-29 17:24
Possibly fixed in version 8 - waiting for confirmation.

**Comment by ashleigh-schap** [comment] 2020-06-29 17:48
Not fixed in v8. Just tried it. Screenshots attached. 
<img width="353" alt="Screen Shot 2020-06-29 at 7 44 44 PM" src="https://user-images.githubusercontent.com/32169583/86038565-6cd8a780-ba41-11ea-817c-3846f1b532eb.png">
<img width="339" alt="Screen Shot 2020-06-29 at 7 44 37 PM" src="https://user-images.githubusercontent.com/32169583/86038570-6e09d480-ba41-11ea-8df9-2852b74a6f65.png">

**Comment by danfinlay** [comment] 2020-06-29 18:51
That's very well defined, thanks for the report! Could you have someone who has sent such a tx to send their [state logs](https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-) to us? Could be a contact you have already or support@metamask.io

**Comment by ashleigh-schap** [comment] 2020-07-01 19:09
Will do! Thanks Dan. :)

**Comment by danfinlay** [comment] 2020-07-01 23:56
Please let me know the ticket ID once you have one so I can follow up. I don't see you in there yet.

**Comment by danfinlay** [comment] 2020-07-02 00:00
I tried this myself and the uniswap gas price suggested was actually higher than the high.

We confirmed today that because the default suggested gas price can be set from a different block from the three-button suggestion, so we are aware of possible disparity there. What I haven't seen any of is evidence for why this should be unique to uniswap.

I did a sample TX on uniswap and confirmed that uniswap is not setting the gasPrice, so this should not be uniswap's fault. We're going to have to be addressing this during this week because ethgasstation is also undergoing an API migration which we are also responding to during this time.

**Comment by ashleigh-schap** [comment] 2020-07-02 08:18
Yes, the same thing happened to me yesterday, but then this morning the low was lower than the low again so I was able to reproduce it. I just sent something to support, ticket #39411. Strangely I was only able to reproduce it on the current version of metmask, not v8, but the other day v8 was also suggesting bad gas #s. V8 also had the problem yesterday where it was actually higher than the high.

**Comment by tmashuang** [comment] 2020-07-02 08:46
Could this be the discrepancy between the time of initial gas price estimation on tx creation and `BASIC_PRICE_ESTIMATES` that's cached. Seems that discrepancies are pretty small, either higher or lower. Unfortunately, the logs don't show localStorage state where we store the cached responses. If possible, could you show the timestamp of last retrieved estimate and the estimates?

To retrieve the info open the UI developer console on Chrome, right click anywhere in Metamask and click `Inspect`, then under the `Console` tab type `window.localStorage.window.localStorage.BASIC_PRICE_ESTIMATES_LAST_RETRIEVED` and press `Enter` on keyboard. To get the estimated values type `window.localStorage.BASIC_PRICE_ESTIMATES`.

If what I am assuming is correct, the solution would be to reduce retrieval time of the gas estimates, which requires change on this line https://github.com/MetaMask/metamask-extension/blob/80132f55800bebfaaaf52c56d57352c3137bb232/ui/app/ducks/gas/gas.duck.js#L209 which increases the amount of times use the api.

**Comment by tmashuang** [comment] 2020-07-02 08:54
Also, removing the price padding here https://github.com/MetaMask/metamask-extension/blob/80132f55800bebfaaaf52c56d57352c3137bb232/ui/app/ducks/gas/gas.duck.js#L235-L240 might be it too.

**Comment by ashleigh-schap** [comment] 2020-07-07 23:29
hey guys, any update here? I got an email back from support saying the issue should be fixed in v8. It wasn't working before; does that mean v8 has been updated? When is v8 release? 

Thanks for your help.

**Comment by tmashuang** [comment] 2020-07-07 23:57
Version 8 is live on Firefox and we're working out small bugs. It is not yet live on Chrome.

**Comment by Gudahtt** [comment] 2021-01-13 15:53
As of #9867 (which shipped in v8.1.6) we no longer use ETH Gas Station for our gas estimates. Now we use `eth_gasPrice` for the initial gas price, and we use our own API (originally built for MetaSwaps) for the gas estimates in the three buttons shown.

I'll close this issue for now, since it seems likely that the original problem here was at least partially caused by ETH Gas Station estimates being severely delayed in some cases. But please let us know if you're still experiencing this issue on the latest version of MetaMask. Thanks!

**Closed by Gudahtt** 2021-01-13 15:53 UTC
