### ISSUE TITLE
send multiple transactions in specific order

### ISSUE THREAD

**Issue by or2008** [MetaMask/metamask-extension#2731] opened 2017-12-12 08:33 UTC
I have a series of transactions that need to be submitted in a specific order, is there a way to send multiple transactions to metamask, and show them in the submit transaction screen one after another?

currently I am using Promise.all as suggested here
https://github.com/MetaMask/metamask-extension/issues/1329

but they appear in a random order to the user..

**Comment by or2008** [comment] 2017-12-13 12:04
that's right, I can chain them, but then Metamask opens a different screen for each transaction (user clicks on submit, the popup close, then a new popup open, and user submit again).. not the best UX. 

I wonder if is there a way to to send serial transactions and open this popup (with 1 of 2 indicator):
<img width="405" alt="screen shot 2017-12-13 at 13 55 37" src="https://user-images.githubusercontent.com/3414979/33937847-b4f8148a-e00d-11e7-9d67-b8f6f3bb6d4f.png">

I also tried working with batch requests, but the transactions order display randomly

**Comment by danfinlay** [comment] 2017-12-18 19:40
Closing as a duplicate of #1666.

**Closed by danfinlay** 2017-12-18 19:40 UTC
Labels: T1-enhancement
