### ISSUE TITLE
Why am I required to have an account? (esp with hardware wallets)

### ISSUE THREAD

**Issue by NullVoxPopuli** [MetaMask/metamask-extension#13043] opened 2021-12-09 23:12 UTC
**Describe the bug**

I do not want a separate account -- it's an address I never use, I've lost the private key already (because I don't care).
For best UX, why not allow "just hardware wallet" support?
I opened a similar issue for the Temple wallet here: https://github.com/madfish-solutions/templewallet-extension/issues/485

**Steps to reproduce (REQUIRED)**

1. Have no prior account
2. Try to connect Ledger wallet to uniswap
3. Open metamask
4. be forced to create a throw-a-way account and be asked a bunch of questions that are irrelevant, because the account won't be used.

**Expected behavior**
I should "just" be able to use my ledger

**Screenshots**

**Browser details (please complete the following information):**
Firefox: 94
Ubuntu: 21.04
Wallet: Ledger Nano X
Metamask: 10.7.1

**Comment by danjm** [comment] 2022-01-06 13:53
This is a duplicate of https://github.com/MetaMask/metamask-extension/issues/12534

Hopefully we will work on this within the next few months

**Closed by danjm** 2022-01-06 13:53 UTC
Labels: area-hardware, ux-enhancement
