### ISSUE TITLE
[Bug]: Trezor addresses are cached after unplugging Trezor

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14546] opened 2022-04-27 15:39 UTC
### Describe the bug

**Problem**: after I've loaded a couple of Trezor addresses, if I unplug Trezor and go to import address I am still able to see the list of addresses and import more addresses while having Trezor unplugged

https://user-images.githubusercontent.com/54408225/165556809-1224fdd7-ad66-4fe0-994f-ca3375fd038b.mp4

.

### Steps to reproduce

1. Unlock Metamask and Trezor
2. Import a couple of Trezor addresses
3. Unplug Trezor
4. Go to Import Hardware Wallet: see the list is available even without having Trezor plugged
5. Import addresses: see you are able to import addresses without having Trezor plugged

### Version

10.4.0

### Browser

Chrome, Firefox

### Operating system

Linux

**Comment by Ivshti** [comment] 2022-04-29 10:46
@seaona afaik this is intended behavior

**Comment by AlexJupiter** [comment] 2022-12-06 15:24
Yes I think this is intended behaviour. Proposing we close this.

**Closed by AlexJupiter** 2022-12-06 15:24 UTC
Labels: type-bug, area-hardware, Sev3-low, team-key-management, bug
