### ISSUE TITLE
Opening blank screen

### ISSUE THREAD

**Issue by Catley94** [MetaMask/metamask-extension#4545] opened 2018-06-11 13:07 UTC
I have just installed Metamask on Firefox v60.0.1 on Ubuntu v 18.04 
Everytime I open it, it has a blank screen and then closes a second later.
I was able to accept the terms and conditions but after it will not open.

Thanks,

Samuel Catley

**Comment by bdresser** [comment] 2018-06-11 16:45
thanks for reporting @Catley94. 

I'm closing this as a duplicate of #4502, you can track progress on this issue there.

**Closed by bdresser** 2018-06-11 16:45 UTC
