### ISSUE TITLE
[CRITICAL] Fix for High-Severity Bug #2393 (P1-asap) remains Unprocessed

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3236] opened 2018-02-13 15:17 UTC
(If you know the developers, please ping them.)

There is a bug-fix out there, for the #2393 issue (and several others mentioned within #2978). Its this  thing where switching Networks disables events and logs. The fix is tiny:

https://github.com/MetaMask/metamask-extension/pull/3224/files

It has been confirmed by 3 other users but remains unprocessed till now, despite its that kind of fix that must go out to the live product yesterday(!).

Please ensure that this gets some attention.

**Comment by danfinlay** [comment] 2018-02-13 19:51
Closing as duplicate of #2978. Please be patient, this is on our radar.

**Closed by danfinlay** 2018-02-13 19:51 UTC
