### ISSUE TITLE
BatchRequest is not working properly with metamask

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#6796] opened 2019-07-03 22:49 UTC
https://codepen.io/rstormsf/pen/bPKxBv?editors=1010
Steps:
```js
function metamaskBug() {
  const web3_beta34 = new Web3(window.web3.currentProvider)
  window.ethereum.enable().then(async (res) => {
    const acc = res[0]
    const batch = new web3_beta34.BatchRequest()

    const tx = web3.eth.sendTransaction.request(
      {
        from: acc,
        to: '0x0039F22efB07A647557C7C5d17854CFD6D489eF3',
        gas: '0x186A0',
        gasPrice: '0x3B9ACA00',
        value: '0x0',
        data: '0x4869207468657265'
      },
      () => {}
    )
    batch.add(tx)
    const tx2 = web3.eth.sendTransaction.request(
      {
        from: acc,
        to: '0x0039F22efB07A647557C7C5d17854CFD6D489eF3',
        gas: '0x186A0',
        gasPrice: '0x3B9ACA00',
        value: '0x0',
        data: '0x4869207468657265'
      },
      () => {}
    )
    batch.add(tx2)
    const { response } = await batch.execute()
    })
}
```

Notice how the UI responds to the **second** transaction.
![metamaskBug2](https://user-images.githubusercontent.com/9360827/60629312-0f683700-9daa-11e9-8a64-db7286d229fb.gif)
Demo: https://codepen.io/rstormsf/pen/bPKxBv?editors=1010

Issues: 
The UI doesn't display passed in values: gas, gasLimit, etc even though it actually knows them since the tx goes thru if I submit them

**Comment by danfinlay** [comment] 2019-07-03 23:42
Was this a sudden change you noticed in behavior, or is this a longer lasting issue?

Also please check your version: We just deployed 6.7.2, which fixed a similar issue: #6777, #6772

**Comment by rstormsf** [comment] 2019-07-04 08:51
@danfinlay 
Now i see a different behavior on 6.7.2
On 1st tx, it shows as `send Ether`
![image](https://user-images.githubusercontent.com/9360827/60653089-35b7c200-9dfe-11e9-8697-ec39bc99c8b4.png)


on 2nd tx, it shows as contract interaction
![image](https://user-images.githubusercontent.com/9360827/60653103-3f412a00-9dfe-11e9-9d02-a67083deb453.png)

**Comment by danfinlay** [comment] 2019-07-04 17:13
We recently added some new methods of detecting method signatures, and it seems your method signature `0x48692074` is being detected as `SENT ETHER` (not to be confused with `SEND ETHER`). This lookup has a timeout, and so at first glance, it seems like your second window rendered before the response could get back in time.

I'm not sure where that `sent ether` key is coming from yet, as it's neither on 4byte nor the parity on-chain method registry, we'll have to look into that, but otherwise this looks approximately correct.

Another issue I notice is that your recipient address is short, and does not resemble an Ethereum address, which is very strange and we'll have to also check for causes of. Looks like maybe the ellipses is getting cut off on your screen for some reason.

**Comment by whymarrh** [comment] 2019-07-04 17:51
@rstormsf thanks for the CodePen, that's a huge help! I see the method name for both transactions when tabbing through the txs, do you see the same on your end?

<img width="944" alt="" src="https://user-images.githubusercontent.com/1623628/60682710-eeb5e500-9e6e-11e9-8a81-23a98438cdc6.png">

I want to confirm that this behaves the same for both of us. Similar to @danfinlay, I find the rending of the recipient address strange, as it seems to render fine on my end. 😬 

I can reproduce the incorrect method names, as you outlined, when I confirm the first tx:

<img width="944" alt="" src="https://user-images.githubusercontent.com/1623628/60682784-389ecb00-9e6f-11e9-940a-3ef6ef291e89.png">

Thanks again for the CodePen eh, that's extremely helpful.

**Comment by rstormsf** [comment] 2019-07-04 19:44
as the data, I used 
```js
web3.fromAscii('Hi there')
"0x4869207468657265"
```
just to say hi to you ;-)

**Comment by rstormsf** [comment] 2019-07-04 19:47
feel free to check this usage on real Dapp: https://multisender.app on testnets, you will see that for some reason 1st tx always thinks it's `send ether`, not `contract interaction`

**Comment by tmashuang** [comment] 2020-02-13 21:38
Closing this as fixed. Tested both links of reproduction, codepan and multisender, and transactions on both sites successfully went through in the correct order and parameters. If this is not the case, please comment and I'll reopen.

**Closed by tmashuang** 2020-02-13 21:38 UTC
