### ISSUE TITLE
[Bug]: UX Multichain: Better Handle Pending Manual + Dapp-Suggested Transactions Between Networks

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#25455] opened 2024-06-20 21:34 UTC
### Describe the bug

When creating but not confirming a manual send on Network A, then switching to another tab that was last connected to Network B and doing a dapp-submitted transaction, the original confirmation for the Send "disappears".

### Expected behavior

To be determined....

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/46655/ede498a2-354f-4583-9ee7-7419eb4af80c

### Steps to reproduce

1. In tab 1, go to Test Dapp and connect to Sepolia
2. In tab 2, manually open MetaMask and switch to Ethereum Mainnet
3. Start a manual send on Ethereum Mainnet and get to the confirmation screen but *don't confirm*; the MetaMask badge icon will show the blue "..."
4. Switch back to tab 1, click the MetaMask icon, see that we're still on Ethereum Mainnet and with the transaction confirmation you started (yay, we didn't auto-switch to Sepolia because a confirmation exists)
5. Click "Send EIP1559 Transaction" in the test-dapp
6. *BEHAVIOR*: The Mainnet transaction disappears, then the Sepolia send confirmation displays

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by darkwing** [comment] 2024-06-20 21:37
By contrast, two dapp-suggested sends across chain work as I would expect:  one after another:


https://github.com/MetaMask/metamask-extension/assets/46655/5034540c-3fbf-4a3d-98db-d05f5ce5a40e

**Comment by jiexi** [comment] 2024-06-20 22:17
Confirmed, seeing this behavior on V12 1c7e132f5f4edeed815b2c9400c7cf09a5a26c91

**Comment by jiexi** [comment] 2024-06-20 22:25
Being on a different network between the manual send and dapp transaction is key to repro

**Comment by darkwing** [comment] 2024-06-21 05:58
We made the conscious decision to disable NetworkPicker in Send flow due to issues we ran into, and that the Network has never been allowable to switch mid-send.  That would be why switching to a dapp on another network blows away the draft transaction.  I think we should close this unless we can think of a more graceful way to let the user know the transaction will be gone

**Comment by jiexi** [comment] 2024-06-21 16:13
What are you thoughts on keeping this open, but removing the release and regression tags?

**Comment by hesterbruikman** [comment] 2024-06-26 13:05
@jiexi @darkwing apologies for the slow response. I agree with removing the release and regression tags. It's in any case not a regression as this is a sideeffect of dapp selected network introduced in v12.

I don't consider this a release blocker either. It's not expected for a previous transaction to disappear. But I consider the flow an edge case with no risk of funds loss. 

- GIVEN User has an unapproved, in-app send confirmation request on network A
- WHEN User opens dapp on network B
- THEN Network does not switch **_(Expected)_**
↓
- WHEN User initiates a dapp confirmation request on network B
- THEN Then confirmation request for network A disappears **_(Not Expected)_**

#### Current
First confirmation request disappears. _It looks like we don't switch network when toggling between dapps, but we do switch when a confirmation request comes in._

#### Expected
- Request waiting to be acknowledged persists
- New request is added to queue 
- Top bar appears on confirmation request screen, allowing to toggle between confirmation requests

**Comment by hesterbruikman** [comment] 2024-10-31 19:54
Needs confirmation of behavior since Send & Swap introduced.

**Comment by bschorchit** [comment] 2024-12-04 18:01
I think the current behavior is currently the best. It also matches behavior for other wallet initiated activity like swaps. I'm closing this for now. Let me know if you want to revisit it @hesterbruikman

**Closed by bschorchit** 2024-12-04 18:01 UTC
Labels: type-bug, Sev3-low, area-multichain, team-confirmations, release-12.0.0
