### ISSUE TITLE
uat: Gas editing screen should show max transaction cost

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2468] opened 2017-10-24 18:54 UTC
Even an advanced user is flying blind if they can't see what the current gas parameters mean in their local currency.

![screen shot 2017-10-24 at 11 50 49 am](https://user-images.githubusercontent.com/542863/31962301-112bbe88-b8b2-11e7-8e1a-a217fd2498fd.png)

**Comment by cjeria** [comment] 2017-10-25 21:08
@danfinlay the UI for this has been spec'd in design. Here's it is in the prototype.
https://invis.io/9UCTYJN3Z#/252407373_send_Screen  

![custom gas modal - advanced saved](https://user-images.githubusercontent.com/597770/32023318-ba24b3c4-b98d-11e7-87c6-b54428083e9e.png)

**Comment by danfinlay** [comment] 2017-10-25 21:51
I'll try to make the data source for that gas slider soon, maybe tomorrow.

**Comment by cjeria** [comment] 2017-10-28 17:08
Latest design
![custom-gas](https://user-images.githubusercontent.com/597770/32113538-73536c1a-baf5-11e7-8578-89c4b1a317db.gif)

**Comment by Boydbueno** [comment] 2018-01-04 10:15
Is there any way I can help getting this through faster?

**Comment by danfinlay** [comment] 2018-01-09 00:19
You could create a react component that accepts recent gas price data and returns a slider colored like this. That would be worthy of a bounty.

**Comment by danfinlay** [comment] 2018-01-09 00:20
That said, we are looking at other input designs, and may not ultimately settle on this slider form. We're doing more design thinking on gas inputs soon.

**Comment by danjm** [comment] 2018-02-26 20:08
Marking as a duplicate of other tickets meant to handle this functionality. In particular, https://github.com/MetaMask/metamask-extension/issues/3037

**Closed** 2018-02-26 20:08 UTC
Labels: NewUI/UAT, T4-needsdesign, duplicate
