### ISSUE TITLE
High CPU usage on chrome（Firefox is ok on my OS）

### ISSUE THREAD

**Issue by yangbinnnn** [MetaMask/metamask-extension#5224] opened 2018-09-10 01:40 UTC
**Describe the bug**
High CPU usage on chrome（Firefox is ok on my OS）

**To Reproduce**
1. Just open the Chrome

**Expected behavior**
Can be used normally

**Screenshots**

![screenshot at 2018-09-10 09 32 07](https://user-images.githubusercontent.com/16743911/45271980-18b3aa80-b4dd-11e8-8ef9-12466e3b7186.png)
![screenshot at 2018-09-10 09 45 32](https://user-images.githubusercontent.com/16743911/45272185-5238e580-b4de-11e8-8656-609e8abbebd0.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu mate 16.04
 - Browser: Chrome Version 69.0.3497.81 (Official Build) (64-bit)
 - MetaMask Version 4.9.3

**Update issue(Maybe is the real problem)**
MainNet is OK, But When I choose Koven Test Network, It show Ropsten Test Network and then High CPU UP Boom!!!
![screenshot at 2018-09-10 09 46 48](https://user-images.githubusercontent.com/16743911/45272225-93c99080-b4de-11e8-9c11-59e375fbfded.png)

**Comment by bdresser** [comment] 2018-09-10 18:04
Thanks for reporting @yangbinnnn. We currently have an open bug bounty on this exact issue (https://github.com/MetaMask/metamask-extension/issues/4074) 

If you're able to identify the root cause of the bug or help us patch it, we'd love your help!

Closing this issue as a duplicate

**Closed by bdresser** 2018-09-10 18:04 UTC
