### ISSUE TITLE
Transaction Failed: nonce too low

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3672] opened 2018-03-22 03:23 UTC
https://sentry.io/metamask/metamask/issues/476290909/events/16314996302/

seems like dapp specified nonce or at least we also concluded on the same bad nonce

```
Transaction Failed: nonce too low
```

**Comment by danfinlay** [comment] 2018-03-26 17:49
Closing as duplicate of #3670 for right now, but could re-open if persists.

**Closed by danfinlay** 2018-03-26 17:49 UTC
Labels: L12-nonceSelection, P1-asap, T00-bug
