### ISSUE TITLE
ETH transaction failed according to metamask (funds not showing) 

### ISSUE THREAD

**Issue by ksmet1977** [MetaMask/metamask-extension#2721] opened 2017-12-10 09:21 UTC
Using the metamask chrome browser extension encountered a failed transaction (0.2 ETH) yesterday when  buying or at least try to buy some eos tokens. The error message is shown below:

![screenhunter_38 dec 09 15 36](https://user-images.githubusercontent.com/10864095/33803523-cd67fb16-dd92-11e7-8e5b-d772b1f9124c.jpg)

However, when I look at transaction on etherscan it shows up as succesfull. 
![screenhunter_39 dec 10 10 15](https://user-images.githubusercontent.com/10864095/33803567-9e0cee7a-dd93-11e7-865e-49d594381601.jpg)

The next transaction (0.02 ETH) was succesfull according to metamask as well. When the transaction failed according to metamask, why doesn't my balance show up correctly? Where is the 0.2 ET that failed to transfer? How do  retrieve it or make sure the transaction shows up correctly?
Thanks.

**Comment by brandoncurtis** [comment] 2017-12-13 23:06
> Where is the 0.2 ET that failed to transfer? How do retrieve it or make sure the transaction shows up correctly?

Every time an Ethereum address sends a transaction, it has to set a value called the "nonce".  The Ethereum network will only accept (mine) transactions in nonce order (0, 1, 2, 3, ...) and nonces cannot be skipped or repeated.  If you do happen to send two transactions with the same nonce, the network will accept one of those transactions and reject the other one.  That looks like what happened here—MetaMaks is showing that you sent a transaction at nonce=0 with the transaction ID `0xd0a6E6...` (the hexadecimal number listed right below the the transaction details), but a _different_ transaction at nonce=0 was actually confirmed by the network (transaction ID `0x5eabd711... visible in the error message and in the TxHash in Etherscan).

Someone or something resent this transaction with a different Transaction ID (TxHash).  Did you try to send the same transaction twice from two different computers or using different Ethereum wallet software?  This is the easiest way to have something like this happen.

The good news is, once a transaction with a particular nonce has gone through, the network automatically discards all other transactions from that address with the same or lower nonces.  So, you can keep transacting from this address and carry on as normal without worrying about this old failed transaction.

Hopefully that answers your questions!

**Comment by danfinlay** [comment] 2017-12-18 19:50
We have been marking long-pending transactions as failed in the past, and we are going to change this soon (#2681).

It looks like you sent this transaction twice as a result of this. We're really sorry that happened. We shouldn't have marked this failed, but did because it was very unlikely that it got mined after this long. We're improving as a result, so that'll have to be the silver lining.

Closing in favor of #2681.

**Closed by danfinlay** 2017-12-18 19:50 UTC

**Comment by ctivanovich** [comment] 2018-01-02 08:34
I just had this happen: I attempted to deposit from metamask to etherdelta, and the funds just disappeared. In the MM log, it is listed as a failed transaction with this same error message about 'nonce', but there is no duplicate, successful transaction...the funds never got deposited to ED, and they haven't returned to MM. I did not do this on a phishing site, I used https://etherdelta.com/. Any idea what has happened? The transaction is not listed on ED either, no on etherscan.

**Comment by brandoncurtis** [comment] 2018-01-02 20:22
@ctivanovich if you received an error in MetaMask and the transaction isn't listed on Etherscan, the transaction failed and your funds were never sent.  You can check your balance in Etherscan or MyEtherWallet and try the transfer again.

**Comment by PAULINO100** [comment] 2018-02-11 14:18
Hello, I bought an ETHG ERC-20 Token at c-cex.com, I sent it to the MM, and it did not arrive, it's on the account, but it will not go to MM to verify: https: //etherscan.io/token/0x78cb641ed233beea4827b8b148e4bf0b17289eca? A = 0xbddb7b5e5997c7940f76d26d5c4622a95ab43440
