### ISSUE TITLE
eth_requestAccounts does not resolve when unlock popup is closed

### ISSUE THREAD

**Issue by tennox** [MetaMask/metamask-extension#11231] opened 2021-06-03 15:56 UTC
**Describe the bug**
When I call `window.ethereum.send('eth_requestAccounts')`, the returned promise does not resolve when i close the wallet unlock popup.

**Steps to reproduce (REQUIRED)**
1. Lock MetaMask
2. Call `window.ethereum.send('eth_requestAccounts')` on any page
3. Close Metamask popup - [See video](https://user-images.githubusercontent.com/2084639/120674581-84f84880-c494-11eb-9549-ff854090821b.mp4)
4. See that Promise does not resolve:
  ![Screenshot from 2021-06-03 17-53-45](https://user-images.githubusercontent.com/2084639/120674765-b8d36e00-c494-11eb-99cc-ef06712151c8.png)

**Expected behavior**
Promise should resolve with error

**Browser details (please complete the following information):**
 - OS: Pop!_OS 20.10
 - Browser: Brave Version 1.24.64 Chromium: 90.0.4430.72 (Official Build) beta (64-bit)
 - MetaMask Version: 9.5.7 (not the one included in Brave)

**Comment by danjm** [comment] 2021-11-10 11:11
Duplicate of https://github.com/MetaMask/metamask-extension/issues/11280

**Closed by danjm** 2021-11-10 11:11 UTC
Labels: type-bug
