### ISSUE TITLE
[Bug]: Metamask on Brave seems to Freeze on the signature prompt for some websites

### ISSUE THREAD

**Issue by GuardianLiarus** [MetaMask/metamask-extension#19932] opened 2023-07-08 14:32 UTC
### Describe the bug

When using Metamask on the brave browser, the extension seems to completely freeze up on this prompt:

![image](https://github.com/MetaMask/metamask-extension/assets/45693898/59bfadb1-e002-4730-92b2-825aa0c2405a)

Sometimes ignoring the prompt and clicking the extension icon shows the prompt, which you can accept but Metamask stops responding after.

Disabling all extensions other than Metamask doesn't fix the issue for me, and it seems to be specific to brave as i'm not having that issue with other browsers

### Steps to reproduce

1. Use the latest version of Brave browser
2. Try to use a function that requires a signature prompt, such as a sell on https://app.uniswap.org/ or a bridge on https://testnet.cashmere.exchange/swap

### Version

10.32.0

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by danjm** [comment] 2023-07-11 11:36
@GuardianLiarus Thanks for the report. We believe this was fixed in v10.33.1, which was released to chrome users yesterday, and so should be available on brave as well. After your metamask version is updated to v10.33.1, can you confirm whether or not the issue is fixed?

**Closed** 2023-07-11 16:04 UTC
Labels: type-bug
