### ISSUE TITLE
New version of metamask is super slow 

### ISSUE THREAD

**Issue by James-Sangalli** [MetaMask/metamask-extension#6017] opened 2019-01-13 22:25 UTC
I have reinstalled multiple times and each time it is so slow, this is in contrast to previous versions

Chrome version: 71.0.3578.98 (Official Build) (64-bit)

Metamask version: 5.3.0

<img width="472" alt="screen shot 2019-01-14 at 11 23 01 am" src="https://user-images.githubusercontent.com/16630514/51091381-fb764c00-17ee-11e9-93f5-f22298d91334.png">
<img width="467" alt="screen shot 2019-01-14 at 11 23 39 am" src="https://user-images.githubusercontent.com/16630514/51091382-fb764c00-17ee-11e9-92d4-743b1b42245c.png">

**Comment by danfinlay** [comment] 2019-01-14 19:47
One reason the new interface appears slower than the old one is that we've preserved the ability to switch back, ie the "new interface" includes both, so you're loading two interfaces.

When we remove the old UI, this process should speed up some.

Another way we plan to speed this up is to make confirmation windows not load the entire app, but to simply load the UI required for the confirmation itself (today even our confirmations contain all our react code).

**Comment by plrspro** [comment] 2019-01-14 23:10
> One reason the new interface appears slower than the old one is that we've preserved the ability to switch back, ie the "new interface" includes both, so you're loading two interfaces.

i have pretty similar situation, but i guess its not related to loading up 2 interfaces, cause my metamask taking 15+ seconds to launch and each button interaction delayed to 3-4 seconds, so its kinda hardly usable if i want to make alot of actions on it.

**Comment by James-Sangalli** [comment] 2019-01-15 21:50
@danfinlay ok but it takes a really long time, sometimes a couple minutes to load. Surely it shouldn't be that slow right?

**Comment by plrspro** [comment] 2019-01-16 02:08
https://plrs.pro/media/metamask-ui-issue.webm
so its lagging for first 20 seconds straight (10 seconds white screen + 10 seconds ui unresponsive) and then each time iam doing any interaction on websites, its same each new popup have same issues.

**Comment by BMillman19** [comment] 2019-01-19 17:39
I also experience this

**Comment by itamarro** [comment] 2019-01-23 00:59
I also experience this. When inspecting I see no errors, but I do see repetitive printouts like this:

[Violation] 'setTimeout' handler took 267ms
[Violation] 'setTimeout' handler took 354ms

...

**Comment by veox** [comment] 2019-01-23 01:33
Doing profiling, similar freeze-ups happen when some timer fires in `background.js`, and then `extensions::sendRequest::108` takes 2.42 seconds.

Monitoring network when inspecting `background.js`, I see an awful lot of `net_version` JSON-RPC queries (?..), and dense (on every block, I'd guess?..) re-sending of pending transactions, requesting those transactions by hash, and similar.

I'm not 100% sure, but I think it gets more pronounced the more transactions I have in history (known to MM), and especially the more pending transactions I've got.

It's possible that the stall happens due to the extension's process taking 100% of a CPU core (saturating it), which I also observe in Chromium's "Task Manager".

FTR, I use a local node (on the same machine).

**Comment by James-Sangalli** [comment] 2019-01-26 07:20
Sorry Gentlemen, I simply downgraded my version before checking the logs. Old version runs fast.

**Comment by bdresser** [comment] 2019-01-28 18:23
v5.4 is being rolled out today & tomorrow and includes a couple fixes to reduce the number of requests we're making to Infura (https://github.com/MetaMask/metamask-extension/pull/6052, https://github.com/MetaMask/metamask-extension/pull/6049) - once your extension updates, let us know if things improve.

**Comment by veox** [comment] 2019-02-07 21:09
@bdresser I saw no improvement with 5.3.2 (or current 5.3.5).

What did help was removing MetaMask altogether, re-installing, and restoring from seed.

I also didn't import an additional account that was present previously.

**Comment by araa47** [comment] 2019-02-15 10:36
Running MetaMask Version 6.0.1 on chrome on a mac. Having to wait about 20seconds + for it to load up. The older version was much faster. Any way to fix this issue?

**Comment by bdresser** [comment] 2019-02-15 18:08
@araa47 anything in your UI console or background console? 

UI console: open the extension, right click, choose "inspect"
background console: head to `chrome://extensions`, make sure Developer Mode is "on" in top-right, click `background.html` on the MetaMask tile.

**Comment by araa47** [comment] 2019-02-16 17:03
@bdresser  was able to solve the issue by backing up my accounts, un-installing the extension and re-installing. Looking good now, thanks for the prompt response.

**Comment by nedis4** [comment] 2019-03-06 08:46
I have the same issue. Why did they break it? Was such a good client.

**Comment by bdresser** [comment] 2019-03-13 21:58
@nedis4 can you provide any useful details outlined above? and let us know if any of the fixes on this thread work for you.

**Comment by D-Nice** [comment] 2019-04-02 22:03
the response is generally bad, couple of seconds delay.

However, it's especially exacerbated when using a custom rpc endpoint such as https://rpc.slock.it/goerli slowing down to a multiple minute crawl, making the client practically unusuable.

**Comment by msuess** [comment] 2019-04-12 10:27
To the people that have this problem: can you confirm that this slowness goes away when you run the profiler? In the popup, click "inspect", switch to "performance" and click the record button to start profiling. Is the UI more responsive when the profiler is running?

**Comment by D-Nice** [comment] 2019-04-18 15:30
Not sure if there were recent updates, but it's not as bad as it used to be.

It started off quite fast, but as you continue using it slows down, but the max latency is at least 10ish seconds from what I've seen so far.

Regarding the profiler, when starting the profiler, things seemed to go fast again, but likewise as use continued it slowed down.

I have reverted to an earlier major version to circumvent this issue.

**Comment by bdresser** [comment] 2019-04-18 18:12
thanks for the update @D-Nice. which earlier version do you find reduces the issue?

**Comment by dkent600** [comment] 2019-04-21 06:40
@msuess Running the profiler did immediately improve performance (which was super slow, using a lot of CPU)

**Comment by msuess** [comment] 2019-04-23 08:46
We're seeing the same issue with an extension we're developing at my company. We have yet to identify the root cause but we are seeing this behaviour with various OSX versions when the laptop is connected to an external *wide*screen.

@dkent600 @D-Nice  Do you mind sharing OS details and what kind of screen config you are running? If you're using external screens, does disconnecting them/changing resolution help? If so, what resolution are you running and what is your exact screen setup?

@bdresser It sounds super weird but but causing repaints did fix the issue for our users. Our "solution" was to insert a visible, 1x1px `canvas` element that we paint to using `requestAnimationFrame`.

This might be a Chromium bug but we're having a hard time to reproduce it.

**Comment by dkent600** [comment] 2019-04-23 22:19
@msuess  

> Do you mind sharing OS details and what kind of screen config you are running? If you're using external screens, does disconnecting them/changing resolution help? If so, what resolution are you running and what is your exact screen setup?

Windows 10, 15" laptop screen, 4K resolution, landscape, 250% text scaling, no external monitor.
I didn't try changing the graphics resolution.

**Comment by D-Nice** [comment] 2019-05-09 20:49
@bdresser MetaMask 4.17.1

I haven't used any new version much recently, so can't judge improvements currently.

**Comment by D-Nice** [comment] 2019-05-31 15:27
Update on this, I have used 6.x updated version recently, albeit sparingly when compared to before, but I have not noticed any slow downs during its use now on Chrome-based browser.

**Comment by bdresser** [comment] 2019-06-05 23:55
Nice! Will leave this open for another month or so, and if we don't hear any more complaints I will close.

**Comment by jkr1986** [comment] 2019-08-18 17:55
Still very laggy if you have alot of transactions...

**Comment by wbt** [comment] 2019-10-25 18:43
Still having a lot of issues, as logged in #6813.

**Comment by marknl** [comment] 2019-10-30 15:14
I'm affected by a slow MM as well. I'm running on Win10 Home / Chrome 73 / MM 7.3.1
Everything the extension does is slow. Because of it, dApps cannot connect to it.

**Comment by danfinlay** [comment] 2019-10-30 18:34
It is possible that this is related to transaction storage, as someone has mentioned. Could someone affected by this issue try the [reset account](https://metamask.zendesk.com/hc/en-us/articles/360015488891-Resetting-an-Account) button and tell us if that improves performance for them?

**Comment by marknl** [comment] 2019-10-30 19:59
Thing is, in Brave browser, the extension is working perfectly fine. It's only in Chrome where it's not working properly. What does "reset account" do? Will I loose my account?

**Comment by wbt** [comment] 2019-11-08 19:52
@danfinlay Without knowing for sure if I'm affected by this issue or a separate one, I did an account reset, refreshed the dapp page, and still observed #6183.

**Comment by hegedis-andor** [comment] 2021-01-13 08:32
> One reason the new interface appears slower than the old one is that we've preserved the ability to switch back, ie the "new interface" includes both, so you're loading two interfaces.
> 
> When we remove the old UI, this process should speed up some.
> 
> Another way we plan to speed this up is to make confirmation windows not load the entire app, but to simply load the UI required for the confirmation itself (today even our confirmations contain all our react code).

Has the loading the old ui been excluded? It is pretty slow for me ~3 secs to load the ui of metamask.

**Comment by tmashuang** [comment] 2021-03-16 18:25
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/6547 and https://github.com/MetaMask/metamask-extension/issues/8991. Some of OP's is no longer relevant and new information was provided in those linked issues and can help further debug the root cause.

**Closed by tmashuang** 2021-03-16 18:25 UTC
Labels: N02-needsReproduction, N03-needsInformation, S2-normal, T00-bug, degraded performance, needs-triage
