### ISSUE TITLE
Unable to connect Metamask to Colony.io

### ISSUE THREAD

**Issue by JMed0115** [MetaMask/metamask-extension#8987] opened 2020-07-14 20:15 UTC
When trying to connect to my Colony in Colony.io I get the error: "The MetaMask extension is not available."  I have not had this happen before, but  I am now using a new version of Metamask, Version 8.0.4

This is using the Chrome extension.

**Comment by tmashuang** [comment] 2020-07-14 20:25
They are probably doing some additional checking on their end of the connection. Without a code snippet of their implementation there really isn't much we can investigate further than "The MetaMask extension is not available." and that it just doesn't work.  Probably should contact Colony and let them know that their connect flow is broken, and/or have them open a new issue with their implementation to see if there is an issue on our end. Closing due to lack on information and reproduction in the form of code examples.

**Closed by tmashuang** 2020-07-14 20:25 UTC

**Comment by rekmarks** [comment] 2020-07-15 01:37
@JMed0115, thank you for bringing this to our attention. We are working with Colony, and this should hopefully be resolved soon. I recommend reaching out to Colony with further inquiries about this problem, as they are most likely to be implementing the fix.
