### ISSUE TITLE
Sending private-net ETH: ETH Amount differs from user entry by factor of ≈ USD price of mainnet ETH

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#9929] opened 2020-11-21 02:57 UTC
**Describe the bug**
When using MetaMask to send ETH, the amount shown in confirmation and actually sent differs from what the user entered by a factor of 472.89.

Example: 
![image](https://user-images.githubusercontent.com/563406/99865145-cae36400-2b75-11eb-8fc4-0543aca2b65f.png)

If I click Next, 
![image](https://user-images.githubusercontent.com/563406/99865168-e3537e80-2b75-11eb-9c87-35662bdaa6f1.png)

If I click Confirm,
![image](https://user-images.githubusercontent.com/563406/99865181-f7977b80-2b75-11eb-9d9d-9b3f547e49eb.png)
and then 
![image](https://user-images.githubusercontent.com/563406/99865190-02eaa700-2b76-11eb-94f7-d68fed22c734.png)
Clicking on it produces details showing the amount sent in the summary and the amount the user entered in the Activity Log:
![image](https://user-images.githubusercontent.com/563406/99865443-b1431c00-2b77-11eb-9173-79c18a9ccb2f.png)
Also notice the "Gas Price (GWEI)" is expressed as a large number of dollars, rather than in GWEI. 
When I then look at the receiving account, which had no prior transactions, I see that the higher amount was actually sent:
![image](https://user-images.githubusercontent.com/563406/99865238-4e04ba00-2b76-11eb-8171-f942b3624462.png)

-------------------

Here's another demo, passing on what should be 1 ETH from that account to another:
![image](https://user-images.githubusercontent.com/563406/99865333-e4d17680-2b76-11eb-96bf-1f01f92152de.png)
Clicking Next:
![image](https://user-images.githubusercontent.com/563406/99865352-fa46a080-2b76-11eb-97bd-7b4988e1b8a4.png)
Clicking Confirm: 
![image](https://user-images.githubusercontent.com/563406/99865362-10ecf780-2b77-11eb-92e3-5489a6d263d4.png)
and after the transaction is mined: 
![image](https://user-images.githubusercontent.com/563406/99865371-219d6d80-2b77-11eb-96fa-26541569377d.png)
Clicking on it produces details showing the amount sent in the summary and the amount the user entered in the Activity Log:
![image](https://user-images.githubusercontent.com/563406/99865424-85279b00-2b77-11eb-908b-384c94aeede9.png)
Also notice the "Gas Price (GWEI)" is expressed as a large number of dollars, rather than in GWEI. 

Note that if the scaled-up amount plus gas fees exceed the account balance, you will be unable to send.  This is what first tipped me off to the bug, when I was unable to send an amount <1/4% the balance of an account, with an insufficient funds error.
![image](https://user-images.githubusercontent.com/563406/99865575-beacd600-2b78-11eb-9c29-84ab4236f6f9.png)

Testing across several orders of magnitude, the actual amount appears to scale perfectly linearly with the amount entered by the user, but I don't know where that particular multiplier comes from. 

**Steps to reproduce (REQUIRED)**
1. Set up a network running on localhost, with some account that has a high balance as well as an additional empty account.
2. Connect to that network in MetaMask, and select the account.
3. Click "Send." 
4. As a recipient, click "Transfer between my accounts."
5. Select another account as the recipient.
6. Enter an amount you wish to send. Note that if (the amount * 472.89) + (the gas price * the gas limit) exceeds the sending account balance, you will get an insufficient funds error.
7. Click "Next." 
8. Notice that the amount the user is asked to approve is a transfer amount of 472.89x what they entered, plus the gas fee.
9. Notice that the transaction is presented in the past tense: "SENT ETHER" as if it's already completed, prior to user confirmation.
10. You don't need to actually confirm the transaction to see this bug in action.  However, if you do, you will see that the higher amount is both sent and received.
11. If you do complete the transaction, you will see "Send Ether" in the transaction history, showing the higher amount actually sent.
12. If you click on the details, you will again see "Send Ether" as the title, and the higher amount, plus a value labeled GWEI and listed in dollars, as well as an Activity Log showing the amount you entered.

**Expected behavior**
1. The amount of ETH to be sent, as entered by the user on the Send ETH screen, exactly matches what is shown on the confirmation screen and what is sent, and what is shown as having been sent.
1. The gas price suggested is not drawn from mainnet ETH Gas Station or similar when not on mainnet.
1. Prior to confirmation, the transaction is labeled "Send ETH" and after confirmation it's "Sent ETH," rather than the other way around.
1. In the transaction details, the value next to "Gas Price (GWEI)" is a gas price in GWEI, matching what the user entered (or left as it was filled in by default based on mainnet statistics), not a large number of dollars.
1. The value of the transaction shown in the Activity Log in the transaction details view matches the amount actually being sent.

There might be several different issues here, but the combination is very concerning about the trustworthiness of MetaMask as a wallet.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: Not in use here
 - Browser: Chrome 86.0.4240.183 (Official Build) (64-bit)
 - MetaMask Version: 8.1.3

**Comment by tmashuang** [comment] 2020-11-21 03:00
> Set up a network running on localhost,
Can you expand on this?

**Comment by wbt** [comment] 2020-11-21 04:40
Downloading & running Ganache might work; I used geth with the puppeth tool.  There might be some tutorials out there for geth.

I found in one case that resetting the account a few times caused the multiplier to rise to 512.27.  After removing and re-adding a network which was different than the one used in testing for this Issue, the multipiler for that network (which had been at 472.89 and then 512.27) fell to 1.  I don't know why.

**Comment by tmashuang** [comment] 2020-11-21 04:41
How are you adding the network?

**Comment by wbt** [comment] 2020-11-21 15:25
I'm adding the networks by going to custom RPC and entering the URL (beginning with http...) with port number and chainID.  This happened across multiple independent chains with different RPC endpoints and chainIds.  The chainId is not one of the preprogrammed ids assigned to mainnnet (1) or a known testnet.
On reflection, I think the multiplier being applied may be the then-current ETH price in USD according to some exchange which Metamask might be using to source conversions.  MetaMask probably updated its sense of the price during the time when I was trying various resets.  
You may notice in the screenshots it's saying "No conversion rate available" because it's private-net ETH with no market value and no way for Metamask to get a price signal on that valueless ETH.  Maybe in that case it's incorrectly applying conversions where it shouldn't?

**Comment by tmashuang** [comment] 2020-11-21 19:38
Can you set the `Currency Symbol` to `ETH`?

**Comment by wbt** [comment] 2020-11-23 16:20
The symbol was already set to ETH. (ETH is fine, it's only used for a gas fee anyway).  If I get back to seeing transactions with a multiplier >>1, I'll try setting the currency symbol to something else and see if that changes things. 
I did just observe this on another user's machine, who typically sticks to one private network (the same one where I first observed this) plus mainnet, and one account, generally without doing resets or using advanced features.  I didn't catch the exact multiplier, but it seemed to be in the 600x range.  That would be consistent with the current USD price of ETH (*dev continues kicking self for not hodling more*).

**Comment by wbt** [comment] 2020-11-23 22:23
Today I saw this again on one of the networks where I'd originally observed it.  From the same sending account as above, I entered a transaction to send 10 ETH to a new account, and that got translated as 5971.4 ETH (a factor of 597.14, at a time when Coindesk reported the ETH price as 595.73 USD).  Several minutes later after the ETH price had gone up a bit, I drafted a transaction and saw the multiplier had changed to 597.14; I rejected that transaction.  I then went to Settings -> Networks and modified the network setting to use TST as the symbol (short for test). 
That same account in the screenshots above looked like this, with the complete account history shown: 
![image](https://user-images.githubusercontent.com/563406/100020231-79251e80-2dad-11eb-8722-c70c473c2872.png)
When clicking on details for the same 1 ETH transaction in the screenshot above, I got this: 
![image](https://user-images.githubusercontent.com/563406/100020426-d3be7a80-2dad-11eb-8fcb-325012f97dfa.png)
I then went to initiate a new transaction to send another 1 ETH/TST to the same address as the prior single-ETH test: 
![image](https://user-images.githubusercontent.com/563406/100020658-2d26a980-2dae-11eb-9db0-d69c30694aea.png)
Notice that the Asset box says "ETH" in big letters but "TST" after the numeric balance.  **In general I would expect those to match even when the network symbol isn't ETH**. 
Then I click Next and see this:
![image](https://user-images.githubusercontent.com/563406/100020966-b4741d00-2dae-11eb-89e2-fc4d5da7d4d5.png)
Again, at the top is "Sent Ether" with Sent in the past tense and Ether instead of TST. There's no longer an ETH logo in front of the number, as on the prior page and in screenshots above. 
I clicked Confirm and the transaction confirms, showing a new History entry with "Send ETH" and "-1 TST" (again tense and symbol issue on "Send ETH"). The recipient balance shows as exactly 2 TST. 
So far that looks much better. 
I then changed the symbol to ETH. In drafting transactions I was still at a multiplier of 1. 
I then cleared out the symbol field in network settings for that network, and in drafting transactions, had a multiplier of 597.14 again, with the balance of the same account at 52546.6396 ETH.  
I changed the symbol back to ETH and the balance reverted to 87.9972 ETH, and draft transactions had a multiplier of 1. 
Back to a blank network symbol, and the high multiplier returned.
Back to ETH as network symbol, and I was back at the expected balance with a multiplier of 1. 

My working hypothesis is now that this issue occurs only when the network Symbol, marked "(optional)", is blank. 
Since "optional" appears to be inaccurate, I would at least replace that with 'e.g. "ETH"' to show an example of the expected value, and definitely improve the handling when that is blank.  MetaMask has some multiplication going on where it shouldn't!

**Comment by tmashuang** [comment] 2020-12-04 14:02
Closing as a duplicate of #9492.

**Closed by tmashuang** 2020-12-04 14:02 UTC

**Comment by tmashuang** [comment] 2020-12-04 14:08
Also related to #9701

**Comment by wbt** [comment] 2020-12-04 21:33
FWIW, I don't really agree with the closure, as I think this issue calls out a few details missed in the other such as the "Gas Price (GWEI)" being expressed as a large number of dollars, "Send Ether" vs. "Sent Ether" messaging, and a fair amount of detail provided here.
The gas price source issue (#2 in Expected Behavior) has been broken off as #10003.
