### ISSUE TITLE
[Bug]: After swapping tokens don't show up in the wallet

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#23612] opened 2024-03-20 16:56 UTC
### Describe the bug

After swapping I should end up with the swapped token in the wallet but it's not showing up. I am seeing this not only on mainnet but also other popular networks and hw wallets. See videos below. 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/6082863/86d7fce8-4f7e-4200-abf2-eeaaed41698d

https://github.com/MetaMask/metamask-extension/assets/6082863/7658d854-3310-4c59-8018-c13e812373de

https://github.com/MetaMask/metamask-extension/assets/6082863/f4b544b2-c649-40ee-8924-bdd9e6cb58d4

https://github.com/MetaMask/metamask-extension/assets/6082863/725d4fde-9356-43b2-92ac-83b41b0b07e3

### Steps to reproduce

1. Swap a token
2. Wait for completion
3. Check the token is in the wallet

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment] 2024-03-21 21:16
Might be related: when we initially start the wallet the prompt to import the existing tokens for current account is not displayed.

**Comment by bergeron** [comment] 2024-03-21 23:29
I'm working on a detection bug introduced by https://github.com/MetaMask/metamask-extension/pull/22928 that _may_ be the cause / related to this.  But haven't tested swaps specifically.  Assigning to myself.

**Comment by davibroc** [comment] 2024-03-27 13:22
@bergeron this has to be fixed before 11.14 goes out.

**Comment by sleepytanya** [comment] 2024-03-29 01:16
NFTs displayed as expected, but ERC20 tokens are not detected when token auto-detection is on, tokens also are not displayed after importing them manually:


https://github.com/MetaMask/metamask-extension/assets/104780023/9a596751-6371-4821-8e54-3e37c48b91f1

**Comment by bergeron** [comment] 2024-04-09 18:08
Should be fixed by https://github.com/MetaMask/metamask-extension/pull/23798 and cherry picked to 11.14 in https://github.com/MetaMask/metamask-extension/pull/23871

**Closed** 2024-04-12 16:43 UTC
Labels: type-bug, Sev1-high, release-blocker, regression-RC, team-assets, release-11.14.0

**Comment by benjisclowder** [comment] 2024-06-14 11:14
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
 
 We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
 
1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

cc: @bergeron

**Comment by benjisclowder** [comment] 2024-08-12 14:54
> **Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
> 
> We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
> 
> 1. What PR fixed the issue?
> 2. Can you pinpoint the commit from which the issue originated?
> 3. Write a short explanation of the technical cause of the bug
> 4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
>    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
>    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
>    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
> 
> Please provide your answers as a reply to this comment and tag me as well.
> 
> You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!
> 
> Tagging eng. who added the fix: [@bergeron](https://github.com/bergeron)

Hi, @bergeron , if you're not able to conduct RCA on this issue, is there anyone you can assign this to? I would very much appreciate it. Thank you!
