### ISSUE TITLE
Ether input on send screen should support full 18 digits of precision

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#12700] opened 2021-11-14 16:31 UTC
Continuing from: https://github.com/MetaMask/metamask-extension/pull/12437

Rotki is one example of a site that asks users to paste in a precise value and is losing money because of this behavior.

**Comment by AustinFoss** [comment] 2024-03-26 13:35
Saw this after Lefteris posted over on X.

Per the above mentioned #12437, which changed 2 files (`ui/hooks/useUserPreferencedCurrency.js`, & `ui/components/ui/currency-input/currency-input.component.js`), I thought I'd get the ball rolling on identifying a list of places that need to be updated to get the full 18 digits working.

The `ui/components/ui/currency-input/currency-input.component.js` is now found at `ui/components/app/currency-input/currency-input.js` on the current develop branch.

List of potential changes:
- [`useUserPreferencedCurrency.js`](https://github.com/MetaMask/metamask-extension/blob/f3b83259a6a8d04c07114d75ca38969662310d2e/ui/hooks/useUserPreferencedCurrency.js#L58)
- [`currency-input.js`](https://github.com/MetaMask/metamask-extension/blob/f3b83259a6a8d04c07114d75ca38969662310d2e/ui/components/app/currency-input/currency-input.js#L159)
    - Originally made edits to two functions, `renderConversionComponent()` still exists but `getValueFromWeiHex()` does not

I've also identified two other potential files that may need attention, possibly more, before implementing this fix for 18 decimals.

- [`send.js`](https://github.com/AustinFoss/metamask-extension/blob/f3b83259a6a8d04c07114d75ca38969662310d2e/ui/ducks/send/send.js#L2029)
- [`confirm-transaction.js`](https://github.com/AustinFoss/metamask-extension/blob/f3b83259a6a8d04c07114d75ca38969662310d2e/ui/selectors/confirm-transaction.js#L284)

I'm not super familiar with the src of MM and how the flow of how a transaction gets executed, there could be several more spots where values need to be adjusted, but I hope this serves as a starting point and bumps this higher on the open issues list for others to find instead of stumbling on it through X.

**Comment by bschorchit** [comment] 2024-03-26 23:27
I've tested this just now and noticed my transaction was submitted with 16 decimals instead of 18. Is that what you're seeing too, @AustinFoss?

**Comment by hesterbruikman** [comment] 2024-04-08 14:28
@bschorchit can you share steps to reproduce please? I haven't been able to. Here's what I tried on 11.13.1 and an updated feature branch:
- Sent transaction with 18 decimals
- Sent transaction with 16 decimals
In both cases I check etherscan and the amount corresponds the number of decimals I used.

**Comment by hesterbruikman** [comment] 2024-04-11 10:38
@sleepytanya can you please take a look to see if you can reproduce this issue on the swap and send flow branch?

**Comment by sleepytanya** [comment] 2024-04-11 17:43
@hesterbruikman 
Tested on latest [send+swap build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN) and can't reproduce it, Etherscan shows correct number of decimals.
 16 decimals - https://etherscan.io/tx/0x673aa71a1792242d6a078bf237b70662e20229b594d10893a71583b459c62744
 18 decimals - https://etherscan.io/tx/0x24c5aec1348a7792921ba0db3a5844280d96e64763578c7a571a36f34bd1297a

**Comment by hesterbruikman** [comment] 2024-05-15 21:47
Thank you @sleepytanya ! Closing this as a fix is in develop.

**Closed by hesterbruikman** 2024-05-15 21:47 UTC
Labels: type-enhancement, area-send, team-wallet-ux
