### ISSUE TITLE
Import ETH keystore

### ISSUE THREAD

**Issue by kewpiedoll** [MetaMask/metamask-extension#10893] opened 2021-04-15 23:06 UTC
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Click on Metamask icon in browser
2. Click the Accounts circle
2. Click 'Import Account'
3. Select Type 'JSON File'
4. Dialog box to choose file appears, and simultaneously:
5. Metamask closes (disappears from the screen). File never uploads to metamask.

**Expected behavior**
Load the JSON file into Metamask

**Browser details (please complete the following information):**
 - OS: MacOS and Kubuntu 20.04
 - Hardware Wallet: none
 - Browser: Firefox Browser 87.0 (64-bit)]
 - MetaMask Version: 9.3.0

**Comment by tmashuang** [comment] 2021-04-15 23:09
Duplicate of https://github.com/MetaMask/metamask-extension/issues/1136 and there's a workaround in the expanded view. Contact your OS to fix the issue.

**Closed by tmashuang** 2021-04-15 23:09 UTC

**Comment by kewpiedoll** [comment] 2021-04-15 23:18
How do I enable the expanded view?

**Comment by tmashuang** [comment] 2021-04-15 23:19
Click the 3 vertical dots button on the home screen and click Expanded view in the dropdown menu.

**Comment by kewpiedoll** [comment] 2021-04-15 23:31
OK thanks. It said it's "not V3 wallet." It worked in myetherwallet though. Oh well. No ETC for me....
