### ISSUE TITLE
web3_sha3() not supported

### ISSUE THREAD

**Issue by montyanderson** [MetaMask/metamask-extension#4317] opened 2018-05-20 20:15 UTC
If I send the RPC input:

``` json
{ "method": "web3_sha3", "params": [ "hello, world!" ]  }
```

I get in response:

``` json
{ "error": { "code": -32603 } }
```

Is the `web3_sha3` method just not implemented? Thanks.

**Comment by jennypollack** [comment] 2020-04-14 16:53
duplicate of #4698

**Closed by jennypollack** 2020-04-14 16:53 UTC
Labels: T06-devQuestion
