### ISSUE TITLE
Full CPU utilization as of early December

### ISSUE THREAD

**Issue by fordacious** [MetaMask/metamask-extension#10109] opened 2020-12-18 22:28 UTC
**Describe the bug**
Metamask idle's at max CPU utilization making it effectively unusable.

**Steps to reproduce (REQUIRED)**
Have Metamask unlocked.

**Expected behavior**
Metamask does not idle at max CPU utilization.

**Browser details (please complete the following information):**
 - OS: Linux
 - Hardware Wallet: No
 - Browser: Firefox 
 - MetaMask Version: 8.1.9

**Additional context (Error Messages, etc.)**
Occasionally, Firefox gives the option to kill the "web page" that is causing the issue. This seems to fix the CPU utilization and allow Metamask to function once more, however it soon returns.

**Comment by Gudahtt** [comment] 2020-12-19 05:35
Thanks for the report! This might be related to the situation detailed in this comment: https://github.com/MetaMask/metamask-extension/issues/10097#issuecomment-748370537

**Comment by fordacious** [comment] 2020-12-21 10:42
Quite possibly. I tried the fixes from that thread but none were successful in solving the issue and many dapps remain unusable.

**Comment by tmashuang** [comment] 2021-03-16 18:25
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/6547 and https://github.com/MetaMask/metamask-extension/issues/8991. New information is being provided in those linked issues and can help further debug the root cause.

**Closed by tmashuang** 2021-03-16 18:25 UTC
Labels: N02-needsReproduction, T00-bug, degraded performance
