### ISSUE TITLE
Token vanishing from display after reloading Metamask

### ISSUE THREAD

**Issue by Desposyniunchained** [MetaMask/metamask-extension#5028] opened 2018-08-10 06:41 UTC
Two days ago I added all token from my account to the metamask "dashboard". After reloading Metamask today only four tokens are visible any longer, the rest is not displayed any longer. 

 OS: WIN10
 Browser: Chrome Version 67.0.3396.99 (Offizieller Build) (64-Bit)
 MetaMask Version 4.9.2

**Comment by estebanmino** [comment] 2018-08-10 14:50
Hi @Desposyniunchained, since #4884 now MetaMask has the ability to maintain tokens per network and account, so you should see all those tokens on main net and none on other networks. 
If you want to add tokens again you have to remember, that token is going to be added to your current network and your current account, so if you change either network or account that new token is going to disappear.
Feel free to ping me if you have more comments about this.

**Comment by Desposyniunchained** [comment] 2018-08-10 15:33
Maybe I did not describe correctly. I will try again. After the new update, I added all the token I have in my account and all of them where visible. Two days later after logging into the MetaMask account again, all tokens which were shown before disappeared again and now only four are left. They do not show up. I have to add them by hand again. I guess that's not supposed to happen. Thank you.

**Comment by estebanmino** [comment] 2018-08-10 15:46
I see, thanks for describing this, I'll see what could have happened. Just to confirm, do you have any issue now that you added those tokens manually?

**Comment by Desposyniunchained** [comment] 2018-08-10 16:58
I did not add any token again.

**Comment by yvesholenstein** [comment] 2018-08-10 18:08
I have exactly the same issue as well. Also using Chrome browser (Version 68.0.3440.106), but on Windows 7 Ultimate. Whenever I have to re-login to MetaMask, only 1 token is shown. The others have to be added manually.

I only have 5 tokens, so I can live with the bug. But it's tedious and I cannot imagine that this is by design.

**Comment by estebanmino** [comment] 2018-08-10 19:43
@yvesholenstein @Desposyniunchained  I'm trying to reproduce this and I can't get the same behavior than you. I started with version 4.8 earlier this week and now I have the updated 4.9.2 on Chrome. But this shouldn't be happening.
One thing that may fix this is restoring your account from the seed phrase. Is this something that you can do?

**Comment by tmashuang** [comment] 2020-11-05 20:09
Closing this. There could have been issues with how to we imported the token contract addresses. If anyone else finds themselves here, feel free to open a new issue with the token in question.

**Closed by tmashuang** 2020-11-05 20:09 UTC
Labels: N02-needsReproduction, T00-bug
