### ISSUE TITLE
Improve experience of popup in full screen mode

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#634] opened 2016-09-09 17:51 UTC
The new metamask popup is not really great when you’re in chrome in mode full window.

(it’s pops as new full window)

**Comment by Zanibas** [comment] 2016-09-09 21:37
Fullscreen Chrome on Ubuntu is already a nightmare, so count me out on testing this :(

**Comment by Zanibas** [comment] 2016-09-09 21:44
Tried it out though, couldn't reproduce the results.

![screenshot from 2016-09-09 14 43 10](https://cloud.githubusercontent.com/assets/1840057/18403803/d190e108-769b-11e6-98db-a76783789bfd.png)

**Comment by flyswatter** [comment] 2016-09-09 21:53
I reproduced on Mac, it's ugly.

- Dan

**Comment by frankiebee** [comment] 2016-10-25 19:34
notification popups go into full screen mode and consume the entire screen.

**Comment by mehtamanan** [comment] 2017-10-09 21:47
Any updates on this issue yet?

**Comment by danfinlay** [comment] 2017-10-09 22:07
Yes, we have a dramatically updated UI coming soon.

**Comment by tmashuang** [comment] 2018-02-27 00:31
Closing, fixed-in-master.

**Closed by tmashuang** 2018-02-27 00:31 UTC
Labels: L3-ui, T0-bug

**Comment by AntonioJuliano** [comment] 2020-08-06 16:24
This is an even bigger problem now. When I have chrome in fullscreen on macOS Catalina 10.15.5 a metamask pop up first pulls me into my Desktop screen from my fullscreen Chrome page, then once I navigate back to the fullscreen Chrome page, the metamask popup overlays the entire Chrome screen

**Comment by prastut** [comment] 2020-08-13 09:30
+1 to @AntonioJuliano 's comment.

**Comment by xastor** [comment] 2021-09-24 08:12
+1 to @AntonioJuliano this has been bugging me forever it seems...

**Comment by mehtaculous** [comment] 2022-12-27 07:05
Any update on this? Still having this issue on MacOS using a chrome browser in full screen mode. 

When I have to submit subsequent txs, MetaMask will open a new window for the first tx but then brings me back to the original site and pops up in the corner of the page for the second tx.

Ultimately, when I am in full screen mode, I would like for MetaMask to NOT open a new window and simply stay on the same page I am on when signing or submitting a tx.

**Comment by Banochkin** [comment] 2024-03-06 09:09
lol, still waiting

**Comment by rdgoarruda** [comment] 2024-08-15 06:01
me too
