### ISSUE TITLE
public uint decimals = 0; not being read by MetaMask when using Add Token

### ISSUE THREAD

**Issue by mattlockyer** [MetaMask/metamask-extension#1911] opened 2017-08-14 21:29 UTC
In your Token contract (Solidity) if you use:

`uint public decimals = 0; `

Tokens are not represented as whole numbers. In fact adding a balance of 1 will result in 0.1 showing up on the UI.

**Comment by Zanibas** [comment] 2017-08-16 18:10
Closing as duplicate of #1912

**Closed by Zanibas** 2017-08-16 18:10 UTC
