### ISSUE TITLE
Provide a way to override nonce with metamask

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#2739] opened 2017-12-13 05:28 UTC
It's annoying if tx failed, I can't use an account cause I can't override nonce.
I'm always getting:
```
2017-12-13 13:27:35  Error importing transaction: Transaction(AlreadyImported)
```
from parity, cause metamask keeps sending it and it can't be processed. Please allow a way to hardcode nonce for failed txs.

**Comment by danfinlay** [comment] 2017-12-15 07:11
Noted, eventually we'll need to expose this as an advanced feature. Closing as duplicate of #1410.

**Closed by danfinlay** 2017-12-15 07:11 UTC
