### ISSUE TITLE
Metamask still does not have a consistent way of switching networks. 

### ISSUE THREAD

**Issue by jordanlesich** [MetaMask/metamask-extension#10597] opened 2021-03-05 16:11 UTC
"wallet_addEthereumChain" was touted as a way to send requests to the wallet to switch networks. 

https://github.com/MetaMask/metamask-extension/issues/5101

 While this does work for non-default chains, MM deliberately throws errors for default chains. This makes it difficult to build a consistent UX around this feature for multi platform apps. 

If there was a way to request a network switch, I could detect whether the network to be switched is default or not and send a corresponding request. But that isn't possible under the current build.  

Most experienced users will already know to switch themselves, but this is not the case for new users who might need guidance. Having this arbitrary mismatch of functionality makes having a comprehensive, consistent mechanism for switching networks impossible.

**Comment by brad-decker** [comment] 2021-03-05 16:20
@jordanlesich you might be interested in ethereum/EIPs#3326. While it did take us a long time to go from EIP -> implementation for `wallet_addEthereumChain` we will likely be able to more rapidly release the implementation for this one, because of the existing UI for switching to custom networks. We'll need to do some thinking around security and presenting the appropriate options in the case of multiple networks with the same chainId.

**Comment by jordanlesich** [comment] 2021-03-05 16:32
I appreciate the information and fast reply. I'll stay subscribed to both threads. Thanks!

**Comment by rhlsthrm** [comment] 2021-03-11 15:39
This feature is definitely more and more necessary in a cross-chain/L2 world! Connext is eagerly waiting for this to improve user experience.

**Comment by pizzarob** [comment] 2021-03-24 02:10
[Cargo](https://cargo.build) is also looking forward to this feature. We will be adding support for multiple chains and while we can easily change the chain to something like xDai using `wallet_addEthereumChain` we cannot easily change it back to Ethereum for the user.

**Comment by adshodgson** [comment] 2021-04-12 10:02
Hi all, is the consensus that **wallet_addEthereumChain** will not work with networks that are already default e.g Mainnet, Rinkeby etc?

(I could get wallet_addEthereumChain working fine with BSC network, so I guess this would make sense if the problem is only with default chains.)

**Comment by matthewlilley** [comment] 2021-04-16 15:30
Yeah, this is an issue for us too. We have a network switch component but currently cannot switch to the native network.

**Comment by spudgy** [comment] 2021-05-21 16:32
Same issue here :(

**Comment by derivativedegen** [comment] 2021-05-27 05:31
same issue! Switching to Matic is smooth and easy. But trying to switch back to ETH mainnet doesnt work at all. I've even tried this on sushiswap and it seems they can switch the wallet to any network but cannot switch it back to ETH. 

hopefully this is resolved soon!

**Comment by sebenns** [comment] 2021-05-27 13:04
My current workaround - which I'm sure everyone here uses - is to catch the error at the moment and ask the user to manually switch on default MM chains. For other networks it is no problem to both add and switch them.
Looking forward to it, I'll stay subscribed to both threads ✌️

**Comment by aureliusbtc** [comment] 2021-05-28 06:33
Following up on this as well as it's an issue for [Nerve](https://twitter.com/NerveFinance) similar to other people above. The sooner switching to ETH (and default chains) is implemented, the better the experience it'd provide to end users.

**Comment by Umar-Abbas** [comment] 2021-05-31 00:48
Any updates on this?

**Comment by mzolkiewski** [comment] 2021-06-07 16:14
We'd love to be able to switch to default networks with custom URL. We're working on a tool called [Automate](https://blog.chronologic.network/automate-speed-up-your-work-with-automated-transactions-745ddb00d37f) which provides extra features via custom RPC and not being able to switch to mainnet programatically really hurts the user experience.

**Comment by helderjnpinto** [comment] 2021-06-07 17:56
hey when wallet_switchEthereumChain is available?

**Comment by froggiedev** [comment] 2021-06-08 03:48
we also need `wallet_switchToEthereumChain()`.

**Comment by brad-decker** [comment] 2021-06-16 18:16
This has landed in 9.6.0 🎉

**Closed by brad-decker** 2021-06-16 18:16 UTC
Labels: T08-featureRequest, area-provider, type-enhancement

**Comment by froggiedev** [comment] 2021-06-18 00:11
Okay, now how to switch to Testnets like Rinkeby?

**Comment by derivativedegen** [comment] 2021-06-19 21:04
Is there any documentation or examples to utilize the new functionality to switch to default chains? 

TIA

**Comment by snwokenk** [comment] 2021-06-24 03:53
[https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain](url)

**Comment by Yhozen** [comment] 2021-06-24 19:44
@snwokenk thank you!

PD: the hyperlink is pointing to metamask's issues, I almost thought I got [rick-rolled](https://www.youtube.com/watch?v=dQw4w9WgXcQ) 😂

**Comment by snwokenk** [comment] 2021-06-24 21:33
> @snwokenk thank you!
> 
> PD: the hyperlink is pointing to metamask's issues, I almost thought I got [rick-rolled](https://www.youtube.com/watch?v=dQw4w9WgXcQ) 😂

lol fixed

**Comment by akinmail** [comment] 2022-01-09 12:38
@snwokenk This link still points to old documentation where it says it does not allow switching to default chain
https://github.com/MetaMask/metamask-extension/issues/10597#issuecomment-867314248

**Comment by akinmail** [comment] 2022-01-09 12:39
Futhermore, bringing this back, Is there any documentation or examples to utilize the new functionality to switch to default chains?

**Comment by Sotatek-SonNguyen2** [comment] 2022-01-10 11:09
Ohh, It so easy.
Please check below code: 
`try {
  await ethereum.request({
    method: 'wallet_switchEthereumChain',
    params: [{ chainId: '0xf00' }],
  });
} catch (switchError) {
  // This error code indicates that the chain has not been added to MetaMask.
  if (switchError.code === 4902) {
    try {
      await ethereum.request({
        method: 'wallet_addEthereumChain',
        params: [{ chainId: '0xf00', rpcUrl: 'https://...' /* ... */ }],
      });
    } catch (addError) {
      // handle "add" error
    }
  }
  // handle other "switch" errors
}`

refer: [This link]( https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain)

**Comment by patniemeyer** [comment] 2022-03-21 21:50
FYI, The pattern above of calling switch chain, catching a possible exception and then attempting to add the chain if needed works on desktop and works for *most chains* on mobile but for some chains I get the "-32602 May not specify default MetaMask chain" exception.  Specifically this is happening for us when trying to add Optimism on iOS Mobile.

**Comment by marino39** [comment] 2022-05-22 15:48
> FYI, The pattern above of calling switch chain, catching a possible exception and then attempting to add the chain if needed works on desktop and works for _most chains_ on mobile but for some chains I get the "-32602 May not specify default MetaMask chain" exception. Specifically this is happening for us when trying to add Optimism on iOS Mobile.

I have the same issue. Have you found any way around it?

**Comment by kmkhami** [comment] 2022-05-25 19:30
> FYI, The pattern above of calling switch chain, catching a possible exception and then attempting to add the chain if needed works on desktop and works for _most chains_ on mobile but for some chains I get the "-32602 May not specify default MetaMask chain" exception. Specifically this is happening for us when trying to add Optimism on iOS Mobile.

+1 . I am also having this same issue.

**Comment by patniemeyer** [comment] 2022-05-25 19:36
Since this issue is closed you may want to follow this issue for the problem:  https://github.com/MetaMask/controllers/issues/740
