### ISSUE TITLE
Metamask doesn't update state of mined transaction + Unexpected property was found in Webextension property

### ISSUE THREAD

**Issue by robertmagier** [MetaMask/metamask-extension#4193] opened 2018-05-05 00:24 UTC
*  Expected Behavior
Metamask works stable. 
  *  Actual Behavior
Metamask is giving me a lot of defects:
1. Works slow and use a lot of CPU resources. 
2. After transaction is being send to my local geth metamask doesn't update current state of blockchain and transaction stays in progress ( three dots ).  
Using web3.eth.getTransactionReceipt returns transaction receipt in my local vue.js application, but Metamask still shows transaction in progress. Blockchain state is also not modified and it looks like my transaction wasn't mined. 
3. Can't start debugging in about:debugging 
4. Metamask stays on top until key ESC is pressed. 
5. In about debuggin section I can see that "Unexpected property was found in Webextension property"

*  Browser Used
Firefox 59.0.3 (64 bits)
  *  Operating System Used
Windows 10 2017 Home. 
![metamaskerror](https://user-images.githubusercontent.com/34715949/39657739-4c3e89aa-4fd0-11e8-9e16-a548884a0421.PNG)

![metamaskerror2](https://user-images.githubusercontent.com/34715949/39657751-671210b2-4fd0-11e8-857e-01569aee4922.PNG)

![metamaskerror3](https://user-images.githubusercontent.com/34715949/39657805-1c167fc0-4fd1-11e8-9235-6d85c6c4af08.PNG)

[metamask.log](https://github.com/MetaMask/metamask-extension/files/1976208/metamask.log)

**Comment by robertmagier** [comment] 2018-05-05 00:58
After uninstalling and installing Firefox I was finally able to start debugging. 
Logs attached. 

[metamask.log](https://github.com/MetaMask/metamask-extension/files/1976207/metamask.log)

**Comment by robertmagier** [comment] 2018-05-05 02:15
I have just deleted my blockchain datadir in geth and initialized it again. After importing my private keys from Metamask to my local node I am able to send transactions and Metamask is correctly updating it. 
I don't know what to think about it. I had similar problem 3 weeks ago and also after deleteing my blockchain datadir everything started to work ok.

**Comment by bdresser** [comment] 2018-10-15 22:45
Sorry for your trouble and for the delay @robertmagier 

What you describe in (1) is a known issue with a standing bounty (#4074)

We've re-written our underlying provider since this issue was opened so I expect (2) is no longer an issue. 

can't reproduce (3), `about:debugging` works for me

for (4), i see the window disappear as soon as I click anywhere in the browser

**Comment by tmashuang** [comment] 2021-01-05 18:58
There have been another of iterations of since this issue and without know what parameters are set in your local geth, I was not able to reproduce the behavior along with your hardware specifications. Closing.

**Closed by tmashuang** 2021-01-05 18:58 UTC
