### ISSUE TITLE
Inform possibility tokens may be lost if recipient address doesn't support network 

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#13751] opened 2022-02-24 22:58 UTC
### Scope

Clearly indicate that the transaction is happening within a network, and if recipient address in Send flow doesn't work with this network, this will result in fund loss 

Reference pattern:
- "Sending on the <network name>"
- "The person I am sending to has a wallet that supports <network name>"

![Untitled.png](https://images.zenhubusercontent.com/61bca1d5fe0c993f7720b3c7/beaefa3e-2bc4-4a1d-a5f0-caa4c1d488ca)

## Archive

- Add notice on the send screen "This transfer will be on the X network, please double-check the network that the recipient account is on!" If you're trying to send XYZ, it'll only let you select a sending address that's also on the XYZ network.
- The problem might be that people are trying to send assets cross-chain, e.g., from Ethereum mainnet to another chain. And this doesn't work as people expect, so people end up losing the assets they send. And we don't provide any error for that - we also don't know when to show that error - shall we do it always? Might also want to add UX flow and education for how the transfer of funds work across to custom networks.

**CS team reported:** 

- Generalized warning when sending txns: we are seeing lots of users losing funds because they are sending to exchanges that don’t support the network they are using, or the token they are using. Many tickets are generated with this exact topic, and we cant offer much in the way of a response except to point them to the recipient (we’ve even added language to the ticket form page to address this). Suggestion: generalized warning regarding double checking recipient compatibility with network/token in the UI.

 **IDEA:** 
Integrated education in the product for **this issue -** increase friction when trying to make txns on unsupported networks (e.g. sending binance token to coinbase - doesn’t work). Ppl don’t understand blockchain txns are not refundable/reversible. Happening on Mobile and Extension
    
Slack thread: https://consensys.slack.com/archives/G8RSKCNCD/p1639076704289400
    
**Address verification warning:**
https://www.figma.com/file/EUQ1LPxKPU9tga4YnjISn1/Network-specific-assets?node-id=634%3A13695
https://www.figma.com/file/EUQ1LPxKPU9tga4YnjISn1/Network-specific-assets?node-id=634%3A13695
        - Action item: determine conditions when we should show the warning
        - We should show this warning when:	
1. The user is sending the selected token to the receiving address for the first time 
AND 1.1 the address has not had any activity yet on the current network	
OR	1.2 it belongs to an exchange - Dan F. exchanges rotate address a lot, so it might be hard to keep it up to date. 	
OR	1.3 it’s a contract - Dan F. said we can know

- At first we will only show when the user is on Binance Smart Chain, but later we intend to show on other networks as well.Copy change: we should replace the word “tokens” for the selected token in this phrase: “Are you sure the recipient can receive **tokens** on <network>?”Maybe we should only release this when we support EIP 3770: Network prefixed addresses

**Comment by bschorchit** [comment] 2022-02-25 19:09
Closing this as it's a duplicate of https://github.com/MetaMask/metamask-extension/issues/13733

**Closed by bschorchit** 2022-02-25 19:09 UTC
