### ISSUE TITLE
metamask is not displayed

### ISSUE THREAD

**Issue by starmankiti** [MetaMask/metamask-extension#5120] opened 2018-08-21 22:51 UTC
Commenting using machine translation
metamask is not displayed

Even after logging in, it will stop on the white screen

**Comment by starmankiti** [comment] 2018-08-21 22:51
![2018-08-22 07 50 13](https://user-images.githubusercontent.com/42591311/44433191-3b3e5c00-a5e0-11e8-8534-4c0ba6871038.png)

**Comment by bdresser** [comment] 2018-08-21 23:03
Closing as a duplicate of #4894. If there's anything useful in your [background logs](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue) please add to the issue there!

**Closed by bdresser** 2018-08-21 23:03 UTC
