### ISSUE TITLE
MetaMask / metamask-extension Build error on Windows10 

### ISSUE THREAD

**Issue by AsadullahSoomro** [MetaMask/metamask-extension#12168] opened 2021-09-21 05:45 UTC
Currently, I am trying to build Metamask on windows 10 using Nodejs v14.17.6

yarn run v1.22.11
$ lavamoat development/build/index.js
(Error#1)

Error#1: LavaMoat - required package not in whitelist: package "@gulp-sourcemaps\map-sources" requested "through2" as "through2"
at requireRelative (LavaMoat/core/kernel:414:15)
at requireRelativeWithContext (LavaMoat/core/kernel:366:16)
at Object.eval (\work\metamask-extension\node_modules@gulp-sourcemaps\map-sources\index.js:4:15)
at internalRequire (LavaMoat/core/kernel:353:25)
at requireRelative (LavaMoat/core/kernel:394:27)
at requireRelativeWithContext (LavaMoat/core/kernel:366:16)
at Object.eval (\work\metamask-extension\node_modules\gulp-sourcemaps\index.js:7:15)
at internalRequire (LavaMoat/core/kernel:353:25)
at requireRelative (LavaMoat/core/kernel:394:27)
at requireRelativeWithContext (LavaMoat/core/kernel:366:16)

OS: Windows 10
MetaMask Version: 10.1.0
Node v14.17.6
Yarn v1.22.11
error screenshot here: 
![image](https://user-images.githubusercontent.com/46569970/134118067-3195c3ea-9198-4aa3-bacf-0601b68ef5bc.png)

**Comment by ryanml** [comment] 2021-09-21 15:16
@AsadullahSoomro - did you run `yarn setup` or just `yarn`?

**Comment by AsadullahSoomro** [comment] 2021-09-22 09:58
> @AsadullahSoomro - did you run `yarn setup` or just `yarn`?
@ryanml 
yes, sir,it is running but right now another exception coming when I am just trying to clone the metamask using

MetaMask/metamask-extension from github

I am just following the docs, but ended up in error when access the extension via browser
Uncaught ReferenceError: LavaPack is not defined
context
background.html

I have tried to get it resolve but unable to find any clue 
![image](https://user-images.githubusercontent.com/46569970/134323410-062126ad-2df3-4171-9d41-a86a99e95568.png)

**Comment by Gudahtt** [comment] 2021-10-13 19:45
Thanks for the report! This is a duplicate of #10748. Please follow that issue for updates.

**Closed by Gudahtt** 2021-10-13 19:45 UTC
Labels: area-buildSystem
