### ISSUE TITLE
Unable to sign transactions/fetch data on Kovan Testnet via metamask extension

### ISSUE THREAD

**Issue by nitika-goel** [MetaMask/metamask-extension#3095] opened 2018-01-25 11:54 UTC
Hi Team,
Metamask extension does not seem to be working on the Kovan Testnet, Neither are we able to create transactions nor fetch data from contracts already created on Kovan testnet. PFB a screenshot for your reference.
![image](https://user-images.githubusercontent.com/33280614/35387107-79d9f7d4-01f4-11e8-8a18-ae3ba66c82bd.png)

**Comment by jordanmurkin** [comment] 2018-01-25 15:28
This issue has also been reported in #3094

**Comment by kumavis** [comment] 2018-01-25 18:59
Thanks for reporting, closing as dupe of #3094

**Closed by kumavis** 2018-01-25 18:59 UTC
