### ISSUE TITLE
eth_signTypedData(): callback function is no longer called in v 4.9.0 on 'SIGN' button

### ISSUE THREAD

**Issue by Maxxi** [MetaMask/metamask-extension#4975] opened 2018-08-07 23:58 UTC
The following code worked fine in <=v 4.8.0:

```
web3.currentProvider.sendAsync( {
            'eth_signTypedData',
            params,
            address
        }, 
        (err, result) => {
            // callback code
        }
);
```
But it stopped working in version 4.9.0.         
_(err, result) => {}_ 
callback function is not called anymore after confirming Signature Request (SIGN button)

However, the callback function is still called on 'CANCEL' button as before.

**Comment by Netherdrake** [comment] 2018-08-08 00:53
+1

**Comment by nnkken** [comment] 2018-08-08 03:29
+1
BTW, when will the current `eth_signTypedData` be deprecated and replaced by the merged EIP-712 behaviour?

**Comment by turshija** [comment] 2018-08-08 10:09
I can confirm this too ...
When user clicks cancel - callback is called with first parameter null and second one contains this object:
```
{ 
  "error": {
    "code": -32603, 
    "message": "Error: MetaMask Message Signature: User denied message signature."
  },
  "id": undefined,
  "jsonrpc": undefined
}
```

But when user clicks "Sign" - nothing happens - callback doesn't trigger
It works in 4.8.0, but stops working in 4.9.0

**Comment by bitpshr** [comment] 2018-08-08 13:35
Hi @Maxxi. This was caused by a premature version bump and will be fixed by #4982. We plan to do a patch release shortly thereafter. Thanks for the issue report and for your patience!

**Comment by Maxxi** [comment] 2018-08-08 14:59
Hi @bitpshr . Thanks for your quick reaction on that problem.

**Closed** 2018-08-08 15:26 UTC
Labels: P1-asap, T00-bug
