### ISSUE TITLE
"transaction underpriced" error

### ISSUE THREAD

**Issue by uvizhe** [MetaMask/metamask-extension#13001] opened 2021-12-07 14:53 UTC
I get the error
`Transaction N failed! Error: [ethjs-rpc] while formatting outputs from RPC '{"value":{"code":-32000, "message":"transaction underpriced"}}'`
when I try to send new transaction with gas price set bellow suggested minimum.

This is very annoying.

MM 10.7.0

**Comment by aloisklink** [comment] 2021-12-07 17:26
I'm having the same issue.

I think it's an issue with the default Infura RPC. It might be on purpose, since running an Ethereum RPC isn't free, and it's probably cheaper to ignore underpriced transactions, but I can't seem to find any info about it anywhere.

While we're waiting for confirmation from the MetaMask/Infura team if this is a permanent/temporary change, **I can confirm that using a custom RPC for Ethereum mainnet works for sending underpriced gas transactions**. I could send a 40 gwei transaction to the mempool using used [AlchemyAPI](https://www.alchemy.com/) and it shows up on Etherscan.

You could also trying hosting your own ETH node on your PC and use that as an RPC server. It will probably even be faster than the default Infura RPC. However, it uses up a few hundred GB of disk space, so it's a bit heavy unless you have a bunch of free space on your computer.

**Comment by uvizhe** [comment] 2021-12-07 17:47
@aloisklink thanks for the tip. Unfortunately, not every DApp allows user to switch networks so custom RPC endpoint doesn't always work.

**Comment by leafcutterant** [comment] 2021-12-08 01:38
This is a duplicate of #10519.

**Comment by uvizhe** [comment] 2021-12-08 06:23
@leafcutterant this is not a dup. This issue is about gas price for new transactions, not for resubmitted ones. So it has nothing to do with `txpool.pricebump`.

**Comment by jorgeacortes** [comment] 2021-12-08 10:54
I just experienced the same behavior. I would've expected to have an advanced option toggle to enable it again and a different notice when setting the gas price below the threshold.

**Comment by mrballsauce** [comment] 2021-12-08 16:28
Only noticed recently - it's a very bad update. You should allow the users to set whatever gas price they want. Auto rejecting the transaction is incredibly frustrating for those that are patient on gas to fall. The calculation also isn't accurate, as the prices change rapidly. It's erratic.

**Comment by aloisklink** [comment] 2021-12-08 17:59
More info, it looks like this bug has been reported to INFURA already:
- https://github.com/INFURA/infura/issues/219

However, it's not a decision INFURA made, it seems to be a bug in geth v1.10.13 (latest version):
- https://github.com/ethereum/go-ethereum/issues/24079

**Comment by uvizhe** [comment] 2021-12-08 19:08
Hmm, if network nodes don't allow for highly underpriced transactions to enter txpool (because of some important design constraints), then wallets should not attempt to send such txs but wait for desired conditions and send then.
A desire to save money has to be satisfied some way. Either a wallet provides this or poor users have to automate it somehow on their own.

**Comment by cyrusadkisson** [comment] 2021-12-09 03:05
I'm also experiencing this issue. For large but non-time-sensitive transactions, this is a killer. I would have gladly set my TX to 55 gwei and waited patiently for it to go through. But MM would only process it if I used the suggested network fees. Hundreds of dollars of difference.

**Comment by aloisklink** [comment] 2021-12-22 01:30
It looks like this issue has been fixed.

Infura has rolled back their Geth version: see their message on their community forum
https://community.infura.io/t/when-can-a-non-replacement-transaction-received-a-transaction-underpriced-error/2535/7

I just sent an underpriced transaction on the default Infura RPC and it worked.
Plus, it looks like the [bug in Geth has also been fixed](https://github.com/ethereum/go-ethereum/issues/24079) so when Infura next updates their Geth, it probably won't occur.

**Comment by Gudahtt** [comment] 2022-01-04 17:39
Thanks for the report! It looks like this is an issue with Infura rather than the wallet itself, so I'm going to close this. I appreciate the updates @aloisklink - feel free to continue to use this thread to discuss the upstream problem if you'd like!

**Closed by Gudahtt** 2022-01-04 17:39 UTC
Labels: area-transactions
