### ISSUE TITLE
[Bug]: Extremely long response times when signing using Trezor after a browser restart

### ISSUE THREAD

**Issue by nirvanaosc** [MetaMask/metamask-extension#20923] opened 2023-09-16 10:56 UTC
### Describe the bug

After adding any Trezor account to Metamask, the time it takes for messages/transactions to appear on Trezor for signing is instant, irrespective of the account number.

However, after a browser restart, the time it takes for transactions/messages to appear on Trezor for signing is proportional to the account number. The higher the account number, the longer it takes to appear on Trezor for signing. For instance, when signing transactions/messages with Trezor Account 1, they consistently appear instantly on Trezor for signing. On the other hand, when signing transactions/messages with higher Trezor Accounts such as 200, 500, 700, and so on, the higher the account number, the longer it takes to appear on Trezor for signing (30+ seconds for Account 500+).

This behaviour only happens after a browser restart. Transactions/messages appears instantly on Trezor when using them right after adding them to Metamask.

I am using latest Trezor firmware and bridge.

### Steps to reproduce

1. Install Metamask extension for Firefox (Windows)
2. Add a single very high Trezor account (i.e. 700)
3. Sign any transaction/message with the Trezor Account (i.e. login message for opensea.io). Transaction appears on Trezor almost instantly for signing.
4. Restart browser
5. Sign any transaction/message with the Trezor Account (i.e. login message for opensea.io). Now transaction takes more than 30 seconds to appear on Trezor for signing.

### Version

11.0.0

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Hardware wallet

Trezor

**Comment by vivek-consensys** [comment] 2024-04-16 10:00
Unable to reproduce, closing.

**Closed by vivek-consensys** 2024-04-16 10:00 UTC
Labels: type-bug, area-hardware, Sev3-low, hardware-trezor, team-accounts, team-hardware-wallets
