### ISSUE TITLE
Feature Request: Show total account balance incl. sum of all token balance

### ISSUE THREAD

**Issue by sebastiantf** [MetaMask/metamask-extension#7645] opened 2019-12-04 17:15 UTC
The extension doesn't **_show the total account balance in USD_** that includes the sum of all token balances.

The MetaMask mobile application has this feature showing the total account balance in USD in the side menu:

![output-onlinepngtools (1)](https://user-images.githubusercontent.com/36922376/70165347-c580d580-16e8-11ea-9b8d-2e802fdf81f0.png)

This would be a nice feature to have in the extension as it gives better info about an account.

**Comment by tamassengel** [comment] 2020-05-17 21:56
This would be so useful. The same "issue" (or missing feature) is present in the browser extension as well.

**Comment by LukeKoz** [comment] 2020-08-17 12:47
I thought I was going crazy and couldn't find the setting for this. This would be super helpful!

**Comment by jboz62** [comment] 2020-09-18 21:42
Yes please, this would be very helpful, lots of empty space on the extension to add that.

**Comment by tamassengel** [comment] 2020-09-19 09:47
In the meantime, as a temporary solution, you can click on View on Etherscan and it will show you your account's total balance there (some prices are missing, not as good as Coingecko/Uniswap, but at least it's something)

**Comment by jboz62** [comment] 2020-09-19 15:39
> In the meantime, as a temporary solution, you can click on View on Etherscan and it will show you your account's total balance there (some prices are missing, not as good as CoinGecko/Uniswap, but at least it's something)

Thanks for the tip, that helps!

**Comment by Gudahtt** [comment] 2021-01-08 00:23
Thanks for the suggestion! This appears to be a duplicate of #6999, so I'm going to close this one.

**Closed by Gudahtt** 2021-01-08 00:23 UTC
Labels: L30-balances
