### ISSUE TITLE
Editing token to be sent changes the displayed recipient address 

### ISSUE THREAD

**Issue by BeckerFelix** [MetaMask/metamask-extension#13031] opened 2021-12-09 09:33 UTC
**Describe the bug**
While in the process of creating a transaction, the displayed recipient address changes to the ERC-20 token contract address when user edits the token to be sent from ETH to said ERC-20 token.

#### Notes:
* As far as I see, this only affects the **displayed** recipient address. The transaction would still be published with the correct, initially intended recipient address, if it was confirmed.
* This bug happens on various blockchains with various gas tokens initially selected. I tested ETH Mainnet, BSC, and Optimism.

**Steps to reproduce (REQUIRED)**

1. Click on "Send" 
2. Choose recipient
3. Choose ETH
4. Click Next
5. On the page that shows the estimated gas fees, click "<EDIT" in the top left
6. Change the asset to send from the gas token to any other token
7. Click Next
8. Observe that the recipient address has changed to the contract address of the token you are about to send

**Expected behavior**
Recipient address does not change

**Screenshots**
![3](https://user-images.githubusercontent.com/33390210/145370618-0974a438-68f4-4eb6-bd84-465640bb4eab.gif)

**Browser details (please complete the following information):**
 - OS: Ubuntu 20.04
 - Hardware Wallet: no / independent of it
 - Browser: Chromium Version 95.0.4638.69, Firefox Browser 94.0
 - MetaMask Version: 10.7.0 on Firefox and 10.7.1 on Chromium.

**Comment by danjm** [comment] 2021-12-09 21:32
Note to other engineers: it seems this bug existed as far back as 9.7.1

I have not found the root cause yet

**Comment by dragana8** [comment] 2021-12-28 09:43
I have found that when in edit mode in ui/ducks/send/send.js  to parameter is set to state.asset.details.address, which is token's address, and that is being used for creating name of the recipient which is causing this bug.  I have tried to use the same state data that is being used to show toAddress in the top section of the screen, but the state is being cleared after edit. We need more info why is this done this way and what is the best approach how to fix this and not to break anything.

**Comment by brad-decker** [comment] 2022-01-20 02:09
@danjm I am escalating this to a sev1 bug because it isn't just UI cosmetic. It could result in loss of funds.

**Comment by danjm** [comment] 2022-01-20 12:27
@brad-decker See the initial post above "As far as I see, this only affects the displayed recipient address. The transaction would still be published with the correct, initially intended recipient address, if it was confirmed."

My initial research into this seemed to confirm that as well

**Comment by danjm** [comment] 2022-01-28 19:37
Blocked by #13386

**Comment by bschorchit** [comment] 2022-09-16 00:42
I think this might have been solved already. I was not able to reproduce it. 
Not closing it though until someone else double checks and confirm it too.

**Comment by ElvirCe** [comment] 2022-09-19 13:09
Yes I can confirm that this has been solved with Dan's PR here https://github.com/MetaMask/metamask-extension/pull/14721 and I am moving the ticket to 'In Review' status.

**Comment by bschorchit** [comment] 2022-09-19 21:30
> Yes I can confirm that this has been solved with Dan's PR here #14721 and I am moving the ticket to 'In Review' status.

Closing the ticket as this has been solved

**Closed by bschorchit** 2022-09-19 21:30 UTC
Labels: type-bug, Sev2-normal, PS-team, Team 🌳, stedmap team
