### ISSUE TITLE
Tokens previously hidden randomly reappear

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#9248] opened 2020-08-17 17:11 UTC
**Describe the bug**
User reported that some of the tokens he has hidden on MetaMask reappeared after updating to 8.0.7

**To Reproduce (REQUIRED)**
Need to reproduce / test more

**Expected behavior**
Once hidden they should never reappear unless the user unhides them.

**Additional context (Error Messages, etc.)**
ticket 44470

**Comment by Gudahtt** [comment] 2020-08-18 01:37
This is a duplicate of #5055; this has been a problem for a long time.

**Closed by Gudahtt** 2020-08-18 01:37 UTC
Labels: L03-UI, N02-needsReproduction, S3-low
