### ISSUE TITLE
Logged on testnet, then logged on main network, but showing yet the balance of testnet instead of a loading spinner

### ISSUE THREAD

**Issue by DaniellMesquita** [MetaMask/metamask-extension#6019] opened 2019-01-14 02:44 UTC
![image](https://user-images.githubusercontent.com/6765277/51094467-6e9ea480-1794-11e9-8230-96bee75c1dae.png)

**Comment by bdresser** [comment] 2019-01-14 21:01
@DaniellMesquita I can't reproduce this – could you include more detailed steps on how you got in this state?

**Comment by DaniellMesquita** [comment] 2019-01-15 02:31
The steps I remember are as follows in the title. Detail that I use a limited Internet connection with 3KBps. But it should show a spinner for loading balances when switching between networks.

**Comment by danjm** [comment] 2019-01-23 16:16
@bdresser I was able to reproduce as described by @DaniellMesquita 

Fix forthcoming

**Comment by danjm** [comment] 2019-01-23 17:06
Actually, just adding a loading screen really harms the experience for users with faster connections. A flash of a loading screen on every network switch is non-ideal.

We perhaps need an animated transition of definite duration on the loading screen. Or in the case of a network change, instead of overlaying an entire loading screen, we could add a simple animated transition to the balance (e.g. fade out, fade in)

I'll put together an MVP of the latter and then run it by @bdresser and @cjeria

**Comment by bdresser** [comment] 2019-02-13 23:37
@danjm is this solved by https://github.com/MetaMask/metamask-extension/pull/5854, or possible to include the cached indicator for wrong-network balances (in addition to stale ones) ?

**Comment by danjm** [comment] 2019-02-19 17:44
@bdresser this is not fixed by the cached balances changes I made. I will do the 'animated transition' type solution I described previously and share a gif here within the next 24 hours.

**Comment by danjm** [comment] 2019-02-21 04:33
@bdresser @DaniellMesquita Let me know what you think of the screen captures here: https://github.com/MetaMask/metamask-extension/pull/6193

Users will always see the loading spinner and fade out/in as is shown in those videos. The spinner will be shown until the network request resolves, so users will see it for as long as is needed.

**Comment by tmashuang** [comment] 2020-02-10 23:10
Closing due to inactivity, my recent attempt to reproduce has been unsuccessful. If this issue has persisted please open a new issue.

**Closed by tmashuang** 2020-02-10 23:10 UTC
Labels: L03-UI, T00-bug, in progress
