### ISSUE TITLE
White screen; extension not working

### ISSUE THREAD

**Issue by dvdschwrtz** [MetaMask/metamask-extension#7756] opened 2020-01-07 19:59 UTC
Basically getting a white screen when I login. Looking at the console I see these two errors as helpful hints. Note that I thought it could be a corrupted local storage so I removed the extension and then re-created the account and same issue:

Uncaught (in promise) BigNumber Error: times() not a number: null
Error in event handler: TypeError: Cannot read property 'getHostNode' of null

Using latest version on Chrome version 79.0.3945.88

**Comment by dvdschwrtz** [comment] 2020-01-07 20:04
Weird. It just started working again after having this issue for 5 mins. There is definitely a bug here though.

**Comment by dvdschwrtz** [comment] 2020-01-07 20:45
it is a reoccuring issue apparently. happening again

**Comment by Gudahtt** [comment] 2020-01-10 21:22
Thanks for the report!

We're having some trouble reproducing this - do you remember what you did or clicked that resulted in this error? Also, could you share the full error including the stack trace?

**Comment by Jetsoanalin** [comment] 2020-01-14 10:53
I'm facing similar issue in my Firefox, Chrome browser latest version both and also metamask is installed latest. once i am done with the get started and adding wallet seedpharse and giving the password when i click on all done after that nothing happens and once i click on the extension in the browser it shows me white screen nothing works there.

**Comment by Jetsoanalin** [comment] 2020-01-22 06:42
Duplicate of #7847

**Comment by Jetsoanalin** [comment] 2020-01-31 04:18
Fixed in the Latest version 7.7.3

**Comment by rickycodes** [comment] 2020-01-31 16:05
Closing this as it sounds like this was fixed in 7.7.3

@dvdschwrtz can you confirm? If it's still outstanding for you we can re-open and further investigate

**Closed by rickycodes** 2020-01-31 16:05 UTC
Labels: N07-needsSupport, T00-bug
