### ISSUE TITLE
[Bug]: Smart Transactions - Custom Nonce is not displayed for some networks if Smart Transactions is enabled

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24275] opened 2024-04-29 08:23 UTC
### Describe the bug

The Custom Nonce section is not displayed anymore for some networks (Mainnet, Sepolia etc) if I have the Smart Transaction settings enabled. Interestingly it is still displayed in some networks (like Optimism, BNB, Polygon).

### Expected behavior

We should see the Custom Nonce section on any network, if this is enabled from Settings and Smart Transactions are enabled from Settings

### Screenshots/Recordings

Now (with Custom Nonce enabled)

![Screenshot from 2024-04-29 10-01-38](https://github.com/MetaMask/metamask-extension/assets/54408225/9f03383f-4db2-4587-81bb-4d4acb566400)

https://github.com/MetaMask/metamask-extension/assets/54408225/5d30b305-4685-4487-906a-464c7f3a64c5

Before (with Custom Nonce enabled)

![Screenshot from 2024-04-29 10-02-45](https://github.com/MetaMask/metamask-extension/assets/54408225/900c6306-fae5-4384-940b-f8e9bd868159)

### Steps to reproduce

1. Select Mainnet / Sepolia
2. Enable Customize tx Nonce from advanced settings
3. Enable Smart Transactions from advanced settings
4. Trigger any tx
5. See nonce section is not there
6. Switch to Optimism / Polygon
7. Trigger any tx
8. See nonce section is there

### Version

11.16.0, 11.15.0 but not in 11.14.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by forest-diggs-consensys** [comment] 2024-07-23 19:47
This is expected behavior - since Smart Transactions are automatically cancelled, users don't end up in the same scenario(s) where they have stuck transactions and need to set a custom nonce.

**Comment by klejeune** [comment] 2024-09-19 09:01
This behavior is working as intended. Closing the ticket.

**Closed by klejeune** 2024-09-19 09:01 UTC
Labels: type-bug, Sev2-normal, regression-RC, team-transactions, regression-RC-11.15.0
