### ISSUE TITLE
Metamask in Chrome shows too little amount Ariva ARV

### ISSUE THREAD

**Issue by Kostak3** [MetaMask/metamask-extension#12181] opened 2021-09-22 11:28 UTC
**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

![MetamaskBUG](https://user-images.githubusercontent.com/91192333/134335253-b8ab8c5b-5937-478e-9af5-5dd624df2ed8.png)
1. Go to 'https://coinmarketcap.com/currencies/ariva/' using Chrome and Metamask 10.1.0  and don't have ARV in it, but have Binance network BSC BNB account.
2. Click on 'fox-avatar of metamask' to add the token in Metamask and agree adding it
3. Swap BNB in my case 0.01 BNB to Ariva ARV - my transaction is:
 https://bscscan.com/tx/0xd3b07010fadeaf133a7c3287536d03b371b7f5fcfe448a840d280bcee910254b
4. See the amount received on the transaction page (above URL) is 1,546.93450241 ARV the Metamask shows :
0.000000154693450241 ARV also +1.54693e-7 ARV . Apparently INCORRECT value. 

**Expected behavior**
Expected to see amount 1,546.93450241 ARV

**Screenshots**
Screenshots and state logs attached.

**Browser details (please complete the following information):**
 - OS: Linux Fedora 33  KDE Plasma 
 - Hardware Wallet: N/A
 - Browser: Chrome Version 93.0.4577.63 (Official Build) (64-bit)
 - MetaMask Version: 10.1.

![MetamaskBUG](https://user-images.githubusercontent.com/91192333/134335311-f5225985-0fd4-4b07-801b-fe0daf28e2ab.png)
0

**Comment by danjm** [comment] 2022-04-07 09:42
This would have been caused by an incorrect decimal amount being proposed by caller of wallet_watchAsset. One thing we could do to improve this is add validation in the wallet_watchAsset confirmation. We could check the contract directly and notify the user  if the number of decimals being proposed by the dapp are different from the decimals reported by the token contract itself.

Closing this, but tagging @bschorchit as I think this is a candidate for a new papercut / improvement issue.

**Closed by danjm** 2022-04-07 09:42 UTC
Labels: type-bug, area-customNetworks, Sev2-normal
