### ISSUE TITLE
vendor folder missing

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#6043] opened 2019-01-17 17:58 UTC
Context:
building metamask from source on windows 10 (64bit)

**Describe the bug**
when running ```gulp build``` after a successful ```npm install``` using sha3 2.0.0 (see #6042)
I get the following error:

```
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:\dev\projects\wighawag\metamask-extension\node_modules\gulp-sass\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:786:3)
    at Object.getInstalledBinaries (C:\dev\projects\wighawag\metamask-extension\node_modules\gulp-sass\node_modules\node-sass\lib\extensions.js:129:13)
    at foundBinariesList (C:\dev\projects\wighawag\metamask-extension\node_modules\gulp-sass\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\dev\projects\wighawag\metamask-extension\node_modules\gulp-sass\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\dev\projects\wighawag\metamask-extension\node_modules\gulp-sass\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\dev\projects\wighawag\metamask-extension\node_modules\gulp-sass\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\dev\projects\wighawag\metamask-extension\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**To Reproduce**
1. ```npm install sha3@2.0.0```
2. ```npm install```
3. ```gulp build```

**Comment by ArvsIndrarys** [comment] 2019-02-04 10:41
I get the same problem with Ubuntu 16.04 :/
I also needed to add `npm install sha3@2.0.0` to avoid a `make` failure when building the `sha3` dependency

**Comment by ArvsIndrarys** [comment] 2019-02-04 10:45
I got it resolved with the  [`npm rebuild node-sass`](https://github.com/dlmanning/gulp-sass/issues/562#issuecomment-261133200) command line.

**Comment by ArvsIndrarys** [comment] 2019-02-05 23:33
The installation of sha3 prevents a `npm install` failure because a `make` command that invokes node-gyp.
Cloning the project and trying `npm i` directly should give you the error.

**Comment by whymarrh** [comment] 2019-02-06 00:53
> Cloning the project and trying `npm i` directly should give you the error.

Unfortunately I can't reproduce this. This might be a Windows-related issue?

**Comment by wighawag** [comment] 2019-02-06 07:49
Thanks @ArvsIndrarys your solution made ```gulp build``` succeed
@whymarrh  for the sha3 issue it might indeed be a windows only issue, see #6042

**Comment by ArvsIndrarys** [comment] 2019-02-06 08:13
I got the same problem on Ubuntu 16.04 :/

**Comment by whymarrh** [comment] 2019-02-06 17:17
@ArvsIndrarys can you share the reproduction steps for Ubuntu?

**Comment by ArvsIndrarys** [comment] 2019-02-06 21:54
I got it by cloning the project and calling `npm install`. I may be an exception

**Comment by whymarrh** [comment] 2019-02-06 22:29
@ArvsIndrarys unfortunately we can't help without the ability to reproduce this reliably. If you are unable to setup the project on Ubuntu 16.04 after following the steps outlined in the readme and have specific things we can address, please open up a new issue.

@wighawag your comment above seems like you've solved your install issue? If you're all set feel free to close this.

**Comment by wighawag** [comment] 2019-02-07 08:02
I can close it but don't you consider it an issue that calling ```npm
install``` is not enough. At least it should be documented, no?

**Comment by whymarrh** [comment] 2019-02-07 23:48
I don't mean to seem dismissive, I would agree that if `npm install` didn't work it would be an issue. That said, unfortunately I can't reproduce these errors on macOS or Ubuntu (and we have devs using both to work on MetaMask). I'm not sure there's anything here that we can fix without being able to reproduce this exact error.

**Comment by wighawag** [comment] 2019-02-11 07:37
you could simply document the fix but this is up to you :)

**Comment by whymarrh** [comment] 2019-02-11 17:24
@wighawag I added a note to the README

**Closed** 2019-02-11 17:24 UTC
Labels: T16-buildSystem, in progress
