### ISSUE TITLE
[Bug]: Token detection detected a token I have no balance for

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16057] opened 2022-10-03 12:13 UTC
### Describe the bug

Token detection feature alerted me it found 1 new token, but it shows me a token I have 0 balance for. 
![Screen Shot 2022-10-03 at 09 09 30](https://user-images.githubusercontent.com/34968356/193573326-74caf829-5c4f-43b4-abd1-04403186b5b1.png)

![Screen Shot 2022-10-03 at 09 06 44](https://user-images.githubusercontent.com/34968356/193573244-f4dc855a-516b-49f7-b74d-48bea6aee6ac.png)

### Steps to reproduce

Not sure what the steps to reproduce are. @seaona have you by any chance come across this bug before?
This was not a token I had a balance in the past in this account nor in any other account in MM. 

### Version

10.19.0

### Browser

Brave

### Operating system

MacOS

**Comment by seaona** [comment] 2022-10-03 16:01
thank you @bschorchit I'll try to repro it

**Comment by seaona** [comment] 2022-10-04 08:40
I've been investigating the issue and it seems like what happened on Mobile is related to Importing Accounts with tokens and re-starting MM. In their case, when they restart MM, the selected account it's always the first account in the wallet, resulting in showing the imported account tokens into the first account.

https://user-images.githubusercontent.com/10508597/190052314-b6ccb956-bc59-4e9b-bb16-b389c8f9c8d6.mov

I'm trying to see how we can reach into the same state in MM, as when we kill MM and re-start it again we see that the selected account is preserved as the one it was previously, making it hard to repro.

I will update with more info soon @bschorchit @danjm

**Comment by bschorchit** [comment] 2022-10-04 21:53
I never imported an account in the MM instance where this bug happened so it could be something unrelated to that (I know I'm probably only making it harder to figure it out, sorry 😅).

**Comment by seaona** [comment] 2022-10-05 09:21
no problem! That's actually good information!! Thank you, I'll continue investigating this @bschorchit

**Comment by danjm** [comment] 2022-10-05 13:40
@bschorchit can you look at that account on etherscan and look at the tokens it holds and confirm there are no SNX tokens? I want to rule out the possibility that someone sent you (without you knowing) a tiny amount of those tokens (which, combined with a rounding bug, could explain the bug you saw)

**Comment by bschorchit** [comment] 2022-10-05 15:05
No SNX tokens on etherscan.

Mariona and I were going over it as well this morning and here's some new findings.

- I had another MM wallet in Chrome with the same SRP, so I opened it and turned token detection on and nothing happened. I noticed it was in v.10.4.1 so I updated to v.10.19.0 and immediately got the same token detected notification for the same token (SNX) with no balance. 

- I did a fresh install of MM and imported the same SRP, turned token detection on and was not able to reproduce this bug.

**Comment by danjm** [comment] 2022-10-20 19:10
Removing this from the v10.21.0 milestone because we will need to figure out how to reproduce it before we can fix it, and we probably won't be able to figure that out until we get more reports, so we shouldn't block v10.21.0 on this

**Comment by seaona** [comment] 2022-10-25 20:52
I could sort of reproduce the issue (see video). Not sure if might be exactly the same case as you @bschorchit but maybe the underlying problem it is the same? @danjm 

[token-detection.webm](https://user-images.githubusercontent.com/54408225/197879380-d4c2fcc4-a3ae-46b1-9073-7c3f19154c4c.webm)

**Comment by NiranjanaBinoy** [comment] 2022-11-10 01:38
@seaona @danjm I was able to reproduce the bug just now, it seems to be happening when we are upgrading to v10.19.0, where token detection v2 is introduced, with token detection turned ON. This seems to be inline with what @bschorchit mentioned in [this comment](https://github.com/MetaMask/metamask-extension/issues/16057#issuecomment-1268569918)
I am attaching a screen recording of the bug while changing from V10.18.0 to V10.19.0.

https://user-images.githubusercontent.com/43930900/200978812-afdda2c1-d6c0-453d-8bac-516be376b683.mov

**Comment by seaona** [comment] 2022-11-10 13:11
great finding @NiranjanaBinoy !!

**Comment by NiranjanaBinoy** [comment] 2022-11-10 23:06
The issue with the object key seems to be because, before token detection v2, the `data` property in `tokensChainsCache` was a list, and after token detection v2, it is an object, so when we upgrade from 10.18.0 to any version with token detection v2 the list is destructured to an object, and the keys are auto-assigned as numbers starting from 0.

**Comment by NiranjanaBinoy** [comment] 2022-11-18 18:39
#16535 fixing the root cause of this issue, but for the users who already have SNX tokens without balance in their state as detectedTokens we will not be able to remove it. So this PR makes sure this issue does not happen to any future users, but for those who already have this 0 balance SNX token as their detected token, it stays.

**Comment by seaona** [comment] 2022-11-22 11:26
@NiranjanaBinoy great work!! I've checked it and looks good for me. I close the issue

**Closed by seaona** 2022-11-22 11:26 UTC
Labels: type-bug, area-tokens, Sev2-normal, team-extension-client
