### ISSUE TITLE
the seed phrases I backed up from MetaMask did not restore the accounts they were given. 

### ISSUE THREAD

**Issue by jazzinuf** [MetaMask/metamask-extension#3042] opened 2018-01-19 12:40 UTC
Couple of days ago I bought some ICO tokens and saved it in my metamask wallet. However this morning, my metamask was locked or seemed to have logged me out. I have the seed words but do not have private keys. I restored the account using the seed words, however it moved to a new account. My original account was:
0x19703b917eb4EBaC0fE469180326B88E2a407A03

and now i'm on another account.
0x6675c59433C3a9100F7709C5D1A26ad1086d6076

I have quite alot of money in the original address and would appreciate it if anyone can help me out as this situation is pretty serious.

**Comment by danfinlay** [comment] 2018-01-29 19:53
Sorry for the long wait, please send an email to support@metamask.io and we'll explore the possibilities.

One question we'll have is "when did you first install MetaMask and copy down this seed phrase?"

**Comment by danfinlay** [comment] 2018-01-29 19:53
Also, have you tried your seed phrase on another wallet, like myetherwallet.com?

**Comment by Ruffdawg212** [comment] 2018-01-29 20:30
Dear Danfinlay

I have the same problem with jazzinuf  and no matter what i did i couldn't solve this problem.
Just like him i participated into ICO and bought some tokens. On that time my original account was : 0x5a839909410A2C2ED09Ce6dFA93D17eDd9791C28

After 1-2 days i forgot my password and used my 12 seed words to unlock it. Now i am using this account
0x8CDE22Ac596C80Ed0Dbb3810A82703A1398fD518

I read all of your posts regarding to this issue and tried everything. I reinstalled the plugin and pressed "create new account" button . I also used 12 seed words on myetherwallet. I can't see that account on there either. 

Can you please advise how can we fix this issue

Thank You

**Comment by jazzinuf** [comment] 2018-01-29 20:39
@ruffdawg212

Few days ago I found an alternative way to get my tokens back, perhaps this way could work for you. Go to myetherwallet and click the “send eth” tab. Once you do click on the “mnemonic phrase” option. Do NOT enter your password, and restore your wallet. There will be many address, find your address and add your token. Listen I did plenty of research for a whole week and felt like I lost almost half of my portfolio. However few days ago I read a post from @danfinlay and found this alternative way. Try this way and let me know if it works. 

Eddie Lim

**Comment by Ruffdawg212** [comment] 2018-01-29 21:01
Dear Eddie

I have been searching my address with your way for 15 minutes but couldn't locate it.
I tried all the servers and i also tried my path option but couldn't see it :(

Too many addresses on the servers. How many minutes did it take you to locate yours ?

**Comment by jazzinuf** [comment] 2018-01-29 21:05
Hey Ruffdawg
For me it was on the first page so found it pretty quick. Keep searching, and I hope the metamask team could help you out. But im sure you will be able to find it, as long as the ICO tokens are still in the address. Let me know how it goes, I understand your pain.

**Comment by danfinlay** [comment] 2018-02-13 22:06
Closing as duplicate of #3127.

**Closed by danfinlay** 2018-02-13 22:06 UTC

**Comment by besiwims** [comment] 2018-11-03 15:35
Good day
Can anyone help me please, I sent ether from cex to metamask for an important purchase. The transfer was successful but my metamask now has a different address and my ether is gone. When I check on ether scan, metamask performed another transacation sending the 0.8 ether to another address and that address happens to be one of my metamask account. That 0.8 ether has just disappeared also. Please help me check what when wrong. It only shows on etherscan. Those addresses are nolonger showing on my metamask. My ICO will use metamask but if this beta one is so unreliable we would rather abondon this ethereum network.

Your withdrawal request has been successfully processed. 

Withdrawal details: 
Instrument: Ethereum 
Requested amount: ETH 0.92759300 
Commission: ETH 0.01000000 
Total to be sent: ETH 0.91759300 
Transaction hash: 0x4532877eda59a738ac82bd8eb97e11a5ad6b69c6ca95b30eeaeec5af866e39cf
--

**Comment by bdresser** [comment] 2018-11-05 19:56
@besiwims please email support@metamask.io and we'll try to help there

**Comment by tomtattan** [comment] 2021-04-17 10:24
hello I seem to be having the same problem , but it was when I bought elongate from pancake swap the next day my account was different and I cannot see any of my tokens … I had to even reconnect my ledger , and now I cannot even see the contents of my ledger wallet or the metamask wallet

**Comment by tobbtechnologies** [comment] 2021-04-17 14:33
Metamask never refunded me my funds() I lost due to their bug in the code.  I need my money
![image](https://user-images.githubusercontent.com/20172628/115116586-8cbe6500-9f9a-11eb-88c7-da058860b1b5.png)

**Comment by leotuna** [comment] 2021-10-02 13:34
It also happened to me.

This is a scary bug and this issue should not be closed.

**Comment by richardsonn09** [comment] 2022-01-30 21:31
@jazzinuf 
@leotuna 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by AgCaliva** [comment] 2022-04-28 01:05
@danfinlay hi sory this was solved?
