### ISSUE TITLE
Build error on Windows10

### ISSUE THREAD

**Issue by wanglonghong** [MetaMask/metamask-extension#10748] opened 2021-03-29 09:21 UTC
I am trying to build Metamask9.2.1 on windows 10 using Nodejs 14.15

yarn run v1.22.4
$ lavamoat development/build/index.js
(Error#1)

  Error#1: LavaMoat - required package not in whitelist: package "@gulp-sourcemaps\map-sources" requested "through2" as "through2"
     at requireRelative (LavaMoat/core/kernel:414:15)
    at requireRelativeWithContext (LavaMoat/core/kernel:366:16)
    at Object.eval (~\work\metamask-extension\node_modules\@gulp-sourcemaps\map-sources\index.js:4:15)
    at internalRequire (LavaMoat/core/kernel:353:25)
    at requireRelative (LavaMoat/core/kernel:394:27)
    at requireRelativeWithContext (LavaMoat/core/kernel:366:16)
    at Object.eval (~\work\metamask-extension\node_modules\gulp-sourcemaps\index.js:7:15)
    at internalRequire (LavaMoat/core/kernel:353:25)
    at requireRelative (LavaMoat/core/kernel:394:27)
    at requireRelativeWithContext (LavaMoat/core/kernel:366:16)

 - OS: WIndows 10
 - MetaMask Version: 9.2.1
 - Node 14.15
 - Yarn 1.22.4

**Comment by cd3vane** [comment] 2021-04-25 00:04
I am having this same error trying to build it currently were you ever able to get around this?

**Comment by chirag64** [comment] 2021-05-16 06:56
Facing the exact same issue on Windows 10 using node v14.15.1. Any update from dev team would be great as this stops contributors from taking part (though am curious how the dev team isn't facing this issue, unless this is specific to Windows 10)

**Comment by paranoiks** [comment] 2021-05-28 10:06
I have the same issue on Windows 10 using Node 14.17

**Comment by sunshasha** [comment] 2021-06-11 09:21
I am having this same error trying to build it currently were you ever able to get around this?

**Comment by paranoiks** [comment] 2021-06-11 09:23
I installed Ubuntu on a VM and built the files in there

**Comment by jaewonha** [comment] 2021-06-18 05:21
any progess?

**Comment by HappyCodingLover** [comment] 2021-06-26 02:39
I did meet same error like this.

**Comment by danjm** [comment] 2021-06-27 23:08
Their is a bug we need to fix in our build system. Before we get the fix merged, you might find that the code change on this branch resolves the issue: https://github.com/MetaMask/metamask-extension/compare/lavamoat-dev-optional?expand=1

**Comment by HappyCodingLover** [comment] 2021-06-28 01:05
@danjm Is the link above correct one?

I can't find anything helpful there.

**Comment by seniordev21** [comment] 2021-06-28 05:00
> There is a bug we need to fix in our build system. Before we get the fix merged, you might find that the code change on this branch resolves the issue: https://github.com/MetaMask/metamask-extension/compare/lavamoat-dev-optional?expand=1

I can't run your method.
please explain me in details.
Thanks.

**Comment by danjm** [comment] 2021-06-28 11:20
@HappyCodingLover @seniordev21

I updated the comment.

If that code change is applied locally, you should be able to build MetaMask by running `yarn start`

**Comment by chirag64** [comment] 2021-06-29 16:59
@danjm 

I switched to the `lavamoat-dev-optional` branch on my local and ran `yarn start`. The command does run successfully and I can see a list of files getting reloaded on the terminal.

But how do I run this dev build on my browser? If I make code changes and want to view them in my browser, how can I do that?

Sorry if this is a stupid question, I couldn't find this info on the README file.

**Comment by ysy717324540** [comment] 2021-09-30 03:28
I make the same mistake by running "yarn dist"

> There is a bug we need to fix in our build system. Before we get the fix merged, you might find that the code change on this branch resolves the issue: https://github.com/MetaMask/metamask-extension/compare/lavamoat-dev-optional?expand=1
> 
> Edit: this will allow you to build MetaMask by running `yarn start`

**Comment by jesseharte** [comment] 2022-03-08 18:00
I also face this issue for `yarn build`, while `yarn start` reports a _Uncaught ReferenceError: LavaPack is not defined_. I found that this is caused by the a _Failed to load resource: net::ERR_FILE_NOT_FOUND runtime-cjs.js_, but I believe that this file should have actually been created during the build: https://github.com/MetaMask/metamask-extension/blob/ac9f263e1a7148fae10fa100f25b5ab52c079e46/development/build/static.js#L169

**Comment by HowardBraham** [comment] 2022-11-30 23:19
Is anyone still having this problem?  After PR https://github.com/MetaMask/metamask-extension/pull/16550 was merged to `develop` today, I think there are no known problems with `yarn start` or `yarn dist` on Windows.

We should close this issue soon if nobody reports anything.

**Closed** 2022-12-23 08:59 UTC
Labels: area-buildSystem, needs-triage, contributor experience

**Comment by thoth-seshat** [comment] 2023-02-08 02:11
@HowardBraham I'm having that issue but I'm on Mac with yarn 3 and node v16

**Comment by HowardBraham** [comment] 2023-02-10 05:56
@thoth-seshat Are you up to date on the `develop` branch?  Are you running `yarn start`?  Have you tried deleting your `node_modules`?

**Comment by AnnaBarotova** [comment] 2023-05-18 15:09
Hi!
I faced this issue on win 10, node 18.16, yarn 3.2.4... I'm up-to-date, node_modules were deleted.

**Comment by HowardBraham** [comment] 2023-05-18 16:29
@AnnaBarotova Try a `git clone` to a brand new folder?  I'm just trying to figure out what might be going on.
