### ISSUE TITLE
Internal JSON-RPC error on Ropsten testnet.

### ISSUE THREAD

**Issue by kgh2927845** [MetaMask/metamask-extension#4504] opened 2018-06-05 16:59 UTC
Metamask doesn't work  at all on Ropsten testnet. I can't transfer any balance to anyone.
Even though some eth amounts are in my wallet, Metamask shows me 0 eth balance in it whenever trying to transfer some amount so that transactions are failed now.
![capture](https://user-images.githubusercontent.com/25010771/40990917-8fba1a7e-68f2-11e8-95d4-788b9b7b76eb.PNG)

**Comment by evansjohnson** [comment] 2018-06-05 17:36
I have also seen this error today.  MetaMask seems to sometimes report the correct balance, sometimes report 0 for both ETH and a token, although this happens without this error appearing as well.  The balances show up as expected on Etherscan Ropsten.

**Comment by bdresser** [comment] 2018-06-06 22:26
@kgh2927845 @evansjohnson transactions on Ropsten are working fine for me – I believe this may have been fixed by #4486. 

could you try again and provide some more detail if you're still having trouble?

**Comment by HigyedArnold** [comment] 2018-06-09 16:52
Same issue here as well.
![error](https://user-images.githubusercontent.com/19395356/41194069-91b02e20-6c1e-11e8-889c-563b0729effc.PNG)

**Comment by HigyedArnold** [comment] 2018-06-09 17:13
Issue solved! The problem is: I used a contract function with <contractInstance>.<function>.call(<parameters>) in order to get the object,string or boolean what that function was returning. The regular call, <contractInstance>.<function>(<parameters>) always returns the transaction receipt.

**Closed** 2018-06-11 16:46 UTC
Labels: N02-needsReproduction
