### ISSUE TITLE
Pushing the "Cancel Transaction" button resubmits prior transactions

### ISSUE THREAD

**Issue by jaschro** [MetaMask/metamask-extension#8594] opened 2020-05-14 16:59 UTC
Here's what happened: 
1. I set the Gwei and gas limit low. 
2. Transaction does not send.  At this point, I should have been able to cancel the transaction.  However, pushing the cancel transaction button did nothing. 
3. I tried to submit new transactions, this time with a higher gwei and gas limit.  But these transactions also got stuck behind the first transaction. 
Three days later the transactions were still stuck. 
At this point, I somehow managed to cancel the transactions, increasing the fees associated. 
However, at times, hitting the cancel transaction button would resubmit other, prior, previously canceled transactions. 

This was on Windows 10 using Chrome. 
I was able to use the MetaMask client for Android and that sent transactions properly. 

I solved the problem by removing the MetaMask extension from Chrome.  I then reinstalled the MetaMask extension with my 11 word string.  That must have cleared the cache of bad transactions. 

**Describe the bug**

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment] 2021-01-12 13:38
Thanks for the report! Are you still experiencing this problem? We fixed a few bugs since you submitted this issue that could result in a transaction getting stuck as "Pending".

**Comment by jaschro** [comment] 2021-01-12 16:40
Hard to say, but I did have a transaction submitted twice a few days ago.

Also, I'd love to see the failure rate of Metamask transactions.  My own
experience is that about 5% of transactions fail, based on my experience of
about 500 transactions over the last year.

This should be a public dashboard.

**Comment by Gudahtt** [comment] 2021-01-13 14:53
Thanks for following up! I'm going to close this for now, as there's not enough information here to investigate further. But we are still looking into various bugs that sound similar to this (e.g. #9928), so I hope we can solve whatever the root problem was here if it isn't solved already. Please let us know if you encounter something like this again, and we can dig in a bit further to ensure we identify the cause.

>Also, I'd love to see the failure rate of Metamask transactions.  My own experience is that about 5% of transactions fail, based on my experience of about 500 transactions over the last year.
>
>This should be a public dashboard.

We don't yet have reliable metrics for this, but I agree this does sound useful! We might be able to provide a public dashboard at some point.

**Closed by Gudahtt** 2021-01-13 14:53 UTC
Labels: N02-needsReproduction, S2-normal, T00-bug
