### ISSUE TITLE
Metamask displays legacy window.web3 alert even after removing the same from the code.

### ISSUE THREAD

**Issue by Vivek205** [MetaMask/metamask-extension#10408] opened 2021-02-09 06:47 UTC
**Describe the bug**
I have recently migrated our web application to the new web3 API based on the [`Provider Metamask Guide`](https://docs.metamask.io/guide/provider-migration.html).
But whenever I open the website, I see a warning message in the metamask stating 
`We noticed that the current website tried to use the removed window.web3 API. If the site appears to be broken, please click here for more information.`

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to https://publisher.singularitynet.io/
2. Click on Metamask chrome extension
3. See the warning message in the metamask screen.

**Expected behavior**
There should not be warning message in the Metamask because we have removed the legacy web3 code

**Screenshots**
<img width="423" alt="Screenshot 2021-02-09 at 12 07 59 PM" src="https://user-images.githubusercontent.com/26110173/107325826-709cd400-6ad0-11eb-923d-aae7a7feb52e.png">

**Browser details (please complete the following information):**
 - OS: Mac OS - Catalina
 - Browser: Chrome Version 88.0.4324.146 (Official Build) (x86_64)
 - MetaMask Version: 9.0.4

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment] 2021-02-09 14:10
Thanks for the report! This looks like a duplicate of #10356, which was just fixed and is included in v9.0.5, the release we are currently preparing.

The mistake we made was triggering this popup when only `web3.currentProvider` is used (many versions of `web3.js` use this internally for example). That property should be safe to use - it's deprecated, but not removed. Any other property should trigger that warning however.

I'd suggest auditing your codebase and the libraries that you are using, to look for any instances of `web3` usage you can find. If you only find uses of `web3.currentProvider`, then a solution is on the way!

**Closed by Gudahtt** 2021-02-09 14:10 UTC

**Comment by noorhashem77** [comment] 2023-01-02 05:51
@Gudahtt we can no longer use any kind of web3 mention in our code?

**Comment by Gudahtt** [comment] 2023-01-04 16:11
@noorhashem77 You can bring your own web3 library, and you should not get this warning. This warning only appears when you try to use the `web3` global without setting it to something first. It has been years since we've injected that `web3` global automatically, you have to set it yourself in your dapp.
