### ISSUE TITLE
Chrome extension causes all browser tabs to close when confirming a transaction; transaction doesn't get confirmed

### ISSUE THREAD

**Issue by shadoweye2018** [MetaMask/metamask-extension#11556] opened 2021-07-18 01:22 UTC
Describe the bug
When I confirm a transaction on metamask, rather than it being confirmed, all instances (windows+tabs) of my browser immediately close and the transaction does not get confirmed.

Steps to reproduce (REQUIRED)
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

Attempt any metamask crypto transaction (mine have been Augur related)
Choose a gas fee
Submit it
Browser closes, transaction has not been submitted
Expected behavior
Transaction is submitted.

OS: windows 10 pro
Browser: Chrome
MetaMask Version: Current chrome extension

**Comment by AlgernonOne** [comment] 2021-07-18 08:05
I'm having the same problem.  I'm using version 9.8.0 on a Macbook Air M1 Chrome browser.  No problems in last 4 months, but the extension started shutting down Chrome today. Happens when I confirm a transaction or sign.  When I relaunch Chrome and open the extionsion, password sign-in pops up. The transaction completed but there's no record in the Activity tab. When it's a Signing task, this never goes through.  Any advice?

**Comment by shadoweye2018** [comment] 2021-07-18 08:22
same problem on last two days. we only need waiting official fix it.

**Comment by danjm** [comment] 2021-07-20 11:49
duplicate of #11554

**Closed by danjm** 2021-07-20 11:49 UTC
