### ISSUE TITLE
[Bug]: Token Icons are not loaded when I change networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15593] opened 2022-08-15 16:26 UTC
### Describe the bug

**Problem:** while having a couple of tokens loaded (with their token image), if I change networks and go back to the network I was, I see that the token icons are not correctly loaded anymore, and blockies is loaded instead.

https://user-images.githubusercontent.com/54408225/184674996-c9a158bf-7dc5-4aca-ae94-d702969162fe.mp4

### Steps to reproduce

1. Unlock MM
2. Load a couple of ERC20 tokens (DAI, USDC..)
3. See token images are there
4. Change network
5. Change back to mainnet
6. See token images are now displayed as blockies

### Version

10.20.0

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment] 2022-09-12 15:23
And not sure if it's the same issue but, Testnet tokens are not available (displayed as a white circle), only when I click Send I can see a Blockies/Jazzicon img

![image](https://user-images.githubusercontent.com/54408225/189693047-60ad66d3-3385-4096-81ee-84df971d1f65.png)


![image](https://user-images.githubusercontent.com/54408225/189693084-d5fca5af-387d-4d25-85aa-e207078aae06.png)

**Comment by danjm** [comment] 2022-09-13 13:01
@seaona I can't reproduce follow the basic steps. Is this still happening for you? Is it happening on all networks and with all tokens

https://user-images.githubusercontent.com/7499938/189907720-4be06158-53bc-4248-97bb-e8b79f3f4ce4.mp4

?

**Comment by seaona** [comment] 2022-09-13 14:30
@danjm I cannot reproduce the description steps anymore. Token icons are displayed fine after changing networks.
The only issue I still see is the one mentioned on the comment above (which might be a different one)

**Comment by danjm** [comment] 2022-09-13 14:39
@seaona That is a separate issue. Can you create a separate ticket for that and then close this one?

**Comment by seaona** [comment] 2022-09-13 14:51
I close this issue as per above comments.

Separate issue can be found [here](https://github.com/MetaMask/metamask-extension/issues/15808). It is not exclusive to 10.19.0 version.

**Closed** 2022-09-13 14:52 UTC
Labels: type-bug, rc :package:
