### ISSUE TITLE
Metamask gone blank whitescreen on firefox browser on my PC

### ISSUE THREAD

**Issue by Packagefather** [MetaMask/metamask-extension#11445] opened 2021-07-02 15:16 UTC
metamask just went blank white on firefox on my windows. i have tried closing browser and opening again, no way, shut down pc and boot again, no way, i do not have the recovery phrase, so uninstalling and installing is not an option

**Comment by jasonzhouu** [comment] 2021-07-04 16:48
[How to Reveal Your Seed Phrase / Secret Recovery Phrase](https://metamask.zendesk.com/hc/en-us/articles/360015290032-How-to-Reveal-Your-Seed-Phrase-Secret-Recovery-Phrase)

**Comment by danjm** [comment] 2021-07-08 10:42
Duplicate of https://github.com/MetaMask/metamask-extension/issues/11245

**Comment by danjm** [comment] 2021-07-08 10:44
@Packagefather You might be able to extract your vault data, and therefore your recovery phrase, by following this tutorial: https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data

**Closed** 2022-04-19 00:38 UTC
