### ISSUE TITLE
Is MetaMask down or just me?

### ISSUE THREAD

**Issue by marsrobertson** [MetaMask/metamask-extension#6519] opened 2019-04-26 11:41 UTC
Tried two different computers, on both MetaMask keep hanging:

<img width="367" alt="Screenshot 2019-04-26 at 12 40 39" src="https://user-images.githubusercontent.com/44369284/56805327-96d08180-6820-11e9-9eea-0a3be5511c8a.png">

**Comment by mouragio** [comment] 2019-04-26 11:42
Same here...

**Comment by fateevv** [comment] 2019-04-26 11:47
The same problem.

**Comment by wnz99** [comment] 2019-04-26 11:59
same, I had to downgrade to 6.3.2.

**Comment by jeschild1** [comment] 2019-04-26 12:01
same here. it was working fine several hours ago... and then kaput!

**Comment by marsrobertson** [comment] 2019-04-26 12:04
@wnz99 how do you downgrade?

Manually `Load Unpacked Extension`?

https://github.com/MetaMask/metamask-extension/blob/develop/docs/add-to-chrome.md

**Comment by wnz99** [comment] 2019-04-26 12:05
@marsrobertson yes, I did it manually. Make sure you have your private keys to restore the accounts.

**Comment by tlatldms** [comment] 2019-04-26 13:46
Same here! Loading Forever

**Comment by Droopy78** [comment] 2019-04-26 13:55
Currently, I'm only seeing spotty Metamask uptime on Rinkeby and Mainnet. Browser doesn't matter, and tried from multiple computers and locations. Have to completely remove metamask from Firefox and Chrome, and then reinstall to get rid of loading indicator.  Now the loading indicator sometimes clears after minutes, so maybe it's a high load/traffic issue (currently I'm back to 10+ mins of waiting).

**Comment by robsecord** [comment] 2019-04-26 13:58
Same issue - forever loading..  Chrome, Brave, Firefox..  
Console for the MM window shows:
<img width="639" alt="Screen Shot 2019-04-26 at 9 57 36 AM" src="https://user-images.githubusercontent.com/1431523/56812912-e3f52900-6809-11e9-985f-520574bcb3f3.png">

**Comment by mouragio** [comment] 2019-04-26 14:09
I have completely removed metamask from Chrome and reinstalled/reconnected. 
Now its working again...

**Comment by junzhli** [comment] 2019-04-26 14:51
Here is the point I found out:
The website which serves contract's method known signature is down now...
It makes Metamask hanging until the server response with error code 503 (service unavailable)

![Screen Shot 2019-04-26 at 10 48 43 PM](https://user-images.githubusercontent.com/4001697/56816125-7979d280-6875-11e9-9813-1557ee4e2cea.png)

Any idea to resolve this issue? Very annoying...

**Comment by perich** [comment] 2019-04-26 15:42
Yup, looks like their entire site is down (for me at least). 

`curl https://www.4byte.directory`

Interestingly, some of my teammates in different regions can still use MetaMask. But for several of us, it's stuck on the spinning pinwheel because of this broken dependency.

**Comment by tlatldms** [comment] 2019-04-26 15:47
@wnz99 Hello. How did you downgrade it? I cannot find metamask-plugin folder. I downloaded 6.3.2 version from its commit log but cannot fix it to be uploaded on chrome extension.

**Comment by wnz99** [comment] 2019-04-26 16:46
@tlatldms get the zip from there: https://github.com/MetaMask/metamask-extension/releases/tag/v6.3.2

Unzip it.

Then follow instructions at https://github.com/MetaMask/metamask-extension/blob/develop/docs/add-to-chrome.md

You just have to select the folder where you have unzipped the extension files.

Remember to backup your private keys first and disable the current add-on first.

**Comment by topocount** [comment] 2019-04-26 16:49
@marsrobertson it's not down it just takes a _really_ long time to resolve function information if it's not stored on the parity function registry. I've logged #6514 to address the root cause of this issue.

**Comment by owocki** [comment] 2019-04-26 16:55
i'm having the same issue here too https://github.com/MetaMask/metamask-extension/issues/6520

**Comment by danlipert** [comment] 2019-04-26 17:00
I also observed this today - after disabling and re-enabling the extension in chrome a few times, I was able to get it to work

**Comment by frncscdf** [comment] 2019-04-26 17:45
Same here.

**Comment by loriopatrick** [comment] 2019-04-26 18:22
Is there a community QA to green light releases? https://github.com/MetaMask/metamask-extension/issues/6525

**Comment by bdresser** [comment] 2019-04-26 19:10
This is fixed in 6.4.1, live on Firefox already, should be live on Chrome momentarily

**Comment by perich** [comment] 2019-04-26 20:45
thanks for the quick turnaround on a Friday

**Comment by marsrobertson** [comment] 2019-04-26 22:24
The other day (DEVCON 3) I said "thank you' to MyEtherWallet guys.

Of course, they don't have any analytics but my rough estimate that they move $10m daily orders of magnitude (could be $5m, could be $50m, could be $150m)

I estimate this not-so-tested release was similar level.

### Post mortem

Enable **BETA** and **NIGHTLY** channel. 

Don't roll out relatively important and well-established in the community _(real money on the line)_ software to 1m+ people... 

# 😇

_(talk is cheap)_

**Comment by bdresser** [comment] 2019-04-26 23:12
Hey folks, still `pending review` on Chrome. It usually doesn't take this long – seems like they've added an additional review step.

Firefox has updated and if you need this on Chrome in the meantime you can v6.4.1 from our [Releases page](https://github.com/MetaMask/metamask-extension/releases). Sorry for the trouble and thanks your for patience.

**Comment by onxy2019** [comment] 2019-04-27 11:44
how can I reconnect to smart contract after reinstalling Metamask?

**Comment by bdresser** [comment] 2019-04-29 20:10
Chrome is up-to-date. Closing this via https://github.com/MetaMask/metamask-extension/pull/6521

We're aware of function names showing up as `[undefined]` which will be fixed in https://github.com/MetaMask/metamask-extension/pull/6524

@onxy2019 I'm not sure I understand your question – reach out to support@metamask.io and we'll help you over there!

**Closed by bdresser** 2019-04-29 20:10 UTC
