### ISSUE TITLE
Optimize against hitting Infura

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3950] opened 2018-04-10 17:27 UTC
Going to consist of many things, please add them here.

**Comment by danfinlay** [comment] 2018-04-10 17:53
The largest win we could hope for is to stop block polling when nothing is using it.

**Comment by whymarrh** [comment] 2019-02-07 01:32
Closing this as a duplicate of #3143, feel free to re-open if needed

**Closed by whymarrh** 2019-02-07 01:32 UTC
