### ISSUE TITLE
How to integrate the estimate gas API in order to get accurate gaslimit number in Mantle Mainnet

### ISSUE THREAD

**Issue by zengbing15** [MetaMask/metamask-extension#23533] opened 2024-03-16 03:10 UTC
### What is this about?

The gas estimation on the Mantle Mainnet is currently inaccurate in MetaMask. 
for example: the tx does not follow the provided parameters, with a fixed gas limit of 400,000 regardless of the tx type.
<img width="938" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/40650475/20a0e292-5f22-4750-8551-29368034019e">

Our fee model is similar to Arbitrum's. We have noticed that when estimating gas on Arbitrum, there is an API that provides an appropriate number. We are unsure how we can integrate that API.
![image](https://github.com/MetaMask/metamask-extension/assets/40650475/e40ea205-0c07-4d1e-80c2-803e4c7c1b51)
![image](https://github.com/MetaMask/metamask-extension/assets/40650475/d6c124c1-c989-4150-a4ab-6f4107a34cb7)

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by bschorchit** [comment] 2024-03-21 16:23
> for example: the tx does not follow the provided parameters, with a fixed gas limit of 400,000 regardless of the tx type.

Hey @zengbing15, I'm not able to reproduce this issue (see screenshot below where I see a different gas limit in Mantle). Could you share more details or reproduction steps?
<img width="366" alt="Screenshot 2024-03-21 at 13 18 13" src="https://github.com/MetaMask/metamask-extension/assets/34968356/1e1010d3-6468-414c-9df9-e1259ec4cc29">

**Comment by zengbing15** [comment] 2024-03-22 10:41
Hi, thank you for your response, I have explained in another issue: https://github.com/MetaMask/metamask-extension/issues/23534#issuecomment-2014811221 please check.  @bschorchit

**Comment by bschorchit** [comment] 2024-03-29 20:44
Closing this in favor of https://github.com/MetaMask/metamask-extension/issues/23534

**Closed by bschorchit** 2024-03-29 20:44 UTC
Labels: external-contributor

**Comment by abdulmenan10** [comment] 2024-03-29 21:05
H hcyv
