### ISSUE TITLE
Invalid JSON RPC error due to undefined networkVersion in publicConfigStore

### ISSUE THREAD

**Issue by bumi** [MetaMask/metamask-extension#1538] opened 2017-06-04 15:57 UTC
I am currently developing an app around some random smart contracts using [ember.js](https://emberjs.com/) and the typical web3 stack.
Using MetaMask (3.7.4) I am randomly running into an  `Invalid JSON RPC response: {"id":1,"jsonrpc":"2.0"}` exception. 
After some debugging it turns out that for a [`net_version` RPC call](https://github.com/MetaMask/metamask-plugin/blob/8f9a230d8d2c8351cd325bddf3c2ca04f06c9619/app/scripts/lib/inpage-provider.js#L89) MetaMask returns `undefined` which results in an invalid JSON RPC response (the result must not be undefined). 
I am unsure if this is some kind of race condition as this error seems to be pretty random and sometimes it works - maybe the net_version request happens too early? 
But in any case I think the RPC calls should not return `undefined`.

### stack trace:
![invalid-rpc](https://cloud.githubusercontent.com/assets/318/26761663/352d78aa-4934-11e7-81e4-98125f31386d.png)

### RPC call + validation
![rpc-validation](https://cloud.githubusercontent.com/assets/318/26763193/c24c3b6c-494e-11e7-9bad-121e5b5db90c.png)

### net_version call in inpage.js
![networkversion-undefined](https://cloud.githubusercontent.com/assets/318/26763197/d66bb4e2-494e-11e7-843c-d694df6f059d.png)

**Comment by bumi** [comment] 2017-06-18 12:33
If this is a real issue I'd be happy to dig deeper but would need some hints as got stuck here and don't fully understand the whole config/initialization process yet. thanks.

**Comment by flyswatter** [comment] 2017-06-18 14:02
I'm pretty sure this is a duplicate of #1575, so the notes there will be a good starting point, sorry we don't have better docs for debugging yet, will soon, and we'll try to figure this one out soon on our end too.

**Comment by Zanibas** [comment] 2017-08-02 17:20
What's the status on this?

**Comment by bumi** [comment] 2017-08-06 19:23
@Zanibas there was some more discussion in #1575 which is not exactly the same but related. (see my comment there: https://github.com/MetaMask/metamask-extension/issues/1575#issuecomment-309418426)
what are your thoughts?

**Comment by kumavis** [comment] 2017-08-23 23:15
verified to be same as root issue of #1575

**Closed** 2017-08-28 18:01 UTC
Labels: L0-provider, P1-asap, T0-bug
