### ISSUE TITLE
[Bug]: fw: incorrect gas estimation on BSC when gasPrice is not explicitly supplied by the website

### ISSUE THREAD

**Issue by Snugface** [MetaMask/metamask-extension#20797] opened 2023-09-08 10:37 UTC
### Describe the bug

This is a duplicate of #20699 , as that one has been open for a week and is yet to receive any acknowledgment from the maintainers. And I am wondering if starting three exact same issues in a row, as some people are doing here, is the right answer to that.

MetaMask incorrectly estimates gas settings on BSC when no gas price is explicitly supplied by the website.
Likely the bug is only specific to BSC, though I haven't tried reproducing it on other chains.

### Steps to reproduce

1. Initiate transaction with a contract on BSC using web3.js without explicitly supplying any gas settings, like so:
`contract.methods.function(args).send({ from: address });`
2. Review gas settings automatically picked by Metamask, and observe that they are falsely reported as "suggested by site", while also being too low for the tx to go through
<details>
<summary>2. Screenshots</summary>

![MM gas bug bad1 Screenshot from 2023-09-02 14-43-20](https://github.com/MetaMask/metamask-extension/assets/17455618/9b00afc9-3a7c-4346-945e-f8701bf7ccf1)
![MM gas bug bad2 Screenshot from 2023-09-02 15-14-43](https://github.com/MetaMask/metamask-extension/assets/17455618/3a100025-abab-4639-a3a5-38a9600ed674)

</details>

3. Send transaction. It will fail with "transaction undepriced" error
4. Now, to avoid this bug one must manually supply gasPrice, for example: `contract.methods.function(args).send({ from: address, gasPrice: '3000000000' });`
5. Review gas settings again. Same contract, same function, same arguments. Same report from Metamask, that gas settings are supplied by the site. But **this time it is true**, and those gas settings are adequate
<details>
<summary>5. Screenshots</summary>

![MM gas bug good1 Screenshot from 2023-09-02 15-35-27](https://github.com/MetaMask/metamask-extension/assets/17455618/7fb3fc47-6fbf-4731-9f44-ba89060cfdac)
![MM gas bug good2 Screenshot from 2023-09-02 15-34-53](https://github.com/MetaMask/metamask-extension/assets/17455618/87ba6b2b-220e-4dae-b91e-4a202b87d815)

</details>

6. Send transaction. Transaction succeeds

### Error messages or log output

```shell
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":
{"code":-32603,
"data":{
"code":-32000,
"message":"transaction underpriced"
}}}'
```

### Version

10.34.3

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows, Linux

### Additional context

`web3.js` version `1.6.1`
RPC in use: https://bsc-dataseed2.binance.org:443 on website; https://bsc-dataseed1.binance.org:443 in wallet. Likely the same behavior is present on others, but I tested with these.
Same behavior is observed with payable and non-payable contract functions. Behavior only first appeared about 3-5 days back. So far every user who reported this behavior is a Metamask user.
No changes were made to the website codebase recently(for many weeks). So the bug is being caused either by updates in Metamask or in BSC nodes.

**Comment by brad-decker** [comment] 2023-09-11 14:36
Duplicate of #20699 , opening multiple issues of the same content is not the intended way to get our attention...If anything it undermines it as it creates more noise.

**Closed by brad-decker** 2023-09-11 14:36 UTC
Labels: type-bug

**Comment by Snugface** [comment] 2023-09-11 18:43
> Duplicate of #20699 , opening multiple issues of the same content is not the intended way to get our attention...If anything it undermines it as it creates more noise.

Apologies for complicating things. And thanks for checking-in. I just wanted to get some sorta acknowledgement, and didn't resist the temptation to post a dupe.
But even so - you've commented on the dupe and closed it. What about the actual bug and the original issue?
Still no real clarity or a comment that's actually about the issue. Is it indeed a bug? Is it something from Metamask's recent update? And a couple more questions, but you see what I mean.
What's up with that actual issue?

**Comment by brad-decker** [comment] 2023-09-25 21:13
@Snugface i'm opening a PR that references this issue, but it only helps with the formatting of the error thrown not the error itself. Just wanted to make sure I don't provide any false hope for a prompt resolution ☹️  BUT hopefully this will allow us to get actual stack traces in our error reporting tool that will further our efforts to resolve this (and other) issues.
