### ISSUE TITLE
Hidden tokens re-appear 

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5055] opened 2018-08-13 18:18 UTC
To repro:
* Hide a token that was auto-detected
* Switch accounts
* Switch back to original account, token is visible again.
Would expect token to remain hidden.

Might need a UX for "clearing" the list of hidden tokens? Would resetting the account do the trick?

**Comment by brad-decker** [comment] 2020-07-22 19:42
This issue was reported by another user through zendesk. While it is operating as intended a couple of things made this more onerous:
1. Token value representation in the UI was truncated at 3 zeroes so having 0.0001 of a token would result in 0.000 showing and thus the "feature" of adding tokens with values is easily perceived as a bug. 
2. We should allow users to hide tokens they no longer want to interact with, such as when they have spent all but a very insignificant amount of token.

I'd like to re-open this issue as a way of tracking the updates to resolve those two items.

**Comment by Gudahtt** [comment] 2020-08-07 20:24
>1. Token value representation in the UI was truncated at 3 zeroes so having 0.0001 of a token would result in 0.000 showing and thus the "feature" of adding tokens with values is easily perceived as a bug.

This has been resolved by #9056, so the only outstanding problem is the one originally reported here (tokens with non-zero balance re-appearing after being hidden).

**Comment by Gudahtt** [comment] 2020-08-07 20:29
I'm re-labelling this as a bug, because this behaviour seems both unexpected and confusing.

If we do want to make it impossible to hide tokens with a non-zero balance, the _least_ we could do is not show the "Hide" button. But I'd strongly prefer letting users choose to hide tokens even with a balance. It's not uncommon to have a positive balance of a token you don't care about.

**Comment by Alko89** [comment] 2020-08-10 07:24
I have a bunch of tokens with non zero balance. It seems only some specific tokens actually reappear (like OMG I reported in #9145). While most of the tokens I actually care about stay hidden until I add them manually.

**Comment by Gudahtt** [comment] 2020-08-11 15:09
@Alko89 This behavior should only affect tokens listed here: https://github.com/MetaMask/eth-contract-metadata/blob/master/contract-map.json

Those are the tokens we check for by default.

**Comment by Alko89** [comment] 2020-08-12 09:53
A solution might be to be able to blacklist a token that is on the list.

**Comment by sleazyp** [comment] 2020-11-07 01:14
I have at least a dozen old token accounts that are no longer used even a couple made with the wrong contract number With 0 token balance. The list is so long I have to scroll down to see some of my used token accounts! Getting really annoying. All it would take is a setting that says keep hidden token hidden when toggled on.

**Closed** 2020-12-08 20:38 UTC
Labels: S3-low, T00-bug
