### ISSUE TITLE
Internal JSON-RPC error -32603 for big contract on mainnet

### ISSUE THREAD

**Issue by yann300** [MetaMask/metamask-extension#3117] opened 2018-01-29 09:16 UTC
Just posting this here cause this error pops up while deploying big contract on mainnet from remix. 
Not sure it is completely related to metamask though.

`Invalid JSON RPC response: {"id":858,"jsonrpc":"2.0","error":{"code":-32603}}`
comment from user : 
"I managed to deploy small contracts on mainnet and it's fine, then i tried a longer contract on mainnet it fails while, the exact same code is fine on Ropsten and Rinkeby"

**Comment by danfinlay** [comment] 2018-01-29 18:34
What version of MetaMask are you on?

**Comment by yann300** [comment] 2018-01-29 18:44
`3.13.7`
seems to work when a mainnet `Custom RPC server` is setup

**Comment by danfinlay** [comment] 2018-01-29 19:15
This *might be* fixed later today, let us know tomorrow if you could if this is still happening.  Has to do with a new REST API we're using with Infura.

**Comment by kivutar** [comment] 2018-01-30 07:13
`3.13.8`
I'm getting the same kind of error when deploying a contract.
I suspect that the issue comes from infura too.
It happens 3 out of 4 times.

**Comment by danfinlay** [comment] 2018-01-30 16:44
To isolate this, we could really use strong reproduction steps. That would be either the contract code that you can't deploy, or the exact request that is throwing this error.

To copy the request:

1. Open the background inspector as described [here under "Background Logs"](http://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue).
2. Click the `Network` tab.
3. Reproduce the issue.
4. Look for a red item in the network list.
5. Right-click that item and click `Copy as cURL`
6. Paste that result either here or to us in an email to support@metamask.io

**Comment by danfinlay** [comment] 2018-01-30 19:13
Alright, Infura believes they've found the root of this problem, and say it should be fixed now!

If anyone can confirm this isn't fixed, I will re-open.

**Closed by danfinlay** 2018-01-30 19:13 UTC
Labels: P1-asap, T0-bug

**Comment by rawadrifai** [comment] 2018-02-02 01:15
Not fixed yet.. I'm running into the same issue.

**Comment by sameepsi** [comment] 2018-02-02 15:35
Still happening with me

**Comment by danfinlay** [comment] 2018-02-02 15:58
I believe this is a duplicate of #3140.

**Comment by ysoufian** [comment] 2018-02-03 05:17
Getting the same error for a very simple contract 
`pragma solidity ^0.4.6; contract Person{}`

**Comment by jtakalai** [comment] 2018-02-27 13:12
Getting that error when trying to open debugger. In Remix, open debugger tab, enter block number and tx, press Play. Get `Invalid JSON RPC response: {"id":1763,"jsonrpc":"2.0","error":{"code":-32603}}`

**Comment by yuhengzhou** [comment] 2018-03-08 04:39
I got error "Invalid JSON RPC response: {"id":3,"jsonrpc":"2.0","error":{"code":-32603}}"  when I call following function.

           web3.personal.unlockAccount('0x4DbA61ebb5892778F6C31Af8948C9C73930b093F', 'xxxxx', 30, function (err, rt) {
                console.log(err);
               .....
            });

**Comment by danfinlay** [comment] 2018-03-08 18:56
This error code can be thrown for a variety of reasons, so if you're getting this error, please open a fresh issue with specific reproduction steps, including the system you're on, and the browser you're using, and we'll try to debug this when we're able to.
