### ISSUE TITLE
Asset details links to Etherscan instead of configured Block Explorer URL

### ISSUE THREAD

**Issue by GibsDev** [MetaMask/metamask-extension#10523] opened 2021-02-25 22:15 UTC
**Describe the bug**
Asset sub menu links to Etherscan instead of configured Block Explorer URL

**Steps to reproduce**

1. Configure BCS network with Block Explorer URL https://bscscan.com/
2. View an account while on the BSC network
2. Click on a non BNB asset
3. Click the menu dots in the top right
4. It says view on Etherscan and opens the browser to etherscan/token/<token address>

Generates a link: `https://etherscan.io/token/<token id>?a=<account address>`

**Expected behavior**
The link should use the configured Block Explorer URL: https://bscscan.com/
Generates a link: `https://bscscan.com/token/<token id>?a=<account address>`

**Screenshots**
![image](https://user-images.githubusercontent.com/5456226/109225154-e66c9500-778a-11eb-9691-700a273fee29.png)

**Browser details**
 - OS: Windows
 - Browser: Firefox Browser 86.0 (64-bit)
 - MetaMask Version: 9.0.5

**Comment by tmashuang** [comment] 2021-02-25 22:17
Duplicate of #10041

**Closed by tmashuang** 2021-02-25 22:17 UTC
