### ISSUE TITLE
Chrome extension 404 errors in developer console

### ISSUE THREAD

**Issue by jurjendevries** [MetaMask/metamask-extension#10690] opened 2021-03-22 15:39 UTC
**Describe the bug**
Chrome Developer console reports 3 404 issues's when using the metamask extension

DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/disable-console.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Steps to reproduce (REQUIRED)**

1. Go to Chrome > Menu > More Tools > Developer Tools (CTRL-SHIFT-I) > Console tab
2. Refresh a page. Didn't matter which page
3. See 404 errors in the console related to the extension ID nkbihfbeogaeaoehlefnkodbefgpgknn .

**Expected behavior**
I don't expect to get 404 errors. I guess it should be checked if those 3 javascript js.map are still needed and need a fix to the correct location or so. Or that a code cleanup is needed.

**Browser details (please complete the following information):**
 - OS / browser: Chrome OS 90.0.4430.19
 - MetaMask Version: 9.2.0

**Comment by tmashuang** [comment] 2021-03-22 19:26
Duplicate of https://github.com/MetaMask/metamask-extension/issues/7077

**Closed by tmashuang** 2021-03-22 19:26 UTC

**Comment by bdhaccess94** [comment] 2021-03-22 19:37
nkbihfbeogaeaoehlefnkodbefgpgknn shows this:
