### ISSUE TITLE
Cannot click on the custom rpc menu both on latest Chrome and Firefox

### ISSUE THREAD

**Issue by meow0703** [MetaMask/metamask-extension#2716] opened 2017-12-09 19:39 UTC
Please help check the CLOSED issue, the issue still happens, i cannot click on the custom rpc menu both on latest Chrome and Firefox
Chrome: Version 62.0.3202.94 (Official Build) (64-bit)
Firefox: 57.0.1 (64-bit)
OS: Ubuntu 17 (64-bit)
Ref: https://github.com/MetaMask/metamask-extension/issues/1267
Tons of thanks

**Comment by danfinlay** [comment] 2017-12-18 19:10
Are you maybe using multiple screens with multiple resolutions?

We've seen some users have issues with the extension pop-up where the clicks seem to register at the wrong location. This may be a browser bug, could you try clicking in other places, see if you get clicks registered at all?

**Comment by Kentoseth** [comment] 2018-01-06 03:33
I can confirm that this is a bug.

I have tested on the latest Chrome (63) & as I figured it may be a Chrome issue, I tested on the Brave browser as well.

@danfinlay I believe you may be right about it being a multiple-screen issue. If it is though, it is unique to this plugin only (I don't ever recall a pop-up issue occurring due to the browser or multiple-screens).

Please clarify if this `hack` is still applicable:

```

    Have the affected user visit chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/popup.html (this opens the popup in a browser window).
    Use the browser zoom commands to zoom out a few clicks. This is in the View menu. The zoom size on this tab should also affect the popup.
```

**Comment by Kentoseth** [comment] 2018-01-06 17:40
**Update 2**

I went ahead and attempted to mimic the 2-point instructions above by opening Metamask in a new window and zooming in/out (with and without page refresh) but the `Custom RPC` button does not work at all.

the only `Warning` I get is when opening the page for the plugin:
```
Warning: Accessing PropTypes via the main React package is deprecated, 
and will be removed in  React v16.0. Use the latest available v15.* prop-types 
package from npm instead. For info on usage, compatibility, migration and more, 
see https://fb.me/prop-types-docs
```

I also made sure to enable popups as well, but still nothing.

**Comment by tmashuang** [comment] 2018-01-15 18:56
Is this just for the Custom RPC button, or on all the clickable links and buttons? Closing in favor of #2767. Will reopen if this issue just specific for the Custom RPC button.

**Comment by Kentoseth** [comment] 2018-01-16 01:21
@tmashuang I can confirm that this issue only occurs with the Custom RPC button. All the others work fine.

Steps to reproduce:

1. Use Ubuntu 14.04 and/or Ubuntu 16.04
2. Download/Install latest Chrome/Chromium
3. Click on `Custom RPC`
4. Test on dual-monitor setup

**Comment by tmashuang** [comment] 2018-01-16 01:37
May I receive a gif/vid of the issue and resolution on each monitor to reproduce. I am running Ubuntu 16.04 on a VM and tested in three different resolutions and menu/title bar scales. Still allowing me to click Custom RPC to navigate to the settings and enter a RPC URL.

**Comment by Kentoseth** [comment] 2018-01-16 01:47
Okay so it's possibly an Ubuntu 14.04 issue. Can you test on Chromium using 14.04 ?

Really appreciate the effort here.

Thank you!

**Comment by tmashuang** [comment] 2018-02-26 21:26
I apologize for losing focus on this issue. I have testing the reproduction steps on Ubuntu 14.04 and still am able to click Custom RPC. Alternatively, you can navigate to the Settings screen to input a Custom RPC, since it is the screen that will navigate to it when clicking Custom RPC, in the three vertical lines icon in the top-right. Closing this issue.

**Closed by tmashuang** 2018-02-26 21:26 UTC
Labels: P2-sooner, T0-bug

**Comment by katkol** [comment] 2018-04-09 10:01
Hi,
I too have the same issue. I am using ubuntu 16.04, chrome and like to connect metamask to ganche. So, I am trying to use custom rpc option, but it didn't work. I attached a avi of it aswell.


[ubuntu-metamask-custom-rpc.zip](https://github.com/MetaMask/metamask-extension/files/1889361/ubuntu-metamask-custom-rpc.zip)

**Comment by Kentoseth** [comment] 2018-04-09 10:50
@katkol 

It will be better to upload the .avi file directly instead of the .zip format.

**Comment by katkol** [comment] 2018-04-09 10:57
@Kentoseth git don't allow to upload avi directly.

**Comment by danfinlay** [comment] 2018-04-09 13:39
@katkol please open a new issue, since it is probably a different cause tham the rest of this thread, and we don’t need to bother everyone who ever posted here to discuss it.
