### ISSUE TITLE
My account is Emptied Out and nobody answer me In Support team!

### ISSUE THREAD

**Issue by anushuiac** [MetaMask/metamask-extension#8507] opened 2020-05-04 04:33 UTC
**Describe the bug**
hello, I sent you an email yesterday and i did not get any answers.
my wallet is emptied out 2 days ago. i installed your extension and transferred some money from exchange , and sent some money to participate in a smart contract named ‘Doubleway’. I always use this smart contract, and haven’t seen such problem.
My address on etherscan is:
https://etherscan.io/address/0xc51fc8b64438ba244731fba6e1d0382bc5f53ea0
the last transaction is the one who emptied my wallet completely:
https://etherscan.io/address/0xb820e82f461530b511ba589865e2f5bcefd8a427
why this happened? and What should I do to get my money back.
I don’t know how can I Trust this wallet Again, you should give me instructions on how can i safe this account and get my money back.
Please answer me and Help

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: X mac
 - Browser :Chrome Version Version 81.0.4044.129 (Official Build) (64-bit)
 - MetaMask Version [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by dpazdan** [comment] 2020-05-04 19:32
Hi there,
It sounds like you may have installed a fake MetaMask extension but I'd like to review it more closely.  Can you provide me your MetaMask support case number?  I will review it immediately and reply directly within the case.

**Comment by anushuiac** [comment] 2020-05-04 19:53
Thank you!
somebody answered my question (RANDY). he said I might have exposed my seed phrase to others but I didnt. As I remembered the first time i installed the metamask extension, it didnt worked but I made an account and seed phrase was generated. simultaneously I installed another copy of that and removed the first one. I may be downloaded a wrong one. I cant remember.
The Support case numbers are 35259 and 35235.
My problem is that i'm participating in a project that is using this address. and maybe I will be receiving amounts of money in next days in that account with that number. How can I change the seed phrase without changing my account address?
As I Know there's no way to get that money back. because it is transferred to an unknown account and then cashed in exchange.

**Comment by ondratra** [comment] 2020-05-05 12:30
Also, consider the possibility that the problem is not within Metamask -> your computer may be compromised. You should reinstall your OS, change passwords, etc. to be absolutely sure your system is clean before using cryptocurrency software wallets again. 

To prevent (the most of) further software-based hacks, get Trezor, Ledger, or other hardware wallets from respected manufacturers. ;-)

**Comment by tmashuang** [comment] 2020-05-06 01:11
Closing since support seems to be handling this.

**Closed by tmashuang** 2020-05-06 01:11 UTC
Labels: N07-needsSupport
