### ISSUE TITLE
Message: Cannot read property

### ISSUE THREAD

**Issue by Bild96** [MetaMask/metamask-extension#8808] opened 2020-06-15 01:18 UTC
I reload the browser twice , reboot the system once ( still same error message )

**OS Ubuntu 20.04 LTS
Brave Browser Version 17.67**

![Screenshot from 2020-06-15 02-50-39](https://user-images.githubusercontent.com/52472445/84609313-d2ac2780-aeb6-11ea-92fa-4875c51dd75f.png)
![Screenshot from 2020-06-15 02-49-50](https://user-images.githubusercontent.com/52472445/84609317-d3dd5480-aeb6-11ea-925c-ad4b2ff344e5.png)

**Comment by rekmarks** [comment] 2020-06-15 04:14
Hi @Bild96, can you please a few more details?

1. What version of the extension are you using? Chrome web store, the 8.0.0 release candidate, or a local build?
2. What were you doing when/before this error appeared?

Reinstalling the extension will likely resolve this problem, but keep in mind that you'll have to re-import your seed phrase and any other accounts you've added to MetaMask.

**Comment by Bild96** [comment] 2020-06-15 10:15
yes it's **8.0.0 release**
trying to connect my Etherum wallet at [Makersplace](https://makersplace.com/profile/)

**Comment by Gudahtt** [comment] 2020-06-16 18:14
From the looks of that stack trace, this is likely caused by an invalid pending signature request. At some point, a signature was requested for an account that does not exist. You're stuck in this broken state as long as this request is pending.

This is certainly a bug, but I can't figure out what it has to do with Makersplace. Did they request a signature at some point do you know? I was able to connect and place an offer without any signature request taking place. It's possible that MetaMask entered this broken state prior to you visiting Makersplace.

**Comment by Gudahtt** [comment] 2020-06-25 13:29
This should be fixed by #8833 

Thanks for the report! You can test that this is fixed by installing the latest version of the RC: https://github.com/MetaMask/metamask-extension/pull/8718#issuecomment-649120680

**Closed by Gudahtt** 2020-06-25 13:29 UTC
Labels: v8
