### ISSUE TITLE
[Bug]: Element (0:) out of place in sign typed data v4

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#21725] opened 2023-11-07 16:50 UTC
### Describe the bug

There is an element in the signature screen that is out of place or extra, the 0: below To: .

### Expected behavior

No extra elements or elements out of place should show.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/120041701/4aa727c5-f129-434d-a3f1-173aeb9ae209)

### Steps to reproduce

1. Open MetaMask and enter your password
2. Switch over to a test network (e.g.: Sepolia)
3. Head over to the test dapp: https://metamask.github.io/test-dapp/ and connect with current MM account
4. Scroll down to Sign typed data v4 and proceed to the signature screen
5. Notice the 0: below To: which should not show

### Version

11.5.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by danjm** [comment] 2023-11-08 13:00
@benjisclowder I see the same `0:` below the `To:` on v11.3.0

Is there a reason it should not be there on v11.5.0 even though it was there in the past?

**Comment by danjm** [comment] 2023-11-09 20:56
I think this is not a bug, but might be worth some design review.

I can see that this behaviour of showing `0: ` below the `To: ` existed as far backi as v10.18.0, before the redesign in recent months.

![Screenshot from 2023-11-09 16-21-57](https://github.com/MetaMask/metamask-extension/assets/7499938/b58d5eab-b35c-4a8f-a964-2f67b465d2c6)


I can also see that our unit tests expect this value to be in the DOM
![Screenshot from 2023-11-09 17-18-50](https://github.com/MetaMask/metamask-extension/assets/7499938/afbe2db0-2e6b-4170-bad0-cb9d5c9bcd33)

And that there are github issues going as far back as Apr 2020, without users complaining about that specific part of the screenshot https://github.com/MetaMask/metamask-extension/issues/8452

However, I need to spend more time with the spec to see what was intended? Should the UI show array indices or not? Because this has been this was in MetaMask for years, I am going to remove the bug label, but I will leave it as an enhancement for the Confirmation teams consideration.

If you come across any info that shows we are significantly deviating from the intentions of this screen, please do flag it, as we may then escalate in priority

**Comment by bschorchit** [comment] 2023-11-10 16:30
Thank you both for flagging that and also for identifying it's not a bug. We'll be taking this issue into account as we go through the signTypedData_v4 redesign

**Comment by bschorchit** [comment] 2024-06-17 23:46
This continues to be true for signatures redesign - I'll check if there's a reason to continue to show or not.

<img width="362" alt="Screenshot 2024-06-17 at 20 42 09" src="https://github.com/MetaMask/metamask-extension/assets/34968356/3010b402-e2bd-4ced-bea8-c0e1a1d7f999">
<img width="362" alt="Screenshot 2024-06-17 at 20 43 02" src="https://github.com/MetaMask/metamask-extension/assets/34968356/ffa5b850-78d0-4114-ac8d-ffcb7fb74d56">

**Comment by bschorchit** [comment] 2024-07-05 19:41
Closing this issue for now

**Closed by bschorchit** 2024-07-05 19:41 UTC
Labels: needs-research, ux-enhancement, team-confirmations
