### ISSUE TITLE
eth_requestAccounts not handling unapproved account correctly

### ISSUE THREAD

**Issue by paulbarclay** [MetaMask/metamask-extension#9854] opened 2020-11-11 17:15 UTC
1) Go to: https://etherscan.io/address/0xd9e1ce17f2641f24ae83637ab66a2cca9c378b9f#writeContract (the specific contract isn't important)
2) Ensure that, in Metamask, you have: (a) One account that's connected to etherscan.io (accountA) (b) One account that's NOT connected to etherscan.io (accountB)
3) Switch to accountB in Metamask
4) Hit the "Connect to Web3" button, select "Metamask" from the dropdown, click OK.

Etherscan now shows "Connected - Web3. But the address shown is the address for accountA, even though you have accountB selected.

I don't believe this is a bug with Etherscan's implementation - I've seen similar behaviour on our own sites. What should happen with "eth_requestAccounts" is that if Metamask is set to an account that is not connected, the approval popup should show up for the account that is requested, and no eth address should be returned if the approval popup is declined.

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome 86.0.4240.111 (Official Build) (x86_64)
 - MetaMask Version: 8.1.3

**Comment by paulbarclay** [comment] 2020-11-11 17:32
Also, as a related note, switching from an approved account to an unapproved account doesn't trigger the 'accountsChanged' event unless you approve the account. So there's no way for a site to detect switching from an approved account to an unapproved account (or between two unapproved accounts).

Per the documentation of accountsChanged, this isn't a bug, but I don't think that documentation matches what most people would expect the function to do when handling unapproved accounts. We can't expose the eth address of the unapproved account, but we need a way to detect that metamask has been changed to an unapproved account.

**Comment by mrwillis** [comment] 2020-11-11 22:44
Have the same issue. Essentially with the new update it is not possible to determine if an account is "connected" if the user switches to an unapproved account. Ideally the developer can push a notification to the user prompting them to approve the dApp.

**Comment by Gudahtt** [comment] 2020-11-13 21:41
This seems like a duplicate of https://github.com/MetaMask/metamask-extension/issues/8956

This has been the intended behavior since v8 as far as I know. Has something changed in the recent version?

**Comment by jacobcantele** [comment] 2021-01-05 20:42
Closing for now because this is expected behavior. It is a confusing UX pattern, but will be upgraded by other work. More info is available in the issue @Gudahtt linked above

**Closed by jacobcantele** 2021-01-05 20:42 UTC
