### ISSUE TITLE
TypeError: Cannot set property localStorage of #<Window> which has only a getter

### ISSUE THREAD

**Issue by xrdavies** [MetaMask/metamask-extension#7437] opened 2019-11-15 10:28 UTC
**Describe the bug**
Followed the instruction to 
```
yarn
yarn test
```

but it throw any error of `TypeError: Cannot set property localStorage of #<Window> which has only a getter`.

**To Reproduce**
1. yarn
2. yarn test
3. See error

**Expected behavior**
`yarn test` should work smoothly.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: OS X 10.14.6
 - NodeVersion: 10.16.3

Branch `MetaMask/Version-v7.2.3`

**Additional context**

```
$ yarn test:unit && yarn lint
$ cross-env METAMASK_ENV=test mocha --exit --require test/setup.js --recursive "test/unit/**/*.js" "ui/app/**/*.test.js"

/Users/ruix/workfolder/active/DeCert/metamask-extension/test/helper.js:44
  global.Promise = require('bluebird')
                    ^
TypeError: Cannot set property localStorage of #<Window> which has only a getter
    at Object.<anonymous> (/Users/ruix/workfolder/active/DeCert/metamask-extension/test/helper.js:44:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/ruix/workfolder/active/DeCert/metamask-extension/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/ruix/workfolder/active/DeCert/metamask-extension/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ruix/workfolder/active/DeCert/metamask-extension/test/setup.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at requires.forEach.mod (/Users/ruix/workfolder/active/DeCert/metamask-extension/node_modules/mocha/bin/_mocha:511:3)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/ruix/workfolder/active/DeCert/metamask-extension/node_modules/mocha/bin/_mocha:510:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Gudahtt** [comment] 2020-12-16 14:47
Thanks for the report!

I am unable to reproduce this. I can't test with OS X, but the most of the rest of my team uses OS X and they have not encountered this problem. Perhaps this has been fixed?

One more thing I'd suggest is updating Node.js. We use v10.18.1 or greater at the moment. I'm unsure whether the Node.js version relates to this error though.

I'll close this for now, but please let us know if this problem persists!

**Closed by Gudahtt** 2020-12-16 14:47 UTC
Labels: L06-testing, T00-bug
