### ISSUE TITLE
Batching Issues

### ISSUE THREAD

**Issue by willfsays** [MetaMask/metamask-extension#5817] opened 2018-11-23 04:29 UTC
**Describe the bug**
When batching a request to approve (with an ERC 20) and then to send tokens, MetaMask reverses the request, you have to add the send to the batch first before the approve to make it work.

When firing the same two async requests without a batch, as per above, MetaMask reverses the request, you have to add the send to the batch first before the approve to make it work.

**To Reproduce**
1. Create a standards-based ERC20 with approve and allowance methods
2. Create another method that checks the allowance >= an amount passed into the function (with a require) (lets call this setValue)
3. Create a new web3.BatchRequest() (web3 version 1.0.0.36)
4. Add batch send to ERC20 approve (e.g. contract.methods.approve(address, 1000).send({from: accountAddress});)
5. Add batch send to ERC20 setValue (e.g. contract.methods.setValue(1000).send({from: accountAddress});)
6. run batch.execute()
7. MetaMask will batch the requests in the wrong order (5 before 4) - proven by the nonce allocated
8. If you reverse the batch order, they run in the expected order (although exception is still seen for setValue even after confirming approve)
***
1. Create a standards-based ERC20 with approve and allowance methods
2. Create another method that checks the allowance >= an amount passed into the function (with a require) (lets call this setValue)
3. call send method to approve (e.g. contract.methods.approve(address, 1000).send({from: accountAddress});)
4. call send method to setValue (e.g. contract.methods.setValue(1000).send({from: accountAddress});)
5. MetaMask will batch the requests in the wrong order (4 before 3) - proven by the nonce allocated
6. If you reverse the call order, they run in the expected order (although exception is still seen for setValue even after confirming approve)

**Expected behavior**
MetaMask will batch the requests in the order in which they are received

**Browser details (please complete the following information):**
 - OS: Windows Pro 10 64-bit
 - Browser Chrome
 - MetaMask Version 5.0.3

**Comment by adamsoffer** [comment] 2019-10-25 13:51
@willfsays Confirmed on my end as well. BatchRequest _does not work_ with MetaMask. It batches the requests in the incorrect order. I've tested with a bunch of other web3 providers and they all work as intended.

cc: @danfinlay

**Comment by danfinlay** [comment] 2019-11-05 22:23
Closing in favor of #5852.

**Closed by danfinlay** 2019-11-05 22:23 UTC
