### ISSUE TITLE
MetaMask no longer working in Chrome 91, which became available for update yesterday!!

### ISSUE THREAD

**Issue by cryptogohan** [MetaMask/metamask-extension#11186] opened 2021-05-26 11:15 UTC
Forgive me foregoing the template.

* Chrome 91 became Stable (aka the default) one day ago.
* MetaMask can't communicate with Ledger's on Chrome 91.

I already reported the issue in #10925 . Back then it wasn't a 100% clear this was Chrome 91 being the issue, but downgrading from the 91 beta to 90 stable seemed to solve the issue. Someone decided to just close the issue and move on back then. Now the first user has shown up that upgraded to 91 on stable that appears to be facing the exact some issue.

I just upgraded chrome to 91 too, exact same issue is back.

I think we can close this as a duplicate and re-open the other one. That one contains a workaround too.

Good luck with the possible flood of Chrome+Ledger+MetaMask users that is about to be unhappy 😬 ! and thanks for all the hard work on MetaMask 🙏 .

**Comment by darkwing** [comment] 2021-05-26 12:27
Closing as duplicate of https://github.com/MetaMask/metamask-extension/issues/10925

**Closed by darkwing** 2021-05-26 12:27 UTC
