### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by prshnandaniya** [MetaMask/metamask-extension#13637] opened 2022-02-15 09:59 UTC
### Describe the bug

metamask not opening to click on connect button it's showing notification in metamask but it's not opening

### Steps to reproduce

1. want to solve popup problem

### Version

10.9.2

### Browser

Brave

### Operating system

MacOS

**Comment by darkwing** [comment] 2022-02-15 13:58
Closing as duplicate of https://github.com/MetaMask/metamask-extension/issues/13590

**Closed by darkwing** 2022-02-15 13:58 UTC
