### ISSUE TITLE
[Bug]: Unable send any token after update Metamask to 12.5.0

### ISSUE THREAD

**Issue by gades** [MetaMask/metamask-extension#28112] opened 2024-10-25 19:06 UTC
### Describe the bug

I have on my wallet a different tokens and after update metamask to 12.5.0 from 12.4.2 I can't sent tokens (CAKE and others ) to other address because I see 0 tokens on sent screen 
<img width="367" alt="Screenshot 2024-10-25 at 22 01 10" src="https://github.com/user-attachments/assets/f6c40f1c-e366-41e3-94af-e9dc09033702">
<img width="390" alt="Screenshot 2024-10-25 at 22 04 07" src="https://github.com/user-attachments/assets/72dfadad-b985-400e-85ec-8d731e024313">

### Expected behavior

1) see correct balance 
2) send tokens 

### Steps to reproduce

1. update metamask to 12.5.0
2. connect Ledger / Trezor 
3. send any tokens to wallet
4. try to send it to another address

### Detection stage

In production (default)

### Version

12.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

**Comment by Gudahtt** [comment] 2024-10-28 15:21
Thanks for the report! We've been unable to reproduce using Ledger or Keystone, but we were able to reproduce using Trezor.

**Comment by danjm** [comment] 2024-10-28 19:00
Hi @gades 

When you get to the send screen and it says you have zero tokens, are you still able to enter an amount of tokens and click "Continue"? I see the same problem you see, with the balance shown as 0, but I was still able to to enter and amount and click continue. See the video below, and let me know if it is working differently for you:


https://github.com/user-attachments/assets/dc7d6e90-4c66-412d-af1f-766fb3062a80

**Comment by gades** [comment] 2024-10-28 20:00
@danjm yes, it's showing 0 but I can sent to address 

<img width="368" alt="Screenshot 2024-10-28 at 21 58 36" src="https://github.com/user-attachments/assets/0473d0c3-26ad-43f0-89d0-bacee31b27f9">
<img width="369" alt="Screenshot 2024-10-28 at 21 58 47" src="https://github.com/user-attachments/assets/53fe53fc-1164-47d7-b498-c642d0648fbd">

@Gudahtt I able reproduce this issue with Trezor and Ledger too (wrong balance i.e. 0 )

**Comment by sleepytanya** [comment] 2024-10-28 22:14
@danjm @bergeron can https://github.com/MetaMask/metamask-extension/issues/27813 be related? Looks similar, just in case it can fixed in the same PR

**Closed** 2024-10-29 13:45 UTC
Labels: type-bug, Sev1-high, hardware-trezor, external-contributor, team-hardware-wallets, regression-prod-12.5.0
