### ISSUE TITLE
[Bug]: Cannot Send a Token after a first Send with token amount 0. Error `Cannot convert string to buffer`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17542] opened 2023-02-01 16:29 UTC
### Describe the bug

**Problem**: when I have an ERC20 token, and perform a send with amount 0. If then I perform another send with any amount, the transaction fails immediately and we get the error `Cannot convert string to buffer`

https://user-images.githubusercontent.com/54408225/216102952-22163fb6-8333-4932-a051-6f49b106b782.mp4

### Steps to reproduce

1. Go to test dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Create a Token
4. Add token to Wallet
5. Open MM
6. Click Send Token
7. Add any recipient
8. Add amount `0`
9. Confirm tx
10. Click Send Token again
11. Add any recipient
12. Add any amount
13. Confirm tx -- tx fails immediately and we get the console error

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment] 2023-02-06 15:30
Could this be related to https://github.com/MetaMask/metamask-extension/issues/17488 ?

**Comment by bschorchit** [comment] 2023-02-14 18:28
Next step: check if we can easily identify the commit that introduced this regression

**Comment by seaona** [comment] 2023-02-15 11:35
It looks like this issue was introduced by this PR

https://github.com/MetaMask/metamask-extension/pull/17334/files

**Comment by brad-decker** [comment] 2023-02-15 15:20
Looks like this was fixed by #17651  -- Thanks @bschorchit for identifying it could be related and thanks @segun for the fix! I tested this first on develop and could not reproduce, then checked out the commit ahead of @segun 's fix and was able to repro, then checked out his commit and was unable to repro -- so confirming it was in fact that not rounding issue that he and I identified and he fixed that was the culprit here. There were like 5-6 cases in the codebase where we round to 0 decimals (needs to be a whole number) and prior to his fix it would just skip the rounding entirely if number of decimals was 0.

**Closed by brad-decker** 2023-02-15 15:20 UTC
Labels: type-bug, area-transactions, Sev2-normal, team-confirmations, team-extension-client
