### ISSUE TITLE
Scrollbar doesn't show up on little metamask window or home page 

### ISSUE THREAD

**Issue by edmundedgar** [MetaMask/metamask-extension#5094] opened 2018-08-18 05:13 UTC
**Describe the bug**
When you have more than a page worth of transactions, there's no visible scrollbar to move down beyond the first page. However, you can scroll with the mouse wheel.

Same on both the little window you get by clicking the little fox in the top right-hand corner of the browser and in the "home" page you get by clicking "open in tab".

**To Reproduce**
Make more transactions than fit on one page
Hover the mouse over the transaction list. 

**Expected behavior**
Expect there to be a scrollbar allowing you to scroll down beyond the first page.

**Screenshots**
![screenshot from 2018-08-18 13-58-20](https://user-images.githubusercontent.com/75964/44296036-a5a98080-a2f0-11e8-8f40-7d9a8b25cfca.png)

**Browser details (please complete the following information):**
Ubuntu 18.04.1 LTS
Chrome Version 68.0.3440.84 (Official Build) (64-bit)
4.9.3
New

**Additional context**
There's supposed to be a scrollbar there per:
https://twitter.com/danfinlay/status/1030680156837310470

**Comment by dpazdan** [comment] 2018-09-17 19:01
similar issue -  https://github.com/MetaMask/metamask-extension/issues/5140

**Comment by tmashuang** [comment] 2020-01-31 01:51
Closing due to the issue is not showing itself anymore. If I am not accurate, open a new issue.

**Closed by tmashuang** 2020-01-31 01:51 UTC
Labels: S06-firefox, T00-bug
