### ISSUE TITLE
[Bug]: MetaMask stays loading indefinetly and get error `StreamProvider - Unknown response id for response: [object Object]` when doing *some* contract interactions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17467] opened 2023-01-27 16:09 UTC
### Describe the bug

**Problem**: when I call the function for mint an ERC1155 token, MetaMask stays loading indefinetly and I get the console error `Error in event handler: Error: StreamProvider - Unknown response id for response: [object Object]` .

https://user-images.githubusercontent.com/54408225/215133926-378001fe-6c51-45d9-8e64-930da22e90a6.mp4

This also happens when I call another contract function.

https://user-images.githubusercontent.com/54408225/215423675-bcd1b1e4-cc28-4e0a-9e29-911371eb2eab.mp4

[EDITED] It seems the error could start whenever we deploy a contract. It's not 100% deterministic, so further investigation needs to be done.

### Steps to reproduce [EDITED]
1. Go to Remix https://remix.ethereum.org/
2. Create a contract
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract Fallback {
    event Log(string func, uint gas);
    fallback() external payable {
        emit Log("fallback", gasleft());
    }
    receive() external payable {
        emit Log("receive", gasleft());
    }
    function getBalance() public view returns (uint) {
        return address(this).balance;
    }
}
```
3. Deploy this contract on Goerli - see error on console // if not, deploy another contract
4. Create another contract 
```
contract SendToFallback {
    uint val = 0;
    function transferToFallback(address payable _to) public payable {
        _to.transfer(msg.value);
    }

    function callFallback(address payable _to) public payable {
        (bool sent, ) = _to.call{value: msg.value}("");
        require(sent, "Failed to send Ether");
    }
    function count(uint _val) public {
        val = _val;
    }
}
```
6. Deploy this contract on Goerli - see error on console

After this, we are into a broken state, shown in the videos above.

### Version

develop [EDITED]

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by wbt** [comment] 2023-02-20 17:32
This looks like a duplicate of #17154 though this one has much more detail in the description, so it might be fair to close that one as a duplicate of this. 
I am seeing the same issue on calls to custom contracts on a private network and even non-transaction signature requests.  
In each case, the signature or transaction confirmation appears to go through just fine, but the interface remains with the forever-loading spinner and gray overlay indefinitely (tested >1hour).  To get to the next confirmation, you have to close out of MetaMask and ignore any "MetaMask Notification" popup window (because clicking X on that will be treated as a rejection), then re-open MetaMask from the button on the browser toolbar. 
I'm also seeing high CPU usage due to an apparent bug in Windows Explorer, which slows down the computer performance somewhat and may make this bug more likely to be observed, but don't have any particular reason to think that's the cause.

**Comment by DimasikS12** [comment] 2023-03-08 10:57
Hi! I have this problem too. Can you please tell me what is causing this error and how to solve it?

**Comment by wbt** [comment] 2023-03-08 16:31
The cause is unclear; it appears to be a bug in MetaMask. 

You can get a short term solution by clicking in some blank area in your browser, then clicking on the MetaMask pinned icon extension to get it to reload and hopefully display the next confirmation prompt, though it sometimes crashes then too (just keep trying).  Do NOT click the X on the crashed "Metamask Notification" popup as this is treated as a signature rejection. 

For the medium term, the only way to really solve it seems to be to use an alternative (see whatthefox.com as an example listing; no endorsement of their proposed alternative implied). 

For a long term fix, someone will have to take a deep dive into MetaMask code, ideally after being able to reliably reproduce the issue.  That's easier said than done though.

**Comment by DimasikS12** [comment] 2023-03-08 16:35
I can reproduce this error, it occurs after running certain contract methods on my site. When calling certain functions on my site that call certain methods on my contract, this error appears in MetaMask.

**Comment by wbt** [comment] 2023-03-08 17:21
Do you have (or can you make) clear steps for reproduction that don't cost real-world money? (e.g. something on a test network).

**Comment by DimasikS12** [comment] 2023-03-09 10:06
And please tell me which MacOS, Linux or Windows system do you use? It's just that I'm currently testing on Windows and don't see this error. By the way, if you have error, you can remove it. You just need to go to the MetaMask settings and reset the account, after that the error disappears.

**Comment by Samclay8** [comment] 2023-03-09 15:57
Windows 11, chrome version 111.0.5563.65, metamask 10.25.0.

Yes the error is specific to chrome and unfortunately resetting account data does not remove the issue. I have reset the account, and even completely uninstalled and reinstalled and the issue persists.

**Comment by wbt** [comment] 2023-03-10 15:35
I'm seeing it on Windows 10.

**Comment by otconline** [comment] 2023-03-10 16:04
Yes, that is right. This bug appeared in the latest version of MetaMask v10.25.0. I installed the previous version of MetaMask 10.24.2 and everything works fine. I also put debuggers in the MetaMask v10.25.0 code and noticed that when calling certain methods of my smart-controct, this error starts to appear, because MetaMask stops receiving id, as far as I understand, this is a store id, which is constantly generated. In general, this bug is due to updating MetaMask to version 10.25.0.

**Comment by DimasikS12** [comment] 2023-03-10 16:19
Yes, that is right. This bug appeared in the latest version of MetaMask v10.25.0. I installed the previous version of MetaMask 10.24.2 and everything works fine. I also put debuggers in the MetaMask v10.25.0 code and noticed that when calling certain methods of my smart-controct, this error starts to appear, because MetaMask stops receiving id, as far as I understand, this is a store id, which is constantly generated. In general, this bug is due to updating MetaMask to version 10.25.0.

**Comment by DimasikS12** [comment] 2023-03-10 16:22
I also noticed that in the previous version of MetaMask this function is not called when the contract method is called, and in the latest version of MetaMask this function is called for some reason when I call the contract method, but no id is generated and an object without an id comes in response.

**Comment by Samclay8** [comment] 2023-03-10 16:46
> <img alt="Screenshot 2023-03-09 at 20 39 06" width="1370" src="https://user-images.githubusercontent.com/33149213/224368131-d6c9f750-91c1-414e-9b72-408a319014c8.png">
> 
> <img alt="Screenshot 2023-03-09 at 20 40 10" width="1370" src="https://user-images.githubusercontent.com/33149213/224368146-26392280-180e-4d99-be00-1d3495bcf3df.png">
> 
> Yes, that is right. This bug appeared in the latest version of MetaMask v10.25.0. I installed the previous version of MetaMask 10.24.2 and everything works fine. I also put debuggers in the MetaMask v10.25.0 code and noticed that when calling certain methods of my smart-controct, this error starts to appear, because MetaMask stops receiving id, as far as I understand, this is a store id, which is constantly generated. In general, this bug is due to updating MetaMask to version 10.25.0. The second screenshot shows that the id was not generated and it simply does not exist, although it should be.

Life saver, thank you. Confirmed an issue with 10.25.0

**Comment by DimasikS12** [comment] 2023-03-10 17:00
But unfortunately, I still cannot figure out why MetaMask v10.25.0 cannot generate this id and why this happens. I also noticed that not all methods of my smart contract cause this error, only some.

**Comment by seaona** [comment] 2023-03-14 09:24
@DimasikS12 @wbt @Samclay8 thank you all for your contributions. We have identified the issue and have [a fix for it](https://github.com/MetaMask/metamask-extension/pull/18129). It will take a couple of weeks in order to be released in production. You should see it fixed once it is released :+1:

**Closed** 2023-03-15 14:46 UTC
Labels: type-bug, team-shared-libraries
