### ISSUE TITLE
some enhancment required

### ISSUE THREAD

**Issue by Bild96** [MetaMask/metamask-extension#8793] opened 2020-06-12 18:05 UTC
**Brave browser v 1.7.67
Linux Ubuntu 20.04 LTS**

* It's not possible to change ( account1 ) wallet name.
* Adding assets are disabled.
* scrolling down, and navigating between other tokens are no possible.

* I'm a frequent user for [gitcoin.co](https://gitcoin.co/chat#) with this release It's not possible to connect with my wallet. 

![Screenshot from 2020-06-12 19-47-27](https://user-images.githubusercontent.com/52472445/84532956-7d6deb80-ace7-11ea-9c50-e40e339de1d4.png)

![Screenshot from 2020-06-12 19-41-35](https://user-images.githubusercontent.com/52472445/84532960-7f37af00-ace7-11ea-85c4-613dc02cb10a.png)

![MetaMask 8 0](https://user-images.githubusercontent.com/52472445/84532964-7fd04580-ace7-11ea-8b19-b01bc87d3369.png)

**Comment by Gudahtt** [comment] 2020-06-12 21:09
Thanks for the feedback!

>It's not possible to change ( account1 ) wallet name.

Great find! This has been addressed in #8801

>Adding assets are disabled.
>scrolling down, and navigating between other tokens are no possible.

There is an "Add token" button below if you scroll down. I'm not sure what you mean about being unable to scroll - did you try using the scroll wheel while the popup was focused?

Note that you can also press `Tab` to select the 'Add token' button.

>I'm a frequent user for gitcoin.co with this release It's not possible to connect with my wallet.

gitcoin.co seemed to work fine when I tried it! It submitted a connect request when loading the page. I would suggest that you try refreshing the page - let me know if that helps.

**Comment by LefterisJP** [comment] 2020-06-13 09:07
> gitcoin.co seemed to work fine when I tried it! It submitted a connect request when loading the page. I would suggest that you try refreshing the page - let me know if that helps.

I think that after complains from people they stopped making the connect request just when visiting the site. You have to prompt for the connect request from inside the gitcoin website now.

https://twitter.com/owocki/status/1271122807972216832

**Comment by Bild96** [comment] 2020-06-16 10:45
It’s working with 7.7.9 version 
Not the new one ( testing )

**Comment by Gudahtt** [comment] 2020-06-16 18:36
It seems to work for me so far! I'll keep trying. Maybe your installation entered into a broken state somehow. if you're still able to reproduce this problem, it would be greatly appreciated if you could [submit a support request here with state logs](https://metamask.zendesk.com/hc/en-us/requests/new).

>I think that after complains from people they stopped making the connect request just when visiting the site. You have to prompt for the connect request from inside the gitcoin website now.

Personally when I tested it, it still prompted upon page load. I can re-request via that prompt as well though.

**Comment by Gudahtt** [comment] 2020-06-25 13:32
I'm going to close this for now, as I can't reproduce any of the reported problems on gitcoin.co. It's possible there was some bug that has since been fixed in the latest version of the v8.0.0 RC.

Please let us know if something is still broken with the latest version of the v8.0.0 RC though!

**Closed by Gudahtt** 2020-06-25 13:32 UTC
Labels: v8
