### ISSUE TITLE
[Bug]: Look into "network is busy" warning logic

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#26745] opened 2024-08-29 12:20 UTC
### Describe the bug

That our "network is busy" warning triggered when the fee is $0.15 feels a little bit too cautious.

### Expected behavior

Shouldn't it trigger when the network is busy to an extent where it actually is something to be cautious about to avoid warning fatigue? 

### Screenshots/Recordings

![image](https://github.com/user-attachments/assets/73c8f611-fba7-4916-a8b2-da483f019440)

### Steps to reproduce

1. Trigger a transaction on e.g. Etheruem
2. Notice the "network is busy" warning symbol in relation to the network fee

### Detection stage

In production (default)

### Version

12.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by bschorchit** [comment] 2024-08-29 14:15
Thanks for the report @eriknson! Closing as a duplicate of https://github.com/MetaMask/MetaMask-planning/issues/2752.

**Closed by bschorchit** 2024-08-29 14:15 UTC
Labels: type-bug, ux-enhancement, team-confirmations, area-design, regression-prod-12.0
