### ISSUE TITLE
Logout/Login, web3.eth.accounts empty

### ISSUE THREAD

**Issue by durimjusaj** [MetaMask/metamask-extension#6357] opened 2019-03-27 16:38 UTC
Im having a problem with accounts when I logout and login again, web3.eth.accounts array is empty defaultAccount is undefined. It acts like not logged in at all.

I tried web3.eth.getAccounts but no success.

If I refresh the tab it works normally.

**Comment by ContemporaryAnarchy** [comment] 2019-04-09 06:27
Duplicate of https://github.com/MetaMask/metamask-extension/issues/6030

**Comment by tmashuang** [comment] 2019-04-10 15:32
Closing for duplicate on #6030, continuing the discussion there.

**Closed by tmashuang** 2019-04-10 15:32 UTC
