### ISSUE TITLE
Nonce problem on localhost

### ISSUE THREAD

**Issue by eloudsa** [MetaMask/metamask-extension#2678] opened 2017-12-06 20:41 UTC
Hello

I'm using Metamask to develop my Dapp but I'm stuck with Metamask 3.12.1 because I'm not able to send transactions to node deployed on localhost due to rpc error (tx doesn't have the correct one).

Nodes as Truffle Develop, testRPC or Ganache are mainly used as in-memory node. Each time they are restarted, they start from a fresh situation.

But Metamask is lost with these development platform.

Right now, I'm stuck because I'm not able to validate transactions agains a development plateform deployed on localhost :-(

I'm using:
- Metamask 3.12.1
- Truffle 4.0.1
- Ganache 1.0.1 

Said

**Comment by johnerfx** [comment] 2017-12-08 10:44
Fixed with #2699?

**Comment by pimotte** [comment] 2017-12-16 13:49
Probably a duplicate of #1999

**Comment by danfinlay** [comment] 2017-12-18 20:03
Closing as a duplicate of #1999. Workaround is to restart testrpc/ganache with a different network ID, OR to reinstall MetaMask.

**Closed by danfinlay** 2017-12-18 20:03 UTC
