### ISSUE TITLE
Turn metamask off without disabling the extension

### ISSUE THREAD

**Issue by livnev** [MetaMask/metamask-extension#1344] opened 2017-04-25 19:07 UTC
I think it would make sense to have an on/off switch for metamask in the metamask menu, here is why:

Currently, if one has metamask enabled in chrome and connected to the mainnet, and navigates to something like [app.augur.net](app.augur.net), then the webapp will fail to work properly because it is supposed to run on another net (some testnet), through its own interface (without using a separate local node like metamask, parity, etc.). So in order to use the webapp properly one has to disable metamask completely via the chrome extensions menu. This is sort of inconvenient and a simple on/off switch in the metamask menu would be very useful. In the future I suspect that this problem could arise pretty frequently if dapps become prevalent.

**Comment by flyswatter** [comment] 2017-05-01 18:18
Related to #537.

I think our current plan is to let people specify network + account when logging in to a new site, and maybe we shouldn't inject web3 until that point either.

**Comment by livnev** [comment] 2017-05-01 19:04
That sounds like an even better way to do it. Thanks for your work!

**Comment by danfinlay** [comment] 2018-03-02 00:04
Closing as duplicate of #714

**Closed by danfinlay** 2018-03-02 00:04 UTC
Labels: T3-discussion
