### ISSUE TITLE
Bug: metamask shows white screen; storage out of quota?

### ISSUE THREAD

**Issue by maxtwen** [MetaMask/metamask-extension#3772] opened 2018-03-28 11:05 UTC
Expected behavior: when clicking on metamask icon, app should be shown
Actual behavior: blank window
Browser used: Version 62.0.3202.75 (Official Build) (64-bit)
OS used: ubuntu 16.04

Additional info: 
1. there's a lot of accounts in metamask (about 15 of them)
2. deleting everything from localStorage in background page did not help; un-install and install back metamask from chrome app store helped
3. when using dev mode for extensions, background page shows following error:
```
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'metamask-config' exceeded the quota.
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1031303)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1027213)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:3266
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087652)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087440)
    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087831)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390856)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390952
    at <anonymous>
```

last 2 lines are some kind of framework, and line 3 (1:3266) after de-minification is
```
                    for (; ; )
                        switch (e.prev = e.next) {
                        case 0:
                            return t = new _({
                                migrations: x
                            }),
                            e.next = 3,
                            U.get();
                        case 3:
                            if (e.t1 = e.sent,
                            e.t1) {
                                e.next = 6;
                                break
                            }
                            e.t1 = D.getState();
                        case 6:
                            if (e.t0 = e.t1,
                            e.t0) {
                                e.next = 9;
                                break
                            }
                            e.t0 = t.generateInitialState(A);
                        case 9:
                            return z = e.t0,
                            e.next = 12,
                            t.migrateData(z);
                        case 12:
                            if (z = e.sent) {
                                e.next = 15;
                                break
                            }
                            throw new Error("MetaMask - migrator returned undefined");
                        case 15:
                            return U.isSupported && U.set(z),
// this line
                            D.putState(z),
                            e.abrupt("return", z.data);
                        case 18:
                        case "end":
                            return e.stop()
                        }
```

**Comment by Gyspyqueen** [comment] 2018-03-29 05:31
What happens when you have eth and tokens do you lose everything nnstall and reinstall?

**Comment by danfinlay** [comment] 2018-03-30 19:19
This should be fixed in MetaMask 4.4.0, by PR #3732.

Can you right click the fox, select "Manage extensions" and confirm your version is the (buggy) 4.3.0? If you're on an old version, click `Update extensions now` to get the latest version.

If you're on 4.4.0, please check your logs for errors:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

If you see some errors then, please open a new issue to report your personal problem. I'm closing this issue now because we fixed the original cause, and I want to make sure we are keeping the instances separated.

**Closed by danfinlay** 2018-03-30 19:19 UTC

**Comment by Gyspyqueen** [comment] 2018-04-01 00:29
Yes version 4.3.0.

I cannot find where you go to for update extensions . Options is blanked out and , remove , hide and manage are all that can be seen. How do I do this

Sue

**Comment by lazaridiscom** [comment] 2018-04-01 00:47
@Gyspyqueen , you have to enable Developer Mode within the extension overview page. See here:

![image](https://user-images.githubusercontent.com/35095758/38168754-2bcd8bf2-355f-11e8-8c33-325710aa4d0d.png)

**Comment by Gyspyqueen** [comment] 2018-04-01 01:31
Found but when click on update does nothing. Next???

Sue

**Comment by lazaridiscom** [comment] 2018-04-01 01:39
> Found but when click on update does nothing

I can confirm this, same on my side (chrome does simply not update the extensions)

> Next???

Follow-up: #3813 (await response of core-team)

**Comment by Jasminrice** [comment] 2018-04-01 07:34
I have the same issue mac 10.13.3 

Also created a meta mask account on Brave 0.19.105 
However it only show one of my 3 accounts

**Comment by danfinlay** [comment] 2018-04-01 07:48
> However it only show one of my 3 accounts

Continue clicking "Add account" in the top right account menu until all of your accounts have been restored.

**Comment by Gyspyqueen** [comment] 2018-04-01 08:18
Have seed but I have tokens and ether on this wallet.

If I uninstall and reinstall will I be able to get both ether and tokens back as they should be

Sue

**Comment by danfinlay** [comment] 2018-04-01 08:19
You would have to re-add the tokens to see them, but yes, the tokens are controlled by those keys, they are not stored on the device, they are stored on the blockchain.

**Comment by Gyspyqueen** [comment] 2018-04-01 08:25
You haven’t mentioned about the ether that is on metamask wha happens there

**Comment by danfinlay** [comment] 2018-04-01 08:41
The ether and the tokens both exist on the blockchain, on those accounts. The seed words restore the accounts, which let you control those ether and tokens again.

The ether is just like tokens, when you restore, you will regain them.

**Comment by Gyspyqueen** [comment] 2018-04-01 09:03
Have reinstalled and now asking for ether. How do I move my ether from my previous account to the new one

**Comment by Gyspyqueen** [comment] 2018-04-01 09:06
This is turning into a nightmare. I have now got new wallet but everything stored on old wallet and key. I am not therefore able to load my old stuff to new wallet

Some help please

Sue

**Comment by Gyspyqueen** [comment] 2018-04-01 09:11
Ignore all. have managed reinstall from old seed.

Thanks
Sue

**Comment by Aceric1201** [comment] 2018-04-07 06:37
Hi i have the same issue i am current at version 4.5.5 and have attempted to reinstall but to no avail, still white screen
 please help
Eric
