### ISSUE TITLE
Stop the message asking to convert SAI after we dismissed it

### ISSUE THREAD

**Issue by clesaege** [MetaMask/metamask-extension#7976] opened 2020-02-03 11:35 UTC
**What problem are you trying to solve?**
I keep having a message asking me to convert SAI to DAI. I don't want to.

**Describe the solution you'd like**
Replace the "Remind Me Later" button to "Dismiss" and don't show more messages one a user has clicked on dismiss.

**Additional context**
Currently metamask is basically forcing me (if I don't want the annoying message to keep popping up) to get rid of my SAI. I think that wallets should stay neutral and not force behaviour on their users through annoying messages.
Feature requester introducing this message: https://github.com/MetaMask/metamask-extension/issues/7411

**Comment by jennypollack** [comment] 2020-02-07 09:22
Duplicate of #7724

**Closed by jennypollack** 2020-02-07 09:22 UTC
