### ISSUE TITLE
I cannot open my metamask

### ISSUE THREAD

**Issue by asiantimber** [MetaMask/metamask-extension#3817] opened 2018-03-31 06:23 UTC
Dear sir,

Have a nice day !

I open my metamask accout today, but I cannot to see anything, the fox picture and the password area..)

I have 50 eth acount on metamask, Please help me,

my mail is asiantimber@gmail.com

I use the file back up and download the new metamask and use it, But I saw 1 ether account only.

many thanks for your help

Best regards
![image](https://user-images.githubusercontent.com/37945280/38160365-b16a433c-34e6-11e8-8501-c3c3a9aacf72.png)

**Comment by lazaridiscom** [comment] 2018-03-31 11:04
Possibly you had more than 1 account. In your new installation, create some new accounts. They will have the same addresses than in the original installation.

**Comment by jrmoreau** [comment] 2018-03-31 16:51
closing. duplicate of #3813

**Closed by jrmoreau** 2018-03-31 16:51 UTC
