### ISSUE TITLE
Not able to change the custom nonce with approve transactions 

### ISSUE THREAD

**Issue by gwenvador** [MetaMask/metamask-extension#10392] opened 2021-02-07 08:31 UTC
**Describe the bug**
It is not possible to modify the custom nonce with approve transactions when advanced options is enabled. This is a problem when replacing a transaction with higher gas price on external site like https://cancel-ethereum-transactions.web.app. Metamask by default increase the nonce by 1 and will not replace the slow transaction. With normal transaction like transfer we can change the nonce but with the approve transactions it is not available.  
 
**Steps to reproduce (REQUIRED)**

1. Enable the custom transaction nonce options 
2. Launch an approve transaction
3. The nonce cannot be modified 

**Browser details (please complete the following information):**
 - MetaMask Version: 9.0.4

**Comment by Gudahtt** [comment] 2021-02-08 03:48
Thanks for the report! This is a duplicate of #10129, so I'll close this issue.

**Closed by Gudahtt** 2021-02-08 03:48 UTC
