### ISSUE TITLE
Ability to create new vault from Sign In screen

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#5347] opened 2018-09-25 16:39 UTC
I'd like to be able to create a fresh new vault from the sign in screen.  As-is, the sign in screen only has two options - "**Sign in**" or "**Import using existing seedphrase**". A third option, "**Create new vault**" (send you to the first screen when you first install the extension) would be helpful in case the user decides they want to create a brand new vault. 

![image](https://user-images.githubusercontent.com/597770/46028657-0a9d8680-c0a6-11e8-9d89-33c465aa57aa.png)

**Comment by bdresser** [comment] 2018-09-25 18:32
makes sense @cjeria - closing as a dupe of #4828

**Closed by bdresser** 2018-09-25 18:32 UTC
