### ISSUE TITLE
Replacing transaction with custom nonce and then Speedup reuses the original

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#9927] opened 2020-11-20 22:07 UTC
Version 8.1.3

### Scenario
When using custom nonce feature to replace a pending transaction, I then click Speedup

### Expected Behavior
The replacement transaction is sped up

### Actual behavior
The original is sped up

**Comment by tmashuang** [comment] 2021-01-05 19:01
Related to #7305.

**Comment by Gudahtt** [comment] 2021-01-19 02:57
Thanks for the report! This appears to be a duplicate of #8268

**Closed by Gudahtt** 2021-01-19 02:57 UTC
Labels: S2-normal, T00-bug
