### ISSUE TITLE
Firefox plugin does not connect to private network

### ISSUE THREAD

**Issue by abec** [MetaMask/metamask-extension#3716] opened 2018-03-25 03:01 UTC
### Expected Behavior
Connect to private network that is not localhost should work in firefox.

### Actual Behavior
Loads infinitely.

### Browser
Firefox

### Operating System
Mac OS X 10.12.6

### Extra
Testing in chrome and it works. Only a firefox issue.

**Comment by danfinlay** [comment] 2018-03-26 16:42
You'll have to look at the `Network` tab of the background inspector to see why the request is failing:

https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by abec** [comment] 2018-03-26 18:15
@danfinlay apparenty you need to turn on debugging in firefox to see network events. Here's are the logged network events:

<img width="893" alt="screen shot 2018-03-26 at 11 14 43 am" src="https://user-images.githubusercontent.com/2106636/37924522-f4ee7cf8-30e6-11e8-8a21-ebfb0bb5da1b.png">

Apparently there's an OPTIONS request which isn't completing.

**Request Headers**
```
OPTIONS / HTTP/1.1
Host: mobidex.io:8545
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: moz-extension://e3f3eef1-98b4-fe43-ab50-db2eb160bd7d
Connection: keep-alive
```

**Comment by danfinlay** [comment] 2018-03-26 21:44
Could you also try switching your network provider in MetaMask? Just try switching the network to another one (like "Main") and back again.

**Comment by danfinlay** [comment] 2018-03-26 21:45
The `OPTIONS` request seems to be going to `mobidex.io`, and that's strange, I don't know of any requests we make to mobidex.

@danjm @kumavis look familiar to you?

**Comment by abec** [comment] 2018-03-26 22:25
@danfinlay I set it up to point to mobidex. That endpoint is just a parity node.

I've switched back and forth between several networks, but connecting to a non-local parity node does not work in Firefox. It works just fine in chrome.

**Comment by Tbaut** [comment] 2018-04-04 18:24
Same problem here with the beta version, running Parity locally. I can't show you my logs because I don't have the ability to show the console from the popup (ctrl+shift+i opens it but asks to reload... and I couldn't manage to get the tab reload without closing)

![image](https://user-images.githubusercontent.com/33178835/38326425-10fa3566-3846-11e8-895a-0b7cb575b994.png)

**Comment by danfinlay** [comment] 2018-04-17 20:38
Since this works in Chrome and not Firefox, I think this may be fixed on our `master` branch.

The problem is that Mozilla has stopped merging our new versions, because they've had some issues reproducing our builds (our builds are not perfectly deterministic).

We are making Firefox publication a high priority, but in the meanwhile, for proper behavior, you may need to use another browser.

**Comment by danfinlay** [comment] 2018-04-23 18:14
@kumavis thinks this looks like a CORS issue. We should write a blog post about that.

**Comment by vincentserpoul** [comment] 2018-04-24 02:55
definitely a CORS issue.
Is there anything we can do to help?

**Comment by danfinlay** [comment] 2018-04-24 16:48
On Geth, there's a flag for setting the CORS setting. I don't know what local client you're using, you'll have to configure it correctly:
https://metamask.helpscoutdocs.com/article/29-using-a-local-node

**Comment by petri** [comment] 2018-04-24 19:26
Perhaps relevant (when using Parity): https://github.com/paritytech/parity/issues/7541

**Comment by Tbaut** [comment] 2018-04-25 09:27
Launching parity with `--jsonrpc-cors all` allows metamask to connect indeed, it would be safer by only allowing metamask's domain, may someone point me to the right one? (Reminder, I can't check myself and open the dev console on metamask for some reason)

**Comment by danfinlay** [comment] 2018-04-25 18:51
The cors domain will vary depending on the browser you're using. In Chrome, it's `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn`. Let us know if you research and find the domain for other browsers.

https://metamask.helpscoutdocs.com/article/29-using-a-local-node

**Comment by Tbaut** [comment] 2018-04-25 22:58
Hey Dan, the issue is for Firefox.

**Comment by Tbaut** [comment] 2018-05-06 20:47
@danfinlay could you please provide me the domain for firefox, I wouldn't want for security reasons to tell users to leave `--jsonrpc-cors` open to any app.

**Comment by vincentserpoul** [comment] 2018-05-07 03:04
@Tbaut --rpccorsdomain=moz-extension://36ff4990-4bdd-4d81-bbd7-91fcbcae8d06

**Comment by Tbaut** [comment] 2018-05-07 15:27
Thanks, however, it didn't work with this domain. It might be architecture specific.

**Comment by vincentserpoul** [comment] 2018-05-07 15:37
are you using geth or parity?
If it doesn't work, just go to firefox, type about:debugging in the address
launch the debug window for metamask
Launch metamask and click on the network panel.
Click on any of the request, you should see the domain in the headers.

**Comment by AyushyaChitransh** [comment] 2018-05-07 16:07
I am using parity, and faced the same issue. I was able to connect to remote RPC using web3-console but was unable to connect to same RPC using metamask.

However, on using `--json-rpc-cors all` I was able to get it working using metamask also.

**Comment by Tbaut** [comment] 2018-05-07 16:28
Thanks @vincentserpoul for the walkthrough. Using `--jsonrpc-cors moz-extension://ae62fc16-c916-4c24-9a36-97f5a850f25c` I'm on parity.
@AyushyaChitransh, consider specific domain rather than `all` as this reduce the attack surface.

**Comment by danfinlay** [comment] 2018-05-21 18:32
Is anyone here having a problem that isn't solved by running their local node with a CORs flag?

Closing until someone can confirm this is our issue.

**Closed by danfinlay** 2018-05-21 18:32 UTC
Labels: P1-asap, T00-bug
