### ISSUE TITLE
Watching events not reliable on a dev environment 

### ISSUE THREAD

**Issue by eloudsa** [MetaMask/metamask-extension#2454] opened 2017-10-23 23:02 UTC
Hello

I'm using Metamask in a development environment with the following tools:
- Truffle v3.4.11 (core: 3.4.11)
- Solidity v0.4.15 (solc-js)
- testrpc v4.1.3
- Metamask v3.11.2
- network: localhost:8545
- frontend app with webpack

The development process requires to migrate new versions of the contracts and/or to restart the node.

If we start from a clean situation, we are able to watch our events from our frontend application: fromBlock: 'latest', toBlock: 'latest'

But if we restart the testrpc node and redeploy our contracts, the events are not more watched through Metamask.

We have tried to switch networks or to lock and unlock Metamask without success.
The only way is to disable and re-enable the Metamask extension from Chrome.

You can imagine that this process slow down the development process 

Did you notice this issue?
Is there another way to "reset" the state of Metamask without disabling and re-enabling the extension?
What do you think about adding a developer mode to Metamask to have access to some additional feature such as clearing its context/cache?

Thanks,

Said

**Comment by futuremarc** [comment] 2017-10-24 02:36
+1. I am encountering this bug on the rinkeby testnet and localhost, havent tested on main net yet but I have a suspicion we'll see the same thing. It's breaking the user experience for my testers of my dApp and is slowing down the development process for me as well. Any help follow-through or insight would be greatly appreciated!

**Comment by tmashuang** [comment] 2017-11-06 17:14
Duplicate of #2393

**Closed by tmashuang** 2017-11-06 17:14 UTC
