### ISSUE TITLE
[Bug]: PPOM report false positives not displayed if flag has no details

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21188] opened 2023-10-04 10:26 UTC
### Describe the bug

**Problem**: whenever we are triggering a malicious transaction, in the case there are no details (i.e. at the moment, Send ETH, because of [this](https://github.com/MetaMask/metamask-extension/issues/20689) ) we don't have the possibility to report a false positive.

### Expected behavior

We should always have a possibility to report a false positive.
Not sure how design should look like though @bschorchit  move false positive in a separate section (independent of Details?)

### Screenshots

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/7fbea9d1-0241-413c-a4ad-dea49a93541f)

### Steps to reproduce

1. Select Mainnet
2. Enable Blockaid from Experimental settings (now on flask)
3. Go to the test dapp
4. Click Send ETH Malicious
5. See there is no possibility of reporting a false positive

### Version

when this PR get's merged (on flask build) https://github.com/MetaMask/metamask-extension/pull/20856

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment] 2024-06-26 15:32
The issue is already fixed in latest code.

**Closed by jpuri** 2024-06-26 15:32 UTC
Labels: type-bug, Sev3-low, needs-estimate, team-confirmations
