### ISSUE TITLE
**CLA Signature Action:** All authors have signed the CLA. You may need to manually re-run the blocking PR check if it doesn't pass in a few minutes.

### ISSUE THREAD

**Issue by Bow0628** [MetaMask/metamask-extension#11449] opened 2021-07-02 19:05 UTC
**CLA Signature Action:** All authors have signed the CLA. You may need to manually re-run the blocking PR check if it doesn't pass in a few minutes.

_Originally posted by @github-actions[bot] in https://github.com/MetaMask/metamask-extension/issues/11405#issuecomment-869963406_

**Comment by ryanml** [comment] 2021-07-05 21:39
Hi @Bow0628 - I'm closing this issue as the PR you tagged has been merged, and also because the CLA comment is expected behavior. If there was another concern you were trying to bring up, please let me know. Thanks!

**Closed by ryanml** 2021-07-05 21:39 UTC
