### ISSUE TITLE
Set up event tracking for Token Detection

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#12829] opened 2021-11-24 15:15 UTC
If we measure the ratio between Token Detection vs Custom Token Form usage, we can indirectly infer that token detection is reliable and is a useful tool. Detailed tracking will be done here:
https://www.notion.so/4e8115ec1e8346a88e13960b04cf1b2a?v=60f22ddf4ac4488a834a6d7a808ae5d8

1. Goal: Reduce reliance of custom token form by analyzing funnel flow
a. Import token
![Screen Shot 2021-11-23 at 8 35 57 PM](https://user-images.githubusercontent.com/6951929/143265095-7a9c7a9a-ed0f-4096-be84-b0e0c8885325.png)
        
b. Opened on Custom Token form
![Screen Shot 2021-11-23 at 8 36 08 PM](https://user-images.githubusercontent.com/6951929/143265164-b5880823-6580-4045-b126-f5a8f4002f53.png)
    
c. Added Custom Token using form
![Screen Shot 2021-11-23 at 8 36 22 PM](https://user-images.githubusercontent.com/6951929/143265205-2c428af3-77e6-4b50-9529-4babd1ae36a7.png)
  

2. Measure indirect satisfaction of token detection by measuring detection enablement

a. Enabled Token Detection
![Screen Shot 2021-11-23 at 8 46 10 PM](https://user-images.githubusercontent.com/6951929/143265282-90e51ed9-f206-4583-8a9a-a9a5676dd719.png)

b. Started Token Detection search
![Screen Shot 2021-11-23 at 8 54 46 PM](https://user-images.githubusercontent.com/6951929/143265368-6e78d6e7-ffa9-43ba-9782-0ff9d096ce08.png)

c. Imported Token
![Screen Shot 2021-11-23 at 8 55 00 PM](https://user-images.githubusercontent.com/6951929/143265397-17477077-4f32-4ead-a8c2-93f00c8d6f9e.png)

**Comment by brad-decker** [comment] 2022-01-20 15:27
@kevinghim I would like to propose that this be treated as the "adding a token funnel":

1. User enters funnel by clicking on 1a "Clicked Import Tokens"
2. User progresses further by searching or entering in token details in custom form "Entered Token Details".
3. User progresses further by clicking next (on the token list) or add custom token (on form) "Selected Token(s) To Import"
4. User progresses to the final step by importing the tokens "Token(s) Imported"

For clarity what we have today:

1. `Clicked "Add Token"`
2. `Token Added` (Swaps has a Token Imported event...)

for #2, the properties we track are below.

```js
this.context.trackEvent({
  event: 'Token Added',
  category: 'Wallet',
  sensitiveProperties: {
    token_symbol: asset.symbol,
    token_contract_address: asset.address,
    token_decimal_precision: asset.decimals,
    unlisted: asset.unlisted, //<- whether the token was in the token list
    source: 'dapp', //<- 'dapp' | 'custom' | 'list'
  },
});
```

A 'Token Added' event is fired for every token that is added so in this case the last step of our funnel would have multiple entries and be kind of strange.

@kevinghim if you agree on the proposed funnel, could you advise on how we should modify the current events (or replace them) such that we track what we want to know? As an example I am thinking for step 2 we can add a property that differentiates the two types of ways a user may enter token details:

```
mode: 'custom form' | 'search'
```

**Comment by kevinghim** [comment] 2022-01-21 01:41
@brad-decker thanks for the proposal. I agree with the steps you outlined here. 

Question on step 4: User progresses to the final step by importing the tokens "Token(s) Imported"

Would we be able to associate a property that tracks the value of the imported token? This would just be triggered initially when the import happens. The rationale behind this is to track the value created by the import token feature.

**Comment by brad-decker** [comment] 2022-01-21 17:10
@kevinghim - When you say value of the imported token... you mean how many of that token or the fiat value for one token or both?

**Comment by kevinghim** [comment] 2022-03-17 16:13
> @kevinghim - When you say value of the imported token... you mean how many of that token or the fiat value for one token or both?

Strike this. Let's not determine value of imported token.

**Comment by brad-decker** [comment] 2022-04-01 18:58
Closing as duplicate of #13951

**Closed by brad-decker** 2022-04-01 18:58 UTC
Labels: area-tokens, area-metrics, Team 🌱, stedmap team
