### ISSUE TITLE
[Bug]: Attempt to send non-native token using Send flow results in Unapproved Contract Interaction

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24463] opened 2024-05-09 16:33 UTC
### Describe the bug

 Attempt to send non-native token using Send flow results in Unapproved Contract Interaction.
[This bug](https://github.com/MetaMask/metamask-extension/issues/24446) is probably related.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/c5444dd2-6a19-45ab-adf9-5607d81991c2

### Steps to reproduce

1. Start Send transaction
2. Select non-native token (in the video LINK -> USDC)
3. Click 'Continue'
4. See Unapproved Contract Interaction tx in the Activity tab

### Version

latest build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by ejwessel** [comment] 2024-05-09 23:28
duplicate of https://github.com/MetaMask/metamask-extension/issues/24446

**Closed by ejwessel** 2024-05-09 23:28 UTC
Labels: type-bug, team-wallet-ux, swap-send-blocker
