### ISSUE TITLE
I need to change my password on every login. And after i click restore from my seed phrase the ether that was in it is gone? Please help.

### ISSUE THREAD

**Issue by RubenOlt** [MetaMask/metamask-extension#4053] opened 2018-04-20 22:41 UTC

**Comment by iamJLAD** [comment] 2018-04-21 16:59
I have this same issue. On my laptop, the original device i added metamask, is fine. Though, on my computer, i need to change passwords every time.

**Comment by RubenOlt** [comment] 2018-04-22 18:56
@radicall-co-nz 

When I first set up the wallet i had to write down the Seed Phrase together with the password. But after that when I wanted to use MM again, I again had to Accept the terms, again create new password. S
till now when I want to login from the browser it again asks me to Accept the terms etc. 
MM should only ask me to enter my password and not everything else. Yesterday I switched to the new Beta of MM, which looked better to me, but when I now go to MM it is again back to the old version.

**Comment by radicall-co-nz** [comment] 2018-04-22 19:14
Then al I can suggest is to try to restore the wallet, rather than log into it...

**Comment by radicall-co-nz** [comment] 2018-04-22 19:15
Not sure about the different versions and how that impacts your probem.

**Comment by RubenOlt** [comment] 2018-04-22 19:16
Yeah but how to restore?

**Comment by jamesray1** [comment] 2018-04-24 10:47
Same issue, worked with with Brave, then Firefox, then I noticed this issue after I added it to Chrome, on Firefox.

**Comment by vlad-saling** [comment] 2018-04-24 16:25
Same issue on Windows with Chrome. Simply can't log in. Have to restore. And yes, I double/tripple checked password, keyboard etc.

Mac + Chrome seems to be working fine though.

**Comment by bdresser** [comment] 2018-06-12 20:46
hey @jamesray1 @vlad-saling @RubenOlt thanks for reporting this & for your patience. we're aware of the issue but having trouble identifying the root cause. 

we've created a bug bounty #3314 and i'll close this issue to consolidate the conversation there.

**Closed by bdresser** 2018-06-12 20:46 UTC
Labels: L13-storage, T00-bug, T10-spooky
