### ISSUE TITLE
User Question: funds missing from account

### ISSUE THREAD

**Issue by Jeetsingh1944** [MetaMask/metamask-extension#4537] opened 2018-06-09 15:28 UTC

**Comment by Jeetsingh1944** [comment] 2018-06-09 15:35
My Ether has been stolen from my meta mask wallet, i transferred some Ether around 16:50 UK time on 06/06/2018. I disconnected my computer from internet and left i switched on my computer at 17:37 UK time to check status of transaction. It was still showing pending and no other transaction was visible. Next day i found someone else have stolen my all Ether from meta mask wallet at 17:05:25 UK time and 18:05:25 UTC time. I do not understand that when i logged in to check transaction and it was showing my transaction pending and no other transaction was visible how someone else stole my Ether at that time. 
I have strong feeling that something going wrong with Meta mask.
Check attachments for proof
![computer logs](https://user-images.githubusercontent.com/34196471/41193400-12aa3b18-6c03-11e8-9f79-acc353ddf59d.png)
![time eth stolen](https://user-images.githubusercontent.com/34196471/41193401-12cd00a8-6c03-11e8-9637-f2c2bf31102a.png)

**Comment by kumavis** [comment] 2018-06-09 18:14
@Jeetsingh1944 Just to clarify, metamask has never been hacked before.

That said, multiple users have fallen victim to phishing campaigns and malware. Did you ever enter your private key or seed phrase on a website claiming to be an airdrop? This is the most common way MetaMask users are victimized. 

Here is another example of a recent phishing campaign against MetaMask:
https://www.reddit.com/r/ethereum/comments/8pddzm/psa_btcmanagercom_is_running_metamask_phishing/

Please email support@metamask.io with your state log file, which can be downloaded from the settings menu. With this information we can try and get a better picture of what happened on your system.

**Comment by Jeetsingh1944** [comment] 2018-06-10 14:05
No i never entered my seed phrase and private key on any website. I have sent log files on the email address you gave. Please get back to me asap.

**Comment by 7nicoale** [comment] 2018-07-09 01:30
hi . good I finally get to you guys just the same situation happened with me
hire is the address my eth. went to :https://etherscan.io/address/0x79675145ff147e3e21ac99fb3aa9969633d4f3ff
what I supose to do and it is safe for me to use metamasc?

**Comment by billtlee** [comment] 2018-11-21 04:45
I just experienced the same thing.  I had just purchased a few ether a few hours for the very first time.  I waited for a long time for the ether to arrive but it never did.  After I looked at etherscan, my ether was transferred to another account a minute after it reached my wallet address.  I had seen this happen before when I was using metamask for development but used the default seed phrase.  Since then, I had re-created the account with a completely new seed phrase and had never posted it or my private key anywhere.  I don't know how this happened.  I am very pissed that I just lost a few hundred USD.  This is the first time I ever purchased any crypto currency.  It's been quite a bad experience.  I have also emailed my logged to you guys.  Please get back to me asap.

Here is the transaction that stole my ether:

https://etherscan.io/address/0x8fcae66ca2565966f5be02ef6e09c3f821f4e9df

**Comment by isaack2808** [comment] 2019-01-03 16:41
This happened to me as well.  First time getting ready to use a large amount of ether on metamask.  Very upset here is the transaction that stole my ether:  
https://etherscan.io/tx/0x7aa7d909563453622651029de39933909953600f5eb7a7eff57540e28061d055

Do not use metamask under any circumstance!  I never gave away my seed phrase or private key!

**Comment by bdresser** [comment] 2019-01-03 17:59
hey all, we've seen increasingly sophisticated phishing campaigns out there that may be the cause of this behavior. Especially if your ETH was sent to an unknown address, then immediately moved from that address – it looks particularly like a phishing attack.

If this happens, please email support@metamask.io with a copy of your [state logs ](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue) and we'll do our best to help you out there.

Closing this issue for now, please reach out with any more questions.

**Closed by bdresser** 2019-01-03 17:59 UTC
Labels: T05-userQuestion
