### ISSUE TITLE
Stuck on "connecting to network"

### ISSUE THREAD

**Issue by mtcarmel1914** [MetaMask/metamask-extension#2636] opened 2017-12-01 06:53 UTC
description added by moderator 11/8

several users have reported their extension stuck on "connecting to Mainnet" or "connecting to network" when they're logged out and they click the extension. 

via slack
>have been getting infinite loading gif on startup.
when I unlock in mainnet it infinite loads, but if I open into rinkeby or kovan its fine and then I can change it over to mainnet. confimed this about 6 times in a row. it fixes it when I restart chrome 50% of the time. 
Mojave 10.14 (18A391)
Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

> the workaround is to turn the plugin off/on, and then make sure its not on mainnet when i type my password. then switch to mainnet. I also noticed that when i switch to a different browser tab while on mainnet it goes into infinite loading as well

**Comment by mtcarmel1914** [comment] 2017-12-01 06:53
will not start! stuck on "connecting to network". How do I fix this issue?

**Comment by vincentserpoul** [comment] 2017-12-06 07:48
I have the same.
I usually just switch to main network back to the network I wanted to connect to. It works for me as a temp workaround

**Comment by danfinlay** [comment] 2017-12-13 18:59
That workaround works for most people.

This seems to happen to some users after some kind of network interruption, it seems to break our network connection and it isn't cleaned up well. We need to find a good way to reproduce this in order to fix this.

If anyone can describe what first caused this for them, it could help us fix it for good.

**Comment by danfinlay** [comment] 2017-12-18 20:22
We need to handle provider errors better.

**Comment by danfinlay** [comment] 2017-12-18 20:24
Partly related to #2552.

**Comment by danfinlay** [comment] 2018-01-03 23:43
The usual workaround for this is to switch the provider (top left menu) and back again. There seems to be some case where we do not catch an infura error, and stop polling for provider connection. If we just catch around our provider connection polling, we should be able to fix this.

**Comment by et** [comment] 2018-05-03 19:29
> If anyone can describe what first caused this for them, it could help us fix it for good.

@danfinlay - I had Little Snitch blocking requests to infura. You could do the same by just blocking requests to infura in your `/etc/hosts`

`0.0.0.0 api.infura.io`

To reproduce:
* Block requests to infura
* Open metamask
* Observe the never ending spinner (this should have some kind of time out to inform the user)
* Allow requests to infura
* Open metamask
* Observe that the never ending spinner is still present. The only way to fix is to change the network.

**Comment by bdresser** [comment] 2018-06-06 18:32
closing in favor of #4064

**Comment by bdresser** [comment] 2018-07-10 17:42
handled in #4279 :)

**Comment by unparalleled-js** [comment] 2018-12-25 00:15
Yeah, it is completely stuck for me. I can't switch networks. I have removed it and re-added it. I have disabled and re-enabled it. I restarted my computer. It is still going!

How can I end this infinite loop??

**Comment by whymarrh** [comment] 2019-02-04 20:01
> Observe the never ending spinner (this should have some kind of time out to inform the user)

I believe this has been fixed with https://github.com/MetaMask/metamask-extension/pull/5893

**Closed by whymarrh** 2019-02-04 20:01 UTC
Labels: T00-bug

**Comment by martianatwork** [comment] 2023-03-27 13:27
Best solution i have found is right click on the extension icon in the browser.
1. Select "Inspect Pop-up"
2. Open the popup
3. Delete the loading overlay using the inspector tool
4. Change network and unlock wallet if required.
5. Reopen the metamask

My metamask was locked, first time it didn't show that the network is changed but once i unlocked it metamask crashed and i had to reopen the popup

**Comment by cryptoKevinL** [comment] 2023-06-21 21:33
I just ran into this as well.  I had to inspect both the pop-up and the extension itself.  Took me about 20 min to remove all the pop-ups to get back to main view.  I have some error dumps from within MM error message if that would help, but there are pretty high level.
<img width="336" alt="Screenshot 2023-06-21 at 2 18 58 PM" src="https://github.com/MetaMask/metamask-extension/assets/19207330/826cc40e-376c-4c76-88f6-15a585810393">

**Comment by kabaluyot** [comment] 2024-01-19 07:20
> Best solution i have found is right click on the extension icon in the browser.
> 
> 1. Select "Inspect Pop-up"
> 2. Open the popup
> 3. Delete the loading overlay using the inspector tool
> 4. Change network and unlock wallet if required.
> 5. Reopen the metamask
> 
> My metamask was locked, first time it didn't show that the network is changed but once i unlocked it metamask crashed and i had to reopen the popup

This worked lmao
