### ISSUE TITLE
Cannot Reset Account on Firefox

### ISSUE THREAD

**Issue by jevdiego** [MetaMask/metamask-extension#4136] opened 2018-04-30 16:00 UTC
Hi,

I need to reset the account (as explained here https://metamask.helpscoutdocs.com/article/36-resetting-an-account), but as shown below, I cannot get to the 'reset account' button. Either I should be able to scroll down (which obviously I can't) or the Metamask window needs to be bigger. I'm assuming this is a bug in the Firefox extension.

![firefox](https://user-images.githubusercontent.com/20283397/39436887-92ac2160-4c9f-11e8-9b20-720796cffed0.png)

**Comment by mallapurbharat** [comment] 2018-05-30 05:14
True... The "Reset account" button displays in Chrome, but doesn't show up in Firefox 60.0.1 (64-bit) on Ubuntu.

**Comment by bdresser** [comment] 2018-06-12 20:18
@mallapurbharat @jevdiego Firefox is now up to date with our most recent release (4.7.4) and I'm no longer seeing this issue – could you confirm this is fixed? 

(It's also fixed on the new UI, click in the top right and then "Try beta!")

**Comment by jevdiego** [comment] 2018-06-13 09:41
Yes, displays now. Thanks for the fix.

**Closed** 2018-06-13 17:32 UTC
Labels: L03.0-oldUI, T00-bug

**Comment by mallapurbharat** [comment] 2018-06-20 02:57
Yes, the issue is fixed now.

**Comment by unparalleled-js** [comment] 2018-12-10 21:55
I am currently having this issue
