### ISSUE TITLE
Can't get logs from injected web3

### ISSUE THREAD

**Issue by roehst** [MetaMask/metamask-extension#3114] opened 2018-01-29 01:45 UTC
Hi, I can't get logs from the injected web3 instance, although I _can_ with a second instance injected just for it;

```
    web3_ = new Web3(
        new Web3.providers.HttpProvider("http://localhost:8545"));
```

This will work and print events:

```
web3_.eth.contract(GameInterface.abi).at("0x1afb35b154f41d21d303958166f6536ab0199d4a").UserPlacesBet().watch(function (e, r) { console.log(r)})
```

But this will not:

```
web3.eth.contract(GameInterface.abi).at("0x1afb35b154f41d21d303958166f6536ab0199d4a").UserPlacesBet().watch(function (e, r) { console.log(r)})
```
Browser is Firefox, OS is Linux.

**Comment by antimatter15** [comment] 2018-01-29 06:53
I believe this is a consequence of #2350

**Comment by danfinlay** [comment] 2018-01-29 18:42
Duplicate of #2978, feel free to rally there. Events/logs are hard to do before websockets.

**Closed by danfinlay** 2018-01-29 18:42 UTC
