### ISSUE TITLE
unable to add existing hardware wallet to a new metamask install....

### ISSUE THREAD

**Issue by anishp55** [MetaMask/metamask-extension#12980] opened 2021-12-06 01:46 UTC
i am unable to add a hardware wallet to a new install of metamask without first creating a software wallet.
i have no desire to setup any software wallet as my hardware one  already exists.  please let me use the hardware wallet without having to create a software wallet.

**Comment by darkwing** [comment] 2021-12-11 01:35
Closing as duplicate of https://github.com/MetaMask/metamask-extension/issues/13043

**Closed by darkwing** 2021-12-11 01:35 UTC
