### ISSUE TITLE
Experimental API - wallet_watchAsset - more characters for symbol?

### ISSUE THREAD

**Issue by HM999** [MetaMask/metamask-extension#7203] opened 2019-09-20 11:10 UTC
https://metamask.github.io/metamask-docs/API_Reference/Experimental_APIs

```
"symbol": tokenSymbol, // A ticker symbol or shorthand, up to 5 chars.
```

Why only 5 characters?

```
At MetaMask, we believe the future of tokens has the potential to be much bigger than any one party can curate, and we want to enable this explosion of creativity.
```

Then you will need more characters.

Imagine the situation where tokens are generated dynamically. For example, I sell multimedia content, or books, or something. Each item gets sold via a token sale. i.e. each item gets it's own token. There will be 10's of thousands of tokens. My website is called MediaSale.com, so all tokens created start MSALE but I vary the following characters. MSALEB389 - Book #389, MSALEV9811 - video #9811 etc. You get the idea.

Anyway, I just thing 12 characters would be better, 5 is too little.

**Comment by vandan** [comment] 2022-07-14 18:07
Duplicate of #7567

**Closed by vandan** 2022-07-14 18:07 UTC
Labels: type-enhancement, area-api
