### ISSUE TITLE
Need to update trezor Firmware 2.3.1 SDK

### ISSUE THREAD

**Issue by epop-cs** [MetaMask/metamask-extension#8866] opened 2020-06-29 13:17 UTC
**Describe the bug**
An user reported that he sees an issue in regards to Trezor Firmware version 2.3.1.

**To Reproduce (REQUIRED)**
Steps to reproduce the behaviour, libraries used with version number, and/or any setup information to easily reproduce:

Please see screenshot attached. Unfortunately I do not posses a Trezor device, so I could not reproduce the user's steps.

**Expected behaviour**
Connection with device is done successfully.

**Screenshots**
![switccheo](https://user-images.githubusercontent.com/58727092/86010232-c631de00-ba23-11ea-9ef6-3c7d60192c93.png)
![2020-06-24_115317](https://user-images.githubusercontent.com/58727092/86010237-c6ca7480-ba23-11ea-81a9-8f2d09f01c32.png)

**Browser details (please complete the following information):**
 - Hardware Wallet  Trezor Firmware version 2.3.1;

**Additional context (Error Messages, etc.)**
No additional errors could be spotted.

**Comment by whymarrh** [comment] 2020-06-29 13:56
Duplicate of https://github.com/MetaMask/metamask-extension/issues/8349

**Closed by whymarrh** 2020-06-29 13:56 UTC

**Comment by whymarrh** [comment] 2020-06-29 13:57
Please comment of #8349 with **details** of what doesn't work
