### ISSUE TITLE
Gas Price Must Be Greater Than Or Equal To 0.1 GWEI.

### ISSUE THREAD

**Issue by beichent** [MetaMask/metamask-extension#3888] opened 2018-04-05 03:31 UTC
When sending transactions to a private Ethereum blockchain like Quorum, there is no mining cost thus gas cost is zero.

However, MetaMask assumes all transactions have a non-zero cost thus doesn't allow to submit the transaction. It displays a warning and the SUBMIT button is disabled.
<img width="359" alt="screen shot 2018-04-04 at 11 29 20 pm" src="https://user-images.githubusercontent.com/37377780/38345968-1b6cfd66-3860-11e8-8e9d-ded324eda445.png">

Could MetaMask offer the configuration to allow setting gas cost as 0 when connecting using the "Custom RPC" option? 

The browser I used is Chrome 65 on iMac.

**Comment by nujabes403** [comment] 2018-04-19 11:25
I modified this code on #4037

**Comment by danfinlay** [comment] 2018-04-20 21:02
Closing as a duplicate of #3074.

**Closed by danfinlay** 2018-04-20 21:02 UTC
