### ISSUE TITLE
Support Hierarchical Deterministic (HD) Wallets in Ledger/Trezor

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#5768] opened 2018-11-15 21:26 UTC
**What problem are you trying to solve?**
When I connect a new HD address on my hardware wallet it replaces my prior HD address

**Describe the solution you'd like**
I can add multiple HD addresses per HW wallet

**Additional context**
I am using a Ledger.

**Comment by kosecki123** [comment] 2019-02-07 14:50
Yes, this is really annoying, hardware wallet account are still view-only accounts, I would love to be able to import more of them.

**Comment by Gudahtt** [comment] 2021-01-06 21:21
This seems like a duplicate of #6649. I'll close for now, but please let me know if I've misunderstood the request.

**Closed by Gudahtt** 2021-01-06 21:21 UTC
Labels: L17-hardware, T01-enhancement
