### ISSUE TITLE
Newer version of matamask throws errors when sending transaction. 

### ISSUE THREAD

**Issue by win2win** [MetaMask/metamask-extension#2015] opened 2017-09-04 22:27 UTC
I have two versions of metamask  chrome extensions.  3.5.2 and  3.9.11. 
I'm currently running private geth node Version: 1.6.7-stable

I can process transactions with older version of metamask, but when I switch to newer I get this error.
The message comes instantaneously, every time.

[ethjs-rpc] rpc error with payload {"id":7663982154336,"jsonrpc":"2.0","params":["0xf86b808504a817c800833d090094001a4039eed5a5099b2bd25085b48ef137902be38084be9a65558207f2a0aff9e56abb6bbeee508bf3fc3918176df97ae118b24bf78d90a9edb762900c1fa0649f391910b82dc97f3259f0d781dde56bf1ed710d5723eeea8fc63bb351a48d"],"method":"eth_sendRawTransaction"} Error: invalid sender

**Comment by flyswatter** [comment] 2017-09-05 18:49
This seems to be a duplicate of #1999, will be working to fix this soon there.

**Closed by flyswatter** 2017-09-05 18:49 UTC

**Comment by iwooden** [comment] 2017-09-05 18:55
The "invalid sender" error generally occurs because Metamask uses [EIP 155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) transaction signing, and your private network isn't supporting it.

Make sure that the genesis block for your private network is set up with the proper "config" parameters: https://github.com/ethereum/go-ethereum/wiki/Private-network . In particular, you will want to make sure that eip155block is set to 0.

**Comment by win2win** [comment] 2017-09-07 00:28
I'm able to get it to work when I'm connecting to ropsten from Metamask. Thanks for the pointer. 
However after following steps of the genesis file you have pointed, problem still persists. I also tried to connect to http://localhost:8545 from metamask on my machine while geth was connecting to ropsten. This didn't work either. It seems like the problem is while connecting to localhost regardless off where localhost is pointing to. 

Anyway I'm glad that it works in the settings which users will find themselves.

**Comment by robert-zaremba** [comment] 2017-09-20 14:23
Can this be related to running geth with `--dev`? Recently i've started using this option and MetaMask stopped working.

**Comment by robert-zaremba** [comment] 2017-09-20 23:05
Can this be related to running geth with `--dev`? Recently i've started using this option and MetaMask stopped working.

**Comment by santiagorp** [comment] 2017-09-22 11:55
I'm having the same issue. My current genesis block is like this:

```
{
  "config": {
    "chainId": 54723,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
```

**Comment by santiagorp** [comment] 2017-09-22 12:23
Following @win2win note: I installed `v3.5.1` and works.

**Comment by flyswatter** [comment] 2017-09-22 16:33
You need to make sure you specify both networkId and chainId and they are the same values.

Using an older MetaMask works because we lacked the EIP155 security feature back then.

**Comment by santiagorp** [comment] 2017-09-22 16:40
@flyswatter Thanks Dan! I'll try that. Pity I'll be missing this year's Devcon... would be great to see you all there!

**Comment by flyswatter** [comment] 2017-09-22 16:52
Yeah, I'll actually be missing it too, so we'll just have to keep attending things :)

**Comment by skozin** [comment] 2017-11-18 01:10
I've had the same issue, but specifying both `networkId` and `chainId` actually helped, thanks @danfinlay!

I've created a repo containing a pre-initialized dev chain that works with MetaMask: https://github.com/skozin/ethereum-dev-net.

However, it seems that, for some reason, Web3 in my Dapp doesn't resolve promises of transactions when pointed to MetaMask's provider, even though MetaMask shows these transactions as completed and I can see them recorded to blockchain. This reproduces both on my local dev net and on Ropsten test net. But this is a different issue, I guess.

**Comment by nujabes403** [comment] 2018-04-23 09:32
@skozin Why specifying `config.eip155block` and `networkId` equal to `config.chainId` makes it work..? I couldn't guess any reason for it.

**Comment by skozin** [comment] 2018-04-23 13:24
@nujabes403 `config.eip155block` helps because it enables EIP 155 transaction signing, which Metamask uses. I don't know why it doesn't work when `networkId` is not the same as `config.chainId`.

**Comment by phucnguyenit** [comment] 2018-05-09 05:12
@skozin & @danfinlay 👍 Confirmed. it works like a charm when networkId is equal to config.chainId.

**Comment by 2946697215** [comment] 2018-08-23 06:33
@skozin it solved my problem!

**Comment by waylandc** [comment] 2018-09-13 03:38
Can someone help please? I'm getting same errors but have tried everything mentioned in this thread without success.

Here's a screenshot showing that my chainid and networkid are the same.

```shell
> admin.nodeInfo
{
  enode: "enode://15c14ef0690fe92f187e5eac07ef2c94afc597fd333d0f07b569f4cae2aecc50f56c685af8abe5283a36811e4d288928b8f3bc1f2c64eb9c7918a054ae52c7ea@[::]:30303",
  id: "15c14ef0690fe92f187e5eac07ef2c94afc597fd333d0f07b569f4cae2aecc50f56c685af8abe5283a36811e4d288928b8f3bc1f2c64eb9c7918a054ae52c7ea",
  ip: "::",
  listenAddr: "[::]:30303",
  name: "Geth/v1.8.14-stable-316fc7ec/linux-amd64/go1.10.3",
  ports: {
    discovery: 30303,
    listener: 30303
  },
  protocols: {
    eth: {
      config: {
        byzantiumBlock: 4,
        chainId: 993,
        clique: {...},
        eip150Block: 0,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0
      },
      difficulty: 157,
      genesis: "0x62f58463e4612edb857fd89e9e0658f603936ea73b3ddf3ae0e26389bd23ba54",
      head: "0x99544057225eb6b4b18a3ee3a57b3eb921b99a170dd62ce33ef763dbd3e9c4e6",
      network: 993
    }
  }
}
```

And here you can see I've set eip155Block in my genesis to 0.

```shell
root@geth-dev-miner-3:/opt# cat genesis.json
{
  "config": {
    "chainId": 993,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 4,
    "clique": {
      "period": 15,
      "epoch": 30000
    }
  },
```

**Comment by JacobCooley** [comment] 2018-12-26 18:13
Getting this error too, it's hurting my brain because I've tried everything.  It went away for a few days and now it's back

**Comment by IamChuancey** [comment] 2019-04-14 03:44
@waylandc@JacobCooley
- Step First:
  This comment by skozin and the files in the repo he provided help me to fix the 
  problem:

  https://github.com/MetaMask/metamask-extension/issues/2015#issuecomment-345405915

  Basically, make sure to set in the genesis.conf :

  eip155Block:0 and chainId equals to the networkId (used with geth)

- Step Second:
  if you had fixed the problem mentioned above (the problem mentioned in Step First), then it Most likely is you start local network in a wrong way like:
```
geth --ipcpath test-chain-directory/geth.ipc --datadir test-chain-directory --dev --rpc --rpccorsdomain "*" console
```
you should cut the `--dev` off! Because using Geth with the 'dev' flag to avoid needing a genesis block and a DAG, you should start your local network Like below:
```
geth --ipcpath test-chain-directory/geth.ipc --datadir test-chain-directory --rpc --rpccorsdomain "*" 
```
G
ood luck!

**Comment by LikeYears** [comment] 2019-08-16 18:30
@danfinlay Hello, sir. Can you tell me how to set the chainID is equal to networkID when I use truffle, ganache ang metamask as develop tool. I only know I can set networkID in 'truffle-config.js', but I cannot find where chainID is. Thanks for your kind help!

**Comment by danfinlay** [comment] 2019-09-16 22:44
@LikeYears  You should be able to just set the `--networkId` flag in ganache-cli to set the chainId also.

@bayanhd
Please open a new issue for the error you are encountering, with detailed instructions on reproducing the issue, ideally a sample dapp that our team can visit and try.

**Comment by livingrock7** [comment] 2019-12-11 13:48
@bayanhd  Were you able to solve the issue?

**Comment by livingrock7** [comment] 2019-12-13 12:09
I resolved the issue. check admin.nodeInfo if your chain id and network id is different you have a problem. I restarted geth in 10 mins with new genesis and got it working in metamask
