### ISSUE TITLE
network bar showing 9545 when being connected to 8545

### ISSUE THREAD

**Issue by simibac** [MetaMask/metamask-extension#6436] opened 2019-04-10 16:27 UTC
**Describe the bug**
network bar showing 9545 when being connected to 8545

**To Reproduce**
1. run ganache-cli
2. connect metamask to it through localhost 8545
3. check networkbar

**Expected behavior**
show correct port number

**Screenshots**
<img width="357" alt="Bildschirmfoto 2019-04-10 um 18 21 14" src="https://user-images.githubusercontent.com/15369592/55896111-da3eb500-5bbd-11e9-9a54-63a609b4c1e4.png">

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - MetaMask Version 6.3.1

**Additional context**

**Comment by tmashuang** [comment] 2019-04-10 16:29
Duplicate of https://github.com/MetaMask/metamask-extension/issues/6321

**Closed** 2019-04-10 16:29 UTC
