### ISSUE TITLE
Error: The current provider doesn't support subscriptions: MetamaskInpageProvider (events)

### ISSUE THREAD

**Issue by coryl** [MetaMask/metamask-extension#2601] opened 2017-11-17 22:03 UTC
I'm trying to listen to events with web3:

```
  incrementEvent = existingContract.events.allEvents(function(error, event){
                  if (error) console.log(error);
                  console.log("event is: " + event);
                })
```
Console logs:

```
Error: The current provider doesn't support subscriptions: MetamaskInpageProvider
    at Subscription.subscribe (bundle.js:45443)
    at Contract._on (bundle.js:48777)
    at (index):48
    at tryCatcher (bundle.js:44235)
    at Promise._settlePromiseFromHandler (bundle.js:42267)
    at Promise._settlePromise (bundle.js:42325)
    at Promise._settlePromise0 (bundle.js:42370)
    at Promise._settlePromises (bundle.js:42453)
    at bundle.js:39334
    at MutationObserver.<anonymous> (bundle.js:43502)
(index):50 event is: null
```
Any ideas? Does metamask not support events? Thanks

**Comment by danfinlay** [comment] 2017-11-21 20:41
web3 1.0 requires a websocket provider, which we don't have yet.

Closing as a duplicate of #2350.

**Closed by danfinlay** 2017-11-21 20:41 UTC

**Comment by elie222** [comment] 2018-03-06 11:23
Any idea when this will be supported?

**Comment by danfinlay** [comment] 2018-03-06 17:41
No, but we know it's very desired. Just balancing important issues, sorry. Follow issue #2350, not this one, please.
