### ISSUE TITLE
User Denied Transaction Error doesn't get caught in callback function although it logs by inpage.js in console.

### ISSUE THREAD

**Issue by AntonCorbijn** [MetaMask/metamask-extension#4434] opened 2018-05-31 19:29 UTC
Bug Reports:
After installed latest version (4.7.0) of Metamask, when rejecting transaction, MetaMask throws error "User denied transaction signature" by inpage.js in chrome console but it was not caught in callback as exception. 

  *  Expected Behavior
      I would expect to catch the error inside of callback. For example
      TestContract.callFunction({from: defaultAddress}, function (err, res) {
             // handle err here
             console.log(err) 
      });
  *  Actual Behavior
      I got nothing from console.log(err) although I can see "User denied transaction signature" error log by inpage.js in console.
  *  Browser Used
      Chrome V66.0.3359.181
  *  Operating System Used
      OSX 10.11.6
![screen shot 2018-05-31 at 9 26 03 pm](https://user-images.githubusercontent.com/32306632/40803609-54a60c4a-6519-11e8-9f65-0621b9aaee56.png)

**Comment by Artod** [comment] 2018-06-01 02:20
Same issue

**Comment by andrewsource147** [comment] 2018-06-01 04:29
Same, team please look at this. I added try catch but it didn't work

**Comment by Arctek** [comment] 2018-06-01 04:42
This breaks a number of dApps as it leaves them in an resolved state, waiting for the promise to fulfill or throw.

**Comment by jjingrong** [comment] 2018-06-01 06:10
+1
This was working pre `4.7.0`

**Comment by wjmelements** [comment] 2018-06-01 06:12
Perhaps 71a6e97327a4c759942784ee81505e3bc5ed545e

**Comment by wjmelements** [comment] 2018-06-01 06:16
I will try a build that reverts https://github.com/MetaMask/metamask-extension/pull/4384

**Comment by yuxulong00** [comment] 2018-06-01 06:58
Same issue

**Comment by wjmelements** [comment] 2018-06-01 07:27
I am somewhat confident that this is related to `createErrorMiddleware` from https://github.com/MetaMask/metamask-extension/pull/4245

**Comment by wjmelements** [comment] 2018-06-01 07:34
whoops it's from ce2834400ca202d5767c3d896407ac565fadfc14, not 4245

**Comment by wjmelements** [comment] 2018-06-01 07:34
https://github.com/MetaMask/metamask-extension/pull/4199

**Comment by wjmelements** [comment] 2018-06-01 07:43
This is a dupe of #4431

**Closed by wjmelements** 2018-06-01 07:43 UTC
