### ISSUE TITLE
8.0.1: "Permissions request already pending; please wait" 

### ISSUE THREAD

**Issue by jmahhh** [MetaMask/metamask-extension#8918] opened 2020-07-04 03:16 UTC
**Describe the bug**
When trying to activate ethereum via the `web3-react` package (which uses `ethereum.enable`), an error `MetaMask - RPC Error: Permissions request already pending; please wait.` is thrown and does not resolve. 

**To Reproduce**
1. Go to niftex.com
2. Click on "No Wallet Connected", select Metamask
3. See error

**Expected behavior**
There were no issues trying to activate Metamask ethereum before 8.0.1. 

`
 MetaMask - RPC Error: Permissions request already pending; please wait. 
Object { code: -32002, message: "Permissions request already pending; please wait.", stack: "i@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:1186257\ns@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:1188421\nresourceUnavailable@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:1189232\nrequestUserApproval@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:53237\nrequestPermissionsMiddleware@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:2313320\nproviderMiddlewareFunction@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:2307710\n_requestPermissions/<@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:47381\n_requestPermissions@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:47283\n[25]</r.default/<@moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/background.js:1:54377\n" }
`

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Firefox Browser 78.0.1 (64-bit)]
 - MetaMask Version 8.0.1

**Comment by tmashuang** [comment] 2020-07-04 03:33
Can we get more information such as `web3-react` version, and a snippet of the implementation? 
From the [Codesandbox](https://codesandbox.io/s/github/NoahZinsmeister/web3-react/tree/v6/example?fontsize=14&hidenavigation=1&theme=dark) provided in the[ README of `web3-react`](https://github.com/NoahZinsmeister/web3-react), I am able to successfully use the package to connect.

**Comment by jmahhh** [comment] 2020-07-04 04:12
Hi @tmashuang the `web3-react` is latest versions:
```
│+ @web3-react/injected-connector@6.0.7
│+ @web3-react/walletconnect-connector@6.1.4
│+ @web3-react/core@6.1.1
│+ @web3-react/network-connector@6.1.3                                                                                                                                                                                                                                                                                                                                                                                                      
```

the snippet:
```
activate(connector, undefined, true).catch(error => {
			if (error instanceof UnsupportedChainIdError) {
				activate(connector);
			} else {
				console.log('activate error: ', error);
				this.setState({ pendingError: true });
			}
		});
```

**Comment by tmashuang** [comment] 2020-07-04 05:17
`connector` is `injected-connector`, yeah? How is this snippet getting initialized? Seems is might be a race condition. I see in the codesandbox mentioned wraps the activate in an `isAuthorized` promise, might be beneficial to do the same in your example. https://github.com/NoahZinsmeister/web3-react/blob/v6/example/hooks.ts#L12-L20

**Comment by jmahhh** [comment] 2020-07-04 05:44
Actually we use that exact same code for eager connects, what I pasted above is for manual connects. The error appears to happen for both. My colleague appears to have no problems so not sure what's going on. What's the context for this error? I haven't seen it before.

**Comment by tmashuang** [comment] 2020-07-04 05:47
I think, I've found a solid reproduction on this issue and will write up a new issue describing it and link this one. Essentially, it is an issue with subsequent calls to 'eth_requestAccounts' before handling the first.

**Comment by tmashuang** [comment] 2020-07-04 05:49
If you are having this issue, and want to get past it, just turn off and on the extension/addon and reconnect.

**Comment by jmahhh** [comment] 2020-07-04 05:56
I looked a little more at the eager connect, which I guess is at the source - it seems to be linked to these two:
```
ethereum.on('chainChanged', handleChainChanged)
ethereum.on('networkChanged', handleNetworkChanged)
```

![image](https://user-images.githubusercontent.com/13865534/86506054-16f65d80-bdbb-11ea-8a7c-69bf9802a164.png)

**Comment by jmahhh** [comment] 2020-07-04 06:02
hmm if I turn Metamask on and off I get: 
```
 Uncaught Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.
    [1]</< moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/inpage.js:1
    [1]< moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/inpage.js:1
    i moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/inpage.js:1
    e moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/inpage.js:1
    <anonymous> moz-extension://ddf63037-6619-43eb-bed3-7f7ec458fb4e/inpage.js:1
```
if then trying a manual connect, the wallet modal gets stuck on `initializing....`
and reloading the page just results in the initial error again.

**Comment by tmashuang** [comment] 2020-07-04 06:29
Unless you have multiple MM providers, this shouldn't happen and somewhere there is probably some caching happening. Also, I documented the root cause of the issue link/mentioned above, which happens when subsequent calls to connect happen without user interaction of the first. The screenshot of your console leads to me believe that the app requests to connect three times, one initial, then two more times with the error. We will pursue the issue from our end, but also recommend only requesting to connect once.

**Comment by Nokhal** [comment] 2020-07-06 19:46
Core issue is await ethereum.enable returning accounts before proper permissioning have been done on them.

**Comment by Gudahtt** [comment] 2020-07-06 21:59
@Nokhal: I haven't seen anything like that in my testing. If you could elaborate, or perhaps provide a test case showing what you mean, that would be greatly appreciated!

@jmahhh: v8.0.3 has been released to Firefox, and this includes a fix to the bug where multiple successive permission requests would interfere with the first one.

The error in the title ("Permissions request already pending; please wait") will still be thrown if you attempt to connect multiple times, but the first request should now resolve correctly. Does this solve your problem?

**Comment by Nokhal** [comment] 2020-07-20 16:51
@Gudahtt 
Calling ethereum.enable() again AFTER the user click on connect on metamask but BEFORE the allowance process is finished will close the "allow" window and make the user unable to finalize connection without disabling-reenabling metamask in the addons section of their browser.

**Comment by Gudahtt** [comment] 2021-01-13 20:06
I don't think this bug is present in the latest version of MetaMask. I'm going to close this for now, but please let us know if you're still experiencing this problem!

@Nokhal it sounds like what you're describing is a separate issue. I've attempted to reproduce this problem as well, and I wasn't able to. If you have the time to spare and are still able to reproduce that issue, could you open a new issue and maybe provide further guidance on how to reproduce it? Thanks!

**Closed by Gudahtt** 2021-01-13 20:06 UTC
