### ISSUE TITLE
[Bug]: Multichain - when there are three unapproved transactions across different networks, confirming the first one causes MetaMask to break with an error: 'Message: Minified React error #185; ...'

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25596] opened 2024-06-29 06:09 UTC
### Describe the bug

When there are three unapproved transactions across different networks, confirming the first one causes MetaMask to break with an error: `Message: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`
STX toggle is OFF.
[Latest v12.0.0 build ]([https://github.com/MetaMask/metamask-extension/commit/d9c4f7514532540a2567bbc65802af3797c5ec5c])

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/8df97df9-efeb-4201-a152-f6433a70fd1a

<img width="347" alt="Screenshot 2024-06-29 at 02 08 41" src="https://github.com/MetaMask/metamask-extension/assets/104780023/b3a0c2b3-4781-4d6a-8b59-63982dba4cc3">

### Steps to reproduce

1. Connect to Polygon on Uniswap
2. Connect to BNB Chain on Pancakeswap
3. Connect to Linea on Sushiswap
4. Start a transaction on Uniswap, do not approve
5. Start a transaction on Sushiswap, do not approve
6. Start a transaction on Pancakeswap
7. Blue badge on MetaMask icon displays '3' transaction
8. Access the first transaction (created on Polygon) and confirm it
9. See the error

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment] 2024-06-29 20:42
Another scenario where the `Minified React error #185` doesn't happen second transaction is created (and submitted) on the wrong network:
1. Start tx on BNB Chain (Pancakeswaps), do not approve
2. Start tx on Linea (Sushiswaps), do not approve
3. Start tx on Ethereum (Uniswap)
4. Approve first transaction (BNB)
5. I start second tx on mainnet from Sushi, don't approve
6. MM popup showing next tx on Ethereum (nonce 1835 in the video, the amount (0.000 000 1) matches second tx, confirmation page shows sushi.com) confirm this transaction
7. MM popup shows third transaction (nonce 1836, amount and dapp match the third transaction)
8. Within the Activity you can see 1 tx on BNB Chain (I think I had 1 previous tx on BNB), two txs on Ethereum, no transaction on Linea.


https://github.com/MetaMask/metamask-extension/assets/104780023/bad15681-e671-465b-ae3c-a5f6ab5254ad


First tx:



<img width="336" alt="firstTx" src="https://github.com/MetaMask/metamask-extension/assets/104780023/2d3645df-fe30-44cd-a49a-9f1c30dcb269">

Second tx:

<img width="332" alt="secondTx" src="https://github.com/MetaMask/metamask-extension/assets/104780023/7f8e9081-555c-41f1-b61e-954027b31baf">


Third tx:

<img width="333" alt="thirdTx" src="https://github.com/MetaMask/metamask-extension/assets/104780023/6eb304ee-eb19-4de9-a310-c649e34ee53a">

**Comment by sleepytanya** [comment] 2024-07-01 05:06
The bug is present in this v12.0.0 build as well: https://github.com/MetaMask/metamask-extension/pull/25098#issuecomment-2198759615

**Comment by darkwing** [comment] 2024-07-01 14:58
I merged a PR for this exact scenario last week.  🤔. Will track this down ASAP https://github.com/MetaMask/metamask-extension/pull/25536

**Comment by darkwing** [comment] 2024-07-02 21:09
I can no longer reproduce any of these issues after this PR.https://github.com/MetaMask/metamask-extension/pull/25641

**Comment by sleepytanya** [comment] 2024-07-04 05:02
@darkwing 

I think it looks acceptable for now? (correct me if I'm wrong). I don't see any errors in all scenarios I've tried.



https://github.com/MetaMask/metamask-extension/assets/104780023/7d9d1d6b-1a76-4d24-87bc-3a803d7eac19

**Comment by bschorchit** [comment] 2024-07-05 19:37
Popup behavior above is being addressed by this PR: https://github.com/MetaMask/metamask-extension/pull/25619

**Comment by bschorchit** [comment] 2024-07-05 19:38
Should we close this issue since it was reported to be fixed by this PR: https://github.com/MetaMask/metamask-extension/pull/25641 ?

**Comment by sleepytanya** [comment] 2024-07-05 20:02
@bschorchit I think so!

**Comment by darkwing** [comment] 2024-07-09 13:57
Closing with Tanya's recommendation.

**Closed by darkwing** 2024-07-09 13:57 UTC
Labels: type-bug, Sev2-normal, release-blocker, team-wallet-ux, regression-RC-12.0.0
