### ISSUE TITLE
Local network shows incorrect name

### ISSUE THREAD

**Issue by jefflau** [MetaMask/metamask-extension#6385] opened 2019-04-02 08:48 UTC
**Describe the bug**

Sometimes when I have many custom RPC endpoints on Metamask, when I go back to the private network, it shows the incorrect name (usually one of my custom endpoint names)

**To Reproduce**
Create a custom RPC endpoint (or many custom RPC endpoints). Start to use a local private ganache node and choose the private network in Metamask. Check the name of the network.
**Expected behavior**

Private network shows the private network name, not the custom endpoint name

**Screenshots**
<img width="371" alt="Screenshot 2019-04-02 at 16 43 54" src="https://user-images.githubusercontent.com/1221141/55388903-bc8ea180-5566-11e9-8a17-6ef44770d330.png">

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - MetaMask Version 6.3.1

**Comment by tmashuang** [comment] 2019-04-10 16:29
Closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/6321

**Closed by tmashuang** 2019-04-10 16:29 UTC
Labels: N02-needsReproduction, T00-bug
