### ISSUE TITLE
[Bug]: Unable to save advanced gas settings when interacting with test dapp contracts - SAVE button greyed out

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#27608] opened 2024-10-03 18:48 UTC
### Describe the bug

When trying to interact with failing and multisig test dapp contracts, the SAVE button on the advanced gas settings screen is greyed out.

### Expected behavior

Should be able to click the SAVE button on the advanced gas settings screen.

### Screenshots/Recordings

https://github.com/user-attachments/assets/ac2d9880-7966-4219-8297-2d6695880876

https://github.com/user-attachments/assets/95900844-7a01-47e4-bcd2-f9d04447beb2

### Steps to reproduce

1. Connect to the test dapp
2. Deploy a failing contract or a multisig contract
3. Send a failing transaction or send to multisig address
4. Edit the gas fees and select Advanced
5. See that the SAVE button is greyed out

### Detection stage

During release testing

### Version

12.4.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

I obtained the build from [here](https://github.com/MetaMask/metamask-extension/pull/27287)

**Comment by bschorchit** [comment] 2024-10-08 16:58
I was able to reproduce it for send failing transaction on both v12.4 and v12.3.1

**Comment by bschorchit** [comment] 2024-10-08 17:00
I think the issue is due to the gas limit being higher than our limits.
<img width="329" alt="Screenshot 2024-10-08 at 14 00 22" src="https://github.com/user-attachments/assets/85a85e60-02ac-45af-8725-0f5200ae2561">

**Comment by bschorchit** [comment] 2024-10-08 17:06
Related with https://github.com/MetaMask/metamask-extension/issues/27089 that was fixed on with https://github.com/MetaMask/metamask-extension/pull/27165

**Comment by bschorchit** [comment] 2024-10-08 17:09
I have tested now with the build from this PR https://github.com/MetaMask/metamask-extension/pull/27165 and noticed the issue is fixed so closing this issue.

**Closed by bschorchit** 2024-10-08 17:09 UTC
Labels: type-bug, Sev2-normal, regression-prod-*, team-confirmations
