### ISSUE TITLE
Address case is inconsistent

### ISSUE THREAD

**Issue by digitaldonkey** [MetaMask/metamask-extension#5826] opened 2018-11-26 13:31 UTC
**Describe the bug**

`await ethereum.enable()` returns the address in different upper/lower case compared to 
`await this.web3.eth.getAccounts()`.

- ethereum.enable returns address in lowercase only
- this.web3.eth.getAccounts() returns address in mixed case

--> The address is returned inconsistently.

**Expected behavior**
Address should always be returned in the same format, to detect account changes properly.

**Workaround**
You can work around with `web3.toChecksumAddress('INSERT ADDRESS HERE')`

**References** 
#4287,  #4003. Maybe #4287

**Comment by bdresser** [comment] 2018-11-26 16:13
also relates to https://github.com/MetaMask/metamask-extension/issues/3514

**Comment by gohuygo** [comment] 2018-11-28 19:48
I can't seem to reproduce this issue (currently on 5.0.3):

```
    const { web3, ethereum } = window;
    ethereum.enable().then(accounts =>console.log("enable: ", accounts))
    web3.eth.getAccounts((err, accounts) => {console.log("getAccounts: ", accounts)})

    getAccounts:  ["0xa20ebf33b7c22a7d0b1fd19945fd1669f53d556a"]
    enable:  ["0xa20ebf33b7c22a7d0b1fd19945fd1669f53d556a"]
```

Can you direct me to where `ethereum.enable()` is declared in the source code? 

I looked into `getAccounts()` and it looks like we normalize to lowercase addresses with `eth-sig-util.normalize()` - https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/preferences.js#L280

**Comment by bitpshr** [comment] 2019-01-09 15:44
Thanks for taking the time to file this @digitaldonkey. I double checked and it looks like @gohuygo is correct, both web3 and our keyring controller return checksummed addresses. I manually verified in the console as well and couldn't reproduce the issue.

Closing, but feel free to reopen if you can add reproduction steps.

**Closed** 2019-01-09 15:44 UTC
Labels: P4-someday, T00-bug

**Comment by billtlee** [comment] 2019-03-20 15:32
I am running into this case.  Metamask listed the wallet as mix case but ethereum.enable returns the address as lowercase.  Why is it being normalized to lowercase when metamask stores the wallet address as mix case?  Is ethereum address case sensitive?  What is the convention?

**Comment by kuzdogan** [comment] 2020-01-27 12:21
This is an issue with the [web3.js](https://github.com/ethereum/web3.js/) library and not Metamask.

The code by @gohuygo does not reproduce the mismatch as it both lines use the web3 injected by Metamask. However, I suppose @digitaldonkey was using the web3.js library. If you create a web3 object with 
```
import Web3 from 'web3';

const web3 = new Web3(window.ethereum);
```

the following code will return checksum capitalized addresses:
```
accounts = await web3.eth.getAccounts();
console.log('accounts'); // 0xAA6042aa65eb...3bd09c5DFe94
```
