### ISSUE TITLE
Multiple click on confirm button trigger multiple transaction

### ISSUE THREAD

**Issue by peterkwidjaja** [MetaMask/metamask-extension#4941] opened 2018-08-03 02:48 UTC
![image](https://user-images.githubusercontent.com/7549500/43621401-c8005f7a-9709-11e8-9404-04954a7cee15.png)

In the screen above, I can click the "confirm" button multiple times before it shows the loading spinner. Only 1 transaction is recorded in MetaMask, but there are actually multiple transactions recorded on etherscan.

**Comment by bdresser** [comment] 2018-08-03 17:41
@peterkwidjaja closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/4532. We'll continue to investigate, thanks for reporting.

**Closed by bdresser** 2018-08-03 17:41 UTC
