### ISSUE TITLE
Blank screen on transaction confirmation popups

### ISSUE THREAD

**Issue by corollari** [MetaMask/metamask-extension#5519] opened 2018-10-15 00:40 UTC
**Describe the bug**
The transaction confirmation popup which appears on a new window is blank/empty

**To Reproduce**
1. Go to https://faucet.metamask.io/ (or any any other page that triggers an ethereum transaction)
2. Click on "1 ether"
3. The confirmation popup which appears on a new window is empty/blank
4. Upon clicking with the right button on the misbehaving popup, the popup is displayed properly

**Expected behavior**
The window popup should display the transaction confirmation screen instead of a blank screen

**Screenshots**
![image](https://user-images.githubusercontent.com/32309574/46924109-6dd56580-d021-11e8-86d4-741cbee4841d.png)

**Browser details (please complete the following information):**
 - OS: Fedora 28
 - Browser: Firefox
 - MetaMask Version: 4.9.2
 - Beta UI

**Additional context**
It is different from the other blank screen reports (such as #4894) in that in those reports the blank screen appears upon clicking the extension's icon and covers the in-page popup, while in mine the blank screen appears on the confirmation popup that appears on a different window and it is solvable by right clicking on the popup.

**Comment by bdresser** [comment] 2018-10-15 16:43
Thanks for reporting @corollari 

First, could you check if there are any errors in the popup logs or background logs? ([See here ](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue )for instructions.)

Then, could you download the latest release of MetaMask from our [releases page](https://github.com/MetaMask/metamask-extension/releases) and see if the issue persists?

**Comment by tmashuang** [comment] 2018-10-15 18:03
Related, https://github.com/MetaMask/metamask-extension/issues/4796. Do not yet know the root cause in some Linux distros.

**Comment by corollari** [comment] 2018-10-15 18:11
@tmashuang I just tried and it does, resizing the popup causes the content to be shown.

**Comment by corollari** [comment] 2018-10-15 18:16
It seems that my issue could also be a duplicate of #2746, should I close it or keep it in order to continue providing information?

**Comment by estebanmino** [comment] 2018-10-15 18:19
@tmashuang I've seen this issue with other extensions that uses popups as well, if I resize it works. I believe is something related to Linux Firefox.

**Comment by corollari** [comment] 2018-10-15 18:29
@estebanmino Then we should file a bug in the Firefox bugtracker, in a few weeks I could try to create a minimal test case and submit it.

**Comment by JSON-LEE13** [comment] 2018-10-16 14:40
@estebanmino @tmashuang  https://consensys.zendesk.com/agent/tickets/10633

**Comment by corollari** [comment] 2018-11-18 06:22
It seems that the bug has disappeared with the 5.0.2 release. Tested it on the computer in which I originally found the bug and it's working properly.

**Comment by bdresser** [comment] 2018-11-19 22:44
Great! Closing for now, holler if it re-appears or if others are still experiencing this.

**Closed by bdresser** 2018-11-19 22:44 UTC
Labels: N02-needsReproduction, T00-bug
