### ISSUE TITLE
MetaMask disappeared, "reload" option in extensions

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6219] opened 2019-02-27 22:30 UTC
**Describe the bug**
I had just confirmed several transactions on a private network, opened MetaMask to verify that the transactions had been confirmed on-chain (they had) and viewed the version number to file issue #6218.  I then returned to my dapp in Chrome and found the MetaMask icon gone.  Visiting chrome://extensions/, the on/off slider was replaced by a reload button: 

![screenshot with reload button](https://user-images.githubusercontent.com/563406/53526766-0e00c800-3ab3-11e9-985a-a2f5908d80ca.png)

I could not find any way to inspect a console for the background page.  Clicking the reload button, the display changed to this: 
![normal screenshot](https://user-images.githubusercontent.com/563406/53526820-2ffa4a80-3ab3-11e9-9fc2-3f5c67c554a4.png)

Returning to my dapp and reloading the page, MetaMask popped up a login interface.  I tried to switch to a different tab to get a cleaner background for a screenshot and it disappeared.  I could not get it back.  The icon remained gone. 

Relaunching Chrome, I got the login popup, entered my password, and was asked if I wanted to connect the dapp to my account, though I'd previously authorized it and successfully confirmed transactions. 

Relaunching Chrome again didn't help.  I had to then click in the three dots on the right of the toolbar, find the Metamask icon there, right-click, and "Show In Toolbar" again.

This is unfortunately hard to reproduce.  However, I'm confident there was not an accidental toolbar edit removing the icon, and the "Reload" button on the Extensions page indicates something went wrong in MetaMask.  If I see it again, I'm not sure where to look for more details. 

**Browser details (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: Chrome 72.0.3626.109 (not in incognito mode)
 - MetaMask Version: 6.1.0

**Comment by bdresser** [comment] 2019-03-05 19:38
thanks for reporting @wbt. I've only seen behavior like this when the user rejected permissions that the extension asked for, although our permission list hasn't changed in a while. 

We'll keep an eye out. In the meantime if you see this again or come up with clues to repro, let us know

**Comment by wbt** [comment] 2019-03-05 23:04
I was recently doing some work completely outside Chrome, having no interaction with the browser (though it was open in the background), and got this popup alert: 
![MetaMask has crashed.](https://user-images.githubusercontent.com/563406/53843349-12742780-3f70-11e9-8b80-c726c8e02fb2.png)
By the time I finished taking the screenshot, it was gone.

Opening Chrome, the MetaMask icon was gone, not even visible in the three-dots dropdown.  In chrome://extensions the reload button was there, as before, with the prior effect.  On returning to the dapp and reloading the page, I got a MetaMask login interface and then request to connect the dapp to my account (again, though it was previously authorized). After clicking connect, the fox icon was back where it used to be. 

It also seems that when MetaMask disappears, it is replaced by the icon of the next extension, normally hidden.  What that extension was varied between the previous and most recent occurrence. 

When I went to Help->About Google Chrome for the version number, it said:
>Version 72.0.3626.119 (Official Build) (64-bit) 

and
>Nearly up to date! Relaunch Google Chrome to finish updating.

after a brief spinner display to the left.  I don't know if Chrome updates have anything to do with this, though either way it's MetaMask showing as not stable.

**Comment by wbt** [comment] 2019-05-24 17:45
I just saw MetaMask disappear from Chrome again, and noted Chrome had an update pending, to version 74.0.3729.169.  Steps to reproduce might involve installing an older version, running MetaMask, letting Chrome download the update but not applying it yet, and waiting for MetaMask to just disappear.

**Comment by danfinlay** [comment] 2021-01-05 20:51
This sounds like it had been a hard crash for some reason that we don't know and so can't reproduce. We have since refactored some of the internal components that manage dapp connection state, and so it's likely some of the problems you had are now fixed.

Please let us know if they aren't, closing for now.

**Closed by danfinlay** 2021-01-05 20:51 UTC

**Comment by olbapnairda** [comment] 2021-05-06 17:53
It's asking for reload permanently. It's completely annoying and disfunctional
