### ISSUE TITLE
Gas price always display 0 when doing a transaction with smart contract

### ISSUE THREAD

**Issue by carloftg** [MetaMask/metamask-extension#6772] opened 2019-06-29 03:32 UTC
Using windows 7, chrome Version 74.0.3729.169 (Official Build) (64-bit) , Metamask version 6.7.1
Steps :
Interact with a smart contract to initiate a transaction, the gas price is not set and everything 0, there is no way to submit the transaction except by magically guessing how much gas and price are necessary in the advanced tab (see screenshot attached)
![metamask-bug](https://user-images.githubusercontent.com/52339276/60379214-e8d49400-9a69-11e9-9c04-f52c0e8b0f20.jpg)

**Comment by elliotolds** [comment] 2019-06-30 06:55
I've been experiencing the same issue over the last few days. I'm running Linux Mint 18, Chrome version 74.0.3729.131 (Official Build) (64-bit). Metamask version 6.7.1.

I also verified this on a different Linux Mint 18 laptop running Chrome 75.0.3770.100 (Official Build) (64-bit). Also Metamask 6.7.1. 

This doesn't occur when using Firefox 67.0.4 (64-bit) (also with Metamask 6.7.1).

When going to the 'advanced' gas tab, I see Metamask estimating a gas price but the gas limit is blank. See screenshot. My coworker and I have also seen Metamask wildly overestimate the gas limit intermittently over the past several days, for instance estimating a 7.5 million gas limit when I'm calling a function that takes at most 50,000 gas. (And when I actually send the transaction, it does end up taking less than 50,000 gas).

Metamask will have a blank gas limit about 80% of the time. The other 20% Metamask is able to somehow figure out a gas limit.

![image](https://user-images.githubusercontent.com/5849793/60393355-f1a88280-9ac8-11e9-87e5-930ce2fe3166.png)

**Comment by alsco77** [comment] 2019-07-01 06:51
Experiencing the same issue with MM 6.7.1 on Firefox,Chrome and Brave. 

This is occurring on our batched approval transactions

**Comment by danfinlay** [comment] 2019-07-01 20:19
Thanks for the reports, we've been investigating this, and we were unable to reproduce the issue once we tested on our latest `develop` build.

This build includes [an improvement](https://github.com/MetaMask/metamask-extension/pull/6713) to how we validate and normalize transaction parameters, and it seems it may have fixed this issue.

Could someone experiencing this problem please try downloading [one of our automated builds of this new release candidate](https://github.com/MetaMask/metamask-extension/pull/6780#issuecomment-507409597), and see if you still experience the issue?

**Comment by 382303784** [comment] 2019-07-02 08:57
> 过去几天我一直遇到同样的问题。我正在运行Linux Mint 18，Chrome版本74.0.3729.131（官方构建）（64位）。Metamask版本6.7.1。
> 
> 我还在运行Chrome 75.0.3770.100（官方版本）（64位）的另一台Linux Mint 18笔记本电脑上验证了这一点。同样是Metamask 6.7.1。
> 
> 使用Firefox 67.0.4（64位）（也使用Metamask 6.7.1）时不会发生这种情况。
> 
> 我在Kovan，Rinkeby和Mainnet上看过这个。
> 
> 当进入“高级”燃气标签时，我看到Metamask估计汽油价格，但燃气限制是空白的。见截图。我的同事和我也看到Metamask过去几天间歇性地过度估计了气体限制，例如当我调用一个最多需要50,000气体的功能时估计750万气体限制。（当我实际发送交易时，它的最终消耗量不到50,000）。
> 
> Metamask将在80％的时间内具有空白气体限制。另外20％Metamask能够以某种方式计算出气体限制。
> 
> ![图片](https://user-images.githubusercontent.com/5849793/60393355-f1a88280-9ac8-11e9-87e5-930ce2fe3166.png)

俺也一样

**Comment by 382303784** [comment] 2019-07-02 08:58
> Using windows 7, chrome Version 74.0.3729.169 (Official Build) (64-bit) , Metamask version 6.7.1
> Steps :
> Interact with a smart contract to initiate a transaction, the gas price is not set and everything 0, there is no way to submit the transaction except by magically guessing how much gas and price are necessary in the advanced tab (see screenshot attached)
> ![metamask-bug](https://user-images.githubusercontent.com/52339276/60379214-e8d49400-9a69-11e9-9c04-f52c0e8b0f20.jpg)

俺也一样

**Comment by thelostone-mc** [comment] 2019-07-03 15:54
From the Gitcoin team here ! 
same issue here
Gas price is set to 0 cause transactions to fail 

metamask :  6.7.1
Network : rinkeby
OS : mac
browser : brave / chrome 

Will leave an update after trying out with 6.7.2

**Comment by danfinlay** [comment] 2019-07-03 19:27
We have a new build that we're more confident fixes this issue, we'll be deploying it soon, anyone who'd like to check if they can repeat the issue can try it here:
https://github.com/MetaMask/metamask-extension/pull/6786#issuecomment-508225062

**Comment by danfinlay** [comment] 2019-07-03 23:45
Should be fixed in 6.7.2, which is rolling out via auto-update to all Chrome and Firefox users now. Let us know if you still experience the issue after version 6.7.2.

**Closed by danfinlay** 2019-07-03 23:45 UTC
