### ISSUE TITLE
Unable to proceed with tx bc of inaccurate/overly aggressive "Insufficient funds for gas" warning

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#13087] opened 2021-12-13 16:12 UTC
**Describe the bug**
Cannot proceed with erc20 send when user has "just enough" ETH for gas.

**Steps to reproduce (REQUIRED)**
Try sending a token with a wallet that has ~0.02 ETH or less.

**Expected behavior**
The next screen should be allowed, so the user can edit gas lower than the suggested gas estimate.  Oftentimes a tx will still be sent eventually with 20 - 40% lower gwei than current estimates.

**Screenshots**

![image](https://user-images.githubusercontent.com/16330048/145847094-781a483d-76ae-4e6f-bb5d-8dcae2bc62ee.png)

![image](https://user-images.githubusercontent.com/16330048/145847109-014c85f0-c298-4866-8f36-705e1bb840e3.png)

![image](https://user-images.githubusercontent.com/16330048/145847128-3f475bf4-dc06-4d33-be68-a67fc63255b5.png)

Notice above, this wallet has plenty enough ETH for current estimates.  I'm not sure why I'm even getting the warning to be honest.

MM v.10.7.1

Related to GH issue #10276 and #12029

**Comment by dpazdan** [comment] 2021-12-13 16:13
cc @danjm @kevinghim

**Comment by bschorchit** [comment] 2022-02-21 18:36
Here's the [design for the fix](https://www.figma.com/file/hdpaC4Hprc2oaPSMx2fs2a/Insufficient-funds-warning?node-id=47%3A423)

**Comment by danjm** [comment] 2022-03-18 11:45
![Screenshot from 2022-03-18 09-15-33](https://user-images.githubusercontent.com/7499938/158997492-e160b03f-2acc-441d-91d9-a99788e1c8e2.png)

**Comment by EHaracic** [comment] 2022-03-23 15:01
### **User Story**
As a user, I want a more informative “Insufficient funds for gas” warning on the send screen.

On the send screen, the user is shown an "Insufficient funds for gas" warning, but no other information about gas. So the user doesn't know if they have insufficient funds because prices are currently high or because the gas limit of the particular contract interaction they are attempting is high.



### Figma/Notion links
Figma link: https://www.figma.com/file/hdpaC4Hprc2oaPSMx2fs2a/Insufficient-funds-warning?node-id=47%3A423

### Acceptance criteria
- Update the Send screen according the Figma designs, screenshots below.
Consider two different scenarios:
1. The user **does not have enough** balance for gas fee before entering the amount
![image](https://user-images.githubusercontent.com/49436614/159729175-1bf9ef45-722d-49af-b270-48fbf1840a9a.png)
2. The user **have enough balance** for gas fee before entering the amount

![image](https://user-images.githubusercontent.com/49436614/159729101-d55d0103-c85a-42af-9188-8e218dcad8bb.png)

- Implement a warning message as shown on the Figma design, scrrenshot below
![image](https://user-images.githubusercontent.com/49436614/159728967-6a18e257-9eab-44cb-a843-1e2f420e9915.png)

#### Steps to Reproduce the issue

**Comment by bschorchit** [comment] 2022-03-24 13:44
A new open question: I think we should use the same warning message we implemented in other flows for consistency. I'm checking with designers and will circle back here soon.
<img width="345" alt="Screen Shot 2022-03-24 at 10 38 17" src="https://user-images.githubusercontent.com/34968356/159929081-ed2ae3cd-7400-4d8e-a312-ce4fddacdbde.png">

**Comment by danjm** [comment] 2022-04-14 12:35
- create a gas display component very similar to the one used on the confirm screen
- pass the gas display component data from state.metamask.send.gas
- display the EditGasFeePopover, AdvancedGasFeePopover, as done in ui/components/app/confirm-page-container/confirm-page-container.component.js, and they need to be inside the GasFeeContextProvider
- create a new EDIT_GAS_MODE.SEND constant
- pass the new EDIT_GAS_MODE.SEND constant somewhere
- add logic in useTransactionFunctions updateTransaciton method for the EDIT_GAS_MODE.SEND case
	- example:
		if (editGasMode === EDIT_GAS_MODES.SEND) {
	        dispatch(updateSendGasLimit(gasLimit))
	        dispatch(updateSendMaxFeePerGas(maxFeePerGas))
	        dispatch(updateSendMaxPriorityFeePerGas(maxPriorityFeePerGas))
	        return
	      }

**Comment by VSaric** [comment] 2022-11-28 16:45
Closed by: #14634

**Closed by VSaric** 2022-11-28 16:45 UTC
Labels: type-bug, area-transactions, area-gas, Sev2-normal, PS-team
