### ISSUE TITLE
More frequent and longer loading time on the send screen

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17577] opened 2023-02-02 19:01 UTC
> -When clicking on a custom token, then pressing send, the extension loads for a while, other times you need  to close the pop-up and try again
![image (13)](https://user-images.githubusercontent.com/7499938/216424668-503b8434-0b4d-415e-88a9-016856e58763.png)
![image (12)](https://user-images.githubusercontent.com/7499938/216424670-f9f32578-b37b-49db-9d43-385c93a5550d.png)

> -Changing the asset I want to send to another one from the transfer window also makes the extension load for a bi

**Comment by danjm** [comment] 2023-02-02 19:02
This is almost definitely related to updates to the assetcontroller

**Comment by bschorchit** [comment] 2023-02-10 14:16
I had initially triaged it to team confirmations, but per Dan's comment that this seems the have been caused by assetscontroller update and the new process for triaging, I've unassigned confirmations team and the team that worked on that update should be assigned to it. cc: @hilvmason

**Closed** 2023-03-08 17:35 UTC
Labels: type-bug, needs-triage, CS-reported, CS-tracking, team-extension-client, team-extension-platform
