### ISSUE TITLE
Fix compatibility with LINE Browser Extension

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4594] opened 2018-06-17 03:58 UTC
Apparently MetaMask is preventing usage of the LINE browser extension.

I was unable to reproduce on my mac.

Randy (support) was able to reproduce this issue.

We need detailed reproduction steps, including the operating system & browser.

**Comment by rdymac** [comment] 2018-06-17 17:45
I was able to reproduce this issue on a Mac by installing the extension and login in to LINE on it. Then try clicking the MetaMask extension icon and the LINE app popups with the prompt message "to leave".

macOS High Sierra 
version: 10.13.5 (17F77)

Google Chrome 
67.0.3396.87 (Build oficial) (64 bits)

[LINE Chrome Extension](https://chrome.google.com/webstore/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc) 
Version: 2.1.4
Last update: March 30th, 2018

Screencapture video: https://www.dropbox.com/s/jgnm7mgo8wpsew4/AwesomeScreenshot-2018-06-17T17-41-17-796Z.webm

**Comment by whymarrh** [comment] 2019-12-13 00:28
> I was able to reproduce this issue

What exactly is the issue? Is this still an issue? (The Dropbox video won't play for me.)

**Comment by Gudahtt** [comment] 2021-01-06 17:10
I'll close this for now, since it's not clear what the problem is here or whether it's still outstanding.

**Closed by Gudahtt** 2021-01-06 17:10 UTC
Labels: T00-bug
