### ISSUE TITLE
Restoring with seed phrase removes accounts from UI, pressing '+' restores them one by one.

### ISSUE THREAD

**Issue by daniphilia** [MetaMask/metamask-extension#1511] opened 2017-05-29 17:09 UTC
When you press '+' to add new accounts, the old accounts are restored in sequential order. 
Had a mini heart attack here.

**Comment by frankiebee** [comment] 2017-05-29 18:05
related to issue #654

**Comment by danfinlay** [comment] 2018-03-01 23:53
Closing as a duplicate of #654

**Closed by danfinlay** 2018-03-01 23:53 UTC
Labels: L3-ui, P4-someday, T1-enhancement
