### ISSUE TITLE
Firefox Broken UI: Popup closes immediately 

### ISSUE THREAD

**Issue by quantumproducer** [MetaMask/metamask-extension#3313] opened 2018-02-24 01:36 UTC
1) Using Firefox, importing JSON File: When I click browse to find a file, the prompt closes.
Therefore it's impossible to import via JSON file on Firefox.
On Brave this works fine.

2) Seen similar inconsistent behavior with transaction prompts on Firefox. Sometimes a new window pops up, othertimes I have to click the fox to see it.

3) When signing for a transaction, this could mean I can't scroll down to click submit/reject.

I recognize these are 3 issues but I think they all need to be fixed together + are likely related.

**Comment by frankiebee** [comment] 2018-02-26 19:42
@quantumproducer issue 1 that you have writen about is a known bug for firefox+linux 
can you provide your firefox version?

**Comment by quantumproducer** [comment] 2018-03-08 22:33
56.09b

**Comment by DomiDre** [comment] 2018-03-15 12:30
I also have the 2nd problem. Always when I want to send a transaction / want to sign something I have to click the fox manually as the popup is blank (see screenshot: https://imgur.com/a/bob8k ). Ubuntu 16.04 and Firefox 59.0.

Also when I want to import an account, the window disappears when I click into anything else. Meaning it's impossible to import a JSON file as the Metamask gui minimizes once I get into the JSON file selector popup, such that I can't enter the password.

**Comment by berkes** [comment] 2018-04-18 09:45
@DomiDre sounds like a new issue. I can reproduce it, so maybe it would be better to open that as new issue instead of continuing it here? 

Or do they share a common, underlying problem?

**Comment by rawkode** [comment] 2018-04-23 06:41
Experiencing this also:

`60.0b14 (64-bit)` on Linux

**Comment by berkes** [comment] 2018-04-23 07:42
Note that I can reproduce the same behaviour with another addon [BitWarden](https://addons.mozilla.org/nl/firefox/addon/bitwarden-password-manager/?src=search). It has a feature to "pop out", but commonly runs in a menu-dialog.

So, this might be caused by a more low-level issue: handling of FF menu-dialogs in a stand-alone popup, or some common library. In any case, it might be worth comparing with BitWarden.

**Comment by rawkode** [comment] 2018-04-23 07:57
I've experienced similar annoyances with BitWarden too, come to mention it. I tend to use the sidebar option with BitWarden now, because of that bug. Is a quick fix to allow MetaMask to open in the sidebar?

**Comment by Jurkovic** [comment] 2018-06-25 16:29
I faced the same problem with broken UI (after clicking on icon nothing showed up)
Instructions from MetaMask FAQ's did help me:


    Open about:debugging in a new tab
    Scroll down and find the Metamask {Internal UUID} (e.g. 12324c61-abc2-4922-a325-012697643ff5)
    Open moz-extension://{Internal UUID}/popup.html in a new tab and import through the tab

After these steps I was able to open MetaMask UI in standard way.
`Using Ubuntu 18.04 and Firefox`

**Comment by quantumproducer** [comment] 2018-06-26 20:46
@Jurkovic  I tried this, check this out -- the UI is bugged and won't show me the buttons under neath to cancel.

<img width="283" alt="screen shot 2018-06-26 at 16 45 08" src="https://user-images.githubusercontent.com/11827932/41938233-82a01b76-7960-11e8-8633-b6acf96020ee.png">

**Comment by estebanmino** [comment] 2018-07-20 18:23
Related to the blank screen issue on Firefox / Ubuntu 18.04, there is a way to fix it
https://consensys.zendesk.com/hc/en-us/articles/360007617432

**Comment by letatcest** [comment] 2018-09-05 10:15
I'd like to add that the solution provided in https://github.com/MetaMask/metamask-extension/issues/3313#issuecomment-406687137 fixes the closing problem on Firefox 61.0.1 (64-bits) in Ubuntu 18.04, but makes gedit behave odd. When I use the XIM input method, my gedit becomes transparent and when reading text, the text is unreadable (see pic). So no other solution (in my case) than to revert to IBUS (I use gedit quite a lot). 
I can still use metamask more or less when using moz-extension:// in the url bar. 
I'll report the XIM/IBUS problem to Ubuntu as well. 
![schermafdruk van 2018-09-05 12-12-39](https://user-images.githubusercontent.com/12709182/45087076-06b0c100-b105-11e8-8478-ed735705a00f.png)

**Comment by berkes** [comment] 2018-09-05 11:49
Thanks @letatcest. I've been bugged by this transparancy-issue for several weeks now. Without a clue what was causing it. See my Q on Stackoverflow (now answered) https://askubuntu.com/questions/1065953/where-can-i-find-more-information-on-a-bug-that-causes-rendering-issues-with-ubu/1072339#1072339. You gave me the information to fix a really annoying issue.

@estebanmino are you the author of that support-page? If so, please put this glitch as severe warning on there. It renders a lot of applications unusable. gedit, but also calculator, email, calendar, etc. Basically every native text-area becomes unusable, making the desktop really hard to use.

**Comment by 7--** [comment] 2019-01-21 18:43
having this issue now.

**Comment by berkes** [comment] 2019-01-28 11:32
The upstream issue, with ibus, is found here: https://github.com/ibus/ibus/issues/2002

**Comment by jeffshee** [comment] 2019-03-10 04:11
I believe that I'm encountering a similar bug (https://github.com/ibus/ibus/issues/2002) in Fedora as well.

Using Firefox 65.0.2 / IBus 1.5.19 / gnome-shell 3.30.2 / Fedora 29

Tested with LastPass's extension which can be found here: https://addons.mozilla.org/ja/firefox/addon/lastpass-password-manager/ After the installation, click on the extension, then click on the password field, the UI of the extension closes immediately.

**Comment by homotopycolimit** [comment] 2019-04-04 13:54
> Open about:debugging in a new tab
> Scroll down and find the Metamask {Internal UUID} (e.g. 12324c61-abc2-4922-a325-012697643ff5)
> Open moz-extension://{Internal UUID}/popup.html in a new tab and import through the tab
> ```

^^ this with home.html instead of popup.html  ^^

**Comment by xuhcc** [comment] 2019-06-09 08:02
It is also possible to open full page view by clicking on "Expand view" item in "Account options" menu.

![Screenshot from 2019-06-09 10-58-27](https://user-images.githubusercontent.com/1660460/59156559-f5d31880-8aa5-11e9-9d07-879805115fd9.png)

**Comment by tmashuang** [comment] 2020-01-31 02:08
Closing due to inactivity.

**Closed by tmashuang** 2020-01-31 02:08 UTC
Labels: P3-soon, T00-bug

**Comment by lvella** [comment] 2023-02-16 18:52
This just happened to me today.
