### ISSUE TITLE
Ropsten test faucet not working

### ISSUE THREAD

**Issue by prographo** [MetaMask/metamask-extension#4500] opened 2018-06-05 14:10 UTC
It doesn't work.

**Comment by evansjohnson** [comment] 2018-06-05 17:39
@prographo can you check if your metamask address shows a balance on Etherscan? (click the 3 dots and the top option "View account on Etherscan".  You may be having the same issue as #4504 where balances are not showing up correctly (even tho the faucet may have worked)

**Comment by bdresser** [comment] 2018-06-06 22:20
@prographo faucet at https://faucet.metamask.io/ works fine for me! what sort of error are you seeing?

**Comment by mmysgp** [comment] 2018-10-15 13:35
got the following error when get ether from metamask faucet since yesterday (14 Oct 2018).
Is it due to the fork?

{"error":"[ethjs-rpc] rpc error with payload {\"id\":4364955207927,\"jsonrpc\":\"2.0\",\"params\":[{\"to\":\"0x0ddde515ab49efbdbbb21f4d08a4f055c46a0b73\",\"from\":\"0x81b7e08f65bdf5648606c89998a9cc8164397647\",\"value\":\"0xde0b6b3a7640000\",\"data\":\"0x\"}],\"method\":\"eth_sendTransaction\"} [object Object]"}

**Comment by bdresser** [comment] 2018-10-15 16:06
Closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/5439

**Closed by bdresser** 2018-10-15 16:06 UTC
Labels: N02-needsReproduction
