### ISSUE TITLE
MM cannot estimate Gas for our dApp

### ISSUE THREAD

**Issue by jaimindp** [MetaMask/metamask-extension#22318] opened 2023-12-18 12:31 UTC
### Describe the bug

Metamask can't estimate the gas, this was fine and no changes were made but on the 15th December, transations on Eth Mainnet, Polygon, BNB Chain and Arbitrum all had errors. The transactions work with other wallets.
<img width="472" alt="Screenshot 2023-12-18 at 12 24 54" src="https://github.com/MetaMask/metamask-extension/assets/43257699/2ca738b6-f6fb-4637-a6d1-77126a4fcbf3">

### Expected behavior

For the transaction to go through normally

### Screenshots/Recordings

<img width="472" alt="Screenshot 2023-12-18 at 12 24 54" src="https://github.com/MetaMask/metamask-extension/assets/43257699/bef8ff7b-93b7-4407-9526-6a67f7ca1c18">

### Steps to reproduce

Download Caddi: https://chromewebstore.google.com/detail/eeobggeikihkgiggaekfbceghlcpemfm
Execute a swap on Uniswap

### Version

11.7.0

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

### Severity

Critical for our application to work with Metamask

**Comment by anaamolnar** [comment] 2023-12-19 13:47
Related to https://github.com/MetaMask/metamask-extension/issues/17866

**Comment by anaamolnar** [comment] 2023-12-19 13:47
Hello @jaimindp 
Thanks for reporting! I will pass this on to the team.

**Comment by OGPoyraz** [comment] 2024-02-05 08:10
Hi @jaimindp 
I cannot reproduce this issue on my end. 
Could you please elaborate the steps to reproduce this issue?

![Image](https://github.com/MetaMask/metamask-extension/assets/7644512/1c8c09e5-ce0e-493c-b011-2235403bbebb)

**Comment by OGPoyraz** [comment] 2024-02-13 09:49
I am closing this issue, but feel free to re-open with detailed reproducible steps.

**Closed by OGPoyraz** 2024-02-13 09:49 UTC
Labels: type-bug, Sev2-normal, team-confirmations-system, external-contributor
