### ISSUE TITLE
bug - metamask infinite loads

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#6520] opened 2019-04-26 16:55 UTC
**Describe the bug**

send a transaction or two, and metamask 6.4.0 crashes.

**To Reproduce**
1. send multiple transactions
2. metamask will crash / get stuck in infinite loading

I've tried turning metamask extension on/off and that doesnt help.
I've tried restarting chrome and that doens't help.

**Expected behavior**
metamask won't get stuck in infinite loading

**Screenshots**
http://bits.owocki.com/aeacd9658f98/Image%202019-04-26%20at%2010.53.12%20AM.png

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows] OS X
 - Browser [e.g. chrome, safari] Chrome Version 73.0.3683.103 (Official Build) (64-bit) 
 - MetaMask Version [e.g. 5.0.2]  6.4.0

**Additional context**

**Comment by owocki** [comment] 2019-04-26 16:57
possible dupe with https://github.com/MetaMask/metamask-extension/issues/6515

**Comment by chejazi** [comment] 2019-04-26 16:59
Which is a dupe of #6514 :P

**Closed** 2019-04-26 16:59 UTC
