### ISSUE TITLE
Can not cancel `wallet_switchEthereumChain` on Firefox

### ISSUE THREAD

**Issue by PierreJeanjacquot** [MetaMask/metamask-extension#11344] opened 2021-06-18 11:52 UTC
Hi there,
First, I'm really excited to see `wallet_switchEthereumChain` is released :+1: 

**Describe the bug**
With Firefox, when the user cancels a `wallet_switchEthereumChain` nothing happens.
It seems to work fine on chrome

**Steps to reproduce**

1. Open Firefox
2. Go to https://hlu0g.csb.app/
2. Click on a button to switch the current chain
3. On `Allow this site to switch the network?` step, click `cancel` => nothing happens, the pop up is still open, no error is thrown

**Expected behavior**
Cancel should cancel the switch request, closing the MetaMask pop up and reject the `ethereum.request()` promise with `{code: 4001, message: "User rejected the request.", data: {…}}`

**Browser details (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser: [Firefox Browser 89.0 (64-bit)]
 - MetaMask Version: [9.6.1]

**Comment by adonesky1** [comment] 2021-06-23 19:05
@PierreJeanjacquot are you still experiencing this issue? We are not able to reproduce.

**Comment by adonesky1** [comment] 2021-06-25 17:23
Closing this issue because we will use duplicate #11383 for reference

**Closed by adonesky1** 2021-06-25 17:23 UTC
