### ISSUE TITLE
[Bug]: LavaPack is not defined

### ISSUE THREAD

**Issue by aminbakhshi** [MetaMask/metamask-extension#14984] opened 2022-06-18 17:04 UTC
### Describe the bug

I am not sure if this is a bug or what, but I cannot run metamask locally, I have this warning error message that "LavaPack is not defined" , I have set up and then run the develop branch, BUT, when I switch to lavamoat-dev-optional, I can run the metamask locally without any problem, but the problem is that this branch is not updated and I don't have many new features.

Could someone help me out here to see what's the problem, and why these set of error messages appears on the console.

### Steps to reproduce

1.

### Version

develop branch

### Browser

Chrome

### Operating system

Windows

**Comment by aminbakhshi** [comment] 2022-06-18 21:48
@danjm Could you please help me with this if you can

**Comment by dfibuch** [comment] 2022-08-11 11:11
This isn't exactly a fix but there is a workaround that I found. I'm running WSL with Ubuntu 18.04 and I cloned the repo there, followed the setup steps again and that problem is no longer there, it all works.

**Comment by HowardBraham** [comment] 2022-11-17 04:12
Duplicate of https://github.com/MetaMask/metamask-extension/issues/13318

**Closed** 2022-11-30 15:19 UTC
Labels: devrel-support-needed, developerQuestion
