### ISSUE TITLE
When I submit a transaction , I stuck on `Estimating transaction cost…`

### ISSUE THREAD

**Issue by tanhuiya** [MetaMask/metamask-extension#5802] opened 2018-11-21 09:59 UTC
![image](https://user-images.githubusercontent.com/10923091/48833777-1b712c80-edb7-11e8-84ab-60830d83be5a.png)

**Comment by tanhuiya** [comment] 2018-11-21 10:00
version  : 5.0.3

**Comment by tanhuiya** [comment] 2018-11-22 01:47
I found the problem happend in my private network using `geth`

![image](https://user-images.githubusercontent.com/10923091/48876880-895f3780-ee3b-11e8-83c3-56e93a983b71.png)

**Comment by jflowers1974** [comment] 2019-01-05 17:31
BUMP - same here....

**Comment by bdresser** [comment] 2019-01-07 16:42
@jflowers1974 are you on a private or public network? any reproduction steps to help us debug? looks like OP found the issue was on their own end, not a MM bug.

**Comment by jennypollack** [comment] 2020-03-16 15:48
Hey @tanhuiya are you still experiencing this issue? Closing for now, but feel free to reopen if it's still causing you trouble.

**Closed by jennypollack** 2020-03-16 15:48 UTC
