### ISSUE TITLE
Metamask on Google Chrome on Ubuntu does not find Ledger Live app

### ISSUE THREAD

**Issue by SCBuergel** [MetaMask/metamask-extension#11224] opened 2021-06-02 10:12 UTC
**Describe the bug**
Metamask on Google Chrome on Ubuntu does not find Ledger Live app and thus cannot connect to my Ledger Nano X.

**Steps to reproduce (REQUIRED)**
1. Enable 'Use Ledger Live' in the Advanced settings in Metamask
2. Attempt to add Hardware Wallet
3. Select 'Ledger' and click 'Connect'
4. This attempts to open the Ledger Live app (see screenshot 1 below) - which I already had running. But then nothing happens, the Metamask screen just keeps saying 'Looking for your Ledger...' (see screenshot 2 below)

**Expected behavior**
Expected to be able to use my Ledger on Ubuntu with Metamask

**Screenshots**

![Screenshot from 2021-06-02 11-58-57](https://user-images.githubusercontent.com/11379673/120462636-66625680-c39b-11eb-8ecd-b8142c236d31.png)

![Screenshot from 2021-06-02 10-09-58](https://user-images.githubusercontent.com/11379673/120462714-77ab6300-c39b-11eb-81b2-ce2ae53ded1d.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Hardware Wallet: Ledger Nano X, Firmware 1.3.0 (latest)
 - Browser: Google Chrome Version 91.0.4472.77 (Official Build) (64-bit)
 - MetaMask Version: 9.5.8

**Comment by darkwing** [comment] 2021-06-14 17:59
Closing as duplicate of https://github.com/MetaMask/metamask-extension/issues/11219 ; we're aware of the issue and have communicated it to the Ledger team.  In the mean time, there is a workaround that may work for you:

https://github.com/MetaMask/metamask-extension/issues/11219#issuecomment-852683567

**Closed by darkwing** 2021-06-14 17:59 UTC
