### ISSUE TITLE
[NewUI] Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by alextsg** [MetaMask/metamask-extension#3370] opened 2018-03-01 02:48 UTC
https://sentry.io/metamask/metamask/issues/474888634/

**Comment by danjm** [comment] 2018-03-01 04:26
Linking my comment on another issue which also applies to this: https://github.com/MetaMask/metamask-extension/issues/3336#issuecomment-369470067

**Comment by danjm** [comment] 2018-03-02 02:10
Closing as a duplicate of #3336

**Closed by danjm** 2018-03-02 02:10 UTC
Labels: L3-ui, NewUI/UAT, P2-sooner, T0-bug
