### ISSUE TITLE
Allow user to view full error message from transaction

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5217] opened 2018-09-07 21:00 UTC
In New UI, there is no easy way to view the full error message for a transaction.

Old UI, you could hover over the "Error" text and a tooltip would contain the full text.

We should make sure there is some method for developers to view transaction error messages.

May need some design. Could tuck this behind a feature flag for developers.

**Comment by whymarrh** [comment] 2018-09-07 21:03
I think this is a duplicate of #3768 where we decided to add the tooltip to the new UI as well?

**Comment by bdresser** [comment] 2018-09-07 21:04
fixed in https://github.com/MetaMask/metamask-extension/pull/5128 on the tx outbox branch

**Closed by bdresser** 2018-09-07 21:04 UTC
