### ISSUE TITLE
Address book overflow makes entire screen scrollable

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6997] opened 2019-08-12 17:46 UTC
Only address list should scroll when the address list is long.

![unknown](https://user-images.githubusercontent.com/542863/62885737-71438700-bcee-11e9-917f-e8d39b29b31d.png)

**Comment by ajnauleau** [comment] 2019-08-15 21:25
Hey do you mind being a bit more specific or taking a wider screenshot? I'm having trouble recreating this bug.

**Comment by danfinlay** [comment] 2019-08-15 23:04
The screenshot was submitted to support by another user. Supposedly the bug happens if there is more than a screen full of addresses. If that is not reproducible, then maybe the issue was actually something else!

**Comment by Gudahtt** [comment] 2021-01-07 19:20
I tested this in Chrome using v8.1.10 and was unable to reproduce. Since this issue is somewhat old, I'm going to close this as assume that we fixed it at some point.

**Closed by Gudahtt** 2021-01-07 19:20 UTC
Labels: L03-UI, N02-needsReproduction, S2-normal, T00-bug
