### ISSUE TITLE
Investigate: Removing Extension & Reinstalling Keeps Old Seed Phrase?

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3452] opened 2018-03-06 19:25 UTC
Based on this comment:
https://github.com/MetaMask/metamask-extension/issues/3127#issuecomment-370819730

Is there any way for an extension to persist seed data, while appearing that a new vault is being created? I'm not aware of such a thing, but we should ensure it.

> I managed to get back into my account again and transfer all my tokens and Ethereum out of my account into another address I own which i don't use with Metamask :D

> Basically last year I installed metamask on mozilla firefox, created an account and recorded that seed. I never used that account and uninistalled metamask.

> Then this year I decided to Metamask and completely forgot I created an account i never used. Anyway I installed the lastest version of Metamask on firefox again and this time google chrome also. I created a brand new account using the firefox installation and a brand new seed was shown and an address which i recorded down.
It turns out the new accounts address for account 1 does not releate to the new seed I was given but actually relates to the seed from my account I never used last year.

> Whilst cleaning up the files on an old memory stick i found a seed phrase to the account I never used. I thought i have nothing to lose as I had already lost it all and tried to recover my account with my seed phase from the account i never used last year. I then created a new password but one which was excatly the same as the new account I recently created and it worked! I went to settings and reveal seed phrase but the new most recent seedphase was still showing not the one I managed to recover my account with. I logged back out and back in and revealed the seed phrase again and this time the correct one was showing. I then as quickly as possible transfered everything out of my address lol.

**Comment by EmanuelKuhn** [comment] 2018-09-13 20:57
Based on my experience reproducing #3127 I have some observations on this:

- If a user uninstall metamask and reinstalls it before closing the browser, the extension data is kept.
  - I noticed this because I was purposely trying to get to a fresh install state. 
  - This might actually happen in the case that a user tries to cancel the password generation process or get a fresh install for another reason.

- It does seem to be the case that extension data is removed after uninstalling and closing the browser.

**Comment by Gudahtt** [comment] 2021-01-06 14:00
I've noticed the same behaviour as well, both on Chrome and Firefox. It has happened sporadically on both browsers when uninstalling and reinstalling in the same browser session.

Since this is an unexpected browser behaviour, not a MetaMask bug, I'll re-label this as a "question" for now. It'd be nice to have a more concrete idea about what conditions this happens under though. I haven't dug through the Chromium or Firefox bug trackers about this yet but that might be a good place to start.

**Closed** 2022-10-26 18:53 UTC
Labels: needs-research
