### ISSUE TITLE
[Bug]: Cannot get the latest value after switching the network

### ISSUE THREAD

**Issue by coding-ice** [MetaMask/metamask-extension#25097] opened 2024-06-06 12:21 UTC
### Describe the bug

Cannot get the latest value after switching the network
link: https://stackblitz.com/edit/vitejs-vite-9rayvh?file=src%2FApp.tsx

### Expected behavior
correct version: `11.14.5 - x`

_No response_

### Steps to reproduce

1.  Click button change to BNB chain.
2. Switch metamask to other chain.
3. Can't get the latest value.

### Version
11.16.7

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by disappearer** [comment] 2024-06-06 13:35
I can confirm this. Our app heavily relies on network switching and this issue is making it unusable with MetaMask.

**Comment by coding-ice** [comment] 2024-06-06 13:43
Please check as soon as possible, thanks.

**Comment by adonesky1** [comment] 2024-06-06 20:07
Can you explain what you mean by "Cannot get the latest value"? Do you mean if you call `eth_chain` you are not receive any response? Or you're not seeing the correct response?

**Comment by tmm** [comment] 2024-06-06 21:07
Reproducible via running RPC requests in the browser console. More info in this comment https://github.com/wevm/wagmi/issues/3998#issuecomment-2153404972

```ts
// start with extension on mainnet, then request accounts:
> await window.ethereum.request({ method: 'eth_requestAccounts' })
[...]
> await window.ethereum.request({ method: 'eth_chainId' })
'0x1'
> await window.ethereum.request({ method: 'wallet_switchEthereumChain', params: [{ chainId: '0x89' }] })
> await window.ethereum.request({ method: 'eth_chainId' })
'0x89'
// switch in extension ui, then run the following:
> await window.ethereum.request({ method: 'eth_chainId' })
'0x89' // should be 0x1
```

**Comment by Gudahtt** [comment] 2024-06-06 21:16
We have been able to reproduce this bug, and are currently investigating. We will post an update soon.

**Comment by Gudahtt** [comment] 2024-06-06 23:44
We have found the problem, and are preparing a fix. We'll have this released as soon as we can.

**Comment by coding-ice** [comment] 2024-06-07 00:26
ok,thinks a lot~

**Comment by c0da523** [comment] 2024-06-07 01:41
> Reproducible via running RPC requests in the browser console. More info in this comment [wevm/wagmi#3998 (comment)](https://github.com/wevm/wagmi/issues/3998#issuecomment-2153404972)
> 
> ```ts
> // start with extension on mainnet, then request accounts:
> > await window.ethereum.request({ method: 'eth_requestAccounts' })
> [...]
> > await window.ethereum.request({ method: 'eth_chainId' })
> '0x1'
> > await window.ethereum.request({ method: 'wallet_switchEthereumChain', params: [{ chainId: '0x89' }] })
> > await window.ethereum.request({ method: 'eth_chainId' })
> '0x89'
> // switch in extension ui, then run the following:
> > await window.ethereum.request({ method: 'eth_chainId' })
> '0x89' // should be 0x1
> ```

I met this problem too.I thought there are somewhere cached in my browser.

**Comment by Sotatek-ToanHa** [comment] 2024-06-07 08:22
please we are also having the same problem

**Comment by adonesky1** [comment] 2024-06-07 14:37
Thank you for your patience. A fix will be released with 11.16.8. Should be going live today!

**Comment by danjm** [comment] 2024-06-07 21:20
The fix for this has been published as part of the 11.16.8 release

You may need to manually update your metamask install to access this fix. https://support.metamask.io/managing-my-wallet/using-metamask/how-to-update-the-version-of-metamask/#:~:text=Chrome%2Dbased%20browsers%3A%20Click%20the,manually%20install%20it%20from%20here.

**Comment by jxom** [comment] 2024-06-07 22:35
For the future, bugs like these should be tagged as sev-critical.

Most libraries to chainId checks to assert the user is on the right chain before executing a transaction.

**Comment by Sotatek-ToanHa** [comment] 2024-06-08 02:30
> Thank you for your patience. A fix will be released with 11.16.8. Should be going live today!

I have found it to work properly. Thank

**Comment by matthewlilley** [comment] 2024-06-08 09:21
> For the future, bugs like these should be tagged as sev-critical.
> 
> Most libraries perform chainId checks to assert the user is on the right chain before executing a transaction.

Absolutely... We had a case of a user losing ETH because of this bug.

Any ideas what we could do to safe guard against this?

**Comment by matthewlilley** [comment] 2024-06-09 08:51
@Gudahtt @danjm I looked at the PR which fixed this issue and couldn't find an accompanying test. I think this would be the best safe guard against this from happening in the future.

**Closed** 2024-06-10 21:21 UTC
Labels: type-bug, Sev2-normal, team-wallet-api-platform, external-contributor, regression-prod-11.16.7

**Comment by simonazhang68** [comment] 2024-06-15 09:22
I have lost my 0.332eth when I use Across procotol to bridge my eth from zks to other chain use metamask wallet? Who will compensate me? Can I ask  metamask refund me? My address is 0x41e3A8766E0FF11eEF0c4D8eBe35a4F8d9772765,last transation  hash is 0x912eff9e32127a10acfe325b2a9bcb8a848e401cdf08103ba5f21e9f2e446c24.

**Comment by simonazhang68** [comment] 2024-06-15 09:23
> Hey @coding-ice thanks for your report here. We have a fix for this issue that is rolling out with version 11.16.7
> 
> Edit: Actually you are reporting that you are seeing this on 11.16.7... We'll take a look!
I have lost my 0.332eth when I use Across procotol to bridge my eth from zks to other chain use metamask wallet? Who will compensate me? Can I ask metamask refund me? My address is 0x41e3A8766E0FF11eEF0c4D8eBe35a4F8d9772765,last transation hash is 0x912eff9e32127a10acfe325b2a9bcb8a848e401cdf08103ba5f21e9f2e446c24.

**Comment by MarcelCloud** [comment] 2024-06-17 08:56
It would help if you also looked into the rabby and metamask sync issue. Rabby has more connection control and it affects interacting with metamask when we have to

**Comment by simonazhang68** [comment] 2024-06-25 11:55
> > Hey @coding-ice thanks for your report here. We have a fix for this issue that is rolling out with version 11.16.7
> > Edit: Actually you are reporting that you are seeing this on 11.16.7... We'll take a look!
> > I have lost my 0.332eth when I use Across procotol to bridge my eth from zks to other chain use metamask wallet? Who will compensate me? Can I ask metamask refund me? My address is 0x41e3A8766E0FF11eEF0c4D8eBe35a4F8d9772765,last transation hash is 0x912eff9e32127a10acfe325b2a9bcb8a848e401cdf08103ba5f21e9f2e446c24.

You have fixed this issue but who will refund my loss? I can't get my money back now!

**Comment by rosewinlet** [comment] 2024-07-13 02:46
Many bugs for Metamask nowadays. I regconise these problems also:
- Chain switching problem like above. Switching chain is quite slow.
- Some RPC is suspended and metamask spins forever. 
- The transaction was made successfully, but still the dapp connected with Metamask does not recognise, while other wallets like OKX, C98, ... are working very well. This problem just happens for some days. 
- Some signing (only signing) but the token was transacted ( I've losted for more than 2000 usdt equivalent token). 

Please take care these problems as soon as possible. We still believe in you!
