### ISSUE TITLE
Does not allow password entry to enable sync with mobile

### ISSUE THREAD

**Issue by pauloram** [MetaMask/metamask-extension#9362] opened 2020-09-06 10:52 UTC
Running Chrome 85.0.4183.83 on MacOS and Metamask 8.0.8 when I go to the mobile sync area and am prompted to enter the password the field does not allow me to type anything. The cursor is in the field but no key presses are recognised and the next field never enables. I have to cancel out of the screen. 

![Issues_·_MetaMask_metamask-extension](https://user-images.githubusercontent.com/334292/92324193-b7793000-f03f-11ea-81ea-1c6f822c14f5.png)

**Comment by mozadak** [comment] 2020-09-20 01:19
I have the same issue. Couldnt sync the app with extension.

**Comment by jacobcantele** [comment] 2020-11-08 02:03
Hi @pauloram , can you confirm you're still having this issue on the latest version of Chrome? I'm not able to reproduce.

**Comment by tmashuang** [comment] 2020-11-30 22:52
Closing issue does not seem to be in the current version with the limited reproduction steps.

**Closed by tmashuang** 2020-11-30 22:52 UTC
Labels: N02-needsReproduction

**Comment by GabArthur** [comment] 2021-02-09 09:35
Still having the issue on the last version of Chrome extension
