### ISSUE TITLE
Reduce conversion code duplication and improve conversion utility api

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6233] opened 2019-03-04 17:58 UTC
For now just linking to https://github.com/MetaMask/metamask-extension/pull/4895#issuecomment-408452748

I think we've started in the right direction with `metamask-extension/ui/app/helpers/conversions.util.js`

We need to fully think through what the API of such a util should be, implement that util, and then replace all cases of conversion with calls to that util.

We might also want to publish this as its own library.

**Comment by kumavis** [comment] 2019-03-28 08:23
duplicate of #6290

**Closed by kumavis** 2019-03-28 08:23 UTC
Labels: L03-UI, T02-refactor
