### ISSUE TITLE
MetaMask may report still-pending transaction as failed

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#9934] opened 2020-11-24 02:06 UTC
**Describe the bug**
Sometimes, MetaMask reports a transaction as having failed, when it is still in the tx pool and might still execute.  

**Steps to reproduce (REQUIRED)**
1. Have an account with some ETH.  Private-net ETH like you'd have on a Ganache instance running locally likely suffices; in my case I had geth running locally.  Use a new account created just for this test, which has no prior transactions.  In this test, the account was prefunded with 10 ETH. 
2. Have another account to receive some ETH. 
3. In Metamask Settings-> Advanced, turn on "Customize transaction nonce."
4. Trigger a 3 ETH transaction from sender to recipient, manually setting the nonce to 2. This will help prevent the transaction from going through, simulating a variety of other hard-to-manually-reproduce conditions.  In my test, I used a 50 Gwei gas price.

![image](https://user-images.githubusercontent.com/563406/100027509-f1461100-2dba-11eb-8668-fa87c9280873.png)

This transaction will remain Pending:
![image](https://user-images.githubusercontent.com/563406/100027570-0c188580-2dbb-11eb-9a63-70c132a76b2b.png)

In Geth logs, I could see the transaction submitted, followed by lines about every 30 seconds saying:
>WARN ... Served eth_sendRawTransaction   ...   err="already known"

Click Cancel: 
![image](https://user-images.githubusercontent.com/563406/100027662-3f5b1480-2dbb-11eb-9231-b77a807bb2f1.png)
Then click "Yes, let's try."

In the transaction history, the amount changes to 0 and the Cancel button disappears:
![image](https://user-images.githubusercontent.com/563406/100027770-716c7680-2dbb-11eb-90fa-3a340920edee.png)

Geth logs show the submitted transaction and about every 20 seconds this warning:
>WARN ... Served eth_sendRawTransaction ... err="replacement transaction underpriced"

Suppose I want to speed up that 0 ETH / cancellation transaction, or recognize this "underpriced" error as requiring a higher gas price. I might click the only visibly remaining option, Speed Up: 
![image](https://user-images.githubusercontent.com/563406/100027924-c60ff180-2dbb-11eb-8973-f4f26d5c6a98.png)

Click Fast, and save. 

A failure popup is observed very briefly, and upon inspecting the MetaMask popup console, the error is seen in more detail, with message: 
>"[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"replacement transaction underpriced"},"stack":"Error: Internal JSON-RPC error.\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:361390)\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:361793)\n    at l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:35483)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:34639"}}'"

Notice that Metamask clearly reports the transaction as having failed:

![image](https://user-images.githubusercontent.com/563406/100037679-a20adb00-2dd0-11eb-8f01-2b32bbfcd3bd.png)

though Geth continues to put out the "replacement transaction underpriced" note every 20 seconds or so, suggesting the tx is still in the pool.

Send another small transaction, accepting default nonce:
![image](https://user-images.githubusercontent.com/563406/100028285-98777800-2dbc-11eb-9083-97ce26c4bf62.png)
This should go through and be confirmed. 

Note that this transaction appears *below* the failed transactions in the transaction history, because it has a lower nonce.
![image](https://user-images.githubusercontent.com/563406/100028496-189ddd80-2dbd-11eb-87be-261c64753ac8.png)

Send another small transaction, which should go through too:
![image](https://user-images.githubusercontent.com/563406/100028534-2bb0ad80-2dbd-11eb-99ac-e53aa7fd59d2.png)

Popups show transaction 1 confirmed, then transaction 2 confirmed, and that transaction changes from Failed to Cancelled, with the cancellation fee charged: 
![image](https://user-images.githubusercontent.com/563406/100028627-5dc20f80-2dbd-11eb-98f0-582119c52383.png)

Initiate another transaction like the first, with nonce 4. 
![image](https://user-images.githubusercontent.com/563406/100033602-7edc2d80-2dc8-11eb-8e2c-666bac1da79c.png)
As before, this transaction remains pending, with the "already known" error in geth logs
![image](https://user-images.githubusercontent.com/563406/100033650-9ddabf80-2dc8-11eb-9dd3-f9c47c80e0d2.png)
Click Cancel, and accept gas fee:
![image](https://user-images.githubusercontent.com/563406/100033709-b34fe980-2dc8-11eb-98a3-0a187c535089.png)

The transaction amount is now 0 but still pending, with the periodic "already known" errors replaced by "replacement transaction underpriced" errors.
![image](https://user-images.githubusercontent.com/563406/100033785-d4183f00-2dc8-11eb-86ef-2a51576b2656.png)

Click Speed Up, thinking this might speed up cancellation (as any visible Cancel option has disappeared), and select Average speed, then Save: 
![image](https://user-images.githubusercontent.com/563406/100033856-fa3ddf00-2dc8-11eb-9fc9-8ae6ea2542dc.png)

The transaction remains pending, but Geth "replacement transaction underpriced" errors continue:
![image](https://user-images.githubusercontent.com/563406/100033956-28bbba00-2dc9-11eb-8313-a11d5012a4e1.png)

Click Speed Up, go to Advanced, and enter a high gas price like 43000: 
![image](https://user-images.githubusercontent.com/563406/100034011-48eb7900-2dc9-11eb-821b-8268ec5e01f2.png)

The transaction remains pending and Geth keeps saying "replacement transaction underpriced." 
Click Speed Up again, and go to Advanced, saving the default value filled in of 47300:
![image](https://user-images.githubusercontent.com/563406/100034164-9ec02100-2dc9-11eb-8bea-34feb4d6338d.png)

The transaction remains pending and Geth keeps saying "replacement transaction underpriced" in its logs.
![image](https://user-images.githubusercontent.com/563406/100034376-10986a80-2dca-11eb-82a0-95c130395a48.png)
Note that the Speed Up button is gone.

However, clicking on the transaction, there are details:
![image](https://user-images.githubusercontent.com/563406/100034461-33c31a00-2dca-11eb-9505-5255e87cc76a.png)

Notably, there are two different links here: "Speed up this cancellation" and "Speed up this transaction."  At this point, the user might recognize that "Speed up this cancellation" is what they have been trying to do, and notice the subtle change that AFTER they submitted a Cancel transaction and the Cancel button disappeared, subsequent speed-up attempts resubmitted the original 3 ETH transaction.  

So here, the user clicks "Speed up this cancellation." A higher cancellation fee is posted:
![image](https://user-images.githubusercontent.com/563406/100034579-7e449680-2dca-11eb-95d5-e2e90cdff610.png)
The user clicks "Yes, let's try." 

A failure message pops up very briefly, but clicking on it causes the popup to disappear even faster, rather than providing any details.  Inspecting the MetaMask logs (which the average user should not be expected to know how to do) reveals this error: 

>"[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"tx fee (1.09 ether) exceeds the configured cap (1.00 ether)"},"stack":"Error: Internal JSON-RPC error.\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:361390)\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:361793)\n    at l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:35483)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:34639"}}'"

Note: Both this and the error above use codes 32603 and 32000. That seems to violate the spirit of using different codes for different errors: you have two different codes for the same error and/or two different errors using the same code. 

In earlier testing trying to develop these steps to reproduce, simply clicking "Speed up this cancellation" several times without having ever sped up the original transaction results in an AssertionError "The field gasPrice must not have more 32 bytes" error, usually within 10-12 speedups of the cancellation.  In any case, the user is not informed about the 32-byte cap, or why that failed.

At this point, MetaMask shows the transaction as having finally failed...one might think this has a similar outcome to cancellation, perhaps without the cancellation fee, and a final notice that the transaction will NOT go through.  Further, this is a 0-ETH transaction now because it was cancelled, so in the worst case it'd be charging the cancellation fee: 

![image](https://user-images.githubusercontent.com/563406/100036245-dd57da80-2dcd-11eb-89ca-857bc090945b.png)

Then, send a small transaction, accepting the default nonce:
![image](https://user-images.githubusercontent.com/563406/100034282-dfb83580-2dc9-11eb-81bd-0e83a48d7dc1.png)

This shows as pending for a bit:
![image](https://user-images.githubusercontent.com/563406/100035147-8224e880-2dcb-11eb-82ba-499157036d37.png)

Then, notification popups show that transaction 4 is confirmed, followed shortly by transaction 3.  While confirmation of transaction 3 was expected, confirmation of transaction 4 was not; the interface had showed it in a final state as Failed.  Further, the amount the transaction was confirmed for was 3 ETH, despite that the transaction had been cancelled!

![image](https://user-images.githubusercontent.com/563406/100035319-e2b42580-2dcb-11eb-97f2-fd2c07800991.png)

The user's balance is adjusted downward to match.  The user, who might have re-initiated a transaction that failed, may have doubled the transaction intended, which could lead to quite negative results, depending on what the transaction does. 

**Expected behavior**
1) MetaMask's UI does not allow submission of a cancellation transaction with a too-high gas price (>32 bytes), communicating the upper limit to the user.  If there is a chain-specific limit for the tx fee (default value of 1 ETH on this private PoA chain) that MetaMask can find out about, that limit is similarly presented and respected.
2) Errors are visible to the user in some way.
3) When errors are passed to a dapp, each unique error has a unique code.
4) If an attempt to replace a previous transaction fails, but the transaction the user attempted to replace is still in the pool, **the transaction is not marked as Failed.**  There may be some way to communicate to the user that the _attempt to speed up_ the transaction failed. 
5) After the user has clicked to Cancel a transaction and submitted that cancellation, the Cancel button does not disappear, but becomes "Speed up cancellation." The "Speed up" button either disappears or becomes "Resubmit & speed up original transaction." 
6) The UI for speeding up a tx and speeding up a tx cancellation are much more similar than they currently are.
7) When submitting a transaction with a higher gas price, Geth logs should not show "replacement transaction underpriced" (not sure if this is an issue in Metamask or elsewhere).
8) When an alert is shown (e.g. "Nonce is higher..." from first screenshot), the popup grows a little taller so the reject/confirm buttons don't get cut off.
9) Gas prices suggested for private networks aren't drawn from current gas price conditions on mainnet.
10) Transactions are shown in the order they are mined, sorted first by block number and then transaction number within the block, rather than nonce. Pending transactions are shown on the most-recent end.  Failed transactions may be sorted by timestamp, in the sequence where they would be if they had succeeded instead. 

Some of those may need to be spun off into separate Issues with links back here.

A transaction with an incorrect nonce not succeeding is just used as a way to simulate / reliably reproduce a condition of a transaction remaining pending for a long time.  I'm not listing that failure to confirm as a deviation from expected behavior here.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: Not in use here
 - Browser: Chrome 86.0.4240.183 (Official Build) (64-bit)
 - MetaMask Version: 8.1.3

**Comment by danfinlay** [comment] 2021-02-02 20:09
Thanks for the report, we've synthesized this and I believe we have a number of duplicates but also a couple new issues here, which we're opening as individual issues so all the work can be prioritized appropriately.

Regarding your expected behaviors:
1. We've opened issue #10335 to track this problem.
2. Partly addressed in #10335, but being addressed continuously in (ideally) all cases.
3. These error codes come from the node, and we have no control over them. We'll do our best to adhere to this in our own code.
4. Duplicate of #9053
5. Fixed by our intended fix to #7305
6. Addressed under #8011 
7. Partly addressed by #8453, and in #10337
8. We're already discussing how to handle tall confirmations internally.
9. Being addressed in #10003
10. Partly captured in #10338, partly in another one above.

I believe that digests all your reports, thanks for sharing it. Closing as all points have been captured elsewhere.

**Closed by danfinlay** 2021-02-02 20:09 UTC
Labels: L18-transactions, S2-normal, T00-bug, needs-triage
