### ISSUE TITLE
Webcam doesn't work to scan QR in browser extension 8.0.5

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-extension#9081] opened 2020-07-27 12:57 UTC
**Describe the bug**
When sending you should be able to scan a QR code using the webcam in the computer, the 

Tested on Brave, Chrome (it opened in full-view, and I was asked for permission to use the webcam by the browser for the "site"), Firefox (it opened in full-view, and I was asked for permission to use the webcam by the browser for the "site"), **but the loading wheel stays forever it says “accessing camera” and loads indefinitely**.

**To Reproduce (REQUIRED)**

1. Go to Account > Send
2. Use the "scan QR code" icon for the recipient address
3. Approve permission request from the browser
4. Loading wheel stays loading indefinitely

**Screenshots**
<img width="356" alt="webcam" src="https://user-images.githubusercontent.com/2995401/88544203-53635500-d019-11ea-9f81-c7cbc708c813.png">

**Browser details (please complete the following information):**
 - OS: tested on Mac OS, user report probably on Windows
 - Brave, Chrome, Firefox
 - MetaMask version 8.0.5

**Comment by tmashuang** [comment] 2020-07-27 18:16
Closing as this is a duplicate of  #9043.

**Closed by tmashuang** 2020-07-27 18:16 UTC
