### ISSUE TITLE
Ropsten test Faucet is not working its throwing RPC Error

### ISSUE THREAD

**Issue by ravi27019** [MetaMask/metamask-extension#4102] opened 2018-04-27 11:58 UTC
POST https://faucet.metamask.io/ 500 (Internal Server Error)

**Comment by bdresser** [comment] 2018-06-11 23:02
@ravi27019 test faucet is working fine for me - you still seeing this error?

**Comment by bdresser** [comment] 2018-10-15 22:08
looks like this is caused by Infura working to get Ropsten up to date with the Constantinople fork. Hang tight. 

Closing this issue as a duplicate of https://github.com/MetaMask/metamask-extension/issues/5439#issuecomment-429662116, will update there with more info.

**Closed by bdresser** 2018-10-15 22:08 UTC
