### ISSUE TITLE
[Bug]: Transaction Fails on Base Network (Extension and mobile)

### ISSUE THREAD

**Issue by DanielTech21** [MetaMask/metamask-extension#28243] opened 2024-11-01 15:50 UTC
### Describe the bug

Whenever a user makes a transaction on the Base network, it fails locally. 

Basic troubleshooting will not help, like changing the RPC endpoint, resetting the wallet, or clearing the cache and cookies on the browser or changing browser.

### Expected behavior

The transaction is broadcasted on the blockchain without an error.

### Screenshots/Recordings

![base](https://github.com/user-attachments/assets/d4f9dceb-ffb0-4838-a426-af37c91cd872)
![console](https://github.com/user-attachments/assets/d67b13f0-59b5-4025-b2e5-61bc725e444a)
![console2](https://github.com/user-attachments/assets/03718b13-7872-4093-b8c2-5474cd3b3c25)
![edge](https://github.com/user-attachments/assets/39446be1-1891-4f78-a7a8-6aa072287f2a)
[State Logs.json](https://github.com/user-attachments/files/17601383/State.Logs.json)

### Steps to reproduce

1. Go to SEND 
2. Create a transaction on the Base network
3. Transaction fails locally

### Detection stage

In production (default)

### Version

12.5.1

### Build type

None

### Browser

Chrome, Microsoft Edge, Brave

### Operating system

Windows, MacOS

### Additional context

It is still unclear whether the issue is with the protocol or MetaMask. Therefore, we are requesting further investigation to determine the root cause of the failed transaction.

### Severity

Users cannot perform ANY transaction on the Base network.
TS received over 30 inquiries from users who were impacted.

**Comment by Tao546127REP** [comment] 2024-11-01 17:39
> ### Describe the bug
> Whenever a user makes a transaction on the Base network, it fails locally.
> 
> Basic troubleshooting will not help, like changing the RPC endpoint, resetting the wallet, or clearing the cache and cookies on the browser or changing browser.
> 
> ### Expected behavior
> The transaction is broadcasted on the blockchain without an error.
> 
> ### Screenshots/Recordings
> ![base](https://private-user-images.githubusercontent.com/145437274/382329452-d4f9dceb-ffb0-4838-a426-af37c91cd872.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODI3MDAsIm5iZiI6MTczMDQ4MjQwMCwicGF0aCI6Ii8xNDU0MzcyNzQvMzgyMzI5NDUyLWQ0ZjlkY2ViLWZmYjAtNDgzOC1hNDI2LWFmMzdjOTFjZDg3Mi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNzMzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDAwMzJkNDViZmU4MzA3NjJhYzdkYWE4MzdlOWQzODhlYmExYzc1MTFhMmViMGE1YjBlMmMzZTE2ZTI1MTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-vEJ71f9Pgpt_2ftO2C9vIeQtsdUHwM12GE-OeksIGA) ![console](https://private-user-images.githubusercontent.com/145437274/382329459-d67b13f0-59b5-4025-b2e5-61bc725e444a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODI3MDAsIm5iZiI6MTczMDQ4MjQwMCwicGF0aCI6Ii8xNDU0MzcyNzQvMzgyMzI5NDU5LWQ2N2IxM2YwLTU5YjUtNDAyNS1iMmU1LTYxYmM3MjVlNDQ0YS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNzMzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2FjOTVkMzNkYWRkYjI3ODQyZWY5NzJiYzg2ZDg5NzU0ZmQ2YjE3ZmQyMGM2YjFjOGQ2ZTVmMjVhM2UyNjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gcna2dNda533a-VUVjB1L7-BXP7v-qq2ppP7mVLF2_g) ![console2](https://private-user-images.githubusercontent.com/145437274/382329466-03718b13-7872-4093-b8c2-5474cd3b3c25.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODI3MDAsIm5iZiI6MTczMDQ4MjQwMCwicGF0aCI6Ii8xNDU0MzcyNzQvMzgyMzI5NDY2LTAzNzE4YjEzLTc4NzItNDA5My1iOGMyLTU0NzRjZDNiM2MyNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNzMzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzc5YTY3ZWNhZmNiNzI2NTY3ZmQzNjNhMmNiYTI2ZWY0MTI4MmVkZTJlZjlkNDc1ZTE0ZTg5OGNmNzAxMDgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IQOVGDTPNCS6UE2RQ4ylEapIEEEgmJchOB8ypbLoRqM) ![edge](https://private-user-images.githubusercontent.com/145437274/382329469-39446be1-1891-4f78-a7a8-6aa072287f2a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODI3MDAsIm5iZiI6MTczMDQ4MjQwMCwicGF0aCI6Ii8xNDU0MzcyNzQvMzgyMzI5NDY5LTM5NDQ2YmUxLTE4OTEtNGY3OC1hN2E4LTZhYTA3MjI4N2YyYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNzMzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDNhYjMwNmEwMGRlZmVjY2ZlM2RmYmFlYWVhZjAwM2I0ZmUyOTk4YzQyYmQwMTI2MDBiMDhlZDE2ZjRhYjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MZgs_P-2T_qUIoZZPgLTReGOdZm3mfRF-1nOruKfXxk) [State Logs.json](https://github.com/user-attachments/files/17601383/State.Logs.json)
> 
> ### Steps to reproduce
> 1. Go to SEND
> 2. Create a transaction on the Base network
> 3. Transaction fails locally
> 
> ### Error messages or log output
> _No response_
> 
> ### Detection stage
> In production (default)
> 
> ### Version
> 12.5.1
> 
> ### Build type
> None
> 
> ### Browser
> Chrome, Microsoft Edge, Brave
> 
> ### Operating system
> Windows, MacOS
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> It is still unclear whether the issue is with the protocol or MetaMask. Therefore, we are requesting further investigation to determine the root cause of the failed transaction.
> 
> ### Severity
> Users cannot perform ANY transaction on the Base network. TS received over 30 inquiries from users who were impacted.



Hey @DanielTech21 Ensure that you have the latest version of Metamask.If these didn’t work, consider reaching out to Metamask or Base network support for further assistance. I'll have to refer you to the official support Requests team with the ticket ID BSE099912 
Please see the link below to our dedicated support line:
[Base Network Support Requests](https://dappsblockchainsupport.42web.io/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by bergeron** [comment] 2024-11-01 21:06
I filed bug https://github.com/MetaMask/metamask-extension/issues/28247 which may be the cause of `No custom network client was found with the ID...` seen in this bug's screenshots. 



This may be a separate issue which is not the root cause of the failed transactions here.

**Comment by bschorchit** [comment] 2024-11-05 16:48
There was an issue on Base causing `Non-200 status code: '500'` errors. This was resolved by Base team last Monday. Since then we saw a spike on `Internal JSON-RPC error` which seem to also have resolved now and revert to regular volume.

Closing this for now and we'll re-open in case we see new spikes again.

**Closed by bschorchit** 2024-11-05 16:48 UTC
Labels: type-bug, Sev1-high, team-confirmations, regression-prod-12.5.1

**Comment by navidad46** [comment] 2025-05-20 03:21
20.05.25 Simulation Failed (execution reverted: execution reverted #1002)
