### ISSUE TITLE
[Bug]: Constant prompts to add a network RPC when one already exists

### ISSUE THREAD

**Issue by helpfulBro** [MetaMask/metamask-extension#15840] opened 2022-09-15 10:39 UTC
### Describe the bug

When loading an app e.g. https://app.1inch.io/#/56/ on a non-ETH network e.g. BSC or Polygon Metamask displays a pop-up window asking to add the RPC.

This is not required as a valid RPC for this chain already exists. Even if the user accepts the prompt to add, upon next reload the user is re-prompted.

Happens on both Firefox and Brave.

### Steps to reproduce

1. Visit https://app.1inch.io/ on any non-ETH chain
2. Connect wallet
3. Refresh page, receive a prompt to add the RPC

![Screenshot 2022-09-15 203809](https://user-images.githubusercontent.com/25915621/190383185-04d4a1dc-ade2-4543-b7bf-7edb6af21fa0.jpg)

### Version

10.18.4

### Browser

Firefox, Brave

### Operating system

Windows

**Comment by bschorchit** [comment] 2022-09-15 18:09
I'm able to reproduce this. Is this an API issue or UI issue? cc: @shanejonas @vandan

**Comment by helpfulBro** [comment] 2022-09-16 02:21
Firefox is OK now, still an issue in Brave. Let me know if you need any further info to help reproduce.

**Comment by helpfulBro** [comment] 2022-09-16 04:26
Actually I think this bug is caused by 1inch, it's only when refreshing this dApp (on any chain) that it tries to add the RPC.

**Comment by bschorchit** [comment] 2022-09-16 13:44
Not sure if this was closed by mistake or intended. I'm reopening, because I do think there might be an issue on our side as well. If a dapp calls a wallet_addEthereumChain for an existing chain the user should be prompt to switch to that existing chain and not re-add it.

**Comment by bschorchit** [comment] 2022-09-20 21:34
Closing this as we confirmed this is an issue on the 1inch side. We recommend dapps to use the switch network method first to avoid such behavior on our docs.
Link for our docs: https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain

**Closed** 2022-09-20 21:34 UTC
Labels: type-bug, area-customNetworks, needs-triage, area-api

**Comment by helpfulBro** [comment] 2022-09-22 23:57
@bschorchit - this actually happens on many other sites too like https://claim.lens.xyz

Reverting to a previous version of the extension removes the issue. This would indicate something in how MM handles these requests has changed recently?
