### ISSUE TITLE
Privacy: Metamask is an always on cross domain forever cookie

### ISSUE THREAD

**Issue by josephg** [MetaMask/metamask-extension#2584] opened 2017-11-15 13:20 UTC
Metamask right now has a big privacy problem - it provides advertisers a permanent user identity that works cross-device (assuming you share your etherium wallet). All an advertiser needs to do is ask for the user's coinBase or accounts and they can use that ID to track the user forever.

Its kind of worse than that, because they can also silently find out how much ethereum you have. Its like if everyone you walked past on the street could silently figure out how much cash you have in your wallet.

Metamask needs a per-site opt-in, the same way chrome handles other security drop-in things.

> nytimes.com wants to access your ethereum accounts. [Accept] [Reject]

**Comment by danfinlay** [comment] 2017-11-27 19:20
We're aware of this, it's a duplicate of #714. Hoping to do this soon, but it requires some considerable code rearrangement.

**Closed by danfinlay** 2017-11-27 19:20 UTC
