### ISSUE TITLE
[Bug]: Chrome Extension breaks login on Battle.net

### ISSUE THREAD

**Issue by IrealiTY** [MetaMask/metamask-extension#14463] opened 2022-04-18 12:12 UTC
### Describe the bug

If the Chrome Metamask Extension is activated, the 2FA authentication on https://battle.net breaks. The website usually waits for user input on the mobile device to confirm the 2FA login. If MetaMask Extension is active it redirects you back to login and 2FA fails.

### Steps to reproduce

1. Have MetaMask Extention activated
2. Visit https://eu.battle.net/login/en/
3. Login with an account that uses Mobile 2FA
4. After a few seconds you will be redirected back to the username and password prompt
5. Deactivate MetaMask extension
6. Repeat Steps 2 & 3
7. 2FA Login will work 

### Version

10.12.4

### Browser

Chrome

### Operating system

Windows

### Additional context

More confirmations online about it:

- https://www.reddit.com/r/Overwatch/comments/tbcbpt/battlenet_browser_login_redirecting_before_i_can/#:~:text=for%20me%20started%20working%20after%20i%20removed%20metamask
- https://us.forums.blizzard.com/en/wow/t/logging-in-to-browser-based-services-authenticator-page-just-refreshes/1187903/4#:~:text=It%20looks%20like%20the%20crypto%20wallet%20Extension%20%E2%80%9CMetamask%E2%80%9D%20is%20causing%20some%20issues

**Comment by IrealiTY** [comment] 2022-04-18 12:12
Can provide a video as a demonstration if needed.

**Comment by clupss** [comment] 2022-06-04 09:10
Can confirm this also happens for me.

**Comment by liquidfrollo** [comment] 2022-06-27 15:40
This happens for me as well

**Comment by ethan-xd** [comment] 2022-08-09 00:55
This is still an active issue. Happened to me today. Thank god for this issue or I would have no idea.

**Comment by jander99** [comment] 2022-08-19 03:06
I just process-of-elimination'd this bug as well. 

MetaMask 10.18.3 on Chrome 104.0.5112.102 Windows 10

**Comment by leighstillard** [comment] 2022-08-28 07:01
This is still an active issue. I'm experiencing it on Chrome 104.0.5112.81 (Official Build) (64-bit) (cohort: Stable)

**Comment by SeraphimRP** [comment] 2022-09-17 04:16
Exists on Edge as well, probably affects any Chromium-based browser that uses Chrome addons.

User Agent: 
`
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.42
`

Edge Version:
`Version 105.0.1343.42 (Official build) (x86_64)`

**Comment by goncalvesm** [comment] 2022-09-28 10:18
Same here

**Comment by clupss** [comment] 2022-11-16 21:17
Still not fixed.

**Comment by ACassiusD** [comment] 2023-08-03 19:04
Still an issue

**Comment by SeraphimRP** [comment] 2023-08-03 20:28
I went through the trouble of testing releases to work out when this started happening. v8.0.0 contains the issue, while v7.7.9 does not.

I'll start bisecting the commits between and see if I can find where this began. I get that these guys are busy with many other things. While I might not be able to implement a solution, I should be able to find where the issue is.

**Comment by SeraphimRP** [comment] 2023-08-03 21:58
Bisecting done, first bad commit looks to be f519fa1ed3839bf0f4024517271902fd21c76596. It's a pretty big commit by the looks of things, so not sure where to continue from here. Hope this helps devs here.

**Comment by HowardBraham** [comment] 2023-08-04 09:11
@SeraphimRP this is good work, but can you bisect it into the actual commits inside PR 7004?  That would help me narrow it down further. (https://github.com/MetaMask/metamask-extension/pull/7004/commits)

The cause of this problem is not at all obvious.  I opened a PR #20396, but it's more of a band-aid and exploration than an actual fix.  It just turns off MetaMask on `https://*.battle.net/*`

It would be great if other people tested it though.  You can either build from source on #20396, or you can download a CircleCI build [here](https://output.circle-artifacts.com/output/job/5793e5e8-9922-4dec-85d0-cba874aa822b/artifacts/0/builds/metamask-chrome-10.34.2.zip).

**Comment by clupss** [comment] 2023-11-02 20:13
Do not close this.

**Comment by thomascooper** [comment] 2023-11-20 20:54
11/20/2023 This issue is still occurring between battle.net login with their own 2FA enabled and the MetaMask extension.

**Comment by BrentMifsud** [comment] 2023-12-23 22:00
can confirm this is still happening.

**Comment by joshivince** [comment] 2023-12-30 17:13
Still here the bug as well with macOS and Google Chrome (Mac M1 and macOS: 13.6.1 (22G313) and Chrome: Version 120.0.6099.129 (Offizieller Build) (arm64)).

Vince

**Closed** 2024-02-02 18:34 UTC
Labels: type-bug, needs-reproduction, area-integration, Sev3-low

**Comment by HowardBraham** [comment] 2024-02-02 18:36
This is now fixed, and should come out in the next release.

We just solved it by blocking Battle.net, but here's the actual problem if you're curious:
- The page headers on Battle.net list the following 4 icons
```
<link rel="icon" type="image/png" sizes="192x192" href="/login/static/images/toolkit/themes/bnet-next/meta/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="16x16" href="/login/static/images/toolkit/themes/bnet-next/meta/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/login/static/images/toolkit/themes/bnet-next/meta/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/login/static/images/toolkit/themes/bnet-next/meta/favicon-96x96.png">
```
- That first one, if you try to actually visit it, is a 404 error: https://us.account.battle.net/login/static/images/toolkit/themes/bnet-next/meta/android-icon-192x192.png
- Our @metamask/providers tries to load that icon
- Battle.net has some sort of code that if you're in the middle of 2FA and you get a 404 error, go back to the login page
- You can independently verify this if you disable MetaMask, then on the 2FA page run either of
      `fetch('https://us.account.battle.net/login/static/images/…it/themes/bnet-next/meta/android-icon-192x192.png')`
      `fetch('https://us.account.battle.net/login/static/404')`  _(not at all an image, but a deliberate 404)_
      you will get the same result of being forced back to the login page
