### ISSUE TITLE
Unable to use derivation paths for connected hardware wallets

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#6165] opened 2019-02-14 23:24 UTC
MetaMask Version 6.0.1

When using a derivation path such as  `m/44'/60'/0'/0`, everything works, but if I choose an account with a derivation path like `m/44'/60'/0'/2`, transactions fail to send because of insufficient funds. I believe this is because it is signing transactions with the wrong account. I would expect those derivation paths to be supported because they are listed as options when connecting the hardware wallet.

Separately, I am unable to connect more than one hardware account at a time.

We are using Ledgers.

cc @brunobar79 

Thanks

**Comment by wjmelements** [comment] 2019-02-14 23:54
Our wallet at `m/44'/60'/0'/0` had no funds, while our wallet at `m/44'/60'/0'/2` had 0.25. We got the received insufficient funds JSON error after confirming the transaction on the device.

**Comment by wjmelements** [comment] 2019-02-14 23:59
The RPC error was `"insufficient funds for gas * price + value"`

**Comment by wjmelements** [comment] 2019-02-15 00:02
I cannot reproduce this issue with the steps provided. Please keep an eye out for more reports.

**Comment by MicahZoltu** [comment] 2019-03-15 09:08
I just ran into this, can we re-open?  Alternatively, what did you do to try to repro that made it work?

My steps were:
1. Install Brave.
1. Install MetaMask extension.
1. Import account via seed phrase + password.
1. Name my accounts.
1. Add ledger, choose MEW/MyCrypto for HD Path, first item in the list.
1. Notice that MetaMask correctly shows me my balance.
1. Notice that the dapp I'm using correctly shows me my address and balance.
1. Notice that the dapp correctly sets the `from` address.
1. Submit a transaction for signing.
1. Receive transaction prompt in MetaMask.
1. Notice that While MetaMask shows the correct named account in the top, it shows as having 0 ETH (incorrect) in the signing prompt.
1. Sign the transaction, receive an error message saying that the transaction failed due to not enough gas (same error as OP).

**Comment by MicahZoltu** [comment] 2019-03-25 11:07
This didn't happen to me the other day, now it happened to me again today.  I don't know what makes it happen vs not, but at the moment I have no way to sign a transaction with my ledger as I cannot get it to prompt me with the correct address.

**Comment by MicahZoltu** [comment] 2019-03-25 11:09
Note: The correct address is presented in the signing UI, but that is not the address that is being signed with.  Everything _except_ the address used for signing is correct.

**Comment by MicahZoltu** [comment] 2019-04-03 09:13
Just got another report of this from an Augur user.  They are unable to use MetaMask to sign transactions with their ledger.  As above, MM appears to be running gas estimation with the wrong derivation path.

This issue is quite frustrating because it renders the ledger unusable from within MetaMask.

**Comment by brunobar79** [comment] 2019-04-03 15:59
@MicahZoltu I’m happy to take a look at this but I need reproduction steps. Can you help me with that?

**Comment by brunobar79** [comment] 2019-04-03 18:45
@MicahZoltu  I don't think it's related to the gas estimation since we use the public key already imported (and visible in the UI for that).

I believe there's something else going on since with the steps described no one would be able to sign a TX with ledger using the first account of the Legacy HD path and I've verified that's not the case. 
I believe I followed a very similar path here and signed a tx proposed by a dapp which worked correctly: http://recordit.co/UNeBMHi6F8

The `transaction failed due to not enough gas` would be also happening if you're signing a tx with an account that has no balance, which it's likely to happen if there's a bug with the HD path / index of the selected account.

A couple of questions:

- Can you reproduce the issue while sending a transaction from the MM UI (instead of a dApp) ?
- Can you tell us which network are you using?

It would be even better if you can share the dApp where you're able to reproduce this issue.

**Comment by wjmelements** [comment] 2019-04-03 22:58
It may be hard to reproduce because current versions of Chrome do not work with Ledger: https://support.ledger.com/hc/en-us/articles/360018810413-U2F-timeout-in-Chrome-browser

We have also seen the issue with Brave.

**Comment by wjmelements** [comment] 2019-04-03 22:59
We were on mainnet.

**Comment by brunobar79** [comment] 2019-04-03 23:05
@wjmelements if you upgrade the firmware to 1.5.5 and the ETH app to 1.2.4 via the ledger live app it should work.

**Comment by MicahZoltu** [comment] 2019-04-04 03:01
Unfortunately, today is a "cannot reproduce" day.  😢 Some days I am able to reproduce this 100% of the time (meaning my ledger is useless from MetaMask) and some days I cannot reproduce it at all.  I have no idea what triggers whether it can be reproduced.

I vaguely remember that on reproducing days I have the same problem sending ETH via MetaMask UI, it isn't a problem specific to using dapps.  Trying to sign _anything_ with the Ledger would have this problem where it was trying to sign with the wrong derivation path.

It may be worth noting, my Ledger has pretty old firmware on it.
Brave: Version 0.62.50 Chromium: 73.0.3683.86 (Official Build) (64-bit)

**Comment by brunobar79** [comment] 2019-04-04 15:01
@MicahZoltu  That’s unfortunate...
 I encourage you to upgrade your ledger firmware and ETH app and keep us posted.

Wouldn’t be surprised if that’s related.

**Comment by Gudahtt** [comment] 2021-01-06 22:30
Thanks for the report! It sounds like this may have been the bug described in #7845, so I'll close this for now since we haven't gotten reports of this in a while.

**Closed by Gudahtt** 2021-01-06 22:30 UTC
Labels: L17-hardware, N02-needsReproduction, S2-normal, T00-bug
