### ISSUE TITLE
Batch confirm transactions

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#8512] opened 2020-05-05 01:25 UTC
**What problem are you trying to solve?**
<img width="360" alt="Screen Shot 2020-05-04 at 6 23 19 PM" src="https://user-images.githubusercontent.com/799573/81027927-57297600-8e34-11ea-9f0a-9ce441feabe7.png">
It also takes a long time after clicking confirm before I am able to click confirm again.

**Describe the solution you'd like**
A button to confirm all transactions with a confirmation, similar to the reject all button.

**Additional context**
I can do this without metamask but I would like to do it with metamask.

**Comment by tmashuang** [comment] 2020-05-06 01:09
Closing as it's a duplicate of #4050.

**Closed by tmashuang** 2020-05-06 01:09 UTC
