### ISSUE TITLE
[Bug]: Token balances displayed as zero 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24918] opened 2024-05-30 19:32 UTC
### Describe the bug

Token balances might randomly appear as zero, and transactions can't be submitted.

Probably the same bug:

https://github.com/MetaMask/metamask-extension/issues/24921
https://github.com/MetaMask/metamask-extension/issues/24925
https://github.com/MetaMask/metamask-extension/issues/24918

Also related https://github.com/MetaMask/metamask-extension/issues/24921

### Expected behavior

Token balances are accurately reflected.

### Screenshots/Recordings

https://jam.dev/c/50618d6c-1bb1-41ef-855f-54f18273509a

### Steps to reproduce

1. Start send+swap transaction
2. Choose any token other that ETH
3. Notice that token balances on the token picker are all 0 and transaction can't be submitted

### Version

dev build

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

dev build [4c64f44](https://github.com/MetaMask/metamask-extension/pull/24914/commits/4c64f449edbfe332f60bb56db6901949af9fb5e8)

**Comment by sleepytanya** [comment] 2024-06-01 16:08
This issue happens on `develop`:

https://github.com/MetaMask/metamask-extension/assets/104780023/81066f0b-920b-471a-9f3f-1f8d9fd8f684

If user selects a different destination token then the subsequent transaction with this token as a primary currency will show it's actual balance:



https://github.com/MetaMask/metamask-extension/assets/104780023/5012e9e6-57d0-466f-9917-6d0db49c2f1f

**Comment by sleepytanya** [comment] 2024-06-03 22:34
Token details tab display inconsistent info:

<img width="1131" alt="Screenshot 2024-06-03 at 15 23 32" src="https://github.com/MetaMask/metamask-extension/assets/104780023/a312a65f-7885-42b9-b585-dc521e782acc">


https://github.com/MetaMask/metamask-extension/assets/104780023/ce1ac68d-5bac-485e-b17d-537df768bd1d

**Comment by sleepytanya** [comment] 2024-06-06 02:23
1. Balances on the home screen randomly switch between 0 and actual numbers
2. Token balances on the send+swap flow randomly switch between 0 and actual numbers too (I don't think I caught it on video, most of the time you will 0 balances on the asset picker)
3. Balance on the token details screen should display the actual balance, token name and fiat value - it doesn't happen in the video
4. When send+swap initiated from the token details screen user have to click 'Send' two or three times to start the flow
5. If user switches back to the original destination token, 'no quotes available' warning is displayed (which shouldn't be displayed), and 'Confirm' button is unavailable (user can't submit send). 


1-4 look like the same bug in different forms, 5 is probably related to a different issue (ticket for the 'no quotes' https://github.com/MetaMask/metamask-extension/issues/24922

Current `develop` (sorry for the long videos - bug happens randomly): https://jam.dev/c/1d7b2875-8a0e-4728-8bcb-b1595fb4dff4

**Comment by sleepytanya** [comment] 2024-06-07 02:02
Latest build from here https://consensys.slack.com/archives/C068SFX90PN/p1717713259996549

Issue is still present:

https://jam.dev/c/8c8c12d3-fef6-44e9-9248-b43a291b2c29

**Comment by BZahory** [comment] 2024-06-07 21:29
Added functionality to allow transactions to be submitted when the balance isn't known. As for the disparities between home and the asset picker modal, this is related to rate-limiting (i.e. out of swap+send scope), but let's leave this issue open as this is something I'd like to better mitigate

**Comment by bergeron** [comment] 2024-06-12 18:42
There's lots of 429 rate limiting happening in those network requests, which is one reason this kind of thing can happen.  Are you using a free infura plan?  Those hit limits quite easy, and you can DM me for a higher limit one like we would use in production.

**Comment by davibroc** [comment] 2024-06-14 17:35
I am also seeing a similar problem with the Swap flow see the video. Only way for the token list to show the balance is to click on the token details.  
https://github.com/MetaMask/metamask-extension/assets/6082863/b724c43c-d2f0-4e42-bc9f-6d2c4b573424

**Comment by sahar-fehri** [comment] 2024-06-21 10:57
I have tried reproducing the steps in this video https://jam.dev/c/8c8c12d3-fef6-44e9-9248-b43a291b2c29
And i did not have any issues: 

https://github.com/MetaMask/metamask-extension/assets/10994169/fb39ccac-5582-4d25-a41d-631f17b16c67

**Comment by davibroc** [comment] 2024-06-21 11:18
Still happening

<img width="792" alt="Screenshot 2024-06-21 at 1 09 21 PM" src="https://github.com/MetaMask/metamask-extension/assets/6082863/64df7a2f-49dc-42ac-938f-27849b6da66a">

**Comment by bergeron** [comment] 2024-06-21 15:58
@davibroc I'd like to see the chrome network tab while this happens, to see whether you're hitting 429 rate limits like the original post.

**Comment by davibroc** [comment] 2024-06-21 19:32
@bergeron here it is 
https://github.com/MetaMask/metamask-extension/assets/6082863/2cdd25cd-3297-477f-b86f-e68d70ec2db4

**Comment by bergeron** [comment] 2024-06-21 19:41
Infura rate limiting seems to be the cause.

I'd like to know what infura key reporters are using.  When I use a free tier key, I also get these issues.  Where 429 errors  on the RPC calls to fetch balances cause `failed to load balance for token...` from the [eth-token-tracker](https://github.com/MetaMask/eth-token-tracker).  Among other UI issues.

<img width="410" alt="Screenshot 2024-06-21 at 11 58 20 AM" src="https://github.com/MetaMask/metamask-extension/assets/3500406/cc7c758e-84ad-4ab8-9e0f-db72d3db6ea4">

But that's happened to me for a while, not specifically on this release.  I had to start using the production infura key locally, where I haven't reproduced these errors.  

Comparing to older 11.x releases, I also haven't detected an increase in the # of RPC requests in this v12 release.

**Comment by sleepytanya** [comment] 2024-06-22 00:14
I do not reproduce the issue on the latest v12.0.0 build [[https://github.com/MetaMask/metamask-extension/commit/eebc4d5b2284024eaeb190cddfa89990f593ca34]](url)



https://github.com/MetaMask/metamask-extension/assets/104780023/af9d21e1-7af8-4e76-bf3f-ab84130b67a4

**Comment by alfeng6** [comment] 2024-09-06 17:50
@sleepytanya do you think we can close this one?

**Closed** 2024-10-22 17:15 UTC
Labels: type-bug, Sev2-normal, team-assets, send-swap
