### ISSUE TITLE
Retry button in tx screen seems to do nothing, errors in background

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#9337] opened 2020-09-01 07:08 UTC
![image](https://user-images.githubusercontent.com/1474978/91813245-fcc6e780-ec64-11ea-8a86-97350859974a.png)

```
8Error: <g> attribute transform: Trailing garbage, "translate(0,NaN)".
ui.js:1 Uncaught (in promise) TypeError: e.stopPropagation is not a function
    at ui.js:1
    at ui.js:1
    at Object.b (ui-libs.js:1)
    at x (ui-libs.js:1)
    at ui-libs.js:1
    at T (ui-libs.js:1)
    at j (ui-libs.js:1)
    at C (ui-libs.js:1)
    at k (ui-libs.js:1)
    at Sn (ui-libs.js:1)
    at le (ui-libs.js:1)
    at jn (ui-libs.js:1)
    at Mn (ui-libs.js:1)
    at kn (ui-libs.js:1)
    at n.unstable_runWithPriority (ui-libs.js:1)
    at Xi (ui-libs.js:1)
    at se (ui-libs.js:1)
    at Cn (ui-libs.js:1)
    at HTMLDocument.u (ui.js:1)
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
b @ ui-libs.js:1
x @ ui-libs.js:1
(anonymous) @ ui-libs.js:1
T @ ui-libs.js:1
j @ ui-libs.js:1
C @ ui-libs.js:1
k @ ui-libs.js:1
Sn @ ui-libs.js:1
le @ ui-libs.js:1
jn @ ui-libs.js:1
Mn @ ui-libs.js:1
kn @ ui-libs.js:1
n.unstable_runWithPriority @ ui-libs.js:1
Xi @ ui-libs.js:1
se @ ui-libs.js:1
Cn @ ui-libs.js:1
u @ ui.js:1
```

**Comment by Gudahtt** [comment] 2021-01-13 22:03
That stack trace looks like it's from our gas prediction graph, which is odd because that isn't on the transaction details modal :thinking: 

We removed that graph in #9867, so that shouldn't crash anymore at least. The error shown might be unrelated to the retry button failure though.

**Comment by digiwand** [comment] 2022-05-09 19:40
As far as I have inspected, the retry button continues to work as expected on the TransactionDetailsItemDetails component. 

I believe we can close this issue now under the presumption that this error was either fixed by now or caused by the gas prediction graph which has since been deprecated, as mentioned by @Gudahtt above. 

Should this error reappear, we can reopen this ticket or create a new one.

cc: @kumavis

**Closed by digiwand** 2022-05-09 19:40 UTC
Labels: type-bug, needs-reproduction, Sev2-normal, needs-triage, transaction safety team
