### ISSUE TITLE
Can't connect Metamask to Trezor on MacOS 11.1 with either Chrome or Brave 

### ISSUE THREAD

**Issue by shaimo** [MetaMask/metamask-extension#10372] opened 2021-02-04 15:23 UTC
Activated a new Trezor One, initialized, updated firmware, etc. When trying to connect to Metamask (9.0.4) it seems to open a separate tab for a second, then closes it before I get the chance to see what it says, then I get a spinning wheel and that's it. Never getting the list of addresses or anything.

I then tried to activate a second Trezor T, and it was just the same.

Tried with Brave and got the same exact behavior.

I would add that it's the first time I'm using Trezor and had to install the Trezor Bridge first.

**Comment by darkwing** [comment] 2021-02-04 17:30
Thank you for this report, @shaimo !  What operating system are you trying on?  Would it be possible to get a screen recording of the process?  For reference, I was able to connect a Trezor One in Chrome and Firefox on Mac with no problem, so I'd like more detail to figure out the differences.  Thank you!

**Comment by shaimo** [comment] 2021-02-04 18:00
@darkwing its in the title - MacOs 11.1

**Comment by pschall42** [comment] 2021-02-05 01:22
I would like this issue resolved as well. It also exists on Linux, this is on Mint 18.3 using Brave: [Screencast 2021-02-04 19:45:29.mp4.zip](https://github.com/MetaMask/metamask-extension/files/5929456/Screencast.2021-02-04.19.45.29.mp4.zip)

I'm wondering if it's being caused by a strange interaction between [PR 10192](https://github.com/MetaMask/metamask-extension/pull/10192) and [PR 10101](https://github.com/MetaMask/metamask-extension/pull/10101)

**Comment by jgemeigh** [comment] 2021-02-06 02:14
Would just like to also report this issue with a Ledger Nano X trying to connect to Metamask on Firefox on an up to date windows 10 build.

**Comment by Joelhaggar** [comment] 2021-02-07 23:10
I have a similar problem on Mac 11.2 in both chrome and firefox.  When I click on the browser extension icon it momentarily opens a blank menu but then closes and opens a browser tab where my only options are to import a wallet with the seed phrase or create a new wallet.  There is no option to connect to a hardware wallet.

**Comment by tmashuang** [comment] 2021-02-11 17:56
FW verisions?

**Comment by darkwing** [comment] 2021-03-16 17:56
Hello @Joelhaggar @jgemeigh @shaimo !  

Unfortunately the video provided will not workin Quicktime.

We've recently updated our Trezor libraries -- please try with an updated version of MetaMask (9.2.0).

**Comment by CoolLamer** [comment] 2021-05-05 20:50
I have same problem, i am runing manjaro.
I tried it in Chrome, Firefox and Brave. Same Issue.
This is from record log is is repeating:
`
kvě 05 22:53:23 seeyou trezord[6751]: 127.0.0.1 - - [05/May/2021:22:53:22 +0200] "POST /acquire/2/null HTTP/1.1" 400 32
kvě 05 22:53:23 seeyou trezord[6751]: POST /acquire/2/null

`

**Comment by CoolLamer** [comment] 2021-05-06 13:32
I fixed it by removing udev rules and installing `trezor-bridge-bin`.

**Comment by AlexJupiter** [comment] 2022-02-17 19:52
Closing this as this issue seems to have been fixed now.

**Closed by AlexJupiter** 2022-02-17 19:52 UTC
Labels: type-bug, needs-reproduction, area-hardware, Sev2-normal, hardware-trezor, hardware-wallet-connection-error
