### ISSUE TITLE
Blank menu area on chrome extension. cl

### ISSUE THREAD

**Issue by databaseindays** [MetaMask/metamask-extension#5172] opened 2018-08-30 17:07 UTC
I was able to signup and use it, but when I tried to log out it did nothing. now when I click fox head on extension icon it just opens a blank white menu. cant log out or in now. 

**Expected behavior**
after using for like 2 minutes the extension is like unresponsive, only opens menu but cant see anything. just blank and white. so cant log out or in. I have not tried closing browser and reopening because that does not remove this behaivior but I will update after I try that

**Screenshots**
does not show on screenshots

**Browser details (please complete the following information):**
Im on Ubuntu 18.04 using Chromium browser Version 68.0.3440.106 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Additional context**
none. new user, wondering why it does not work

**Comment by bdresser** [comment] 2018-09-04 19:45
closing as a duplicate of #4894

**Closed by bdresser** 2018-09-04 19:45 UTC
