### ISSUE TITLE
MetaMask Crashes Right After Seed Phrase Registration

### ISSUE THREAD

**Issue by leonlbc** [MetaMask/metamask-extension#11055] opened 2021-05-12 00:34 UTC
"RangeError: Incorrect locale information provided" appears right after the seed phrase is validated, which makes the extension unusable.

1. Install MetaMask from Chrome Web Store;
2. Configure a new account/ Create a new wallet;
3. Confirm the seed phrase;
4. Page crashes, asks you to reload it, but doesn't work anyway;

**Browser details:**
 - Windows
 - Browser: Chrome Version 90.0.4430.93 64 bits
 - MetaMask Version: 9.5.0

Error that shows up:

"MetaMask encountered an error
Try again by reloading the page, or contact support

Message: Incorrect locale information provided
Code: RangeError

Stack:
RangeError: Incorrect locale information provided
  at new DateTimeFormat (<anonymous>)
  at r.getTranslatedUINoficiations (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:86362)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:410446
  at Array.map (<anonymous>)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:410388)
  at ca (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:59367)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:104449)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45648)
  at eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:84115)
  at Object.enqueueSetState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:50429)
  at t.x.setState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:136:1461)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:48080
  at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:19:98310)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:19:98540
  at Array.forEach (<anonymous>)
  at Object.notifyListeners (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:19:98510)
  at S (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:19:102095)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:19:103236
  at Object.confirmTransitionTo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:19:98249)
  at Object.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:19:103045)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:874787
"

**Comment by tmashuang** [comment] 2021-05-12 02:48
Duplicate of #11047, #11045, #11044, #11038, and #11033

Fixed by #11036

**Closed by tmashuang** 2021-05-12 02:48 UTC
