### ISSUE TITLE
[Bug]: Unable to submit a transaction on BNB Chain (happens on any network, with BNB being more consistent to reproduce)

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25134] opened 2024-06-07 04:39 UTC
### Describe the bug

All transactions, including swaps, fail on BNB Chain. It happens on other networks too.

Possibly related issues (?):

 https://github.com/MetaMask/metamask-extension/issues/25273
 https://github.com/MetaMask/metamask-extension/issues/25198

Commit that possibly introduced the bug: 
 https://github.com/MetaMask/metamask-extension/commit/04c2e90094802b23b4265e2ad303978cd3e132c0

### Expected behavior

-

### Screenshots/Recordings

Video:  https://jam.dev/c/31318d29-90df-4d7b-9d0a-7268d3db7f5a

Pop-up notification:

<img width="379" alt="Screenshot 2024-06-07 at 00 37 28" src="https://github.com/MetaMask/metamask-extension/assets/104780023/741d8585-fdd5-4b4c-b091-ff7cda98ef27">

![Screenshot 2024-06-07 at 12 24 23 PM](https://github.com/MetaMask/metamask-extension/assets/104780023/cd7f3f8d-ff84-4d07-b7ed-d7cdaf70c6bc)

### Steps to reproduce

1. Switch to BNB Chain
2. Start send+swap transaction
3. See all transactions fail

### Version

Latest send+swap build, `develop`

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Latest build [Slack discussion link](https://consensys.slack.com/archives/C068SFX90PN/p1717713259996549)

**Comment by sleepytanya** [comment] 2024-06-07 23:40
Since this bug is present on develop and possibly was introduced by [24861](https://github.com/MetaMask/metamask-extension/pull/24861) I'm removing send-swap label.
Slack thread for details: https://consensys.slack.com/archives/CTQAGKY5V/p1717532860180689

**Comment by sleepytanya** [comment] 2024-06-10 18:03
As of right now on `develop` I see the same behavior on mainnet as well - all transactions fail, including simple send send+swap, swap with the error ' Transaction NaN failed! Header not found'. Re-loading extension resolves the issue.

**Comment by hesterbruikman** [comment] 2024-06-11 10:38
@legobeat Am I understanding correctly that this issue is:
- Caused by an incorrect nonce tracker due to a patch being removed?
- Would be fixed by your PR https://github.com/MetaMask/metamask-extension/pull/25188

**Closed** 2024-06-15 00:51 UTC
Labels: type-bug, Sev1-high, release-blocker, team-wallet-ux, regression-RC-12.0.0

**Comment by benjisclowder** [comment] 2024-08-12 14:57
Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

What PR fixed the issue?
Can you pinpoint the commit from which the issue originated?
Write a short explanation of the technical cause of the bug
How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @dbrans
