### ISSUE TITLE
Can't send transaction in MetaMask 4.5 extension

### ISSUE THREAD

**Issue by mananz** [MetaMask/metamask-extension#3851] opened 2018-04-03 20:21 UTC
Since earlier today (I assume since the MM extension got updated), I get a spinning wheel of death when sending transactions through MetaMask on a regular basis.

**Expected behaviour**

The following transaction is expected to succeed:

<img width="360" alt="01-transaction" src="https://user-images.githubusercontent.com/35743525/38273405-25a56c5c-378c-11e8-9478-d379cd71e084.png">

**Actual behaviour**

After pressing the "submit" button, the popup keeps showing the following spinner:

<img width="360" alt="02-permanent-loading" src="https://user-images.githubusercontent.com/35743525/38273406-25bd6d2a-378c-11e8-8fcd-a63d194d1a86.png">

Additionally, Ganache logs show no transaction being committed:

<img width="1280" alt="03-ganache-logs" src="https://user-images.githubusercontent.com/35743525/38273407-25d73c46-378c-11e8-8b49-6e9f48972303.png">

** Actions performed to try to mitigate the issue**

- Switch back and forth between networks
- Reset MM accounts
- Disable and enable MM extension
- Restart Ganache
- Redeploy contracts

Browser version: 65.0.3325.181
MetaMask version: 4.5.0
Operating system: macOS 10.13.3

[MetaMask console log](https://github.com/MetaMask/metamask-extension/files/1873216/metamask-console-log.txt)

**Comment by davesumter** [comment] 2018-04-03 22:30
same here. I'm also now seeing: 

Failure: error replacement transaction underpriced

**Comment by rhlsthrm** [comment] 2018-04-04 01:01
I'm having the same issues which are really messing up my development.

**Comment by jupitermandy** [comment] 2018-04-04 02:02
Same issue, just follow the TutorialToken example to do some transactions, and the MetaMask is spinning and never stop.
I have changed the Ganache setting with different port and networkId, and it still doesn't work.

**Comment by dmill** [comment] 2018-04-04 03:42
Thanks @jupitermandy! Confirmed for me too - I was getting this behavior last night, but after reinstalling things are back in working order. 4.5.1 must've fixed it, so a big thanks to whoever on the team put that patch in with such a quick turnaround.

**Comment by Pedro-vk** [comment] 2018-04-04 14:15
I've version 4.5.1, I've removed it and installed again, but the issue is still here.

**Comment by mananz** [comment] 2018-04-04 14:34
Upgrading didn't help for me. I've had to manually install 4.3 to be able to keep things working.

**Comment by rhlsthrm** [comment] 2018-04-04 16:46
@mananz how do you install an older version?

**Comment by kumavis** [comment] 2018-04-04 19:05
@rhlsthrm https://github.com/MetaMask/metamask-extension/releases unzip and drag into the extensions page (chrome)

**Comment by kumavis** [comment] 2018-04-04 19:07
v4.5.2 resolves an issues with our validation of `chainId` on txParams submitted by some apps (mycrypto, mew, ...)

**Comment by kumavis** [comment] 2018-04-04 19:09
@danjm old-ui not showing an error here is a problem. I think we can slightly de-escalate the priority now that v4.5.2 is live

**Comment by danfinlay** [comment] 2018-04-23 18:01
Closing in favor of #3881

**Closed by danfinlay** 2018-04-23 18:01 UTC
Labels: P1-asap, T00-bug
