### ISSUE TITLE
eth_signTypedData_v3 / v4 support for struct array

### ISSUE THREAD

**Issue by Amxx** [MetaMask/metamask-extension#7090] opened 2019-08-31 16:39 UTC
Let consider the following types

	let TYPES = {
		EIP712Domain: [
			{ name: "name",              type: "string"  },
			{ name: "version",           type: "string"  },
			{ name: "chainId",           type: "uint256" },
			{ name: "verifyingContract", type: "address" },
		],
		TX: [
			{ name: "op",     type: "uint8"   },
			{ name: "to",     type: "address" },
			{ name: "value",  type: "uint256" },
			{ name: "data",   type: "bytes"   },
			{ name: "nounce", type: "uint256" },
		],
		TXS: [
			{ name: "data", type: "TX[]" },
		],
	};
	let TXS = [{
		op:     0,
		to:     "0x0000000000000000000000000000000000000001",
		value:  0,
		data:   "",
		nounce: 0,
	},{
		op:     0,
		to:     "0x0000000000000000000000000000000000000002",
		value:  0,
		data:   "",
		nounce: 1,
	}];

### Single object signature
I am able to use `eth_signTypedData_v3` to sign a single `TX` object :
```
web3.currentProvider.sendAsync({
	method: "eth_signTypedData_v3",
	params: [ wallet, JSON.stringify({ types: TYPES, domain: DOMAIN, primaryType: "TX", message: TXS[0] }) ],
	from: wallet,
}, callback);
```
→ no error, signature can be verified

### Array signature
When I try to sign a TXS object
```
web3.currentProvider.sendAsync({
	method: "eth_signTypedData_v3",
	params: [ wallet, JSON.stringify({ types: TYPES, domain: DOMAIN, primaryType: "TXS", message: { data: TXS } }) ],
	from: wallet,
}, callback);
```

I get the correct values in the popup
![Capture d’écran de 2019-08-31 18-35-09](https://user-images.githubusercontent.com/2432299/64066767-2a2a2100-cc1e-11e9-97eb-dc5b75dd63f9.png)
But when I try to sign it I get an error:

```
code: -32603
​​message: "addUnapprovedMessageAsync/</<@moz-extension://d037ca05-8eff-4b95-8d5e-6012c580356f/background.js:1:101555\nh@moz-extension://d037ca05-8eff-4b95-8d5e-6012c580356f/background.js:1:902070\n[396]</a.prototype.emit/<@moz-extension://d037ca05-8eff-4b95-8d5e-6012c580356f/background.js:1:903864\n[396]</a.prototype.emit@moz-extension://d037ca05-8eff-4b95-8d5e-6012c580356f/background.js:1:903934\n_setMsgStatus@moz-extension://d037ca05-8eff-4b95-8d5e-6012c580356f/background.js:1:104058\nerrorMessage@moz-extension://d037ca05-8eff-4b95-8d5e-6012c580356f/background.js:1:103799\nsignTypedMessage@moz-extension://d037ca05-8eff-4b95-8d5e-6012c580356f/background.js:1:128522\n"
```

**Am I doing anything wrong? Is that not implemented? If not, is there any ETA for this feature?**

### EDIT:
apparently `eth_signTypedData_v4` is supposed to support that, but it gives me an error (using firefox + metamask 7.1.0)

**Comment by Amxx** [comment] 2019-09-01 07:58
In chrome + metamask 7.1.0 the errors are different:

Array + eth_signTypedData_v3: `RPC Error: Error: MetaMask Message Signature: Error: Arrays currently unimplemented in encodeData`

Array + eth_signTypedData_v4: `RPC Error: The method eth_signTypedData_v4 does not exist/is not available`

**Comment by BrendanChou** [comment] 2019-09-04 17:10
See #6868. I believe this is essentially a duplicate

**Comment by whymarrh** [comment] 2019-09-09 18:18
This in indeed a duplicate of #6868

Thanks for the details here @Amxx, we'll be updating our support in 7.2.0

**Closed by whymarrh** 2019-09-09 18:18 UTC
