### ISSUE TITLE
[Bug]: Unable to send tokens other that ETH from Tokens tab

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24462] opened 2024-05-09 15:08 UTC
### Describe the bug

Unable to send tokens other than ETH from the Tokens tab, as the 'Continue' button remains inactive. Additionally, the 'Send' button may require two clicks to initiate an action, as you can see in the video.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/155ae5c2-acb0-4bbd-9f9e-4fb4ebc4b484

### Steps to reproduce

1. Start Send transaction

### Version

latest build

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by BZahory** [comment] 2024-05-17 10:14
Duplicate of https://github.com/MetaMask/metamask-extension/issues/24490 – closing

**Closed by BZahory** 2024-05-17 10:14 UTC
Labels: type-bug, Sev2-normal, team-wallet-ux, swap-send-blocker
