### ISSUE TITLE
ganache and metamask not working fine

### ISSUE THREAD

**Issue by monica-gahlawat** [MetaMask/metamask-extension#8374] opened 2020-04-21 08:40 UTC
inpage.js:1 MetaMask - RPC Error: [object Object] {code: -32603, message: "[object Object]", data: {…}, stack: "Error: [object Object]↵    at a (chrome-extension:…eogaeaoehlefnkodbefgpgknn/background.js:1:1206771"}

**Comment by kumavis** [comment] 2020-04-22 02:22
not sure what the underlying layer is, but obviously there is a problem with the error serialization 

possibly related https://github.com/MetaMask/eth-json-rpc-middleware/pull/20

**Comment by shahafn** [comment] 2020-04-22 23:56
Might be related to the bug I encoutnred in #8385 ?

**Comment by monica-gahlawat** [comment] 2020-04-23 01:27
Error is RPC -32603

**Comment by wbt** [comment] 2020-05-06 23:32
I am seeing something similar where the issue I came here to report was not the cause of the underlying error (I knew before triggering the transaction that it would fail a require statement), but the way MetaMask fails to show any error details such as the reason thrown in require():
![image](https://user-images.githubusercontent.com/563406/81238480-326a0580-8fd0-11ea-8868-3b0381fe346c.png)

**Comment by adrianmcli** [comment] 2020-06-15 01:52
If I had to guess, it looks like MetaMask calls `.toString()` on the error object containing the revert string, causing it to return `[object Object]` instead of the underlying error object with revert string.

**Comment by Gudahtt** [comment] 2021-01-11 20:02
Thanks for the report! Unfortunately the original issue here doesn't have enough information for us to investigate further. Please re-submit the bug including relevant details such as the MetaMask version, OS and OS version, browser version, as well as more information about the situation you were in when this occurred.

The error serialization issues talked about here are quite concerning on their own though. The ticket #8975 already tracks that problem though, and has a lot more information in it, so I'm going to close this for now and use #8975 for tracking the serialization issues.

**Closed by Gudahtt** 2021-01-11 20:02 UTC
Labels: T00-bug
