### ISSUE TITLE
I can't run and deploy source code.

### ISSUE THREAD

**Issue by seniordev21** [MetaMask/metamask-extension#11400] opened 2021-06-28 04:49 UTC
My error is this.
I already installed nodejs(14.15.1) and yarn setup command successfully.(on windows 10)
But I can't run yarn start, yarn dist.
Please fix my errors.
Thanks.

****$ lavamoat development/build/index.js prod**
(Error#1)
Error#1: LavaMoat - required package not in whitelist: package "@gulp-sourcemaps\map-sources" requested "through2" as "through2"
  at requireRelative (LavaMoat/core/kernel:518:15)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)
  at Object.eval (C:\Users\Admin\Downloads\metamask-extension-9.6.1\metamask-extension-9.6.1\node_modules\@gulp-sourcemaps\map-sources\index.js:4:15)
  at internalRequire (LavaMoat/core/kernel:457:25)
  at requireRelative (LavaMoat/core/kernel:498:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)
  at Object.eval (C:\Users\Admin\Downloads\metamask-extension-9.6.1\metamask-extension-9.6.1\node_modules\gulp-sourcemaps\index.js:7:15)
  at internalRequire (LavaMoat/core/kernel:457:25)
  at requireRelative (LavaMoat/core/kernel:498:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**

**Comment by davidcallanan** [comment] 2021-06-28 12:31
I do not think this is the place to ask for help. This site is meant for reporting bugs with the MetaMask platform itself.

**Comment by darkwing** [comment] 2021-06-28 14:46
Closing as duplicate of https://github.com/MetaMask/metamask-extension/issues/11095

**Closed by darkwing** 2021-06-28 14:46 UTC
