### ISSUE TITLE
[Bug]: Cannot scan QR address in Darkmode

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14391] opened 2022-04-07 13:20 UTC
### Describe the bug

**Problem**: the QR code for an address is not detected if I am using Darkmode, whereas it is detected with the default theme.

https://user-images.githubusercontent.com/54408225/162208152-b5f6cebc-29b6-4e91-b45f-93de152c4ee4.mp4

### Steps to reproduce

1. Unlock Metamask
2. Go to Experimental//Settings
3. Enable Dark Mode
4. Click Account Details
5. (with another MM instance) Click send
6. Scan address -- QR is not detected

### Version

10.13.0

### Browser

Chrome, Firefox

### Operating system

Linux

**Comment by darkwing** [comment] 2022-04-07 13:33
Closing an a duplicate of https://github.com/MetaMask/metamask-extension/issues/14304

Great catch though @seaona !

**Closed by darkwing** 2022-04-07 13:33 UTC
Labels: theming, rc :package:
