### ISSUE TITLE
Mac/Opera Wallet Verify Bug

### ISSUE THREAD

**Issue by Yogitoraito** [MetaMask/metamask-extension#11267] opened 2021-06-09 19:51 UTC
### Explanation
Create new wallet without seed keys verify.

### Steps 
1. I created a new wallet.
2. I set my password.
3. The website showed me the "Seed Phrase". I saved the "Seed Phrase" 
4. The website asked for my "Seed Phrase" confirmation.
5. At that moment I closed the window and opened metamask again.
6. The website didn’t asked for "Seed Phrase" verify, just asked the password.
7. I entered my password, the website directed me to my wallet, without any "Seed Phrase" confirmation.

### Screenshots

<img width="1324" alt="Screen_Shot_2021-06-09_at_22 46 49" src="https://user-images.githubusercontent.com/79153050/121419615-d1e88d00-c974-11eb-971e-e1c633353639.png">
<img width="568" alt="Screen_Shot_2021-06-09_at_22 06 30" src="https://user-images.githubusercontent.com/79153050/121419270-73231380-c974-11eb-9da2-9ed6c4e16909.png">
<img width="747" alt="Screen_Shot_2021-06-09_at_22 16 31" src="https://user-images.githubusercontent.com/79153050/121419283-761e0400-c974-11eb-927b-623d5f0cb53c.png">

### Browser details
OS: MacOS High Sierra 10.13.6
Browser: Opera MacOs 76.0.4017.154
Metamask: 9.5.9  
Metamask Wallet (THIS WALLET FOR TEST!! PLEASE DONT SEND ANYTHING) : 0xac46E240B17F0C5599088Bc8e6612b527f3EbFE9

**Comment by darkwing** [comment] 2021-06-14 19:18
I couldn't reproduce using the steps provided.  When I closed the window before confirming the seed phrase, I then opened a new window, and when clicking the MetaMask extension button in the toolbar, MetaMask opened to full window to the "Secure your wallet" video screen, which shows *before* the seed phrase process.

**Comment by darkwing** [comment] 2021-06-14 20:44
Could you provide a video illustrating the issue?  Perhaps I'm not reproducing correctly.  Thank you!

**Comment by jacobc-eth** [comment] 2022-03-30 21:25
Hi @Yogitoraito, it appears this issue does not exist in current versions of Opera. I tested on v85. Could you please update and retry? I'm going to close this issue for now, but if the issue persists for you, let me know and we'll re-open.

**Closed by jacobc-eth** 2022-03-30 21:25 UTC
Labels: needs-reproduction, needs-information
