### ISSUE TITLE
Account info icons

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8682] opened 2020-05-28 16:22 UTC
![icon misalignment](https://user-images.githubusercontent.com/542863/83167150-ba6d9780-a0c4-11ea-9520-97f05ce5449a.png)

On some systems, this happens. Not on all, though!

Seen on both mac and manjaro chrome.

**Comment by tmashuang** [comment] 2020-05-28 16:52
Possible solution would be to remove the this line.
https://github.com/MetaMask/metamask-extension/blob/a6f21563864babedc2636cfb0aba0cb2d7a79d66/ui/app/components/ui/menu/menu.scss#L36

**Comment by brad-decker** [comment] 2020-05-29 15:10
@tmashuang and @danfinlay -- could you check out the active rules on the .menu-item button when you get a chance? I can only recreate the above experience if I disable the grid-template-columns rule applied. I'd like to see what rules are active on browsers that show the bad behavior by default.

**Comment by tmashuang** [comment] 2020-05-29 18:18
Is this what youre referring to?
![image](https://user-images.githubusercontent.com/13376180/83291859-f0327f00-a19d-11ea-88be-56cc27d1592d.png)

**Comment by tmashuang** [comment] 2020-05-29 18:36
Neither of those options, `auto`/`1fr 1fr`, are working for me. Changing the `grid-template-columns` to any value doesn't seem to work for me either. Only when removing the `display: grid` entirely fixes it for me.

**Comment by Gudahtt** [comment] 2020-06-01 17:45
`display: grid` was used to accommodate a menu item with a subtitle, [as shown here](https://user-images.githubusercontent.com/2459287/82957944-9148ec00-9f8a-11ea-8df5-64c40c0ee26a.png).

I can't reproduce this failure locally, and I can't find any known CSS grid bugs that seem relevant 🤔.

What version of Chrome is this reproducible in? I'm using 83.0.4103.61

**Comment by brad-decker** [comment] 2020-06-01 17:46
@Gudahtt how do we get to that view? I'd love to see how the failed state looks when viewing that screen.

**Comment by Gudahtt** [comment] 2020-06-01 18:03
That's shown with a custom RPC endpoint that has a custom block explorer URL. The custom block explorer URL is used for the subtitle

**Comment by tmashuang** [comment] 2020-06-01 18:05
81.0.4044.138 is my version, once I tested 83.0.4103.61 it display as intended. Closing, but will be aware of users/support tickets/issues with slightly older versions having this issue.

**Closed by tmashuang** 2020-06-01 18:05 UTC
