### ISSUE TITLE
Unable to send ZRX tokens using myetherwallet

### ISSUE THREAD

**Issue by cooperdickerson** [MetaMask/metamask-extension#2717] opened 2017-12-09 22:12 UTC
I have been trying to send some ZRX tokens to my from metamask to an exchange account. I connect myetherwallet to metamask and can see the amounts of my tokens. Then I enter the wallet I want to send it to, select ZRX for the token and fill in the amount to send. Then the gas limit field automatically adjusts itself. Then I press the "generate transaction" and "send transaction" buttons after which the follow box pops up:
![image](https://user-images.githubusercontent.com/34405460/33799906-b9242f6e-dcfa-11e7-991d-517dccbef7ac.png)

As you can see, most of the fields in this box aren't populated. After this I click the "Yes, I am sure! Make transaction." button and a metamask window appears wanting me to verify the transaction. This metamask window says nothing about how many tokens I'm sending. When I submit the transaction it just says that the transaction failed and gives an error saying "rpc error with payload" and "transaction underpriced". 

If anyone can help I would really appreciate it. 
Thanks

**Comment by brandoncurtis** [comment] 2017-12-10 01:42
Everything is a bit overloaded today and as you found, the MyEtherWallet (MEW) token-sending informational interface doesn't seem to be loading.  You're also correct that MetaMask does not show the number of tokens being transacted, which is just a shortcoming of the current version of MetaMask.

Even weirder, when transferring ZRX you'll see that the transaction is sending 0 ETH from your address to address `0xe41d2489571d322189246dafa5ebde1f4699f498`.  This is the [address of the ZRX token contract](https://etherscan.io/address/0xe41d2489571d322189246dafa5ebde1f4699f498).  What your transaction is actually doing is asking the ZRX token contract, which is basically a little program that maintains a spreadsheet listing the balance of each Ethereum address that holds ZRX, to `transfer` some or all of your balance to another account's balance.  Information about how much ZRX to move, and what address to move it to, is encoded in the `data` field of your transaction, which you can see in the "Raw Transaction" and "Signed Transaction" text boxes in MEW.

You're right that that's pretty weird and abstract and not a great user experience.  Ethereum and the tools built to work with it, like MetaMask, are very new and still expose a lot of confusing implementation details to the user.  As the ecosystem matures, these edges will be rounded off.

As for the "transaction underpriced" error, that suggest that your transaction's gas price was set too low.  I just tried a ZRX transfer myself, and I think the problem is that MEW suggests a gas price of 20 gwei.  The network is very congested right now [in part due to cryptokitties](https://medium.com/metamask/metamask-cryptokitty-performance-update-83d851af0147), and lately transactions have needed a gas price of 30-60 gwei to go through properly.  You can check [ETH Gas Station](https://ethgasstation.info/) for realtime info on network congestion and suggested gas prices.

Let me know if you need any additional help!

**Comment by cooperdickerson** [comment] 2017-12-11 01:49
@brandoncurtis Thanks for that explanation. I was able to get the transaction through by changing the gas price on metamask. I really appreciate your help.

**Closed** 2017-12-11 01:55 UTC
