### ISSUE TITLE
Support EIP-2930

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#12869] opened 2021-11-26 12:12 UTC
Allows users to use `access_list` feature for type tx =1 or type =2 
https://eips.ethereum.org/EIPS/eip-2930

Use case:
https://help.gnosis-safe.io/en/articles/5249851-why-can-t-i-transfer-eth-from-a-contract-into-a-safe

I don't believe Metamask supports txType = 1 at all

**Comment by danfinlay** [comment] 2021-12-01 17:30
Closing as a duplicate of #11863, where we will be tracking this feature request.

**Closed by danfinlay** 2021-12-01 17:30 UTC
