### ISSUE TITLE
Can't customize transaction nonce in ERC20 approve transactions

### ISSUE THREAD

**Issue by invocamanman** [MetaMask/metamask-extension#10812] opened 2021-04-02 20:45 UTC
**Describe the bug**
Transaction nonce can't be customized in ERC20 `approve` transactions

**Steps to reproduce**

1. Activate `Customize transaction Nonce`
2. Click in  `approve` button of any dapp ( like uniswap) or, send a transaction to an ERC20 token with the hex Data for approve tokens ( I know is the same, but i though that maybe with this alternative route it could be customized the nonce)
3. There's no place to customize the nonce, only the amount approved, gas and gasLimit

**Expected behavior**
In the approve pannel, when click on `transaction details` should be a nonce field when the `Customize transaction Nonce`
option is activated

**Browser details (please complete the following information):**
 - OS: Ubuntu 20
 - Browser:  Chrome Version 87.0.4280.66 (Official Build) (64-bit)
 - MetaMask Version: 9.2.1

**Comment by tmashuang** [comment] 2021-04-02 20:47
Duplicate of https://github.com/MetaMask/metamask-extension/issues/10129

**Closed by tmashuang** 2021-04-02 20:47 UTC
