### ISSUE TITLE
Metamask is not initiating when I click on the foz icon on the Crome 

### ISSUE THREAD

**Issue by Sudheerverma** [MetaMask/metamask-extension#3719] opened 2018-03-25 17:48 UTC
Metamask is not initiating when I click on the foz icon on the Crome it's showing connecting to main ethereum Network

**Comment by lazaridiscom** [comment] 2018-03-25 17:54
Hi @Sudheerverma , this is a know issue. You could close this issue as a "duplicate of #3706".

Some info in this: https://github.com/MetaMask/metamask-extension/issues/3706#issuecomment-375835556

**Comment by jrmoreau** [comment] 2018-03-26 16:23
@Sudheerverma do you see a blank screen or rather a spinning loading sign which indicates it's not connecting to the network?

**Comment by Sudheerverma** [comment] 2018-03-26 16:25
Hi Team,

Yes same issue

**Comment by Sudheerverma** [comment] 2018-03-26 16:28
It's spinning loading and not connecting to main ethereum network

**Comment by kevcowley** [comment] 2018-03-27 12:52
I have the icon but get a blank screen, appreciate any updates

**Comment by AquaWookie** [comment] 2018-03-27 13:00
^ Same. Newest Chrome Newest MetaMask no errors thrown in console- same blank screen.

**Comment by AquaWookie** [comment] 2018-03-27 13:00
I even tried to remake in Firefox from seed but it lost my tokens from an ICO I participated in recently that required me to configure the wallet for them. Need this fixed in Chrome.

**Comment by cwrthiem** [comment] 2018-03-28 03:40
![metamask](https://user-images.githubusercontent.com/37857419/38007599-64275d18-3274-11e8-963d-8694502e7c3e.png)

**Comment by danfinlay** [comment] 2018-03-30 18:51
This should be fixed in MetaMask 4.4.0, by PR #3732.

Can you right click the fox, select "Manage extensions" and confirm your version is the (buggy) 4.3.0? If you're on an old version, click `Update extensions now` to get the latest version.

If you're on 4.4.0, please check your logs for errors:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

If you see some errors then, please open a new issue to report your personal problem. I'm closing this issue now because we fixed the original cause, and I want to make sure we are keeping the instances separated.

**Closed by danfinlay** 2018-03-30 18:51 UTC
