### ISSUE TITLE
Indefinitely loading tokens after restarting local Ganache node. 

### ISSUE THREAD

**Issue by robertmagier** [MetaMask/metamask-extension#5705] opened 2018-11-08 20:20 UTC
Steps to reproduce. 

1. Start your local Ganache. 
2. Create a new token contract on your local Ganache. 
3. Change Metamask network to your local node and Add this token to your Metamask.
4. Stop and start Ganache.  This will remove token contracts from it. 
5. Change network to Main Ethereum Network and back to your local network. 
6. Create new Token Contract on your local Ganache. 
7. Add this new token to Metmask. 
8. Check Token balance in Metamask. 

It will show loading tokens for ever.  I assume this is because token created in step 2 doesn't exist anymore. It makes sense on Main Ethereum Network as token will be always there, but it doesn't work on Local Node. I tried to reset my account, but it doesn't remove information about old Tokens.  The only sollution is to unsitall metamask, stop firefox and start it again and install metamask again.

**Comment by tmashuang** [comment] 2018-11-08 20:30
Looks like we have additional reproduction steps since this issue https://github.com/MetaMask/metamask-extension/issues/5696. If this issue is the correct reproduction, closing the older issue as a duplicate would speed up the development process.

**Comment by robertmagier** [comment] 2018-11-08 21:14
Great. I added one more step. It is required to change network to Main Ethereum and back to Local one. 
It is there in description.

**Comment by tmashuang** [comment] 2020-02-04 20:43
Closing due to this being an older thread. With the advent of Ganache Workspaces, where state can be saved locally, I recommend use that feature so that it can be easily synced with MetaMask. If continue to see the issue on the latest version of MetaMask and Ganache, please open a new issue with those specifics.

**Closed by tmashuang** 2020-02-04 20:43 UTC
Labels: S02-customNetworks, S03-tokens, T00-bug
