### ISSUE TITLE
MetaMask Extension Not Loading in FireFox [Bug]: 

### ISSUE THREAD

**Issue by mo-diggity** [MetaMask/metamask-extension#22659] opened 2024-01-25 01:01 UTC
### Describe the bug

When trying to open the Metamask extension in Firefox it just loads forever. Very similar to this issue https://github.com/MetaMask/metamask-extension/issues/22355, however the solution to that one does not work for me. When inspecting MetaMask, there is nothing shown under the storage tab for me.

### Expected behavior

Metamask to open, access to my wallets

### Steps to reproduce

Have Metamask installed in Firefox
Try to open it

### Version

11.7.2?

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Hardware wallet

Ledger

**Comment by deshvin** [comment] 2024-01-25 18:39
@mo-diggity 
Can you please provide error messages from the console logs for MetaMask?

1. In Firefox, navigate to: moz-extension://91a50b78-b633-4de3-a3a2-e326ba454b76/home.html#
2. Press **F12** (or **fn + F12**) to open the **Web Developer Tools** pane
3. Switch to the **Console** tab
4. Look for red error messages; expand them if needed
5. Screenshot or copy/paste the errors in your response.

**Comment by 0xFirekeeper** [comment] 2024-01-30 19:40
![27fe865ccd9a3680d1619f7eccc07c09](https://github.com/MetaMask/metamask-extension/assets/43042585/9fa9510d-3672-4702-bfa8-e59d27681f6a)

**Comment by mo-diggity** [comment] 2024-02-10 21:55
> @mo-diggity Can you please provide error messages from the console logs for MetaMask?
> 
>     1. In Firefox, navigate to: moz-extension://91a50b78-b633-4de3-a3a2-e326ba454b76/home.html#
> 
>     2. Press **F12** (or **fn + F12**) to open the **Web Developer Tools** pane
> 
>     3. Switch to the **Console** tab
> 
>     4. Look for red error messages; expand them if needed
> 
>     5. Screenshot or copy/paste the errors in your response.



> @mo-diggity Can you please provide error messages from the console logs for MetaMask?
> 
>     1. In Firefox, navigate to: moz-extension://91a50b78-b633-4de3-a3a2-e326ba454b76/home.html#
> 
>     2. Press **F12** (or **fn + F12**) to open the **Web Developer Tools** pane
> 
>     3. Switch to the **Console** tab
> 
>     4. Look for red error messages; expand them if needed
> 
>     5. Screenshot or copy/paste the errors in your response.

@deshvin 

prob overly cautious but i went to debug extensions > MM > console instead of where you said to go. Hopefully this still is helpful

![image](https://github.com/MetaMask/metamask-extension/assets/133728135/bc1dc30e-bf0e-48cb-927c-e9bbf79517c6)

**Comment by mo-diggity** [comment] 2024-02-10 21:56
> @mo-diggity Can you please provide error messages from the console logs for MetaMask?
> 
>     1. In Firefox, navigate to: moz-extension://91a50b78-b633-4de3-a3a2-e326ba454b76/home.html#
> 
>     2. Press **F12** (or **fn + F12**) to open the **Web Developer Tools** pane
> 
>     3. Switch to the **Console** tab
> 
>     4. Look for red error messages; expand them if needed
> 
>     5. Screenshot or copy/paste the errors in your response.

@deshvin prob overly cautious but i went to debug extensions > MM > console instead of where you said to go. Hopefully this still is helpful
![image](https://github.com/MetaMask/metamask-extension/assets/133728135/0ee61b62-fc51-4a1a-9df4-562fd7a50f96)

**Comment by A7jj** [comment] 2024-02-26 14:22
I have the same issue here!

**Comment by A7jj** [comment] 2024-02-26 14:25
<img width="1045" alt="Screen Shot 2024-02-23 at 2 36 44 AM" src="https://github.com/MetaMask/metamask-extension

**Comment by A7jj** [comment] 2024-02-26 14:26
<img width="1045" alt="Screen Shot 2024-02-23 at 2 36 44 AM" src="https://github.com/MetaMask/metamask-extension/assets/80799823/7606edd6-3608-497f-87c0-f0e7bddb0e97">

**Comment by gauthierpetetin** [comment] 2024-02-27 16:51
Hi @A7jj , we're currently actively working on this issue but unfortunately we're not able to reproduce it so far.
Of course, if you can think of any additional information that could help us reproducing this issue, please share it with us.

**Comment by A7jj** [comment] 2024-02-28 06:24
@gauthierpetetin, unfortunately I have nothing, I was hopping that you have the solution. Keep me posted for any progress.

**Comment by gauthierpetetin** [comment] 2024-02-28 09:56
Sure, will do!

**Comment by GianMassimiani** [comment] 2024-02-29 21:05
@gauthierpetetin you can change the title of the issue because it's not only Firefox related. I have the same issue in Chrome. I noticed that this popped up right after a chrome update. Note that I migrated from Firefox to Chrome about one year ago after I encountered this other issue https://github.com/MetaMask/metamask-extension/issues/9196
![image](https://github.com/MetaMask/metamask-extension/assets/30569186/feaf4ca1-92e6-4492-ba16-138b2c4ce737)

**Comment by GianMassimiani** [comment] 2024-02-29 21:21
Also, it seems to be the same issue reported here https://github.com/MetaMask/metamask-extension/issues/20847

**Comment by danjm** [comment] 2024-03-01 01:47
@GianMassimiani that is a different issue from the firefox problem.The error you are seeing was fixed in v11.7.5

If you update to the latest MetaMask version the error should go away.

**Comment by grintraitao** [comment] 2024-03-04 08:13
Got the bug on my Chrome my main work Chrome profile, Metamask extension on the other profile works fine. 
Metamask version: 11.7.2
Chrome version: 122.0.6261.95 (Official Build) (64-bit)

**Comment by GianMassimiani** [comment] 2024-03-04 20:58
> @GianMassimiani that is a different issue from the firefox problem.The error you are seeing was fixed in v11.7.5
> 
> If you update to the latest MetaMask version the error should go away.

@danjm thanks, updating Metamask indeed fixed it

**Comment by mo-diggity** [comment] 2024-03-05 22:42
> > @GianMassimiani that is a different issue from the firefox problem.The error you are seeing was fixed in v11.7.5
> > If you update to the latest MetaMask version the error should go away.
> 
> @danjm thanks, updating Metamask indeed fixed it

@GianMassimiani      I am also unable to update firefox - im sure i could if i deleted it but that would lose my seed.

**Comment by tab00** [comment] 2024-03-15 19:15
I encountered this error now. It stays forever loading:
![image](https://github.com/MetaMask/metamask-extension/assets/12715448/541f2c67-3270-4a22-886d-c2636ac7b046)

Here's debug output in the FireFox console:
![image](https://github.com/MetaMask/metamask-extension/assets/12715448/97c299df-d4a7-40ab-88cc-7f2db12931e3)

How can we fix it?

**Comment by A7jj** [comment] 2024-03-15 20:17
unfortunately, until this moment there's no solution for it as I worked with Meta mask engineers, they have no solution for it yet, I encountered this problem over a month ago, and still working on it. Nothing yet! My best advice for you is to start using Binance App! for the future!

**Comment by SKYBITDev3** [comment] 2024-03-16 16:50
Try my solution that I've just posted at https://github.com/MetaMask/metamask-extension/issues/9196?#issuecomment-2002042848

**Comment by A7jj** [comment] 2024-03-17 15:30
@SKYBITDev3 my problem on MacOS. I hope there is a way to fix it.
I appreciate your help!

**Comment by mo-diggity** [comment] 2024-03-23 03:53
> Try my solution that I've just posted at #9196

@SKYBITDev3 This worked for me!, Thank you! I had pretty much had given up hope on this

**Comment by gauthierpetetin** [comment] 2024-06-14 15:19
Hi everyone, if you're still facing a similar issue, this issue is the possible cause: https://github.com/MetaMask/metamask-extension/issues/9196

**Closed by gauthierpetetin** 2024-06-14 15:19 UTC
Labels: type-bug, needs-information, Sev1-high, team-extension-platform, in-progress, external-contributor
