### ISSUE TITLE
Breaks Google Chat and Google Hangouts

### ISSUE THREAD

**Issue by rtheunissen** [MetaMask/metamask-extension#2838] opened 2018-01-02 17:47 UTC
Having the extension enabled throws an error in the console when attempting to start a Google Hangouts video call or media upload.

**Comment by kumavis** [comment] 2018-01-02 21:38
we use google hangouts all the time with no issue

hangouts has introduced new URIs recently -- can you give us an example link that doesn't work for you?

**Comment by 3X3Q** [comment] 2018-02-11 00:13
I am able to reproduce this. Spent a while trying to figure out which extension of mine was messing with Hangouts; it's Metamask.

![metamask](https://user-images.githubusercontent.com/8482049/36067908-42f3f6da-0e7d-11e8-9a73-08afaca2d016.PNG)
![metamask1](https://user-images.githubusercontent.com/8482049/36067909-4305434a-0e7d-11e8-9fd0-daa66fd4646d.PNG)

**Comment by Slyke** [comment] 2018-02-19 00:36
I too am having this issue. It took me a while to figure out why my Hangouts suddenly stopped working. I ended up disabling my extensions one by one until it started working, and MetaMask is the culprit. Let me know if you need any details on the versions I'm running.

**Comment by scbrownell** [comment] 2018-02-23 19:37
I'm having this problem as well. If I disable the MetaMask extension, Hangouts works normally.

**Comment by BlueT** [comment] 2018-03-05 06:43
I'm having the same issue.

Was wondering why I suddenly can't answer to my work concalls (hangout) anymore on all of Firefox (58.0.2 Quantum, 64bit, Ubuntu Linux 16.04), Google Chrome, and Chromiun.
After lots of checks and try disabling extensions one by one, found out that was due to MetaMask extension.

**Comment by mfppvl** [comment] 2018-05-12 23:50
Google hangouts stops as soon as metamask open, after closing metamask you can rejoin same hangouts conversation. (windows 10, chrome)

**Comment by bdresser** [comment] 2018-06-18 16:45
@Levino @rtheunissen is your Hangout running in a browser tab or as a popup?

**Comment by Levino** [comment] 2018-06-18 17:44
Popup

**Comment by bdresser** [comment] 2018-06-18 17:50
gotcha, sounds like this is related to #4553 and should be fixed shortly.

**Comment by bdresser** [comment] 2018-06-21 22:16
fix was merged in #4592, will be out with the next release

**Closed by bdresser** 2018-06-21 22:16 UTC
Labels: N02-needsReproduction, T00-bug
