### ISSUE TITLE
Metamask does not broadcast new transactions when there are several waiting to be confirmed.

### ISSUE THREAD

**Issue by MarkWieczorek** [MetaMask/metamask-extension#5113] opened 2018-08-21 08:24 UTC
I have encountered this problem several times:

* I submitted several (about 4) transactions with very low gas prices. They show up on etherscan as pending, and I don't care how long it takes for these low priority transactions to confirm.
* After submitting these transactions, I next submitted a high priority transaction with a high gas price that should ensure that it is confirmed immediately. However, even though metamask lists this as "submitted", it is not broadcast to the network and does not show up on etherscan.

This scenario has happened several times to me: As soon as the low gas price transactions confirm in a couple days, metamask will submit the last transaction to the network, and it will immediately confirm. This behavior is really annoying: In this situation I expect that if I submit a transaction with a high gas price, that metamask will broadcast this immediately to the network.

**edit** : after about 24 hours, the higher priority transaction was finally broadcast, even though the other 4 low priority transactions haven't confirmed yet. That's great, but not normal.

Browser: Chrome
OS: macOS

**Comment by bdresser** [comment] 2018-08-21 18:07
@MarkWieczorek transactions from the same account must be processed in order of their nonce. So if you submit a series of transactions with low gas prices, then later submit a transaction with a high gas price, the later transaction will have a higher nonce and *cannot* be confirmed until the earlier tx are confirmed.

We've considered adding a warning to the confirm screen when a user tries to submit a transaction but already has several pending. We also have new designs for the transaction "outbox" (#4786) that will hopefully make this clearer.

@danfinlay this is a common question - any other thoughts?

**Comment by MarkWieczorek** [comment] 2018-08-21 18:29
Does this mean that if this transaction is eventually dropped from the mempool, that none of the other transactions with higher nonces will ever confirm ?

**Comment by danfinlay** [comment] 2018-08-21 21:43
> Does this mean that if this transaction is eventually dropped from the mempool, that none of the other transactions with higher nonces will ever confirm ?

No, because MetaMask remembers the transaction and re-broadcasts it on a gradually diminishing interval. It may be dropped from one client's mempool, but as long as your client remembers it, the transaction is still mineable.

**Comment by MarkWieczorek** [comment] 2018-08-22 10:01
Perhaps it would be useful to put a warning icon next the the first transaction when their are others that follow, like "Warning, transactions are processed sequentially. The following transactions will only be processed after this transaction is confirmed." If I thought I understood how Ethereum works, I presume that there are a lot of people who also didn't realize this...

**Comment by danfinlay** [comment] 2018-08-22 17:33
You'll be glad to hear we're already planning to add UI to emphasize the sequential nature of tx processing.

https://github.com/MetaMask/Design/issues/25#issuecomment-404629221

**Comment by bdresser** [comment] 2018-08-22 17:37
@MarkWieczorek The designs Dan and I linked above should help - but we've also [discussed this](https://github.com/MetaMask/Design/issues/25#issuecomment-411836556) particular warning before although haven't moved on it. Opened an issue here (https://github.com/MetaMask/metamask-extension/issues/5126) to discuss

Closing this for now, thanks again for the feedback.

**Closed by bdresser** 2018-08-22 17:37 UTC
Labels: design feedback

**Comment by CptanPanic** [comment] 2018-08-28 16:50
So what is the current work around for this issue?  I have it now with some stuck low-gas transactions?  Just wait?

**Comment by danfinlay** [comment] 2018-08-29 20:18
Your earliest stuck transaction should have a "retry with higher gas" button, and you should click that to resubmit it with a higher gas price.
