### ISSUE TITLE
Edit permission screen doesn't allow to set custom amount and reverts always to max

### ISSUE THREAD

**Issue by lyricalpolymath** [MetaMask/metamask-extension#7735] opened 2019-12-31 11:46 UTC
Setting the allowance in the edit permission screen
(while opening an Oasis Save https://oasis.app/save  but possibly on every similar smart contract) 
doesn't work, it doesn't set a custom amount and always leaves the maximum

**To Reproduce (REQUIRED)**
- get some DAI
- create your Oasis Safe proxy (if you don't have one already)
- set the allowance and in the MM pop-up click "Edit Permission"
- choose custom amount

you will see in the data field (or after confirming the tx) that it has set the maximum allowance possible ffff...ffff rather than your custom set value

**Expected behavior**
you'd expect your custom allowance to be set there

**Screenshots**
![Screenshot 2019-12-31 at 12 19 00](https://user-images.githubusercontent.com/516744/71620577-f4e11000-2bca-11ea-9949-0b9391e13d0f.jpg)
![Screenshot 2019-12-31 at 12 11 54](https://user-images.githubusercontent.com/516744/71620673-73d64880-2bcb-11ea-95d7-014665c15c91.jpg)
![Screenshot 2019-12-31 at 12 12 52](https://user-images.githubusercontent.com/516744/71620672-733db200-2bcb-11ea-944c-984989820f32.jpg)

**Browser details (please complete the following information):**
 - OS: Os X 10.14.6
- Browser Version 79.0.3945.88 (Official Build) (64-bit)
 - MetaMask Version 7.7.1

**Comment by jennypollack** [comment] 2020-01-28 17:28
thanks for reporting @lyricalpolymath closing in favor of https://github.com/MetaMask/metamask-extension/issues/7915 which is tracking the current fix

**Comment by jennypollack** [comment] 2020-01-28 17:36
Duplicate of #7915
Thanks for reporting @lyricalpolymath

**Comment by jennypollack** [comment] 2020-01-29 13:07
closed in #7919

**Closed by jennypollack** 2020-01-29 13:07 UTC
Labels: N02-needsReproduction, T00-bug

**Comment by tmashuang** [comment] 2020-01-30 20:37
Fixed by https://github.com/MetaMask/metamask-extension/pull/7918, will be out in the next release.
