### ISSUE TITLE
UI: always show sign button

### ISSUE THREAD

**Issue by dorijan** [MetaMask/metamask-extension#7458] opened 2019-11-18 16:01 UTC
Hi,
when user is shown MM dialog to sign order (we are using 0x to sign orders) on lower screen resolutions, user has to scroll down and right to be able to see the buttons. Is there a way that this buttons would always be visible? It is really big problem for us, because we have to explain to users that they have to scroll.
[Image1](https://p13.zdusercontent.com/attachment/2313093/2l9fTuDV2pFr5jYpvvH7soOmN?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..A-bNl5ZVBk-J2US9qBNrUg.p271czSCrem1-fWiQ6nrGMl5GuLrL03km-r0QVuzSZ9bFKH8_Np6hA08uH9nc32vAxaZHNHBzZhHrjn-Z4OQvmuPryDbgqmFb1JaAdshsgQqsa8xXvr_H-uMtqH4NOn0aqPOLsgnJ8UE0do9q96OdXAFcfthXJ1j1ApkOdl-iGlDD64iSUKhUfplhtW5prbxL7uDMveVn4q6m0NcJ1ogGLJsq4LmjYPpR4parLZY3k0taxCEtQPAnqQfXL5ZszVXEWeZr2Yh7NlZn4mktzr9Ql_LBEHJG4-Ogaj4yLlovcY.6TCvYYhW4ckH7R8QFqrR7g)

[image2](https://p13.zdusercontent.com/attachment/2313093/ZG2lLa75FvTUG2n2QEiu2PIZz?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..hYV08ReYtS6rBdgMiRB8vg.7gI8nHpVhmLJ9OK0p7vWaxP3doEYUp5KH_BXuexLPhlR-IxURYPMuSQvs6cxjDONG5BaNpSMvC3IFDpiUD66TGVO1XuFx707_WxIz2UMLV0Ti3nQBcIfPAHb7FpVEJAhPAlVCLD1W2u17d3S8_P4saf3guLQfuGXzLuu3lVfo5Ue-kxZ3l08--5Ux9bCDdZDgajQ-OwyGUOcBXtgRNNfds38dCzyRkiWGkDQ0TONq3IOD2Wx8oyQUhMDfMJ6GDUxpW0T0Qstn5lNE01eL5zcJFT6Z8NeZgatbKK5Yo87VuA.e4Va1xJSU6gU7BaXOxnKNw)

Thank you

**Comment by Gudahtt** [comment] 2021-01-07 23:54
Closing as a duplicate of #7443

This issue should be resolved in the latest version of MetaMask. Please open a new issue if you're still seeing this. Thanks!

**Closed by Gudahtt** 2021-01-07 23:54 UTC
Labels: L03-UI
