### ISSUE TITLE
Allow editing gas price on transaction "cancel" screen.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8192] opened 2020-03-13 21:21 UTC
When the gas market is extremely volatile as it has been this week, sometimes a person may want to cancel a transaction _urgently_.

In this case, our default cancelation, which adds a small gas price over the replaced transaction, is insufficient, and results in a stalled transaction.

The current workaround would be to then "speed up" the cancellation attempt.

We may want to allow editing gas price, and maybe even basing it on current market conditions, on cancellations also.

**Comment by danfinlay** [comment] 2020-03-13 21:24
Another way to work around this is to force your MetaMask to forget about pending transactions, using the "reset account" feature:
https://metamask.zendesk.com/hc/en-us/articles/360015488891-Resetting-an-Account

After this, any transactions sent will have gas prices set in the usual way, allowing replacing pending transactions. You just have to be careful, since this can "unclog" your transaction queue in a way that processes all your pending transactions, if only the first one was priced low. You could avoid that situation by using "Cancel all" before resetting account.

**Comment by Gudahtt** [comment] 2020-07-14 14:42
This is a duplicate of #8011

**Closed by Gudahtt** 2020-07-14 14:42 UTC
Labels: L34-advancedGas
