### ISSUE TITLE
[Bug]: Can't load to home page

### ISSUE THREAD

**Issue by LeeChunHao2000** [MetaMask/metamask-extension#25567] opened 2024-06-27 16:20 UTC
### Describe the bug

sentry loading seems not working

### Screenshots/Recordings

![截圖 2024-06-28 凌晨12 14 57](https://github.com/MetaMask/metamask-extension/assets/64617939/50ba4854-3ade-4be3-9b43-97e10497913a)

### Steps to reproduce

1. Open Browser

### Version

11.16.10

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by anaamolnar** [comment] 2024-06-28 10:17
Hi there, @LeeChunHao2000 Thanks for reporting this! Would you mind letting us know if the behavior is consistent even after you restart your device? Did you do anything specific before this happened? Can you please if you have a newer version for update in Firefox? Thank you!

**Comment by LeeChunHao2000** [comment] 2024-06-28 13:18
@anaamolnar Hi there, thank you for your follow-up. I've tried restarting both the device and the browser, but unfortunately, the issue still persists. The problem occurs simply by launching the browser and opening MetaMask. My current Firefox version is 127.0.2. Any further info you need just feel free to let me know. Thank you!

**Comment by gauthierpetetin** [comment] 2024-07-12 21:14
Hi @LeeChunHao2000 , thanks for reporting this issue!
We'll close it in favour of [this one](https://github.com/MetaMask/metamask-extension/issues/25567), which we're already investigating on at the moment, as our assumption is it has the same root cause.

**Closed by gauthierpetetin** 2024-07-12 21:14 UTC
Labels: type-bug, Sev1-high, team-extension-platform, external-contributor, regression-prod-11.16.10

**Comment by LeeChunHao2000** [comment] 2024-07-12 22:14
@gauthierpetetin Hi, I fixed the problems by following steps：

### 1. Go to local metamask extension folder

It's like：

`/Users/{username}/Library/Application Support/Firefox/Profiles/6b7devvk.default-release-2/storage/default/moz-extension+++{extension-uuid}^userContextId=XXXXXXX/idb/`

### 2. Rename file

Rename this file to another number, like plus 1 or minus 1：

`{numbers}wleabcEoxlt-eengsairo.files/{numbers_file}`

### Restart Firefox

Then it works

**Comment by gauthierpetetin** [comment] 2024-07-15 09:21
Thanks a lot for sharing this @LeeChunHao2000 , this will help us in our investigation.
cc @MetaMask/extension-platform for visibility
