### ISSUE TITLE
[Bug]: Typed Data v4 signing not working with Trezor after 11.7.3 and 11.7.4 roll out

### ISSUE THREAD

**Issue by 0xGitGuy** [MetaMask/metamask-extension#22665] opened 2024-01-25 18:49 UTC
### Describe the bug

Signing with typed datav4 with trezor hw throws keyring controller error. Error is not present when non-trezor wallets are used. Did not update trezor firmware. Same firmware with 11.7.2 works fine:

(tested at https://metamask.github.io/test-dapp/ to be sure it's not dapp specific)

`Result: Error: Keyring Controller signTypedMessage: Error: Invalid parameter "" (= {"path":"m/44'/60'/0'/0/3","data":{"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Group":[{"name":"name","type":"string"},{"name":"members","type":"Person[]"}],"Mail":[{"name":"from","type":"Person"},{"name":"to","type":"Person[]"},{"name":"contents","type":"string"},{"name":"attachment","type":"bytes"}],"Person":[{"name":"name","type":"string"},{"name":"wallets","type":"address[]"}]},"message":{"contents":"Hello, Bob!","from":{"name":"Cow","wallets":`

This renders all permit signing on dapps not possible can could hinder withdrawal of funds or other actions. 

Bug is not present in 11.7.2

### Expected behavior

No error 

### Steps to reproduce

1. Use metamask 11.7.3 or 11.7.4
2. https://metamask.github.io/test-dapp/
3. Sign the sample typed v4 
4. Error should appear after signing

### Error messages or log output

```shell
Result: Error: Keyring Controller signTypedMessage: Error: Invalid parameter "" (= {"path":"m/44'/60'/0'/0/3","data":{"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Group":[{"name":"name","type":"string"},{"name":"members","type":"Person[]"}],"Mail":[{"name":"from","type":"Person"},{"name":"to","type":"Person[]"},{"name":"contents","type":"string"},{"name":"attachment","type":"bytes"}],"Person":[{"name":"name","type":"string"},{"name":"wallets","type":"address[]"}]},"message":{"contents":"Hello, Bob!","from":{"name":"Cow","wallets":
```

### Version

11.7.3, 11.7.4

### Build type

None

### Browser

Brave

### Operating system

Windows

### Hardware wallet

Trezor

### Severity

- users who depend on permit signing to withdraw, move or swap funds will not be able to perform action if funds are on protocol that enforces typed v4 signing.

**Comment by danjm** [comment] 2024-01-25 19:54
@0xGitGuy I am having trouble reproducing this. Which network were you on when you saw this bug? And what model of trezor are you using?

**Comment by vania221** [comment] 2024-01-25 22:31
Очікуємо подробиць для подальшого сортування. Незрозуміло, чи розбіжність у значеннях стосується лише маркера та/або мережі чи впливає на всіх користувачів. #1133

**Comment by vivek-consensys** [comment] 2024-01-30 12:48
Unable to reproduce this issue, will be closing this ticket. If this issue arises again, we will revisit.

**Closed by vivek-consensys** 2024-01-30 12:48 UTC
Labels: type-bug, external-contributor, team-hardware-wallets

**Comment by 0xGitGuy** [comment] 2024-01-30 13:24
11.7.5 its resolved. Will monitor
