### ISSUE TITLE
"What's new" message every time I open metamask

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#11220] opened 2021-06-01 23:10 UTC
Metamask 9.5.8

plz make it stop

**Comment by wjmelements** [comment] 2021-06-01 23:11
<img width="357" alt="Screen Shot 2021-06-01 at 4 11 32 PM" src="https://user-images.githubusercontent.com/799573/120401077-0a90c280-c2f4-11eb-8c77-127f3843594f.png">

**Comment by danjm** [comment] 2021-06-01 23:20
Thanks @wjmelements 

If you close the popup, lock metamask, then unlock metamask, do you see the popup again? See the below screen capture:

**Comment by wjmelements** [comment] 2021-06-01 23:21
> Thanks @wjmelements
> 
> If you close the popup, lock metamask, then unlock metamask, do you see the popup again? See the below screen capture:

Yes, the popup continues. Even if that were your spec I would consider it to be wrong behavior. As soon as I dismiss it I never want to see it again. I didn't even want to see it the first time.

**Comment by wjmelements** [comment] 2021-06-01 23:26
To be clear, the popup appears every time I open the Metamask popout, not when I unlock.

**Comment by wjmelements** [comment] 2021-06-01 23:27
If I open while it is locked, the popup recurs when I unlock.

**Comment by wjmelements** [comment] 2021-06-01 23:28
Opening and closing multiple times does not create multiple popups.

**Comment by danjm** [comment] 2021-06-01 23:31
If it is not too much trouble, would you be able to capture a video of going from a state of having metamask open and not seeing the "Whats new" message, to closing and then opening again to see the "Whats new" message again? It could help us debug.

**Comment by danjm** [comment] 2021-06-01 23:33
Also, what browser are you using?

**Comment by wjmelements** [comment] 2021-06-01 23:37
Chrome 90.0.4430.93

https://user-images.githubusercontent.com/799573/120402729-a839c100-c2f7-11eb-883d-81037361a520.mov

**Comment by danjm** [comment] 2021-06-01 23:38
Great. Thank-you. We will try to make this go away asap.

**Comment by danjm** [comment] 2021-06-01 23:53
@wjmelements Here are some simple steps you can take to make this go away now, so you don't have to wait for the bug fix.

1. Open MetaMask in full screen
2. You'll see the "What's new" message
3. If there is a scroll bar in the "What's new" message scroll to the bottom
4. Click the 'x' in the top right corner of the "What's new" message
5. Now you should not see the popup any more

Video below demonstrates how to do this:


https://user-images.githubusercontent.com/7499938/120403837-93712380-c31f-11eb-804e-97a3593a9fe8.mp4

**Comment by danjm** [comment] 2021-06-01 23:58
@wjmelements yeah, you have to open it in full screen first

**Comment by danjm** [comment] 2021-06-01 23:58
Click the three stacked dots to open a menu, and then click "Expand view"

![Screenshot from 2021-06-01 21-28-41](https://user-images.githubusercontent.com/7499938/120404181-5d806f00-c320-11eb-876b-8c269c5f6afb.png)

**Comment by wjmelements** [comment] 2021-06-02 00:00
Indeed, closing it in fullscreen fixed the issue. I appreciate the workaround. Of course, I hope you will agree this is not desirable behavior.

**Comment by danjm** [comment] 2021-06-02 00:01
So the intended behaviour is: see the message once, close it, never see it again.

Do you think that is correct, or do you think it should be different?

**Comment by wjmelements** [comment] 2021-06-02 00:02
Yes, that is correct.

**Comment by danjm** [comment] 2021-06-02 00:03
Also, out of caution and respect for privacy, I am going to delete your videos from your posts. Thank-you, they were helpful.

**Closed** 2021-06-03 16:28 UTC
Labels: Sev2-normal, type-bug
