### ISSUE TITLE
SAI migration notice is out of date

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#8431] opened 2020-04-27 21:21 UTC
From https://migrate.makerdao.com/

> Swapping Sai for Dai is no longer possible through the Migration Portal. Please visit a decentralized exchange to swap your Sai tokens.

So please remove the migration notice. Current SAI holders will need to wait for May 12th and get ETH.

**Comment by Gudahtt** [comment] 2020-04-28 05:06
Thanks for the report! We've already removed this notice on `develop`, but it hasn't shipped yet. It'll be in the next release.

**Comment by Gudahtt** [comment] 2020-04-28 05:06
Duplicate of #8376

**Closed by Gudahtt** 2020-04-28 05:06 UTC

**Comment by wjmelements** [comment] 2020-04-28 05:21
Okay, please ship it soon. We are seeing more confused people in our forum than usual.

**Comment by Gudahtt** [comment] 2020-05-01 12:13
This will be included in v7.7.9, which we're preparing for release now. It should be out soon.
