### ISSUE TITLE
MetaMask stuck in spinning state after transaction request

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#6515] opened 2019-04-26 01:33 UTC
Since updating to 6.4.0 from 6.3.2, Metamask has been stuck in a spinning state. It seems that transaction requests break the entire network for MetaMask permanently, and that there is no recovery besides uninstalling.

If I disable and re-enable the extension, I see the password prompt from the Rinkeby network. If I enter my password without changing the network, it gets stuck in the spinning state.
If I change the network first, it seems fine until I go to send a transaction, then instead of seeing the pending transaction it gets stuck in the spinning state, and then I can't sign in for that network either.

The dapp I was using was Etherscan's Write Contract tab.

**Comment by wjmelements** [comment] 2019-04-26 01:34
"Spinning State":
<img width="357" alt="Screen Shot 2019-04-25 at 6 34 02 PM" src="https://user-images.githubusercontent.com/799573/56777927-b7e59380-6788-11e9-86ef-621b4ce70c20.png">

**Comment by wjmelements** [comment] 2019-04-26 01:35
Unhelpful logs:
<img width="620" alt="Screen Shot 2019-04-25 at 6 34 38 PM" src="https://user-images.githubusercontent.com/799573/56777949-d186db00-6788-11e9-85e7-cb1dc8b0f942.png">

**Comment by wjmelements** [comment] 2019-04-26 01:36
Could be https://github.com/MetaMask/metamask-extension/issues/6514

**Comment by dragononcrypto** [comment] 2019-04-26 06:01
Ditto, 6.4 on chromium.

**Comment by shivansh9007** [comment] 2019-04-26 07:29
Same issue. I get an error on the pop up console saying 4byte.directory service unavailable(response 503).
This might be the cause I suppose.

**Comment by dannieb** [comment] 2019-04-26 08:09
I'm seeing the same issue, fresh install on 6.4, once I log in and try to perform a transaction it gets stuck in the spinning state.  Is there a fix coming out for this?

**Comment by PierreJeanjacquot** [comment] 2019-04-26 08:32
Same issue, working with MetaMask 6.3.2, KO with MetaMask 6.4
Small transactions may not be affected but transactions requiring a lot of gas take a while before prompting the user to sign.

**Comment by gicpeatc82** [comment] 2019-04-26 08:38
maby need fix transactions.util.js , can't await it.

`async function getMethodFrom4Byte (fourBytePrefix) {
  const fourByteResponse = (await fetch(https://www.4byte.directory/api/v1/signatures/?`

**Comment by DavidBelinchon** [comment] 2019-04-26 08:38
Same issue with MetaMask 6.4
Send ether between accounts it works but transactions with contracts take a while

**Comment by jinserk** [comment] 2019-04-26 10:33
Same issue with MetaMask 6.4 updated.

**Comment by imbenwolf** [comment] 2019-04-26 11:23
same issue

**Comment by bdresser** [comment] 2019-04-26 17:07
We're aware and working on a fix, will report back with ETA

**Comment by Chornuy91** [comment] 2019-04-26 20:15
4131219117651775

**Comment by bdresser** [comment] 2019-04-26 23:14
This is fixed in v6.4.1 - live on Firefox but unfortunately still `pending review` on Chrome. 

If you need this on Chrome in the meantime you can grab v6.4.1 from our [Releases page](https://github.com/MetaMask/metamask-extension/releases). Sorry for the trouble and thanks your for patience.

**Comment by bdresser** [comment] 2019-04-30 20:01
Chrome is up-to-date. Closing this via #6521

You can read a full post-mortem of the incident [here](https://medium.com/metamask/incident-postmortem-slow-confirmation-popups-23108bc954bc)

We're aware of function names showing up as `[undefined]` which will be fixed in #6524

**Closed by bdresser** 2019-04-30 20:01 UTC
