### ISSUE TITLE
[Bug]: Changing network from popup sends RPC requests to the previous selected network

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19801] opened 2023-06-28 11:05 UTC
### Describe the bug

**Problem**: changing networks from the popup view makes that the RPC requests continue to call the previous node chain.
i.e. I was on the zkEVM testnet from Polygon. Then I switched to Goerli from the popup. I can see how RPC requests are still sent to zkEVM node and all transactions I try to perform fail with the RPC error `"message":"invalid chain id"}}}'`

https://github.com/MetaMask/metamask-extension/assets/54408225/eda2aafc-cba3-4b3c-b500-ae6e404bea13

In the state logs I can see the network id for the zkEVM but the provider config from Goerli

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/e40f5f50-6232-4d17-affb-7b2c216c4fc8)

### Steps to reproduce
1. Add zkEVM Testnet
2. Select zkEVM testnet
3. Perform a couple of transactions
4. Change to Goerli network from the popup
5. Perform a transaction
6. See tx fails and RPC requests are still being sent to zkEVM node

### Version

current develop not repro on `10.33.0` branch

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Gudahtt** [comment] 2023-06-30 00:49
This seems most likely to be caused by an exception thrown in an event listener to the network controller (either the `stateChange` event or the `networkWillChange` event). That would result in the exact situation depicted. But there was no error in the console.... perhaps it was swallowed or sent to the UI. Difficult to know what might have thrown that error, so many different things listen for network controller state changes.

**Comment by Gudahtt** [comment] 2023-07-12 22:42
The symptom we're seeing here should be resolved by #19963. I'll close this for now, but we should keep an eye out in Sentry for subscriber errors so that we can find and resolve the underlying cause (if it's still around)

**Closed by Gudahtt** 2023-07-12 22:42 UTC
Labels: type-bug, release-blocker, team-shared-libraries, release-10.34.0
