### ISSUE TITLE
Metamask stuck in loading

### ISSUE THREAD

**Issue by naveenkumarmarri** [MetaMask/metamask-extension#4061] opened 2018-04-23 23:00 UTC
I followed the truffle tutorial http://truffleframework.com/tutorials/pet-shop for building a basic Dapp.
I was able to build and migrate the network but when I click on submit for authorizing the transaction. The notification window goes into forever loading status

![image](https://user-images.githubusercontent.com/2484004/39157374-9ac141ae-4728-11e8-83cd-eb2c08f987dc.png)

Is there anything wrong I'm doing here?

**Comment by seanbebliss** [comment] 2018-04-24 10:12
That happens to me just trying to send any token from one address to another.

**Comment by elie222** [comment] 2018-04-24 12:48
MetaMask is currently broken

**Comment by danfinlay** [comment] 2018-04-24 16:50
We are currently looking for why this happens for many people when using Truffle.

Closing as a duplicate of #3881.

**Closed by danfinlay** 2018-04-24 16:50 UTC
