### ISSUE TITLE
Edit Gas Price Not working

### ISSUE THREAD

**Issue by vatankhahbehrouz** [MetaMask/metamask-extension#10827] opened 2021-04-05 21:43 UTC
**the bug**
The edit gas price not working, when changing the level of gas or try to change the amount of gas, 
the save button is disabled.

![image](https://user-images.githubusercontent.com/81998981/113630742-5dbd0080-9636-11eb-9411-0a71ea0a8e28.png)

Chrome/ Mac and Windows

**Comment by danjm** [comment] 2021-04-08 14:12
@vatankhahbehrouz It looks like you don't have sufficient balance for the set amounts of gas and gas price. If you lower those to a point where the "Insufficient balance" message is not showing, then you should be able to save. If this is for a swap, there is a minimum value for the gas limit and you won't be able to set it below that. Also a word of caution: if you set the gas price too low, your transaction might take a very long time to be confirmed.

Closing for now, but if you find that you are unable to save even after editing gas to levels where you have sufficient balance, please open another issue.

**Closed by danjm** 2021-04-08 14:12 UTC
