### ISSUE TITLE
Private Network TXs forever pending

### ISSUE THREAD

**Issue by elie222** [MetaMask/metamask-extension#3480] opened 2018-03-08 18:27 UTC
I'm using Truffle and MetaMask and the transactions are forever pending. I see in Ganache that they've gone through and the blockchain state has been updated, but MetaMask and my client are not getting these updates and display old state.

In MetaMask the TX shows as forever pending.

**Comment by elie222** [comment] 2018-03-08 18:31
If I then retry do the tx with higher gas, it says failed because the account has a nonce of 1 and not 0. But the client still doesn't show the most up to date data when querying the blockchain although Ganache and `truffle develop` console do.

**Comment by elie222** [comment] 2018-03-11 11:57
So there are some real issues here. In the truffle console the tx has gone through. If I open Brave with MetaMask it shows the most up to date state. But my Chrome MetaMask seems to be stuck and is always showing the old state. I have the state logs for each browser's MetaMask, is there someone I can email it to?

**Comment by tmashuang** [comment] 2018-03-13 13:53
I believe this is a duplicate issue of the larger #199. Closing in favor #1999, will reopen if that is not the case.

**Closed by tmashuang** 2018-03-13 13:53 UTC

**Comment by zuuubu** [comment] 2019-04-25 12:05
I have part of this problem - I see that the transaction is confirmed in Metamask (I also get notification about it) but my transaction is never resolved in client javascript. When error occurs, it's caught, but otherwise it looks like its pending indefinitely.
Here is the code snippet:
`contract.deployed().then(function(instance){
    instance.createVoting(hexBallotName, hexOptions, {from:currentAccount})
    .then(function(result){
         console.log(result); // <- never happens
    }).catch(function (error){
        console.log(error); // <- this does happen when invoked
    });
});`
I use my private blockchain and truffle, I've tried this with Chrome, Firefox and Brave.
