### ISSUE TITLE
Metamask does not work!

### ISSUE THREAD

**Issue by barrcoder** [MetaMask/metamask-extension#6315] opened 2019-03-17 15:47 UTC
Almost a week I cant use my Metamask. It does not load information about my wallets. After I try to make a transaction it stop to work at all. When I download Metamask in another browser, there not displayed information about all wallets, so I can not access my assets. 
At the moment, after logging in, nothing is loading at all.

**Browser details (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - MetaMask Version [6.2.2]
![Thats how it looking after logging in](https://user-images.githubusercontent.com/35033135/54493788-a1703080-48dc-11e9-9c17-da495088249b.png)

**Comment by bdresser** [comment] 2019-03-18 18:09
@barrcoder please email support@metamask.io and we'll do our best to get your extension back in working order. As a reminder, you should always back up your seed phrase. 

Closing this issue as a duplicate of #4894

**Closed by bdresser** 2019-03-18 18:09 UTC
