### ISSUE TITLE
[Bug]: wallet_addEthereumChain, can't add chain with http rpcUrls

### ISSUE THREAD

**Issue by Cherasowy** [MetaMask/metamask-extension#14165] opened 2022-03-23 21:00 UTC
### Describe the bug

I am using the wallet_addEthereumChain call but it completely rejects the rpcUrls saying it has to be https, in EIP this method has no such condition.
This method is specified by [EIP-3085](https://eips.ethereum.org/EIPS/eip-3085)

### Steps to reproduce

1. 
        `window.ethereum.request({
          method: 'wallet_addEthereumChain',
          params: [
            {
              chainId: '12345678',
              chainName: 'Test',
              rpcUrls: ['http://localhost:9876'],
              nativeCurrency: {
                name: 'TestETH',
                symbol: 'tETH',
                decimals: 18,
              },
            },
          ],
        });`

### Version

10.11.3

### Browser

Chrome

### Operating system

Windows

**Comment by Cherasowy** [comment] 2022-03-23 21:01
Error: MetaMask - RPC Error: Expected an array with at least one valid string HTTPS url 'rpcUrls'

**Comment by rekmarks** [comment] 2022-03-24 06:55
Thank you for creating an issue, @Cherasowy! You are correct that the EIP doesn't require it, but we do. From the EIP (italics mine):

> Only the `chainId` is required per this specification, but a wallet **MAY** require any other fields listed, _impose additional requirements on them,_ or ignore them outright. If a field does not meet the requirements of this specification and the wallet does not ignore the field, the wallet **MUST** reject the request.

In other words, this is working as intended. If you need to add an `http` endpoint, you can do so via the "add custom network" form in network settings.

I will now close this issue.

**Closed by rekmarks** 2022-03-24 06:55 UTC
