### ISSUE TITLE
Chain ID changes to hexadecimal automatically 

### ISSUE THREAD

**Issue by afmfe-iul** [MetaMask/metamask-extension#9817] opened 2020-11-06 15:51 UTC
When adding custom networks if I input a chain ID with Base 10 format, after saving the field is updated to hexadecimal. This change is misleading for casual users that are not proficient on the matter, making them think they are not connected to the right network.

**Steps to reproduce**
1. Go to the Network list
2. Click on Custom RPC
3. Input the network details with a chain ID in base 10
4. Save and check that the chain ID updated to hexadecimal.

**Expected behavior**
 After saving custom network settings, keep the chain ID on the same number base that was inputted by the user.

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Chrome Version 86.0.4240.183 (Official Build) (64-bit)
 - MetaMask Version: v8.1.3

**Comment by afmfe-iul** [comment] 2020-11-06 18:25
A bit of a follow up on this issue, the behavior I described above happens only when adding new custom networks, when editing said networks, the behavior changes a bit:
1. Go to Settings > Networks and pick a custom one.
2. Edit the chain ID from hexa to the same value in decimal.
3. Save the new details.
4. Nothing happens (the "Save" button stays enabled and the chain ID stays in decimal), even tho the network request with the `eth_chainId` method succeeds.

**Comment by jacobcantele** [comment] 2020-11-07 22:34
@rekmarks can you confirm whether this is a bug?

**Comment by rekmarks** [comment] 2020-11-08 01:35
@jacobcantele, it's not a bug, but a bad UX decision that I made.

We already fixed it with #9780, which ensures that the chain ID will always be displayed in decimal. We also updated the form field tooltip to inform the user of this.

Thank you for reporting this @afmfe-iul. The fix will be included in version 8.1.4 of the MetaMask extension. Since there's no further action for us to take here, I will close this issue.

**Closed by rekmarks** 2020-11-08 01:35 UTC

**Comment by woodydeck** [comment] 2021-11-21 15:02
I'd just like to say this is a horrible decision to revert. Yes, it's easier to read, but consistency is more important. I'm dealing with this nonsense in 2021. It's not just this issue, it's the culture surrounding it.

The advantage of hexadecimal is security. You can't spoof a similar looking chain ID as easily. I'm not for or against either, but please to anyone who reads this in the future, if you make a bad decision in life, live with it. Don't make things worse trying to revert and cover up. You are the father of that baby. Pay up!

ERC1155 is plagued by devs not reading the token ID standard too. It works fine, but now we have branches of people not adhering to it, and I have to ban 20 crawlers a day from spamming requests on non-existent metadata.
