### ISSUE TITLE
Can't select gasPrice when deploying new contract

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#4635] opened 2018-06-21 20:00 UTC
Chrome Metamask version: 4.8.0

There are so many issues in this build:
1. Can't select gasPrice when deploying from https://remix.ethereum.org
2. I don't see current gasPrice
![image](https://user-images.githubusercontent.com/9360827/41742403-b0547042-7552-11e8-9a48-412300a06b18.png)
3. Back button is not clickable on the image above(Not CANCEL, **back** on the top) 
4. I constantly lose my custom RPC settings and I always have to set them again and again
5. I even lose my accounts, I can only recover them if I click + -> it will get it from the array of my seed phrase, but metamask state is glitching. 

My main issue is that I cannot modify gasPrice, I cannot see it , I cannot set it. (tried on ropsten, rinkeby, kovan)

**Comment by bdresser** [comment] 2018-06-21 20:19
thanks for reporting @rstormsf. 

(1 / 2) is a known issue, not new to 4.8.0 (#3519). Gas controls when deploying a contract are still available on the old UI, so I'd recommend you use that for deploys for the time being. 

<img width="357" alt="screen shot 2018-06-21 at 1 12 09 pm" src="https://user-images.githubusercontent.com/1016190/41743460-ac301f90-7555-11e8-8877-a64505e30591.png">

(3) thanks for catching, will file and perhaps can be addressed at the same time as (1 / 2)

(4) is also known, tracking in #4498 

We've had some issues with storage like you mention in (5). If you're able to provide reliable reproduction steps or can trace the cause of the error, check out the bug bounty described in #3314.

cc @danjm @alextsg

**Comment by bdresser** [comment] 2018-06-21 20:21
ah, sorry - looks slightly different from #3519 so will leave open

**Comment by vittominacori** [comment] 2018-07-03 18:04
Very useful to have. 
Any DApp user is forced to keep your suggested gas price and limit.
Also they can't view details on how much it is set. 
In these days, when gas price has gone to the moon, they are only burning ETH.

**Comment by bdresser** [comment] 2018-07-05 16:34
@vittominacori as mentioned above, you're able to edit the suggested gas price when deploying a contract on the old UI. If this is a blocker for you, I'd recommend you switch back.

We're working on refactoring our confirm screens, and this will be fixed in the new UI as soon as the refactor is ready!

**Closed** 2018-07-12 16:52 UTC
Labels: L03.1-newUI/UAT, P2-sooner
