### ISSUE TITLE
metamask js error on send button

### ISSUE THREAD

**Issue by Obie-Wan** [MetaMask/metamask-extension#4529] opened 2018-06-07 22:56 UTC
last Chrome on Windows 7
JS ERROR upon clicking NEXT button in send dialog:
Uncaught TypeError: Cannot read property 'negative' of null
    at i.cmp (ui.js:1)
    at i.gt (ui.js:1)
    at b.onSubmit (ui.js:1)
    at HTMLUnknownElement.r (ui.js:1)
    at HTMLUnknownElement.o (ui.js:1)
    at Object.o.invokeGuardedCallback (ui.js:1)
    at d (ui.js:1)
    at Object.executeDispatchesInOrder (ui.js:1)
    at p (ui.js:1)
    at h (ui.js:1)
    at Array.forEach (<anonymous>)
    at t.exports (ui.js:1)
    at Object.processEventQueue (ui.js:1)
    at ui.js:1
    at Object.handleTopLevel [as _handleTopLevel] (ui.js:1)
    at f (ui.js:1)
    at u.perform (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at dispatchEvent (ui.js:1)
    at HTMLDocument.o (ui.js:1)

**Comment by whymarrh** [comment] 2019-02-07 01:38
@Obie-Wan I'm going to close this for now since this very likely isn't an issue anymore. If you can provide reliable reproduction steps, please ping us and we can re-open the issue.

**Closed by whymarrh** 2019-02-07 01:38 UTC
Labels: N02-needsReproduction, T00-bug
