### ISSUE TITLE
[Bug]: ppom failing on RC v12.5  - Ethereum Mainnet

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#27951] opened 2024-10-18 09:03 UTC
### Describe the bug

PPOM failing on Ethereum Mainnet

### Expected behavior

PPOM alert should work as expected

### Screenshots/Recordings

https://github.com/user-attachments/assets/50cefb40-274d-4b5a-a426-e35901d9abf4

### Steps to reproduce

1. go to test Dapp
2. Switch to Ethereum Mainnet in MetaMask
3. Trigger any of the following:

```
Malicious ERC20 transfer (USDC)
Malicious ERC20 Approval (BUSD) 
Malicious Set Approval for All 
Malicious ERC 20 Approval with Odd Hex Data

```

4. See error `Error validating JSON RPC using PPOM:  Error: simulation: fallback: (code: -32000, message: , data: None)`

https://github.com/user-attachments/assets/fa49c57f-ab98-4ff2-bb1a-0068d57899fe

### Detection stage

During release testing

### Version

12.5.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by Unik0rnMaggie** [comment] 2024-10-18 13:41
On Linea network there is no console error, but the malicious transactions are not flagged:


```
Malicious ERC20 transfer (USDC) - not flagged;
Malicious ERC20 Approval (BUSD) - not flagged;
Malicious Set Approval for All - not flagged
Malicious ERC 20 Approval with Odd Hex Data - not flagged

```

https://github.com/user-attachments/assets/5bad5945-c904-4c8b-85bc-bca06b784ebe

**Comment by sleepytanya** [comment] 2024-10-18 14:38
@Unik0rnMaggie Linea may not be fully supported yet. I see the same behavior in prod and in RC 12.5.0:

```
Malicious ERC20 transfer (USDC) - not flagged;
Malicious ERC20 Approval (BUSD) - not flagged;
Malicious Set Approval for All - not flagged
Malicious ERC 20 Approval with Odd Hex Data - not flagged
Sign Permit -not flagged
```

@bschorchit

**Comment by sleepytanya** [comment] 2024-10-18 14:44
PPOM works for me in the latest build https://github.com/MetaMask/metamask-extension/pull/27411#issuecomment-2421046991


https://github.com/user-attachments/assets/4f3c1f37-d04b-4053-863b-273b73c8da14

**Comment by bschorchit** [comment] 2024-10-21 20:30
@Unik0rnMaggie closing for now as we have confirmed it's no longer an issue. Please do re-open if you encounter it again.

**Closed by bschorchit** 2024-10-21 20:30 UTC
Labels: type-bug, team-confirmations, regression-RC-12.5.0
