### ISSUE TITLE
Extension on Brave - does not confirm (greyed button) deposits into Compound/AAVE

### ISSUE THREAD

**Issue by ahadda5** [MetaMask/metamask-extension#10491] opened 2021-02-23 07:15 UTC
Cannot confirm BAT/ETH or any ERC token supply transaction to Compound or AAVE through Metamask 

1. Connect your metamask Mainnet to Compound [https://app.compound.finance/](Compound)
 or [https://app.aave.com/](AAVE) and , make sure you have sufficient  balance .  
2. I connect it to app.compound and DISABLED  the Brave browser ( its guard is down ) to ensure Brave is not interfering. 
3. I try to supply BAT, through initiating the deposit on compound or aave  however the confirm button is always greyed out.

I use compound and AAVe and did not try it with out Defi.  Also i tried to change the limit up and down . 

ALSO  i did follow the links to make Metamask my default  web3 app in the brave settings. 

**Expected behavior**
The button should be confirmed and the transaction go through. 

**Screenshots**
Attached
![bravemetamask](https://user-images.githubusercontent.com/21275079/108812193-21729b00-75c8-11eb-9f61-296d5d774486.jpg)

**Browser details (please complete the following information):**
 - OS: windows 10
 - Hardware Wallet: none
 - Browser: Brave Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit)
 - MetaMask Version: 9.0.5
 -
**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment] 2021-02-23 14:06
Thanks for the report! The most likely explanation is that you don't have sufficient ETH for the transaction. Did you check to ensure you had at least 0.005722 ETH to spend?

**Comment by ahadda5** [comment] 2021-02-23 14:18
haha.  Yes i only have BAT and no ETH.   I thought gas will be consumed from the token balance.   So i have to have ETH balance independently .Correct?

**Comment by Gudahtt** [comment] 2021-02-23 14:29
Yep, that's right! Unfortunately all Ethereum transactions require ETH to process.

This screen should _really_ be explaining this, but it's missing that error message now unfortunately. This is tracked in a separate issue: #9442

I'll close this for now because it appears to be working as intended, aside from the missing error message tracked in #9442.

**Closed by Gudahtt** 2021-02-23 14:29 UTC
Labels: N03-needsInformation, S2-normal, T00-bug
