### ISSUE TITLE
Ensure failing mv3 e2e test results in a failed build

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17901] opened 2023-02-24 16:03 UTC
We previously modified the exit code from these tests so that the build would not fail if they failed. Time to make these tests real.

- [ ] Include mv3 e2e tests in "All Tests Pass" circleci job (add to the `all-tests-pass` job in `.circleci/config.yml`
- [ ] Stop suppressing failure codes via https://github.com/MetaMask/metamask-extension/blob/develop/.circleci/config.yml#L742

Note that we should only do it once the mv3 e2e tests are passing (this will depend on fixing the currently failing tests as part of a separate ticket)

**Comment by DigitalsupportTeam** [comment] 2023-02-26 10:12
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by danjm** [comment] 2023-04-11 16:25
To start, lets ensure that existing "mv2 tests" run against the mv3 build. Mv3 tests can be disabled until we resolve blocking issues

**Comment by pedronfigueiredo** [comment] 2023-10-10 12:48
Closing as a duplicate of  #18442

**Closed** 2023-10-10 12:48 UTC
Labels: MV3, team-extension-client, team-extension-platform
