### ISSUE TITLE
Mainnet transactions hanging on PollingBlockTracker error

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#5764] opened 2018-11-15 18:23 UTC
**Describe the bug**
bug - metamask hangs on sending mainnet tx

**To Reproduce**
1. open up metamask
2. try to send a tx, any tx
3. hangs on loading screenforever

**Expected behavior**
A clear description of what you expected to happen.
sends tx, or tells me a workaround IFF theres some infura issue.

**Screenshots**

![screen recording 2018-11-15 at 11 22 am](https://user-images.githubusercontent.com/513929/48573236-d0dc4580-e8c8-11e8-9346-6882daef6d3e.gif)

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows] OSX
 - Browser [e.g. chrome, safari] Chrome
 - MetaMask Version [e.g. 5.0.2] 5.0.2

**Additional context**
New UI

**Comment by bdresser** [comment] 2018-11-15 18:43
@owocki thanks for reporting - is this consistent or intermittent? If you can reproduce, do you see anything in the consoles? 

I had one transaction hang this morning with a `bigNumber` error but haven't seen anything since. Tried with kudos and it took an unusually long time but eventually landed (and i sent my first kudo 😄)

**Comment by danfinlay** [comment] 2018-11-15 19:32
Is "having an infura issue" part of the reproduction? I'm not able to reproduce from the current steps.

**Comment by owocki** [comment] 2018-11-15 22:30
Edit: I was just able to send a tx from my other browser, Chrome Canary (also 5.0.2 on chrome OS X)..  Perhaps my wallet is borked from https://github.com/MetaMask/metamask-extension/issues/5739 ?  Should I try re-installing?

**Comment by owocki** [comment] 2018-11-16 02:35
restarting my browser helped

**Comment by bdresser** [comment] 2018-11-21 17:03
see also https://sentry.io/metamask/metamask/issues/771970804/

**Comment by bdresser** [comment] 2019-01-07 15:50
We think this was fixed by https://github.com/MetaMask/metamask-extension/pull/5902

@owocki thanks for the report, let me know if you see this behavior again

**Closed by bdresser** 2019-01-07 15:50 UTC
Labels: L24-blocktracker, N02-needsReproduction, T00-bug
