### ISSUE TITLE
Sometimes, the mouse click position does not represent the mouse position.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2767] opened 2017-12-18 19:43 UTC
Opening to connect some possibly related issues:
- #2724 
- #1383

Many reports were on Windows 10 with Chrome.

**Comment by danfinlay** [comment] 2017-12-18 19:44
Can anyone else confirm that:

- Everyone here is using Windows 10
- Everyone here is using Chrome
- Everyone here has two monitors set to two different resolutions.

**Comment by eeldivad** [comment] 2017-12-18 23:23
I confirm I'm using Win 10 with Chrome and the problem is when I move the browser to the secondary browser.  The main monitor works fine.

**Comment by danfinlay** [comment] 2017-12-18 23:40
Opened issue with chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=795949&can=2&q=action%20view%20resolution&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by danfinlay** [comment] 2018-01-04 00:16
Can someone here try this out again with the latest Chrome, version `63.0.3239.108` or later?

**Comment by eeldivad** [comment] 2018-01-04 03:23
I'm still having same issue and using the latest version 63.0.3239.108.  It works fine on main monitor but when I drag it over to second monitor the mouse pointer is off in metamask window.  I did more testing and realize its not an issue with resolution.  It's an issue with scaling.  In win10 in the display settings where you change the resolution, there is an option to change "Scale and Layout" for size of text, apps, and other items.  If it's set to 100% then everything works fine.  Mine was set to 125%, which gives an issue with metamask on secondary monitor.  I changed it between 100% and 125% and that fixes or produces the issue again.

**Comment by danfinlay** [comment] 2018-01-05 21:35
Specifically, they ask:

> Could you please check the issue on latest stable #63.0.3239.108 by creating a new profile without any apps and extensions and please let us know if the issue still persist or not.

Could you confirm @eeldivad or @tim if you can reproduce with these instructions?

**Comment by eeldivad** [comment] 2018-01-06 04:47
I created a new profile using latest stable version and installed metamask and I still get the same issue when scaling is set to 125%.  When I set scaling to 100% then issue is resolved.  I read that the chrome team can't reproduce the issue using different resolutions.  I recommend they try changing the scaling option to see the problem.

**Comment by eeldivad** [comment] 2018-01-06 17:44
Here's a screenshot of the scaling option so it's not mistaken for the browser scale option.  Notice it's set to 125% when I have issues with secondary monitor with metamask.

![1-6-2018 12-41-54 pm](https://user-images.githubusercontent.com/11731971/34642333-18402f94-f2df-11e7-9a32-5b411a602c95.png)

**Comment by tmashuang** [comment] 2018-01-11 04:13
The issue is the text size, MetaMask works best in 100% text size. This can offset the positioning of the mouse position and the buttons/clickable links. Will investigate how to be compatible with other text sizes.

**Comment by tmashuang** [comment] 2018-01-11 04:37
https://productforums.google.com/forum/#!topic/chrome/tyzywUJfkQI

Found a resolution is to
> Yes! Disabling chrome://flags/#enable-use-zoom-for-dsf "Use Blink's zoom for device scale factor" fixes the mouse offset issue for me on latest Chrome (63.0.3239.108).

**Comment by eeldivad** [comment] 2018-01-11 06:39
Thanks for the workaround.  I don't want to modify the default settings in chrome so I'll just remember to keep chrome on my main monitor till the issue is resolved.  Great find though.

**Comment by eeldivad** [comment] 2018-03-14 05:19
This appears to be fixed.  I'm not sure what fixed it but I'm now at chrome version 65.0.3325.162.  Did metamask update too?  I'm at metamask 4.2.0

**Comment by danfinlay** [comment] 2018-03-14 22:45
Chrome did say they fixed this, we didn't fix it on our end, but it's good to hear you see it fixed!

I'll close this for now, please comment if you experience it again!

**Comment by WebStra** [comment] 2019-01-11 17:07
I have the same problem on MacOs X El Capitan.
Chrome Version 71.0.3578.98.

**Comment by bdresser** [comment] 2019-01-11 19:09
@WebStra could you open a new issue with reproduction steps?

**Comment by sukiakiumo** [comment] 2019-03-11 17:36
I am getting this _all_ the time

OS El capitan 10.11.6
Chrome: 72.0.3626.121 

It is REALLY annoying. I have to close and open the window and it is fixed, but within an hour or so, it will revert. 

Interestingly, it is not consistent in all windows. Some windows are fine, other's are not. But within a given window, ALL tabs suffer from the same offset -issue. It is offset down by ~25pixels. 

I use chrome on 3-different monitors. 

This is a bug and should be fixed.

**Comment by bdresser** [comment] 2019-03-12 17:02
@sukiakiumo does this happen consistently across your monitors? do you experience the issue when not connected to any additional monitors? do you use non-standard zoom settings? does it happen on non-MetaMask windows? 

we haven't been able to reproduce this, so any more information you can provide would help.

**Comment by sukiakiumo** [comment] 2019-03-12 17:31
@bdresser 
Checking it out a little bit more, it seems like it is purely chrome issue and beyond metamask. In that sense, I guess it can be closed here and I'll see if I can figure to whom to refer this bug to. Thanks for asking useful questions!

**Closed** 2019-03-12 19:46 UTC
Labels: T00-bug, T13-blocked

**Comment by pdavisjones** [comment] 2019-03-21 16:02
Confirming that I have this bug also with Chrome Versions 72.0.3626.121 and 73.0.3683.86.
