### ISSUE TITLE
Nonces get confused with Avalanche chain

### ISSUE THREAD

**Issue by gpersoon** [MetaMask/metamask-extension#10539] opened 2021-03-01 15:50 UTC
**Describe the bug**
I have funds on the same EHT address in both the Ethereum mainnet and the Avalanche mainnet.
When doing transactions on Avalanche i notices they fail: the seem to have the wrong nonce.
They actually have the Ethereum mainnet nonce, which doesn't work for Avalanche.
It seems when switching between Ethereum mainnet and Avalanche not all info is correctly updated.

**Steps to reproduce**
1) Configure an RPC for Avalanche:
- RPC url=https://api.avax.network/ext/bc/C/rpc
- Chain ID=43114
- See: https://docs.avax.network/v/v1.0.4/build/tutorials/platform/deploy-a-smart-contract-on-avalanche-using-remix-and-metamask
2) Use an account that has done transactions on mainnet in metamask and notice the activity on Mainnet in Metamask
3) Switch to Avalanche and notice the activity => this is the same as on mainnet, which is unusual

4) Get some C-Avax from an exchange and transfer it to Avalance address
5) Do an Avalanche transaction and observe the Nonce
6) This nonce is an higher number and is the Nonce of the Ethereum mainnet

**Expected behavior**
Expect Avalanche to have its own Nonce

**Screenshots**
![image](https://user-images.githubusercontent.com/5469459/109517640-c4845280-7aa9-11eb-8af4-4f1f1647eff7.png)

**Browser details:**
 - OS: Windows 10
 - Browser: Version 88.0.4324.190 (Official Build) (64-bit) & Version 90.0.4430.8 (Official Build) canary (64-bit)
 - MetaMask Version: 9.0.5

**Additional context (Error Messages, etc.)**
A workaround is to reset the metamask account (every time when you switch between mainnet and avalanche),
which is also documented here:
https://support.avalabs.org/en/articles/4872721-metamask-transactions-are-stuck-rejected

**Comment by tmashuang** [comment] 2021-03-01 19:34
I believe this is fixed by https://github.com/MetaMask/metamask-extension/pull/10528. This also happens on ETC. I believe this issue is caused by grouping txs by net_version, which the PR fixes by grouping by chain id and falling back to net version. There is no migration unfortunately so the txs in history will need to be cleared via Resetting Account as mentioned as a workaround. The PR is included in v9.1.0, I'll comeback to this once it is released.

**Comment by jpop32** [comment] 2021-03-15 21:28
Hm, looks like this didn't make into 9.1.0, 9.1.1 nor 9.2.0. I see it is internally merged into `add-chain-id-to-txMeta` branch. Any idea on the ETA for the release of that functionality?

It will make our lives on the non-Ethereum, non-id-1 networks (like Avalanche) soooo much easier. A good portion of my day is spent telling people to reset their accounts... :-)

**Comment by brad-decker** [comment] 2021-03-15 22:03
@jpop32 this was included in v9.1.0, but didn't make it into the release notes because it's not a user-facing feature. We also couldn't retroactively apply this logic to existing transactions in-state, so as @tmashuang advised you'll have to clear history via Resetting Account.

**Comment by jpop32** [comment] 2021-03-15 22:12
Hm. Interesting. If it fixes the problem mentioned in this issue it definitely is something users should be aware of. Those that had the issue, at least. And this could be closed then.

I will check is the problem fixed.

**Comment by jpop32** [comment] 2021-03-15 22:21
Attempted send on Ethereum:
<img width="349" alt="Screenshot 2021-03-15 at 23 14 51" src="https://user-images.githubusercontent.com/6398640/111228548-b32c6180-85e4-11eb-8d81-e0da64aa97b7.png">
Imediately after, no account reset, just network switch and send on Avalanche:
<img width="347" alt="Screenshot 2021-03-15 at 23 15 23" src="https://user-images.githubusercontent.com/6398640/111228553-b45d8e80-85e4-11eb-8caf-1d1249e3d4d6.png">
Notice the different nonce numbers. Oh my!

Stick a fork in it, it's done!

**Comment by brad-decker** [comment] 2021-03-15 22:30
Thanks for checking @jpop32! Going to close this and the related issue. Appreciate it.

**Closed by brad-decker** 2021-03-15 22:30 UTC
Labels: N02-needsReproduction, S2-normal, T00-bug, needs-triage, x02-customNetworks
