### ISSUE TITLE
ERC20 integration looks confusing for ERC721 tokens

### ISSUE THREAD

**Issue by wmsouza** [MetaMask/metamask-extension#7014] opened 2019-08-15 04:35 UTC
**Describe the bug**
Example: If I try to transfer an ERC721 token with the ABC code and with an id of #20000, on the transfer screen it will show 20000 ABC, which is not intuitive and makes me think I am transferring 20,000 units of something, instead of a single ERC721 token.

**To Reproduce**
1. Go to Opensea or other exchange
2. Click to gift an item
3. The screen will show 12345 ABC

**Expected behavior**
While that behavior is good for ERC20 tokens, it is not for ERC721 as it gives the false impression that the user is transferring several units of the token instead of just one.

**Screenshots**
![image](https://user-images.githubusercontent.com/4406463/63072972-76722300-bef4-11e9-91c1-f0f86943b87b.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - MetaMask Version 7.0.1

**Additional details**
I don't recall this being the behavior before, so I am assuming this is due to a new change.
This is similar to https://github.com/MetaMask/metamask-extension/issues/5145

**Comment by bdresser** [comment] 2019-08-19 16:32
Closing this as a dupe of https://github.com/MetaMask/metamask-extension/issues/5230 and https://github.com/MetaMask/metamask-extension/issues/5145. Please feel free to add design feedback on either of those issues if you have any. We support sending 721s in our mobile app, if you haven't tried out the public beta yet: https://twitter.com/metamask_io/status/1156193940145692672

If you feel there is a substantive difference from what you're requesting here and those two issues, let me know

**Closed by bdresser** 2019-08-19 16:32 UTC
