### ISSUE TITLE
Broadcast Network

### ISSUE THREAD

**Issue by damiandennis** [MetaMask/metamask-extension#10533] opened 2021-02-27 21:32 UTC
This has probably been suggested before but I could not find a ticket suggesting it. It would be good if the website you are on could have the ability to broadcast the network the site uses and metamask would set the selected network automatically and possibly add it automatically as well if it does not exist, not sure the security implications for doing this however but makes sense with some of the layer 2+ solutions, like Matic, testing sites and even BSC. Mainly I am thinking about the user experience, to have to know the network you are required on makes it more difficult for the average user.

**Comment by Gudahtt** [comment] 2021-03-01 15:53
Thanks for the suggestion! This looks like a duplicate of #5101, which was recently implemented and will be included in our next release.

I'll close this issue for now, but please let me know if it seems like that feature doesn't meet your needs.

**Closed by Gudahtt** 2021-03-01 15:53 UTC
