### ISSUE TITLE
[Bug]: Metamask causing issues with loading Google Docs and error "Unable to load file"

### ISSUE THREAD

**Issue by MButcho** [MetaMask/metamask-extension#15478] opened 2022-08-05 09:21 UTC
### Describe the bug

After latest update of MM, Google Docs started to show following error: 
![image](https://user-images.githubusercontent.com/41790777/183045744-3c31d542-f166-4e9a-b2c6-7317e7960a26.png)

After disabling MM extension, the error disappeared

### Steps to reproduce

1. Enable MM extension
2. Open Google Doc with enabled MM for that site (option On all sites or On click and click MM icon)
3. "Unable to load file" appear

### Version

10.18.0

### Browser

Brave

### Operating system

Windows

### Hardware wallet

Ledger

**Comment by bschorchit** [comment] 2022-08-05 16:39
Duplicate of https://github.com/MetaMask/metamask-extension/issues/15374
And related to https://github.com/MetaMask/metamask-extension/issues/15460

**Closed by bschorchit** 2022-08-05 16:39 UTC
Labels: type-bug
