### ISSUE TITLE
[Bug]: RPC Error when switching network on 10.28.1

### ISSUE THREAD

**Issue by fmoyaj** [MetaMask/metamask-extension#18453] opened 2023-04-05 02:09 UTC
### Describe the bug

I just updated to 10.28.1 and I get an error when trying to switch networks from various dapps, including app.aave.com. I am able to add the network, but if I have previously added the network and just try to switch to the network from the dapp the console shows the following message: `RPC Error: networkConfigurationId [object Object] does not match a configured networkConfiguration `

### Steps to reproduce

1. Install 10.28.1
2. Go to app.aave.com testnet
3. Go to a modal for a network that you aren't connected to (e.g. Fantom) and click on switch network. Add network by clicking "switch network".
4. Switch back to another network (e.g. Ethereum mainnet) and repeat step 3. This time, aave will show a cannot switch network error, and you will see aforementioned error in the developer console.

### Error messages or log output

```shell
RPC Error: networkConfigurationId [object Object] does not match a configured networkConfiguration
```

### Version

10.28.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by henryli17** [comment] 2023-04-05 13:06
Having the same issue when trying to switch to the Localhost 8545 network.

**Comment by duxiaofeng-github** [comment] 2023-04-06 01:57
same here

**Comment by cryptosunshine** [comment] 2023-04-06 02:15
I had the same problem, this looks unprofessional, please fix the bug.

**Comment by waynechan-bw** [comment] 2023-04-06 07:48
same here :(

**Comment by pakwin9133** [comment] 2023-04-06 07:49
same here

**Comment by elvis824** [comment] 2023-04-06 07:50
same here 😡

**Comment by MesProtocol** [comment] 2023-04-06 07:55
same here, version 10.27.0 was working fine

**Comment by hhh111** [comment] 2023-04-06 09:23
same here

**Comment by chendatony31** [comment] 2023-04-06 09:30
Debugger our dapp for a long time and it turns out the bug of metamask. ToT

**Comment by Piliponful** [comment] 2023-04-06 12:37
Great update guys, thank you so much

**Comment by Piliponful** [comment] 2023-04-06 12:38
Love using web3 ecosystem

**Comment by yulafezmesi** [comment] 2023-04-06 12:50
same here

**Comment by danjm** [comment] 2023-04-06 15:12
thanks everyone

we have merged a fix for this and will include it in a patch release in the coming days

**Comment by MananTank** [comment] 2023-04-06 19:14
@danjm Would really appreciate it if this gets released as soon as possible

**Comment by LittleCabbage524** [comment] 2023-04-07 11:11
same here, but not everyone meets, i am confused about it

**Comment by simonmahns** [comment] 2023-04-07 16:40
wen

**Comment by mhm233** [comment] 2023-04-07 20:59
Update dropped today and still no fix! the bug made it pretty much unusable if you have many chains added.

**Comment by sjunaiduk** [comment] 2023-04-08 01:04
I am also facing this issue, this started happening in the update on April 7th, for MetaMask extension on chrome v10.28.2.

**Comment by danjm** [comment] 2023-04-08 03:52
@mhm233 @sjunaiduk Can you give us more information about how you are experiencing this bug? Perhaps you could share some dapps you are using where this is happening? Or maybe you could open the chrome developer console and share any errors that you see?

**Comment by sjunaiduk** [comment] 2023-04-08 04:52
> @mhm233 @sjunaiduk Can you give us more information about how you are experiencing this bug? Perhaps you could share some dapps you are using where this is happening? Or maybe you could open the chrome developer console and share any errors that you see?

Hey,  I'm testing on a dapp on my local host,  it isn't a public one but I imagine this would occur with any dapp when your wallet has been connected and you try to switch to a network other than Ethereum. 

The error I see is what other users are sharing in this thread,  when I get on my computer tomorrow I'll find a public dapp where you can reproduce the issue

**Comment by danjm** [comment] 2023-04-08 05:49
Thanks.

Well I understand the problem now and am working on a fix.

This bug will be experienced by anyone who added a network while on v10.27.0 or earlier, and are now on v10.28.1 or v10.28.2 and trying to confirm a dapp prompted switch to that network. This bug will not affect users who first added the network, via a dapp wallet_addEthereumChain request, while on v10.28.1 . This bug also won't affect users who added the network via the MetaMask UI in v10.28.1

The simplest work around is to open MetaMask and use the network switcher. But you will have to do that every time a dapp prompts you to switch to that network.

If you want to permanently fix the issue for a given network, you can open MetaMask, then open "Settings", then select the "Network" tab of settings and edit any field in any way. Save the change in the network form. Switching to this network from dapp (or deleting it) will succeed. I have demo's this workaround in the attached video, which first shows the failure to switch and then shows the successful network switch after editing the rpc url in the network form by adding a trailing /


https://user-images.githubusercontent.com/7499938/230705658-3a517a39-88bf-4ccc-b85d-95d05d29d10e.mp4

**Comment by scotthconner** [comment] 2023-04-08 13:58
Thanks! The workaround worked. I thought it was something I had done in my code, but realized released dApps also had the problem, but not on mobile.

I also checked Microsoft Edge and that worked too - so I went to sleep knowing it was MetaMask on Chrome.

I've now unblocked myself with the workaround. Thanks - I was almost about to do web development in a Microsoft Browser for the first time in 15 years!

**Comment by rafael-csouza** [comment] 2023-04-09 20:11
same bug here, I change to wallet_addEthereumChain to fix for now :/

**Comment by artall64** [comment] 2023-04-10 00:27
Even though a fix has been released, it appears that it does not fully resolve the issue for many existing dApp users. 
Users of popular projects such as 1inch and Uniswap are receiving alerts suggesting that they need to manually change network now. 

Perhaps there is still room for a proper fix that would address the issue for all existing users (users who added network into MetaMask before 10.27.0) ?

**Comment by Johnmub** [comment] 2023-04-10 01:34
It happens the same to me. I thought it was a problem with my code, previously it worked and today when I ran my application again I found this problem.

Thanks for the information.

> Thanks.
> 
> Well I understand the problem now and am working on a fix.
> 
> This bug will be experienced by anyone who added a network while on v10.27.0 or earlier, and are now on v10.28.1 or v10.28.2 and trying to confirm a dapp prompted switch to that network. This bug will not affect users who first added the network, via a dapp wallet_addEthereumChain request, while on v10.28.1 . This bug also won't affect users who added the network via the MetaMask UI in v10.28.1
> 
> The simplest work around is to open MetaMask and use the network switcher. But you will have to do that every time a dapp prompts you to switch to that network.
> 
> If you want to permanently fix the issue for a given network, you can open MetaMask, then open "Settings", then select the "Network" tab of settings and edit any field in any way. Save the change in the network form. Switching to this network from dapp (or deleting it) will succeed. I have demo's this workaround in the attached video, which first shows the failure to switch and then shows the successful network switch after editing the rpc url in the network form by adding a trailing /

**Comment by UYScutiNet** [comment] 2023-04-10 02:41
> Thanks.
> 
> Well I understand the problem now and am working on a fix.
> 
> This bug will be experienced by anyone who added a network while on v10.27.0 or earlier, and are now on v10.28.1 or v10.28.2 and trying to confirm a dapp prompted switch to that network. This bug will not affect users who first added the network, via a dapp wallet_addEthereumChain request, while on v10.28.1 . This bug also won't affect users who added the network via the MetaMask UI in v10.28.1
> 
> The simplest work around is to open MetaMask and use the network switcher. But you will have to do that every time a dapp prompts you to switch to that network.
> 
> If you want to permanently fix the issue for a given network, you can open MetaMask, then open "Settings", then select the "Network" tab of settings and edit any field in any way. Save the change in the network form. Switching to this network from dapp (or deleting it) will succeed. I have demo's this workaround in the attached video, which first shows the failure to switch and then shows the successful network switch after editing the rpc url in the network form by adding a trailing /

Thanks for your information, This solved the problem.

**Comment by LittleCabbage524** [comment] 2023-04-10 03:02
i think the  issue does not has been resloved. The latest release still does not support automatic network switching.

**Comment by iseekTo** [comment] 2023-04-10 03:28
> i think the issue does not has been resloved. The latest release still does not support automatic network switching.

same as you

**Comment by captain-woof** [comment] 2023-04-10 06:59
What an unprofessional update!
How does an existing core feature even break?

**Comment by danjm** [comment] 2023-04-10 22:51
Thanks everyone for your input on this. We are going to try to have a fix published this week, hopefully within a day or two (but exact timelines can't be guaranteed).

See my previous comment for some notes on workarounds from a users perspective.

For dapp developers trying to avoid their users having to follow a workaround, you may find this approach mentioned on another thread helpful https://github.com/MetaMask/metamask-extension/issues/18509#issuecomment-1501607666

**Comment by devsalman247** [comment] 2023-04-11 11:22
Same here :(((

**Comment by D1scoDancer** [comment] 2023-04-11 13:04
![image](https://user-images.githubusercontent.com/60194526/231171103-341c5403-603a-4e3d-9831-0842592352f7.png)

**Closed** 2023-04-11 19:16 UTC
Labels: type-bug, team-extension-client, team-extension-platform

**Comment by mayassalman** [comment] 2023-04-12 10:39
> For dapp developers trying to avoid their users having to follow a workaround, you may find this approach mentioned on another thread helpful [#18509 (**comment**)](https://github.com/MetaMask/metamask-extension/issues/18509#issuecomment-1501607666)

**`It didn't work for me, waiting for the bug to be fixed, thanks.`**

**Comment by leye195** [comment] 2023-04-13 12:52
Still have problem... 

![image](https://user-images.githubusercontent.com/30601503/231764053-f98aa14a-1167-43c5-bf60-26b621dee242.png)

**Comment by ian** [comment] 2023-04-13 14:20
Verified working on our end. Thanks for the quick fix!

**Comment by iliyacrypto** [comment] 2023-06-03 21:01
![Capture](https://github.com/MetaMask/metamask-extension/assets/103365775/b22638f9-f667-4050-9c0a-ff8e0ffc8943)
  I even can not enter  my metamask  it shows this error and I can not open the app anymore

**Comment by iliyacrypto** [comment] 2023-06-03 21:04
![Capture](https://github.com/MetaMask/metamask-extension/assets/103365775/b22638f9-f667-4050-9c0a-ff8e0ffc8943)
  I even can not enter  my metamask  it shows this error and I can not open the app anymore

**Comment by Hamiand** [comment] 2023-06-08 03:02
Hi, I can't switch back to any network anymore. Can anyone help please?
![metamask issue](https://github.com/MetaMask/metamask-extension/assets/10685915/92f3451e-2b36-4a8d-afd3-96133b5bbb1d)

**Comment by talhamalik883** [comment] 2023-06-10 21:12
running it same issue, my metamask is stuck. Not able to switch chain.
<img width="341" alt="Screenshot 2023-06-11 at 2 12 07 AM" src="https://github.com/MetaMask/metamask-extension/assets/12577610/29f1ad31-462f-40d9-bc66-40bf1717716f">

**Comment by call3hudson** [comment] 2023-07-14 02:22
issue stands still
