### ISSUE TITLE
Unable to paste public address in recipient address field 

### ISSUE THREAD

**Issue by JSON-LEE13** [MetaMask/metamask-extension#5164] opened 2018-08-29 21:56 UTC
Users experience a issue pasting a public address in the address field. They will have to type a few characters in the field and the delete them in order to paste the address.

![image](https://user-images.githubusercontent.com/38339632/44817782-79c1b100-abb4-11e8-9061-2f5e66058092.png)

**Comment by bdresser** [comment] 2018-09-06 17:38
closing as dupe of https://github.com/MetaMask/metamask-extension/issues/5198

**Closed by bdresser** 2018-09-06 17:38 UTC
