### ISSUE TITLE
[Bug]: Linux version has been super buggy for years.  When fix???

### ISSUE THREAD

**Issue by sgehrman** [MetaMask/metamask-extension#15208] opened 2022-07-13 07:10 UTC
### Describe the bug

Barely works on linux

### Steps to reproduce

1.
install linux
install metamask

### Error messages or log output

```shell
"duh, i'm buggy"
```

### Version

latest

### Browser

Chrome

### Operating system

Linux

### Additional context

duh

**Comment by danjm** [comment] 2022-07-13 15:56
@sgehrman What buggy behavior, in particular, are you seeing?

**Comment by Lissanro** [comment] 2022-07-15 14:43
I am on Linux (Ubuntu Studio 22.04) and I did not notice yet any bugs specific to Linux. I use latest version of MetaMask I built from the source code. Without description of what is actually the problem, nobody can help.

**Comment by sgehrman** [comment] 2022-10-18 11:46
the popout window size is bad.  scroll bars within scrollbars is weird.

using chrome. nothing special about my setup.

![gnome-shell-screenshot-JKIXT1](https://user-images.githubusercontent.com/287137/196420935-247cedb8-037e-4e96-a205-19475a6b67e2.png)

**Comment by Gudahtt** [comment] 2022-10-26 18:23
I have been unable to reproduce this as well; I've been using MetaMask on Linux for years and have never seen the depicted problem.

Please feel free to leave more details about the Chrome version, desktop envioronment, linux version, etc. and we can attempt to reproduce it again, but until then I will close this as cannot reproduce.

**Closed by Gudahtt** 2022-10-26 18:23 UTC
Labels: type-bug, needs-information

**Comment by sgehrman** [comment] 2022-10-27 10:48
latest chrome, debian latest.

It's never worked on any of my linux machines.

**Comment by Lissanro** [comment] 2022-10-27 12:29
For me MetaMask works perfectly on all my Linux computers (I tested in Firefox, Chrome, Brave), even on Jetson Nano (Chromium, ARM64 architecture).
