### ISSUE TITLE
Add "custom block explorer" setting for Ethereum Main Network and all other preset networks

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#7647] opened 2019-12-04 19:53 UTC
**What problem are you trying to solve?**
There is no choice for block explorer currently.  Users have to use etherscan within MM.  They can use other explorers but have to manually copy/paste.

**Describe the solution you'd like**
Add a custom setting, either blank field or a list of other existing block explorers.

I would like if we could select an "edit" button next to each network in the network dropdown list.  It then allows users to change some of the fields like RPC URL and Block Explorer URL:
![image](https://user-images.githubusercontent.com/16330048/70175912-300c2400-169d-11ea-9dde-7ebaaa6bda3f.png)

![image](https://user-images.githubusercontent.com/16330048/70175988-4b772f00-169d-11ea-8241-f8978b278037.png)

**Comment by rdymac** [comment] 2020-02-08 11:33
I the version 7.7.2, the Networks tab in Settings lets you set a custom block explorer for each network, including the Main Ethereum Network.

@whymarrh this issue can be close.

**Comment by dpazdan** [comment] 2020-02-09 01:31
You cannot edit any fields for pre-set networks provided in MetaMask.  The option to do so is greyed out. 
![image](https://user-images.githubusercontent.com/16330048/74094576-3d80c880-4aa9-11ea-9b83-da2f54261d3a.png)

I guess you can add an additional Mainnet to the list, that might work.

**Comment by Gudahtt** [comment] 2021-03-01 15:58
I'm going to close this in favour of #10478, which is a duplicate of this issue. Typically we'd close the newer issue in the case of duplicates, but in this case I think the newer ticket describes the problem more clearly without suggesting solutions, and there was a comment from a community member that would be nice to preserve.

**Closed by Gudahtt** 2021-03-01 15:58 UTC
Labels: T01-enhancement
