### ISSUE TITLE
Display version of Metamask while logged out

### ISSUE THREAD

**Issue by 1blockologist** [MetaMask/metamask-extension#5601] opened 2018-10-25 09:41 UTC
**What problem are you trying to solve?**
When Metamask is not signed in, there is no way within the GUI to get the current version. User can alternatively go to their extension manager to see, but when logged in it is easy to get this within the interface.

**Describe the solution you'd like**
The logged out view should just mention it, or clicking the Metamask icon within the GUI should show an about view.

**Additional context**
When testing on multiple browsers, it isn't clear which Metamask version has been pushed to that environment already. And the users/idents may be radically different, leaving the current user to not know what the password for that Metamask instance is.

![image](https://user-images.githubusercontent.com/21366360/47491281-6707d900-d7ff-11e8-8f67-eeaa943ad68f.png)

**Comment by bdresser** [comment] 2018-10-25 15:00
thanks @1blockologist, totally agree. 

closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/5589

**Closed by bdresser** 2018-10-25 15:00 UTC
