### ISSUE TITLE
Transaction receipt callback is not called on Metamask 4.12

### ISSUE THREAD

**Issue by AleG94** [MetaMask/metamask-extension#5425] opened 2018-10-04 13:33 UTC
With MetaMask 4.12, the receipt is not returned in both callback and promise versions.

`contract.methods.method().send({ from: address }).then(receipt => console.log(receipt))`

`contract.methods.method().send({ from: address }).on('receipt', function(receipt) {
   console.log(receipt);
})`

Both these examples are not working in Metamask 4.12 but working fine in 4.9

**Comment by obernardovieira** [comment] 2018-10-04 15:38
Important to note that the _truffle_ community and the _web3.js_ community has been reporting this kind of errors recently.

**Comment by danfinlay** [comment] 2018-10-04 17:58
Could you share what JS library you are using to get these results?

Please note web3 1.0 is in beta, and not yet supported by MetaMask.
Like it, Drizzle (from the Truffle team) depends on websockets/subscriptions, which MetaMask does not yet support.

If you want to use these event-based APIs, you will need to connect to your own websocket-hosting ethereum server, as it is not provided by MetaMask at this time. You can still read from a different server, and propose transactions to the MetaMask API if you want to work around this limitation for now.

Leaving open in case this isn't a websocket issue, but it really looks like one to me. I have not had any issues getting tx receipts with the latest MetaMask builds.

**Comment by obernardovieira** [comment] 2018-10-04 18:16
@danfinlay can be a websocket issue. I've read something related too, but those who got problems with metamask 4.12, after downgraded to 4.11.1 and had no issues. Sorry, can't be more specific than that, since I'm not using 4.12 currently and I have no issues.

**Comment by AleG94** [comment] 2018-10-04 18:48
@danfinlay I am using web3 1.0beta36 and this is the error I'm getting only the first time.

`MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: "Internal JSON-RPC error."}`
`ERROR Error: Uncaught (in promise): Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.`

But everything has been working flawlessy for the last month and it's still working fine on metamask 4.9 and 4.11 so it should be something you can address. This will break the workflow for many dapps.

**Comment by danfinlay** [comment] 2018-10-04 23:14
This would be a very serious issue, but I'm unable to reproduce. A sample call that any MetaMask user can enter in their console while connected to the main network:

```
web3.eth.getTransactionReceipt('0xec7bf72ecac93325adad8bfb08f22108a6f4fd270a8275a207fb0c18ec082dbd', console.log)
```

Returns the correct value for me.

Can you provide reproduction steps or a reproduction app? Until we can reproduce the error, we cannot be sure that a given action will fix the issue.

**Comment by danfinlay** [comment] 2018-10-05 00:10
Alright, we’ve published a rollback to 4.11.1, called 4.13.0. We would still really appreciate reproduction steps.

**Comment by AleG94** [comment] 2018-10-05 08:52
@danfinlay Thank you so much for your help. Here is a code snippet to reproduce the issue. Be sure to connect to use `web3 1.0.0beta.36` and to connect to `Ropsten` testnet.

```
this.web3 = new Web3(window.web3.currentProvider);
this.web3.eth.getAccounts().then(accounts => {

   let abi = [{"constant":true,"inputs":[],"name":"rate","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"weiRaised","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"closingTime","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"openingTime","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"token","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_rate","type":"uint256"},{"name":"_openingTime","type":"uint256"},{"name":"_closingTime","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"purchaser","type":"address"},{"indexed":true,"name":"beneficiary","type":"address"},{"indexed":false,"name":"value","type":"uint256"},{"indexed":false,"name":"amount","type":"uint256"}],"name":"TokenPurchase","type":"event"},{"constant":false,"inputs":[{"name":"_beneficiary","type":"address"}],"name":"buyTokens","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"_token","type":"address"}],"name":"setToken","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"hasClosed","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"remainingSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_amount","type":"uint256"}],"name":"burnTokens","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"withdrawFunds","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}];

   let contract = new this.web3.eth.Contract(abi,'0x96c60DDa637487820AF1858b94b5c732F0beFfD3');
   contract.methods.buyTokens(accounts[0]).send({ from: accounts[0], value: this.web3.utils.toWei('0.00005', 'ether')})
   .then(receipt => console.log(receipt));

});
```

This will not print the receipt on console with MetaMask 4.12 while I can confirm it is working fine again on 4.13. I hope this can help you to track down the issue.

**Comment by danfinlay** [comment] 2018-10-05 17:03
We do not currently support web3 1.0 beta since it depends on the subscriptions API. If you want promises and a similar interface, I recommend either [ethjs](https://www.npmjs.com/package/ethjs), [truffle-contract](https://github.com/trufflesuite/truffle-contract), or maybe [ethers.js](https://www.npmjs.com/package/ethers).

I cannot promise that our next release will support web3 1.0 beta, it's surprising that it worked even momentarily.

Closing as a duplicate of #3642.

**Comment by danfinlay** [comment] 2018-10-05 18:43
I [confirmed](https://github.com/danfinlay/issue-5425-repro) this is because we don't support the subscriptions API, and [apparently](https://github.com/MetaMask/provider-engine/blob/master/zero.js#L45) we did have a rudimentary version of subscription support previously. We need to port that subprovider to `json-rpc-engine`.

**Comment by AleG94** [comment] 2018-10-05 18:59
Are you going to port that in the next release or at a later time? So I know if I should migrate to another library or stick with web3 1.0. 
I'm seeing many new dapps using web3 1.0 and I believe this change would break their workflow. 
Thank you for your patience.

**Comment by AleG94** [comment] 2018-10-08 09:31
Metamask 4.14 is not working for me in any browser. It doesn't even recognize my account and the error is:
`TypeError: t.setEngine is not a function`.

**Comment by danfinlay** [comment] 2018-10-08 16:47
Thanks for trying, sorry there was an issue. Looking into what could cause that now.

**Comment by tmashuang** [comment] 2018-10-08 21:36
We have been working implementing the web3 1.0 subscription method once again.  Let us know if this build is breaking your dapps.
https://github.com/MetaMask/metamask-extension/pull/5458#issuecomment-427979200

**Comment by AleG94** [comment] 2018-10-08 22:13
Thank you for your efforts to fix this. I am really sorry to report that the new build isn't working. For every transaction, Metamask says `ALERT: Transaction Error. Exception thrown in contract code.`. I have tried with multiple contract functions and nothing. Downgraded to 4.11 and everything is working properly again. Even the old 4.12 didn't have this issue.

Another thing that gets printed in console is `MaxListenersExceededWarning: "Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit"`.

**Comment by tmashuang** [comment] 2018-10-08 23:33
Seemed to work just fine for me. Hmm.
https://ropsten.etherscan.io/tx/0xe373bd2b29ce93f65488dcfc81db1b8e07cfaf52c741689707eeccaa5c0f0aa3

**Comment by danfinlay** [comment] 2018-10-09 03:33
@AlecG94 thanks so much for your help reproducing this issue. Would you mind sending us your state logs after getting that error, so we could inspect how the transaction was composed? You can send it privately to support@metamask.io

https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-New-UI-

**Comment by AleG94** [comment] 2018-10-09 09:21
I just sent the state logs. I can confirm that, despite the error, the transaction is being mined succesfully so it's probably just a display error. The receipt callback is also working fine now. The `MaxListenersExceededWarning` for `data` listeners is still there though.

**Comment by DaneWiid1** [comment] 2018-10-09 16:06
@danfinlay when you say you have no short term plans to support Web3 1.0 is this specifically the promi events and event watchers ? Will Web3 1.0 still work using callbacks for tx/call results or do you suggest a rollback to 0.20.x ?

**Comment by tmashuang** [comment] 2018-10-09 16:45
For me, it is coming from here, 
https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/tx-gas-utils.js#L30-L37

The catch results in `TypeError: l.slice is not a function`

**Comment by danfinlay** [comment] 2018-10-09 22:37
Thanks for your patience. We have a new build that we hope has fixed this issue here: https://github.com/MetaMask/metamask-extension/pull/5475#issuecomment-428371017

**Comment by AleG94** [comment] 2018-10-10 09:31
The new build is working for me but the `MaxListenersExceededWarning: "Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit"` is still there. It wasn't an issue on 4.11. Thank you.

**Comment by danfinlay** [comment] 2018-10-10 14:16
That's great to hear!

The warning should be very easy to fix: Is that warning in the page console, or which console do you see that in?

**Comment by AleG94** [comment] 2018-10-10 20:44
The warning is shown in the browser console after I unlock my Metamask account. It's been present since the initial 4.12 (the one with the receipt bug) and it's still here in the lastest build. It's not present in 4.11 and 4.9.

**Comment by allegramarie** [comment] 2018-11-12 20:54
Hi, wanted to confirm I'm having the same issue as above with async/await - transaction success is confirmed in 4.13, but not 4.14. Similar to the above, the transaction goes through in MetaMask and is mined, but I never get a confirmation. I'm actually not getting any kind of error, just an extended wait. Also on web3 1.0.0beta.36.

const result = await token.methods.transferFrom(user, owner, amount, 0).send({ from: user, gas: gas, chainId })

Do I need to refactor to callbacks to move forward?

**Comment by bdresser** [comment] 2018-11-12 21:05
@allegramarie try v5.0.2 and let us know if you still have trouble

**Comment by allegramarie** [comment] 2018-11-12 21:11
Thanks! I'm on v5.0.2, no change.

**Comment by tmashuang** [comment] 2018-11-12 23:18
@allegramarie Could I have the whole snippet? My steps to reproduce came up with no issues returning the tx details. This is my simpler repro snippet that can be ran in your project's console, the contract is on Ropsten.

```
web3.eth.getAccounts().then(async accounts => {
  var abi = [{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
  var contract = new web3.eth.Contract(abi, '0xC87f3D029dD512B8042F7c2eeb0ffFD4db4EdFC4')
  try {
    const result = await contract.methods.set(2).send({ from: accounts[0]})
    console.log(result)
  } catch (error) {
    console.log(error)
  }
})
```

**Comment by allegramarie** [comment] 2018-11-13 15:20
Here's the whole snippet. I ran your repro on Ropsten and didn't have any issues getting a response in the console, but I'm on a private network with this contract. 

`const buyAsset = async (amount, assetToken) => {
	try {
		const chainId = await web3.eth.net.getId();
		let user = await getUserAccount();
		user = user.toString();
		const token = Token(assetToken);
		let owner = await token.methods.owner().call();
		owner = owner.toString();
		try {
			const result = await token.methods.transferFrom(owner, user, amount, 5).send({ from: user, gas: gas, chainId });
			return result;
		}
		catch (err) {
			console.log('error!')
		}
	}
	catch (err) {
		console.log('error buying an asset', err)
	}
}`

**Comment by AleG94** [comment] 2019-04-05 10:14
Hey guys, I wanted to report this is happening again. 

I can't tell you exaclty when it started but I'm on `6.3.1` and I'm not able to get any receipt.

`contract.methods.method().send({ from: address })
     .on('receipt', console.log)
     .then(console.log)`

Neither of the two is called. Tx hash callback is working fine though.

**Closed** 2019-04-08 20:32 UTC
Labels: P1-asap, T00-bug

**Comment by alexiicon** [comment] 2020-04-03 06:47
Hi, All
This issue i'm now see in Metamask browser on Android. And the worst of all i do not see how to debug it on Android? I' calling send(...) transaction generated and contract method called, but no receipt, no any callback. The same code is working through Chrome on PC. How can i avoid this problem on Android device and Metamask browser?

**Comment by vlddm** [comment] 2020-07-06 04:14
Same issue with Metamask 8.0.2 and Web3js 1.2.9
Code for rinkeby:
```
<html>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/web3/1.2.9/web3.min.js"></script>
<script>

    const abi=[{
            "constant": false,
            "inputs": [
                {
                    "name": "_owner",
                    "type": "address"
                },
                {
                    "name": "value",
                    "type": "uint256"
                }
            ],
            "name": "allocateTo",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function",
            "signature": "0x08bca566"
        }]


window.onload = async function () {
    const accounts = await window.ethereum.enable()
    console.log(accounts)
    const web3 = new Web3(window.ethereum);


    const from = accounts[0]
    const contract = new web3.eth.Contract(abi, '0xbF7A7169562078c96f0eC1A8aFD6aE50f12e5A99')
    contract.methods.allocateTo(from, 1e18.toString(10)).send({from})
    .on('transactionHash', console.log)
    .then(console.log)
}
</script>
</body>
</html>
```
Got txhash, never got receipt.
