### ISSUE TITLE
Sending eth to contract fails with default gas. 

### ISSUE THREAD

**Issue by robertmagier** [MetaMask/metamask-extension#8074] opened 2020-02-20 00:30 UTC
MetaMask is setting the gas limit of 21000 by default for eth sends even if it's to a contract which will always fail. An improvement would be to add additional gas padding if the the receiving address is a contract. This is identical to #7115. It seems it was fixed, but I got this error again. 

[Failing tx](https://kovan.etherscan.io/tx/0xa29b00bb23d7f2acfb10a8bbcbef28e8307be754b5ba0c5bcca7aa22606afeb9)

Version: 7.7.4
OS: PopOS
Web browser: Firefox 68.0.1 (64-bit)
Ethereum network: Kovan

**Comment by jennypollack** [comment] 2020-03-10 16:51
can confirm that sending to this address `0x5fa5b2f4b18b3ad1a529c4d5fc519eb4b88bfff5` on kovan is failing, but i was unable to repro on mainnet or rinkeby

**Comment by robertmagier** [comment] 2020-03-10 17:05
Do you need anything from me? I guess I can deploy this ocntract on mainnet if this is required.

**Comment by robertmagier** [comment] 2020-03-10 17:22
Ok. I deployed same contract on mainnet and it worked ok. 
[Transaction on Mainnet](https://etherscan.io/tx/0xde9747b981a5be1b2b273a6b3264e0c4ecce3a24d7cef6f86ae5a9b3d6a640c0)

In my opinion, you have this problem only on Kovan.

**Comment by jennypollack** [comment] 2020-03-10 17:32
agreed, thanks @robertmagier 
this seems to be a kovan issue
will investigate there

**Comment by zaryab19aug** [comment] 2020-10-07 09:11
Solidity v0.6.0.

MetaMask is setting the gas limit of 21000 by default for eth sends even if it's to a contract which will always fail. It works fine on solidity 0.4.26;

[https://etherscan.io/tx/0x52b7f19ae6be4cb3c731c3c455e6192e6ec1b2e5632991d31bc998e13b8539ab](Failed Tx)

Version: 8.0.10
OS: Ubuntu
Web browser: Firefox 81.0 (64-bit)
Ethereum network: Mainnet, Rineby, Testnet

**Comment by bschorchit** [comment] 2022-11-25 14:12
Duplicate of https://github.com/MetaMask/metamask-extension/issues/7772

**Closed by bschorchit** 2022-11-25 14:12 UTC
Labels: type-bug, area-gas, Sev2-normal, needs-triage, team-transactions
