### ISSUE TITLE
[Bug]: When there are multiple account, the delete key for the last account cannot be found

### ISSUE THREAD

**Issue by junjie9021** [MetaMask/metamask-extension#23083] opened 2024-02-21 08:19 UTC
### Describe the bug

When there are multiple account, the delete key for the last account cannot be found
<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/71370818/5bc305a1-24ec-4c77-bb5f-5536813931ae">

### Steps to reproduce

pls check `Describe the bug`

### Version

11.10.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment] 2024-02-22 15:13
Hi @junjie9021 , when you say "the delete key for the last account cannot be found", do you mean you can find the delete key for other accounts? (other than the last one)

**Comment by plasmacorral** [comment] 2024-02-22 16:53
This is a duplicate of https://github.com/MetaMask/metamask-extension/issues/22836.  The [fix](https://github.com/MetaMask/metamask-extension/pull/22889) is merged to develop and expected in upcoming release 11.12.0

**Closed by plasmacorral** 2024-02-22 16:53 UTC
Labels: type-bug, team-accounts, external-contributor, regression-prod-11.10.0
