### ISSUE TITLE
Skip initial setup + some feedback on mnemonic save workflow

### ISSUE THREAD

**Issue by buybackoff** [MetaMask/metamask-extension#6378] opened 2019-03-30 17:49 UTC
**What problem are you trying to solve?**
After a new install I have this wall in chrome:

![image](https://user-images.githubusercontent.com/489852/55279312-9380cd80-5328-11e9-9b35-f286bd15806b.png)

The problem is that I have my accounts in JSON format and passwords in a secure password manager. The first option is useless, the second option is just annoyingly lengthy, this screen where I need to press buttons in order is useless to confirm I stored it safely. It does not add protection from unsaved mnemonic (see below).

And now when I clicked through this I have a new garbage account that I cannot delete from UI. I need an option for a clean empty setup where I could import my existing account that do not have mnemonics.

**Describe the solution you'd like**

Add a third option "Import existing keys". Or even better just "Skip this step".

**Additional context**

Regarding clicking mnemonic words in order. You show the mnemonic and ask to save it somewhere. Cannot return to that screen now but either there is no save file option or it is not obvious. Mnemonic is a text that I need to copy-paste and store somewhere not to lose, and my first reaction is one of those things: email to myself or paste to sticky notes or notepad.

![image](https://user-images.githubusercontent.com/489852/55279551-aa282400-532a-11e9-9d1b-eaa02ae7873a.png)

But it's probably just my habit and not the main point. The main point is that at this step UI has my password, so it is completely possible to generate an encrypted text file and trigger its download so that a user has "Save as..." dialog. Even if the user stores it on desktop it's much better than plain text in clipboard - the file is on disk and is encrypted. Then I could just send that to myself in GMail, instead of saving the text file on desktop myself, going to 7Zip and archive it with encryption (which is BTW [broken](https://threadreaderapp.com/thread/1087848040583626753.html)), then fight with GMail and play with file extensions so that it actually allows me to send an encrypted file.

The file UI offers to save could be called "AccountBackup.metamask" or similar and UI should offer to upload such file. I would prefer the mnemonic never touches disk or placed in clipboard unencrypted. File content encryption should be some well know algo so that an advanced user could decrypt it manually from code.

Also UI should hint to use a password manager (optionally give links to good ones).

**Comment by terenceodonoghue** [comment] 2020-09-24 02:03
Keen to see this - using Metamask on multiple devices with a hardware wallet, it's a bit of a hassle to have to set up a new account every time that I won't use (not to mention I can't delete that account from Metamask later)

I'd be happy to raise a PR for a "Skip this step" option if the authors are open to it?

**Comment by tmashuang** [comment] 2020-12-09 20:30
Duplicate of #6466

**Closed by tmashuang** 2020-12-09 20:30 UTC
Labels: design feedback

**Comment by buybackoff** [comment] 2020-12-09 20:54
I don't really care anymore for the issue, but from GH point of view, that issue is the duplicate, it was raised later. Good work fixing it in 1.5 years anyways!
