### ISSUE TITLE
Cannot read property 'number' of null

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-extension#6750] opened 2019-06-25 05:54 UTC
**Describe the bug**
After siging tx (Confirm button) throws `"code":-32603,"message":"TypeError: Cannot read property 'number' of null`

**Screenshots**
![image](https://user-images.githubusercontent.com/9456433/60071995-82800680-9735-11e9-8380-ad1499ef842b.png)
![image](https://user-images.githubusercontent.com/9456433/60073021-b4469c80-9738-11e9-8d20-bd4741aa3224.png)

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - MetaMask Version 6.6.2

**Additional context**
I've got this error for the second time in my life. No idea how to reproduce this again.

**Comment by bdresser** [comment] 2019-06-25 15:37
@mqklin what site/dapp were you using when you encountered this error? any tips on how to reproduce?

**Comment by mqklin** [comment] 2019-06-26 07:47
@bdresser I used Zerion (https://beta.zerion.io), called `sendTransaction` (interacted with Compound - Lend tab on Zerion). But, as I said, it's very rare, and I can't reproduce this again.

**Comment by felixwatts** [comment] 2019-06-26 15:24
I've also encountered this in our in-house app.

**Comment by whymarrh** [comment] 2019-06-27 13:46
@frankiebee does this stand out to you? I'd guess a block is `null` somewhere?

**Comment by mqklin** [comment] 2019-06-28 04:56
Block is `null` very often on Infura, that's why we've created this wrapper:
```
export default async function handleNodeNullResponse(response, [f, args = []], responseTransformer = () => response) {
  if (response === null) {
    await sleep(3000);
    return f(...args);
  }
  return responseTransformer(response);
}
```
Then call:

```
async function getEthExchangeRate() {
  const contract = w3u.createContract(cETH.ABI, cETH.address);
  return handleNodeNullResponse(
    await contract.methods.exchangeRateCurrent().call(),
    [getEthExchangeRate],
    BigNumber,
  );
}

const ethExchangeRate = await getEthExchangeRate();
```

**Comment by frankiebee** [comment] 2019-06-29 12:34
yeah most likely the number is null it would be nice to know at what point it failed and having the debug history for the transaction would be very useful 
@mqklin if you could get your mm state and send it to support@metamask.io referencing this issue number it would be a lot of help!

**Comment by danfinlay** [comment] 2019-07-03 15:57
To help us diagnose your issue, you can download your "state logs" by [following this guide], and then sending them to support@metamask.io .

**Comment by mqklin** [comment] 2019-07-03 17:44
I've already done this! If I encounter this problem again, I'll immediately send you the logs

**Comment by mqklin** [comment] 2019-07-10 11:10
@danfinlay I've just got this error again, sent logs to support@metamask.io, please check!

**Comment by remon-nashid** [comment] 2019-07-11 17:38
I've reproduced this issue a couple of times, though quite sporadically, over the last few days. I sent my metamask state logs to support@metamask.io.

**Comment by dpazdan** [comment] 2019-07-11 18:03
related support case: 22367

**Comment by nick** [comment] 2019-08-21 16:30
I also just saw this issue. Restarting Chrome seemed to fix it.

**Comment by charleenfei** [comment] 2019-09-06 14:52
has anyone been able to consistently reproduce this error?

**Comment by danfinlay** [comment] 2019-09-06 16:54
This bug makes me want to convert our tx managing files over to typescript, since it is very stubborn about leaving code paths open that could allow things like trying to access a property on an undefined value.

**Comment by charleenfei** [comment] 2019-09-09 12:07
@danfinlay, would be amazing if you guys did manage the error in metamask -- we have implemented a wrapper to catch rpc errors but ideally we would love to not have to wrap every function call in a retry catch block :)

**Comment by khelmy** [comment] 2019-09-30 16:01
I just ran into this bug too while using ganache-cli, so I don't think it's an issue with Infura returning null. Restarting Chrome fixed it, but I have no idea what caused it.

**Comment by khelmy** [comment] 2019-09-30 17:23
Looks like I can recreate it by turning off a previously connected instance of ganache-cli and starting it up again while not restarting Chrome.

**Comment by elenapan** [comment] 2019-11-20 13:04
This happens when switching MetaMask accounts and attempting to send a transaction without first reloading the tab.
Reloading the tab is necessary on some dApps which initialize the selected account once when the page loads and do not subscribe to the web3 provider's changes. Thus they are trying to send a transaction from an unselected account.

In my apps, I use this snippet to subscribe to MetaMask changes:
```javascript
web3.currentProvider.publicConfigStore.on('update', (out) => {
    console.log('Selected address', out.selectedAddress)
    // Do something with out.selectedAddress here
})
```
You will notice this runs even when the user opens MetaMask and closes it without changing anything. Depending on how you handle account changes, you might need to check if `out.selectedAddress` is the same as the old address you have saved in some variable.

**Comment by danfinlay** [comment] 2019-11-20 18:31
That is an internal API and is prone to random change. I recommend using the supported EIP-1193 compatible event listener `ethereum.on('accountsChanged', handler)`:

https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.on(eventname%2C-callback)

**Comment by sarru1291** [comment] 2019-11-29 15:41
Here a solution that I applied after reading the above comments and it worked. I closed the chrome and restart it and finally that error is gone.
So, I think this error arose as I've opened, added or switched to so many accounts in metamask. this may be the reason for you, you can try .

**Comment by tmashuang** [comment] 2020-11-09 18:12
Going to close this, as there have been changes to the aforementioned parts of code that this error could have originated from. If anyone is continuing to get this error please open a new issue with enough information to reproduce your issue.

**Closed by tmashuang** 2020-11-09 18:12 UTC
Labels: N02-needsReproduction
