### ISSUE TITLE
[Bug]: [MV3] When I terminate SW while showing the Private Key popup, user is logged out but private key remains visible

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15915] opened 2022-09-21 09:41 UTC
### Describe the bug

**Problem**: when I go to Account Details and I click to reveal private key, if service worker is terminated at that time, I see that user is logged out, but the Private Key is exposed and popup continues to be displayed.

[private-key-sw.webm](https://user-images.githubusercontent.com/54408225/191471702-8e739e7b-876f-4012-9519-acb4d0ca767f.webm)

### Steps to reproduce

1. Unlock MM
2. Click Account Details
3. Click Reveal Private Key
4. Enter password
5. Terminate Service Worker -- see how user is logged out but popup is still visible with the private key

### Version

[MV3 build] develop

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment] 2023-01-24 17:30
This bug is no longer reproducible as of https://github.com/MetaMask/metamask-extension/pull/15558

And so is no longer an MV3 blocker. However, we should clean up some code so that if a user is ever logged out, modal state is cleared (or the modal is hidden). In practice, that doesn't matter today, because it is impossible to log out if a modal is open. However, ensuring the clearing of state ensures no sensitive information is ever accidentally revealed in case of a regression that allowed log out while a modal is open. Ultimately the fix for this will be to refactor away the old modal system, but we can do a quick fix as a precaution in the meantime (but agian, need not block MV3). An issue for this is here: https://github.com/MetaMask/metamask-extension/issues/17383

**Closed by danjm** 2023-01-24 17:30 UTC
Labels: type-bug, needs-reproduction, MV3, team-extension-client, team-extension-platform
