### ISSUE TITLE
Don't store every tx retry attempt in tx history

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3128] opened 2018-01-29 22:13 UTC
This may be the cause of the storage issues we've seen.

**Comment by whymarrh** [comment] 2019-08-22 00:02
Refs #7015

**Comment by Gudahtt** [comment] 2024-07-24 12:34
Closing in favor of #9372 (it's a duplicate of this, but it has more info)

**Closed by Gudahtt** 2024-07-24 12:34 UTC
Labels: type-enhancement, area-storage
