### ISSUE TITLE
Cannot sign Matic Mainnet transaction with ledger nano-s

### ISSUE THREAD

**Issue by boffix** [MetaMask/metamask-extension#10336] opened 2021-02-02 20:02 UTC
**Describe the bug**
Cannot sign a transaction via ledger and metamask for transfering Matic token on Matic Mainnet

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Config Custom Network RPC for Matic, see at bottom "Additional Context"
2. Connect hardware wallet -> Ledger
3. Send 5 Matic to another address
4. verify and confirm transaction
5. get error message: **Failed transaction** Transaction 0 failed! Error: Ledger: The transaction signature is not valid

**Expected behavior**
Token should be send after confirmation done via Ledger.

**Screenshots**
https://user-images.githubusercontent.com/42446112/106655469-b0782e80-6599-11eb-9ea3-d6e7979d2781.mp4
![2021-02-02 18_29_00-MetaMask](https://user-images.githubusercontent.com/42446112/106655597-de5d7300-6599-11eb-889f-a5e058e4f54c.png)
![2021-02-02 20_51_53-Guide_ How to Set Up Custom Matic Mainnet RPC for MetaMask   Transfer Assets fro](https://user-images.githubusercontent.com/42446112/106655644-eb7a6200-6599-11eb-8de2-d96579e0c428.png)

**Browser details (please complete the following information):**
 - OS: [Windows 10 (Version	10.0.19042 Build 19042]
 - Hardware Wallet: [Ledger Nano S Firmware version 1.6.1]
 - Browser: [Chrome Version 88.0.4324.104 (Official Build) (64-bit)
 - MetaMask Version: [9.0.4]

**Additional context (Error Messages, etc.)**
Custom Network "Matic" added like this:
**Network Name**: Matic Mainnet
**New RPC UR**L: https://rpc-mainnet.matic.network
**Chain ID**: 137
**Symbol**: MATIC
**Block Explorer URL**: https://explorer.matic.network/

**Comment by Gudahtt** [comment] 2021-02-02 20:08
Thanks for the report!

This might be a duplicate of #10294 - we can check when that has been fixed.

**Comment by boffix** [comment] 2021-02-02 20:15
Thanks, will keep an eye on that too!

**Comment by boffix** [comment] 2021-02-10 19:04
> Thanks for the report!
> 
> This might be a duplicate of #10294 - we can check when that has been fixed.

Awesome! Just checked #10294 - and tried to send a Matic again. Guess what :) it worked. Many thanks to all involved, that was a fast solution.

**Comment by darkwing** [comment] 2021-02-10 21:53
Excellent, thank you for the update @boffix !

**Closed** 2021-02-10 21:53 UTC
Labels: L17-hardware, S2-normal, T00-bug, ledger-hardware-wallet, x02-customNetworks

**Comment by numa-nalo** [comment] 2021-03-03 00:22
> Awesome! Just checked #10294 - and tried to send a Matic again. Guess what :) it worked. Many thanks to all involved, that was a fast solution.

🐲 On my hand I still can't send MATIC tokens from Ledger Nano S to Metamask on the Matic network... how come ?
