### ISSUE TITLE
Clicking "Import using account seed phrase" Nothing happens.

### ISSUE THREAD

**Issue by stoplion** [MetaMask/metamask-extension#9326] opened 2020-08-30 00:12 UTC
When I click Clicking "Import using account seed phrase" Nothing happens.

**Expected behavior**
I have no idea, I've never used this plugin. I'm guessing a popup comes up?
Instead nothing happens.

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser Chrome Version  85.0.4183.83
 - MetaMask latest

**Comment by tmashuang** [comment] 2020-08-31 17:16
Curious as I couldn't reproduce this issue, possible that there could be an issue with generating the url, [extension.runtime.getURL](https://github.com/MetaMask/metamask-extension/blob/b6ccd22d6c0ff6b9797c7aa24429f3df6d031af7/app/scripts/platforms/extension.js#L86).
Another issue could be a third party setting can be preventing opening a tab
[this.openTab](https://github.com/MetaMask/metamask-extension/blob/b6ccd22d6c0ff6b9797c7aa24429f3df6d031af7/app/scripts/platforms/extension.js#L95)

**Comment by jacobcantele** [comment] 2020-11-08 01:11
Closing this issue for now since we've been unable to reproduce. HAppy to re-open if there are further reports of this.

**Closed by jacobcantele** 2020-11-08 01:11 UTC
Labels: N02-needsReproduction
