### ISSUE TITLE
Warn users when sending tokens to token contract address

### ISSUE THREAD

**Issue by epheph** [MetaMask/metamask-extension#9673] opened 2020-10-21 22:58 UTC
**Describe the bug**
Hello, I run the "TokenOops" twitter bot ( https://twitter.com/TokenOops ), which chronicles the many millions of dollars of value lost to users accidentally sending ERC20 tokens to the token address, instead of the intended recipient. Recently, someone lost over $1,000,000 worth of $AAVE . Given how minimal/infrequently updated metamask token lists are, which requires users to copy/paste the contract address into MetaMask "Add Token" form, it is INCREDIBLY easy to make this mistake.

MetaMask should warn users when sending tokens to the contract address itself.

It is strange, because I see references to this protection in MetaMask's documentation, but it does not warn me when attempting to make this mistake?

https://metamask.zendesk.com/hc/en-us/articles/360020028092-What-is-the-known-contract-address-warning-

![Screen Shot 2020-10-21 at 4 50 33 PM](https://user-images.githubusercontent.com/361654/96798390-0d225580-13be-11eb-8bda-4a3f42bd8291.png)

**Steps to reproduce (REQUIRED)**
Either add a built-in token, or "Add Token" for a token you have a balance of. Put address of token in the "to". Hit "Send" if you are willing to lose that amount of token.

**Expected behavior**
System should warn violently about the potential loss of funds, potentially even requiring some sort of a "type confirm" as seen from Uniswap's UI.

**Screenshots**

**Browser details (please complete the following information):**
 - OS X
 - Hardware Wallet: n/a
 - Browser: Version 86.0.4240.80 (Official Build) (x86_64)
 - MetaMask Version: 8.0.10

**Comment by epheph** [comment] 2020-10-22 03:14
Related: #9606

**Comment by epheph** [comment] 2020-10-22 16:57
Received this Twitter DM just this morning from someone who lost a lot of tokens:

![Screen Shot 2020-10-22 at 10 55 28 AM](https://user-images.githubusercontent.com/361654/96905166-540f5a00-1455-11eb-9783-626f39bfe6f7.png)

**Comment by jacobcantele** [comment] 2020-11-08 00:10
This is a duplicate of #9437 so I'll be closing this one for now. Resolving this is a priority for us though.

**Closed by jacobcantele** 2020-11-08 00:10 UTC
Labels: T01-enhancement

**Comment by epheph** [comment] 2020-11-09 16:27
Not sure how I missed the original ticket, thanks for linking them!
