### ISSUE TITLE
Metamask no longer working with iDex - the exchange will not connect with the wallet and says that there is no plugin extension.

### ISSUE THREAD

**Issue by kiwisanchez** [MetaMask/metamask-extension#3357] opened 2018-02-28 21:34 UTC

**Comment by tmashuang** [comment] 2018-02-28 21:42
Have you contacted IDEX with their issue? Will leave this open for others to chime in on the issue with IDEX and MetaMask.

**Comment by kiwisanchez** [comment] 2018-02-28 21:47
Hi Thomas - yes have raised it with them, will see what they come back
with.  See if other people chime in with other probs.

Thanks

**Comment by tmashuang** [comment] 2018-02-28 21:52
Related reddit post on Auroradao by one of its moderators: 
https://www.reddit.com/r/auroradao/comments/80t5ok/idex_metamask_announcement/

**Comment by kiwisanchez** [comment] 2018-02-28 21:53
Legend, thanks for the info.

**Comment by ThreePhper** [comment] 2018-03-01 04:13
Dose idex detect MetakMask by web3.currentProvider.constructor.name.
I found it has been changed from "MetamaskInpageProvider" to "f" today.

**Comment by jeff70** [comment] 2018-03-01 14:04
Yep mine don't connect to it either.

**Comment by webcaetano** [comment] 2018-03-02 03:46
Bancor also start experiencing multiple tx Failed. On this new major version

Related:
https://github.com/bancorprotocol/contracts/issues/195

**Comment by Gektorian** [comment] 2018-03-02 06:19
not working on my end as well

**Comment by relpmis** [comment] 2018-03-02 10:00
not working for me, confirm

**Comment by kumavis** [comment] 2018-03-02 18:19
devs: please use `web3.currentProvider.isMetaMask`

**Comment by danfinlay** [comment] 2018-03-02 18:22
With a little more detail:

Caused by #3372. Sites here broke because they used an undocumented method of identifying MetaMask, which we broke because we didn't know anyone was doing it:
```
window.web3.currentProvider.constructor.name === 'MetamaskInpageProvider'
```

The correct way to identify MetaMask from in a page is:
```
window.web3.currentProvider.isMetaMask
```

Closing as a duplicate of #3372

**Closed by danfinlay** 2018-03-02 18:22 UTC
Labels: S4-Dapp, T7-userquestion

**Comment by keife** [comment] 2018-03-06 02:43
IDEX sucks! Never working with MetaMask, worst exchange I have come across.
