### ISSUE TITLE
Speed up transaction replaced the original one. After canceling the speed up, it shows as failed in metamask, even thought the original transaction was successful

### ISSUE THREAD

**Issue by georgeandrei** [MetaMask/metamask-extension#8831] opened 2020-06-18 09:56 UTC
A user attempted doing a transaction with low gas price.
After waiting several minutes, he clicked "Speed up". When the request to confirm from his ledger came, he changed his mind and cancelled the "speed up" operation, leaving the transaction as it was on etherscan.
The transaction has successfully gone through (see etherscan link attached), however metamask displays it as failed.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Submit transaction with  Ledger
2. Click on Speed Up
3. Cancel the Speed  Up request on Ledger
4. See failed  transaction in metamask transaction history, even though the original went through

https://etherscan.io/tx/0x3ee88beabe40bca47317de402168ea23ab521ca7fc6a24ce33d9c920e03ae8a6 - this is the confirmed transaction

It seems the original transaction has been removed to be replaced with the failed one (note the 20GWei gas transaction on etherscan vs the 25GWei gas transaction on metamask screenshot). The only option is to "Retry" the transaction in metamask, which should not be there as it actually went through.

Expected behaviour:

After canceling the speed up, see the original transaction in the history with the correct status

![image](https://user-images.githubusercontent.com/45980656/85006504-e11e6b80-b162-11ea-9125-11105ff83d08.png)

**Browser details (please complete the following information):**
 Firefox 77.0.1 (64-bit)
Metamask 7.7.9 (last updated June 5, 2020)

**Additional context (Error Messages, etc.)**

**Comment by OneBiteLawnOrder** [comment] 2020-07-15 18:06
Another issue I have encountered is that because the failed Speed Up transaction replaces the original transaction there is no option to further Speed Up or Cancel the original transaction in the case that it remains pending due to a low gas price.

**Comment by brad-decker** [comment] 2020-07-21 21:01
@tmashuang @Gudahtt related to #9041 and #9040

**Comment by tmashuang** [comment] 2020-07-22 18:48
> It is related, but a different flow. That solution could just be to suppress/omit hardware wallet rejection of tx from updating the tx,

**Comment by Gudahtt** [comment] 2021-01-13 15:42
Related to #9053

**Comment by danfinlay** [comment] 2021-02-02 18:35
Closing as a duplicate of #9053

**Closed by danfinlay** 2021-02-02 18:35 UTC
Labels: S2-normal, T00-bug
