### ISSUE TITLE
Batch requests but only approve once?

### ISSUE THREAD

**Issue by jamesmorgan** [MetaMask/metamask-extension#6974] opened 2019-08-08 08:13 UTC
**What problem are you trying to solve?**
I currently use web3.js and the BatchRequest functionality - I would like to be able to do this but only `approve` once - currently it should  `1 or 100` if I batch send 100 transactions and I need to approve each one separately. Is there a way of doing this which requires a user to only approve once? 

**Describe the solution you'd like**
Present the same diagalog but with an `approve all` button which approves and submits the txs in the order issued on the batch. 

**Additional context**
I am using this feature on networks such as POA and xDAI which allows for cheaper and faster throughput of txs when compared to eth mainnet. 

This is the web3 feature I am using at present - https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#batchrequest

**Comment by bdresser** [comment] 2019-08-08 20:02
closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/4050, added this specific usecase there as a comment

**Closed by bdresser** 2019-08-08 20:02 UTC
