### ISSUE TITLE
[Bug]: deprecated test networks warning reappears after being dismissed

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#15829] opened 2022-09-14 13:21 UTC
### Describe the bug

The deprecated test network warning should not be shown again on Ropsten until the user switches away and back again

https://user-images.githubusercontent.com/53189696/190165398-d4d5b2e4-d1a7-4f1f-8aaa-534ab9ca42b1.mov

### Steps to reproduce

1. Dismiss the warning
2. Reload the page

### Version

10.19.0

### Browser

Firefox

### Operating system

MacOS

**Comment by bschorchit** [comment] 2022-09-14 15:58
Dan M. opened a similar ticket 😅 For this very specific case, this is the intended behavior:
https://github.com/MetaMask/metamask-extension/issues/15803#issuecomment-1245426762

**Comment by danjm** [comment] 2022-09-14 20:46
closing as per Barbara's comment

**Closed** 2022-09-14 20:47 UTC
Labels: type-bug, rc :package:
