### ISSUE TITLE
Havent been able to open metamask for a few months now please help. 

### ISSUE THREAD

**Issue by 513yoshi** [MetaMask/metamask-extension#5317] opened 2018-09-22 02:41 UTC

**Comment by donpdonp** [comment] 2018-09-23 20:37
same here. at some point, months ago, metamask started crashing as soon as the icon is clicked. ive uninstalled and reinstalled many times. id really like to have metamask back. FF 63.0b7. MetaMask 4.9.2

**Comment by tmashuang** [comment] 2018-09-23 20:41
Without any additional information, such as OS and Error messages, there it only one instance I know of that MetaMask won't open. https://consensys.zendesk.com/hc/en-us/articles/360007617432

**Comment by donpdonp** [comment] 2018-09-23 20:44
OS: Ubuntu 18.04 on Intel Core i5. Where would I look for error messages?

**Comment by donpdonp** [comment] 2018-09-23 20:46
so i took a look at the stdout from firefox and there is an error message there. this message repeats about 5 times for each time I try to open the metamask extension by clicking on the icon.

```
IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer Processing error: message was deserialized, but the handler returned false (indicating failure)
```

**Comment by tmashuang** [comment] 2018-09-23 20:46
If the OS is indeed Ubuntu 18.04, there is a workaround in the support article I linked. The longer thread is on Ubuntu.18.04 is https://github.com/MetaMask/metamask-extension/issues/3313.

**Comment by bdresser** [comment] 2018-09-24 19:38
closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/3313

Possibly also related to the open bounty on https://github.com/MetaMask/metamask-extension/issues/4894.

**Closed by bdresser** 2018-09-24 19:38 UTC

**Comment by donpdonp** [comment] 2018-09-26 16:13
For the benefit of the early posters who still need a work-around, the tickets posted here lead to firefox, which lead to a graphics issue. There is something about Xwindows that is causing it. On Ubuntu 18.04, I tried switching from X to X/Wayland and metamask is working again.
