### ISSUE TITLE
Events not working while using Metamask

### ISSUE THREAD

**Issue by rawadrifai** [MetaMask/metamask-extension#2536] opened 2017-11-04 23:49 UTC
Hello
I have an event configured to fire after a certain function is called in my contract.
The event fires perfectly when using truffle console. It also fires perfect when I'm watching it from the frontend and using a local web3. But when I use metamask and inject a web3, events stop working. Well, they still get registered but "watching" them from the frontend stops working. If I refresh the page, it's able to get all the events fine.
Any idea what's going on?

This video will describe it better:
https://drive.google.com/file/d/1XGfMHeChTZc_gMAlmb6itKJaotm7Fd-g/view

**Comment by tmashuang** [comment] 2017-11-06 17:13
Duplicate of #2393

**Closed by tmashuang** 2017-11-06 17:13 UTC
