### ISSUE TITLE
Rounding issue when sending max tokens

### ISSUE THREAD

**Issue by alextsg** [MetaMask/metamask-extension#5303] opened 2018-09-20 00:04 UTC
https://github.com/MetaMask/metamask-extension/pull/4895#issuecomment-422995316

> for a test token with precision 18, while the balance was 30,000.000000011117116443 tokens, I tried to send max token balance to another account. When I click 'max' button, the value is rounded up to 30000.000000011118 tokens. This is not noticed by people. The transactions are failing with bad-instruction or no-event errors.

**Comment by bdresser** [comment] 2018-10-19 19:34
this also applies to showing long ETH amounts on the confirm screen. 

relates to https://github.com/MetaMask/metamask-extension/issues/5180 as well

**Comment by bdresser** [comment] 2018-10-19 19:36
actually, closing as a dupe of https://github.com/MetaMask/metamask-extension/issues/5180

**Closed by bdresser** 2018-10-19 19:36 UTC
Labels: L03-UI
