### ISSUE TITLE
Transfer fails stating insufficient funds

### ISSUE THREAD

**Issue by Youngerdryas** [MetaMask/metamask-extension#2655] opened 2017-12-04 22:18 UTC
When transferring less than a tenth of wallet value I receive the error: insufficient funds for gas * price + value

I am attempting to move 1 ETH from a wallet containing 3.99 ETH with a gas limit 31500 Gas Price of 20 GWEI. There should be no funding error. 

This error started after multiple transactions being stuck pending all day yesterday. Those transactions all ultimately failed to go through.

I have been using Meta Mask reliably for about 2 months at this point. I'm not sure what has changed in the last few days.
![metamask error](https://user-images.githubusercontent.com/34253543/33579264-6b65d9aa-d906-11e7-8665-8dc79f1b489e.jpg)

Using Google Chrome on Windows 10.

**Comment by ili16** [comment] 2017-12-04 22:36
same problem here, would love to get a response by MetaMask ASAP

**Comment by Tigerfood** [comment] 2017-12-04 22:38
same shit here bro

**Comment by k06a** [comment] 2017-12-04 22:39
Same for me

**Comment by Tigerfood** [comment] 2017-12-04 22:40
did you get this error before : transaction underpriced ?

**Comment by tmashuang** [comment] 2017-12-04 22:46
Currently, the network has a backlog of transactions, ~140,000, so transactions are waiting to get mined.

**Comment by voldemarz** [comment] 2017-12-04 22:47
I was getting this as well when trying to transfer funds from EtherDelta. 
![image](https://user-images.githubusercontent.com/1264210/33580395-55ebb5c6-d94d-11e7-953e-0399e15af321.png)

**Comment by voldemarz** [comment] 2017-12-04 22:47
@tmashuang How does that relate to this issue?

**Comment by k06a** [comment] 2017-12-04 22:55
@tmashuang I can see only 15K transactions in mempool: https://etherscan.io/txsPending

**Comment by tmashuang** [comment] 2017-12-04 23:02
Whoops added and extra 0. 15k pending transactions. Regardless, this shouldn't be related to the insufficient gas. Please submit your state logs to https://support.metamask.io. Guide to state logs, https://support.metamask.io/kb/article/15-copying-state-logs

**Comment by TheBritton** [comment] 2017-12-04 23:08
also having the same problem. Started today with Metamask . errors out in same way with every tranaction. Tried sending 2 Eth with 500,000 gas at 25 gwei . Fails . account has 7 eth balance

**Comment by efalken** [comment] 2017-12-04 23:16
Same error...nothing works from my MetaMask for past 30 minutes...I have enough funds

**Comment by danyalaytekin** [comment] 2017-12-04 23:19
I think it's a Kitty overload.

**Comment by TheBritton** [comment] 2017-12-04 23:26
kitty overload ? Bloody Purrfect mate :(

**Comment by dmunicio** [comment] 2017-12-05 00:15
I am having the same problem. I think that is related to the new installed version of metamask (3.12.1). 
I get the error sending 0.1ETH to a changelly address...

**Comment by scottie** [comment] 2017-12-05 00:36
same here

**Comment by danyalaytekin** [comment] 2017-12-05 00:37
@dmunicio It happens on 3.5.2.

**Comment by Youngerdryas** [comment] 2017-12-05 00:44
So my ETH is frozen in Meta while a cat game puts the brakes on blockchain...

**Comment by efalken** [comment] 2017-12-05 00:48
Interestingly, if I send within accounts in my 'seed phrase' (ie, not 'loose' accounts), it works fine....MyEtherWallet is slow, but still works...MetaMask, however, still down

**Comment by dmunicio** [comment] 2017-12-05 00:50
I am sending it with my "Account 1" which is not a loose account...

**Comment by k06a** [comment] 2017-12-05 00:51
Looks like Metamask node is out of sync

**Comment by Youngerdryas** [comment] 2017-12-05 00:56
I just tried sending between my two meta accounts under one seed and had the same error.

**Comment by rshuk** [comment] 2017-12-05 01:09
@Youngerdryas same here

**Comment by efalken** [comment] 2017-12-05 01:10
ok...transferring between accounts fails for me now too...maybe I was just lucky that one time

**Comment by scottie** [comment] 2017-12-05 01:11
fixed for me:
was change the settings so im using https://mainnet.infura.io

**Comment by scottie** [comment] 2017-12-05 01:22
exact fix for me was to close chrome, open BRAVE, go to cryptokitties.co and sign in AFTER i login to BRAVE metamask using my 12 WORDS. Then i changed settings connection to https://mainnet.infura.io after this all was good using 35 GIEI all transaction went threw very fast :) good luck guys

**Comment by giaset** [comment] 2017-12-05 02:50
Same issue for me :(

**Comment by stanishev** [comment] 2017-12-05 02:56
using @scottie 's solution, changing the settings to: https://mainnet.infura.io worked for me too. 
select Custom RPC
https://mainnet.infura.io in the New RPC URL field
save
and that should be it (doing this in latest firefox, but I suspect this should work across browsers).

**Comment by efalken** [comment] 2017-12-05 03:17
what is this infura thingy? Works! Does it have a token? Might be valuable...

**Comment by tommyms** [comment] 2017-12-05 04:35
Had the same issue, just send unds back using MEW and Private Key if nothing else works.

**Comment by VivekNair** [comment] 2017-12-05 05:15
Can confirm that @stanishev and @scottie fixes worked for me. Use the Brave browser (https://brave.com/). It comes with MetaMask pre-packaged already.

You will be prompted once you visit cryptokitties.co to install MetaMask.

**Comment by rshuk** [comment] 2017-12-05 05:19
I tried the above steps and was able to execute ETH transfer transaction however, I had selected 1 GWEI as gas price and now the transaction is showing as "Pending" from last couple of minutes (see TxHash: 0xc6553f0893ed11f65a9a7996e94225f5c13327bfc80c7915abf942579d6787bf).

Can I be sure that my transaction will be included in some block? Also, until when you guys will try to execute the transaction post which you would give up? Have miners raised mining fees lately which means that I cannot transfer balance/tokens using 1 GWEI?

**Comment by MadameMadman** [comment] 2017-12-05 08:34
still broken Metamask has been down for me since around 5pm today PST, so for the past 7 hours. I was able to put ETH into my account just fine, but haven't been able to do anything since then. I am able to deposit funds to my accounts, but any transfering is out of the question. I've tried both chrome and brave browsers, I've reentered passphrases, and restarted my computer to no avail.

**Comment by vishaluae** [comment] 2017-12-05 08:35
Crypto Kitties are clogging the network

**Comment by CptanPanic** [comment] 2017-12-05 11:43
So are people saying that the error "gas * price + value" is not the real error, but is actually caused by an overload of the system?

**Comment by Tigerfood** [comment] 2017-12-05 12:06
still i cant do nothing... already 6 hours passed and my transaction is in progress X_x

**Comment by voldemarz** [comment] 2017-12-05 12:17
@Tigerfood That has nothing to do with Metamask.

**Comment by JesseBusman** [comment] 2017-12-05 12:24
I can't send any transactions with MetaMask anymore.
I installed the Firefox addon with the same seed words, same problem. Can't do anything.
That leads me to believe the problem is not on my end.

**Comment by submariner86** [comment] 2017-12-05 12:42
chaning RPC does not help me at all.. its not working same RPC error.. f****

**Comment by samdoyle1991** [comment] 2017-12-05 13:28
Nothing working for me, tried the Brave fix as stated above, but still can not send/receive tokens/ETH.

**Comment by efalken** [comment] 2017-12-05 14:38
samdoyle1991: did you try the mainnet.infura.io fix? Worked like a charm for me.

**Comment by samdoyle1991** [comment] 2017-12-05 14:48
@efalken Yep, tried the https://mainnet.infura.io fix, and did not work for me.

**Comment by MeBaranov** [comment] 2017-12-05 16:37
If i change to mainnet - even the amount of eth on account disappears :(

**Comment by tadyu228** [comment] 2017-12-05 16:51
https://mainnet.infura.io/ and Brave also showed same error.

Any response from MetaMask ?

**Comment by tadyu228** [comment] 2017-12-05 16:56
When I was asked to submit the transaction . It showed "Data included: 0 bytes" Is it abnormal ?

**Comment by abitrolly** [comment] 2017-12-05 17:28
> https://mainnet.infura.io in the New RPC URL field

I thought this is the default RPC.

**Comment by wordsandstuff** [comment] 2017-12-05 18:23
its the cats...

**Comment by efalken** [comment] 2017-12-05 22:17
yeah, today infura does not work..but the main net worked right away for transactions 1 and 2, but then it just stopped, as if they were done with me (out of gas errors)...so, I'm not sure at all what's going on, and infura is not a reliable solution (worth trying...but that's about it).

**Comment by danfinlay** [comment] 2017-12-06 04:38
We've now written a post about this issue, please see if it helps. Those saying "it's the cats" are basically right, but there are some tips too:

https://medium.com/metamask/metamask-cryptokitty-performance-update-83d851af0147

**Comment by naterexw** [comment] 2017-12-06 09:56
According to [ETH Gas Station](https://ethgasstation.info/), minimum recommended gas price is 31 Gwei.  I tried using 35 Gwei and my transaction was successful.  Recommend you adjust your metamask gas price to >31 and give it a try again

**Comment by cwrightogs** [comment] 2017-12-06 17:52
I had a number of transactions not showing up on Etherscan and the nonce kept increasing.   Switching to Brave and mainnet.infura.io solved it for me.  My last transaction showed up immediately (had to use 43 Gwei!) and the nonce went back down to what I expected.  Thanks for the help gang!!

**Comment by sevku** [comment] 2017-12-07 08:44
@naterexw may have worked earlier, now it's failing even with 40 Gwei (USD 2.90 !!)

**Comment by illBeRespawned** [comment] 2017-12-07 11:04
pretty amazing that a kitten game can shut down the ethereum network given the billions of dollars going into ERC20 token based ICOs that haven't even launched any of their applicaitons yet and are featuring hundreds of unaudited smart contracts.

I wonder what's going to happen once a few of them actually go live if this tiny kitten game can bring the network down.

**Comment by vishaluae** [comment] 2017-12-07 12:38
ethgasstation recommends 61 gwei for a standard speed (<5m) transaction (Predicted wait time of 1.9 minutes)

**Comment by chusoruiz** [comment] 2017-12-08 19:42
Hi there,

I have also tried to buy some kitties but imposible to do. Now I try to send the money back to coinbase and it is also imposible. I press SEND, write the Coinbase Recipient Address and a fewer amount in order to have somthing for the fee. Later appears again like If I want to buy more ETH.

Any solution?

Thanks

**Comment by danfinlay** [comment] 2017-12-18 20:09
These failures were related to the great kitty backlog of 2017. This issue should be mostly mitigated now, let us know if you have these problems again.

**Closed by danfinlay** 2017-12-18 20:09 UTC

**Comment by 7urboPitt** [comment] 2018-03-20 21:51
"First of all I want to say that I have been a member of this community for about 2 years, and interacted successfully with many different blockchain software applications. I'm not a "noob".

I only used MetaMask to go in and out of EtherDelta because I tend to not trust any third-party wallet software. I had a sell order for 30,000 E4ROW tokens (yes not worth much, but still a total USD value of my account at about $2,000).

When I initially installed MetaMask years ago, I received a seed phrase which I wrote on a sheet of paper and stored securely. Usually MetaMask just required me to enter my private key to sign into my hot wallet, which I did without issue. Once, it wouldn't let me sign in for whatever reason, so I backed up from the seed phrase I had stored. That was successful, so I figured from that point on that there would be no future problems with the seed phrase.

About 2 weeks ago, I tried signing into MetaMask to cancel my unfilled sell order. The password was not working for whatever reason, so I was prompted to use my seed phrase to re-boot the account. I entered the seed phrase as I did the previous time, from the written version I had, but this time the MetaMask software generated a new wallet. I started panicking because I knew that if my seed phrase generated a new wallet that was evidence of a bug, and evidence that I'd never be able to access my old wallet again.

Sure enough, it was a software bug that was never announced on any of their public communication channels.

Here is the exact software bug that caused me to lose all my hotwallet funds in their Github issues tab: https://github.com/MetaMask/metamask-extension/issues/2383

I went with this information to the MetaMask support Slack channel, and was treated with total disrespect by the devs. My problem was not taken seriously (I was blamed for writing down the wrong seed phrase, which is impossible because I already generated the account previously with the same seed phrase), and I was promptly ignored after linking them to the Github error for this exact problem (another user not affiliated with the dev team was kind enough to try to help at this point, but that was 7 or so days ago and the main dev has not responded to my issue since).

MetaMask is a venture of ConsenSys, arguably the largest blockchain company in the world. If their software developers write poor code that leads to a user losing all their funds, they should at the very least take responsibility for their error, which they have not done. They should also, in my opinion, refund the funds that were lost as a direct result of their team's error. This is a company with billions of dollars. I do not expect this to happen, it would just be ethical.

The main reason I'm making this post is to warn people about MetaMask. There are people who have much more funds in their hotwallet than I do, and after seeing how unprofessional the team is, I would actively recommend searching for alternative options (even using centralized exchanges to go in-and-out of trades instead of MetaMask + EtherDelta."    Is metamask kidding users ? this kind of thing has happened to me just now on windows 10 and all other updated. I am new to this game and has mined my first 30 min just now so uh i guess i dont lose too much now, hey metamask ?   Wasnt gona mine for a year with this dangerous appware losing (maybe washing) my hashes.  Churio Metamask , sorry i coulnt  lose any more for you, i know you like your sorries in your complaint replies.

**Comment by Zanibas** [comment] 2018-03-20 22:21
> When I initially installed MetaMask years ago, I received a seed phrase which I wrote on a sheet of paper and stored securely. Usually MetaMask just required me to enter my private key to sign into my hot wallet, which I did without issue. Once, it wouldn't let me sign in for whatever reason, so I backed up from the seed phrase I had stored. That was successful, so I figured from that point on that there would be no future problems with the seed phrase.

If this is the case, then that seed word should be still valid. I recommend trying to visit MEW or MyCrypto to see if that seed word still generates the correct accounts. It is hard for me to understand why a seed phrase that worked in the past would suddenly start generating new accounts.

**Comment by lazaridiscom** [comment] 2018-03-20 22:27
@7urboPitt , that's quite a criticism, you should possibly open a new issue, to give this more visibility. Kind of "User Experience Report / Criticism to MetaMask".

Beside what @Zanibas suggested, it may(!) could help to try an older version of MetaMask.

@danfinlay , I've seen this description 3 or 4 times during the time that I look at issues (around 3 weeks or so) : 

> About 2 weeks ago, I tried signing into MetaMask to cancel my unfilled sell order. The password was not working for whatever reason, so I was prompted to use my seed phrase to re-boot the account.

**Comment by danfinlay** [comment] 2018-03-21 00:45
Thanks for digesting that, @lazaridiscom.

It's very strange that a person's password would suddenly not work, I've opened an issue for exploring possible causes, it may merit a bug bounty:
https://github.com/MetaMask/metamask-extension/issues/3643

**Comment by sameer300** [comment] 2018-12-06 14:10
Hi everyone sir I have some fund in my metamask account but don't know how to transfer it into my bank account plz help me you will get your charges my Gmail I'd is mw8933@gmail.com and whats up number is-919958148218

**Comment by bdresser** [comment] 2018-12-06 21:05
@sameer300 please reach out to support@metamask.io

**Comment by shahidkarimi** [comment] 2021-03-16 10:12
Why close this issue @danfinlay ? This issue is still there.

**Comment by GianfrancoCorrea** [comment] 2022-01-05 22:20
i'm having this problem with matic network
