### ISSUE TITLE
Can't click address list item when you first time import a hw wallet

### ISSUE THREAD

**Issue by codeoneline** [MetaMask/metamask-extension#9935] opened 2020-11-24 04:15 UTC
When you first time use metamask 8.0.10, after you connect your hw wallet(trezor or ledger), it will show a list of addresses, but sometimes your can't click them

![Screenshot from 2020-11-24 12-12-57](https://user-images.githubusercontent.com/44689567/100047960-ad9ce700-2e4e-11eb-86fb-b70bfec5fd31.png)

**Comment by tmashuang** [comment] 2020-11-24 04:17
Duplicate of #6343, try refreshing the page or 
> Closing the extension configuration page, and accessing again though the icon allows the buttons to be selected successfully.

as someone mentioned on the issue.

**Closed by tmashuang** 2020-11-24 04:17 UTC

**Comment by codeoneline** [comment] 2020-11-24 04:34
> Duplicate of #6343, try refreshing the page or
> 
> > Closing the extension configuration page, and accessing again though the icon allows the buttons to be selected successfully.
> 
> as someone mentioned on the issue.

Well, I have make a pull requrest for this issue
