### ISSUE TITLE
Some ERC-20 tokens do not show the transfer amount or destination address on Ledger S or X due to outdated ledgerjs in MetaMask

### ISSUE THREAD

**Issue by ciconsulting** [MetaMask/metamask-extension#9035] opened 2020-07-18 13:53 UTC
**Describe the bug**

Some ERC-20 tokens do not show the amount being sent or the destination address on Ledger Nano S or X. 

**To Reproduce (REQUIRED)**

Send an affected ERC-20 token.

**Expected behavior**

See the amount being sent and the destination address on the ledger screen instead of only the fees and the ERC-20 token contract address.

**Screenshots**

N/A

**Browser details (please complete the following information):**

N/A the prloblem is caused by MetaMask using an outdated version of ledgerjs

**Additional context (Error Messages, etc.)**

Updating MetMask to the latest version of ledgerjs will fix the problem.

**Comment by tmashuang** [comment] 2020-07-22 16:48
Closing as a duplicate of #9035.

**Closed by tmashuang** 2020-07-22 16:48 UTC
