### ISSUE TITLE
Clear controller state on import

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#7230] opened 2019-09-30 13:00 UTC
Issue to track #7206

**Comment by bdresser** [comment] 2019-10-07 17:44
PR ready; needs discussion with @jennypollack and @frankiebee after devcon

**Comment by Gudahtt** [comment] 2019-10-17 01:43
This may be a duplicate of #2989

**Comment by Gudahtt** [comment] 2021-01-07 22:34
Closing as a duplicate of #2989

**Closed by Gudahtt** 2021-01-07 22:34 UTC
Labels: L04-backend/core
