### ISSUE TITLE
Lock\Unlock\Account Switch doesn't change web3.eth.account array

### ISSUE THREAD

**Issue by akucheruk-vareger** [MetaMask/metamask-extension#2582] opened 2017-11-14 18:16 UTC
Hi,
I know about [poll the web3.eth.accounts array](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#ear-listening-for-selected-account-changes) workaround but seems it doesn't help.

When I do Lock\Unlock\Account Switch the web3.eth.account array doesn't change and console.log(web3.eth.account) from code or browser console always returns the very first state until the page is completely reloaded and a new web3 from metamask is injected.

**Comment by tmashuang** [comment] 2017-11-14 18:23
Closing as a duplicate of #2268.

**Closed by tmashuang** 2017-11-14 18:23 UTC
