### ISSUE TITLE
Transaction incorrectly reported as "dropped"

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#7370] opened 2019-11-08 18:56 UTC
**Describe the bug**
I sent a transaction and MetaMask has labeled it as "dropped" although when I click through on the block explorer link the block explorer shows the tx is confirmed. Even after refreshing MetaMask the tx still shows as "dropped".

**To Reproduce**
1. Try to send DAI to a multisig address
2. See the tx is "dropped" in MetaMask
3. Click on the block explorer link to see the tx actually is confirmed

**Expected behavior**
A clear description of what you expected to happen.

I expect that the tx is shown as Confirmed in MetaMask

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser: Chromium 78.0.3904.70
 - MetaMask Version: 7.4.0

**Comment by wjmelements** [comment] 2019-11-10 22:47
I have seen the same thing on the same version. I submitted logs to zendesk.

**Comment by wjmelements** [comment] 2019-11-10 23:01
<img width="355" alt="Screen Shot 2019-11-09 at 4 55 54 PM" src="https://user-images.githubusercontent.com/799573/68552357-fd874800-03ca-11ea-8579-63eec4340bc8.png">

**Comment by wjmelements** [comment] 2019-11-14 23:12
<img width="356" alt="Screen Shot 2019-11-14 at 3 11 56 PM" src="https://user-images.githubusercontent.com/799573/68903818-1eb0a700-06f1-11ea-89b0-ebea78efb1fe.png">

**Comment by danfinlay** [comment] 2019-11-15 04:43
I have also now experienced this. Reviewing the code, there are [two places](https://github.com/MetaMask/metamask-extension/search?q=setTxStatusDropped&unscoped_q=setTxStatusDropped) this could be happening. 

Those files were edited [15 days ago](https://github.com/MetaMask/metamask-extension/pull/7327), so that seems a likely introduction point. So between those two method calls, either:

1. [The pending-tx-tracker is emitting its dropped event at the wrong time](https://github.com/MetaMask/metamask-extension/blob/514be408f8eef60b27b79743d6525bf60a354ce4/app/scripts/controllers/transactions/index.js#L598)
2. [The tx is being set to dropped during the successful tx cleanup phase, when other same-nonce txs are being marked as dropped](https://github.com/MetaMask/metamask-extension/blob/514be408f8eef60b27b79743d6525bf60a354ce4/app/scripts/controllers/transactions/index.js#L655-L668).

Looking at number 2 there, it looks like we are setting the tx with that ID to dropped right after setting it to confirmed, and that sure looks like a likely cause of this issue:
https://github.com/MetaMask/metamask-extension/blob/514be408f8eef60b27b79743d6525bf60a354ce4/app/scripts/controllers/transactions/index.js#L501-L502

However, that order of methods [is two years old](https://github.com/MetaMask/metamask-extension/commit/10aecf49227098fb7fdbd7db193a9dcc6fecf5af), so if that is the cause, it is because some other related behavior changed recently.

@frankiebee, could you look closer at this?

**Comment by safepayment** [comment] 2019-11-16 04:05
Having the same issue. In my case, it happened when I trigger multiple transfers at the same time. Hope it help to reproduce.

1) I clicked my'PAY' button to transfer tokens, and confirmed on meta mask.
2) I 'PAY' immediately for 2-3 addresses immediately. All were clicked within the same minutes.
3) Then the old one got DROP. Attached the screenshot. But the tx is success and confirmed later.

![metamask-drop](https://user-images.githubusercontent.com/50819254/68987855-1bd8c200-0869-11ea-8910-6882e31de4f7.png)

**Closed** 2019-12-05 19:34 UTC
Labels: T00-bug
