### ISSUE TITLE
[Bug]: The new password is not recognized; Metamask only accepts the old password after wallet reset

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-extension#25696] opened 2024-07-05 12:06 UTC
### Describe the bug

After going through the 'Forgot password' flow in Metamask and setting a new password, Metamask throws an 'Invalid password' warning when trying to login with the new password

### Expected behavior

Metamask should only recognize the newly set password.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/82837486/0de00905-ee01-4241-a90e-da60c5eb0976

### Steps to reproduce

1. Open the extension
2. Proceed to Forget password flow
3. Paste your secret recovery phrase
4. Set a new different password
5. Proceed to Restore your Wallet
6. After entering the account, lock it and try to login with the new password
7. It will throw an Invalid password error

### Version

12.0.0

### Build type

Beta

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by owencraston** [comment] 2024-07-17 00:53
This issue was patch fixed in v12 but still needs to be addressed on the `develop` branch.

**Closed** 2024-07-18 10:07 UTC
Labels: type-bug, Sev1-high, release-blocker, team-accounts, regression-RC-12.0.0

**Comment by benjisclowder** [comment] 2024-08-12 15:42
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

**1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?**
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

**Tagging eng. who added the fix:** @owencraston

**Comment by owencraston** [comment] 2024-08-12 20:15
1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

**Comment by owencraston** [comment] 2024-08-12 20:23
1. What PR fixed the issue?
-  patch fix: https://github.com/MetaMask/metamask-extension/pull/25787
- main fix: https://github.com/MetaMask/metamask-extension/pull/25847
2. Can you pinpoint the commit from which the issue originated?
- Unsure. Likely was a big for a while we just never caught it. The issue stems from the keyring controller which was fixed here: https://github.com/MetaMask/core/pull/4514
3. Write a short explanation of the technical cause of the bug
- Currently, when a user locks the app and then resets their password, they are not able to log in wth their new password.
- This is because the encryption key was generated with the old password and not cleared.
- To solve this we will remove the encryption key from state when the user locks the wallet as well as when #createNewVaultWithKeyring is called.
- This allows for a new encryption key to be generated with the new password when the user logs in again and submitPassword is called.
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
- Better end to end testing that tested the password reset flow
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
- yes. and I added new unit tests for this case [here](https://github.com/MetaMask/metamask-extension/pull/25847/files#diff-29e97c9c098aa22d75e9f194b6c36558ce4cc06b6b6dd22d87fde6b457cde9f6R8)
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
- no
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
- QA that went through this user journey.
- Better E2E


cc @benjisclowder
