### ISSUE TITLE
[Bug]: Token icons are not displayed on send flow

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25189] opened 2024-06-10 21:11 UTC
### Describe the bug

All chain icons other than Ethereum mainnet are not displayed on confirmation screen. For Arbitrum, Linea mainnet, Base, zkSync Era icons also not displayed for the currencies on the asset selection screen:

Related issue: https://github.com/MetaMask/metamask-extension/issues/24450

### Expected behavior

All chain / token icons are accurately shown.

### Screenshots/Recordings

<img width="409" alt="Screenshot 2024-06-10 at 16 59 37" src="https://github.com/MetaMask/metamask-extension/assets/104780023/c9a6eff0-74f1-4b8a-bca4-48a8325a14d8">

### Steps to reproduce

1. Switch to any network other than mainnet, e.g. Base
2. Start send+swap / legacy / EIP 1559 etc. transaction
3. Notice that chain icon is not shown on the confirmation screen

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment] 2024-06-20 16:52
Removing confirmations as the confirmations piece is not a regression on the release. I'm creating a separate issue to track the confirmations piece of it.

**Comment by chloeYue** [comment] 2024-07-05 16:13
Reopen this issue because I can still reproduce the issue on the latest v12.0.0. Checking with wallet UX team to see if the fix has been cherry-picked into the release branch.

**Comment by sleepytanya** [comment] 2024-07-07 19:34
Fixed on `develop`:

<img width="1438" alt="Screenshot 2024-07-07 at 15 33 34" src="https://github.com/MetaMask/metamask-extension/assets/104780023/9f5f00b0-b26e-4ecc-957d-2bfb9ec6da2c">

**Comment by danjm** [comment] 2024-07-09 18:31
closed by https://github.com/MetaMask/metamask-extension/commit/09136cd77c97f24461e9a0880370c76229b2a3c4

**Closed by danjm** 2024-07-09 18:31 UTC
Labels: type-bug, Sev2-normal, release-blocker, team-assets, release-12.1.0, release-12.0.0, regression-RC-12.0.0
