### ISSUE TITLE
[Bug]: [MV3] Reset account popup remains visible after SW stopps and user is logged out

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15916] opened 2022-09-21 09:51 UTC
### Describe the bug

**Problem**: when I am in the middle of resetting an account, if service worker stopps, I still can see the Reset account popup open while MM is locked.

[reset-account-popup.webm](https://user-images.githubusercontent.com/54408225/191473593-8ba809d5-69e9-48ed-8e35-b988048e8429.webm)

### Steps to reproduce

1. Unlock MM
2. Go to Advanced Settings
3. Click Reset Account
4. Terminate SW -- see how MM is locked but popup is still displayed

### Version

[MV3 build] develop

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment] 2023-01-24 17:30
This bug is no longer reproducible as of https://github.com/MetaMask/metamask-extension/pull/15558

And so is no longer an MV3 blocker. However, we should clean up some code so that if a user is ever logged out, modal state is cleared (or the modal is hidden). In practice, that doesn't matter today, because it is impossible to log out if a modal is open. However, ensuring the clearing of state ensures no sensitive information is ever accidentally revealed in case of a regression that allowed log out while a modal is open. Ultimately the fix for this will be to refactor away the old modal system, but we can do a quick fix as a precaution in the meantime (but agian, need not block MV3). An issue for this is here: https://github.com/MetaMask/metamask-extension/issues/17383

**Closed** 2023-01-24 17:30 UTC
Labels: type-bug, needs-reproduction, MV3, team-extension-client, team-extension-platform
