### ISSUE TITLE
[Bug]: Overly high default max priority fee on a custom network

### ISSUE THREAD

**Issue by TheAppleTucker** [MetaMask/metamask-extension#21249] opened 2023-10-08 16:25 UTC
### Describe the bug

We're running a number of production rollups, including [Manta Pacific](https://l2beat.com/scaling/projects/mantapacific).

We're noticing that the default max priority on Metamask tends to be set at 1.5 gwei with the slow option being 1gwei and the aggressive option being 2 gwei (see screenshot).

For these OP stack L2s, a relatively low priority fee of 0.0001 gwei should be more than enough to get a transaction through: https://community.optimism.io/docs/developers/build/transaction-fees/#priority-fee

As a result, users are far overpaying for gas on the network when sending transactions populated natively within Metamask (or have to manually specify a lower priority fee).

### Expected behavior

The expected behavior is that the default priority fee should be a relatively low value on these app-rollups. Or the developer should be able to specify default gas settings in an add-to-Metamask button.

### Screenshots

Default gas suggestions:
<img width="258" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/47281632/e7f674b4-3988-47d7-9167-47551a24498b">

Manually specifying 0.01 gwei max priority fee in metamask sends a valid transaction:
<img width="646" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/47281632/86ab1b2e-9204-49c2-8236-f1480758b83a">

### Steps to reproduce

1. Add Manta Pacific via the add to metamask button here: https://pacific-info.manta.network/
2. Attempt to send a transaction (no funds are necessary for this step)
3. View the gas market settings
4. Inspect the default values for the 3 speeds on the gas market

### Version

11.0.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by jpuri** [comment] 2023-10-24 06:31
We need to check why the gas estimates are do high, but till then user can specify custom gas estimates using advanced option.

**Comment by seaona** [comment] 2023-10-24 09:46
Thanks for reporting @TheAppleTucker. What seems to be happening is that this specific network is not supported by the Metaswap API, and whenever this happens we don't get the `low`, `medium`, `high` values from the API call. In those cases, the priority fee values seem to be defaulting to `1`, `1.5` and `2` always, independently on the network conditions. 
This seems a general behaviour, not only for this network but for all. I've tried blocking the gas API for Mainnet and I see the same values for the priority fees, which are way higher than the recommended ones (the ones we would get if the gas API was enabled).

We now need to verify if this is the expected behaviour or if it needs a fix. It seems that the behaviour is not ideal as you are pointing out.

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/10557b39-8547-4a3c-9c19-5e9ee6649dba)

https://github.com/MetaMask/metamask-extension/assets/54408225/2ca3a16a-d789-460c-b5d9-382305fded27

**Comment by TheAppleTucker** [comment] 2023-10-26 19:50
Yeah, I think this makes sense. I think this happens in general with custom networks (ie. a local devnet)

**Comment by bschorchit** [comment] 2024-08-19 22:38
Hey there, closing as this was fixed in the recent releases (staring with v11.16). Let us know if encounter this or any other issue!

**Closed** 2024-08-19 22:38 UTC
Labels: type-bug, Sev2-normal, team-confirmations
