### ISSUE TITLE
ethereum.enable never returns when user closes login prompt. 

### ISSUE THREAD

**Issue by dwbauschlicher** [MetaMask/metamask-extension#5702] opened 2018-11-08 16:31 UTC
When a user has metamask installed but is not logged in, a call to ethereum.enable() will never return if they close the login prompt.

I expect the promise to return with an error or at least return with some notification of the user not allowing permission. 

This occurs even when privacy mode is off, which is weird because I would expect privacy mode off to just immediately return with success. I assume this is because ethereum.enable cannot tell if privacy mode is enabled if the user is not logged in?

Chrome
Metamask 5.0.1
Privacy mode off

**Comment by bitpshr** [comment] 2018-11-08 16:34
Hi @dwbauschlicher, thanks for taking the time to report this issue. This is a duplicate of #5700. Please see the [response on that issue](https://github.com/MetaMask/metamask-extension/issues/5700#issuecomment-437034583) and let us know if you have any additional questions

**Closed by bitpshr** 2018-11-08 16:34 UTC

**Comment by dwbauschlicher** [comment] 2018-11-08 18:38
How are dapps getting around this then? Setting a timeout? Is there an easy
way to check if the user is logged in or not in advance?

**Comment by bitpshr** [comment] 2018-11-08 18:41
Hi @dwbauschlicher. We expose non-standard methods to check if a dapp has a cached approval, if a dapp is currently enabled, and if MetaMask is unlocked. It should be noted these are not standardized across dapp browsers (yet) since some dapp browsers don't implement locking or caching at all. For more information, check out the thread on the pull request at #4703, starting around [here](https://github.com/MetaMask/metamask-extension/pull/4703#issuecomment-430814765).

**Comment by dwbauschlicher** [comment] 2018-11-09 17:07
Both ethereum.isUnlocked and ethereum.isEnabled are undefined. Calling
isUnlocked() and isEnabled() just throws errors. This is on version 5.0.1

**Comment by bitpshr** [comment] 2018-11-09 17:13
Hi @dwbauschlicher. The nonstandard convenience methods are exposed at `ethereum._metamask`:

```js
ethereum._metamask.isApproved()
ethereum._metamask.isEnabled()
ethereum._metamask.isUnlocked()
```

They are all asynchronous and return `Promise` objects.

**Comment by dwbauschlicher** [comment] 2018-11-09 17:17
Got it. I appreciate the quick response!

**Comment by dwbauschlicher** [comment] 2018-11-09 17:49
When I call ethereum.enable() I am still getting a popup to enable access
even if the account is unlocked  and privacy mode is off,. Is that the
expected behavior now? I read
https://github.com/MetaMask/metamask-extension/issues/5679 and it looks
like that use to not be the behavior?

**Comment by bitpshr** [comment] 2018-11-09 18:09
Hi @dwbauschlicher, this is intended behavior. You can see a detailed explanation of why this happens [here](https://github.com/MetaMask/metamask-extension/issues/5699#issuecomment-436967312).

**Comment by realisation** [comment] 2019-05-16 06:51
@bitpshr I don't get any behavior when I call ethereum.enable() even though the user is logged out of metamask - which I think means the account is unlocked? If so, I should expect metamask to pop up and request log in information, but nothing happens other than returning a promise resolved to the accounts array, accounts[0]

What am I missing here?

**Comment by realisation** [comment] 2019-05-16 06:54
Getting most specific, this is for a dapp which the user has already approved to use metamask. But, then after logging out of metamask or quitting chrome and therefore not being logged into metamask, I want to be able to prompt the user to log into metamask and go on to use the dapp.

**Comment by bitpshr** [comment] 2019-05-16 14:22
Hi @realisation. WHat you're describing may be related to a new bug reported at https://github.com/MetaMask/metamask-extension/issues/6618. Please subscribe to that issue for a fix. Thanks!
